/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Diagnostics.Quitting.Chronology.SourceMatchedChronologicalData
import UniformEquilibrium.Quitting.Cycles.BlockSurvival

/-!
# Survival of repeated source-matched root samples

A finite list of source-matched radial reset profiles can be sampled at
specified live times and repeated as an executable periodic root sequence.
If its one-period deleted-player Continue product is strictly below one for
every player, every deleted-player survival tail vanishes.  Joint survival
then vanishes by domination.

The strict contraction is a real producer hypothesis, not a consequence of a
favorable debt chord.  The final regression uses an existing literal
two-player quitting game: resetting the mover from sure Quit to `Never`
strictly decreases its semantic debt, while repetition of the reset endpoint
has zero opponent exposure and survival identically one.
-/

noncomputable section

namespace GameTheory

open Filter Math.Probability
open scoped Topology

variable {ι : Type} [Fintype ι] [DecidableEq ι]
variable {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
variable {witness : QuittingTerminalExploitabilityWitness reward}

namespace QuittingCounterexampleStoppingLawFrontier

/-- A finite cycle of complete product roots sampled from literal
source-matched radial reset profiles. -/
def sourceMatchedRadialSampledCycle
    (frontier : QuittingCounterexampleStoppingLawFrontier witness)
    {period : ℕ}
    (rank : ℕ) (weight : {who // who ∈ frontier.active} → ℝ)
    (hweight0 : ∀ mover, 0 ≤ weight mover)
    (hweight1 : ∀ mover, weight mover ≤ 1)
    (mover : Fin period → {who // who ∈ frontier.active})
    (sampleTime : Fin period → ℕ) (phase : Fin period) : ι → PMF Bool :=
  quittingProfileLiveRoot reward
    (frontier.sourceMatchedRadialResetProfile rank (mover phase)
      (weight (mover phase)) (hweight0 (mover phase))
      (hweight1 (mover phase))) (sampleTime phase)

/-- The periodic executable sequence generated by the sampled reset roots. -/
def sourceMatchedRadialRepeatedRoots
    (frontier : QuittingCounterexampleStoppingLawFrontier witness)
    {period : ℕ}
    (rank : ℕ) (weight : {who // who ∈ frontier.active} → ℝ)
    (hweight0 : ∀ mover, 0 ≤ weight mover)
    (hweight1 : ∀ mover, weight mover ≤ 1)
    (mover : Fin period → {who // who ∈ frontier.active})
    (sampleTime : Fin period → ℕ) (phase : Fin period) :
    ℕ → ι → PMF Bool :=
  quittingCyclicRootSequence
    (frontier.sourceMatchedRadialSampledCycle rank weight hweight0 hweight1
      mover sampleTime) phase

/-- Strict one-period deleted-player contraction makes every tail of the
repeated source-matched schedule vanish. -/
theorem sourceMatchedRadialRepeatedRoots_opponentSurvival
    (frontier : QuittingCounterexampleStoppingLawFrontier witness)
    {period : ℕ}
    (rank : ℕ) (weight : {who // who ∈ frontier.active} → ℝ)
    (hweight0 : ∀ mover, 0 ≤ weight mover)
    (hweight1 : ∀ mover, weight mover ≤ 1)
    (mover : Fin period → {who // who ∈ frontier.active})
    (sampleTime : Fin period → ℕ) (phase : Fin period)
    (hcontracts : ∀ who,
      (∏ cyclePhase : Fin period,
        quittingStationaryFixedOpponentsContinueMass
          (frontier.sourceMatchedRadialSampledCycle rank weight
            hweight0 hweight1 mover sampleTime cyclePhase) who) < 1)
    (who : ι) (start : ℕ) :
    Tendsto
      (Math.survivalProduct (fun time ↦
        quittingRootOpponentContinueMass
          (frontier.sourceMatchedRadialRepeatedRoots rank weight
            hweight0 hweight1 mover sampleTime phase time) who) start)
      atTop (nhds 0) := by
  let cycle := frontier.sourceMatchedRadialSampledCycle rank weight
    hweight0 hweight1 mover sampleTime
  let reachedPhase := quittingCyclicOrbit phase start
  have hzero := tendsto_zero_quittingOpponentSurvivalWeight_cyclicRootSequence
    cycle reachedPhase who (hcontracts who)
  have heq : ∀ fuel,
      quittingOpponentSurvivalWeight
          (frontier.sourceMatchedRadialRepeatedRoots rank weight
            hweight0 hweight1 mover sampleTime phase) who start fuel =
        quittingOpponentSurvivalWeight
          (quittingCyclicRootSequence cycle reachedPhase) who 0 fuel := by
    intro fuel
    change quittingOpponentSurvivalWeight
        (quittingCyclicRootSequence cycle phase) who start fuel = _
    rw [quittingOpponentSurvivalWeight_cyclicRootSequence,
      quittingOpponentSurvivalWeight_cyclicRootSequence]
    simp only [quittingCyclicOrbit_zero, reachedPhase, cycle]
  apply hzero.congr'
  filter_upwards [] with fuel
  rw [← heq fuel]
  rfl

/-- The same contraction hypothesis also kills joint survival on every tail.
-/
theorem sourceMatchedRadialRepeatedRoots_jointSurvival
    (frontier : QuittingCounterexampleStoppingLawFrontier witness)
    {period : ℕ} (hperiod : 0 < period)
    (rank : ℕ) (weight : {who // who ∈ frontier.active} → ℝ)
    (hweight0 : ∀ mover, 0 ≤ weight mover)
    (hweight1 : ∀ mover, weight mover ≤ 1)
    (mover : Fin period → {who // who ∈ frontier.active})
    (sampleTime : Fin period → ℕ) (phase : Fin period)
    (hcontracts : ∀ who,
      (∏ cyclePhase : Fin period,
        quittingStationaryFixedOpponentsContinueMass
          (frontier.sourceMatchedRadialSampledCycle rank weight
            hweight0 hweight1 mover sampleTime cyclePhase) who) < 1)
    (start : ℕ) :
    Tendsto
      (Math.survivalProduct (fun time ↦
        quittingStationaryContinueMass
          (frontier.sourceMatchedRadialRepeatedRoots rank weight
            hweight0 hweight1 mover sampleTime phase time)) start)
      atTop (nhds 0) := by
  let player : ι := (mover ⟨0, hperiod⟩).1
  apply Math.tendsto_survivalProduct_zero_of_le
    (fun time ↦ quittingStationaryContinueMass
      (frontier.sourceMatchedRadialRepeatedRoots rank weight
        hweight0 hweight1 mover sampleTime phase time))
    (fun time ↦ quittingRootOpponentContinueMass
      (frontier.sourceMatchedRadialRepeatedRoots rank weight
        hweight0 hweight1 mover sampleTime phase time) player)
    start
  · intro time
    exact quittingStationaryContinueMass_nonneg _
  · intro time
    exact quittingStationaryContinueMass_le_fixedOpponentsContinueMass _ player
  · exact frontier.sourceMatchedRadialRepeatedRoots_opponentSurvival
      rank weight hweight0 hweight1 mover sampleTime phase hcontracts
      player start

end QuittingCounterexampleStoppingLawFrontier

end GameTheory
