/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.AnchoredCyclicRenewal
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.AnchoredCyclicScreen
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.AtomicBlockerCompletion
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.AtomicOwner
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Ballisticity
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.BoundedSelfResetLocalization
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Capacity.AggregatePrefixConsumption
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Capacity.NearMaximizerRebase
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Capacity.ReachableCarryTelescope
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Capacity.StatePreservingChronology
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Capacity.TerminalIncomingPathAlternative
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Circulant.ColliderClosure
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Circulant.ColliderCompletion
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Circulant.ConstantStepCycle
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Circulant.Trichotomy
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Circulant.TrichotomyClosure
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.CollisionRepairScreen
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Conditioned.Diffuse.Closure
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Conditioned.Diffuse.FixedOutsider
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Conditioned.Diffuse.FloorClip
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Conditioned.Diffuse.Reset
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Conditioned.FloorViability
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Conditioned.NegativeTangent
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Conditioned.SlackThreshold
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Debt.BoundaryProvenanceAlternative
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Debt.CapCarrier
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Debt.Conservation
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Debt.DynamicLimit
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Debt.KilledCapacityPotential
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Debt.KilledTailPotential
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Debt.OneStageObstructionCarrier
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Debt.Quantitative
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Debt.Source.DynamicAlternative
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Debt.Source.ObstructionCarrier
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Debt.Source.StrategicDecoder
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Debt.TailBridge
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Debt.ViolationCollapse
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.DiffuseTailSoloStructure
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.EventualAllContinuePlateau
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.ExactCycleStrata
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.ExistenceBranches
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.ImmediateSingletonCollision
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.MarkedAtomBudgetPrefixes
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Orbit.Limit
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Orbit.SelfLoop
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Packet.Defect
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Packet.Energy
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Packet.Support
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Packet.Surplus
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Packet
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.PeriodOne.AttachmentRepair
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.PeriodOne.TangentReadout
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.PeriodicBlockProfile
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.PeriodicWindows
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.PreemptionCycle
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.PreemptionGeometry
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.PreemptionTransport
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Players.DebtTransferCardinality
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Players.ReindexNaturality
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Players.SmallPlayers
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Players.ThreeRoleSpectator
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Seam
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.SearchConsequences
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.SolanVieilleBoundary
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.SoloExitPreferenceScreen
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.Atom.ContinuePrefixAccess
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.Atom.ExactPrefixChronology
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.DynamicDebtSemanticChronology
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.Frontier
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.NegativeTargetAtomicDispatch
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.ObserverAbsent.DefectPolarityDispatch
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.ObserverAbsent.ForcedOwnerDispatch
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.ObserverAbsent.RectangleBaselineDispatch
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.OffDiagonal.ActiveTransferCycle
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.OffDiagonal.AtomSequenceDispatch
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.OffDiagonal.EndpointReturn
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.OffDiagonal.SlopeFrontier
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.OffDiagonal.StaticOrientationDispatch
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.ReachedRowDebtLocalization
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.SourceMatchedChattering
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.SourceMatchedRadialResetCube
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.SourceMatchedRadialScaling
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.SourceMatchedResetCube
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Tangent.CollisionAwareFiniteReturn
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Tangent.Packet
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.TargetTailGluingObstruction
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.TerminalFunding.FarkasDecoder
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Toggles.FiniteInstability
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Toggles.StrictOrbit
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.Toggles

/-!
# Counterexample-regime diagnostics inventory

Import-only inventory of the quantitative counterexample-regime pipeline.
Every extension in this subtree materially consumes a selected
`QuittingCounterexampleRegime`, its frontier, or a provenance-preserving object
derived from it.  Reusable mathematical and game-semantic owners live outside
this subtree.

Ordinary consumers should import the narrow module that owns the declarations
they use.
-/
