import UniformEquilibrium.Quitting.Cycles.ConstantRootSurvival
import UniformEquilibrium.Quitting.Punishment.SoloCycleCompletion
import UniformEquilibrium.Quitting.Punishment.SoloQuitterEquilibrium
import UniformEquilibrium.Quitting.Terminal.TailCompression.ElementaryCaps
import UniformEquilibrium.Quitting.Stationary.CompleteBehavioralCap

/-!
# One actual punishment row before every solo-prefix length

The target is v = reward({owner}), not each outsider's own singleton.
One stationary punishment row is obtained from the actual minmax BEFORE K.
The generated profile plays exactly K solo rows, then this same continuation.
Delivery uses joint survival; outsider full-response comparisons use deleted
survival. The coupled owner estimate retains its signed singleton anchor.
-/

noncomputable section

namespace GameTheory

open scoped BigOperators

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- Exactly K literal solo rows followed by the selected actual punishment row. -/
def quittingSoloPunishmentPrefixRoots (owner : ι) (hazard : PMF Bool)
    (punishment : ι → PMF Bool) (length : ℕ) : ℕ → ι → PMF Bool :=
  quittingPhaseSwitchRoots (fun _ => quittingSoloStationaryRoot owner hazard)
    (fun _ => punishment) length

/-- The actual unrestricted behavioral profile generated by that word. -/
def quittingSoloPunishmentPrefixProfile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (owner : ι) (hazard : PMF Bool) (punishment : ι → PMF Bool) (length : ℕ) :
    (quittingGame reward).BehaviorProfile :=
  quittingRootSequenceProfile reward
    (quittingSoloPunishmentPrefixRoots owner hazard punishment length) 0

/-- Every pre-cutoff live root is the original solo row, including all its marginals. -/
theorem quittingSoloPunishmentPrefixProfile_liveRoot_before
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (owner : ι) (hazard : PMF Bool) (punishment : ι → PMF Bool)
    {length time : ℕ} (htime : time < length) :
    quittingProfileLiveRoot reward
        (quittingSoloPunishmentPrefixProfile reward owner hazard punishment length) time =
      quittingSoloStationaryRoot owner hazard := by
  unfold quittingSoloPunishmentPrefixProfile
  rw [quittingProfileLiveRoot_quittingRootSequenceProfile_zero]
  exact quittingPhaseSwitchRoots_of_lt _ _ htime

/-- The same actual continuation begins at K, not at K+1. -/
theorem quittingSoloPunishmentPrefixProfile_liveRoot_after
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (owner : ι) (hazard : PMF Bool) (punishment : ι → PMF Bool) (length offset : ℕ) :
    quittingProfileLiveRoot reward
        (quittingSoloPunishmentPrefixProfile reward owner hazard punishment length)
          (length + offset) = punishment := by
  unfold quittingSoloPunishmentPrefixProfile
  rw [quittingProfileLiveRoot_quittingRootSequenceProfile_zero]
  exact quittingPhaseSwitchRoots_add _ _ length offset

private theorem solo_root_sequence_value
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (owner who : ι) (hazard : PMF Bool) (hpositive : 0 < (hazard true).toReal) :
    quittingRootSequenceTerminalValue reward
        (fun _ => quittingSoloStationaryRoot owner hazard) who 0 =
      quittingSoloReward reward owner who := by
  have hvalue := quittingTerminalPayoff_soloStationary reward owner who hazard hpositive
  rw [quittingTerminalPayoff_eq_rootSequence_profileLiveRoot,
    quittingProfileLiveRoot_stationary] at hvalue
  exact hvalue

private theorem solo_other_original_cap_le
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (owner other : ι) (hazard : PMF Bool) (hpositive : 0 < (hazard true).toReal)
    (hother : other ≠ owner)
    (hnash : IsεQuittingRootEndpointNash reward (quittingSoloReward reward owner) 0
      (quittingSoloStationaryRoot owner hazard)) :
    quittingRootSequenceBestResponseValue reward
        (fun _ => quittingSoloStationaryRoot owner hazard) other ≤
      quittingSoloReward reward owner other := by
  change quittingContinuationBestResponseValue reward
      (quittingStationaryProfile reward (quittingSoloStationaryRoot owner hazard)) other ≤ _
  rw [quittingContinuationBestResponseValue_stationary_eq_fullRateUnilateralCap,
    quittingStationaryFullRateUnilateralCap_of_lt _ _ _
      (quittingStationaryFixedOpponentsContinueMass_solo_other_lt_one hother hazard hpositive),
    quittingStationaryUnilateralCap_solo_other reward hother hazard hpositive,
    quittingStationaryFixedOpponentsQuitValue_solo_other_eq_mix reward hother hazard]
  exact max_le
    ((isεQuittingRootEndpointNash_soloStationaryRoot_iff reward owner hazard).mp
      hnash other hother) le_rfl

private theorem solo_prefix_owner_cap_le
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (owner : ι) (hazard : PMF Bool) (punishment : ι → PMF Bool) (length : ℕ)
    (error : ℝ) (herror : 0 ≤ error)
    (hpunishment : quittingStationaryUnilateralCap reward punishment owner ≤
      quittingSoloReward reward owner owner + error) :
    quittingRootSequenceBestResponseValue reward
        (quittingSoloPunishmentPrefixRoots owner hazard punishment length) owner ≤
      quittingSoloReward reward owner owner + error := by
  let plan := fun _ : ℕ => quittingSoloStationaryRoot owner hazard
  let punish := fun _ : ℕ => punishment
  have hprefix (reply : ℕ → PMF Bool) :
      quittingRootSequenceHazardTerminalValue reward
          (quittingTruncatedRoots plan length) owner
          (quittingTruncatedHazard reply length) 0 ≤
        (1 - quittingJointSurvivalWeight
          (quittingRootSequenceUpdate plan owner reply) 0 length) *
            quittingSoloReward reward owner owner + 0 := by
    rw [add_zero, quittingSoloReward_self]
    exact le_of_eq
      (quittingRootSequenceHazardTerminalValue_truncated_eq_one_sub_survival_mul_of_isolated
        reward plan owner reply length (fun _ _ other hother =>
          quittingSoloStationaryRoot_apply_other hother hazard))
  have htail (reply : ℕ → PMF Bool) :
      quittingRootSequenceHazardTerminalValue reward punish owner reply 0 ≤
        quittingSoloReward reward owner owner + error :=
    (quittingRootSequenceHazardTerminalValue_const_le_cap
      reward punishment owner reply).trans hpunishment
  unfold quittingRootSequenceBestResponseValue quittingContinuationBestResponseValue
  apply csSup_le
  · exact ⟨_, ⟨(quittingRootSequenceProfile reward
      (quittingSoloPunishmentPrefixRoots owner hazard punishment length) 0) owner, rfl⟩⟩
  · rintro _ ⟨deviation, rfl⟩
    change quittingTerminalPayoff reward
        (Function.update (quittingPhaseSwitchProfile reward plan punish length)
          owner deviation) owner ≤ _
    simpa only [add_zero] using
      quittingTerminalPayoff_update_quittingPhaseSwitchProfile_le_coupled reward
        plan punish length owner herror hprefix htail deviation

/-- The actual minmax source selects ONE row before every prefix length.
All caps are suprema over complete behavioral replacements of the actual profile. -/
theorem exists_soloPunishmentPrefix_estimates_of_punishmentIR
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (owner : ι) (hazard : PMF Bool) (hpositive : 0 < (hazard true).toReal)
    (hnash : IsεQuittingRootEndpointNash reward (quittingSoloReward reward owner) 0
      (quittingSoloStationaryRoot owner hazard))
    (hIR : quittingPunishmentValue reward owner ≤ quittingSoloReward reward owner owner)
    (bound : ℝ) (hreward : ∀ terminal who, |reward terminal who| ≤ bound)
    (error : ℝ) (herror : 0 < error) :
    ∃ punishment : ι → PMF Bool,
      punishment owner = PMF.pure false ∧
      quittingStationaryUnilateralCap reward punishment owner ≤
        quittingSoloReward reward owner owner + error ∧
      ∀ length : ℕ,
        (∀ who,
          |quittingTerminalPayoff reward
              (quittingSoloPunishmentPrefixProfile reward owner hazard punishment length) who -
            quittingSoloReward reward owner who| ≤
          2 * bound * (1 - (hazard true).toReal) ^ length) ∧
        quittingRootSequenceBestResponseValue reward
            (quittingSoloPunishmentPrefixRoots owner hazard punishment length) owner ≤
          quittingSoloReward reward owner owner + error ∧
        (∀ other, other ≠ owner →
          quittingRootSequenceBestResponseValue reward
              (quittingSoloPunishmentPrefixRoots owner hazard punishment length) other ≤
            quittingSoloReward reward owner other +
              2 * bound * (1 - (hazard true).toReal) ^ length) ∧
        quittingRootSequenceBestResponseValue reward
            (quittingSoloPunishmentPrefixRoots owner hazard punishment length) owner -
          quittingTerminalPayoff reward
            (quittingSoloPunishmentPrefixProfile reward owner hazard punishment length) owner ≤
          error + 2 * bound * (1 - (hazard true).toReal) ^ length ∧
        (∀ other, other ≠ owner →
          quittingRootSequenceBestResponseValue reward
              (quittingSoloPunishmentPrefixRoots owner hazard punishment length) other -
            quittingTerminalPayoff reward
              (quittingSoloPunishmentPrefixProfile reward owner hazard punishment length) other ≤
            4 * bound * (1 - (hazard true).toReal) ^ length) := by
  obtain ⟨selected, hselected⟩ := exists_quittingStationaryPunishmentRoot_lt_add reward owner herror
  let punishment := Function.update selected owner (PMF.pure false)
  have hcap : quittingStationaryUnilateralCap reward punishment owner ≤
      quittingSoloReward reward owner owner + error := by
    have hequal := quittingStationaryUnilateralCap_congr_of_opponents reward owner
      (first := punishment) (second := selected)
      (fun player hplayer => Function.update_of_ne hplayer _ _)
    rw [hequal]
    linarith
  refine ⟨punishment, Function.update_self _ _ _, hcap, ?_⟩
  have hcontinue : (hazard false).toReal = 1 - (hazard true).toReal := by
    linarith [quittingSoloHazardMass_add hazard]
  intro length
  let original := fun _ : ℕ => quittingSoloStationaryRoot owner hazard
  let switched := quittingSoloPunishmentPrefixRoots owner hazard punishment length
  have hprefix : ∀ time, time < length → switched time = original time :=
    fun _ htime => quittingPhaseSwitchRoots_of_lt _ _ htime
  have hjoint : quittingJointSurvivalWeight original 0 length =
      (1 - (hazard true).toReal) ^ length := by
    dsimp only [original]
    rw [quittingJointSurvivalWeight_const, quittingStationaryContinueMass_solo, hcontinue]
  have hdelivery (who : ι) :
      |quittingTerminalPayoff reward
          (quittingSoloPunishmentPrefixProfile reward owner hazard punishment length) who -
        quittingSoloReward reward owner who| ≤
      2 * bound * (1 - (hazard true).toReal) ^ length := by
    have hclose := abs_quittingRootSequenceTerminalValue_sub_le_of_prefix_eq
      reward switched original who length hreward hprefix
    dsimp only [original] at hclose
    rw [solo_root_sequence_value reward owner who hazard hpositive, hjoint] at hclose
    unfold quittingSoloPunishmentPrefixProfile
    rw [quittingTerminalPayoff_eq_rootSequence_profileLiveRoot,
      quittingProfileLiveRoot_quittingRootSequenceProfile_zero]
    exact hclose
  have howner := solo_prefix_owner_cap_le reward owner hazard punishment length
    error herror.le hcap
  have hother (other : ι) (hne : other ≠ owner) :
      quittingRootSequenceBestResponseValue reward switched other ≤
        quittingSoloReward reward owner other +
          2 * bound * (1 - (hazard true).toReal) ^ length := by
    have hclose := abs_quittingRootSequenceBestResponseValue_sub_le_of_prefix_eq
      reward switched original other length hreward hprefix
    have hclock := quittingOpponentSurvivalWeight_const_le_pow_continue
      (quittingSoloStationaryRoot owner hazard) other owner (Ne.symm hne) length
    rw [quittingSoloStationaryRoot_apply_owner, hcontinue] at hclock
    have hbound := quittingRewardCoordinateBound_nonneg_of_player reward owner hreward
    have hscaled := mul_le_mul_of_nonneg_left hclock (by positivity : 0 ≤ 2 * bound)
    have hbase := solo_other_original_cap_le reward owner other hazard hpositive hne hnash
    dsimp only [original] at hclose
    linarith [(abs_le.mp hclose).2]
  refine ⟨hdelivery, howner, hother, ?_, ?_⟩
  · linarith [(abs_le.mp (hdelivery owner)).1]
  · intro other hne
    have hdouble :
        2 * bound * (1 - (hazard true).toReal) ^ length +
          2 * bound * (1 - (hazard true).toReal) ^ length =
        4 * bound * (1 - (hazard true).toReal) ^ length := by ring
    linarith [hother other hne, (abs_le.mp (hdelivery other)).1]

/-- A nonnegative owner needs no supplied minmax witness: actual all-Continue
opponents already give its individual-rationality inequality. -/
theorem exists_soloPunishmentPrefix_estimates_of_nonnegative_owner
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (owner : ι) (hazard : PMF Bool) (hpositive : 0 < (hazard true).toReal)
    (hnash : IsεQuittingRootEndpointNash reward (quittingSoloReward reward owner) 0
      (quittingSoloStationaryRoot owner hazard))
    (howner : 0 ≤ quittingSoloReward reward owner owner)
    (bound : ℝ) (hreward : ∀ terminal who, |reward terminal who| ≤ bound)
    (error : ℝ) (herror : 0 < error) :
    ∃ punishment : ι → PMF Bool,
      punishment owner = PMF.pure false ∧
      quittingStationaryUnilateralCap reward punishment owner ≤
        quittingSoloReward reward owner owner + error ∧
      ∀ length : ℕ,
        (∀ who,
          |quittingTerminalPayoff reward
              (quittingSoloPunishmentPrefixProfile reward owner hazard punishment length) who -
            quittingSoloReward reward owner who| ≤
          2 * bound * (1 - (hazard true).toReal) ^ length) ∧
        quittingRootSequenceBestResponseValue reward
            (quittingSoloPunishmentPrefixRoots owner hazard punishment length) owner ≤
          quittingSoloReward reward owner owner + error ∧
        (∀ other, other ≠ owner →
          quittingRootSequenceBestResponseValue reward
              (quittingSoloPunishmentPrefixRoots owner hazard punishment length) other ≤
            quittingSoloReward reward owner other +
              2 * bound * (1 - (hazard true).toReal) ^ length) ∧
        quittingRootSequenceBestResponseValue reward
            (quittingSoloPunishmentPrefixRoots owner hazard punishment length) owner -
          quittingTerminalPayoff reward
            (quittingSoloPunishmentPrefixProfile reward owner hazard punishment length) owner ≤
          error + 2 * bound * (1 - (hazard true).toReal) ^ length ∧
        (∀ other, other ≠ owner →
          quittingRootSequenceBestResponseValue reward
              (quittingSoloPunishmentPrefixRoots owner hazard punishment length) other -
            quittingTerminalPayoff reward
              (quittingSoloPunishmentPrefixProfile reward owner hazard punishment length) other ≤
            4 * bound * (1 - (hazard true).toReal) ^ length) := by
  have hIR := quittingPunishmentValue_le_max_solo reward owner
  rw [QuittingSureSetOwnerRepair.quittingSetReward_of_nonempty reward
    (Finset.singleton_nonempty owner) owner] at hIR
  change quittingPunishmentValue reward owner ≤ max (quittingSoloReward reward owner owner) 0
    at hIR
  rw [max_eq_left howner] at hIR
  exact exists_soloPunishmentPrefix_estimates_of_punishmentIR reward owner hazard
    hpositive hnash hIR bound hreward error herror

end GameTheory
