/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.Debt.Dynamic.FiniteDynamicDebtPositiveLimit

/-!
# Buffered one-seam return or exit

This is the exact compactness core isolated by the cycle-geometry audit.
A finite cell assignment represents a cover whose cells have diameter below
`tolerance` inside a chosen buffer.  Seriality constructs an exact relation
orbit.  Within at most the number of cells, either two downstream buffered
states share a cell (hence give one small closing seam), or the exact orbit
leaves the buffer.

The theorem deliberately does not claim return to the initial state, retain a
game-theoretic terminal anchor, identify the ranking with optimized debt, or
decode an exit as a debt-decreasing splice.  Those are the missing strategic
interfaces, not consequences of compactness.
-/


noncomputable section

namespace GameTheory

variable {Point Cell : Type*}

/-- **Supplied-path finite-cover fork.**  The theorem preserves a supplied
exact orbit rather than selecting an arbitrary successor.  This is the form
needed for calibrated plateau paths: the topology only chooses two downstream
indices or detects a buffer exit. -/
theorem exactPrefix_downstream_close_or_exit
    [PseudoMetricSpace Point] [Fintype Cell]
    (relation : Point → Point → Prop) (path : ℕ → Point)
    (exact : ∀ time, relation (path time) (path (time + 1)))
    (buffer : Set Point) (cell : Point → Cell) (tolerance : ℝ)
    (cell_close : ∀ point₁, point₁ ∈ buffer →
      ∀ point₂, point₂ ∈ buffer →
        cell point₁ = cell point₂ → dist point₁ point₂ < tolerance) :
    (∀ time : Fin (Fintype.card Cell),
      relation (path time) (path (time + 1))) ∧
      (((∀ time : Fin (Fintype.card Cell + 1), path time ∈ buffer) ∧
          ∃ first last : Fin (Fintype.card Cell + 1),
            first < last ∧ dist (path first) (path last) < tolerance) ∨
        ∃ time : Fin (Fintype.card Cell + 1), path time ∉ buffer) := by
  constructor
  · intro time
    exact exact time
  · by_cases exit : ∃ time : Fin (Fintype.card Cell + 1),
        path time ∉ buffer
    · exact Or.inr exit
    · left
      have path_mem : ∀ time : Fin (Fintype.card Cell + 1),
          path time ∈ buffer := by
        intro time
        exact not_not.mp (fun hnot ↦ exit ⟨time, hnot⟩)
      refine ⟨path_mem, ?_⟩
      have hcard : Fintype.card Cell <
          Fintype.card (Fin (Fintype.card Cell + 1)) := by simp
      obtain ⟨first, last, hne, hsame⟩ :=
        Fintype.exists_ne_map_eq_of_card_lt
          (fun time : Fin (Fintype.card Cell + 1) ↦ cell (path time)) hcard
      rcases lt_or_gt_of_ne hne with hlt | hgt
      · exact ⟨first, last, hlt,
          cell_close (path first) (path_mem first) (path last)
            (path_mem last) hsame⟩
      · exact ⟨last, first, hgt,
          cell_close (path last) (path_mem last) (path first)
            (path_mem first) hsame.symm⟩

/-- An arbitrary chosen successor for a serial relation. -/
def serialSuccessor (relation : Point → Point → Prop)
    (serial : ∀ point, ∃ next, relation point next) (point : Point) : Point :=
  Classical.choose (serial point)

/-- The chosen successor is related to its current point. -/
theorem serialSuccessor_related
    (relation : Point → Point → Prop)
    (serial : ∀ point, ∃ next, relation point next) (point : Point) :
    relation point (serialSuccessor relation serial point) :=
  Classical.choose_spec (serial point)

/-- The exact orbit generated by repeatedly choosing a related successor. -/
def serialOrbit (relation : Point → Point → Prop)
    (serial : ∀ point, ∃ next, relation point next)
    (entry : Point) : ℕ → Point
  | 0 => entry
  | time + 1 => serialSuccessor relation serial
      (serialOrbit relation serial entry time)

@[simp] theorem serialOrbit_zero
    (relation : Point → Point → Prop)
    (serial : ∀ point, ∃ next, relation point next) (entry : Point) :
    serialOrbit relation serial entry 0 = entry := rfl

theorem serialOrbit_related
    (relation : Point → Point → Prop)
    (serial : ∀ point, ∃ next, relation point next)
    (entry : Point) (time : ℕ) :
    relation (serialOrbit relation serial entry time)
      (serialOrbit relation serial entry (time + 1)) := by
  rw [serialOrbit]
  exact serialSuccessor_related relation serial _

/-- **Finite-cover one-seam return or exit.**  A serial exact orbit of length
at most the number of cover cells either leaves the buffer or contains two
ordered downstream states in one cell. -/
theorem exists_exactPath_downstream_close_or_exit
    [PseudoMetricSpace Point] [Fintype Cell]
    (relation : Point → Point → Prop)
    (serial : ∀ point, ∃ next, relation point next)
    (buffer : Set Point) (cell : Point → Cell) (tolerance : ℝ)
    (cell_close : ∀ point₁, point₁ ∈ buffer →
      ∀ point₂, point₂ ∈ buffer →
        cell point₁ = cell point₂ → dist point₁ point₂ < tolerance)
    (entry : Point) :
    ∃ path : Fin (Fintype.card Cell + 1) → Point,
      path 0 = entry ∧
      (∀ time : Fin (Fintype.card Cell),
        relation (path time.castSucc) (path time.succ)) ∧
      ((∃ first last : Fin (Fintype.card Cell + 1),
          first < last ∧ path first ∈ buffer ∧ path last ∈ buffer ∧
            dist (path first) (path last) < tolerance) ∨
        ∃ time : Fin (Fintype.card Cell + 1), path time ∉ buffer) := by
  let orbit := serialOrbit relation serial entry
  let path : Fin (Fintype.card Cell + 1) → Point := fun time ↦ orbit time
  refine ⟨path, rfl, ?_, ?_⟩
  · intro time
    exact serialOrbit_related relation serial entry time
  · by_cases exit : ∃ time, path time ∉ buffer
    · exact Or.inr exit
    · left
      have path_mem : ∀ time, path time ∈ buffer := by
        intro time
        exact not_not.mp (fun hnot ↦ exit ⟨time, hnot⟩)
      have hcard : Fintype.card Cell <
          Fintype.card (Fin (Fintype.card Cell + 1)) := by simp
      obtain ⟨first, last, hne, hsame⟩ :=
        Fintype.exists_ne_map_eq_of_card_lt
          (fun time : Fin (Fintype.card Cell + 1) ↦ cell (path time)) hcard
      rcases lt_or_gt_of_ne hne with hlt | hgt
      · exact ⟨first, last, hlt, path_mem first, path_mem last,
          cell_close (path first) (path_mem first) (path last)
            (path_mem last) hsame⟩
      · exact ⟨last, first, hgt, path_mem last, path_mem first,
          cell_close (path last) (path_mem last) (path first)
            (path_mem first) hsame.symm⟩

/-- **Buffered ranking form.**  Starting above level `high`, the same finite
exact path either has a downstream one-seam pair inside `{rank ≥ low}`, or
reaches a point whose rank is lower than the entry rank by more than
`high - low`. -/
theorem exists_exactPath_close_or_rank_exit
    [PseudoMetricSpace Point] [Fintype Cell]
    (relation : Point → Point → Prop)
    (serial : ∀ point, ∃ next, relation point next)
    (rank : Point → ℝ) (high low : ℝ) (cell : Point → Cell)
    (tolerance : ℝ)
    (cell_close : ∀ point₁, low ≤ rank point₁ →
      ∀ point₂, low ≤ rank point₂ →
        cell point₁ = cell point₂ → dist point₁ point₂ < tolerance)
    (entry : Point) (entry_high : high ≤ rank entry) :
    ∃ path : Fin (Fintype.card Cell + 1) → Point,
      path 0 = entry ∧
      (∀ time : Fin (Fintype.card Cell),
        relation (path time.castSucc) (path time.succ)) ∧
      ((∃ first last : Fin (Fintype.card Cell + 1),
          first < last ∧ low ≤ rank (path first) ∧
            low ≤ rank (path last) ∧
            dist (path first) (path last) < tolerance) ∨
        ∃ time : Fin (Fintype.card Cell + 1),
          rank entry - rank (path time) > high - low) := by
  let buffer : Set Point := {point | low ≤ rank point}
  obtain ⟨path, hentry, hpath, hclose | hexit⟩ :=
    exists_exactPath_downstream_close_or_exit
      relation serial buffer cell tolerance
      (fun point₁ hpoint₁ point₂ hpoint₂ hsame ↦
        cell_close point₁ hpoint₁ point₂ hpoint₂ hsame)
      entry
  · refine ⟨path, hentry, hpath, Or.inl ?_⟩
    rcases hclose with ⟨first, last, hlt, hfirst, hlast, hdist⟩
    exact ⟨first, last, hlt, hfirst, hlast, hdist⟩
  · refine ⟨path, hentry, hpath, Or.inr ?_⟩
    rcases hexit with ⟨time, htime⟩
    refine ⟨time, ?_⟩
    have hrank : rank (path time) < low := lt_of_not_ge htime
    linarith

/-! ## Local seriality inside the buffer -/

/-- Choose a related successor while inside the buffer; outside, freeze the
path because only the first exit is relevant. -/
def bufferedSuccessor (relation : Point → Point → Prop) (buffer : Set Point)
    (serial : ∀ point, point ∈ buffer → ∃ next, relation point next)
    (point : Point) : Point :=
  Classical.choose (show ∃ next, point ∈ buffer → relation point next by
    classical
    by_cases hpoint : point ∈ buffer
    · obtain ⟨next, hnext⟩ := serial point hpoint
      exact ⟨next, fun _ ↦ hnext⟩
    · exact ⟨point, fun hmem ↦ False.elim (hpoint hmem)⟩)

/-- The buffered successor is an exact relation step whenever its current
point remains in the buffer. -/
theorem bufferedSuccessor_related
    (relation : Point → Point → Prop) (buffer : Set Point)
    (serial : ∀ point, point ∈ buffer → ∃ next, relation point next)
    (point : Point) (hpoint : point ∈ buffer) :
    relation point (bufferedSuccessor relation buffer serial point) := by
  exact (Classical.choose_spec (show
    ∃ next, point ∈ buffer → relation point next by
      classical
      by_cases hmem : point ∈ buffer
      · obtain ⟨next, hnext⟩ := serial point hmem
        exact ⟨next, fun _ ↦ hnext⟩
      · exact ⟨point, fun hcontra ↦ False.elim (hmem hcontra)⟩)) hpoint

/-- Iterate the locally serial relation until it exits the buffer, then keep
the irrelevant suffix constant. -/
def bufferedOrbit (relation : Point → Point → Prop) (buffer : Set Point)
    (serial : ∀ point, point ∈ buffer → ∃ next, relation point next)
    (entry : Point) : ℕ → Point
  | 0 => entry
  | time + 1 => bufferedSuccessor relation buffer serial
      (bufferedOrbit relation buffer serial entry time)

@[simp] theorem bufferedOrbit_zero
    (relation : Point → Point → Prop) (buffer : Set Point)
    (serial : ∀ point, point ∈ buffer → ∃ next, relation point next)
    (entry : Point) :
    bufferedOrbit relation buffer serial entry 0 = entry := rfl

/-- Every buffered-orbit step whose source remains buffered is exact. -/
theorem bufferedOrbit_related
    (relation : Point → Point → Prop) (buffer : Set Point)
    (serial : ∀ point, point ∈ buffer → ∃ next, relation point next)
    (entry : Point) (time : ℕ)
    (hmem : bufferedOrbit relation buffer serial entry time ∈ buffer) :
    relation (bufferedOrbit relation buffer serial entry time)
      (bufferedOrbit relation buffer serial entry (time + 1)) := by
  rw [bufferedOrbit]
  exact bufferedSuccessor_related relation buffer serial _ hmem

/-- **Buffered one-seam return or exit under local seriality.**  Only points
inside the buffer need a related successor.  The close branch keeps the whole
finite orbit inside and hence every transition is exact; the exit branch
retains exactness at every still-buffered source. -/
theorem exists_bufferedPath_downstream_close_or_exit
    [PseudoMetricSpace Point] [Fintype Cell]
    (relation : Point → Point → Prop) (buffer : Set Point)
    (serial : ∀ point, point ∈ buffer → ∃ next, relation point next)
    (cell : Point → Cell) (tolerance : ℝ)
    (cell_close : ∀ point₁, point₁ ∈ buffer →
      ∀ point₂, point₂ ∈ buffer →
        cell point₁ = cell point₂ → dist point₁ point₂ < tolerance)
    (entry : Point) :
    ∃ path : Fin (Fintype.card Cell + 1) → Point,
      path 0 = entry ∧
      (∀ time : Fin (Fintype.card Cell), path time.castSucc ∈ buffer →
        relation (path time.castSucc) (path time.succ)) ∧
      (((∀ time, path time ∈ buffer) ∧
          ∃ first last : Fin (Fintype.card Cell + 1),
            first < last ∧ dist (path first) (path last) < tolerance) ∨
        ∃ time : Fin (Fintype.card Cell + 1), path time ∉ buffer) := by
  let orbit := bufferedOrbit relation buffer serial entry
  let path : Fin (Fintype.card Cell + 1) → Point := fun time ↦ orbit time
  refine ⟨path, rfl, ?_, ?_⟩
  · intro time hmem
    exact bufferedOrbit_related relation buffer serial entry time hmem
  · by_cases exit : ∃ time, path time ∉ buffer
    · exact Or.inr exit
    · left
      have path_mem : ∀ time, path time ∈ buffer := by
        intro time
        exact not_not.mp (fun hnot ↦ exit ⟨time, hnot⟩)
      refine ⟨path_mem, ?_⟩
      have hcard : Fintype.card Cell <
          Fintype.card (Fin (Fintype.card Cell + 1)) := by simp
      obtain ⟨first, last, hne, hsame⟩ :=
        Fintype.exists_ne_map_eq_of_card_lt
          (fun time : Fin (Fintype.card Cell + 1) ↦ cell (path time)) hcard
      rcases lt_or_gt_of_ne hne with hlt | hgt
      · exact ⟨first, last, hlt,
          cell_close (path first) (path_mem first) (path last)
            (path_mem last) hsame⟩
      · exact ⟨last, first, hgt,
          cell_close (path last) (path_mem last) (path first)
            (path_mem first) hsame.symm⟩

/-- Local-serial buffered theorem with a quantitative ranking exit. -/
theorem exists_bufferedPath_close_or_rank_exit
    [PseudoMetricSpace Point] [Fintype Cell]
    (relation : Point → Point → Prop) (rank : Point → ℝ)
    (high low : ℝ)
    (serial : ∀ point, low ≤ rank point → ∃ next, relation point next)
    (cell : Point → Cell) (tolerance : ℝ)
    (cell_close : ∀ point₁, low ≤ rank point₁ →
      ∀ point₂, low ≤ rank point₂ →
        cell point₁ = cell point₂ → dist point₁ point₂ < tolerance)
    (entry : Point) (entry_high : high ≤ rank entry) :
    ∃ path : Fin (Fintype.card Cell + 1) → Point,
      path 0 = entry ∧
      (∀ time : Fin (Fintype.card Cell), low ≤ rank (path time.castSucc) →
        relation (path time.castSucc) (path time.succ)) ∧
      (((∀ time, low ≤ rank (path time)) ∧
          ∃ first last : Fin (Fintype.card Cell + 1),
            first < last ∧ dist (path first) (path last) < tolerance) ∨
        ∃ time : Fin (Fintype.card Cell + 1),
          rank entry - rank (path time) > high - low) := by
  let buffer : Set Point := {point | low ≤ rank point}
  obtain ⟨path, hentry, hpath, hclose | hexit⟩ :=
    exists_bufferedPath_downstream_close_or_exit
      relation buffer
      (fun point hpoint ↦ serial point hpoint)
      cell tolerance
      (fun point₁ hpoint₁ point₂ hpoint₂ hsame ↦
        cell_close point₁ hpoint₁ point₂ hpoint₂ hsame)
      entry
  · exact ⟨path, hentry, hpath, Or.inl hclose⟩
  · refine ⟨path, hentry, hpath, Or.inr ?_⟩
    rcases hexit with ⟨time, htime⟩
    refine ⟨time, ?_⟩
    have hrank : rank (path time) < low := lt_of_not_ge htime
    linarith

/-! ## Adapter to the actual compact exact-D tail -/

section Quitting

open Filter Math.Probability

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- Every supplied infinite exact dynamic-debt tail has a downstream
one-seam segment at the resolution of any supplied finite cover of its compact
debt box.  The exact path is preserved; only its two downstream indices are
selected. -/
theorem quittingDynamicDebtTail_exists_downstream_oneSeam
    [Fintype Cell]
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (path : ℕ → QuittingDebtPoint ι)
    (hbox : ∀ time, path time ∈ quittingDebtBox reward)
    (hedge : ∀ time,
      IsQuittingDynamicDebtEdge reward (path time) (path (time + 1)))
    (cell : QuittingDebtPoint ι → Cell) (tolerance : ℝ)
    (cell_close : ∀ point₁, point₁ ∈ quittingDebtBox reward →
      ∀ point₂, point₂ ∈ quittingDebtBox reward →
        cell point₁ = cell point₂ → dist point₁ point₂ < tolerance) :
    ∃ first last : Fin (Fintype.card Cell + 1),
      first < last ∧ dist (path first) (path last) < tolerance ∧
        ∀ time : Fin (Fintype.card Cell),
          IsQuittingDynamicDebtEdge reward
            (path time) (path (time + 1)) := by
  obtain ⟨hexact, hclose | hexit⟩ :=
    exactPrefix_downstream_close_or_exit
      (IsQuittingDynamicDebtEdge reward) path hedge
      (quittingDebtBox reward) cell tolerance cell_close
  · rcases hclose.2 with ⟨first, last, hlt, hdist⟩
    exact ⟨first, last, hlt, hdist, hexact⟩
  · rcases hexit with ⟨time, hnot⟩
    exact False.elim (hnot (hbox time))

/-- The formal quitting split can be sharpened by a downstream exact-D seam
for every supplied finite cover of the compact debt box.  This remains a
state-space seam only: it does not preserve the finite terminal packet or
compile the seam into a repair. -/
theorem quittingGame_uniformEquilibriumPayoff_or_positiveTail_oneSeam
    [Nonempty ι] [Fintype Cell]
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (cell : QuittingDebtPoint ι → Cell) (tolerance : ℝ)
    (cell_close : ∀ point₁, point₁ ∈ quittingDebtBox reward →
      ∀ point₂, point₂ ∈ quittingDebtBox reward →
        cell point₁ = cell point₂ → dist point₁ point₂ < tolerance) :
    (∃ payoff : Payoff ι,
      (quittingGame reward).IsUniformEquilibriumPayoff none payoff) ∨
    ∃ (path : ℕ → QuittingDebtPoint ι) (who : ι)
        (first last : Fin (Fintype.card Cell + 1)),
      (∀ time, path time ∈ quittingDebtBox reward) ∧
      (∀ time, IsQuittingDynamicDebtEdge reward
        (path time) (path (time + 1))) ∧
      0 < (path 0).2 who ∧
      Summable (quittingOpponentClockCharge
        (quittingDynamicDebtTailRoots path) who) ∧
      first < last ∧ dist (path first) (path last) < tolerance := by
  rcases quittingGame_uniformEquilibriumPayoff_or_positiveDynamicDebtTail
      reward with hpayoff | htail
  · exact Or.inl hpayoff
  · rcases htail with
      ⟨path, _subseq, who, _hmono, _hlimit, hbox, hedge, hpositive, hclock⟩
    obtain ⟨first, last, hlt, hdist, _hexact⟩ :=
      quittingDynamicDebtTail_exists_downstream_oneSeam
        reward path hbox hedge cell tolerance cell_close
    exact Or.inr ⟨path, who, first, last, hbox, hedge, hpositive, hclock,
      hlt, hdist⟩

end Quitting


end GameTheory
