/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegimeAll

/-!
# Decentralized rollover and liquidation games

This experiment gives the reduced quitting-game obstruction a self-contained
economic presentation.  A finite family of claimants repeatedly chooses
between `Call` (`true`) and `Roll` (`false`).  A nonempty set of callers
liquidates the project and receives the corresponding settlement vector; if
everyone rolls, the same live project is restarted.  Perpetual rollover has
terminal payoff zero.

The definitions below are deliberately a thin interface over the quitting
game API.  They do not copy its probability or equilibrium theory.  The main
results prove the exact dictionary:

* a clearing quote is the quitting root successor payoff;
* local clearing is exact root Nash and liquidation intensity is absorption;
* a fractional sole-caller plan is exactly the normalized singleton packet;
* every packet target is already an exact no-call phantom self-loop, although
  perpetual rollover realizes zero rather than that book quote;
* finite clearing capacity is exactly finite punishment-floor prefix-charge
  capacity;
* a bounded rollover obstruction is equivalent to nonexistence of a uniform
  equilibrium payoff;
* every obstruction forces a packet, at least four claimants, quiet late
  clearing rows whose restarted schedules remain uniformly run-vulnerable,
  and an orbit-attached no-call phantom limit.

Thus the model changes the interpretation, not the mathematical problem.  It
also keeps the crucial separation between a Bellman book quote and a payoff
actually realized by infinite play.
-/

noncomputable section

namespace GameTheory
namespace RolloverLiquidation

open Filter StochasticGame

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- A decentralized rollover market is specified by its liquidation
settlement vector for every nonempty set of simultaneous callers. -/
structure Market (ι : Type) [Fintype ι] where
  settlement : {S : Finset ι // S.Nonempty} → Payoff ι

namespace Market

variable (market : Market ι)

/-- The stochastic game played by the claimants.  `true` means Call and
`false` means Roll. -/
abbrev behaviorGame := quittingGame market.settlement

/-- A possibly history-dependent decentralized calling schedule. -/
abbrev Schedule := market.behaviorGame.BehaviorProfile

/-- One claimant's possibly history-dependent unilateral calling policy. -/
abbrev CallPolicy (who : ι) := market.behaviorGame.BehaviorStrategy who

/-- Expected cash settlement of a schedule.  Nonliquidation contributes
zero. -/
def terminalSettlement (schedule : market.Schedule) (who : ι) : ℝ :=
  quittingTerminalPayoff market.settlement schedule who

/-- The schedule in which every claimant rolls at every history. -/
def alwaysRoll : market.Schedule :=
  quittingAlwaysContinueProfile market.settlement

/-- A history-independent schedule generated by independent call rows,
launched at a supplied restart date. -/
def rowSchedule (rows : ℕ → ι → PMF Bool) (start : ℕ) : market.Schedule :=
  quittingRootSequenceProfile market.settlement rows start

omit [DecidableEq ι] in
/-- Perpetual rollover realizes zero cash settlement. -/
@[simp] theorem terminalSettlement_alwaysRoll (who : ι) :
    market.terminalSettlement market.alwaysRoll who = 0 := by
  exact quittingTerminalPayoff_quittingAlwaysContinue market.settlement who

/-- Probability that at least one claimant calls in an independent row. -/
def liquidationIntensity (_market : Market ι) (row : ι → PMF Bool) : ℝ :=
  quittingRootAbsorptionMass row

/-- The current book quote obtained from a call row and a continuation book
quote. -/
def clearingQuote (tail : Payoff ι) (row : ι → PMF Bool) : Payoff ι :=
  quittingRootSuccessorPayoff market.settlement tail row

/-- Exact local clearing: no claimant can improve the one-period
call-versus-roll decision while the continuation quote is held fixed. -/
def IsLocallyClearing (tail : Payoff ι) (row : ι → PMF Bool) : Prop :=
  IsεQuittingRootNash market.settlement tail 0 row

/-- The rollover clearing graph, with the row stored in simplex form. -/
def IsExactClearingEdge
    (current tail : QuittingNashBellmanPoint ι) : Prop :=
  IsQuittingNashBellmanEdge market.settlement current tail

omit [DecidableEq ι] in
/-- The rollover quote is literally the expected quitting root payoff. -/
@[simp] theorem clearingQuote_apply
    (tail : Payoff ι) (row : ι → PMF Bool) (who : ι) :
    market.clearingQuote tail row who =
      quittingRootExpectedPayoff market.settlement tail row who :=
  rfl

omit [DecidableEq ι] in
/-- The rollover liquidation intensity is literally the quitting root's
one-stage absorption mass. -/
theorem liquidationIntensity_eq_absorptionMass (row : ι → PMF Bool) :
    market.liquidationIntensity row = quittingRootAbsorptionMass row :=
  rfl

/-- A fractional sole-caller liquidation plan: a probability vector over
singleton callers together with the book quote it supports. -/
abbrev FractionalLiquidationPacket :=
  QuittingNormalizedSingletonSourcePacket market.settlement

/-- Simplex presentation of the row in which every claimant rolls. -/
def noCallPoint (_market : Market ι)
    (quote : Payoff ι) : QuittingNashBellmanPoint ι :=
  (quote, quittingAllContinueSimplexRoot)

/-- A no-call phantom quote is an exact Bellman self-loop at the all-Roll
row.  It is a book-value statement, not a realization statement. -/
def IsNoCallPhantomQuote (quote : Payoff ι) : Prop :=
  market.IsExactClearingEdge (market.noCallPoint quote)
    (market.noCallPoint quote)

/-- **The packet target is already a phantom self-loop.**  The Bellman part
is the identity at all-Roll, and `solo_le_target` is exactly the local Nash
condition preventing a claimant from calling alone against that quote. -/
theorem FractionalLiquidationPacket.target_isNoCallPhantomQuote
    (packet : market.FractionalLiquidationPacket) :
    market.IsNoCallPhantomQuote packet.target := by
  unfold IsNoCallPhantomQuote IsExactClearingEdge noCallPoint
  constructor
  · change packet.target = quittingRootSuccessorPayoff market.settlement
      packet.target
      (quittingRootOfSimplex
        (quittingAllContinueSimplexRoot (ι := ι)))
    rw [quittingRootOfSimplex_allContinueSimplexRoot,
      quittingRootSuccessorPayoff_allContinueRoot_eq]
  · change IsεQuittingRootEndpointNash market.settlement packet.target 0
      (quittingRootOfSimplex
        (quittingAllContinueSimplexRoot (ι := ι)))
    rw [quittingRootOfSimplex_allContinueSimplexRoot,
      isZeroQuittingRootEndpointNash_iff_isZeroQuittingRootNash]
    exact quittingAllContinueRoot_isZeroNash_of_singleton_le
      market.settlement packet.target packet.solo_le_target

/-- The same packet target lies above every claimant's behavioral security
value. -/
theorem FractionalLiquidationPacket.securityValue_le_target
    (packet : market.FractionalLiquidationPacket) (who : ι) :
    quittingPunishmentValue market.settlement who ≤ packet.target who :=
  packet.punishment_le_target who

/-- Despite the exact phantom self-loop, actual perpetual rollover still
realizes zero. -/
theorem FractionalLiquidationPacket.phantom_not_cash
    (packet : market.FractionalLiquidationPacket) (who : ι)
    (hnonzero : packet.target who ≠ 0) :
    market.terminalSettlement market.alwaysRoll who ≠ packet.target who := by
  simp only [terminalSettlement_alwaysRoll]
  exact Ne.symm hnonzero

/-- A finite chain of exact, security-floor-anchored clearing rows. -/
abbrev ClearingPrefix :=
  QuittingPunishmentFloorFinitePrefix market.settlement

/-- Cumulative conditional liquidation intensity along a clearing prefix. -/
def ClearingPrefix.totalLiquidationIntensity
    (chain : market.ClearingPrefix) : ℝ :=
  chain.charge

/-- The canonical extended-real capacity of all exact floor-anchored
clearing prefixes. -/
def clearingCapacity : ENNReal :=
  quittingPunishmentFloorPrefixChargeCapacity market.settlement

/-- The market has finite clearing capacity when the universal prefix
capacity is not `⊤`. -/
def HasFiniteClearingCapacity : Prop :=
  market.clearingCapacity ≠ ⊤

/-- Finite clearing capacity is exactly the existence of one nonnegative
real bound for every exact floor-anchored clearing prefix. -/
theorem hasFiniteClearingCapacity_iff_exists_bound :
    market.HasFiniteClearingCapacity ↔
      ∃ capacity : ℝ, 0 ≤ capacity ∧
        ∀ chain : market.ClearingPrefix,
          chain.totalLiquidationIntensity ≤ capacity := by
  simpa only [HasFiniteClearingCapacity, clearingCapacity,
    ClearingPrefix.totalLiquidationIntensity] using
    (punishmentFloorPrefixChargeCapacity_ne_top_iff
      (reward := market.settlement))

/-- A bounded rollover obstruction packages the two substantive properties
of a hypothetical counterexample: one uniform unilateral run margin against
every schedule, and finite capacity for every exact local clearing prefix.
The packet and phantom limits are consequences, not extra fields. -/
structure IsBoundedRolloverObstruction where
  runGap : ℝ
  runGap_pos : 0 < runGap
  everySchedule_runVulnerable :
    HasTerminalExploitabilityGap market.settlement runGap
  finiteClearingCapacity : market.HasFiniteClearingCapacity

namespace IsBoundedRolloverObstruction

variable {market : Market ι}

/-- Forget the economic names and recover the canonical quitting
counterexample regime. -/
def toCounterexampleRegime
    (obstruction : market.IsBoundedRolloverObstruction) :
    QuittingCounterexampleRegime market.settlement where
  terminalGap := obstruction.runGap
  terminalGap_pos := obstruction.runGap_pos
  terminalExploitability := obstruction.everySchedule_runVulnerable

/-- Every quitting counterexample regime is a bounded rollover
obstruction. -/
def ofCounterexampleRegime
    (regime : QuittingCounterexampleRegime market.settlement) :
    market.IsBoundedRolloverObstruction where
  runGap := regime.terminalGap
  runGap_pos := regime.terminalGap_pos
  everySchedule_runVulnerable := regime.terminalExploitability
  finiteClearingCapacity := regime.prefixChargeCapacity_ne_top

/-- Every bounded rollover obstruction has no uniform-equilibrium payoff. -/
theorem not_exists_uniformEquilibriumPayoff
    (obstruction : market.IsBoundedRolloverObstruction) :
    ¬ ∃ payoff : Payoff ι,
      market.behaviorGame.IsUniformEquilibriumPayoff none payoff :=
  obstruction.toCounterexampleRegime.not_exists_uniformEquilibriumPayoff

/-- The analytic waist forces a fractionally viable sole-caller liquidation
plan in every bounded rollover obstruction. -/
theorem nonempty_fractionalLiquidationPacket
    (obstruction : market.IsBoundedRolloverObstruction) :
    Nonempty market.FractionalLiquidationPacket :=
  obstruction.toCounterexampleRegime.nonempty_normalizedSingletonSourcePacket

/-- No bounded rollover obstruction exists with fewer than four
claimants. -/
theorem four_le_card
    (obstruction : market.IsBoundedRolloverObstruction) :
    4 ≤ Fintype.card ι := by
  have hcard := obstruction.toCounterexampleRegime.three_lt_card
  omega

/-- Every exact clearing prefix is bounded by the canonical real capacity. -/
theorem prefix_intensity_le_capacity
    (obstruction : market.IsBoundedRolloverObstruction)
    (chain : market.ClearingPrefix) :
    chain.totalLiquidationIntensity ≤
      quittingPunishmentFloorPrefixChargeBound market.settlement :=
  obstruction.toCounterexampleRegime.prefixCharge_le chain

end IsBoundedRolloverObstruction

/-- **Exact connection to the quitting conjecture.**  Existence of a bounded
rollover obstruction is equivalent to nonexistence of a uniform-equilibrium
payoff in the underlying quitting game. -/
theorem nonempty_boundedRolloverObstruction_iff
    [Nonempty ι] :
    Nonempty market.IsBoundedRolloverObstruction ↔
      ¬ ∃ payoff : Payoff ι,
        market.behaviorGame.IsUniformEquilibriumPayoff none payoff := by
  constructor
  · rintro ⟨obstruction⟩
    exact obstruction.not_exists_uniformEquilibriumPayoff
  · intro hno
    exact ⟨IsBoundedRolloverObstruction.ofCounterexampleRegime
      (quittingCounterexampleRegimeOfNoUniformPayoff
        market.settlement hno)⟩

/-- An arbitrary infinite exact security-floor clearing orbit. -/
abbrev ClearingOrbit :=
  QuittingPunishmentFloorInfiniteOrbit market.settlement

namespace IsBoundedRolloverObstruction

variable {market : Market ι}

/-- Finite clearing capacity makes total liquidation intensity summable along
every infinite exact floor-anchored clearing orbit. -/
theorem orbit_liquidationIntensity_summable
    (obstruction : market.IsBoundedRolloverObstruction)
    (orbit : market.ClearingOrbit) :
    Summable (fun time =>
      market.liquidationIntensity (orbit.roots time)) :=
  obstruction.toCounterexampleRegime
    |>.infiniteOrbit_absorptionMass_summable orbit

/-- **Quiet late restarts remain uniformly run-vulnerable.**  Along every
exact clearing orbit, sufficiently late rows have arbitrarily small
liquidation intensity, while the genuine decentralized schedule launched at
that date still admits a unilateral terminal-settlement improvement of at
least the fixed run gap.  The claimant and deviation may vary with the
restart date. -/
theorem eventually_quiet_and_restart_runVulnerable
    (obstruction : market.IsBoundedRolloverObstruction)
    (orbit : market.ClearingOrbit)
    (ε : ℝ) (hε : 0 < ε) :
    ∀ᶠ time in atTop,
      market.liquidationIntensity (orbit.roots time) < ε ∧
        ∃ (who : ι) (deviation : market.CallPolicy who),
          market.terminalSettlement
              (market.rowSchedule orbit.roots time) who +
              obstruction.runGap ≤
            market.terminalSettlement
              (Function.update (market.rowSchedule orbit.roots time)
                who deviation) who := by
  simpa only [liquidationIntensity, terminalSettlement, rowSchedule,
    toCounterexampleRegime] using
    obstruction.toCounterexampleRegime
      |>.eventually_smallAbsorption_and_terminalExploitability orbit ε hε

/-- **Orbit-attached phantom quote.**  Every infinite exact clearing orbit
has a coordinatewise limiting book quote in the reward box, above all
security values, and that limit is an exact all-Roll self-loop. -/
theorem orbit_exists_attachedPhantomLimit
    (obstruction : market.IsBoundedRolloverObstruction)
    (orbit : market.ClearingOrbit) :
    ∃ limit : Payoff ι,
      (∀ who, Tendsto (fun time => orbit.value time who) atTop
        (nhds (limit who))) ∧
      limit ∈ quittingPunishmentFloorForwardCarrier market.settlement ∧
      (∀ who,
        quittingPunishmentValue market.settlement who ≤ limit who) ∧
      market.IsNoCallPhantomQuote limit := by
  simpa only [IsNoCallPhantomQuote, IsExactClearingEdge, noCallPoint] using
    obstruction.toCounterexampleRegime.infiniteOrbit_exists_selfLoop_limit
      orbit

end IsBoundedRolloverObstruction

end Market
end RolloverLiquidation
end GameTheory
