/-
Copyright (c) 2026 UniformEquilibrium contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: UniformEquilibrium contributors
-/

import UniformEquilibrium.Diagnostics.Quitting.TerminalCapNashEndpointTransport
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticResetIncidenceReturn

/-!
# Law-tight cap--Nash saturation hull

This module constructs the closed hull generated by exact cap--Nash prefixes
and debt-nonincreasing replacement within one terminal-law fibre.  When its
origin belongs to the joint terminal-semantic carrier, the hull is a compact
carrier subset.  A positive global debt floor and one positive finite atom at
the origin give a debt minimizer which retains that atom.

The construction does not supply a carrier origin or a positive atom.  It
does not identify a minimum face or unique root, prove absorption or chamber
membership, recover ancestry or timing, or produce a uniform equilibrium.
-/

noncomputable section

namespace GameTheory

open Set
open scoped Topology

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- A closed subset of the joint semantic/outcome-law carrier which contains
the origin, is stable under exact roots selected against the displayed cap,
and is downward closed under replacement inside one outcome-law fibre. -/
structure IsQuittingLawTightCapNashInvariant
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (origin : QuittingTerminalSemanticLawPoint ι)
    (points : Set (QuittingTerminalSemanticLawPoint ι)) : Prop where
  isClosed : IsClosed points
  subset_carrier : points ⊆ quittingTerminalSemanticLawCarrier reward
  origin_mem : origin ∈ points
  prefix_mem : ∀ (point : QuittingTerminalSemanticLawPoint ι),
    point ∈ points → ∀ (root : ι → PMF Bool),
    IsεQuittingRootNash reward point.1.2 0 root →
      (quittingTerminalSemanticPrefix reward root point.1,
        quittingTerminalOutcomeLawPrefix root point.2) ∈ points
  sameLaw_of_debt_le : ∀ (point : QuittingTerminalSemanticLawPoint ι),
    point ∈ points → ∀ (replacement : QuittingTerminalSemanticPair ι),
    (replacement, point.2) ∈ quittingTerminalSemanticLawCarrier reward →
      quittingTerminalSemanticDebtSum replacement ≤
        quittingTerminalSemanticDebtSum point.1 →
      (replacement, point.2) ∈ points

/-- The intersection of all closed, exact-cap-prefix invariant and law-tight
sets containing `origin`.  If `origin` belongs to the joint carrier, the
carrier itself is one such set and this hull is a carrier subset. -/
def quittingLawTightCapNashSaturationHull
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (origin : QuittingTerminalSemanticLawPoint ι) :
    Set (QuittingTerminalSemanticLawPoint ι) :=
  ⋂₀ {points | IsQuittingLawTightCapNashInvariant reward origin points}

theorem isQuittingLawTightCapNashInvariant_carrier
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (origin : QuittingTerminalSemanticLawPoint ι)
    (horigin : origin ∈ quittingTerminalSemanticLawCarrier reward) :
    IsQuittingLawTightCapNashInvariant reward origin
      (quittingTerminalSemanticLawCarrier reward) where
  isClosed := (quittingTerminalSemanticLawCarrier_isCompact reward).isClosed
  subset_carrier := fun _ point_mem ↦ point_mem
  origin_mem := horigin
  prefix_mem point point_mem root _ :=
    quittingTerminalSemanticLawPrefix_mem_carrier
      reward root point point_mem
  sameLaw_of_debt_le _ _ _ replacement_mem _ := replacement_mem

theorem quittingLawTightCapNashSaturationHull_origin_mem
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (origin : QuittingTerminalSemanticLawPoint ι) :
    origin ∈ quittingLawTightCapNashSaturationHull reward origin := by
  rw [quittingLawTightCapNashSaturationHull, mem_sInter]
  intro points hpoints
  exact hpoints.origin_mem

theorem quittingLawTightCapNashSaturationHull_subset_carrier
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (origin : QuittingTerminalSemanticLawPoint ι)
    (horigin : origin ∈ quittingTerminalSemanticLawCarrier reward) :
    quittingLawTightCapNashSaturationHull reward origin ⊆
      quittingTerminalSemanticLawCarrier reward := by
  intro point hpoint
  rw [quittingLawTightCapNashSaturationHull, mem_sInter] at hpoint
  exact hpoint (quittingTerminalSemanticLawCarrier reward)
    (isQuittingLawTightCapNashInvariant_carrier reward origin horigin)

theorem quittingLawTightCapNashSaturationHull_isClosed
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (origin : QuittingTerminalSemanticLawPoint ι) :
    IsClosed (quittingLawTightCapNashSaturationHull reward origin) := by
  rw [quittingLawTightCapNashSaturationHull]
  apply isClosed_sInter
  intro points hpoints
  exact hpoints.isClosed

theorem quittingLawTightCapNashSaturationHull_isCompact
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (origin : QuittingTerminalSemanticLawPoint ι)
    (horigin : origin ∈ quittingTerminalSemanticLawCarrier reward) :
    IsCompact (quittingLawTightCapNashSaturationHull reward origin) :=
  (quittingTerminalSemanticLawCarrier_isCompact reward).of_isClosed_subset
    (quittingLawTightCapNashSaturationHull_isClosed reward origin)
    (quittingLawTightCapNashSaturationHull_subset_carrier
      reward origin horigin)

theorem quittingLawTightCapNashSaturationHull_prefix_mem
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (origin point : QuittingTerminalSemanticLawPoint ι)
    (hpoint : point ∈ quittingLawTightCapNashSaturationHull reward origin)
    (root : ι → PMF Bool)
    (hnash : IsεQuittingRootNash reward point.1.2 0 root) :
    (quittingTerminalSemanticPrefix reward root point.1,
      quittingTerminalOutcomeLawPrefix root point.2) ∈
        quittingLawTightCapNashSaturationHull reward origin := by
  rw [quittingLawTightCapNashSaturationHull, mem_sInter] at hpoint ⊢
  intro points hpoints
  exact hpoints.prefix_mem point (hpoint points hpoints) root hnash

theorem quittingLawTightCapNashSaturationHull_sameLaw_of_debt_le
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (origin point : QuittingTerminalSemanticLawPoint ι)
    (hpoint : point ∈ quittingLawTightCapNashSaturationHull reward origin)
    (replacement : QuittingTerminalSemanticPair ι)
    (hreplacement : (replacement, point.2) ∈
      quittingTerminalSemanticLawCarrier reward)
    (hdebt : quittingTerminalSemanticDebtSum replacement ≤
      quittingTerminalSemanticDebtSum point.1) :
    (replacement, point.2) ∈
      quittingLawTightCapNashSaturationHull reward origin := by
  rw [quittingLawTightCapNashSaturationHull, mem_sInter] at hpoint ⊢
  intro points hpoints
  exact hpoints.sameLaw_of_debt_le point (hpoint points hpoints)
    replacement hreplacement hdebt

private def quittingLawTightCapNashAtomCone
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (origin : QuittingTerminalSemanticLawPoint ι)
    (coalition : {S : Finset ι // S.Nonempty}) :
    Set (QuittingTerminalSemanticLawPoint ι) :=
  quittingTerminalSemanticLawCarrier reward ∩
    {point | quittingTerminalSemanticDebtSum point.1 *
          origin.2 (some coalition) ≤
        quittingTerminalSemanticDebtSum origin.1 *
          point.2 (some coalition)}

private theorem isQuittingLawTightCapNashInvariant_atomCone
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (origin : QuittingTerminalSemanticLawPoint ι)
    (horigin : origin ∈ quittingTerminalSemanticLawCarrier reward)
    (coalition : {S : Finset ι // S.Nonempty})
    (hfloor : ∃ debtFloor : ℝ, 0 < debtFloor ∧
      ∀ point ∈ quittingTerminalSemanticLawCarrier reward,
        debtFloor ≤ quittingTerminalSemanticDebtSum point.1)
    (hatom : 0 < origin.2 (some coalition)) :
    IsQuittingLawTightCapNashInvariant reward origin
      (quittingLawTightCapNashAtomCone reward origin coalition) := by
  obtain ⟨debtFloor, hfloor_pos, hfloor⟩ := hfloor
  have horigin_debt_pos : 0 < quittingTerminalSemanticDebtSum origin.1 :=
    hfloor_pos.trans_le (hfloor origin horigin)
  let debt : QuittingTerminalSemanticLawPoint ι → ℝ := fun point ↦
    quittingTerminalSemanticDebtSum point.1
  let atom : QuittingTerminalSemanticLawPoint ι → ℝ := fun point ↦
    point.2 (some coalition)
  have hdebt : Continuous debt :=
    continuous_quittingTerminalSemanticDebtSum.comp continuous_fst
  have hatomContinuous : Continuous atom :=
    (continuous_apply (some coalition)).comp continuous_snd
  refine
    { isClosed := ?_
      subset_carrier := fun _ point_mem ↦ point_mem.1
      origin_mem := ⟨horigin, by
        change quittingTerminalSemanticDebtSum origin.1 *
            origin.2 (some coalition) ≤
          quittingTerminalSemanticDebtSum origin.1 *
            origin.2 (some coalition)
        exact le_rfl⟩
      prefix_mem := ?_
      sameLaw_of_debt_le := ?_ }
  · exact (quittingTerminalSemanticLawCarrier_isCompact reward).isClosed.inter
      (isClosed_le (hdebt.mul continuous_const)
        (continuous_const.mul hatomContinuous))
  · rintro point ⟨hpoint_carrier, hpoint_cone⟩ root hnash
    have hprefix_carrier := quittingTerminalSemanticLawPrefix_mem_carrier
      reward root point hpoint_carrier
    have hdebt_scale :
        quittingTerminalSemanticDebtSum
            (quittingTerminalSemanticPrefix reward root point.1) =
          quittingStationaryContinueMass root *
            quittingTerminalSemanticDebtSum point.1 := by
      unfold quittingTerminalSemanticDebtSum
      simp_rw [quittingTerminalSemanticDebt_prefix_eq_continueMass_mul_of_capNash
        point.1 root _ hnash]
      exact (Finset.mul_sum ..).symm
    have hcontinue_nonneg := quittingStationaryContinueMass_nonneg root
    have hroot_nonneg := quittingRootCoalitionMass_nonneg root coalition.1
    have hscaledCone :
        quittingStationaryContinueMass root *
            (quittingTerminalSemanticDebtSum point.1 *
              origin.2 (some coalition)) ≤
          quittingStationaryContinueMass root *
            (quittingTerminalSemanticDebtSum origin.1 *
              point.2 (some coalition)) :=
      mul_le_mul_of_nonneg_left hpoint_cone hcontinue_nonneg
    refine ⟨hprefix_carrier, ?_⟩
    change quittingTerminalSemanticDebtSum
          (quittingTerminalSemanticPrefix reward root point.1) *
            origin.2 (some coalition) ≤
      quittingTerminalSemanticDebtSum origin.1 *
        (quittingRootCoalitionMass root coalition.1 +
          quittingStationaryContinueMass root * point.2 (some coalition))
    rw [hdebt_scale]
    nlinarith [mul_nonneg horigin_debt_pos.le hroot_nonneg]
  · rintro point ⟨_, hpoint_cone⟩ replacement replacement_mem hdebt_le
    refine ⟨replacement_mem, ?_⟩
    change quittingTerminalSemanticDebtSum point.1 *
        origin.2 (some coalition) ≤
      quittingTerminalSemanticDebtSum origin.1 * point.2 (some coalition)
      at hpoint_cone
    change quittingTerminalSemanticDebtSum replacement *
        origin.2 (some coalition) ≤
      quittingTerminalSemanticDebtSum origin.1 * point.2 (some coalition)
    nlinarith [mul_nonneg (sub_nonneg.mpr hdebt_le) hatom.le]

/-- Every point of the canonical hull satisfies the debt-weighted retained
finite-atom inequality. -/
theorem quittingLawTightCapNashSaturationHull_atomCone
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (debtFloor : ℝ) (hfloor_pos : 0 < debtFloor)
    (hfloor : ∀ point ∈ quittingTerminalSemanticLawCarrier reward,
      debtFloor ≤ quittingTerminalSemanticDebtSum point.1)
    (origin : QuittingTerminalSemanticLawPoint ι)
    (horigin : origin ∈ quittingTerminalSemanticLawCarrier reward)
    (coalition : {S : Finset ι // S.Nonempty})
    (hatom : 0 < origin.2 (some coalition))
    {point : QuittingTerminalSemanticLawPoint ι}
    (hpoint : point ∈ quittingLawTightCapNashSaturationHull reward origin) :
    quittingTerminalSemanticDebtSum point.1 * origin.2 (some coalition) ≤
      quittingTerminalSemanticDebtSum origin.1 * point.2 (some coalition) := by
  rw [quittingLawTightCapNashSaturationHull, mem_sInter] at hpoint
  exact (hpoint (quittingLawTightCapNashAtomCone reward origin coalition)
    (isQuittingLawTightCapNashInvariant_atomCone reward origin horigin
      coalition ⟨debtFloor, hfloor_pos, hfloor⟩ hatom)).2

/-- The compact canonical hull has a debt minimizer. Under a positive ambient
debt floor and a positive origin atom, the minimizer retains a positive atom
of the same terminal coalition and satisfies the exact cone inequality. -/
theorem exists_quittingLawTightCapNashSaturationHull_minimum_retaining_atom
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (debtFloor : ℝ) (hfloor_pos : 0 < debtFloor)
    (hfloor : ∀ point ∈ quittingTerminalSemanticLawCarrier reward,
      debtFloor ≤ quittingTerminalSemanticDebtSum point.1)
    (origin : QuittingTerminalSemanticLawPoint ι)
    (horigin : origin ∈ quittingTerminalSemanticLawCarrier reward)
    (coalition : {S : Finset ι // S.Nonempty})
    (hatom : 0 < origin.2 (some coalition)) :
    ∃ minimum : QuittingTerminalSemanticLawPoint ι,
      minimum ∈ quittingLawTightCapNashSaturationHull reward origin ∧
      (∀ point ∈ quittingLawTightCapNashSaturationHull reward origin,
        quittingTerminalSemanticDebtSum minimum.1 ≤
          quittingTerminalSemanticDebtSum point.1) ∧
      debtFloor ≤ quittingTerminalSemanticDebtSum minimum.1 ∧
      quittingTerminalSemanticDebtSum minimum.1 *
          origin.2 (some coalition) ≤
        quittingTerminalSemanticDebtSum origin.1 *
          minimum.2 (some coalition) ∧
      0 < minimum.2 (some coalition) := by
  have hcompact := quittingLawTightCapNashSaturationHull_isCompact
    reward origin horigin
  have hnonempty :
      (quittingLawTightCapNashSaturationHull reward origin).Nonempty :=
    ⟨origin, quittingLawTightCapNashSaturationHull_origin_mem reward origin⟩
  have hcontinuous : Continuous
      (fun point : QuittingTerminalSemanticLawPoint ι ↦
        quittingTerminalSemanticDebtSum point.1) :=
    continuous_quittingTerminalSemanticDebtSum.comp continuous_fst
  obtain ⟨minimum, hminimum_mem, hminimum⟩ :=
    hcompact.exists_isMinOn hnonempty hcontinuous.continuousOn
  have hminimum_carrier :=
    quittingLawTightCapNashSaturationHull_subset_carrier
      reward origin horigin hminimum_mem
  have hminimum_floor := hfloor minimum hminimum_carrier
  have horigin_floor := hfloor origin horigin
  have hcone := quittingLawTightCapNashSaturationHull_atomCone
    reward debtFloor hfloor_pos hfloor origin horigin coalition hatom
    hminimum_mem
  refine ⟨minimum, hminimum_mem, hminimum, hminimum_floor, hcone, ?_⟩
  nlinarith

end GameTheory
