/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticSimultaneousResetOrientationLocalization
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticPositiveSlopeRectangle
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticStoppingLawResetCube

/-!
# Orientation routing for stopping-law reset cubes

A common-scale family of stopping-law replacements is simultaneously:

* a literal Boolean reset cube, whose common-source/path discrepancy is either
  small or localized to a signed two-reset square; and
* a simultaneous reset family, whose loss of an active unilateral debt
  orientation is localized to an actual debt recipient or a positive-slope
  terminal atom.

This module composes those two exact alternatives. It also exposes a typed
routing theorem: a chronological rotor or reprojection consumer receives only
the near-return branch, while a nonlinear consumer receives the signed square
together with the simultaneous-reset orientation certificate.

No chronological compiler is asserted here. Supplying the near-return
consumer remains a separate semantic obligation.
-/

noncomputable section

namespace GameTheory

open Math.Finset
open Math.Finset.CubicalResetIntegrability
open Math.Optimization

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- The literal reset cube generated by one profile, one replacement for each
player, and one common stopping-law scale. -/
def quittingCommonScaleStoppingLawResetCubeData
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    (replacement : ∀ who, (quittingGame reward).BehaviorStrategy who)
    (lambda : ℝ) (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) :
    QuittingStoppingLawResetCubeData reward where
  source := profile
  target := replacement
  scale := fun _who ↦ lambda
  scale_nonneg := fun _who ↦ hlambda0
  scale_le_one := fun _who ↦ hlambda1

/-- The common-scale cube vertex is exactly the existing simultaneous-subset
stopping-law profile. -/
theorem quittingCommonScaleStoppingLawResetCubeData_profile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    (replacement : ∀ who, (quittingGame reward).BehaviorStrategy who)
    (lambda : ℝ) (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1)
    (moved : Finset ι) :
    (quittingCommonScaleStoppingLawResetCubeData reward profile replacement
      lambda hlambda0 hlambda1).profile moved =
        quittingStoppingLawMixtureSubsetProfile reward profile replacement
          lambda hlambda0 hlambda1 moved := by
  funext who
  by_cases hwho : who ∈ moved
  · simp [QuittingStoppingLawResetCubeData.profile,
      quittingCommonScaleStoppingLawResetCubeData,
      quittingStoppingLawMixtureSubsetProfile, hwho]
  · simp [QuittingStoppingLawResetCubeData.profile,
      quittingCommonScaleStoppingLawResetCubeData,
      quittingStoppingLawMixtureSubsetProfile, hwho]

/-- The game-facing orientation output attached to one active member of a
flat simultaneous stopping-law reset. -/
def HasQuittingStoppingLawResetOrientationAlternative
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    (replacement : ∀ who, (quittingGame reward).BehaviorStrategy who)
    (who : ι) (lambda : ℝ)
    (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) : Prop :=
  let source := quittingTerminalSemanticPair reward profile
  let simultaneousProfile :=
    quittingSimultaneousStoppingLawMixtureProfile reward profile replacement
      lambda hlambda0 hlambda1
  let simultaneousTarget :=
    quittingTerminalSemanticPair reward simultaneousProfile
  let endpointProfile := Function.update profile who (replacement who)
  let gain := quittingTerminalPayoff reward endpointProfile who -
    quittingTerminalPayoff reward profile who
  let opponents := Finset.univ.erase who
  let charge := gain / (2 * (opponents.card : ℝ))
  ((quittingTerminalSemanticDebt simultaneousTarget who ≤
        quittingTerminalSemanticDebt source who - lambda * gain / 2) ∧
      ∃ recipient ∈ opponents,
        lambda * charge ≤
          quittingTerminalSemanticDebtChange source simultaneousTarget
            recipient) ∨
    ∃ moved ⊆ opponents, ∃ mover ∈ opponents, mover ∉ moved ∧
      let edgeSource := quittingStoppingLawMixtureHybridProfile reward profile
        replacement who lambda hlambda0 hlambda1 moved
      let edgeTarget := quittingStoppingLawMixtureHybridProfile reward profile
        replacement who lambda hlambda0 hlambda1
          (insert mover moved)
      lambda * charge ≤
          quittingTerminalSemanticDebt
              (quittingTerminalSemanticPair reward edgeTarget) who -
            quittingTerminalSemanticDebt
              (quittingTerminalSemanticPair reward edgeSource) who ∧
        HasQuittingStoppingLawPositiveSlopeAtom reward edgeSource mover who
          (replacement mover) charge

/-- The simultaneous-reset localization theorem, packaged as the reusable
orientation output above. -/
theorem hasQuittingStoppingLawResetOrientationAlternative_of_activePassport_flat
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    (replacement : ∀ who, (quittingGame reward).BehaviorStrategy who)
    (who : ι) (terminal : {S : Finset ι // S.Nonempty}) (cutoff : ℕ)
    (lambda : ℝ) (hlambda0 : 0 < lambda) (hlambda1 : lambda ≤ 1)
    (hpassport : IsQuittingStoppingLawMinimumResetPassport reward profile who
      (replacement who) terminal cutoff)
    (hflat : quittingTerminalSemanticDebtSum
        (quittingTerminalSemanticPair reward
          (quittingSimultaneousStoppingLawMixtureProfile reward profile
            replacement lambda hlambda0.le hlambda1)) =
      quittingTerminalSemanticDebtSum
        (quittingTerminalSemanticPair reward profile)) :
    HasQuittingStoppingLawResetOrientationAlternative reward profile
      replacement who lambda hlambda0.le hlambda1 := by
  simpa only [HasQuittingStoppingLawResetOrientationAlternative] using
    activePassport_flatSimultaneous_directed_or_localizedPositiveSlope
      reward profile replacement who terminal cutoff lambda hlambda0 hlambda1
        hpassport hflat

/-- **Near return or signed curvature with an oriented semantic consumer.**

For the active player's debt observable, failure of the quantitative reset
return produces a signed two-reset square and, simultaneously, the existing
recipient-or-positive-slope orientation certificate. -/
theorem terminalSemanticDebt_resetCube_nearReturn_or_curvatureWithOrientation
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    (replacement : ∀ who, (quittingGame reward).BehaviorStrategy who)
    (who : ι) (terminal : {S : Finset ι // S.Nonempty}) (cutoff : ℕ)
    (lambda : ℝ) (hlambda0 : 0 < lambda) (hlambda1 : lambda ≤ 1)
    (word : List ι) (threshold : ℝ) (hthreshold : 0 ≤ threshold)
    (hpassport : IsQuittingStoppingLawMinimumResetPassport reward profile who
      (replacement who) terminal cutoff)
    (hflat : quittingTerminalSemanticDebtSum
        (quittingTerminalSemanticPair reward
          (quittingSimultaneousStoppingLawMixtureProfile reward profile
            replacement lambda hlambda0.le hlambda1)) =
      quittingTerminalSemanticDebtSum
        (quittingTerminalSemanticPair reward profile)) :
    let data := quittingCommonScaleStoppingLawResetCubeData reward profile
      replacement lambda hlambda0.le hlambda1
    let debt := fun candidate : (quittingGame reward).BehaviorProfile ↦
      quittingTerminalSemanticDebt
        (quittingTerminalSemanticPair reward candidate) who
    let nearReturn :=
      |data.value debt (finalSet ∅ word) - data.value debt ∅ -
          frozenEdgeSum (data.value debt) ∅ word| ≤
        (squareCount word : ℝ) * threshold
    let signedCurvature :=
      HasSquareAboveAlong (data.value debt) threshold ∅ word ∨
        HasSquareAboveAlong (fun reset ↦ -data.value debt reset)
          threshold ∅ word
    nearReturn ∨
      signedCurvature ∧
        HasQuittingStoppingLawResetOrientationAlternative reward profile
          replacement who lambda hlambda0.le hlambda1 := by
  dsimp only
  let data := quittingCommonScaleStoppingLawResetCubeData reward profile
    replacement lambda hlambda0.le hlambda1
  let debt := fun candidate : (quittingGame reward).BehaviorProfile ↦
    quittingTerminalSemanticDebt
      (quittingTerminalSemanticPair reward candidate) who
  have hcube := data.nearFrozenReturn_or_signedSquareAbove
    debt ∅ word threshold hthreshold
  have horientation :=
    hasQuittingStoppingLawResetOrientationAlternative_of_activePassport_flat
      reward profile replacement who terminal cutoff lambda hlambda0 hlambda1
        hpassport hflat
  rcases hcube with hnear | hpositive | hnegative
  · exact Or.inl hnear
  · exact Or.inr ⟨Or.inl hpositive, horientation⟩
  · exact Or.inr ⟨Or.inr hnegative, horientation⟩

/-- **Typed consumer routing.** A near-return consumer—such as a rotor or
carrier reprojection compiler—can only be invoked after receiving the literal
near-return estimate. The nonlinear consumer receives both the signed square
and the game-facing orientation certificate. -/
theorem terminalSemanticDebt_resetCube_routeNearReturnConsumer
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    (replacement : ∀ who, (quittingGame reward).BehaviorStrategy who)
    (who : ι) (terminal : {S : Finset ι // S.Nonempty}) (cutoff : ℕ)
    (lambda : ℝ) (hlambda0 : 0 < lambda) (hlambda1 : lambda ≤ 1)
    (word : List ι) (threshold : ℝ) (hthreshold : 0 ≤ threshold)
    (hpassport : IsQuittingStoppingLawMinimumResetPassport reward profile who
      (replacement who) terminal cutoff)
    (hflat : quittingTerminalSemanticDebtSum
        (quittingTerminalSemanticPair reward
          (quittingSimultaneousStoppingLawMixtureProfile reward profile
            replacement lambda hlambda0.le hlambda1)) =
      quittingTerminalSemanticDebtSum
        (quittingTerminalSemanticPair reward profile))
    (NearResult CurvatureResult : Prop)
    (nearConsumer :
      let data := quittingCommonScaleStoppingLawResetCubeData reward profile
        replacement lambda hlambda0.le hlambda1
      let debt := fun candidate : (quittingGame reward).BehaviorProfile ↦
        quittingTerminalSemanticDebt
          (quittingTerminalSemanticPair reward candidate) who
      |data.value debt (finalSet ∅ word) - data.value debt ∅ -
          frozenEdgeSum (data.value debt) ∅ word| ≤
          (squareCount word : ℝ) * threshold → NearResult)
    (curvatureConsumer :
      let data := quittingCommonScaleStoppingLawResetCubeData reward profile
        replacement lambda hlambda0.le hlambda1
      let debt := fun candidate : (quittingGame reward).BehaviorProfile ↦
        quittingTerminalSemanticDebt
          (quittingTerminalSemanticPair reward candidate) who
      (HasSquareAboveAlong (data.value debt) threshold ∅ word ∨
          HasSquareAboveAlong (fun reset ↦ -data.value debt reset)
            threshold ∅ word) →
        HasQuittingStoppingLawResetOrientationAlternative reward profile
          replacement who lambda hlambda0.le hlambda1 → CurvatureResult) :
    NearResult ∨ CurvatureResult := by
  have hroute :=
    terminalSemanticDebt_resetCube_nearReturn_or_curvatureWithOrientation
      reward profile replacement who terminal cutoff lambda hlambda0 hlambda1
        word threshold hthreshold hpassport hflat
  rcases hroute with hnear | ⟨hcurvature, horientation⟩
  · exact Or.inl (nearConsumer hnear)
  · exact Or.inr (curvatureConsumer hcurvature horientation)

/-! ## Pure-time witness switches on literal cube edges -/

/-- Orientation of a literal reset-cube edge.  `insert` follows the reset;
`delete` traverses the same edge back toward its unreset endpoint. -/
inductive QuittingResetEdgeOrientation
  | insert
  | delete

/-- Literal source profile of an oriented edge in a frozen reset cube. -/
def quittingResetEdgeSourceProfile
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    (data : QuittingStoppingLawResetCubeData reward)
    (base : Finset ι) (mover : ι) :
    QuittingResetEdgeOrientation → (quittingGame reward).BehaviorProfile
  | .insert => data.profile base
  | .delete => data.profile (insert mover base)

/-- Literal receiving profile of an oriented edge in a frozen reset cube. -/
def quittingResetEdgeReceivingProfile
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    (data : QuittingStoppingLawResetCubeData reward)
    (base : Finset ι) (mover : ι) :
    QuittingResetEdgeOrientation → (quittingGame reward).BehaviorProfile
  | .insert => data.profile (insert mover base)
  | .delete => data.profile base

/-- A selected pure quit time whose regret rises on one actual,
off-diagonal reset-cube edge.  The base set, changed mover, direction, and
literal source/receiving profiles are all retained. -/
structure QuittingPureTimeResetEdgeWitnessSwitch
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    (data : QuittingStoppingLawResetCubeData reward)
    (observer : ι) (quitTime : Option ℕ) (charge : ℝ) where
  base : Finset ι
  mover : ι
  mover_not_mem : mover ∉ base
  observer_ne_mover : observer ≠ mover
  orientation : QuittingResetEdgeOrientation
  regret_increase : charge ≤
    quittingPureTimeDeviationRegret reward
        (quittingResetEdgeReceivingProfile data base mover orientation)
        observer quitTime -
      quittingPureTimeDeviationRegret reward
        (quittingResetEdgeSourceProfile data base mover orientation)
        observer quitTime

/-- An edge witness together with its provenance inside one supplied reset
square. In particular, the changed mover is one of the square coordinates,
and the uninserted endpoint lies between the square's base and full face. -/
structure QuittingPureTimeResetSquareEdgeWitnessSwitch
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    (data : QuittingStoppingLawResetCubeData reward)
    (observer : ι) (squareBase : Finset ι) (first second : ι)
    (quitTime : Option ℕ) (charge : ℝ) where
  edge : QuittingPureTimeResetEdgeWitnessSwitch data observer quitTime charge
  mover_eq_first_or_second : edge.mover = first ∨ edge.mover = second
  squareBase_subset_edgeBase : squareBase ⊆ edge.base
  edgeBase_subset_fullSquare : edge.base ⊆ insert second (insert first squareBase)

/-- A square-localized edge witness whose two reset coordinates belong to a
set has its changed mover in that set. -/
theorem QuittingPureTimeResetSquareEdgeWitnessSwitch.mover_mem_of_mem
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    {data : QuittingStoppingLawResetCubeData reward}
    {observer : ι} {squareBase active : Finset ι} {first second : ι}
    {quitTime : Option ℕ} {charge : ℝ}
    (witness : QuittingPureTimeResetSquareEdgeWitnessSwitch data observer
      squareBase first second quitTime charge)
    (hfirst : first ∈ active) (hsecond : second ∈ active) :
    witness.edge.mover ∈ active := by
  rcases witness.mover_eq_first_or_second with h | h
  · simpa [h] using hfirst
  · simpa [h] using hsecond

/-- Propositional existence wrapper for a square-localized edge switch. -/
def HasQuittingPureTimeResetSquareEdgeWitnessSwitch
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    (data : QuittingStoppingLawResetCubeData reward)
    (observer : ι) (squareBase : Finset ι) (first second : ι)
    (quitTime : Option ℕ) (charge : ℝ) : Prop :=
  Nonempty (QuittingPureTimeResetSquareEdgeWitnessSwitch data observer
    squareBase first second quitTime charge)

/-- Propositional existence wrapper for an edge-localized switch. -/
def HasQuittingPureTimeResetEdgeWitnessSwitch
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    (data : QuittingStoppingLawResetCubeData reward)
    (observer : ι) (quitTime : Option ℕ) (charge : ℝ) : Prop :=
  Nonempty (QuittingPureTimeResetEdgeWitnessSwitch data observer quitTime charge)

private theorem hasResetSquareEdgeWitnessSwitch_of_upperToBase
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    (data : QuittingStoppingLawResetCubeData reward)
    (observer : ι) (base : Finset ι) (first second : ι)
    (hfirst : first ∉ base) (hsecond : second ∉ base)
    (hne : first ≠ second)
    (hobserverFirst : observer ≠ first)
    (hobserverSecond : observer ≠ second)
    (charge eta : ℝ)
    (switch : OrientedSupremumWitnessSwitch
      (quittingPureTimeDeviationPayoff reward
        (data.profile (insert second (insert first base))) observer)
      (quittingPureTimeDeviationPayoff reward (data.profile base) observer)
      charge eta) :
    HasQuittingPureTimeResetSquareEdgeWitnessSwitch data observer base
      first second switch.sourceWitness ((charge + eta) / 2) := by
  let sourceRegret := quittingPureTimeDeviationRegret reward
    (data.profile (insert second (insert first base))) observer
      switch.sourceWitness
  let middleRegret := quittingPureTimeDeviationRegret reward
    (data.profile (insert first base)) observer switch.sourceWitness
  let receivingRegret := quittingPureTimeDeviationRegret reward
    (data.profile base) observer switch.sourceWitness
  have htotal : charge + eta ≤ receivingRegret - sourceRegret := by
    dsimp only [sourceRegret, receivingRegret,
      quittingPureTimeDeviationRegret]
    rw [quittingContinuationBestResponseValue_eq_sSup_pureTimeDeviationPayoff,
      quittingContinuationBestResponseValue_eq_sSup_pureTimeDeviationPayoff]
    linarith [switch.receiving_regret, switch.source_approx]
  rcases half_le_one_twoStep_increment
      (charge + eta) sourceRegret middleRegret receivingRegret htotal with
    hfirstEdge | hsecondEdge
  · refine ⟨{
      edge := {
        base := insert first base
        mover := second
        mover_not_mem := by simp [hsecond, Ne.symm hne]
        observer_ne_mover := hobserverSecond
        orientation := .delete
        regret_increase := ?_
      }
      mover_eq_first_or_second := Or.inr rfl
      squareBase_subset_edgeBase := Finset.subset_insert first base
      edgeBase_subset_fullSquare := Finset.subset_insert second _
    }⟩
    simpa only [sourceRegret, middleRegret,
      quittingResetEdgeReceivingProfile, quittingResetEdgeSourceProfile] using
      hfirstEdge
  · refine ⟨{
      edge := {
        base := base
        mover := first
        mover_not_mem := hfirst
        observer_ne_mover := hobserverFirst
        orientation := .delete
        regret_increase := ?_
      }
      mover_eq_first_or_second := Or.inl rfl
      squareBase_subset_edgeBase := Finset.Subset.rfl
      edgeBase_subset_fullSquare := by
        intro who hwho
        simp [hwho]
    }⟩
    simpa only [middleRegret, receivingRegret,
      quittingResetEdgeReceivingProfile, quittingResetEdgeSourceProfile] using
      hsecondEdge

private theorem hasResetSquareEdgeWitnessSwitch_of_sideToSide
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    (data : QuittingStoppingLawResetCubeData reward)
    (observer : ι) (base : Finset ι) (first second : ι)
    (hfirst : first ∉ base) (hsecond : second ∉ base)
    (hobserverFirst : observer ≠ first)
    (hobserverSecond : observer ≠ second)
    (charge eta : ℝ)
    (switch : OrientedSupremumWitnessSwitch
      (quittingPureTimeDeviationPayoff reward
        (data.profile (insert first base)) observer)
      (quittingPureTimeDeviationPayoff reward
        (data.profile (insert second base)) observer)
      charge eta) :
    HasQuittingPureTimeResetSquareEdgeWitnessSwitch data observer base
      first second switch.sourceWitness ((charge + eta) / 2) := by
  let sourceRegret := quittingPureTimeDeviationRegret reward
    (data.profile (insert first base)) observer switch.sourceWitness
  let middleRegret := quittingPureTimeDeviationRegret reward
    (data.profile base) observer switch.sourceWitness
  let receivingRegret := quittingPureTimeDeviationRegret reward
    (data.profile (insert second base)) observer switch.sourceWitness
  have htotal : charge + eta ≤ receivingRegret - sourceRegret := by
    dsimp only [sourceRegret, receivingRegret,
      quittingPureTimeDeviationRegret]
    rw [quittingContinuationBestResponseValue_eq_sSup_pureTimeDeviationPayoff,
      quittingContinuationBestResponseValue_eq_sSup_pureTimeDeviationPayoff]
    linarith [switch.receiving_regret, switch.source_approx]
  rcases half_le_one_twoStep_increment
      (charge + eta) sourceRegret middleRegret receivingRegret htotal with
    hfirstEdge | hsecondEdge
  · refine ⟨{
      edge := {
        base := base
        mover := first
        mover_not_mem := hfirst
        observer_ne_mover := hobserverFirst
        orientation := .delete
        regret_increase := ?_
      }
      mover_eq_first_or_second := Or.inl rfl
      squareBase_subset_edgeBase := Finset.Subset.rfl
      edgeBase_subset_fullSquare := by
        intro who hwho
        simp [hwho]
    }⟩
    simpa only [sourceRegret, middleRegret,
      quittingResetEdgeReceivingProfile, quittingResetEdgeSourceProfile] using
      hfirstEdge
  · refine ⟨{
      edge := {
        base := base
        mover := second
        mover_not_mem := hsecond
        observer_ne_mover := hobserverSecond
        orientation := .insert
        regret_increase := ?_
      }
      mover_eq_first_or_second := Or.inr rfl
      squareBase_subset_edgeBase := Finset.Subset.rfl
      edgeBase_subset_fullSquare := by
        intro who hwho
        simp [hwho]
    }⟩
    simpa only [middleRegret, receivingRegret,
      quittingResetEdgeReceivingProfile, quittingResetEdgeSourceProfile] using
      hsecondEdge

/-- **Source-matched debt square to an actual edge witness switch.**

For two fresh reset coordinates in one supplied
`QuittingStoppingLawResetCubeData`, the four profiles are literal cube
vertices.  After the prescribed-payoff and fixed-witness budgets are paid, a
large debt square produces a full oriented pure-time certificate on one
diagonal.  Along a two-edge cube path from its source to receiving vertex,
one actual off-diagonal reset edge raises the selected source witness's regret
by at least `(charge + eta) / 2`.

This is a static cube certificate.  It does not make the selected edge a
chronological edge of play. -/
theorem exists_resetCubePureTimeSquareEdgeWitnessSwitch_of_abs_debtCurvature
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    (data : QuittingStoppingLawResetCubeData reward)
    (observer : ι) (base : Finset ι) (first second : ι)
    (hfirst : first ∉ base) (hsecond : second ∉ base)
    (hne : first ≠ second)
    (hobserverFirst : observer ≠ first)
    (hobserverSecond : observer ≠ second)
    (prescribedBound q charge eta : ℝ)
    (hcharge : 0 < charge) (heta : 0 < eta)
    (hprescribed :
      |quittingTerminalPayoff reward
              (data.profile (insert second (insert first base))) observer -
          quittingTerminalPayoff reward (data.profile (insert first base))
            observer -
          quittingTerminalPayoff reward (data.profile (insert second base))
            observer +
          quittingTerminalPayoff reward (data.profile base) observer| ≤
        prescribedBound)
    (hface : ∀ quitTime : Option ℕ,
      |quittingPureTimeDeviationPayoff reward
              (data.profile (insert second (insert first base))) observer
              quitTime -
          quittingPureTimeDeviationPayoff reward
              (data.profile (insert first base)) observer quitTime -
          quittingPureTimeDeviationPayoff reward
              (data.profile (insert second base)) observer quitTime +
          quittingPureTimeDeviationPayoff reward (data.profile base) observer
              quitTime| ≤ q)
    (hcurvature : charge + prescribedBound + q + 3 * eta ≤
      |quittingTerminalSemanticDebt
              (quittingTerminalSemanticPair reward
                (data.profile (insert second (insert first base)))) observer -
          quittingTerminalSemanticDebt
              (quittingTerminalSemanticPair reward
                (data.profile (insert first base))) observer -
          quittingTerminalSemanticDebt
              (quittingTerminalSemanticPair reward
                (data.profile (insert second base))) observer +
          quittingTerminalSemanticDebt
              (quittingTerminalSemanticPair reward (data.profile base))
              observer|) :
    (∃ certificate : QuittingPureTimeWitnessSwitchCertificate reward
        (data.profile (insert second (insert first base))) (data.profile base)
        observer charge eta,
      HasQuittingPureTimeResetSquareEdgeWitnessSwitch data observer base
        first second certificate.switch.sourceWitness ((charge + eta) / 2)) ∨
      (∃ certificate : QuittingPureTimeWitnessSwitchCertificate reward
          (data.profile (insert first base)) (data.profile (insert second base))
          observer charge eta,
        HasQuittingPureTimeResetSquareEdgeWitnessSwitch data observer base
          first second certificate.switch.sourceWitness
            ((charge + eta) / 2)) := by
  have hswitch :=
    exists_pureTimeWitnessSwitchCertificate_of_abs_debtCurvature reward
      (data.profile base) (data.profile (insert first base))
      (data.profile (insert second base))
      (data.profile (insert second (insert first base))) observer
      prescribedBound q charge eta hcharge heta hprescribed hface hcurvature
  rcases hswitch with hswitch | hswitch
  · rcases hswitch with ⟨certificate⟩
    exact Or.inl ⟨certificate,
      hasResetSquareEdgeWitnessSwitch_of_upperToBase data observer base first second
        hfirst hsecond hne hobserverFirst hobserverSecond charge eta
          certificate.switch⟩
  · rcases hswitch with ⟨certificate⟩
    exact Or.inr ⟨certificate,
      hasResetSquareEdgeWitnessSwitch_of_sideToSide data observer base first second
        hfirst hsecond hobserverFirst hobserverSecond charge eta
          certificate.switch⟩

end GameTheory
