/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticSimultaneousResetOrientationLocalization
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticStoppingLawResetCube

/-!
# Orientation routing for stopping-law reset cubes

A common-scale family of stopping-law replacements is simultaneously:

* a literal Boolean reset cube, whose common-source/path discrepancy is either
  small or localized to a signed two-reset square; and
* a simultaneous reset family, whose loss of an active unilateral debt
  orientation is localized to an actual debt recipient or a positive-slope
  terminal atom.

This module composes those two exact alternatives. It also exposes a typed
routing theorem: a chronological rotor or reprojection consumer receives only
the near-return branch, while a nonlinear consumer receives the signed square
together with the simultaneous-reset orientation certificate.

No chronological compiler is asserted here. Supplying the near-return
consumer remains a separate semantic obligation.
-/

noncomputable section

namespace GameTheory

open Math.Finset
open Math.Finset.CubicalResetIntegrability

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- The literal reset cube generated by one profile, one replacement for each
player, and one common stopping-law scale. -/
def quittingCommonScaleStoppingLawResetCubeData
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    (replacement : ∀ who, (quittingGame reward).BehaviorStrategy who)
    (lambda : ℝ) (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) :
    QuittingStoppingLawResetCubeData reward where
  source := profile
  target := replacement
  scale := fun _who ↦ lambda
  scale_nonneg := fun _who ↦ hlambda0
  scale_le_one := fun _who ↦ hlambda1

/-- The common-scale cube vertex is exactly the existing simultaneous-subset
stopping-law profile. -/
theorem quittingCommonScaleStoppingLawResetCubeData_profile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    (replacement : ∀ who, (quittingGame reward).BehaviorStrategy who)
    (lambda : ℝ) (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1)
    (moved : Finset ι) :
    (quittingCommonScaleStoppingLawResetCubeData reward profile replacement
      lambda hlambda0 hlambda1).profile moved =
        quittingStoppingLawMixtureSubsetProfile reward profile replacement
          lambda hlambda0 hlambda1 moved := by
  funext who
  by_cases hwho : who ∈ moved
  · simp [QuittingStoppingLawResetCubeData.profile,
      quittingCommonScaleStoppingLawResetCubeData,
      quittingStoppingLawMixtureSubsetProfile, hwho]
  · simp [QuittingStoppingLawResetCubeData.profile,
      quittingCommonScaleStoppingLawResetCubeData,
      quittingStoppingLawMixtureSubsetProfile, hwho]

/-- The game-facing orientation output attached to one active member of a
flat simultaneous stopping-law reset. -/
def HasQuittingStoppingLawResetOrientationAlternative
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    (replacement : ∀ who, (quittingGame reward).BehaviorStrategy who)
    (who : ι) (lambda : ℝ)
    (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) : Prop :=
  let source := quittingTerminalSemanticPair reward profile
  let simultaneousProfile :=
    quittingSimultaneousStoppingLawMixtureProfile reward profile replacement
      lambda hlambda0 hlambda1
  let simultaneousTarget :=
    quittingTerminalSemanticPair reward simultaneousProfile
  let endpointProfile := Function.update profile who (replacement who)
  let gain := quittingTerminalPayoff reward endpointProfile who -
    quittingTerminalPayoff reward profile who
  let opponents := Finset.univ.erase who
  let charge := gain / (2 * (opponents.card : ℝ))
  ((quittingTerminalSemanticDebt simultaneousTarget who ≤
        quittingTerminalSemanticDebt source who - lambda * gain / 2) ∧
      ∃ recipient ∈ opponents,
        lambda * charge ≤
          quittingTerminalSemanticDebtChange source simultaneousTarget
            recipient) ∨
    ∃ moved ⊆ opponents, ∃ mover ∈ opponents, mover ∉ moved ∧
      let edgeSource := quittingStoppingLawMixtureHybridProfile reward profile
        replacement who lambda hlambda0 hlambda1 moved
      let edgeTarget := quittingStoppingLawMixtureHybridProfile reward profile
        replacement who lambda hlambda0 hlambda1
          (insert mover moved)
      lambda * charge ≤
          quittingTerminalSemanticDebt
              (quittingTerminalSemanticPair reward edgeTarget) who -
            quittingTerminalSemanticDebt
              (quittingTerminalSemanticPair reward edgeSource) who ∧
        HasQuittingStoppingLawPositiveSlopeAtom reward edgeSource mover who
          (replacement mover) charge

/-- The simultaneous-reset localization theorem, packaged as the reusable
orientation output above. -/
theorem hasQuittingStoppingLawResetOrientationAlternative_of_activePassport_flat
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    (replacement : ∀ who, (quittingGame reward).BehaviorStrategy who)
    (who : ι) (terminal : {S : Finset ι // S.Nonempty}) (cutoff : ℕ)
    (lambda : ℝ) (hlambda0 : 0 < lambda) (hlambda1 : lambda ≤ 1)
    (hpassport : IsQuittingStoppingLawMinimumResetPassport reward profile who
      (replacement who) terminal cutoff)
    (hflat : quittingTerminalSemanticDebtSum
        (quittingTerminalSemanticPair reward
          (quittingSimultaneousStoppingLawMixtureProfile reward profile
            replacement lambda hlambda0.le hlambda1)) =
      quittingTerminalSemanticDebtSum
        (quittingTerminalSemanticPair reward profile)) :
    HasQuittingStoppingLawResetOrientationAlternative reward profile
      replacement who lambda hlambda0.le hlambda1 := by
  simpa only [HasQuittingStoppingLawResetOrientationAlternative] using
    activePassport_flatSimultaneous_directed_or_localizedPositiveSlope
      reward profile replacement who terminal cutoff lambda hlambda0 hlambda1
        hpassport hflat

/-- **Near return or signed curvature with an oriented semantic consumer.**

For the active player's debt observable, failure of the quantitative reset
return produces a signed two-reset square and, simultaneously, the existing
recipient-or-positive-slope orientation certificate. -/
theorem terminalSemanticDebt_resetCube_nearReturn_or_curvatureWithOrientation
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    (replacement : ∀ who, (quittingGame reward).BehaviorStrategy who)
    (who : ι) (terminal : {S : Finset ι // S.Nonempty}) (cutoff : ℕ)
    (lambda : ℝ) (hlambda0 : 0 < lambda) (hlambda1 : lambda ≤ 1)
    (word : List ι) (threshold : ℝ) (hthreshold : 0 ≤ threshold)
    (hpassport : IsQuittingStoppingLawMinimumResetPassport reward profile who
      (replacement who) terminal cutoff)
    (hflat : quittingTerminalSemanticDebtSum
        (quittingTerminalSemanticPair reward
          (quittingSimultaneousStoppingLawMixtureProfile reward profile
            replacement lambda hlambda0.le hlambda1)) =
      quittingTerminalSemanticDebtSum
        (quittingTerminalSemanticPair reward profile)) :
    let data := quittingCommonScaleStoppingLawResetCubeData reward profile
      replacement lambda hlambda0.le hlambda1
    let debt := fun candidate : (quittingGame reward).BehaviorProfile ↦
      quittingTerminalSemanticDebt
        (quittingTerminalSemanticPair reward candidate) who
    let nearReturn :=
      |data.value debt (finalSet ∅ word) - data.value debt ∅ -
          frozenEdgeSum (data.value debt) ∅ word| ≤
        (squareCount word : ℝ) * threshold
    let signedCurvature :=
      HasSquareAboveAlong (data.value debt) threshold ∅ word ∨
        HasSquareAboveAlong (fun reset ↦ -data.value debt reset)
          threshold ∅ word
    nearReturn ∨
      signedCurvature ∧
        HasQuittingStoppingLawResetOrientationAlternative reward profile
          replacement who lambda hlambda0.le hlambda1 := by
  dsimp only
  let data := quittingCommonScaleStoppingLawResetCubeData reward profile
    replacement lambda hlambda0.le hlambda1
  let debt := fun candidate : (quittingGame reward).BehaviorProfile ↦
    quittingTerminalSemanticDebt
      (quittingTerminalSemanticPair reward candidate) who
  have hcube := data.nearFrozenReturn_or_signedSquareAbove
    debt ∅ word threshold hthreshold
  have horientation :=
    hasQuittingStoppingLawResetOrientationAlternative_of_activePassport_flat
      reward profile replacement who terminal cutoff lambda hlambda0 hlambda1
        hpassport hflat
  rcases hcube with hnear | hpositive | hnegative
  · exact Or.inl hnear
  · exact Or.inr ⟨Or.inl hpositive, horientation⟩
  · exact Or.inr ⟨Or.inr hnegative, horientation⟩

/-- **Typed consumer routing.** A near-return consumer—such as a rotor or
carrier reprojection compiler—can only be invoked after receiving the literal
near-return estimate. The nonlinear consumer receives both the signed square
and the game-facing orientation certificate. -/
theorem terminalSemanticDebt_resetCube_routeNearReturnConsumer
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    (replacement : ∀ who, (quittingGame reward).BehaviorStrategy who)
    (who : ι) (terminal : {S : Finset ι // S.Nonempty}) (cutoff : ℕ)
    (lambda : ℝ) (hlambda0 : 0 < lambda) (hlambda1 : lambda ≤ 1)
    (word : List ι) (threshold : ℝ) (hthreshold : 0 ≤ threshold)
    (hpassport : IsQuittingStoppingLawMinimumResetPassport reward profile who
      (replacement who) terminal cutoff)
    (hflat : quittingTerminalSemanticDebtSum
        (quittingTerminalSemanticPair reward
          (quittingSimultaneousStoppingLawMixtureProfile reward profile
            replacement lambda hlambda0.le hlambda1)) =
      quittingTerminalSemanticDebtSum
        (quittingTerminalSemanticPair reward profile))
    (NearResult CurvatureResult : Prop)
    (nearConsumer :
      let data := quittingCommonScaleStoppingLawResetCubeData reward profile
        replacement lambda hlambda0.le hlambda1
      let debt := fun candidate : (quittingGame reward).BehaviorProfile ↦
        quittingTerminalSemanticDebt
          (quittingTerminalSemanticPair reward candidate) who
      |data.value debt (finalSet ∅ word) - data.value debt ∅ -
          frozenEdgeSum (data.value debt) ∅ word| ≤
          (squareCount word : ℝ) * threshold → NearResult)
    (curvatureConsumer :
      let data := quittingCommonScaleStoppingLawResetCubeData reward profile
        replacement lambda hlambda0.le hlambda1
      let debt := fun candidate : (quittingGame reward).BehaviorProfile ↦
        quittingTerminalSemanticDebt
          (quittingTerminalSemanticPair reward candidate) who
      (HasSquareAboveAlong (data.value debt) threshold ∅ word ∨
          HasSquareAboveAlong (fun reset ↦ -data.value debt reset)
            threshold ∅ word) →
        HasQuittingStoppingLawResetOrientationAlternative reward profile
          replacement who lambda hlambda0.le hlambda1 → CurvatureResult) :
    NearResult ∨ CurvatureResult := by
  have hroute :=
    terminalSemanticDebt_resetCube_nearReturn_or_curvatureWithOrientation
      reward profile replacement who terminal cutoff lambda hlambda0 hlambda1
        word threshold hthreshold hpassport hflat
  rcases hroute with hnear | ⟨hcurvature, horientation⟩
  · exact Or.inl (nearConsumer hnear)
  · exact Or.inr (curvatureConsumer hcurvature horientation)

end GameTheory
