/-
Copyright (c) 2025 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.ProofView.Concepts.Mixed.MixedExtension
import UniformEquilibrium.ProofView.Concepts.Potential.PotentialGame
import UniformEquilibrium.ProofView.Concepts.Potential.PotentialTeam
import UniformEquilibrium.ProofView.Concepts.Classes.TeamGame

/-!
# Mixed extensions of potential games

This file contains the reusable Monderer-Shapley infrastructure: the expected
extension of an exact potential is an exact potential for the mixed extension.
It also packages the finite-outcome identical-interest game generated by a
potential and proves the corresponding best-response equivalence.
-/

noncomputable section

open scoped BigOperators

namespace GameTheory

open Math.Probability
open Math.PMFProduct

namespace KernelGame

variable {ι : Type}

/-- The multilinear/expected extension of a pure-profile potential. -/
def mixedPotential [Fintype ι] (G : KernelGame ι) (Φ : Profile G → ℝ)
    (σ : ∀ i, PMF (G.Strategy i)) : ℝ :=
  expect (pmfPi (A := G.Strategy) σ) Φ

open Classical in
/-- Integrating a function after a pure coordinate update can be moved from the
product distribution to the integrand. -/
theorem expect_pmfPi_update_pure [DecidableEq ι] [Fintype ι]
    {A : ι → Type*} [∀ i, Finite (A i)]
    (σ : ∀ i, PMF (A i)) (j : ι) (a : A j)
    (f : (∀ i, A i) → ℝ) :
    expect (pmfPi (A := A) (Function.update σ j (PMF.pure a))) f =
      expect (pmfPi (A := A) σ) (fun s => f (Function.update s j a)) := by
  letI (i : ι) : Fintype (A i) := Fintype.ofFinite (A i)
  rw [← pmfPi_bind_update_pure (A := A) σ j a]
  rw [expect_bind]
  simp

open Classical in
/-- The expected potential after a unilateral mixed update is the updating
player's expectation of the corresponding pure-update expected potentials. -/
theorem mixedPotential_update [DecidableEq ι] [Fintype ι]
    (G : KernelGame ι) [∀ i, Finite (G.Strategy i)] (Φ : Profile G → ℝ)
    (σ : ∀ i, PMF (G.Strategy i)) (who : ι) (τ : PMF (G.Strategy who)) :
    G.mixedPotential Φ (Function.update σ who τ) =
      expect τ (fun a => G.mixedPotential Φ (Function.update σ who (PMF.pure a))) := by
  letI (i : ι) : Fintype (G.Strategy i) := Fintype.ofFinite (G.Strategy i)
  unfold mixedPotential
  rw [pmfPi_update_bind]
  rw [expect_bind]

open Classical in
/-- Pure unilateral deviations in the mixed extension change expected utility by
exactly the same amount as they change the expected potential. -/
theorem IsExactPotential.mixedExtension_pure_diff
    [DecidableEq ι] [Fintype ι]
    {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    (σ : ∀ i, PMF (G.Strategy i)) (who : ι) (a : G.Strategy who) :
    G.mixedExtension.eu (Function.update σ who (PMF.pure a)) who -
        G.mixedExtension.eu σ who =
      G.mixedPotential Φ (Function.update σ who (PMF.pure a)) -
        G.mixedPotential Φ σ := by
  have heu_update :
      G.mixedExtension.eu (Function.update σ who (PMF.pure a)) who =
        expect (pmfPi (A := G.Strategy) (Function.update σ who (PMF.pure a)))
          (fun s : Profile G => G.eu s who) :=
    G.mixedExtension_eu (Function.update σ who (PMF.pure a)) who
  have heu_base :
      G.mixedExtension.eu σ who =
        expect (pmfPi (A := G.Strategy) σ) (fun s : Profile G => G.eu s who) :=
    G.mixedExtension_eu σ who
  rw [heu_update, heu_base]
  unfold mixedPotential
  rw [expect_pmfPi_update_pure (A := G.Strategy) σ who a
    (fun s : Profile G => G.eu s who)]
  rw [expect_pmfPi_update_pure (A := G.Strategy) σ who a Φ]
  rw [← expect_sub, ← expect_sub]
  exact congrArg (fun f => expect (pmfPi (A := G.Strategy) σ) f)
    (funext fun s => hΦ who s a)

open Classical in
/-- The mixed extension of an exact-potential game is again an exact-potential
game, with potential given by the expected extension of the original potential.

This is the main reusable Monderer-Shapley bridge. -/
theorem IsExactPotential.mixedExtension_isExactPotential
    [DecidableEq ι] [Fintype ι]
    {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ) :
    G.mixedExtension.IsExactPotential (G.mixedPotential Φ) := by
  intro who σ τ
  change
    G.mixedExtension.eu
        (Function.update (σ : ∀ i, PMF (G.Strategy i)) who (τ : PMF (G.Strategy who))) who -
        G.mixedExtension.eu (σ : ∀ i, PMF (G.Strategy i)) who =
      G.mixedPotential Φ
        (Function.update (σ : ∀ i, PMF (G.Strategy i)) who (τ : PMF (G.Strategy who))) -
        G.mixedPotential Φ (σ : ∀ i, PMF (G.Strategy i))
  have heu := G.mixedExtension_eu_update σ who τ
  have hpot := G.mixedPotential_update Φ σ who τ
  rw [heu, hpot]
  calc
    expect τ
        (fun a =>
          G.mixedExtension.eu (Function.update σ who (PMF.pure a)) who) -
        G.mixedExtension.eu σ who
        =
      expect τ
        (fun a =>
          G.mixedExtension.eu (Function.update σ who (PMF.pure a)) who -
            G.mixedExtension.eu σ who) := by
          rw [expect_sub, expect_const]
    _ =
      expect τ
        (fun a =>
          G.mixedPotential Φ (Function.update σ who (PMF.pure a)) -
            G.mixedPotential Φ σ) := by
          exact congrArg (fun f => expect τ f)
            (funext fun a => hΦ.mixedExtension_pure_diff σ who a)
    _ =
      expect τ
        (fun a => G.mixedPotential Φ (Function.update σ who (PMF.pure a))) -
        G.mixedPotential Φ σ := by
          rw [expect_sub, expect_const]

open Classical in
/-- Pure unilateral deviations in the mixed extension of a weighted-potential
game change expected utility by the player's positive weight times the expected
potential change. -/
theorem IsWeightedExactPotential.mixedExtension_pure_diff
    [DecidableEq ι] [Fintype ι]
    {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} {w : ι → ℝ} (hΦ : G.IsWeightedExactPotential Φ w)
    (σ : ∀ i, PMF (G.Strategy i)) (who : ι) (a : G.Strategy who) :
    G.mixedExtension.eu (Function.update σ who (PMF.pure a)) who -
        G.mixedExtension.eu σ who =
      w who * (G.mixedPotential Φ (Function.update σ who (PMF.pure a)) -
        G.mixedPotential Φ σ) := by
  have heu_update :
      G.mixedExtension.eu (Function.update σ who (PMF.pure a)) who =
        expect (pmfPi (A := G.Strategy) (Function.update σ who (PMF.pure a)))
          (fun s : Profile G => G.eu s who) :=
    G.mixedExtension_eu (Function.update σ who (PMF.pure a)) who
  have heu_base :
      G.mixedExtension.eu σ who =
        expect (pmfPi (A := G.Strategy) σ) (fun s : Profile G => G.eu s who) :=
    G.mixedExtension_eu σ who
  rw [heu_update, heu_base]
  unfold mixedPotential
  rw [expect_pmfPi_update_pure (A := G.Strategy) σ who a
    (fun s : Profile G => G.eu s who)]
  rw [expect_pmfPi_update_pure (A := G.Strategy) σ who a Φ]
  rw [← expect_sub, ← expect_sub]
  rw [← expect_const_mul]
  exact congrArg (fun f => expect (pmfPi (A := G.Strategy) σ) f)
    (funext fun s => hΦ.2 who s a)

open Classical in
/-- Mixed unilateral deviations in the mixed extension of a weighted-potential
game change expected utility by the player's positive weight times the expected
potential change. -/
theorem IsWeightedExactPotential.mixedExtension_update_diff
    [DecidableEq ι] [Fintype ι]
    {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} {w : ι → ℝ} (hΦ : G.IsWeightedExactPotential Φ w)
    (σ : ∀ i, PMF (G.Strategy i)) (who : ι) (τ : PMF (G.Strategy who)) :
    G.mixedExtension.eu (Function.update σ who τ) who -
        G.mixedExtension.eu σ who =
      w who * (G.mixedPotential Φ (Function.update σ who τ) -
        G.mixedPotential Φ σ) := by
  have heu := G.mixedExtension_eu_update σ who τ
  have hpot := G.mixedPotential_update Φ σ who τ
  rw [heu, hpot]
  calc
    expect τ
        (fun a =>
          G.mixedExtension.eu (Function.update σ who (PMF.pure a)) who) -
        G.mixedExtension.eu σ who
        =
      expect τ
        (fun a =>
          G.mixedExtension.eu (Function.update σ who (PMF.pure a)) who -
            G.mixedExtension.eu σ who) := by
          rw [expect_sub, expect_const]
    _ =
      expect τ
        (fun a =>
          w who * (G.mixedPotential Φ (Function.update σ who (PMF.pure a)) -
            G.mixedPotential Φ σ)) := by
          exact congrArg (fun f => expect τ f)
            (funext fun a => hΦ.mixedExtension_pure_diff σ who a)
    _ =
      w who *
        expect τ
          (fun a =>
            G.mixedPotential Φ (Function.update σ who (PMF.pure a)) -
              G.mixedPotential Φ σ) := by
          rw [expect_const_mul]
    _ =
      w who * (expect τ
        (fun a => G.mixedPotential Φ (Function.update σ who (PMF.pure a))) -
          G.mixedPotential Φ σ) := by
          rw [expect_sub, expect_const]

/-- A finite-outcome identical-interest game generated by a potential `Φ`.

The outcome type is the pure-profile type, so it is finite whenever the pure
strategy spaces are finite. Its mixed extension has expected utility equal to
`G.mixedPotential Φ`. -/
def finitePotentialTeamGame (G : KernelGame ι) (Φ : Profile G → ℝ) : KernelGame ι where
  Strategy := G.Strategy
  Outcome := Profile G
  utility := fun s _ => Φ s
  outcomeKernel := fun σ => PMF.pure σ

@[simp] theorem finitePotentialTeamGame_Strategy (G : KernelGame ι) (Φ : Profile G → ℝ) :
    (G.finitePotentialTeamGame Φ).Strategy = G.Strategy := rfl

@[simp] theorem finitePotentialTeamGame_utility (G : KernelGame ι) (Φ : Profile G → ℝ)
    (s : Profile G) (i : ι) :
    (G.finitePotentialTeamGame Φ).utility s i = Φ s := rfl

@[simp] theorem finitePotentialTeamGame_outcomeKernel (G : KernelGame ι) (Φ : Profile G → ℝ)
    (σ : Profile G) :
    (G.finitePotentialTeamGame Φ).outcomeKernel σ = PMF.pure σ := rfl

/-- The finite potential-generated game is an identical-interest/team game. -/
theorem finitePotentialTeamGame_isTeamGame (G : KernelGame ι) (Φ : Profile G → ℝ) :
    (G.finitePotentialTeamGame Φ).IsTeamGame := by
  intro s i j
  rfl

@[simp] theorem finitePotentialTeamGame_eu (G : KernelGame ι) (Φ : Profile G → ℝ)
    (σ : Profile G) (who : ι) :
    (G.finitePotentialTeamGame Φ).eu σ who = Φ σ := by
  simp [KernelGame.eu, finitePotentialTeamGame]

open Classical in
/-- The mixed extension of the finite potential-generated team game has
expected utility equal to the expected/multilinear potential of `G`. -/
theorem finitePotentialTeamGame_mixedExtension_eu [Fintype ι] (G : KernelGame ι)
    [∀ i, Finite (G.Strategy i)] (Φ : Profile G → ℝ)
    (σ : ∀ i, PMF (G.Strategy i)) (who : ι) :
    (G.finitePotentialTeamGame Φ).mixedExtension.eu σ who =
      G.mixedPotential Φ σ := by
  letI (i : ι) : Fintype (G.Strategy i) := Fintype.ofFinite (G.Strategy i)
  unfold KernelGame.eu KernelGame.mixedExtension mixedPotential finitePotentialTeamGame
  change expect ((pmfPi (A := G.Strategy) σ).bind PMF.pure) Φ =
    expect (pmfPi (A := G.Strategy) σ) Φ
  rw [PMF.bind_pure]

open Classical in
/-- Version of `finitePotentialTeamGame_mixedExtension_eu` stated over the
finite potential team's own mixed-profile type. This is convenient after
`Function.update` has fixed that type. -/
theorem finitePotentialTeamGame_mixedExtension_eu_self [Fintype ι] (G : KernelGame ι)
    [∀ i, Finite (G.Strategy i)] (Φ : Profile G → ℝ)
    (σ : ∀ i, PMF ((G.finitePotentialTeamGame Φ).Strategy i)) (who : ι) :
    (G.finitePotentialTeamGame Φ).mixedExtension.eu σ who =
      G.mixedPotential Φ σ := by
  exact G.finitePotentialTeamGame_mixedExtension_eu Φ σ who

/-- The finite potential-generated team game is itself an exact-potential game,
with the original potential as potential function. -/
theorem finitePotentialTeamGame_isExactPotential [DecidableEq ι] (G : KernelGame ι)
    (Φ : Profile G → ℝ) :
    (G.finitePotentialTeamGame Φ).IsExactPotential Φ := by
  intro who σ s'
  simp [finitePotentialTeamGame_eu]

open Classical in
/-- Weighted exact potentials preserve unilateral mixed-deviation comparisons
after passing to the mixed extension and replacing the game by the finite
potential-generated identical-interest game. -/
theorem IsWeightedExactPotential.mixedExtension_le_iff_finitePotentialTeamGame
    [DecidableEq ι] [Fintype ι]
    {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} {w : ι → ℝ} (hΦ : G.IsWeightedExactPotential Φ w)
    (σ : ∀ i, PMF (G.Strategy i)) (who : ι)
    (τ₁ τ₂ : PMF (G.Strategy who)) :
    G.mixedExtension.eu (Function.update σ who τ₁) who ≤
        G.mixedExtension.eu (Function.update σ who τ₂) who ↔
      (G.finitePotentialTeamGame Φ).mixedExtension.eu (Function.update σ who τ₁) who ≤
        (G.finitePotentialTeamGame Φ).mixedExtension.eu
          (Function.update σ who τ₂) who := by
  have hτ₁ := hΦ.mixedExtension_update_diff σ who τ₁
  have hτ₂ := hΦ.mixedExtension_update_diff σ who τ₂
  have hteam₁ :
      (G.finitePotentialTeamGame Φ).mixedExtension.eu (Function.update σ who τ₁) who =
        G.mixedPotential Φ (Function.update σ who τ₁) :=
    G.finitePotentialTeamGame_mixedExtension_eu Φ (Function.update σ who τ₁) who
  have hteam₂ :
      (G.finitePotentialTeamGame Φ).mixedExtension.eu (Function.update σ who τ₂) who =
        G.mixedPotential Φ (Function.update σ who τ₂) :=
    G.finitePotentialTeamGame_mixedExtension_eu Φ (Function.update σ who τ₂) who
  have hdiff :
      G.mixedExtension.eu (Function.update σ who τ₁) who -
          G.mixedExtension.eu (Function.update σ who τ₂) who =
        w who *
          (G.mixedPotential Φ (Function.update σ who τ₁) -
            G.mixedPotential Φ (Function.update σ who τ₂)) := by
    calc
      G.mixedExtension.eu (Function.update σ who τ₁) who -
          G.mixedExtension.eu (Function.update σ who τ₂) who
          =
        (G.mixedExtension.eu (Function.update σ who τ₁) who -
            G.mixedExtension.eu σ who) -
          (G.mixedExtension.eu (Function.update σ who τ₂) who -
            G.mixedExtension.eu σ who) := by ring
      _ =
        w who * (G.mixedPotential Φ (Function.update σ who τ₁) -
            G.mixedPotential Φ σ) -
          w who * (G.mixedPotential Φ (Function.update σ who τ₂) -
            G.mixedPotential Φ σ) := by
              rw [hτ₁, hτ₂]
      _ =
        w who *
          (G.mixedPotential Φ (Function.update σ who τ₁) -
            G.mixedPotential Φ (Function.update σ who τ₂)) := by ring
  rw [hteam₁, hteam₂]
  constructor
  · intro h
    have heu_sub :
        G.mixedExtension.eu (Function.update σ who τ₁) who -
            G.mixedExtension.eu (Function.update σ who τ₂) who ≤ 0 :=
      sub_nonpos.mpr h
    have hscaled :
        w who *
          (G.mixedPotential Φ (Function.update σ who τ₁) -
            G.mixedPotential Φ (Function.update σ who τ₂)) ≤ 0 := by
      rwa [hdiff] at heu_sub
    have hpot_sub :
        G.mixedPotential Φ (Function.update σ who τ₁) -
            G.mixedPotential Φ (Function.update σ who τ₂) ≤ 0 := by
      let X : ℝ :=
        G.mixedPotential Φ (Function.update σ who τ₁) -
          G.mixedPotential Φ (Function.update σ who τ₂)
      have hinv_nonneg : 0 ≤ (w who)⁻¹ := inv_nonneg.mpr (hΦ.1 who).le
      have h := mul_le_mul_of_nonneg_left hscaled hinv_nonneg
      change (w who)⁻¹ * (w who * X) ≤ (w who)⁻¹ * 0 at h
      change X ≤ 0
      calc
        X = (w who)⁻¹ * (w who * X) := by
          rw [← mul_assoc, inv_mul_cancel₀ (hΦ.1 who).ne', one_mul]
        _ ≤ (w who)⁻¹ * 0 := h
        _ = 0 := by rw [mul_zero]
    exact sub_nonpos.mp hpot_sub
  · intro h
    have hpot_sub :
        G.mixedPotential Φ (Function.update σ who τ₁) -
            G.mixedPotential Φ (Function.update σ who τ₂) ≤ 0 :=
      sub_nonpos.mpr h
    have heu_sub :
        G.mixedExtension.eu (Function.update σ who τ₁) who -
            G.mixedExtension.eu (Function.update σ who τ₂) who ≤ 0 := by
      rw [hdiff]
      exact mul_nonpos_of_nonneg_of_nonpos (hΦ.1 who).le hpot_sub
    exact sub_nonpos.mp heu_sub

open Classical in
/-- Weighted exact potentials preserve best-response correspondences after
passing to the mixed extension and replacing the game by the finite
potential-generated identical-interest game. -/
theorem IsWeightedExactPotential.mixedExtension_isBestResponse_iff_finitePotentialTeamGame
    [DecidableEq ι] [Fintype ι]
    {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} {w : ι → ℝ} (hΦ : G.IsWeightedExactPotential Φ w)
    (σ : ∀ i, PMF (G.Strategy i)) (who : ι) (τ : PMF (G.Strategy who)) :
    G.mixedExtension.IsBestResponse who σ τ ↔
      (G.finitePotentialTeamGame Φ).mixedExtension.IsBestResponse who σ τ := by
  constructor
  · intro h τ'
    exact (hΦ.mixedExtension_le_iff_finitePotentialTeamGame σ who τ' τ).mp (h τ')
  · intro h τ'
    exact (hΦ.mixedExtension_le_iff_finitePotentialTeamGame σ who τ' τ).mpr (h τ')

open Classical in
/-- Exact potentials preserve unilateral mixed-deviation comparisons after
passing to the mixed extension and replacing the game by the finite
potential-generated identical-interest game. -/
theorem IsExactPotential.mixedExtension_le_iff_finitePotentialTeamGame
    [DecidableEq ι] [Fintype ι]
    {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    (σ : ∀ i, PMF (G.Strategy i)) (who : ι)
    (τ₁ τ₂ : PMF (G.Strategy who)) :
    G.mixedExtension.eu (Function.update σ who τ₁) who ≤
        G.mixedExtension.eu (Function.update σ who τ₂) who ↔
      (G.finitePotentialTeamGame Φ).mixedExtension.eu (Function.update σ who τ₁) who ≤
        (G.finitePotentialTeamGame Φ).mixedExtension.eu
          (Function.update σ who τ₂) who :=
  hΦ.toWeightedExactPotential.mixedExtension_le_iff_finitePotentialTeamGame
    σ who τ₁ τ₂

open Classical in
/-- Exact potentials preserve best-response correspondences after passing to
the mixed extension and replacing the game by the finite potential-generated
identical-interest game. -/
theorem IsExactPotential.mixedExtension_isBestResponse_iff_finitePotentialTeamGame
    [DecidableEq ι] [Fintype ι]
    {G : KernelGame ι} [∀ i, Finite (G.Strategy i)] [Finite G.Outcome]
    {Φ : Profile G → ℝ} (hΦ : G.IsExactPotential Φ)
    (σ : ∀ i, PMF (G.Strategy i)) (who : ι) (τ : PMF (G.Strategy who)) :
    G.mixedExtension.IsBestResponse who σ τ ↔
      (G.finitePotentialTeamGame Φ).mixedExtension.IsBestResponse who σ τ :=
  hΦ.toWeightedExactPotential.mixedExtension_isBestResponse_iff_finitePotentialTeamGame
    σ who τ

/-- Mixed extensions preserve identical interests, since the mixed extension
does not change the outcome utility function. -/
theorem IsTeamGame.mixedExtension [Fintype ι] {G : KernelGame ι} (hteam : G.IsTeamGame) :
    G.mixedExtension.IsTeamGame := by
  intro ω i j
  exact hteam ω i j

/-- A team game's mixed extension is an exact-potential game, with potential
given by any fixed player's mixed-extension expected utility. -/
theorem IsTeamGame.mixedExtension_isExactPotential
    [DecidableEq ι] [Fintype ι] {G : KernelGame ι} (hteam : G.IsTeamGame) (i₀ : ι) :
    G.mixedExtension.IsExactPotential (fun σ => G.mixedExtension.eu σ i₀) := by
  intro who σ τ
  have h1 := hteam.mixedExtension.eu_eq (Function.update σ who τ) who i₀
  have h2 := hteam.mixedExtension.eu_eq σ who i₀
  linarith

end KernelGame

end GameTheory
