/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import Mathlib.RingTheory.Finiteness.Cofinite
import Mathlib.RingTheory.Finiteness.NilpotentKer
import Mathlib.RingTheory.Ideal.Quotient.Noetherian
import Mathlib.RingTheory.PrincipalIdealDomain

/-!
# Finite-dimensional quotients of product-generated ideals

This module reduces finite-dimensionality of an ideal generated by
coordinatewise products to finite-dimensionality of the finitely many ideals
obtained by selecting one factor in each coordinate.

The proof intersects all selection ideals. The product-generated ideal is
contained in that intersection. Conversely, the intersection lies in its
radical: a prime containing every coordinatewise product contains a selected
factor at every coordinate. The induced quotient map therefore has nilpotent
kernel.

## Main declaration

* `moduleFinite_quotient_span_range_prod_of_branches`: finite-dimensional
  selection quotients imply a finite-dimensional product-generated quotient.
-/

noncomputable section

namespace Math
namespace CofiniteIdeal

/-- The quotient by the unit ideal is finite-dimensional over any field. -/
theorem moduleFinite_quotient_top
    {K A : Type*} [Field K] [CommRing A] [Algebra K A] :
    Module.Finite K (A ⧸ (⊤ : Ideal A)) := by
  refine ⟨?_⟩
  rw [Subsingleton.elim
    (⊤ : Submodule K (A ⧸ (⊤ : Ideal A))) ⊥]
  exact Submodule.fg_bot

/-- Finite-dimensional quotients over a field are closed under intersection
of two ideals. -/
theorem moduleFinite_quotient_inf
    {K A : Type*} [Field K] [CommRing A] [Algebra K A]
    (I J : Ideal A)
    [Module.Finite K (A ⧸ I)]
    [Module.Finite K (A ⧸ J)] :
    Module.Finite K (A ⧸ I ⊓ J) := by
  have hI : (I.restrictScalars K).CoFG :=
    Module.Finite.equiv
      (Submodule.Quotient.restrictScalarsEquiv K I).symm
  have hJ : (J.restrictScalars K).CoFG :=
    Module.Finite.equiv
      (Submodule.Quotient.restrictScalarsEquiv K J).symm
  have htarget : ((I ⊓ J).restrictScalars K).CoFG := by
    rw [Submodule.restrictScalars_inf]
    exact hI.inf hJ
  exact Module.Finite.equiv
    (Submodule.Quotient.restrictScalarsEquiv K (I ⊓ J))

/-- Finite-dimensional quotients over a field are closed under finite
intersections of ideals. -/
theorem moduleFinite_quotient_finset_inf
    {K A ι : Type*} [Field K] [CommRing A] [Algebra K A]
    (S : Finset ι) (I : ι → Ideal A)
    (hI : ∀ i ∈ S, Module.Finite K (A ⧸ I i)) :
    Module.Finite K (A ⧸ S.inf I) := by
  classical
  induction S using Finset.induction with
  | empty =>
      rw [Finset.inf_empty]
      exact moduleFinite_quotient_top
  | @insert i S hi ih =>
      rw [Finset.inf_insert]
      letI : Module.Finite K (A ⧸ I i) :=
        hI i (Finset.mem_insert_self i S)
      letI : Module.Finite K (A ⧸ S.inf I) :=
        ih fun j hj => hI j (Finset.mem_insert_of_mem hj)
      exact moduleFinite_quotient_inf (I i) (S.inf I)

/-- If every ideal obtained by selecting one generator at each coordinate has
a finite-dimensional quotient, then so does the ideal generated by the
coordinatewise products of all choices. -/
theorem moduleFinite_quotient_span_range_prod_of_branches
    {K A σ τ : Type*} [Field K] [CommRing A] [Algebra K A]
    [IsNoetherianRing A] [Finite σ] [Fintype τ]
    (f : σ → τ → A)
    (hbranch : ∀ c : σ → τ,
      Module.Finite K
        (A ⧸ Ideal.span (Set.range fun s => f s (c s)))) :
    Module.Finite K
      (A ⧸ Ideal.span (Set.range fun s => ∏ k, f s k)) := by
  classical
  letI : Fintype σ := Fintype.ofFinite σ
  let B : (σ → τ) → Ideal A :=
    fun c => Ideal.span (Set.range fun s => f s (c s))
  let J : Ideal A :=
    Ideal.span (Set.range fun s => ∏ k, f s k)
  let Q : Ideal A := Finset.univ.inf B
  have hQfinite : Module.Finite K (A ⧸ Q) := by
    apply moduleFinite_quotient_finset_inf Finset.univ B
    intro c _
    exact hbranch c
  letI := hQfinite
  have hJQ : J ≤ Q := by
    change Ideal.span (Set.range fun s => ∏ k, f s k) ≤ Q
    rw [Ideal.span_le]
    rintro _ ⟨s, rfl⟩
    change (∏ k, f s k) ∈ Finset.univ.inf B
    rw [← Ideal.span_singleton_le_iff_mem]
    apply Finset.le_inf
    intro c _
    rw [Ideal.span_singleton_le_iff_mem]
    apply (B c).mem_of_dvd
      (Finset.dvd_prod_of_mem (f s) (Finset.mem_univ (c s)))
    change f s (c s) ∈ Ideal.span (Set.range fun s => f s (c s))
    exact Ideal.subset_span ⟨s, rfl⟩
  have hQrad : Q ≤ J.radical := by
    rw [Ideal.radical_eq_sInf]
    apply le_sInf
    intro P hP
    letI : P.IsPrime := hP.2
    have hexists : ∀ s : σ, ∃ k : τ, f s k ∈ P := by
      intro s
      have hprod : ∏ k, f s k ∈ P := by
        apply hP.1
        change (∏ k, f s k) ∈
          Ideal.span (Set.range fun s => ∏ k, f s k)
        exact Ideal.subset_span ⟨s, rfl⟩
      rw [Ideal.IsPrime.prod_mem_iff] at hprod
      obtain ⟨k, _, hk⟩ := hprod
      exact ⟨k, hk⟩
    choose c hc using hexists
    calc
      Q ≤ B c := Finset.inf_le (Finset.mem_univ c)
      _ ≤ P := by
        change Ideal.span (Set.range fun s => f s (c s)) ≤ P
        rw [Ideal.span_le]
        rintro _ ⟨s, rfl⟩
        exact hc s
  let q : (A ⧸ J) →ₐ[K] A ⧸ Q :=
    Ideal.Quotient.factorₐ K hJQ
  refine Module.finite_of_surjective_of_ker_le_nilradical q
    (Ideal.Quotient.factor_surjective hJQ) ?_ ?_
  · intro x hx
    rw [mem_nilradical]
    induction x using Quotient.inductionOn' with
    | _ a =>
      have hx' : q (Quotient.mk'' a) = 0 := hx
      change Ideal.Quotient.mk Q a = 0 at hx'
      have haQ : a ∈ Q := Ideal.Quotient.eq_zero_iff_mem.mp hx'
      obtain ⟨n, hn⟩ := Ideal.mem_radical_iff.mp (hQrad haQ)
      refine ⟨n, ?_⟩
      change Ideal.Quotient.mk J (a ^ n) = 0
      exact Ideal.Quotient.eq_zero_iff_mem.mpr hn
  · exact IsNoetherian.noetherian _

end CofiniteIdeal
end Math
