/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.SpecialCases.SingleController.Basic
import MathUE.Probability.FiniteClosedCoreReach

/-!
# Hybrid occupation/gain-flow completion for Vrieze's LP

Vrieze's ordinary optimal dual has two nonnegative controller-action flows.
The occupation flow `z` supplies the stationary policy on its positive state
support.  At a zero-`z` state, the gain-row flow `yGain` has positive total
mass by the dual gain-coupling equation and supplies the completion.

The gain-coupling equation also rules out a closed `yGain`-support trap away
from positive `z` support.  Thus this hybrid policy reaches the occupation
support under the same stationary kernel that will later be used for the
gain and reward identities.  No strict-complementarity upgrade is needed for
this flow-routing layer.
-/

noncomputable section

namespace GameTheory
namespace StochasticGame

open Math.Probability

variable {G : StochasticGame Bool} [Finite G.State]
  [∀ i, Finite (G.Act i)] [∀ i, Nonempty (G.Act i)]

/-- A one-step edge generated by a positive gain-flow action at a state
outside the positive occupation support. -/
def vriezeYGainSucc
    (G : StochasticGame Bool) [Finite G.State]
    [∀ i, Finite (G.Act i)] [∀ i, Nonempty (G.Act i)]
    (controller : Bool)
    (z yGain : G.State → G.Act controller → ℝ)
    (source destination : G.State) : Prop :=
  ¬ G.vriezeOccupationSupport controller z source ∧
    ∃ action : G.Act controller,
      0 < yGain source action ∧
        destination ∈
          (G.controllerKernel controller
            (fun _ => PMF.pure action) source).support

/-- At a zero-occupation state, gain coupling forces strictly positive total
`yGain` mass. -/
theorem vriezeYGain_mass_pos_of_not_occupationSupport
    {controller : Bool}
    {z yGain : G.State → G.Act controller → ℝ}
    {lam : G.State → ℝ}
    (hdual : G.IsVriezeDualFeasible controller z yGain lam)
    (state : G.State)
    (hstate : ¬ G.vriezeOccupationSupport controller z state) :
    0 < ∑ action, yGain state action := by
  classical
  have hzMass_nonpos : (∑ action, z state action) ≤ 0 :=
    le_of_not_gt hstate
  have hzMass_nonneg : 0 ≤ ∑ action, z state action :=
    Finset.sum_nonneg fun action _ => hdual.z_nonneg state action
  have hzMass_zero : (∑ action, z state action) = 0 :=
    le_antisymm hzMass_nonpos hzMass_nonneg
  have hinflow_nonneg :
      0 ≤ ∑ pair : G.State × G.Act controller,
        yGain pair.1 pair.2 *
          G.transProb controller pair.1 pair.2 state :=
    Finset.sum_nonneg fun pair _ =>
      mul_nonneg (hdual.yGain_nonneg pair.1 pair.2)
        ENNReal.toReal_nonneg
  have hcoupling := hdual.gain_coupling state
  rw [hzMass_zero] at hcoupling
  linarith

/-- The gain-flow support graph cannot contain a nonempty trap disjoint from
positive occupation support.  Equivalently, every state reaches positive
`z` support through positive `yGain` edges while outside that support. -/
theorem all_canReach_vriezeOccupationSupport_via_yGain_of_dualFeasible
    {controller : Bool}
    {z yGain : G.State → G.Act controller → ℝ}
    {lam : G.State → ℝ}
    (hdual : G.IsVriezeDualFeasible controller z yGain lam) :
    ∀ source : G.State,
      FiniteReachability.CanReachSet
        (G.vriezeYGainSucc controller z yGain)
        (G.vriezeOccupationSupport controller z) source := by
  classical
  let R : G.State → Prop :=
    G.vriezeOccupationSupport controller z
  let Succ : G.State → G.State → Prop :=
    G.vriezeYGainSucc controller z yGain
  let bad : G.State → Prop := fun state =>
    ¬ FiniteReachability.CanReachSet Succ R state
  by_contra hall
  push Not at hall
  obtain ⟨badState, hbadState⟩ := hall
  change bad badState at hbadState
  have hbad_not_R : ∀ {state : G.State}, bad state → ¬ R state := by
    intro state hstate hR
    exact hstate ⟨state, hR, Relation.ReflTransGen.refl⟩
  have hbad_closed : ∀ {source destination : G.State},
      bad source → Succ source destination → bad destination := by
    intro source destination hsource hstep
    exact
      (FiniteReachability.trap_closed_of_not_canReachSet
        Succ R (hbad_not_R hsource) hsource hstep).2
  have hkernel_pure : ∀ (source : G.State)
      (action : G.Act controller),
      G.controllerKernel controller (fun _ => PMF.pure action) source =
        G.transition source
          (G.jointOfControllerAct controller action) := by
    intro source action
    unfold controllerKernel jointOfControllerAct
    rw [PMF.pure_bind]
  have hbad_of_transProb_pos : ∀ {source destination : G.State}
      (action : G.Act controller),
      bad source → 0 < yGain source action →
      0 < G.transProb controller source action destination →
      bad destination := by
    intro source destination action hsource hyPositive htransition
    apply hbad_closed hsource
    refine ⟨hbad_not_R hsource, action, hyPositive, ?_⟩
    rw [PMF.mem_support_iff, hkernel_pure source action]
    intro hzero
    simp [transProb, hzero] at htransition
  let indicator : G.State → ℝ := fun state =>
    if bad state then 1 else 0
  have hindicator_nonneg : ∀ state, 0 ≤ indicator state := by
    intro state
    dsimp only [indicator]
    split <;> norm_num
  have htransProb_nonneg : ∀ source
      (action : G.Act controller) destination,
      0 ≤ G.transProb controller source action destination := by
    intro source action destination
    exact ENNReal.toReal_nonneg
  have hindicator_expect_nonneg : ∀ source
      (action : G.Act controller),
      0 ≤ ∑ destination,
        G.transProb controller source action destination *
          indicator destination := by
    intro source action
    exact Finset.sum_nonneg fun destination _ =>
      mul_nonneg
        (htransProb_nonneg source action destination)
        (hindicator_nonneg destination)
  have hindicator_expect_bad : ∀ source
      (action : G.Act controller),
      bad source → 0 < yGain source action →
      (∑ destination,
        G.transProb controller source action destination *
          indicator destination) = 1 := by
    intro source action hsource hyPositive
    calc
      (∑ destination,
          G.transProb controller source action destination *
            indicator destination) =
          ∑ destination,
            G.transProb controller source action destination := by
        apply Finset.sum_congr rfl
        intro destination _
        by_cases hzero :
            G.transProb controller source action destination = 0
        · simp [hzero]
        · have hpositive :
              0 < G.transProb controller source action destination :=
            lt_of_le_of_ne
              (htransProb_nonneg source action destination)
              (Ne.symm hzero)
          have hdestination :=
            hbad_of_transProb_pos action hsource hyPositive hpositive
          simp [indicator, hdestination]
      _ = 1 := by
        simpa [transProb] using
          pmf_toReal_sum_one
            (G.transition source
              (G.jointOfControllerAct controller action))
  let yInflow : G.State → ℝ := fun destination =>
    ∑ pair : G.State × G.Act controller,
      yGain pair.1 pair.2 *
        G.transProb controller pair.1 pair.2 destination
  let yMass : G.State → ℝ := fun state =>
    ∑ action, yGain state action
  have hzMass_zero_of_bad : ∀ state, bad state →
      (∑ action, z state action) = 0 := by
    intro state hstate
    apply le_antisymm
    · exact le_of_not_gt (hbad_not_R hstate)
    · exact Finset.sum_nonneg fun action _ =>
        hdual.z_nonneg state action
  have hcoupling_indicator : ∀ state,
      indicator state * (yInflow state - yMass state) =
        -(indicator state) := by
    intro state
    by_cases hstate : bad state
    · have hcoupling := hdual.gain_coupling state
      rw [hzMass_zero_of_bad state hstate] at hcoupling
      have hindicator : indicator state = 1 := by
        dsimp only [indicator]
        rw [if_pos hstate]
      rw [hindicator]
      dsimp only [yInflow, yMass]
      linarith
    · have hindicator : indicator state = 0 := by
        dsimp only [indicator]
        rw [if_neg hstate]
      rw [hindicator]
      ring
  have hyInflow_reindex :
      (∑ destination, indicator destination * yInflow destination) =
        ∑ pair : G.State × G.Act controller,
          yGain pair.1 pair.2 *
            (∑ destination,
              G.transProb controller pair.1 pair.2 destination *
                indicator destination) := by
    dsimp only [yInflow]
    calc
      _ = ∑ destination,
          ∑ pair : G.State × G.Act controller,
            yGain pair.1 pair.2 *
              G.transProb controller pair.1 pair.2 destination *
                indicator destination := by
        apply Finset.sum_congr rfl
        intro destination _
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl
        intro pair _
        ring
      _ = ∑ pair : G.State × G.Act controller,
          ∑ destination,
            yGain pair.1 pair.2 *
              G.transProb controller pair.1 pair.2 destination *
                indicator destination := Finset.sum_comm
      _ = _ := by
        apply Finset.sum_congr rfl
        intro pair _
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl
        intro destination _
        ring
  have hyMass_reindex :
      (∑ state, indicator state * yMass state) =
        ∑ pair : G.State × G.Act controller,
          yGain pair.1 pair.2 * indicator pair.1 := by
    dsimp only [yMass]
    calc
      _ = ∑ state, ∑ action,
          yGain state action * indicator state := by
        apply Finset.sum_congr rfl
        intro state _
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl
        intro action _
        ring
      _ = _ :=
        (Fintype.sum_prod_type
          (fun pair : G.State × G.Act controller =>
            yGain pair.1 pair.2 * indicator pair.1)).symm
  have hflowTerm : ∀ pair : G.State × G.Act controller,
      yGain pair.1 pair.2 * indicator pair.1 ≤
        yGain pair.1 pair.2 *
          (∑ destination,
            G.transProb controller pair.1 pair.2 destination *
              indicator destination) := by
    intro pair
    have hyNonneg := hdual.yGain_nonneg pair.1 pair.2
    by_cases hsource : bad pair.1
    · by_cases hyZero : yGain pair.1 pair.2 = 0
      · simp [hyZero]
      · have hyPositive : 0 < yGain pair.1 pair.2 :=
          lt_of_le_of_ne hyNonneg (Ne.symm hyZero)
        have hexpect :=
          hindicator_expect_bad pair.1 pair.2 hsource hyPositive
        have hindicator : indicator pair.1 = 1 := by
          dsimp only [indicator]
          rw [if_pos hsource]
        rw [hindicator, hexpect]
    · have hindicator : indicator pair.1 = 0 := by
        dsimp only [indicator]
        rw [if_neg hsource]
      rw [hindicator, mul_zero]
      exact mul_nonneg hyNonneg
        (hindicator_expect_nonneg pair.1 pair.2)
  have hyMass_le_yInflow :
      (∑ state, indicator state * yMass state) ≤
        ∑ destination,
          indicator destination * yInflow destination := by
    rw [hyMass_reindex, hyInflow_reindex]
    exact Finset.sum_le_sum fun pair _ => hflowTerm pair
  have hcoupling_sum :
      (∑ destination,
          indicator destination * yInflow destination) -
        (∑ state, indicator state * yMass state) =
          -(∑ state, indicator state) := by
    rw [← Finset.sum_sub_distrib,
      ← Finset.sum_neg_distrib]
    apply Finset.sum_congr rfl
    intro state _
    calc
      indicator state * yInflow state -
          indicator state * yMass state =
        indicator state * (yInflow state - yMass state) := by ring
      _ = -(indicator state) := hcoupling_indicator state
  have hindicator_sum_pos : 0 < ∑ state, indicator state := by
    apply Finset.sum_pos'
    · intro state _
      exact hindicator_nonneg state
    · refine ⟨badState, Finset.mem_univ badState, ?_⟩
      have hindicator_badState : indicator badState = 1 := by
        dsimp only [indicator]
        rw [if_pos hbadState]
      rw [hindicator_badState]
      norm_num
  linarith

/-- Convert a finite real probability vector to a PMF for the hybrid
completion. -/
private noncomputable def flowCompletionWeightsToPMF
    {alpha : Type*} [Fintype alpha] (weight : alpha → ℝ)
    (hnonneg : ∀ item, 0 ≤ weight item)
    (hsum : ∑ item, weight item = 1) : PMF alpha :=
  PMF.ofFintype (fun item => ENNReal.ofReal (weight item)) (by
    rw [← ENNReal.ofReal_one, ← hsum]
    exact
      (ENNReal.ofReal_sum_of_nonneg
        (fun item _ => hnonneg item)).symm)

private theorem flowCompletionWeightsToPMF_apply_toReal
    {alpha : Type*} [Fintype alpha] (weight : alpha → ℝ)
    (hnonneg : ∀ item, 0 ≤ weight item)
    (hsum : ∑ item, weight item = 1) (item : alpha) :
    ((flowCompletionWeightsToPMF weight hnonneg hsum) item).toReal =
      weight item := by
  unfold flowCompletionWeightsToPMF
  rw [PMF.ofFintype_apply]
  exact ENNReal.toReal_ofReal (hnonneg item)

/-- Certificate for the one-policy hybrid completion: normalized occupation
flow on positive `z` support, normalized gain flow off support, closed core,
and actual fixed-kernel reachability of that core. -/
structure IsVriezeFlowCompletion
    (controller : Bool)
    (z yGain : G.State → G.Act controller → ℝ)
    (tau : G.State → PMF (G.Act controller)) : Prop where
  normalized_z_on_support :
    ∀ state (_ : G.vriezeOccupationSupport controller z state)
      (action : G.Act controller),
      ((tau state) action).toReal =
        z state action / (∑ candidate, z state candidate)
  normalized_yGain_off_support :
    ∀ state (_ : ¬ G.vriezeOccupationSupport controller z state)
      (action : G.Act controller),
      ((tau state) action).toReal =
        yGain state action /
          (∑ candidate, yGain state candidate)
  occupationSupport_closed :
    IsClosedCore (G.controllerKernel controller tau)
      {state | G.vriezeOccupationSupport controller z state}
  reaches_occupationSupport :
    ∀ source,
      ∃ target,
        G.vriezeOccupationSupport controller z target ∧
          PMFReachable
            (G.controllerKernel controller tau) source target

/-- Dual feasibility alone compiles the hybrid `z`/`yGain` policy together
with fixed-kernel closed-core reachability. -/
theorem exists_vriezeFlowCompletion_of_dualFeasible
    {controller : Bool}
    {z yGain : G.State → G.Act controller → ℝ}
    {lam : G.State → ℝ}
    (hdual : G.IsVriezeDualFeasible controller z yGain lam) :
    ∃ tau : G.State → PMF (G.Act controller),
      G.IsVriezeFlowCompletion controller z yGain tau := by
  classical
  let tau : G.State → PMF (G.Act controller) := fun state =>
    if hstate : G.vriezeOccupationSupport controller z state then
      flowCompletionWeightsToPMF
        (fun action =>
          z state action / (∑ candidate, z state candidate))
        (fun action =>
          div_nonneg (hdual.z_nonneg state action) hstate.le)
        (by
          rw [← Finset.sum_div]
          exact div_self hstate.ne')
    else
      flowCompletionWeightsToPMF
        (fun action =>
          yGain state action /
            (∑ candidate, yGain state candidate))
        (fun action =>
          div_nonneg (hdual.yGain_nonneg state action)
            (G.vriezeYGain_mass_pos_of_not_occupationSupport
              hdual state hstate).le)
        (by
          rw [← Finset.sum_div]
          exact div_self
            (G.vriezeYGain_mass_pos_of_not_occupationSupport
              hdual state hstate).ne')
  have htau_z : ∀ state
      (hstate : G.vriezeOccupationSupport controller z state)
      (action : G.Act controller),
      ((tau state) action).toReal =
        z state action / (∑ candidate, z state candidate) := by
    intro state hstate action
    dsimp only [tau]
    rw [dif_pos hstate]
    exact flowCompletionWeightsToPMF_apply_toReal _ _ _ action
  have htau_y : ∀ state
      (hstate : ¬ G.vriezeOccupationSupport controller z state)
      (action : G.Act controller),
      ((tau state) action).toReal =
        yGain state action /
          (∑ candidate, yGain state candidate) := by
    intro state hstate action
    dsimp only [tau]
    rw [dif_neg hstate]
    exact flowCompletionWeightsToPMF_apply_toReal _ _ _ action
  have hpureKernel : ∀ (source : G.State)
      (action : G.Act controller),
      G.controllerKernel controller (fun _ => PMF.pure action) source =
        G.transition source
          (G.jointOfControllerAct controller action) := by
    intro source action
    unfold controllerKernel jointOfControllerAct
    rw [PMF.pure_bind]
  have hsucc_to_kernel : ∀ {source destination : G.State},
      G.vriezeYGainSucc controller z yGain source destination →
        PMFSupportStep
          (G.controllerKernel controller tau) source destination := by
    intro source destination hstep
    obtain ⟨hsource, action, hyPositive, hsupport⟩ := hstep
    have hyMassPositive :=
      G.vriezeYGain_mass_pos_of_not_occupationSupport
        hdual source hsource
    have htauPositive : 0 < ((tau source) action).toReal := by
      rw [htau_y source hsource action]
      exact div_pos hyPositive hyMassPositive
    have htransition_ne :
        G.transition source
            (G.jointOfControllerAct controller action) destination ≠ 0 := by
      rw [← hpureKernel source action]
      exact (PMF.mem_support_iff _ _).mp hsupport
    have htransitionPositive :
        0 < G.transProb controller source action destination := by
      exact ENNReal.toReal_pos htransition_ne
        (PMF.apply_ne_top
          (G.transition source
            (G.jointOfControllerAct controller action)) destination)
    have hkernelPositive :
        0 < ((G.controllerKernel controller tau source)
          destination).toReal := by
      rw [G.controllerKernel_apply_toReal_eq_sum]
      apply Finset.sum_pos'
      · intro candidate _
        exact mul_nonneg ENNReal.toReal_nonneg ENNReal.toReal_nonneg
      · exact ⟨action, Finset.mem_univ action,
          mul_pos htauPositive htransitionPositive⟩
    unfold PMFSupportStep
    intro hzero
    simp [hzero] at hkernelPositive
  have hclosed :
      IsClosedCore (G.controllerKernel controller tau)
        {state | G.vriezeOccupationSupport controller z state} := by
    intro source hsource destination hsupport
    exact G.vriezeOccupationSupport_closed_under_controllerKernel
      hdual tau htau_z hsource hsupport
  have hreach : ∀ source,
      ∃ target,
        G.vriezeOccupationSupport controller z target ∧
          PMFReachable
            (G.controllerKernel controller tau) source target := by
    intro source
    obtain ⟨target, htarget, hpath⟩ :=
      G.all_canReach_vriezeOccupationSupport_via_yGain_of_dualFeasible
        hdual source
    exact ⟨target, htarget,
      (Relation.ReflTransGen.mono
        (r := G.vriezeYGainSucc controller z yGain)
        (p := PMFSupportStep
          (G.controllerKernel controller tau))
        (fun _ _ edge => hsucc_to_kernel edge))
          source target hpath⟩
  exact ⟨tau, {
    normalized_z_on_support := htau_z
    normalized_yGain_off_support := htau_y
    occupationSupport_closed := hclosed
    reaches_occupationSupport := hreach
  }⟩

/-- The hybrid completion feeds directly into the generic closed-core
transience compiler. -/
theorem IsVriezeFlowCompletion.exists_closedCoreTransienceCertificate
    [Nonempty G.State]
    {controller : Bool}
    {z yGain : G.State → G.Act controller → ℝ}
    {tau : G.State → PMF (G.Act controller)}
    (completion : G.IsVriezeFlowCompletion
      controller z yGain tau) :
    Nonempty
      (ClosedCoreTransienceCertificate
        (G.controllerKernel controller tau)
        {state | G.vriezeOccupationSupport controller z state}) :=
  Math.Probability.exists_closedCoreTransienceCertificate
    (G.controllerKernel controller tau)
    {state | G.vriezeOccupationSupport controller z state}
    completion.occupationSupport_closed
    completion.reaches_occupationSupport

end StochasticGame
end GameTheory
