/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.Stationary.Root
import UniformEquilibrium.Quitting.Terminal.TargetTail.TerminalTargetSemantics

/-!
# Stationary approximate equilibria of finite quitting games

Solan and Solan, *Quitting games and linear complementarity problems*,
Math. Oper. Res. **45**(2) (2020), Section 5.1, phrase their existence
statements for *stationary* `ε`-equilibria: at every positive accuracy one
product root is repeated forever.  Their Theorem 2.13(1) concludes only that
some `ε`-equilibrium exists, while their Theorem 5.1(1) upgrades the same
conclusion to a stationary profile, at the price of replacing the min-max
normal players by the α-players of `GameTheory.QuittingLCPClassification.normalCore`.

This file supplies the three conclusion shapes used by that upgrade and
nothing else.  It contains no producer and no matrix hypothesis.

* `IsεQuittingStationaryNash` names one stationary `ε`-equilibrium.  The
  deviation class is all behavior strategies, not merely stationary ones, so
  this is the strong reading of the source's conclusion.
* `HasQuittingStationaryApproximateEquilibria` is the literal Section 5.1
  conclusion: a stationary `ε`-equilibrium for every `ε > 0`.
* `IsQuittingStationaryUniformEquilibriumPayoff` additionally pins one payoff
  vector approached by those stationary profiles.  It implies both the literal
  conclusion and `StochasticGame.IsUniformEquilibriumPayoff`, so a producer
  proved at this strength discharges the source statement and the repository's
  uniform-payoff semantics at once.
-/

noncomputable section

namespace GameTheory

open StochasticGame

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- A **stationary `ε`-equilibrium**: the stationary behavior profile
generated by the product root `root` is a terminal `ε`-Nash profile against
every behavior deviation. -/
def IsεQuittingStationaryNash
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) (ε : ℝ)
    (root : ι → PMF Bool) : Prop :=
  (quittingGame reward).IsεAsymptoticNash (quittingTerminalPayoff reward) ε
    (quittingStationaryProfile reward root)

/-- Relaxing the accuracy keeps a stationary approximate equilibrium. -/
theorem IsεQuittingStationaryNash.mono
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {ε δ : ℝ}
    {root : ι → PMF Bool} (h : IsεQuittingStationaryNash reward ε root)
    (hle : ε ≤ δ) : IsεQuittingStationaryNash reward δ root :=
  StochasticGame.IsεAsymptoticNash.mono h hle

/-- The conclusion of Solan and Solan's Section 5.1: a stationary
`ε`-equilibrium exists at every positive accuracy. -/
def HasQuittingStationaryApproximateEquilibria
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) : Prop :=
  ∀ ε : ℝ, 0 < ε → ∃ root : ι → PMF Bool,
    IsεQuittingStationaryNash reward ε root

/-- One payoff vector approached uniformly by stationary `ε`-equilibria.  This
is strictly more than the source's conclusion: it names the limit payoff and
so also exhibits a uniform-equilibrium payoff. -/
def IsQuittingStationaryUniformEquilibriumPayoff
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (value : Payoff ι) : Prop :=
  ∀ ε : ℝ, 0 < ε → ∃ root : ι → PMF Bool,
    IsεQuittingStationaryNash reward ε root ∧
      ∀ who, |quittingTerminalPayoff reward
        (quittingStationaryProfile reward root) who - value who| ≤ ε

/-- Forgetting the limit payoff gives the literal Section 5.1 conclusion. -/
theorem IsQuittingStationaryUniformEquilibriumPayoff.hasApproximateEquilibria
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {value : Payoff ι}
    (h : IsQuittingStationaryUniformEquilibriumPayoff reward value) :
    HasQuittingStationaryApproximateEquilibria reward := by
  intro ε hε
  obtain ⟨root, hnash, _⟩ := h ε hε
  exact ⟨root, hnash⟩

/-- The pinned limit payoff is a uniform-equilibrium payoff of the quitting
game. -/
theorem IsQuittingStationaryUniformEquilibriumPayoff.isUniformEquilibriumPayoff
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {value : Payoff ι}
    (h : IsQuittingStationaryUniformEquilibriumPayoff reward value) :
    (quittingGame reward).IsUniformEquilibriumPayoff none value := by
  apply quittingGame_isUniformEquilibriumPayoff_of_terminalNash_all_errors_approxTarget
  intro ε hε
  obtain ⟨root, hnash, hclose⟩ := h ε hε
  exact ⟨quittingStationaryProfile reward root, hnash, hclose⟩

/-- A stationary approximate-equilibrium family targeting some payoff exhibits
a uniform-equilibrium payoff. -/
theorem exists_uniformEquilibriumPayoff_of_stationaryFamily
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {value : Payoff ι}
    (h : IsQuittingStationaryUniformEquilibriumPayoff reward value) :
    ∃ payoff : Payoff ι,
      (quittingGame reward).IsUniformEquilibriumPayoff none payoff :=
  ⟨value, h.isUniformEquilibriumPayoff⟩

/-- An exact stationary equilibrium anchors its own terminal payoff, so the
degenerate one-profile family is already a stationary uniform-equilibrium
payoff. -/
theorem isQuittingStationaryUniformEquilibriumPayoff_of_exact
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) (root : ι → PMF Bool)
    (hexact : IsεQuittingStationaryNash reward 0 root) :
    IsQuittingStationaryUniformEquilibriumPayoff reward
      (quittingTerminalPayoff reward
        (quittingStationaryProfile reward root)) := by
  intro ε hε
  refine ⟨root, hexact.mono hε.le, ?_⟩
  intro who
  simpa using hε.le

/-- Rewriting the pinned payoff along an equality of payoff vectors. -/
theorem IsQuittingStationaryUniformEquilibriumPayoff.congr_value
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {value target : Payoff ι}
    (h : IsQuittingStationaryUniformEquilibriumPayoff reward value)
    (hvalue : value = target) :
    IsQuittingStationaryUniformEquilibriumPayoff reward target := by
  rw [← hvalue]
  exact h

end GameTheory
