/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import MathUE.Topology.CompactBudgetedPrefixRelation
import MathUE.Topology.ExtendedOrbit

/-!
# Compact relation chains with edge budgets

Arbitrarily long finite relation prefixes satisfying every elapsed cumulative
edge-cost budget have a common infinite limit path. If the budgets tend to
infinity, that path is an extended orbit with unbounded edge-cost variation.

This is a sufficient compactness interface for Simon-type viability
questions. Its substantive input is the production of the budgeted finite
prefixes; compactness does not manufacture those prefixes from local
nonemptiness or contractibility alone.

The module also records the complementary finite-cell Lyapunov interface.
Exact coverage, bounds, and cellwise decrease proofs compile to the global
potential inequality that obstructs arbitrarily large finite-orbit variation.
No certificate search or polyhedral decision procedure is asserted here.
-/

noncomputable section

namespace Math
namespace Topology

open Filter Set
open scoped BigOperators Topology

/-- The common linear budget generated by repeatedly adding the same edge
cost. -/
def linearEdgeBudget (addedCost : ℝ) (cutoff : ℕ) : ℝ :=
  addedCost * cutoff

/-- A positive edge increment makes the common linear budget diverge. -/
theorem linearEdgeBudget_tendsto_atTop
    {addedCost : ℝ} (hpositive : 0 < addedCost) :
    Tendsto (linearEdgeBudget addedCost) atTop atTop := by
  exact tendsto_natCast_atTop_atTop.const_mul_atTop hpositive

/-- A restart set supports another relation edge with a uniform cost lower
bound after every visit. Positivity is imposed only when divergence is needed. -/
def HasRestartableExtension {Point : Type*}
    (relation : Point → Point → Prop) (cost : Point → Point → ℝ)
    (restartSet : Set Point) (addedCost : ℝ) : Prop :=
  restartSet.Nonempty ∧
    ∀ point ∈ restartSet,
      ∃ target ∈ restartSet,
        relation point target ∧ addedCost ≤ cost point target

/-- Exact finite-cell data for a bounded strict Lyapunov potential. The cells
need only cover the state type; disjointness is unnecessary. Requiring the
edge inequality for every pair of cells containing the endpoints makes the
interface sound even when cells overlap. -/
def HasFiniteCellLyapunovCertificate {State Cell : Type*} [Fintype Cell]
    (relation : Correspondence State State) (cost : State → State → ℝ)
    (cell : Cell → Set State) (localPotential : Cell → State → ℝ)
    (constant lower upper : ℝ) : Prop :=
  (∀ state, ∃ index, state ∈ cell index) ∧
    (∀ index state, state ∈ cell index →
      lower ≤ localPotential index state) ∧
    (∀ index state, state ∈ cell index →
      localPotential index state ≤ upper) ∧
    ∀ firstCell nextCell first next,
      first ∈ cell firstCell → next ∈ cell nextCell →
      next ∈ relation first →
      localPotential nextCell next ≤
        localPotential firstCell first - constant * cost first next

/-- A finite-cell certificate selects one containing cell at each state and
thereby produces a single globally bounded strict Lyapunov potential. -/
theorem HasFiniteCellLyapunovCertificate.exists_globalPotential
    {State Cell : Type*} [Fintype Cell]
    {relation : Correspondence State State} {cost : State → State → ℝ}
    {cell : Cell → Set State} {localPotential : Cell → State → ℝ}
    {constant lower upper : ℝ}
    (hcertificate : HasFiniteCellLyapunovCertificate
      relation cost cell localPotential constant lower upper) :
    ∃ potential : State → ℝ,
      (∀ state, lower ≤ potential state) ∧
      (∀ state, potential state ≤ upper) ∧
      ∀ first next, next ∈ relation first →
        potential next ≤ potential first - constant * cost first next := by
  classical
  rcases hcertificate with ⟨hcover, hlower, hupper, hdecrease⟩
  let chosenCell : State → Cell := fun state ↦ Classical.choose (hcover state)
  have hchosenCell : ∀ state, state ∈ cell (chosenCell state) := by
    intro state
    exact Classical.choose_spec (hcover state)
  let potential : State → ℝ := fun state ↦
    localPotential (chosenCell state) state
  refine ⟨potential, ?_, ?_, ?_⟩
  · intro state
    exact hlower (chosenCell state) state (hchosenCell state)
  · intro state
    exact hupper (chosenCell state) state (hchosenCell state)
  · intro first next hnext
    exact hdecrease (chosenCell first) (chosenCell next) first next
      (hchosenCell first) (hchosenCell next) hnext

/-- Exact finite-cell inequalities certify the existing global finite-orbit
obstruction. This theorem does not assert that the certificate data exist. -/
theorem not_hasArbitrarilyLargeFiniteOrbitVariationWith_of_finiteCellCertificate
    {State Cell : Type*} [Fintype Cell]
    {relation : Correspondence State State} {cost : State → State → ℝ}
    {cell : Cell → Set State} {localPotential : Cell → State → ℝ}
    {constant lower upper : ℝ} (hconstant : 0 < constant)
    (hcertificate : HasFiniteCellLyapunovCertificate
      relation cost cell localPotential constant lower upper) :
    ¬HasArbitrarilyLargeFiniteOrbitVariationWith relation cost := by
  obtain ⟨potential, hlower, hupper, hdecrease⟩ :=
    hcertificate.exists_globalPotential
  exact not_hasArbitrarilyLargeFiniteOrbitVariationWith_of_potential_bounds
    hconstant hlower hupper hdecrease

/-- A positive-cost self-loop is a cheap negative regression for any proposed
strict finite-cell certificate, independently of its claimed bounds. -/
theorem not_hasFiniteCellLyapunovCertificate_of_positive_selfLoop
    {State Cell : Type*} [Fintype Cell]
    {relation : Correspondence State State} {cost : State → State → ℝ}
    {cell : Cell → Set State} {localPotential : Cell → State → ℝ}
    {constant lower upper : ℝ} {state : State}
    (hconstant : 0 < constant) (hloop : state ∈ relation state)
    (hcost : 0 < cost state state) :
    ¬HasFiniteCellLyapunovCertificate
      relation cost cell localPotential constant lower upper := by
  rintro ⟨hcover, _, _, hdecrease⟩
  obtain ⟨index, hindex⟩ := hcover state
  have hdrop := hdecrease index index state state hindex hindex hloop
  have hpositive : 0 < constant * cost state state := mul_pos hconstant hcost
  linarith

/-- An affine functional with exact rational coefficients, evaluated later in
real coordinate space. -/
structure RationalAffineFunctional (Coordinate : Type*) where
  offset : ℚ
  coefficient : Coordinate → ℚ

namespace RationalAffineFunctional

/-- Real evaluation of an exact rational affine functional. -/
def eval {Coordinate : Type*} [Fintype Coordinate]
    (functional : RationalAffineFunctional Coordinate)
    (point : Coordinate → ℝ) : ℝ := by
  classical
  exact (functional.offset : ℝ) +
    ∑ coordinate, (functional.coefficient coordinate : ℝ) * point coordinate

end RationalAffineFunctional

/-- A closed polyhedral cell described by exact rational weak halfspaces.
Equalities can be represented by two opposite inequalities. A common finite
row type can be padded when different cells use different row counts. -/
structure RationalPolyhedralCell (Coordinate Row : Type*) where
  normal : Row → Coordinate → ℚ
  lower : Row → ℚ

namespace RationalPolyhedralCell

/-- Real points satisfying every rational halfspace row of a cell. -/
def realization {Coordinate Row : Type*} [Fintype Coordinate]
    (cell : RationalPolyhedralCell Coordinate Row) :
    Set (Coordinate → ℝ) := by
  classical
  exact {point | ∀ row,
    (cell.lower row : ℝ) ≤
      ∑ coordinate, (cell.normal row coordinate : ℝ) * point coordinate}

@[simp]
theorem mem_realization {Coordinate Row : Type*} [Fintype Coordinate]
    (cell : RationalPolyhedralCell Coordinate Row)
    (point : Coordinate → ℝ) :
    point ∈ cell.realization ↔
      ∀ row, (cell.lower row : ℝ) ≤
        ∑ coordinate, (cell.normal row coordinate : ℝ) * point coordinate :=
  Iff.rfl

end RationalPolyhedralCell

/-- A finite rational-polyhedral specialization of the exact finite-cell
certificate. The relation lives on a supplied carrier subtype; each carrier
point must be covered by a cell. Coverage, bounds, and affine descent remain
proof obligations, not outputs of an unformalized checker. -/
def HasRationalPolyhedralLyapunovCertificate
    {Coordinate Cell Row : Type*}
    [Fintype Coordinate] [Fintype Cell] [Fintype Row]
    (carrier : Set (Coordinate → ℝ))
    (relation : Correspondence carrier carrier)
    (cost : carrier → carrier → ℝ)
    (cell : Cell → RationalPolyhedralCell Coordinate Row)
    (localPotential : Cell → RationalAffineFunctional Coordinate)
    (constant lower upper : ℝ) : Prop :=
  HasFiniteCellLyapunovCertificate relation cost
    (fun index ↦
      {state | (state : Coordinate → ℝ) ∈ (cell index).realization})
    (fun index state ↦ localPotential index |>.eval state)
    constant lower upper

/-- A supplied exact rational-polyhedral certificate rules out arbitrarily
large finite-orbit variation on its carrier. No certificate existence,
coverage algorithm, or rational inequality decision procedure is claimed. -/
theorem not_hasArbitrarilyLargeFiniteOrbitVariationWith_of_rationalPolyhedralCertificate
    {Coordinate Cell Row : Type*}
    [Fintype Coordinate] [Fintype Cell] [Fintype Row]
    {carrier : Set (Coordinate → ℝ)}
    {relation : Correspondence carrier carrier}
    {cost : carrier → carrier → ℝ}
    {cell : Cell → RationalPolyhedralCell Coordinate Row}
    {localPotential : Cell → RationalAffineFunctional Coordinate}
    {constant lower upper : ℝ} (hconstant : 0 < constant)
    (hcertificate : HasRationalPolyhedralLyapunovCertificate
      carrier relation cost cell localPotential constant lower upper) :
    ¬HasArbitrarilyLargeFiniteOrbitVariationWith relation cost := by
  exact not_hasArbitrarilyLargeFiniteOrbitVariationWith_of_finiteCellCertificate
    hconstant hcertificate

variable {Point : Type*} [TopologicalSpace Point] [T2Space Point]

/-- Relation prefixes satisfying every edge-cost budget whose cutoff has elapsed. -/
def compactEdgeBudgetedPrefixSolutionSet
    (box : Set Point) (relation : Point → Point → Prop)
    (cost : Point → Point → ℝ) (budget : ℕ → ℝ) (horizon : ℕ) :
    Set (ℕ → Point) :=
  {path |
    path ∈ compactFinitePrefixSolutionSet box relation horizon ∧
      ∀ cutoff ≤ horizon,
        budget cutoff ≤
          ∑ time ∈ Finset.range cutoff, cost (path time) (path (time + 1))}

omit [TopologicalSpace Point] [T2Space Point] in
/-- A restartable extension can be iterated to one path whose prefix at every
horizon satisfies the same linear cumulative budget. In particular, the
finite-prefix witnesses are compatible rather than chosen independently. -/
theorem exists_compatible_edgeBudgetedFinitePrefixes_of_restartableExtension
    (box : Set Point) (relation : Point → Point → Prop)
    (cost : Point → Point → ℝ) (restartSet : Set Point) (addedCost : ℝ)
    (hcontained : restartSet ⊆ box)
    (hrestart : HasRestartableExtension relation cost restartSet addedCost) :
    ∃ path : ℕ → Point, ∀ horizon,
      path ∈ compactEdgeBudgetedPrefixSolutionSet
        box relation cost (linearEdgeBudget addedCost) horizon := by
  classical
  obtain ⟨⟨initial, hinitial⟩, hextend⟩ := hrestart
  let next : restartSet → restartSet := fun point ↦
    ⟨Classical.choose (hextend point point.property),
      (Classical.choose_spec (hextend point point.property)).1⟩
  have hnext : ∀ point : restartSet,
      relation point (next point) ∧ addedCost ≤ cost point (next point) := by
    intro point
    exact (Classical.choose_spec (hextend point point.property)).2
  let start : restartSet := ⟨initial, hinitial⟩
  let restartPath : ℕ → restartSet := fun time ↦ (next^[time]) start
  have hrestartPath_succ : ∀ time,
      restartPath (time + 1) = next (restartPath time) := by
    intro time
    simp only [restartPath, Function.iterate_succ_apply']
  let path : ℕ → Point := fun time ↦ restartPath time
  refine ⟨path, fun horizon ↦ ⟨⟨?_, ?_⟩, ?_⟩⟩
  · intro time
    exact hcontained (restartPath time).property
  · intro time
    change relation (restartPath time) (restartPath ((time : ℕ) + 1))
    rw [hrestartPath_succ]
    exact (hnext (restartPath time)).1
  · intro cutoff _hcutoff
    calc
      linearEdgeBudget addedCost cutoff =
          ∑ _time ∈ Finset.range cutoff, addedCost := by
        simp [linearEdgeBudget, Finset.sum_const, nsmul_eq_mul, mul_comm]
      _ ≤ ∑ time ∈ Finset.range cutoff,
          cost (path time) (path (time + 1)) := by
        apply Finset.sum_le_sum
        intro time _htime
        change addedCost ≤ cost (restartPath time) (restartPath (time + 1))
        rw [hrestartPath_succ]
        exact (hnext (restartPath time)).2

omit [TopologicalSpace Point] [T2Space Point] in
/-- Increasing the horizon only adds relation and edge-budget constraints. -/
theorem compactEdgeBudgetedPrefixSolutionSet_succ_subset
    (box : Set Point) (relation : Point → Point → Prop)
    (cost : Point → Point → ℝ) (budget : ℕ → ℝ) (horizon : ℕ) :
    compactEdgeBudgetedPrefixSolutionSet
        box relation cost budget (horizon + 1) ⊆
      compactEdgeBudgetedPrefixSolutionSet box relation cost budget horizon := by
  intro path hpath
  refine ⟨compactFinitePrefixSolutionSet_succ_subset
    box relation horizon hpath.1, ?_⟩
  intro cutoff hcutoff
  exact hpath.2 cutoff (hcutoff.trans (Nat.le_succ horizon))

/-- Edge-budgeted prefixes form a closed set when the relation graph is
closed and the edge cost is continuous. -/
theorem compactEdgeBudgetedPrefixSolutionSet_isClosed
    (box : Set Point) (relation : Point → Point → Prop)
    (cost : Point → Point → ℝ) (budget : ℕ → ℝ)
    (hbox : IsCompact box)
    (hgraph : IsClosed
      {pair : Point × Point |
        pair.1 ∈ box ∧ pair.2 ∈ box ∧ relation pair.1 pair.2})
    (hcost : Continuous fun pair : Point × Point ↦ cost pair.1 pair.2)
    (horizon : ℕ) :
    IsClosed (compactEdgeBudgetedPrefixSolutionSet
      box relation cost budget horizon) := by
  have hprefix := compactFinitePrefixSolutionSet_isClosed
    box relation hbox hgraph horizon
  have hbudgetClosed : IsClosed {path : ℕ → Point |
      ∀ cutoff ≤ horizon,
        budget cutoff ≤
          ∑ time ∈ Finset.range cutoff,
            cost (path time) (path (time + 1))} := by
    rw [show {path : ℕ → Point |
        ∀ cutoff ≤ horizon,
          budget cutoff ≤
            ∑ time ∈ Finset.range cutoff,
              cost (path time) (path (time + 1))} =
      ⋂ cutoff : ℕ, ⋂ (_h : cutoff ≤ horizon),
        {path | budget cutoff ≤
          ∑ time ∈ Finset.range cutoff,
            cost (path time) (path (time + 1))} by
      ext path
      simp]
    apply isClosed_iInter
    intro cutoff
    apply isClosed_iInter
    intro _h
    apply isClosed_le continuous_const
    exact continuous_finsetSum _ fun time _ ↦ by
      have hpair : Continuous (fun path : ℕ → Point ↦
          (path time, path (time + 1))) :=
        (continuous_apply time).prodMk (continuous_apply (time + 1))
      change Continuous
        ((fun pair : Point × Point ↦ cost pair.1 pair.2) ∘
          fun path : ℕ → Point ↦ (path time, path (time + 1)))
      exact hcost.comp hpair
  rw [show compactEdgeBudgetedPrefixSolutionSet
      box relation cost budget horizon =
    compactFinitePrefixSolutionSet box relation horizon ∩
      {path : ℕ → Point |
        ∀ cutoff ≤ horizon,
          budget cutoff ≤
            ∑ time ∈ Finset.range cutoff,
              cost (path time) (path (time + 1))} by
    ext path
    rfl]
  exact hprefix.inter hbudgetClosed

/-- Every edge-budgeted prefix set is compact. -/
theorem compactEdgeBudgetedPrefixSolutionSet_isCompact
    (box : Set Point) (relation : Point → Point → Prop)
    (cost : Point → Point → ℝ) (budget : ℕ → ℝ)
    (hbox : IsCompact box)
    (hgraph : IsClosed
      {pair : Point × Point |
        pair.1 ∈ box ∧ pair.2 ∈ box ∧ relation pair.1 pair.2})
    (hcost : Continuous fun pair : Point × Point ↦ cost pair.1 pair.2)
    (horizon : ℕ) :
    IsCompact (compactEdgeBudgetedPrefixSolutionSet
      box relation cost budget horizon) := by
  exact (isCompact_pi_infinite fun _ ↦ hbox).of_isClosed_subset
    (compactEdgeBudgetedPrefixSolutionSet_isClosed
      box relation cost budget hbox hgraph hcost horizon)
    (fun _ hpath ↦ hpath.1.1)

/-- Arbitrarily long compatible edge-budgeted prefixes yield one infinite
relation chain satisfying every budget. -/
theorem exists_infiniteChain_of_edgeBudgetedFinitePrefixes
    (box : Set Point) (relation : Point → Point → Prop)
    (cost : Point → Point → ℝ) (budget : ℕ → ℝ)
    (hbox : IsCompact box)
    (hgraph : IsClosed
      {pair : Point × Point |
        pair.1 ∈ box ∧ pair.2 ∈ box ∧ relation pair.1 pair.2})
    (hcost : Continuous fun pair : Point × Point ↦ cost pair.1 pair.2)
    (hprefix : ∀ horizon,
      (compactEdgeBudgetedPrefixSolutionSet
        box relation cost budget horizon).Nonempty) :
    ∃ path : ℕ → Point,
      (∀ time, path time ∈ box) ∧
      (∀ time, relation (path time) (path (time + 1))) ∧
      ∀ cutoff, budget cutoff ≤
        ∑ time ∈ Finset.range cutoff,
          cost (path time) (path (time + 1)) := by
  let prefixSet : ℕ → Set (ℕ → Point) := fun horizon ↦
    compactEdgeBudgetedPrefixSolutionSet
      box relation cost budget horizon
  have hnested : ∀ horizon, prefixSet (horizon + 1) ⊆ prefixSet horizon :=
    compactEdgeBudgetedPrefixSolutionSet_succ_subset
      box relation cost budget
  have hnonempty : ∀ horizon, (prefixSet horizon).Nonempty := hprefix
  have hcompactZero : IsCompact (prefixSet 0) :=
    compactEdgeBudgetedPrefixSolutionSet_isCompact
      box relation cost budget hbox hgraph hcost 0
  have hclosed : ∀ horizon, IsClosed (prefixSet horizon) :=
    compactEdgeBudgetedPrefixSolutionSet_isClosed
      box relation cost budget hbox hgraph hcost
  obtain ⟨path, hpath⟩ :=
    IsCompact.nonempty_iInter_of_sequence_nonempty_isCompact_isClosed
      prefixSet hnested hnonempty hcompactZero hclosed
  have hpref : ∀ horizon, path ∈ prefixSet horizon := Set.mem_iInter.mp hpath
  refine ⟨path, (hpref 0).1.1, ?_, ?_⟩
  · intro time
    exact (hpref (time + 1)).1.2 ⟨time, Nat.lt_succ_self time⟩
  · intro cutoff
    exact (hpref cutoff).2 cutoff le_rfl

/-- Diverging finite edge budgets compile to an extended orbit with unbounded
edge-cost variation. -/
theorem exists_extendedOrbit_unboundedVariation_of_edgeBudgetedFinitePrefixes
    (box : Set Point) (relation : Point → Point → Prop)
    (cost : Point → Point → ℝ) (budget : ℕ → ℝ)
    (hbox : IsCompact box)
    (hgraph : IsClosed
      {pair : Point × Point |
        pair.1 ∈ box ∧ pair.2 ∈ box ∧ relation pair.1 pair.2})
    (hcost : Continuous fun pair : Point × Point ↦ cost pair.1 pair.2)
    (hbudget : Tendsto budget atTop atTop)
    (hprefix : ∀ horizon,
      (compactEdgeBudgetedPrefixSolutionSet
        box relation cost budget horizon).Nonempty) :
    ∃ orbit : ExtendedOrbitData (fun point ↦ {next | relation point next}),
      HasUnboundedExtendedVariationWith cost orbit := by
  obtain ⟨path, _, hrelation, hpathBudget⟩ :=
    exists_infiniteChain_of_edgeBudgetedFinitePrefixes
      box relation cost budget hbox hgraph hcost hprefix
  have hstep : IsInfiniteOrbit (fun point ↦ {next | relation point next}) path :=
    hrelation
  let orbit := ExtendedOrbitData.ofInfiniteOrbit path hstep
  refine ⟨orbit, ?_⟩
  intro bound
  obtain ⟨cutoff, hcutoff⟩ := ((tendsto_atTop.1 hbudget) bound).exists
  refine ⟨1, cutoff, ?_⟩
  rw [show orbit.prefixVariationWith cost 1 cutoff =
      ∑ time ∈ Finset.range cutoff,
        cost (path time) (path (time + 1)) by
    exact ExtendedOrbitData.prefixVariationWith_ofInfiniteOrbit
      path hstep cost cutoff]
  exact hcutoff.trans (hpathBudget cutoff)

end Topology
end Math
