import Mathlib.MeasureTheory.Measure.Regular
import Mathlib.Topology.Metrizable.Urysohn
import MathUE.Topology.CountableObservation

/-!
# Regularity of countable observation topologies

The clopen generators of a countable observation topology make it regular.
Together with second countability, this gives pseudometrizability and hence
weak regularity for every finite Borel measure.
-/

namespace Math.CountableObservation

open MeasureTheory Set TopologicalSpace

universe u v

variable {Path : Type u} (Prefix : ℕ → Type v)
  (observe : (n : ℕ) → Path → Prefix n)

/-- A topology generated by discrete observation fibers is regular. -/
abbrev regularSpace :
    @RegularSpace Path (topology Prefix observe) := by
  letI : TopologicalSpace Path := topology Prefix observe
  rw [regularSpace_generateFrom rfl]
  intro set hset path hpath
  rcases hset with ⟨n, value, rfl⟩
  have hopen := isOpen_cylinder Prefix observe n value
  have hclosed := isClosed_cylinder Prefix observe n value
  rw [hclosed.isOpen_compl.nhdsSet_eq, Filter.disjoint_principal_left]
  simpa only [compl_compl] using hopen.mem_nhds hpath

/-- A countable observation topology is pseudometrizable. -/
abbrev pseudoMetrizableSpace [∀ n, Countable (Prefix n)] :
    @PseudoMetrizableSpace Path (topology Prefix observe) := by
  letI : TopologicalSpace Path := topology Prefix observe
  letI : RegularSpace Path := regularSpace Prefix observe
  letI : SecondCountableTopology Path :=
    secondCountableTopology Prefix observe
  infer_instance

/-- The generated measurable space is a Borel space for the generated
topology. -/
abbrev borelSpace [∀ n, Countable (Prefix n)] :
    @BorelSpace Path (topology Prefix observe)
      (measurableSpace Prefix observe) := by
  exact @BorelSpace.mk Path (topology Prefix observe)
    (measurableSpace Prefix observe)
    (borel_eq_measurableSpace Prefix observe).symm

/-- Every finite measure on a countable observation space is weakly regular. -/
theorem weaklyRegular [∀ n, Countable (Prefix n)]
    (measure : @Measure Path (measurableSpace Prefix observe))
    [IsFiniteMeasure measure] :
    @Measure.WeaklyRegular Path (measurableSpace Prefix observe)
      (topology Prefix observe) measure := by
  letI : TopologicalSpace Path := topology Prefix observe
  letI : MeasurableSpace Path := measurableSpace Prefix observe
  letI : PseudoMetrizableSpace Path :=
    pseudoMetrizableSpace Prefix observe
  letI : BorelSpace Path := borelSpace Prefix observe
  infer_instance

/-- A measurable set under a finite countable-observation law has simultaneous
closed inner and open outer approximations with the stated gap mass. -/
theorem exists_isClosed_isOpen_measure_sdiff_le
    [∀ n, Countable (Prefix n)]
    (measure : @Measure Path (measurableSpace Prefix observe))
    [IsFiniteMeasure measure] {set : Set Path}
    (hset : @MeasurableSet Path (measurableSpace Prefix observe) set)
    {epsilon : ℝ} (hepsilon : 0 < epsilon) :
    ∃ closed openSet,
      @IsClosed Path (topology Prefix observe) closed ∧
      @IsOpen Path (topology Prefix observe) openSet ∧
      closed ⊆ set ∧ set ⊆ openSet ∧
      measure (openSet \ closed) ≤ ENNReal.ofReal epsilon := by
  letI : TopologicalSpace Path := topology Prefix observe
  letI : MeasurableSpace Path := measurableSpace Prefix observe
  letI : PseudoMetrizableSpace Path :=
    pseudoMetrizableSpace Prefix observe
  letI : BorelSpace Path := borelSpace Prefix observe
  letI : Measure.WeaklyRegular measure :=
    weaklyRegular Prefix observe measure
  have hhalf : 0 < epsilon / 2 := half_pos hepsilon
  have hhalfENN : ENNReal.ofReal (epsilon / 2) ≠ 0 :=
    (ENNReal.ofReal_pos.mpr hhalf).ne'
  obtain ⟨closed, hclosedSubset, hclosed, hinner⟩ :=
    hset.exists_isClosed_sdiff_lt (measure_ne_top measure set) hhalfENN
  obtain ⟨openSet, hsubsetOpen, hopen, -, houter⟩ :=
    hset.exists_isOpen_sdiff_lt (measure_ne_top measure set) hhalfENN
  refine ⟨closed, openSet, hclosed, hopen, hclosedSubset, hsubsetOpen, ?_⟩
  have hdecompose :
      openSet \ closed = (openSet \ set) ∪ (set \ closed) := by
    ext path
    constructor <;> simp only [mem_sdiff, mem_union] at *
    · intro hpath
      by_cases hpathSet : path ∈ set
      · exact Or.inr ⟨hpathSet, hpath.2⟩
      · exact Or.inl ⟨hpath.1, hpathSet⟩
    · rintro (⟨hpathOpen, hpathSet⟩ | ⟨hpathSet, hpathClosed⟩)
      · exact ⟨hpathOpen, fun hclosedPath ↦ hpathSet (hclosedSubset hclosedPath)⟩
      · exact ⟨hsubsetOpen hpathSet, hpathClosed⟩
  rw [hdecompose]
  have hstrict : measure ((openSet \ set) ∪ (set \ closed)) <
      ENNReal.ofReal epsilon := by
    calc
      measure ((openSet \ set) ∪ (set \ closed)) ≤
          measure (openSet \ set) + measure (set \ closed) := measure_union_le _ _
      _ < ENNReal.ofReal (epsilon / 2) + ENNReal.ofReal (epsilon / 2) :=
        ENNReal.add_lt_add houter hinner
      _ = ENNReal.ofReal epsilon := by
        rw [← ENNReal.ofReal_add hhalf.le hhalf.le]
        congr 2
        ring
  exact hstrict.le

end Math.CountableObservation
