/-
Copyright (c) 2026 UniformEquilibrium contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: UniformEquilibrium contributors.
-/

import UniformEquilibrium.Quitting.Examples.FinFourOwnerRiskyStationaryClosure
import UniformEquilibrium.Quitting.Paths.SureExitSet

/-!
# Pure-pair defect of the owner-risky table

This file records the stable, Research-independent content of the table's paid
pair: the exact two gains and the full semantic-debt vector at `{0,3}`.
-/

noncomputable section

namespace GameTheory

namespace FinFourOwnerRiskyStationaryClosure

open QuittingSureSetOwnerRepair

/-- Actual profile generated by the pure pair `{0,3}` followed by Continue. -/
def sharpPurePairProfile (R singletonLevel : ℝ) :
    (quittingGame (sharpReward R singletonLevel)).BehaviorProfile :=
  quittingRootThenContinuationProfile (sharpReward R singletonLevel)
    (quittingPureSetRoot {0, 3})
    (quittingAlwaysContinueProfile (sharpReward R singletonLevel))

/-- Semantic debt of the actual pure-pair profile. -/
def sharpPurePairDebt (R singletonLevel : ℝ) : Player → ℝ :=
  quittingTerminalSemanticDebt
    (quittingTerminalSemanticPair
      (sharpReward R singletonLevel) (sharpPurePairProfile R singletonLevel))

/-- Player zero gains exactly `1/100` by joining the singleton `{3}`. -/
theorem sharpMarkedGain_eq (R singletonLevel : ℝ) :
    quittingSetReward (sharpReward R singletonLevel) {0, 3} 0 -
        quittingSetReward (sharpReward R singletonLevel) {3} 0 =
      1 / 100 := by
  norm_num +decide [quittingSetReward, sharpReward, sharpActivePassive,
    sharpActiveGain, indicator, sharpScale]

/-- Player one gains exactly one by joining the pair `{0,3}`. -/
theorem sharpPayerGain_eq (R singletonLevel : ℝ) :
    quittingSetReward (sharpReward R singletonLevel) {0, 1, 3} 1 -
        quittingSetReward (sharpReward R singletonLevel) {0, 3} 1 =
      1 := by
  norm_num +decide [quittingSetReward, sharpReward, sharpActivePassive,
    sharpActiveGain, indicator, sharpScale]

/-- The pure pair `{0,3}` has semantic-debt vector `(0,1,1/100,1)`. -/
theorem sharpPurePairDebt_eq (R singletonLevel : ℝ) :
    sharpPurePairDebt R singletonLevel = ![0, 1, 1 / 100, 1] := by
  unfold sharpPurePairDebt sharpPurePairProfile
  rw [quittingTerminalSemanticPair_pureSetRootThenContinuation_eq_of_two_le_card
    _ {0, 3} (by decide)]
  funext who
  fin_cases who <;>
    norm_num +decide [quittingTerminalSemanticDebt, quittingSetReward,
      sharpReward, sharpActivePassive, sharpActiveGain,
      sharpSpectatorPassive, indicator, sharpScale, sharpLoss]

/-- At the pair `{0,3}`, the marked owner is slack while the two nonmembers
carry distinct positive semantic debts. -/
theorem sharpPurePairDebt_zero_and_distinct_pos (R singletonLevel : ℝ) :
    sharpPurePairDebt R singletonLevel 0 = 0 ∧
      0 < sharpPurePairDebt R singletonLevel 1 ∧
        0 < sharpPurePairDebt R singletonLevel 2 ∧
          sharpPurePairDebt R singletonLevel 1 ≠
            sharpPurePairDebt R singletonLevel 2 := by
  rw [sharpPurePairDebt_eq]
  simp

end FinFourOwnerRiskyStationaryClosure

end GameTheory
