/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.AbsorptionPath.CollisionConcentration
import UniformEquilibrium.Quitting.AbsorptionPath.NormalizedFiniteWindowOccupation
import UniformEquilibrium.Quitting.AbsorptionPath.SurvivalWeightedObstructionAdapter
import UniformEquilibrium.Quitting.Classification.Existence.PureTimeDeviationLedger
import UniformEquilibrium.Quitting.Cycles.PeriodOneTangentAtlas
import UniformEquilibrium.Quitting.Cycles.PeriodicJointSurvival
import UniformEquilibrium.Quitting.Examples.SolanVieilleBoundaryEquilibrium
import UniformEquilibrium.Quitting.Examples.BlockPair.FourPlayerPairedSingletonPeriodTwoStationary
import UniformEquilibrium.Quitting.Stationary.ApproximabilityCompactification
import UniformEquilibrium.Quitting.Stationary.EndpointCompiler

/-!
# Nonstationarity of the Solan--Vieille boundary equilibrium

For the explicit four-player boundary table, terminal approximate equilibria cannot
remain uniformly close to all-Continue at every date once the approximation is small
enough. Compactification at the stationary all-Continue apex, together with the exact
stationary endpoint obstruction, then rules out stationary terminal approximate
equilibria at all sufficiently small positive errors.

This does not contradict existence: the same table has the exact period-two equilibrium
compiled in `SolanVieilleBoundaryEquilibrium`. The result separates the nonstationary
mechanism from the stationary and uniformly near-all-Continue strategy classes.
-/

noncomputable section

namespace GameTheory
namespace SolanVieilleBoundary

open StochasticGame Filter Set
open Math.Probability Math.PMFProduct

/-- A time-indexed root sequence conditional on continued play. -/
abbrev BoundaryRootSequence {ι : Type} := ℕ → ι → PMF Bool

/-- The behavioral profile generated by a boundary-table root sequence. -/
def boundaryRootSequenceProfile
    {ι : Type} [Fintype ι] [DecidableEq ι]
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : BoundaryRootSequence (ι := ι)) :
    (quittingGame reward).BehaviorProfile :=
  quittingRootSequenceProfile reward roots 0

/-- The stationary behavioral profile generated by one root. -/
def boundaryStationaryProfile
    {ι : Type} [Fintype ι] [DecidableEq ι]
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) : (quittingGame reward).BehaviorProfile :=
  quittingStationaryProfile reward root

/-- Terminal approximate Nash equilibrium for the boundary table. -/
def IsBoundaryTerminalApproxNash
    {ι : Type} [Fintype ι] [DecidableEq ι]
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) (epsilon : ℝ)
    (candidate : (quittingGame reward).BehaviorProfile) : Prop :=
  (quittingGame reward).IsεAsymptoticNash
    (quittingTerminalPayoff reward) epsilon candidate
private theorem boundaryReward_abs_le_four
    (terminal : {S : Finset (Fin 4) // S.Nonempty}) (player : Fin 4) :
    |SolanVieilleBoundary.boundaryReward terminal player| ≤ 4 := by
  fin_cases terminal <;> fin_cases player <;>
    simp [SolanVieilleBoundary.boundaryReward]

private theorem quitProbability_lt_of_nearAllContinue
    {roots : BoundaryRootSequence (ι := Fin 4)} {ε : ℝ}
    (hclose : ∀ time player,
      |(roots time player false).toReal - 1| < ε)
    (time : ℕ) (player : Fin 4) :
    (roots time player true).toReal < ε := by
  have hsum := quittingRoot_continueProbability_add_quitProbability
    (roots time) player
  have hlower := (abs_lt.mp (hclose time player)).1
  linarith

private theorem absorptionMass_lt_four_mul_of_nearAllContinue
    {roots : BoundaryRootSequence (ι := Fin 4)} {ε : ℝ}
    (hclose : ∀ time player,
      |(roots time player false).toReal - 1| < ε)
    (time : ℕ) :
    quittingRootAbsorptionMass (roots time) < 4 * ε := by
  rw [quittingRootAbsorptionMass,
    quittingStationaryContinueMass_eq_prod_continueProbability]
  have hunion := Math.one_sub_prod_one_sub_le_sum
    (fun player : Fin 4 => (roots time player true).toReal) Finset.univ
    (fun _ _ => ENNReal.toReal_nonneg)
    (fun player _ => ENNReal.toReal_mono ENNReal.one_ne_top
      (PMF.coe_le_one (roots time player) true))
  have hsum :
      (∑ player : Fin 4, (roots time player true).toReal) < 4 * ε := by
    rw [Fin.sum_univ_four]
    have hzero := quitProbability_lt_of_nearAllContinue hclose time 0
    have hone := quitProbability_lt_of_nearAllContinue hclose time 1
    have htwo := quitProbability_lt_of_nearAllContinue hclose time 2
    have hthree := quitProbability_lt_of_nearAllContinue hclose time 3
    linarith
  have hcontinue :
      (∏ player : Fin 4, (roots time player false).toReal) =
        ∏ player : Fin 4, (1 - (roots time player true).toReal) := by
    apply Finset.prod_congr rfl
    intro player _
    have hmass := quittingRoot_continueProbability_add_quitProbability
      (roots time) player
    linarith
  rw [hcontinue]
  exact hunion.trans_lt hsum

/-- Under a near-all-Continue row, quitting immediately pays its owner at
least `1 - 32ε`. -/
private theorem boundary_fixedOpponentsQuitValue_ge
    {roots : BoundaryRootSequence (ι := Fin 4)} {ε : ℝ}
    (hclose : ∀ time player,
      |(roots time player false).toReal - 1| < ε)
    (who : Fin 4) (time : ℕ) :
    1 - 32 * ε ≤ quittingFixedOpponentsQuitValue
      SolanVieilleBoundary.boundaryReward roots who time := by
  have hnear := abs_quittingFixedOpponentsQuitValue_sub_one_le
    SolanVieilleBoundary.boundaryReward_unitSoloExit roots who time
    boundaryReward_abs_le_four
  have hopponent := quittingRootOpponentAbsorptionMass_le_absorptionMass
    (roots time) who
  have habsorption :=
    (absorptionMass_lt_four_mul_of_nearAllContinue hclose time).le
  have hlower := (abs_le.mp hnear).1
  linarith

/-- Under an all-Continue perturbation, terminal `ε`-Nash forces the
probability of never quitting below `2ε`. This coarse constant suffices for
the later argument. -/
theorem boundary_survivalLimit_le_two_mul
    {roots : BoundaryRootSequence (ι := Fin 4)} {ε : ℝ}
    (hε0 : 0 < ε) (hεsmall : ε < 1 / 64)
    (hclose : ∀ time player,
      |(roots time player false).toReal - 1| < ε)
    (hnash : IsBoundaryTerminalApproxNash SolanVieilleBoundary.boundaryReward ε
      (boundaryRootSequenceProfile SolanVieilleBoundary.boundaryReward roots)) :
    quittingJointSurvivalLimit roots 0 ≤ 2 * ε := by
  have hrootNash : IsεQuittingRootSequenceNash
      SolanVieilleBoundary.boundaryReward ε roots :=
    (isεQuittingRootSequenceNash_iff_isεAsymptoticNash
      SolanVieilleBoundary.boundaryReward ε roots).mpr hnash
  by_cases hlimitZero : quittingJointSurvivalLimit roots 0 = 0
  · rw [hlimitZero]
    positivity
  have hlimitPos : 0 < quittingJointSurvivalLimit roots 0 :=
    lt_of_le_of_ne (quittingJointSurvivalLimit_nonneg roots 0)
      (Ne.symm hlimitZero)
  have hvalueTendsto : ∀ who : Fin 4,
      Tendsto (fun time => quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward roots who time)
        atTop (nhds 0) := by
    intro who
    simpa using
      tendsto_quittingRootSequenceTerminalValue_tail_zero_of_survivalLimit_pos
        SolanVieilleBoundary.boundaryReward roots who 0
        boundaryReward_abs_le_four hlimitPos
  let who : Fin 4 := 0
  have hquitLower : ∀ time,
      1 - 32 * ε ≤ quittingFixedOpponentsQuitValue
        SolanVieilleBoundary.boundaryReward roots who time :=
    boundary_fixedOpponentsQuitValue_ge hclose who
  have hstage : ∀ time,
      quittingJointSurvivalWeight roots 0 time *
        ((1 - 32 * ε) - quittingRootSequenceTerminalValue
          SolanVieilleBoundary.boundaryReward roots who time) ≤ ε := by
    intro time
    have htransfer := quittingJointSurvivalWeight_mul_stageDeviationGain_le
      SolanVieilleBoundary.boundaryReward roots hrootNash who time
      (PMF.pure true) (fun offset => roots (time + 1 + offset) who)
    have hupdated :
        quittingRootSuccessorPayoff SolanVieilleBoundary.boundaryReward
          (fun _ => quittingRootSequenceHazardTerminalValue
            SolanVieilleBoundary.boundaryReward
            (fun offset => roots (time + 1 + offset)) who
            (fun offset => roots (time + 1 + offset) who) 0)
          (Function.update (roots time) who (PMF.pure true)) who =
        quittingFixedOpponentsQuitValue
          SolanVieilleBoundary.boundaryReward roots who time := by
      rw [quittingRootSuccessorPayoff,
        quittingRootExpectedPayoff_update_eq_endpointMix]
      simp
      exact quittingRootQuitPayoff_eq_fixedOpponentsQuitValue
        SolanVieilleBoundary.boundaryReward roots who _ time
    rw [hupdated] at htransfer
    have hweight := quittingJointSurvivalWeight_nonneg roots 0 time
    nlinarith [mul_le_mul_of_nonneg_left (hquitLower time) hweight]
  have hleft : Tendsto
      (fun time => quittingJointSurvivalWeight roots 0 time *
        ((1 - 32 * ε) - quittingRootSequenceTerminalValue
          SolanVieilleBoundary.boundaryReward roots who time))
      atTop
      (nhds (quittingJointSurvivalLimit roots 0 * (1 - 32 * ε))) := by
    have hsurvival := tendsto_quittingJointSurvivalLimit roots 0
    have hconstant : Tendsto (fun _ : ℕ => (1 - 32 * ε : ℝ))
        atTop (nhds (1 - 32 * ε)) := tendsto_const_nhds
    simpa [who] using hsurvival.mul (hconstant.sub (hvalueTendsto who))
  have hlimitIneq :
      quittingJointSurvivalLimit roots 0 * (1 - 32 * ε) ≤ ε :=
    le_of_tendsto' hleft hstage
  have hfactor : 1 / 2 < 1 - 32 * ε := by
    linarith
  nlinarith [quittingJointSurvivalLimit_nonneg roots 0]

/-- The second estimate in (13), with a deliberately loose constant: under
an all-Continue perturbation, the probability that the first quitting
coalition contains at least two players is at most `24ε`. -/
theorem boundary_collisionMass_le_twentyFour_mul
    {roots : BoundaryRootSequence (ι := Fin 4)} {ε : ℝ}
    (hε0 : 0 < ε)
    (hclose : ∀ time player,
      |(roots time player false).toReal - 1| < ε) :
    quittingRootSequenceCollisionMass roots 0 ≤ 24 * ε := by
  have hcollision := quittingRootSequenceCollisionMass_le
    roots 0 (4 * ε) fun offset ↦ by
      simpa using
        (absorptionMass_lt_four_mul_of_nearAllContinue hclose offset).le
  have hlimit := quittingJointSurvivalLimit_nonneg roots 0
  norm_num [Nat.choose] at hcollision
  nlinarith

/-- Every singleton quitter in the boundary table contributes total social payoff
`5`. -/
private theorem sum_boundaryReward_singleton (owner : Fin 4) :
    ∑ who : Fin 4, SolanVieilleBoundary.boundaryReward
      (quittingSingletonTerminal owner) who = 5 := by
  change ∑ who : Fin 4,
    quittingSoloReward SolanVieilleBoundary.boundaryReward owner who = 5
  simp_rw [SolanVieilleBoundary.soloReward_eval]
  fin_cases owner <;>
    norm_num [Fin.sum_univ_four, Fin.ext_iff]

/-- The boundary table's social-payoff estimate. Singleton absorption
contributes `5`; multi-quitter
absorption costs at most `16` in total, so after rewriting singleton mass the
loss is at most `21` times collision mass. -/
theorem boundary_sum_terminalValue_ge
    (roots : BoundaryRootSequence (ι := Fin 4)) :
    5 * (1 - quittingJointSurvivalLimit roots 0) -
        21 * quittingRootSequenceCollisionMass roots 0 ≤
      ∑ who : Fin 4, quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward roots who 0 := by
  have hdecomp (who : Fin 4) :=
    quittingRootSequenceTerminalValue_eq_singleton_add_collision
      SolanVieilleBoundary.boundaryReward roots 0 who
  have hcollision (who : Fin 4) :
      -4 * quittingRootSequenceCollisionMass roots 0 ≤
        quittingRootSequenceCollisionRewardContribution
          SolanVieilleBoundary.boundaryReward roots 0 who := by
    have hbound :=
      abs_quittingRootSequenceCollisionRewardContribution_le
        SolanVieilleBoundary.boundaryReward roots 0 who
        boundaryReward_abs_le_four
    simpa [neg_mul] using neg_le_of_abs_le hbound
  have hsumCollision :
      -16 * quittingRootSequenceCollisionMass roots 0 ≤
        ∑ who : Fin 4, quittingRootSequenceCollisionRewardContribution
          SolanVieilleBoundary.boundaryReward roots 0 who := by
    rw [Fin.sum_univ_four]
    have hzero := hcollision 0
    have hone := hcollision 1
    have htwo := hcollision 2
    have hthree := hcollision 3
    linarith
  have hsingleton :
      (∑ who : Fin 4, ∑ owner : Fin 4,
        quittingRootSequenceSingletonMass roots 0 owner *
          SolanVieilleBoundary.boundaryReward
            (quittingSingletonTerminal owner) who) =
        5 * ∑ owner : Fin 4,
          quittingRootSequenceSingletonMass roots 0 owner := by
    rw [Finset.sum_comm, Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro owner _
    rw [← Finset.mul_sum, sum_boundaryReward_singleton]
    ring
  have hmass :=
    sum_quittingRootSequenceSingletonMass_add_collisionMass roots 0
  simp_rw [hdecomp, Finset.sum_add_distrib]
  rw [hsingleton]
  linarith

/-- The payoff conclusion following (13), with loose constants: under a
near-all-Continue `ε`-equilibrium, some player receives at least
`5/4 - 129ε`. -/
theorem boundary_exists_player_value_ge
    {roots : BoundaryRootSequence (ι := Fin 4)} {ε : ℝ}
    (hε0 : 0 < ε) (hεsmall : ε < 1 / 64)
    (hclose : ∀ time player,
      |(roots time player false).toReal - 1| < ε)
    (hnash : IsBoundaryTerminalApproxNash SolanVieilleBoundary.boundaryReward ε
      (boundaryRootSequenceProfile SolanVieilleBoundary.boundaryReward roots)) :
    ∃ who : Fin 4,
      5 / 4 - 129 * ε ≤ quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward roots who 0 := by
  have hsurvival := boundary_survivalLimit_le_two_mul
    hε0 hεsmall hclose hnash
  have hcollision := boundary_collisionMass_le_twentyFour_mul
    hε0 hclose
  have hsocial := boundary_sum_terminalValue_ge roots
  by_contra hno
  push Not at hno
  have hzero := hno 0
  have hone := hno 1
  have htwo := hno 2
  have hthree := hno 3
  rw [Fin.sum_univ_four] at hsocial
  linarith

private theorem boundaryReward_singleton_eq_solo
    (owner who : Fin 4) :
    SolanVieilleBoundary.boundaryReward
      (quittingSingletonTerminal owner) who =
    quittingSoloReward SolanVieilleBoundary.boundaryReward owner who := rfl

/-- A solo quitter pays `1` to itself, `4` to its partner, and `0` to the
opposite pair. -/
private theorem soloReward_eq_self_or_partner (owner who : Fin 4) :
    quittingSoloReward SolanVieilleBoundary.boundaryReward owner who =
      if owner = who then 1
      else if owner = boundaryPartner who then 4 else 0 := by
  fin_cases owner <;> fin_cases who <;> rfl

private theorem singletonReward_sum_eq_pairMass
    (roots : BoundaryRootSequence (ι := Fin 4)) (who : Fin 4) :
    (∑ owner : Fin 4,
      quittingRootSequenceSingletonMass roots 0 owner *
        SolanVieilleBoundary.boundaryReward
          (quittingSingletonTerminal owner) who) =
      quittingRootSequenceSingletonMass roots 0 who +
        4 * quittingRootSequenceSingletonMass roots 0
          (boundaryPartner who) := by
  simp_rw [boundaryReward_singleton_eq_solo,
    soloReward_eq_self_or_partner]
  rw [Fin.sum_univ_four]
  fin_cases who <;> simp [boundaryPartner] <;> ring

private theorem finiteWindow_singletonRewardContribution_eq_pairMass
    {roots : BoundaryRootSequence (ι := Fin 4)}
    (window : QuittingFiniteRootWindow roots) (who : Fin 4) :
    window.singletonRewardContribution
        SolanVieilleBoundary.boundaryReward who =
      window.singletonMass who +
        4 * window.singletonMass (boundaryPartner who) := by
  unfold QuittingFiniteRootWindow.singletonRewardContribution
  simp_rw [boundaryReward_singleton_eq_solo,
    soloReward_eq_self_or_partner]
  rw [Fin.sum_univ_four]
  fin_cases who <;> simp [boundaryPartner] <;> ring

/-- Boundary-table payoff identity up to multi-quitter outcomes: player `i`'s
payoff differs from `rᵢ + 4r_partner(i)` by at most four times collision
mass. -/
theorem boundary_terminalValue_pairMass_approx
    (roots : BoundaryRootSequence (ι := Fin 4)) (who : Fin 4) :
    |quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward roots who 0 -
      (quittingRootSequenceSingletonMass roots 0 who +
        4 * quittingRootSequenceSingletonMass roots 0
          (boundaryPartner who))| ≤
      4 * quittingRootSequenceCollisionMass roots 0 := by
  rw [quittingRootSequenceTerminalValue_eq_singleton_add_collision,
    singletonReward_sum_eq_pairMass]
  simp only [add_sub_cancel_left]
  exact abs_quittingRootSequenceCollisionRewardContribution_le
    SolanVieilleBoundary.boundaryReward roots 0 who
      boundaryReward_abs_le_four

/-- Immediate Quit and `ε`-Nash give every boundary-table player the value floor
`1 - 33ε`. -/
theorem boundary_terminalValue_ge_one_sub_thirtyThree_mul
    {roots : BoundaryRootSequence (ι := Fin 4)} {ε : ℝ}
    (hclose : ∀ time player,
      |(roots time player false).toReal - 1| < ε)
    (hnash : IsBoundaryTerminalApproxNash SolanVieilleBoundary.boundaryReward ε
      (boundaryRootSequenceProfile SolanVieilleBoundary.boundaryReward roots))
    (who : Fin 4) :
    1 - 33 * ε ≤ quittingRootSequenceTerminalValue
      SolanVieilleBoundary.boundaryReward roots who 0 := by
  have hrootNash : IsεQuittingRootSequenceNash
      SolanVieilleBoundary.boundaryReward ε roots :=
    (isεQuittingRootSequenceNash_iff_isεAsymptoticNash
      SolanVieilleBoundary.boundaryReward ε roots).mpr hnash
  have htransfer :=
    quittingJointSurvivalWeight_mul_stageDeviationGain_le
      SolanVieilleBoundary.boundaryReward roots hrootNash who 0
      (PMF.pure true) (fun offset => roots (1 + offset) who)
  have hupdated :
      quittingRootSuccessorPayoff SolanVieilleBoundary.boundaryReward
        (fun _ => quittingRootSequenceHazardTerminalValue
          SolanVieilleBoundary.boundaryReward
          (fun offset => roots (1 + offset)) who
          (fun offset => roots (1 + offset) who) 0)
        (Function.update (roots 0) who (PMF.pure true)) who =
      quittingFixedOpponentsQuitValue
        SolanVieilleBoundary.boundaryReward roots who 0 := by
    rw [quittingRootSuccessorPayoff,
      quittingRootExpectedPayoff_update_eq_endpointMix]
    simp
    exact quittingRootQuitPayoff_eq_fixedOpponentsQuitValue
      SolanVieilleBoundary.boundaryReward roots who _ 0
  rw [hupdated] at htransfer
  have hquit := boundary_fixedOpponentsQuitValue_ge hclose who 0
  simp only [quittingJointSurvivalWeight_zero_fuel, one_mul] at htransfer
  linarith

/-- The singleton-mass lower bound following (13), again with loose
constants: every player is the unique first quitter with probability at
least `2/15 - 61ε`. -/
theorem boundary_singletonMass_ge_two_fifteenths_sub_sixtyOne_mul
    {roots : BoundaryRootSequence (ι := Fin 4)} {ε : ℝ}
    (hε0 : 0 < ε)
    (hclose : ∀ time player,
      |(roots time player false).toReal - 1| < ε)
    (hnash : IsBoundaryTerminalApproxNash SolanVieilleBoundary.boundaryReward ε
      (boundaryRootSequenceProfile SolanVieilleBoundary.boundaryReward roots))
    (who : Fin 4) :
    2 / 15 - 61 * ε ≤
      quittingRootSequenceSingletonMass roots 0 who := by
  have hcollision := boundary_collisionMass_le_twentyFour_mul
    hε0 hclose
  have hpair : ∀ player : Fin 4,
      1 - 129 * ε ≤
        quittingRootSequenceSingletonMass roots 0 player +
          4 * quittingRootSequenceSingletonMass roots 0
            (boundaryPartner player) := by
    intro player
    have hvalue :=
      boundary_terminalValue_ge_one_sub_thirtyThree_mul
        hclose hnash player
    have happ := boundary_terminalValue_pairMass_approx roots player
    have hupper := (abs_le.mp happ).2
    linarith
  have hmass :=
    sum_quittingRootSequenceSingletonMass_add_collisionMass roots 0
  have hcollision0 := quittingRootSequenceCollisionMass_nonneg roots 0
  have hsurvival0 := quittingJointSurvivalLimit_nonneg roots 0
  have hsum :
      (∑ player : Fin 4,
        quittingRootSequenceSingletonMass roots 0 player) ≤ 1 := by
    linarith
  have hzero := hpair 0
  have hone := hpair 1
  have htwo := hpair 2
  have hthree := hpair 3
  change 1 - 129 * ε ≤
    quittingRootSequenceSingletonMass roots 0 0 +
      4 * quittingRootSequenceSingletonMass roots 0 1 at hzero
  change 1 - 129 * ε ≤
    quittingRootSequenceSingletonMass roots 0 1 +
      4 * quittingRootSequenceSingletonMass roots 0 0 at hone
  change 1 - 129 * ε ≤
    quittingRootSequenceSingletonMass roots 0 2 +
      4 * quittingRootSequenceSingletonMass roots 0 3 at htwo
  change 1 - 129 * ε ≤
    quittingRootSequenceSingletonMass roots 0 3 +
      4 * quittingRootSequenceSingletonMass roots 0 2 at hthree
  rw [Fin.sum_univ_four] at hsum
  have hzeroLower : 2 / 15 - 61 * ε ≤
      quittingRootSequenceSingletonMass roots 0 0 := by
    linarith
  have honeLower : 2 / 15 - 61 * ε ≤
      quittingRootSequenceSingletonMass roots 0 1 := by
    linarith
  have htwoLower : 2 / 15 - 61 * ε ≤
      quittingRootSequenceSingletonMass roots 0 2 := by
    linarith
  have hthreeLower : 2 / 15 - 61 * ε ≤
      quittingRootSequenceSingletonMass roots 0 3 := by
    linarith
  fin_cases who
  · exact hzeroLower
  · exact honeLower
  · exact htwoLower
  · exact hthreeLower

/-- The finite chronology estimate behind Lemma 11 of the companion proof.
If player `i`'s continuation value stays at least `1 + δ` through `fuel`,
then `δ` times the probability that `i` is the unique first quitter in that
window is at most the equilibrium error. -/
theorem boundary_delta_mul_finiteSingletonMass_le_epsilon
    {roots : BoundaryRootSequence (ι := Fin 4)} {ε δ : ℝ}
    (hεsmall : ε < 1) (hδ : 0 ≤ δ)
    (hclose : ∀ time player,
      |(roots time player false).toReal - 1| < ε)
    (hnash : IsBoundaryTerminalApproxNash SolanVieilleBoundary.boundaryReward ε
      (boundaryRootSequenceProfile SolanVieilleBoundary.boundaryReward roots))
    (who : Fin 4) (fuel : ℕ)
    (hfloor : ∀ offset, offset < fuel →
      1 + δ ≤ quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward roots who offset) :
    δ * (⟨0, fuel⟩ : QuittingFiniteRootWindow roots).singletonMass who ≤ ε := by
  have hrootNash : IsεQuittingRootSequenceNash
      SolanVieilleBoundary.boundaryReward ε roots :=
    (isεQuittingRootSequenceNash_iff_isεAsymptoticNash
      SolanVieilleBoundary.boundaryReward ε roots).mpr hnash
  have hcontinue : ∀ offset, offset < fuel →
      0 < (roots offset who false).toReal := by
    intro offset _
    have hlower := (abs_lt.mp (hclose offset who)).1
    linarith
  have hgain :=
    delta_mul_sum_jointSurvivalWeight_mul_quitProbability_le_continueUntil_gain
      SolanVieilleBoundary.boundaryReward_cappedJointExit roots who 0 fuel hδ
      (fun offset hoffset => by simpa using hcontinue offset hoffset)
      (fun offset hoffset => by simpa using hfloor offset hoffset)
  let hazard : ℕ → PMF Bool := fun time =>
    if time < fuel then PMF.pure false else roots time who
  have hdeviation := hrootNash who hazard
  have hforced : quittingRootSequenceHazardTerminalValue
      SolanVieilleBoundary.boundaryReward roots who hazard 0 =
      quittingRootSequenceTerminalValue SolanVieilleBoundary.boundaryReward
        (quittingContinueUntilRoots roots who fuel) who 0 := by
    unfold quittingRootSequenceHazardTerminalValue
    rw [show quittingRootSequenceUpdate roots who hazard =
        quittingContinueUntilRoots roots who fuel by
      exact quittingRootSequenceUpdate_continueUntilHazard roots who fuel]
  rw [hforced] at hdeviation
  have hsingleton :
      (⟨0, fuel⟩ : QuittingFiniteRootWindow roots).singletonMass who ≤
        ∑ offset ∈ Finset.range fuel,
          quittingJointSurvivalWeight roots 0 offset *
            (roots offset who true).toReal := by
    rw [← Fin.sum_univ_eq_sum_range]
    apply Finset.sum_le_sum
    intro phase _
    rw [quittingRootCoalitionMass_singleton_eq_opponentContinue_mul_quit]
    simp only [QuittingFiniteRootWindow.survivalWeight,
      QuittingFiniteRootWindow.rootAt, Nat.zero_add]
    have hopponent := quittingStationaryContinueMass_le_one
      (Function.update (roots phase.val) who (PMF.pure false))
    have hsurvival := quittingJointSurvivalWeight_nonneg roots 0 phase.val
    have hquit : 0 ≤ (roots phase.val who true).toReal := ENNReal.toReal_nonneg
    change quittingJointSurvivalWeight roots 0 phase.val *
        (quittingStationaryContinueMass
            (Function.update (roots phase.val) who (PMF.pure false)) *
          (roots phase.val who true).toReal) ≤ _
    nlinarith [mul_nonneg hsurvival hquit,
      mul_nonneg hsurvival
        (mul_nonneg
          (quittingStationaryContinueMass_nonneg
            (Function.update (roots phase.val) who (PMF.pure false))) hquit)]
  have hscaled := mul_le_mul_of_nonneg_left hsingleton hδ
  simp only [Nat.zero_add] at hgain
  linarith

/-- The first stopping-time conclusion in the companion proof: for
`ε < 10⁻⁴`, every player's continuation value eventually falls below
`1 + √ε`. -/
theorem boundary_exists_tail_value_lt_one_add_sqrt
    {roots : BoundaryRootSequence (ι := Fin 4)} {ε : ℝ}
    (hε0 : 0 < ε) (hεsmall : ε < 1 / 10000)
    (hclose : ∀ time player,
      |(roots time player false).toReal - 1| < ε)
    (hnash : IsBoundaryTerminalApproxNash SolanVieilleBoundary.boundaryReward ε
      (boundaryRootSequenceProfile SolanVieilleBoundary.boundaryReward roots))
    (who : Fin 4) :
    ∃ time, quittingRootSequenceTerminalValue
      SolanVieilleBoundary.boundaryReward roots who time <
        1 + Real.sqrt ε := by
  by_contra hnever
  push Not at hnever
  have hsqrt0 : 0 ≤ Real.sqrt ε := Real.sqrt_nonneg ε
  have hsqrtSq : Real.sqrt ε ^ 2 = ε := Real.sq_sqrt hε0.le
  have hsqrtSmall : Real.sqrt ε < 1 / 100 := by
    nlinarith
  have hfinite : ∀ fuel,
      (⟨0, fuel⟩ : QuittingFiniteRootWindow roots).singletonMass who ≤
        Real.sqrt ε := by
    intro fuel
    have hchronology := boundary_delta_mul_finiteSingletonMass_le_epsilon
      (by linarith : ε < 1) hsqrt0 hclose hnash who fuel
      (fun offset _ => hnever offset)
    have hmass0 :=
      (⟨0, fuel⟩ : QuittingFiniteRootWindow roots).singletonMass_nonneg who
    nlinarith
  have hinfinite : quittingRootSequenceSingletonMass roots 0 who ≤
      Real.sqrt ε := by
    exact le_of_tendsto'
      (tendsto_finiteWindow_singletonMass roots 0 who) hfinite
  have hlower :=
    boundary_singletonMass_ge_two_fifteenths_sub_sixtyOne_mul
      hε0 hclose hnash who
  nlinarith

/-- Lemma 12's first-drop estimate. If player `i` starts above `1 + α`, then
at the first time its continuation value falls below `1 + √ε`, little of
`i`'s singleton mass and a controlled positive amount of its partner's mass
have already occurred. -/
theorem boundary_exists_firstDrop_with_partnerMass
    {roots : BoundaryRootSequence (ι := Fin 4)} {ε α : ℝ}
    (hε0 : 0 < ε) (hεsmall : ε < 1 / 10000)
    (hclose : ∀ time player,
      |(roots time player false).toReal - 1| < ε)
    (hnash : IsBoundaryTerminalApproxNash SolanVieilleBoundary.boundaryReward ε
      (boundaryRootSequenceProfile SolanVieilleBoundary.boundaryReward roots))
    (who : Fin 4)
    (hinitial : 1 + α ≤ quittingRootSequenceTerminalValue
      SolanVieilleBoundary.boundaryReward roots who 0)
    (hα : Real.sqrt ε < α) :
    ∃ cutoff : ℕ,
      0 < cutoff ∧
      quittingRootSequenceTerminalValue
          SolanVieilleBoundary.boundaryReward roots who cutoff <
        1 + Real.sqrt ε ∧
      (⟨0, cutoff⟩ : QuittingFiniteRootWindow roots).singletonMass who ≤
        Real.sqrt ε ∧
      (α - 2 * Real.sqrt ε - 96 * ε) / 4 ≤
        (⟨0, cutoff⟩ : QuittingFiniteRootWindow roots).singletonMass
          (boundaryPartner who) := by
  have hexists := boundary_exists_tail_value_lt_one_add_sqrt
    hε0 hεsmall hclose hnash who
  let cutoff := Nat.find hexists
  have hdrop : quittingRootSequenceTerminalValue
      SolanVieilleBoundary.boundaryReward roots who cutoff <
        1 + Real.sqrt ε := Nat.find_spec hexists
  have hcutoffPos : 0 < cutoff := by
    by_contra hnot
    have hzero : cutoff = 0 := Nat.eq_zero_of_not_pos hnot
    rw [hzero] at hdrop
    linarith
  have hbefore : ∀ offset, offset < cutoff →
      1 + Real.sqrt ε ≤ quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward roots who offset := by
    intro offset hoffset
    exact le_of_not_gt (Nat.find_min hexists hoffset)
  have hsqrt0 : 0 ≤ Real.sqrt ε := Real.sqrt_nonneg ε
  have hsqrtPos : 0 < Real.sqrt ε := Real.sqrt_pos.2 hε0
  have hsqrtSq : Real.sqrt ε ^ 2 = ε := Real.sq_sqrt hε0.le
  have hchronology := boundary_delta_mul_finiteSingletonMass_le_epsilon
    (by linarith : ε < 1) hsqrt0 hclose hnash who cutoff hbefore
  have hown0 :=
    (⟨0, cutoff⟩ : QuittingFiniteRootWindow roots).singletonMass_nonneg who
  have hown :
      (⟨0, cutoff⟩ : QuittingFiniteRootWindow roots).singletonMass who ≤
        Real.sqrt ε := by
    nlinarith
  let window : QuittingFiniteRootWindow roots := ⟨0, cutoff⟩
  have hdecomp := window.terminalValue_eq_singleton_add_collision_add_survival_mul
    SolanVieilleBoundary.boundaryReward who
  have hsingleton :=
    finiteWindow_singletonRewardContribution_eq_pairMass window who
  rw [hsingleton] at hdecomp
  have hcollisionAbs := window.abs_collisionRewardContribution_le
    SolanVieilleBoundary.boundaryReward who boundaryReward_abs_le_four
  have hcollisionReward := (abs_le.mp hcollisionAbs).2
  have hcollisionFinite : window.collisionMass ≤ 24 * ε :=
    (finiteWindow_collisionMass_le_sequenceCollisionMass roots 0 cutoff).trans
      (boundary_collisionMass_le_twentyFour_mul hε0 hclose)
  have hsurvival0 := quittingJointSurvivalWeight_nonneg roots 0 cutoff
  have hsurvival1 := quittingJointSurvivalWeight_le_one roots 0 cutoff
  have htail : quittingJointSurvivalWeight roots 0 cutoff *
      quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward roots who cutoff ≤
      1 + Real.sqrt ε := by
    calc
      _ ≤ quittingJointSurvivalWeight roots 0 cutoff *
          (1 + Real.sqrt ε) :=
        mul_le_mul_of_nonneg_left hdrop.le hsurvival0
      _ ≤ 1 * (1 + Real.sqrt ε) :=
        mul_le_mul_of_nonneg_right hsurvival1 (by positivity)
      _ = 1 + Real.sqrt ε := one_mul _
  refine ⟨cutoff, hcutoffPos, hdrop, hown, ?_⟩
  change (α - 2 * Real.sqrt ε - 96 * ε) / 4 ≤
    window.singletonMass (boundaryPartner who)
  have hdecomp0 : quittingRootSequenceTerminalValue
      SolanVieilleBoundary.boundaryReward roots who 0 =
        window.singletonMass who +
          4 * window.singletonMass (boundaryPartner who) +
          window.collisionRewardContribution
            SolanVieilleBoundary.boundaryReward who +
          quittingJointSurvivalWeight roots 0 cutoff *
            quittingRootSequenceTerminalValue
              SolanVieilleBoundary.boundaryReward roots who cutoff := by
    simpa [window] using hdecomp
  change window.singletonMass who ≤ Real.sqrt ε at hown
  linarith

private theorem finiteWindow_singletonTotal_eq_four_roles
    {roots : BoundaryRootSequence (ι := Fin 4)}
    (window : QuittingFiniteRootWindow roots) (who : Fin 4) :
    window.singletonTotal =
      window.singletonMass who +
        window.singletonMass (boundaryPartner who) +
        window.singletonMass (boundaryOppositeFirst who) +
        window.singletonMass (boundaryOppositeSecond who) := by
  unfold QuittingFiniteRootWindow.singletonTotal
  rw [Fin.sum_univ_four]
  fin_cases who <;>
    simp [boundaryPartner, boundaryOppositeFirst, boundaryOppositeSecond] <;>
    ring

/-- Corollary 13, with constants adapted to the collision allowance: two
partners cannot both begin more than `7√ε` above their solo-quitting value. -/
theorem boundary_not_both_partners_high
    {roots : BoundaryRootSequence (ι := Fin 4)} {ε α : ℝ}
    (hε0 : 0 < ε) (hεsmall : ε < 1 / 10000)
    (hclose : ∀ time player,
      |(roots time player false).toReal - 1| < ε)
    (hnash : IsBoundaryTerminalApproxNash SolanVieilleBoundary.boundaryReward ε
      (boundaryRootSequenceProfile SolanVieilleBoundary.boundaryReward roots))
    (who : Fin 4) (hα : 7 * Real.sqrt ε < α) :
    ¬ (1 + α ≤ quittingRootSequenceTerminalValue
          SolanVieilleBoundary.boundaryReward roots who 0 ∧
        1 + α ≤ quittingRootSequenceTerminalValue
          SolanVieilleBoundary.boundaryReward roots (boundaryPartner who) 0) := by
  rintro ⟨hwhoInitial, hpartnerInitial⟩
  have hsqrtPos : 0 < Real.sqrt ε := Real.sqrt_pos.2 hε0
  have hsqrtSq : Real.sqrt ε ^ 2 = ε := Real.sq_sqrt hε0.le
  have hsqrtSmall : Real.sqrt ε < 1 / 100 := by
    nlinarith
  have hmargin : Real.sqrt ε <
      (α - 2 * Real.sqrt ε - 96 * ε) / 4 := by
    nlinarith
  obtain ⟨whoCutoff, _, _, hwhoSmall, hpartnerLarge⟩ :=
    boundary_exists_firstDrop_with_partnerMass hε0 hεsmall hclose hnash who
      hwhoInitial (by linarith)
  obtain ⟨partnerCutoff, _, _, hpartnerSmall, hwhoLarge⟩ :=
    boundary_exists_firstDrop_with_partnerMass hε0 hεsmall hclose hnash
      (boundaryPartner who) hpartnerInitial (by linarith)
  rw [boundaryPartner_partner] at hwhoLarge
  rcases le_total whoCutoff partnerCutoff with hcutoffs | hcutoffs
  · have hmono := finiteWindow_singletonMass_mono_fuel
      roots 0 (boundaryPartner who) hcutoffs
    nlinarith
  · have hmono := finiteWindow_singletonMass_mono_fuel
      roots 0 who hcutoffs
    nlinarith

/-- The second stopping-time preparation from the companion proof. Before
the first high player's drop, its partner must itself have a low continuation
value; that earlier stage is still reached with probability at least `1/8`. -/
theorem boundary_exists_partnerDrop_before_with_reach
    {roots : BoundaryRootSequence (ι := Fin 4)} {ε α : ℝ}
    (hε0 : 0 < ε) (hεsmall : ε < 1 / 1000000)
    (hclose : ∀ time player,
      |(roots time player false).toReal - 1| < ε)
    (hnash : IsBoundaryTerminalApproxNash SolanVieilleBoundary.boundaryReward ε
      (boundaryRootSequenceProfile SolanVieilleBoundary.boundaryReward roots))
    (who : Fin 4)
    (hinitial : 1 + α ≤ quittingRootSequenceTerminalValue
      SolanVieilleBoundary.boundaryReward roots who 0)
    (hmargin : Real.sqrt ε <
      (α - 2 * Real.sqrt ε - 96 * ε) / 4) :
    ∃ firstDrop partnerDrop : ℕ,
      partnerDrop < firstDrop ∧
      quittingRootSequenceTerminalValue
          SolanVieilleBoundary.boundaryReward roots
          (boundaryPartner who) partnerDrop < 1 + Real.sqrt ε ∧
      (⟨0, firstDrop⟩ : QuittingFiniteRootWindow roots).singletonMass who ≤
        Real.sqrt ε ∧
      (α - 2 * Real.sqrt ε - 96 * ε) / 4 ≤
        (⟨0, firstDrop⟩ : QuittingFiniteRootWindow roots).singletonMass
          (boundaryPartner who) ∧
      1 / 8 ≤ quittingJointSurvivalWeight roots 0 partnerDrop := by
  have hεsmall' : ε < 1 / 10000 := by linarith
  have hsqrtPos : 0 < Real.sqrt ε := Real.sqrt_pos.2 hε0
  obtain ⟨firstDrop, _, _, hownSmall, hpartnerLarge⟩ :=
    boundary_exists_firstDrop_with_partnerMass hε0 hεsmall' hclose hnash who
      hinitial (by linarith)
  have hexistsLow : ∃ partnerDrop, partnerDrop < firstDrop ∧
      quittingRootSequenceTerminalValue
          SolanVieilleBoundary.boundaryReward roots
          (boundaryPartner who) partnerDrop < 1 + Real.sqrt ε := by
    by_contra hnone
    push Not at hnone
    have hfloor : ∀ offset, offset < firstDrop →
        1 + Real.sqrt ε ≤ quittingRootSequenceTerminalValue
          SolanVieilleBoundary.boundaryReward roots
            (boundaryPartner who) offset := by
      intro offset hoffset
      exact hnone offset hoffset
    have hchronology := boundary_delta_mul_finiteSingletonMass_le_epsilon
      (by linarith : ε < 1) (Real.sqrt_nonneg ε) hclose hnash
      (boundaryPartner who) firstDrop hfloor
    have hsqrtSq : Real.sqrt ε ^ 2 = ε := Real.sq_sqrt hε0.le
    have hmass0 :=
      (⟨0, firstDrop⟩ : QuittingFiniteRootWindow roots).singletonMass_nonneg
        (boundaryPartner who)
    nlinarith [mul_pos hsqrtPos (sub_pos.mpr
      (lt_of_lt_of_le hmargin hpartnerLarge))]
  obtain ⟨partnerDrop, hpartnerBefore, hpartnerLow⟩ := hexistsLow
  have hprefixOwn := finiteWindow_singletonMass_mono_fuel
    roots 0 who hpartnerBefore.le
  have htotalOwn :=
    boundary_singletonMass_ge_two_fifteenths_sub_sixtyOne_mul
      hε0 hclose hnash who
  have hreach := sequenceSingletonMass_sub_finiteWindow_le_survivalWeight
    roots 0 partnerDrop who
  have hsqrtSq : Real.sqrt ε ^ 2 = ε := Real.sq_sqrt hε0.le
  have hsqrtSmall : Real.sqrt ε < 1 / 1000 := by
    nlinarith
  refine ⟨firstDrop, partnerDrop, hpartnerBefore, hpartnerLow,
    hownSmall, hpartnerLarge, ?_⟩
  nlinarith

/-- Choose the preceding partner drop to be the last low continuation time.
Every strictly later continuation before the first drop is then at least
`1 + √ε`. -/
theorem boundary_exists_lastPartnerDrop_with_reach
    {roots : BoundaryRootSequence (ι := Fin 4)} {ε α : ℝ}
    (hε0 : 0 < ε) (hεsmall : ε < 1 / 1000000)
    (hclose : ∀ time player,
      |(roots time player false).toReal - 1| < ε)
    (hnash : IsBoundaryTerminalApproxNash SolanVieilleBoundary.boundaryReward ε
      (boundaryRootSequenceProfile SolanVieilleBoundary.boundaryReward roots))
    (who : Fin 4)
    (hinitial : 1 + α ≤ quittingRootSequenceTerminalValue
      SolanVieilleBoundary.boundaryReward roots who 0)
    (hmargin : Real.sqrt ε <
      (α - 2 * Real.sqrt ε - 96 * ε) / 4) :
    ∃ firstDrop partnerDrop : ℕ,
      partnerDrop < firstDrop ∧
      quittingRootSequenceTerminalValue
          SolanVieilleBoundary.boundaryReward roots
          (boundaryPartner who) partnerDrop < 1 + Real.sqrt ε ∧
      (∀ time, partnerDrop < time → time < firstDrop →
        1 + Real.sqrt ε ≤ quittingRootSequenceTerminalValue
          SolanVieilleBoundary.boundaryReward roots
            (boundaryPartner who) time) ∧
      (⟨0, firstDrop⟩ : QuittingFiniteRootWindow roots).singletonMass who ≤
        Real.sqrt ε ∧
      (α - 2 * Real.sqrt ε - 96 * ε) / 4 ≤
        (⟨0, firstDrop⟩ : QuittingFiniteRootWindow roots).singletonMass
          (boundaryPartner who) ∧
      1 / 8 ≤ quittingJointSurvivalWeight roots 0 partnerDrop := by
  obtain ⟨firstDrop, witness, hwitnessBefore, hwitnessLow,
      hownSmall, hpartnerLarge, _⟩ :=
    boundary_exists_partnerDrop_before_with_reach hε0 hεsmall hclose hnash who
      hinitial hmargin
  let lowTimes := (Finset.range firstDrop).filter fun time =>
    quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward roots
        (boundaryPartner who) time < 1 + Real.sqrt ε
  have hlowTimes : lowTimes.Nonempty := by
    exact ⟨witness, Finset.mem_filter.mpr
      ⟨Finset.mem_range.mpr hwitnessBefore, hwitnessLow⟩⟩
  let partnerDrop := lowTimes.max' hlowTimes
  have hpartnerMem : partnerDrop ∈ lowTimes :=
    Finset.max'_mem lowTimes hlowTimes
  have hpartnerBefore : partnerDrop < firstDrop :=
    Finset.mem_range.mp (Finset.mem_filter.mp hpartnerMem).1
  have hpartnerLow : quittingRootSequenceTerminalValue
      SolanVieilleBoundary.boundaryReward roots
      (boundaryPartner who) partnerDrop < 1 + Real.sqrt ε :=
    (Finset.mem_filter.mp hpartnerMem).2
  have hafter : ∀ time, partnerDrop < time → time < firstDrop →
      1 + Real.sqrt ε ≤ quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward roots
          (boundaryPartner who) time := by
    intro time hdropTime htime
    apply le_of_not_gt
    intro hlow
    have hmem : time ∈ lowTimes :=
      Finset.mem_filter.mpr ⟨Finset.mem_range.mpr htime, hlow⟩
    exact (not_le_of_gt hdropTime) (Finset.le_max' lowTimes time hmem)
  have hprefixOwn := finiteWindow_singletonMass_mono_fuel
    roots 0 who hpartnerBefore.le
  have htotalOwn :=
    boundary_singletonMass_ge_two_fifteenths_sub_sixtyOne_mul
      hε0 hclose hnash who
  have hreach := sequenceSingletonMass_sub_finiteWindow_le_survivalWeight
    roots 0 partnerDrop who
  have hsqrtSq : Real.sqrt ε ^ 2 = ε := Real.sq_sqrt hε0.le
  have hsqrtSmall : Real.sqrt ε < 1 / 1000 := by
    nlinarith
  refine ⟨firstDrop, partnerDrop, hpartnerBefore, hpartnerLow, hafter,
    hownSmall, hpartnerLarge, ?_⟩
  nlinarith

/-- Between the last partner drop and the first drop, Lemma 11 can be applied
to the restarted `8ε`-equilibrium. Thus almost all partner mass already lies
before the last low-continuation time. -/
theorem boundary_exists_partnerDrop_with_retained_mass
    {roots : BoundaryRootSequence (ι := Fin 4)} {ε α : ℝ}
    (hε0 : 0 < ε) (hεsmall : ε < 1 / 1000000)
    (hclose : ∀ time player,
      |(roots time player false).toReal - 1| < ε)
    (hnash : IsBoundaryTerminalApproxNash SolanVieilleBoundary.boundaryReward ε
      (boundaryRootSequenceProfile SolanVieilleBoundary.boundaryReward roots))
    (who : Fin 4)
    (hinitial : 1 + α ≤ quittingRootSequenceTerminalValue
      SolanVieilleBoundary.boundaryReward roots who 0)
    (hmargin : Real.sqrt ε <
      (α - 2 * Real.sqrt ε - 96 * ε) / 4) :
    ∃ partnerDrop : ℕ,
      quittingRootSequenceTerminalValue
          SolanVieilleBoundary.boundaryReward roots
          (boundaryPartner who) partnerDrop < 1 + Real.sqrt ε ∧
      (⟨0, partnerDrop⟩ : QuittingFiniteRootWindow roots).singletonMass who ≤
        Real.sqrt ε ∧
      (α - 38 * Real.sqrt ε - 100 * ε) / 4 ≤
        (⟨0, partnerDrop⟩ : QuittingFiniteRootWindow roots).singletonMass
          (boundaryPartner who) ∧
      1 / 8 ≤ quittingJointSurvivalWeight roots 0 partnerDrop := by
  obtain ⟨firstDrop, partnerDrop, hpartnerBefore, hpartnerLow, hafter,
      hownSmall, hpartnerLarge, hpartnerReach⟩ :=
    boundary_exists_lastPartnerDrop_with_reach hε0 hεsmall hclose hnash who
      hinitial hmargin
  let restart := partnerDrop + 1
  have hrestartLe : restart ≤ firstDrop := by
    dsimp only [restart]
    omega
  have hrestartOwn := finiteWindow_singletonMass_mono_fuel
    roots 0 who hrestartLe
  have htotalOwn :=
    boundary_singletonMass_ge_two_fifteenths_sub_sixtyOne_mul
      hε0 hclose hnash who
  have hrestartReachBound :=
    sequenceSingletonMass_sub_finiteWindow_le_survivalWeight
      roots 0 restart who
  have hsqrtSq : Real.sqrt ε ^ 2 = ε := Real.sq_sqrt hε0.le
  have hsqrtPos : 0 < Real.sqrt ε := Real.sqrt_pos.2 hε0
  have hsqrtSmall : Real.sqrt ε < 1 / 1000 := by
    nlinarith
  have hrestartReach : 1 / 8 ≤
      quittingJointSurvivalWeight roots 0 restart := by
    nlinarith
  let shifted : BoundaryRootSequence (ι := Fin 4) :=
    fun offset => roots (restart + offset)
  have hrootNash : IsεQuittingRootSequenceNash
      SolanVieilleBoundary.boundaryReward ε roots :=
    (isεQuittingRootSequenceNash_iff_isεAsymptoticNash
      SolanVieilleBoundary.boundaryReward ε roots).mpr hnash
  have hshiftRootNash : IsεQuittingRootSequenceNash
      SolanVieilleBoundary.boundaryReward (8 * ε) shifted := by
    have hshift := isεQuittingRootSequenceNash_shift_of_survival_ge
      SolanVieilleBoundary.boundaryReward roots hε0.le
      (by norm_num : (0 : ℝ) < 1 / 8) hrootNash restart hrestartReach
    simpa [shifted, mul_comm] using hshift
  have hshiftNash : IsBoundaryTerminalApproxNash
      SolanVieilleBoundary.boundaryReward (8 * ε)
      (boundaryRootSequenceProfile SolanVieilleBoundary.boundaryReward shifted) :=
    (isεQuittingRootSequenceNash_iff_isεAsymptoticNash
      SolanVieilleBoundary.boundaryReward (8 * ε) shifted).mp hshiftRootNash
  have hshiftClose : ∀ time player,
      |(shifted time player false).toReal - 1| < 8 * ε := by
    intro time player
    have := hclose (restart + time) player
    dsimp only [shifted]
    linarith
  let tailFuel := firstDrop - restart
  have htailFloor : ∀ offset, offset < tailFuel →
      1 + Real.sqrt ε ≤ quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward shifted
          (boundaryPartner who) offset := by
    intro offset hoffset
    have hglobal := hafter (restart + offset) (by
      dsimp only [restart]
      omega) (by
      dsimp only [tailFuel] at hoffset
      omega)
    rw [quittingRootSequenceTerminalValue_eq_shift
      SolanVieilleBoundary.boundaryReward shifted (boundaryPartner who) offset]
    rw [quittingRootSequenceTerminalValue_eq_shift
      SolanVieilleBoundary.boundaryReward roots (boundaryPartner who)
        (restart + offset)] at hglobal
    simpa [shifted, Nat.add_assoc] using hglobal
  have htailChronology := boundary_delta_mul_finiteSingletonMass_le_epsilon
    (by nlinarith : 8 * ε < 1) (Real.sqrt_nonneg ε) hshiftClose hshiftNash
    (boundaryPartner who) tailFuel htailFloor
  have htailMass0 :=
    (⟨0, tailFuel⟩ : QuittingFiniteRootWindow shifted).singletonMass_nonneg
      (boundaryPartner who)
  have htailMass :
      (⟨0, tailFuel⟩ : QuittingFiniteRootWindow shifted).singletonMass
          (boundaryPartner who) ≤ 8 * Real.sqrt ε := by
    nlinarith
  let beforeRestart : QuittingFiniteRootWindow roots := ⟨0, restart⟩
  let afterRestart : QuittingFiniteRootWindow roots := ⟨restart, tailFuel⟩
  have hadjacent : beforeRestart.ChronologicallyAdjacent afterRestart := by
    simp [QuittingFiniteRootWindow.ChronologicallyAdjacent,
      beforeRestart, afterRestart]
  have hconcat := beforeRestart.singletonMass_concat afterRestart hadjacent
    (boundaryPartner who)
  have hconcat' :
      (⟨0, firstDrop⟩ : QuittingFiniteRootWindow roots).singletonMass
          (boundaryPartner who) =
        beforeRestart.singletonMass (boundaryPartner who) +
          quittingJointSurvivalWeight roots 0 restart *
            afterRestart.singletonMass (boundaryPartner who) := by
    change (⟨0, restart + tailFuel⟩ : QuittingFiniteRootWindow roots).singletonMass
        (boundaryPartner who) = _ at hconcat
    rw [show restart + tailFuel = firstDrop by
      dsimp only [tailFuel]
      omega] at hconcat
    simpa [beforeRestart, afterRestart] using hconcat
  have hafterEq : afterRestart.singletonMass (boundaryPartner who) =
      (⟨0, tailFuel⟩ : QuittingFiniteRootWindow shifted).singletonMass
        (boundaryPartner who) := by
    unfold QuittingFiniteRootWindow.singletonMass
      QuittingFiniteRootWindow.survivalWeight QuittingFiniteRootWindow.rootAt
    apply Finset.sum_congr rfl
    intro phase _
    rw [quittingJointSurvivalWeight_eq_shift]
    simp [afterRestart, shifted]
  rw [hafterEq] at hconcat'
  have hsurvivalRestart := quittingJointSurvivalWeight_le_one roots 0 restart
  have hsurvivalRestart0 := quittingJointSurvivalWeight_nonneg roots 0 restart
  have hbeforeRestartLower :
      (α - 2 * Real.sqrt ε - 96 * ε) / 4 - 8 * Real.sqrt ε ≤
        beforeRestart.singletonMass (boundaryPartner who) := by
    have htransport : quittingJointSurvivalWeight roots 0 restart *
        (⟨0, tailFuel⟩ : QuittingFiniteRootWindow shifted).singletonMass
            (boundaryPartner who) ≤ 8 * Real.sqrt ε := by
      calc
        _ ≤ 1 * (⟨0, tailFuel⟩ : QuittingFiniteRootWindow shifted).singletonMass
            (boundaryPartner who) :=
          mul_le_mul_of_nonneg_right hsurvivalRestart htailMass0
        _ ≤ 8 * Real.sqrt ε := by simpa using htailMass
    linarith
  let beforeDrop : QuittingFiniteRootWindow roots := ⟨0, partnerDrop⟩
  let dropStage : QuittingFiniteRootWindow roots := ⟨partnerDrop, 1⟩
  have hdropAdjacent : beforeDrop.ChronologicallyAdjacent dropStage := by
    simp [QuittingFiniteRootWindow.ChronologicallyAdjacent,
      beforeDrop, dropStage]
  have hdropConcat := beforeDrop.singletonMass_concat dropStage hdropAdjacent
    (boundaryPartner who)
  have hdropConcat' : beforeRestart.singletonMass (boundaryPartner who) =
      beforeDrop.singletonMass (boundaryPartner who) +
        quittingJointSurvivalWeight roots 0 partnerDrop *
          dropStage.singletonMass (boundaryPartner who) := by
    change (⟨0, partnerDrop + 1⟩ : QuittingFiniteRootWindow roots).singletonMass
        (boundaryPartner who) = _ at hdropConcat
    simpa [beforeDrop, dropStage, beforeRestart, restart] using hdropConcat
  have hdropStageMass : dropStage.singletonMass (boundaryPartner who) < ε := by
    dsimp only [dropStage]
    unfold QuittingFiniteRootWindow.singletonMass
      QuittingFiniteRootWindow.survivalWeight QuittingFiniteRootWindow.rootAt
    simp only [Fin.sum_univ_one, Fin.val_zero,
      quittingJointSurvivalWeight_zero_fuel, one_mul, Nat.add_zero]
    rw [quittingRootCoalitionMass_singleton_eq_opponentContinue_mul_quit]
    have hopponent := quittingStationaryContinueMass_le_one
      (Function.update (roots partnerDrop) (boundaryPartner who) (PMF.pure false))
    have hquit := quitProbability_lt_of_nearAllContinue hclose partnerDrop
      (boundaryPartner who)
    have hquit0 : 0 ≤ (roots partnerDrop (boundaryPartner who) true).toReal :=
      ENNReal.toReal_nonneg
    nlinarith [mul_nonneg
      (quittingStationaryContinueMass_nonneg
        (Function.update (roots partnerDrop) (boundaryPartner who) (PMF.pure false)))
      hquit0]
  have hdropSurvival :=
    quittingJointSurvivalWeight_le_one roots 0 partnerDrop
  have hdropSurvival0 :=
    quittingJointSurvivalWeight_nonneg roots 0 partnerDrop
  have hbeforeDropLower :
      (α - 38 * Real.sqrt ε - 100 * ε) / 4 ≤
        beforeDrop.singletonMass (boundaryPartner who) := by
    have hdropTransport : quittingJointSurvivalWeight roots 0 partnerDrop *
        dropStage.singletonMass (boundaryPartner who) ≤ ε := by
      calc
        _ ≤ 1 * dropStage.singletonMass (boundaryPartner who) :=
          mul_le_mul_of_nonneg_right hdropSurvival
            (dropStage.singletonMass_nonneg (boundaryPartner who))
        _ ≤ ε := by simpa using hdropStageMass.le
    linarith
  have hownDrop := finiteWindow_singletonMass_mono_fuel
    roots 0 who hpartnerBefore.le
  refine ⟨partnerDrop, hpartnerLow, ?_, ?_, hpartnerReach⟩
  · exact hownDrop.trans hownSmall
  · exact hbeforeDropLower

private theorem boundary_shifted_opposite_pair_contradiction
    {roots : BoundaryRootSequence (ι := Fin 4)} {ε : ℝ}
    (hε0 : 0 < ε) (hεsmall : ε < 1 / 1000000000000)
    (hclose : ∀ time player,
      |(roots time player false).toReal - 1| < ε)
    (hnash : IsBoundaryTerminalApproxNash SolanVieilleBoundary.boundaryReward ε
      (boundaryRootSequenceProfile SolanVieilleBoundary.boundaryReward roots))
    (who : Fin 4) (drop : ℕ)
    (hreach : 1 / 8 ≤ quittingJointSurvivalWeight roots 0 drop)
    (hfirstHigh : 1 + 1 / 100 ≤ quittingRootSequenceTerminalValue
      SolanVieilleBoundary.boundaryReward roots (boundaryOppositeFirst who) drop)
    (hsecondHigh : 1 + 1 / 100 ≤ quittingRootSequenceTerminalValue
      SolanVieilleBoundary.boundaryReward roots (boundaryOppositeSecond who) drop) :
    False := by
  let shifted : BoundaryRootSequence (ι := Fin 4) := fun offset => roots (drop + offset)
  have hrootNash : IsεQuittingRootSequenceNash
      SolanVieilleBoundary.boundaryReward ε roots :=
    (isεQuittingRootSequenceNash_iff_isεAsymptoticNash
      SolanVieilleBoundary.boundaryReward ε roots).mpr hnash
  have hshiftRootNash : IsεQuittingRootSequenceNash
      SolanVieilleBoundary.boundaryReward (8 * ε) shifted := by
    have hshift := isεQuittingRootSequenceNash_shift_of_survival_ge
      SolanVieilleBoundary.boundaryReward roots hε0.le
      (by norm_num : (0 : ℝ) < 1 / 8) hrootNash drop hreach
    simpa [shifted, mul_comm] using hshift
  have hshiftNash : IsBoundaryTerminalApproxNash
      SolanVieilleBoundary.boundaryReward (8 * ε)
      (boundaryRootSequenceProfile SolanVieilleBoundary.boundaryReward shifted) :=
    (isεQuittingRootSequenceNash_iff_isεAsymptoticNash
      SolanVieilleBoundary.boundaryReward (8 * ε) shifted).mp hshiftRootNash
  have hshiftClose : ∀ time player,
      |(shifted time player false).toReal - 1| < 8 * ε := by
    intro time player
    have := hclose (drop + time) player
    dsimp only [shifted]
    linarith
  have hshiftSmall : 8 * ε < 1 / 10000 := by linarith
  have hsqrtEightSq : Real.sqrt (8 * ε) ^ 2 = 8 * ε :=
    Real.sq_sqrt (mul_nonneg (by norm_num) hε0.le)
  have hsqrtEight0 : 0 ≤ Real.sqrt (8 * ε) := Real.sqrt_nonneg _
  have htailNotBoth := boundary_not_both_partners_high
    (mul_pos (by norm_num) hε0) hshiftSmall hshiftClose hshiftNash
    (boundaryOppositeFirst who) (α := 1 / 100) (by nlinarith)
  apply htailNotBoth
  constructor
  · change 1 + 1 / 100 ≤ quittingRootSequenceTerminalValue
      SolanVieilleBoundary.boundaryReward (fun offset => roots (drop + offset))
        (boundaryOppositeFirst who) 0
    rw [← quittingRootSequenceTerminalValue_eq_shift]
    exact hfirstHigh
  · rw [boundaryPartner_oppositeFirst]
    change 1 + 1 / 100 ≤ quittingRootSequenceTerminalValue
      SolanVieilleBoundary.boundaryReward (fun offset => roots (drop + offset))
        (boundaryOppositeSecond who) 0
    rw [← quittingRootSequenceTerminalValue_eq_shift]
    exact hsecondHigh

/-- For every sufficiently small positive `ε`, no terminal `ε`-equilibrium
remains `ε`-close to all-Continue at every stage. -/
theorem no_nearAllContinue_terminalApproximateEquilibrium :
  ∃ ε₀ : ℝ, 0 < ε₀ ∧ ∀ ε, 0 < ε → ε < ε₀ →
    ¬ ∃ roots : BoundaryRootSequence (ι := Fin 4),
      (∀ time player,
        |(roots time player false).toReal - 1| < ε) ∧
      IsBoundaryTerminalApproxNash SolanVieilleBoundary.boundaryReward ε
        (boundaryRootSequenceProfile SolanVieilleBoundary.boundaryReward roots) := by
  refine ⟨1 / 1000000000000, by norm_num, ?_⟩
  intro ε hε0 hεsmall
  rintro ⟨roots, hclose, hnash⟩
  have hsqrtPos : 0 < Real.sqrt ε := Real.sqrt_pos.2 hε0
  have hsqrtSq : Real.sqrt ε ^ 2 = ε := Real.sq_sqrt hε0.le
  have hsqrtSmall : Real.sqrt ε < 1 / 1000000 := by
    nlinarith
  have hεmillion : ε < 1 / 1000000 := by linarith
  obtain ⟨who, hwhoHigh⟩ := boundary_exists_player_value_ge
    hε0 (by linarith : ε < 1 / 64) hclose hnash
  let α : ℝ := 1 / 4 - 129 * ε
  have hwhoInitial : 1 + α ≤ quittingRootSequenceTerminalValue
      SolanVieilleBoundary.boundaryReward roots who 0 := by
    dsimp only [α]
    linarith
  have hmargin : Real.sqrt ε <
      (α - 2 * Real.sqrt ε - 96 * ε) / 4 := by
    dsimp only [α]
    nlinarith
  obtain ⟨drop, hpartnerLow, hownSmall, hpartnerMass, hreach⟩ :=
    boundary_exists_partnerDrop_with_retained_mass hε0 hεmillion hclose hnash
      who hwhoInitial hmargin
  let window : QuittingFiniteRootWindow roots := ⟨0, drop⟩
  let ownMass := window.singletonMass who
  let partnerMass := window.singletonMass (boundaryPartner who)
  let firstOppositeMass := window.singletonMass (boundaryOppositeFirst who)
  let secondOppositeMass := window.singletonMass (boundaryOppositeSecond who)
  let collisionMass := window.collisionMass
  let survival := quittingJointSurvivalWeight roots 0 drop
  have hownMass : ownMass ≤ Real.sqrt ε := by
    simpa [window, ownMass] using hownSmall
  have hpartnerMass' :
      (α - 38 * Real.sqrt ε - 100 * ε) / 4 ≤ partnerMass := by
    simpa [window, partnerMass] using hpartnerMass
  have hcollision : collisionMass ≤ 24 * ε := by
    dsimp only [collisionMass, window]
    exact (finiteWindow_collisionMass_le_sequenceCollisionMass roots 0 drop).trans
      (boundary_collisionMass_le_twentyFour_mul hε0 hclose)
  have hcollision0 : 0 ≤ collisionMass := window.collisionMass_nonneg
  have hsurvival0 : 0 ≤ survival :=
    quittingJointSurvivalWeight_nonneg roots 0 drop
  have hsurvival1 : survival ≤ 1 :=
    quittingJointSurvivalWeight_le_one roots 0 drop
  have hfirstOpposite0 : 0 ≤ firstOppositeMass :=
    window.singletonMass_nonneg _
  have hsecondOpposite0 : 0 ≤ secondOppositeMass :=
    window.singletonMass_nonneg _
  have hown0 : 0 ≤ ownMass := window.singletonMass_nonneg _
  have hpartner0 : 0 ≤ partnerMass := window.singletonMass_nonneg _
  have hmass : ownMass + partnerMass + firstOppositeMass +
      secondOppositeMass + collisionMass + survival = 1 := by
    have habsorption := window.absorptionMass_eq_one_sub_survivalWeight
    have hsplit := window.absorptionMass_eq_singletonTotal_add_collisionMass
    have hroles := finiteWindow_singletonTotal_eq_four_roles window who
    dsimp only [window] at habsorption
    dsimp only [ownMass, partnerMass, firstOppositeMass,
      secondOppositeMass, collisionMass, survival]
    linarith
  have hpartnerDecomp :=
    window.terminalValue_eq_singleton_add_collision_add_survival_mul
      SolanVieilleBoundary.boundaryReward (boundaryPartner who)
  have hpartnerSingleton :=
    finiteWindow_singletonRewardContribution_eq_pairMass
      window (boundaryPartner who)
  rw [boundaryPartner_partner] at hpartnerSingleton
  rw [hpartnerSingleton] at hpartnerDecomp
  have hpartnerCollisionAbs := window.abs_collisionRewardContribution_le
    SolanVieilleBoundary.boundaryReward (boundaryPartner who)
      boundaryReward_abs_le_four
  have hpartnerCollision := (abs_le.mp hpartnerCollisionAbs).2
  have hpartnerTail : survival *
      quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward roots (boundaryPartner who) drop ≤
      survival * (1 + Real.sqrt ε) :=
    mul_le_mul_of_nonneg_left hpartnerLow.le hsurvival0
  have hpartnerFloor :=
    boundary_terminalValue_ge_one_sub_thirtyThree_mul
      hclose hnash (boundaryPartner who)
  have hoppositeMass : firstOppositeMass + secondOppositeMass ≤
      4 * Real.sqrt ε + 105 * ε := by
    have hsurvivalSqrt : survival * Real.sqrt ε ≤ Real.sqrt ε :=
      mul_le_of_le_one_left (Real.sqrt_nonneg ε) hsurvival1
    change quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward roots (boundaryPartner who) 0 = _
      at hpartnerDecomp
    dsimp only [window] at hpartnerDecomp
    simp only [Nat.zero_add] at hpartnerDecomp
    change quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward roots (boundaryPartner who) 0 =
      partnerMass + 4 * ownMass +
        (⟨0, drop⟩ : QuittingFiniteRootWindow roots).collisionRewardContribution
          SolanVieilleBoundary.boundaryReward
          (boundaryPartner who) +
        survival * quittingRootSequenceTerminalValue
          SolanVieilleBoundary.boundaryReward roots (boundaryPartner who) drop
      at hpartnerDecomp
    change window.collisionRewardContribution
        SolanVieilleBoundary.boundaryReward (boundaryPartner who) ≤
      4 * collisionMass at hpartnerCollision
    nlinarith
  have hoppositeHigh (target other : Fin 4)
      (htarget : target = boundaryOppositeFirst who ∧
          other = boundaryOppositeSecond who ∨
        target = boundaryOppositeSecond who ∧
          other = boundaryOppositeFirst who)
      (hpartners : boundaryPartner target = other) :
      1 + 1 / 100 ≤ quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward roots target drop := by
    have htargetFloor := boundary_terminalValue_ge_one_sub_thirtyThree_mul
      hclose hnash target
    have htargetDecomp :=
      window.terminalValue_eq_singleton_add_collision_add_survival_mul
        SolanVieilleBoundary.boundaryReward target
    have htargetSingleton :=
      finiteWindow_singletonRewardContribution_eq_pairMass window target
    rw [hpartners] at htargetSingleton
    rw [htargetSingleton] at htargetDecomp
    have htargetCollisionAbs := window.abs_collisionRewardContribution_le
      SolanVieilleBoundary.boundaryReward target boundaryReward_abs_le_four
    have htargetCollision := (abs_le.mp htargetCollisionAbs).2
    have htargetMassBound :
        window.singletonMass target + 4 * window.singletonMass other ≤
          4 * (firstOppositeMass + secondOppositeMass) := by
      rcases htarget with hforward | hbackward
      · rw [hforward.1, hforward.2]
        change firstOppositeMass + 4 * secondOppositeMass ≤
          4 * (firstOppositeMass + secondOppositeMass)
        linarith
      · rw [hbackward.1, hbackward.2]
        change secondOppositeMass + 4 * firstOppositeMass ≤
          4 * (firstOppositeMass + secondOppositeMass)
        linarith
    by_contra hnotHigh
    have htargetLow : quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward roots target drop < 1 + 1 / 100 :=
      lt_of_not_ge hnotHigh
    have hsurvivalPartner : survival ≤ 1 - partnerMass := by
      linarith
    have htailUpper : survival *
        quittingRootSequenceTerminalValue
          SolanVieilleBoundary.boundaryReward roots target drop <
        (1 - partnerMass) * (1 + 1 / 100) := by
      calc
        _ < survival * (1 + 1 / 100) :=
          mul_lt_mul_of_pos_left htargetLow
            (lt_of_lt_of_le (by norm_num : (0 : ℝ) < 1 / 8) hreach)
        _ ≤ (1 - partnerMass) * (1 + 1 / 100) :=
          mul_le_mul_of_nonneg_right hsurvivalPartner (by norm_num)
    change quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward roots target 0 = _ at htargetDecomp
    dsimp only [window] at htargetDecomp
    simp only [Nat.zero_add] at htargetDecomp
    change quittingRootSequenceTerminalValue
        SolanVieilleBoundary.boundaryReward roots target 0 =
      (⟨0, drop⟩ : QuittingFiniteRootWindow roots).singletonMass target +
        4 * (⟨0, drop⟩ : QuittingFiniteRootWindow roots).singletonMass other +
        (⟨0, drop⟩ : QuittingFiniteRootWindow roots).collisionRewardContribution
          SolanVieilleBoundary.boundaryReward target +
        survival * quittingRootSequenceTerminalValue
          SolanVieilleBoundary.boundaryReward roots target drop at htargetDecomp
    change window.collisionRewardContribution
        SolanVieilleBoundary.boundaryReward target ≤
      4 * collisionMass at htargetCollision
    dsimp only [α] at hpartnerMass'
    nlinarith
  have hfirstHigh := hoppositeHigh
    (boundaryOppositeFirst who) (boundaryOppositeSecond who)
    (Or.inl ⟨rfl, rfl⟩) (boundaryPartner_oppositeFirst who)
  have hsecondHigh := hoppositeHigh
    (boundaryOppositeSecond who) (boundaryOppositeFirst who)
    (Or.inr ⟨rfl, rfl⟩) (boundaryPartner_oppositeSecond who)
  exact boundary_shifted_opposite_pair_contradiction hε0 hεsmall hclose hnash
    who drop hreach hfirstHigh hsecondHigh

/-- For every sufficiently small positive `ε`, the boundary table has no
stationary terminal `ε`-equilibrium. The proof compactifies stationary
approximations at the all-Continue apex. -/
theorem no_stationary_terminalApproximateEquilibrium :
  ∃ ε₀ : ℝ, 0 < ε₀ ∧ ∀ ε, 0 < ε → ε < ε₀ →
    ¬ ∃ root : Fin 4 → PMF Bool,
      IsBoundaryTerminalApproxNash SolanVieilleBoundary.boundaryReward ε
        (boundaryStationaryProfile SolanVieilleBoundary.boundaryReward root) := by
  obtain ⟨apexAccuracy, hapexAccuracy, hnoApex⟩ :=
    no_nearAllContinue_terminalApproximateEquilibrium
  have hnotApproximable : ¬ (∀ requested : ℝ, 0 < requested →
      ∃ stationaryRoot : Fin 4 → PMF Bool,
        (quittingGame SolanVieilleBoundary.boundaryReward).IsεAsymptoticNash
          (quittingTerminalPayoff SolanVieilleBoundary.boundaryReward)
          requested
          (quittingStationaryProfile SolanVieilleBoundary.boundaryReward
            stationaryRoot)) := by
    intro happroximable
    rcases
        exactStationaryEndpoint_or_nearAllContinue_of_stationaryApproximable
          SolanVieilleBoundary.boundaryReward happroximable with
      hexact | hnear
    · obtain ⟨value, simplexRoot, hpositive, hfixed, hendpoint⟩ := hexact
      let exactRoot := quittingRootOfSimplex simplexRoot
      have habsorbs : quittingStationaryContinueMass exactRoot < 1 :=
        quittingStationaryContinueMass_lt_one_of_totalHazard_pos
          exactRoot hpositive
      have hactual := quittingTerminalPayoff_stationary_eq_of_fixedPoint
        SolanVieilleBoundary.boundaryReward exactRoot value habsorbs hfixed
      have hactualEndpoint : IsεQuittingRootEndpointNash
          SolanVieilleBoundary.boundaryReward
          (fun player ↦ quittingTerminalPayoff
            SolanVieilleBoundary.boundaryReward
            (quittingStationaryProfile
              SolanVieilleBoundary.boundaryReward exactRoot) player)
          0 exactRoot := by
        simpa [exactRoot, hactual] using hendpoint
      have habsorption : 0 < quittingRootAbsorptionMass exactRoot := by
        change 0 < 1 - quittingStationaryContinueMass exactRoot
        linarith
      have hcomplementary :=
        (isQuittingStationaryGainComplementary_iff_endpointNash
          SolanVieilleBoundary.boundaryReward exactRoot habsorption).2
          hactualEndpoint
      exact
        FourPlayerPairedSingleton.periodTwo_not_stationaryGainComplementary_of_absorbs
          exactRoot habsorbs hcomplementary
    · let requested := apexAccuracy / 2
      have hrequested : 0 < requested := by
        dsimp only [requested]
        linarith
      obtain ⟨nearRoot, hnearNash, hnearHazard⟩ :=
        hnear requested hrequested
      let nearRoots : BoundaryRootSequence (ι := Fin 4) := fun _ ↦ nearRoot
      have hclose : ∀ time player,
          |(nearRoots time player false).toReal - 1| < requested := by
        intro time player
        have hsum := quittingRoot_continueProbability_add_quitProbability
          nearRoot player
        have hquit0 : 0 ≤ (nearRoot player true).toReal :=
          ENNReal.toReal_nonneg
        dsimp only [nearRoots]
        rw [show (nearRoot player false).toReal - 1 =
            -(nearRoot player true).toReal by linarith, abs_neg,
          abs_of_nonneg hquit0]
        exact hnearHazard player
      apply hnoApex requested hrequested (by dsimp only [requested]; linarith)
      refine ⟨nearRoots, hclose, ?_⟩
      have hprofile :
          boundaryRootSequenceProfile SolanVieilleBoundary.boundaryReward nearRoots =
            quittingStationaryProfile SolanVieilleBoundary.boundaryReward
              nearRoot := by
        funext player time history
        rfl
      rw [hprofile]
      exact hnearNash
  by_contra hnoGap
  push Not at hnoGap
  apply hnotApproximable
  intro requested hrequested
  obtain ⟨epsilon, hepsilon, hepsilonRequested, root, hnash⟩ :=
    hnoGap requested hrequested
  refine ⟨root, ?_⟩
  exact StochasticGame.IsεAsymptoticNash.mono hnash hepsilonRequested.le

/-- The boundary phenomenon in one statement: the displayed period-two
profile is an exact terminal equilibrium with the named cross-block payoff,
while sufficiently accurate stationary and uniformly near-all-Continue
terminal equilibria do not exist. -/
theorem periodTwoProfile_exact_and_stationary_nearContinue_excluded :
    (quittingGame boundaryReward).IsεAsymptoticNash
        (quittingTerminalPayoff boundaryReward) 0
        FourPlayerPairedSingleton.periodTwoProfile ∧
      quittingTerminalPayoff boundaryReward
          FourPlayerPairedSingleton.periodTwoProfile = crossBlockPayoff ∧
      (∃ ε₀ : ℝ, 0 < ε₀ ∧ ∀ ε, 0 < ε → ε < ε₀ →
        ¬ ∃ root : Fin 4 → PMF Bool,
          IsBoundaryTerminalApproxNash boundaryReward ε
            (boundaryStationaryProfile boundaryReward root)) ∧
      ∃ ε₀ : ℝ, 0 < ε₀ ∧ ∀ ε, 0 < ε → ε < ε₀ →
        ¬ ∃ roots : BoundaryRootSequence (ι := Fin 4),
          (∀ time player,
            |(roots time player false).toReal - 1| < ε) ∧
          IsBoundaryTerminalApproxNash boundaryReward ε
            (boundaryRootSequenceProfile boundaryReward roots) := by
  refine ⟨FourPlayerPairedSingleton.periodTwoProfile_isExactTerminalNash,
    ?_, no_stationary_terminalApproximateEquilibrium,
    no_nearAllContinue_terminalApproximateEquilibrium⟩
  rw [crossBlockPayoff_eq_oddValue]
  exact FourPlayerPairedSingleton.periodTwoProfile_terminalPayoff

end SolanVieilleBoundary
end GameTheory
