/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.Classification.Existence.RootSequenceWindowLedger

/-!
# Global refusal ledger

Forcing one player to Continue at an arbitrary finite set of dates produces
an exact Bellman telescope.  Its chronology is the survival law of the
modified root sequence: selected earlier dates use opponent-only survival,
while unselected dates retain joint survival.

If the prescribed conditional value exceeds immediate Quit by `delta` on
the selected dates, refusal gains at least `delta` times the original
survival-weighted prescribed Quit clock.  A global Nash cap bounds every
finite such charge, and nonnegative-series exhaustion gives the corresponding
statement for an arbitrary set of dates without constructing an infinite
refusal deviation.
-/

noncomputable section

namespace GameTheory

open Math.Probability Math.PMFProduct

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- The unilateral hazard which forces Continue exactly on `dates` and uses
the prescribed marginal everywhere else. -/
def quittingFiniteRefusalHazard
    (roots : ℕ → ι → PMF Bool) (who : ι) (dates : Finset ℕ)
    (time : ℕ) : PMF Bool :=
  if time ∈ dates then PMF.pure false else roots time who

/-- The root sequence generated by a finite refusal hazard. -/
def quittingFiniteRefusalRoots
    (roots : ℕ → ι → PMF Bool) (who : ι) (dates : Finset ℕ) :
    ℕ → ι → PMF Bool :=
  quittingRootSequenceUpdate roots who
    (quittingFiniteRefusalHazard roots who dates)

omit [Fintype ι] in
@[simp] theorem quittingFiniteRefusalRoots_of_mem
    (roots : ℕ → ι → PMF Bool) (who : ι) (dates : Finset ℕ)
    {time : ℕ} (htime : time ∈ dates) :
    quittingFiniteRefusalRoots roots who dates time =
      Function.update (roots time) who (PMF.pure false) := by
  simp [quittingFiniteRefusalRoots, quittingFiniteRefusalHazard,
    quittingRootSequenceUpdate, htime]

omit [Fintype ι] in
@[simp] theorem quittingFiniteRefusalRoots_of_not_mem
    (roots : ℕ → ι → PMF Bool) (who : ι) (dates : Finset ℕ)
    {time : ℕ} (htime : time ∉ dates) :
    quittingFiniteRefusalRoots roots who dates time = roots time := by
  funext player
  by_cases hplayer : player = who
  · subst player
    simp [quittingFiniteRefusalRoots, quittingFiniteRefusalHazard,
      quittingRootSequenceUpdate, htime]
  · simp [quittingFiniteRefusalRoots, quittingFiniteRefusalHazard,
      quittingRootSequenceUpdate, htime, Function.update_of_ne hplayer]

/-- Forcing Continue on finitely many dates can only increase every finite
joint-survival prefix. -/
theorem quittingJointSurvivalWeight_le_finiteRefusal
    (roots : ℕ → ι → PMF Bool) (who : ι) (dates : Finset ℕ)
    (time : ℕ) :
    quittingJointSurvivalWeight roots 0 time ≤
      quittingJointSurvivalWeight
        (quittingFiniteRefusalRoots roots who dates) 0 time := by
  rw [quittingJointSurvivalWeight_eq_prod,
    quittingJointSurvivalWeight_eq_prod]
  simp only [Nat.zero_add]
  apply Finset.prod_le_prod
  · intro offset _
    exact quittingStationaryContinueMass_nonneg (roots offset)
  · intro offset _
    by_cases htime : offset ∈ dates
    · rw [quittingFiniteRefusalRoots_of_mem roots who dates htime]
      exact quittingStationaryContinueMass_le_update_pure_false
        (roots offset) who
    · rw [quittingFiniteRefusalRoots_of_not_mem roots who dates htime]

/-- A value gap over immediate Quit makes pure Continue profitable in
proportion to the prescribed Quit probability. -/
theorem delta_mul_quitProbability_le_continueAdvantage_of_value_sub_quit
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (who : ι) (time : ℕ) {delta : ℝ}
    (hdelta : 0 < delta)
    (hgap : delta ≤
      quittingRootSequenceTerminalValue reward roots who time -
        quittingRootQuitPayoff reward
          (quittingRootSequenceTailVector reward roots (time + 1))
          (roots time) who) :
    delta * (roots time who true).toReal ≤
      quittingRootContinuePayoff reward
          (quittingRootSequenceTailVector reward roots (time + 1))
          (roots time) who -
        quittingRootSequenceTerminalValue reward roots who time := by
  let quit := quittingRootQuitPayoff reward
    (quittingRootSequenceTailVector reward roots (time + 1))
    (roots time) who
  let cont := quittingRootContinuePayoff reward
    (quittingRootSequenceTailVector reward roots (time + 1))
    (roots time) who
  let value := quittingRootSequenceTerminalValue reward roots who time
  let q := (roots time who true).toReal
  let c := (roots time who false).toReal
  have hvalue : value = q * quit + c * cont := by
    rw [show value = quittingRootSuccessorPayoff reward
      (quittingRootSequenceTailVector reward roots (time + 1))
      (roots time) who from
        quittingRootSequenceTerminalValue_eq_successorPayoff_tailVector
          reward roots who time]
    exact quittingRootSuccessorPayoff_eq_endpointMix reward _ _ _
  have hmass : q + c = 1 := by
    dsimp only [q, c]
    linarith [quittingRoot_continueProbability_add_quitProbability
      (roots time) who]
  have hq0 : 0 ≤ q := ENNReal.toReal_nonneg
  have hc0 : 0 ≤ c := ENNReal.toReal_nonneg
  have hc1 : c ≤ 1 := by linarith
  have hvalueQuit : delta ≤ value - quit := hgap
  have hfactor : value - quit = c * (cont - quit) := by
    have hq : q = 1 - c := by linarith
    rw [hvalue]
    rw [hq]
    ring
  have hcontQuit : 0 ≤ cont - quit := by
    by_contra hnegative
    have : cont - quit < 0 := lt_of_not_ge hnegative
    rw [hfactor] at hvalueQuit
    nlinarith
  have hdeltaCont : delta ≤ cont - quit := by
    rw [hfactor] at hvalueQuit
    nlinarith [mul_nonneg (sub_nonneg.mpr hc1) hcontQuit]
  have hmix : cont - value = q * (cont - quit) := by
    rw [hvalue]
    nlinarith
  dsimp only [cont, value, q] at hmix ⊢
  rw [hmix]
  simpa [mul_comm] using mul_le_mul_of_nonneg_right hdeltaCont hq0

private theorem quittingFiniteRefusal_gap_step
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (who : ι) (dates : Finset ℕ)
    (time : ℕ) :
    quittingRootSequenceHazardTerminalValue reward roots who
          (quittingFiniteRefusalHazard roots who dates) time -
        quittingRootSequenceTerminalValue reward roots who time =
      (if time ∈ dates then
        quittingRootContinuePayoff reward
            (quittingRootSequenceTailVector reward roots (time + 1))
            (roots time) who -
          quittingRootSequenceTerminalValue reward roots who time
      else 0) +
        quittingStationaryContinueMass
            (quittingFiniteRefusalRoots roots who dates time) *
          (quittingRootSequenceHazardTerminalValue reward roots who
              (quittingFiniteRefusalHazard roots who dates) (time + 1) -
            quittingRootSequenceTerminalValue reward roots who (time + 1)) := by
  have hdeviation :=
    quittingRootSequenceHazardTerminalValue_eq_hazardBellman
      reward roots who (quittingFiniteRefusalHazard roots who dates) time
  have hplan := quittingRootSequenceTerminalValue_eq_absorbingContribution_add
    reward roots who time
  have hsplit := quittingRootAbsorbingContribution_eq_own_split
    reward roots who time
  have hfactor := quittingStationaryContinueMass_eq_forcedContinue_mul_own
    (roots time) who
  have hcontinueMass : quittingFixedOpponentsContinueMass roots who time =
      quittingStationaryContinueMass
        (Function.update (roots time) who (PMF.pure false)) := rfl
  have hcontinue := quittingRootContinuePayoff_eq_fixedOpponents
    reward roots who
      (quittingRootSequenceTailVector reward roots (time + 1)) time
  by_cases htime : time ∈ dates
  · rw [show quittingFiniteRefusalHazard roots who dates time = PMF.pure false
        by simp [quittingFiniteRefusalHazard, htime]] at hdeviation
    rw [if_pos htime,
      quittingFiniteRefusalRoots_of_mem roots who dates htime]
    simp only [PMF.pure_apply,
      if_neg (by decide : (true : Bool) ≠ false), ENNReal.toReal_zero,
      if_true, ENNReal.toReal_one, zero_mul, one_mul] at hdeviation
    rw [hdeviation, hcontinue, hcontinueMass]
    simp only [quittingRootSequenceTailVector]
    ring
  · rw [show quittingFiniteRefusalHazard roots who dates time = roots time who
        by simp [quittingFiniteRefusalHazard, htime]] at hdeviation
    rw [if_neg htime,
      quittingFiniteRefusalRoots_of_not_mem roots who dates htime]
    rw [hplan, hsplit, hfactor, hdeviation, hcontinueMass]
    ring

private theorem quittingFiniteRefusal_gap_eq_range_sum
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (who : ι) (dates : Finset ℕ) :
    ∀ fuel start,
      (∀ time ∈ dates, time < start + fuel) →
      quittingRootSequenceHazardTerminalValue reward roots who
            (quittingFiniteRefusalHazard roots who dates) start -
          quittingRootSequenceTerminalValue reward roots who start =
        ∑ offset ∈ Finset.range fuel,
          if start + offset ∈ dates then
            quittingJointSurvivalWeight
                (quittingFiniteRefusalRoots roots who dates) start offset *
              (quittingRootContinuePayoff reward
                  (quittingRootSequenceTailVector reward roots
                    (start + offset + 1))
                  (roots (start + offset)) who -
                quittingRootSequenceTerminalValue reward roots who
                  (start + offset))
          else 0 := by
  intro fuel
  induction fuel with
  | zero =>
      intro start hbound
      have htail : quittingRootSequenceTerminalValue reward
          (quittingFiniteRefusalRoots roots who dates) who start =
          quittingRootSequenceTerminalValue reward roots who start := by
        apply quittingRootSequenceTerminalValue_congr
        intro offset
        apply quittingFiniteRefusalRoots_of_not_mem
        intro hmem
        have := hbound (start + offset) hmem
        omega
      change quittingRootSequenceTerminalValue reward
          (quittingFiniteRefusalRoots roots who dates) who start -
        quittingRootSequenceTerminalValue reward roots who start = 0
      rw [htail]
      ring
  | succ fuel ih =>
      intro start hbound
      have hstep := quittingFiniteRefusal_gap_step
        reward roots who dates start
      have hnext := ih (start + 1) fun time htime => by
        have := hbound time htime
        omega
      have hpeel : ∀ f : ℕ → ℝ,
          ∑ offset ∈ Finset.range (fuel + 1), f offset =
            (∑ offset ∈ Finset.range fuel, f (offset + 1)) + f 0 :=
        fun f => Finset.sum_range_succ' f fuel
      rw [hpeel, hstep, hnext]
      have hshift : ∀ offset : ℕ,
          quittingJointSurvivalWeight
                (quittingFiniteRefusalRoots roots who dates) start
                (offset + 1) *
              (if start + (offset + 1) ∈ dates then
                quittingRootContinuePayoff reward
                    (quittingRootSequenceTailVector reward roots
                      (start + (offset + 1) + 1))
                    (roots (start + (offset + 1))) who -
                  quittingRootSequenceTerminalValue reward roots who
                    (start + (offset + 1))
              else 0) =
            quittingStationaryContinueMass
                (quittingFiniteRefusalRoots roots who dates start) *
              (quittingJointSurvivalWeight
                  (quittingFiniteRefusalRoots roots who dates)
                  (start + 1) offset *
                (if start + 1 + offset ∈ dates then
                  quittingRootContinuePayoff reward
                      (quittingRootSequenceTailVector reward roots
                        (start + 1 + offset + 1))
                      (roots (start + 1 + offset)) who -
                    quittingRootSequenceTerminalValue reward roots who
                      (start + 1 + offset)
                else 0)) := by
        intro offset
        rw [quittingJointSurvivalWeight_succ_left]
        rw [show start + (offset + 1) = start + 1 + offset by omega]
        ring
      simp_rw [mul_ite, mul_zero] at hshift
      rw [Finset.sum_congr rfl fun offset _ => hshift offset,
        Finset.mul_sum]
      simp only [mul_ite, mul_zero]
      rw [quittingJointSurvivalWeight_zero_fuel]
      simp only [Nat.add_zero, one_mul]
      by_cases hstart : start ∈ dates
      · simp [hstart]
        ring
      · simp [hstart]

/-- Exact arbitrary-finite-date refusal telescope.  The selected local
advantages are weighted by survival under the modified root sequence. -/
theorem quittingFiniteRefusal_terminalValue_sub_eq_sum
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (who : ι) (dates : Finset ℕ) :
    quittingRootSequenceHazardTerminalValue reward roots who
          (quittingFiniteRefusalHazard roots who dates) 0 -
        quittingRootSequenceTerminalValue reward roots who 0 =
      ∑ time ∈ dates,
        quittingJointSurvivalWeight
            (quittingFiniteRefusalRoots roots who dates) 0 time *
          (quittingRootContinuePayoff reward
              (quittingRootSequenceTailVector reward roots (time + 1))
              (roots time) who -
            quittingRootSequenceTerminalValue reward roots who time) := by
  obtain ⟨cutoff, hcutoff⟩ := dates.exists_nat_subset_range
  have hbound : ∀ time ∈ dates, time < 0 + cutoff := by
    intro time htime
    simpa using Finset.mem_range.mp (hcutoff htime)
  rw [quittingFiniteRefusal_gap_eq_range_sum
    reward roots who dates cutoff 0 hbound]
  simp only [Nat.zero_add]
  rw [← Finset.sum_filter]
  apply Finset.sum_congr
  · ext time
    simp only [Finset.mem_filter, Finset.mem_range]
    constructor
    · exact fun h => h.2
    · exact fun h => ⟨Finset.mem_range.mp (hcutoff h), h⟩
  · intro time _
    rfl

/-- A positive prescribed value gap over immediate Quit makes finite refusal
pay at least the original survival-weighted selected Quit clock. -/
theorem delta_mul_finiteRefusalCharge_le_gain
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (who : ι) (dates : Finset ℕ)
    {delta : ℝ} (hdelta : 0 < delta)
    (hgap : ∀ time ∈ dates, delta ≤
      quittingRootSequenceTerminalValue reward roots who time -
        quittingRootQuitPayoff reward
          (quittingRootSequenceTailVector reward roots (time + 1))
          (roots time) who) :
    delta * ∑ time ∈ dates,
        quittingJointSurvivalWeight roots 0 time *
          (roots time who true).toReal ≤
      quittingRootSequenceHazardTerminalValue reward roots who
          (quittingFiniteRefusalHazard roots who dates) 0 -
        quittingRootSequenceTerminalValue reward roots who 0 := by
  rw [quittingFiniteRefusal_terminalValue_sub_eq_sum]
  rw [Finset.mul_sum]
  apply Finset.sum_le_sum
  intro time htime
  have hlocal :=
    delta_mul_quitProbability_le_continueAdvantage_of_value_sub_quit
      reward roots who time hdelta (hgap time htime)
  have hlocal0 : 0 ≤
      quittingRootContinuePayoff reward
          (quittingRootSequenceTailVector reward roots (time + 1))
          (roots time) who -
        quittingRootSequenceTerminalValue reward roots who time :=
    le_trans (mul_nonneg hdelta.le ENNReal.toReal_nonneg) hlocal
  calc
    delta * (quittingJointSurvivalWeight roots 0 time *
        (roots time who true).toReal) =
      quittingJointSurvivalWeight roots 0 time *
        (delta * (roots time who true).toReal) := by ring
    _ ≤ quittingJointSurvivalWeight roots 0 time *
        (quittingRootContinuePayoff reward
            (quittingRootSequenceTailVector reward roots (time + 1))
            (roots time) who -
          quittingRootSequenceTerminalValue reward roots who time) :=
      mul_le_mul_of_nonneg_left hlocal
        (quittingJointSurvivalWeight_nonneg roots 0 time)
    _ ≤ quittingJointSurvivalWeight
          (quittingFiniteRefusalRoots roots who dates) 0 time *
        (quittingRootContinuePayoff reward
            (quittingRootSequenceTailVector reward roots (time + 1))
            (roots time) who -
          quittingRootSequenceTerminalValue reward roots who time) :=
      mul_le_mul_of_nonneg_right
        (quittingJointSurvivalWeight_le_finiteRefusal roots who dates time)
        hlocal0

/-- A global Nash cap bounds every finite selected refusal charge. -/
theorem delta_mul_finiteRefusalCharge_le_of_nash
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) {epsilon delta : ℝ}
    (hnash : IsεQuittingRootSequenceNash reward epsilon roots)
    (hdelta : 0 < delta) (who : ι) (dates : Finset ℕ)
    (hgap : ∀ time ∈ dates, delta ≤
      quittingRootSequenceTerminalValue reward roots who time -
        quittingRootQuitPayoff reward
          (quittingRootSequenceTailVector reward roots (time + 1))
          (roots time) who) :
    delta * ∑ time ∈ dates,
        quittingJointSurvivalWeight roots 0 time *
          (roots time who true).toReal ≤ epsilon := by
  have hgain := delta_mul_finiteRefusalCharge_le_gain
    reward roots who dates hdelta hgap
  have hcap := hnash who (quittingFiniteRefusalHazard roots who dates)
  linarith

/-- The selected refusal charge over an arbitrary set of dates is summable
under one global Nash cap and a uniform positive value gap. -/
theorem summable_selectedRefusalCharge_of_nash
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) {epsilon delta : ℝ}
    (hnash : IsεQuittingRootSequenceNash reward epsilon roots)
    (hdelta : 0 < delta) (who : ι) (selected : Set ℕ)
    (hgap : ∀ time ∈ selected, delta ≤
      quittingRootSequenceTerminalValue reward roots who time -
        quittingRootQuitPayoff reward
          (quittingRootSequenceTailVector reward roots (time + 1))
          (roots time) who) :
    Summable (selected.indicator fun time =>
      quittingJointSurvivalWeight roots 0 time *
        (roots time who true).toReal) := by
  classical
  apply summable_of_sum_le (c := epsilon / delta)
  · intro time
    by_cases htime : time ∈ selected
    · simp only [Set.indicator_of_mem htime]
      exact mul_nonneg
        (quittingJointSurvivalWeight_nonneg roots 0 time)
        ENNReal.toReal_nonneg
    · simp [Set.indicator, htime]
  · intro dates
    let chosen := dates.filter fun time => time ∈ selected
    have hfinite := delta_mul_finiteRefusalCharge_le_of_nash
      reward roots hnash hdelta who chosen fun time htime => by
        exact hgap time (Finset.mem_filter.mp htime).2
    have hsum :
        (∑ time ∈ dates, if time ∈ selected then
            quittingJointSurvivalWeight roots 0 time *
              (roots time who true).toReal else 0) =
          ∑ time ∈ chosen,
            quittingJointSurvivalWeight roots 0 time *
              (roots time who true).toReal := by
      dsimp only [chosen]
      rw [Finset.sum_filter]
    change (∑ time ∈ dates, if time ∈ selected then
      quittingJointSurvivalWeight roots 0 time *
        (roots time who true).toReal else 0) ≤ epsilon / delta
    rw [hsum]
    rw [le_div_iff₀ hdelta]
    simpa [mul_comm] using hfinite

/-- Countable exhaustion of the global refusal inequality. -/
theorem delta_mul_tsum_selectedRefusalCharge_le_of_nash
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) {epsilon delta : ℝ}
    (hnash : IsεQuittingRootSequenceNash reward epsilon roots)
    (hdelta : 0 < delta) (who : ι) (selected : Set ℕ)
    (hgap : ∀ time ∈ selected, delta ≤
      quittingRootSequenceTerminalValue reward roots who time -
        quittingRootQuitPayoff reward
          (quittingRootSequenceTailVector reward roots (time + 1))
          (roots time) who) :
    delta * ∑' time, selected.indicator (fun time =>
        quittingJointSurvivalWeight roots 0 time *
          (roots time who true).toReal) time ≤ epsilon := by
  classical
  have hsummable := summable_selectedRefusalCharge_of_nash
    reward roots hnash hdelta who selected hgap
  have hsum : ∑' time, selected.indicator (fun time =>
      quittingJointSurvivalWeight roots 0 time *
        (roots time who true).toReal) time ≤ epsilon / delta := by
    apply hsummable.tsum_le_of_sum_le
    intro dates
    have hall := delta_mul_finiteRefusalCharge_le_of_nash
      reward roots hnash hdelta who
        (dates.filter fun time => time ∈ selected) fun time htime => by
          exact hgap time (Finset.mem_filter.mp htime).2
    have hrewrite :
        (∑ time ∈ dates, if time ∈ selected then
          quittingJointSurvivalWeight roots 0 time *
            (roots time who true).toReal else 0) =
        ∑ time ∈ dates.filter (fun time => time ∈ selected),
          quittingJointSurvivalWeight roots 0 time *
            (roots time who true).toReal := by
      rw [Finset.sum_filter]
    change (∑ time ∈ dates, if time ∈ selected then
      quittingJointSurvivalWeight roots 0 time *
        (roots time who true).toReal else 0) ≤ epsilon / delta
    rw [hrewrite, le_div_iff₀ hdelta]
    simpa [mul_comm] using hall
  simpa [mul_comm] using (le_div_iff₀ hdelta).mp hsum

end GameTheory
