/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.EssentialAPS.Basic

/-!
# Greatest essential-APS families inside a supplied carrier

The paper iterates essential APS inside compact component carriers. This file
keeps that restriction explicit: `carrier owner` is the set in which the
owner's fixed-point computation is allowed to live, and the restricted
operator intersects every one-step image with that carrier.

The restricted operator is monotone. Its greatest subinvariant family is
constructed directly as the union of all subinvariant families. Monotonicity
then gives both inclusions needed for a fixed point.

This is an exact order-theoretic greatest fixed point. It is not a path
realization theorem: the zero-mass regression shows why semantic execution
also needs an absorption-progress condition.
-/

noncomputable section

namespace GameTheory

open StochasticGame

variable {ι : Type}

/-- Essential APS restricted to a supplied owner-indexed carrier. -/
def quittingEssentialAPSRestrictedOperator
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (carrier family : ι → Set (Payoff ι)) : ι → Set (Payoff ι) :=
  fun owner ↦ carrier owner ∩
    quittingEssentialAPSOperator reward family owner

/-- The restricted operator is monotone in its continuation family. -/
theorem monotone_quittingEssentialAPSRestrictedOperator
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (carrier : ι → Set (Payoff ι)) :
    Monotone (quittingEssentialAPSRestrictedOperator reward carrier) := by
  intro E F hEF owner value hvalue
  exact ⟨hvalue.1,
    (monotone_quittingEssentialAPSOperator reward hEF) owner hvalue.2⟩

/-- An owner-indexed payoff family is subinvariant inside `carrier` when every
one of its points stays in the carrier and is regenerated by one APS step. -/
def IsQuittingEssentialAPSSubinvariantWithin
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (carrier family : ι → Set (Payoff ι)) : Prop :=
  family ≤ quittingEssentialAPSRestrictedOperator reward carrier family

/-- Union of all essential-APS subinvariant families inside `carrier`. -/
def quittingEssentialAPSGreatestFamily
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (carrier : ι → Set (Payoff ι)) : ι → Set (Payoff ι) :=
  fun owner ↦ {value | ∃ family : ι → Set (Payoff ι),
    IsQuittingEssentialAPSSubinvariantWithin reward carrier family ∧
      value ∈ family owner}

/-- Every subinvariant family is contained coordinatewise in the greatest
family inside the same carrier. -/
theorem quittingEssentialAPSFamily_le_greatest
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (carrier family : ι → Set (Payoff ι))
    (hfamily :
      IsQuittingEssentialAPSSubinvariantWithin reward carrier family) :
    family ≤ quittingEssentialAPSGreatestFamily reward carrier := by
  intro owner value hvalue
  exact ⟨family, hfamily, hvalue⟩

/-- The union of all subinvariant families is itself subinvariant. -/
theorem quittingEssentialAPSGreatestFamily_subinvariant
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (carrier : ι → Set (Payoff ι)) :
    IsQuittingEssentialAPSSubinvariantWithin reward carrier
      (quittingEssentialAPSGreatestFamily reward carrier) := by
  intro owner value hvalue
  rcases hvalue with ⟨family, hfamily, hvalue⟩
  exact monotone_quittingEssentialAPSRestrictedOperator reward carrier
    (quittingEssentialAPSFamily_le_greatest
      reward carrier family hfamily)
    owner (hfamily owner hvalue)

/-- The restricted image of the greatest family is itself subinvariant. -/
theorem quittingEssentialAPSRestrictedGreatest_subinvariant
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (carrier : ι → Set (Payoff ι)) :
    IsQuittingEssentialAPSSubinvariantWithin reward carrier
      (quittingEssentialAPSRestrictedOperator reward carrier
        (quittingEssentialAPSGreatestFamily reward carrier)) := by
  intro owner value hvalue
  exact monotone_quittingEssentialAPSRestrictedOperator reward carrier
    (quittingEssentialAPSGreatestFamily_subinvariant reward carrier)
    owner hvalue

/-- One restricted APS step from the greatest family cannot leave it. -/
theorem quittingEssentialAPSRestrictedGreatest_le
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (carrier : ι → Set (Payoff ι)) :
    quittingEssentialAPSRestrictedOperator reward carrier
        (quittingEssentialAPSGreatestFamily reward carrier) ≤
      quittingEssentialAPSGreatestFamily reward carrier :=
  quittingEssentialAPSFamily_le_greatest reward carrier
    (quittingEssentialAPSRestrictedOperator reward carrier
      (quittingEssentialAPSGreatestFamily reward carrier))
    (quittingEssentialAPSRestrictedGreatest_subinvariant reward carrier)

/-- **Greatest fixed point inside a supplied carrier.** -/
theorem quittingEssentialAPSGreatestFamily_fixed
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (carrier : ι → Set (Payoff ι)) :
    quittingEssentialAPSRestrictedOperator reward carrier
        (quittingEssentialAPSGreatestFamily reward carrier) =
      quittingEssentialAPSGreatestFamily reward carrier := by
  exact le_antisymm
    (quittingEssentialAPSRestrictedGreatest_le reward carrier)
    (quittingEssentialAPSGreatestFamily_subinvariant reward carrier)

/-- Every fixed family inside `carrier` is contained in the greatest one. -/
theorem quittingEssentialAPSFixedFamily_le_greatest
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (carrier family : ι → Set (Payoff ι))
    (hfixed :
      quittingEssentialAPSRestrictedOperator reward carrier family =
        family) :
    family ≤ quittingEssentialAPSGreatestFamily reward carrier := by
  apply quittingEssentialAPSFamily_le_greatest reward carrier family
  intro owner value hvalue
  have howner := congrFun hfixed owner
  rw [← howner] at hvalue
  exact hvalue

/-- The unrestricted greatest family is the special case with carrier
`Set.univ` in every owner coordinate. -/
def quittingEssentialAPSUnrestrictedGreatestFamily
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :
    ι → Set (Payoff ι) :=
  quittingEssentialAPSGreatestFamily reward (fun _ ↦ Set.univ)

end GameTheory
