/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import Mathlib
import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic

/-!
# A hidden-fiber span counterexample

This file records an exact finite counterexample showing that the span of
within-public-fiber charge differences is only a quotient obstruction, not a
sufficient online balancing criterion.

There is one vertex, one mode, two public observations, and three loop edges.
The target edge masses are `1/4`, `1/6`, and `7/12`; the respective charges
are `1`, `2`, and `-1`.  The target charge is zero, and the two edges in the
first public fiber have difference one, so their real span is all of `ℝ` and
their integer generated subgroup is all of `ℤ`.  Nevertheless, every edge in
that public fiber has charge at least one.  Hence a public run of `n` copies
of that observation forces charge at least `n`, while its target row mass
`(5/12)^n` is strictly positive.

This is the finite algebraic and pathwise core of the obstruction.  It does
not introduce a causal-policy or filtration API, and it makes no formal
minimality claim.
-/

noncomputable section

namespace GameTheory

namespace HiddenFiberSpanCounterexample

/-- The three distinct loop edges of the counterexample. -/
inductive Edge
  | low
  | high
  | negative
  deriving DecidableEq, Fintype

private theorem Edge.univ_eq :
    (Finset.univ : Finset Edge) = {Edge.low, Edge.high, Edge.negative} := by
  ext edge
  cases edge <;> simp

/-- Both positive edges have public observation `false`; the negative edge
has public observation `true`. -/
def observation : Edge → Bool
  | .low | .high => false
  | .negative => true

/-- Integer charge of each hidden edge. -/
def charge : Edge → ℤ
  | .low => 1
  | .high => 2
  | .negative => -1

/-- Rational target mass of each hidden edge. -/
def targetMass : Edge → ℚ
  | .low => 1 / 4
  | .high => 1 / 6
  | .negative => 7 / 12

/-- Source and target maps of the one-vertex loop graph. -/
def source (_ : Edge) : Unit := ()

def target (_ : Edge) : Unit := ()

@[simp] theorem source_eq_target (edge : Edge) : source edge = target edge :=
  rfl

/-- The target masses form a probability row. -/
theorem sum_targetMass_eq_one :
    ∑ edge, targetMass edge = 1 := by
  simp [Edge.univ_eq, targetMass]; norm_num

/-- Every target edge has strictly positive rational mass. -/
theorem targetMass_pos (edge : Edge) : 0 < targetMass edge := by
  cases edge <;> norm_num [targetMass]

/-- The target row has exactly zero mean charge. -/
theorem targetMeanCharge_eq_zero :
    ∑ edge, targetMass edge * (charge edge : ℚ) = 0 := by
  simp [Edge.univ_eq, targetMass, charge]; norm_num

/-- Public mass of one observation after forgetting the hidden edge. -/
def publicMass (output : Bool) : ℚ :=
  ∑ edge, if observation edge = output then targetMass edge else 0

@[simp] theorem publicMass_false : publicMass false = 5 / 12 := by
  simp [publicMass, Edge.univ_eq, observation, targetMass]; norm_num

@[simp] theorem publicMass_true : publicMass true = 7 / 12 := by
  simp [publicMass, Edge.univ_eq, observation, targetMass]

/-- The within-`false` fiber charge difference is the unit direction. -/
@[simp] theorem high_sub_low_charge : charge .high - charge .low = 1 := by
  rfl

/-- The real span of the within-fiber difference is the whole scalar charge
space. -/
theorem real_span_high_sub_low_eq_top :
    Submodule.span ℝ
        ({(charge .high : ℝ) - (charge .low : ℝ)} : Set ℝ) = ⊤ := by
  apply top_unique
  intro value _
  have hone : (1 : ℝ) ∈ Submodule.span ℝ
      ({(charge .high : ℝ) - (charge .low : ℝ)} : Set ℝ) := by
    apply Submodule.subset_span
    norm_num [charge]
  have hscaled := (Submodule.span ℝ
    ({(charge .high : ℝ) - (charge .low : ℝ)} : Set ℝ)).smul_mem value hone
  simpa using hscaled

/-- The integer subgroup generated by the within-fiber difference is the
saturated lattice `ℤ`. -/
theorem integer_zmultiples_high_sub_low_eq_top :
    AddSubgroup.zmultiples (charge .high - charge .low) = ⊤ := by
  change AddSubgroup.zmultiples (1 : ℤ) = ⊤
  exact Int.zmultiples_one

/-- Every edge with public observation `false` has charge at least one. -/
theorem one_le_charge_of_observation_false (edge : Edge)
    (houtput : observation edge = false) : 1 ≤ charge edge := by
  cases edge <;> simp_all [observation, charge]

/-- Consequently an all-`false` public run has cumulative charge at least its
length, independently of how hidden edges are selected inside that fiber. -/
theorem length_le_sum_charge_of_all_observation_false
    (run : List Edge)
    (houtput : ∀ edge ∈ run, observation edge = false) :
    (run.length : ℤ) ≤ (run.map charge).sum := by
  induction run with
  | nil => simp
  | cons edge tail ih =>
      have hedge : 1 ≤ charge edge :=
        one_le_charge_of_observation_false edge (houtput edge (by simp))
      have htail : ∀ candidate ∈ tail, observation candidate = false := by
        intro candidate hcandidate
        exact houtput candidate (by simp [hcandidate])
      have hih := ih htail
      simp only [List.length_cons, Nat.cast_add, Nat.cast_one,
        List.map_cons, List.sum_cons]
      omega

/-- The exact public-row mass of an `n`-step all-`false` run is positive. -/
theorem publicFalseRunMass_pos (n : ℕ) :
    0 < publicMass false ^ n := by
  apply pow_pos
  rw [publicMass_false]
  norm_num

/-- For every proposed deterministic charge bound, there is an all-`false`
run of positive target mass whose charge exceeds it. -/
theorem exists_positiveMass_run_exceeding_bound (bound : ℕ) :
    ∃ run : List Edge,
      (∀ edge ∈ run, observation edge = false) ∧
      0 < publicMass false ^ run.length ∧
      (bound : ℤ) < (run.map charge).sum := by
  let run := List.replicate (bound + 1) Edge.low
  refine ⟨run, ?_, publicFalseRunMass_pos run.length, ?_⟩
  · intro edge hedge
    have : edge = Edge.low := by
      simpa [run] using (List.eq_of_mem_replicate hedge)
    subst edge
    rfl
  · have hlower :=
      length_le_sum_charge_of_all_observation_false run (by
        intro edge hedge
        have : edge = Edge.low := by
          simpa [run] using (List.eq_of_mem_replicate hedge)
        subst edge
        rfl)
    simp [run, charge] at hlower ⊢

end HiddenFiberSpanCounterexample

end GameTheory
