import UniformEquilibrium.ProofView.Concepts.Stochastic.Equilibrium.Discounted.FinkHeterogeneous
import MathUE.Finset.SupNonexpansive
import Mathlib.Topology.UniformSpace.HeineCantor
import Mathlib.Topology.Order.Lattice

/-!
# A. M. Fink, *Equilibrium in a Stochastic n-Person Game* (1964)

A. M. Fink, “Equilibrium in a Stochastic n-Person Game,”
*Journal of Science of the Hiroshima University, Series A-I* **28** (1964),
89–93. DOI: `10.32917/hmj/1206139508`.

This file follows the paper in order.  The paper's state-dependent action set
`J^h(i)` is represented literally by `Game.Act i h`, and the reader-facing
strategy space `Game.X` therefore contains exactly the paper's mixed actions.
The only state-independent action carrier is the internal contingent-plan
adapter `Game.rewardGame`, used to apply the reusable heterogeneous-discount
Fink theorem.  The adapter is discharged by explicit marginalization and
cost/reward identities before Theorem 2 is transferred back to literal
state-dependent profiles.

All numbered statements, the two corollaries, the maps `T`, `β`, and `φ`, and
the three displayed properties of `f` are proved without `sorry`.
-/

noncomputable section

namespace Literature.Fink1964

open GameTheory
open GameTheory.StochasticGame
open Filter Set
open Math.Probability
open Math.PMFProduct
open Math.ProbabilityMassFunction
open scoped NNReal Topology

/-- The finite stochastic cost game on pages 89--90. -/
structure Game (ι : Type) where
  State : Type
  state_nonempty : Nonempty State
  Act : State → ι → Type
  act_nonempty : ∀ s i, Nonempty (Act s i)
  cost : (s : State) → (∀ i, Act s i) → ι → ℝ
  transition : (s : State) → (∀ i, Act s i) → PMF State
  discount : ι → ℝ
  discount_pos : ∀ i, 0 < discount i
  discount_lt_one : ∀ i, discount i < 1

variable {ι : Type}

namespace Game

instance instNonemptyState (P : Game ι) : Nonempty P.State := P.state_nonempty

instance instNonemptyAct (P : Game ι) (s : P.State) (i : ι) :
    Nonempty (P.Act s i) := P.act_nonempty s i

/-- The paper's state-player coordinates. -/
abbrev Agent (P : Game ι) := P.State × ι

/-- The paper's action set `J^h(i)` at a state-player coordinate. -/
abbrev AgentAction (P : Game ι) (p : P.Agent) := P.Act p.1 p.2

/-- The compact product `X` of all state-player mixed-action simplices. -/
abbrev X (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)] :=
  MixedSimplex P.Agent P.AgentAction

/-- The value space `R`, with the sup metric inherited from the finite pi type. -/
abbrev R (P : Game ι) := P.State → Payoff ι

/-- A literal joint action at state `s`. -/
abbrev JointActionAt (P : Game ι) (s : P.State) := ∀ i, P.Act s i

/-- The PMF represented by one simplex coordinate. -/
def actionPMF (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.X) (s : P.State) (i : ι) : PMF (P.Act s i) :=
  (stdSimplexEquiv (α := P.Act s i)).symm (x (s, i))

@[simp] theorem actionPMF_apply_toReal
    (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.X) (s : P.State) (i : ι) (a : P.Act s i) :
    ((P.actionPMF x s i) a).toReal = x (s, i) a := by
  simp [actionPMF, stdSimplexEquiv_symm_apply]

/-- Equation (3)'s one-stage cost plus discounted continuation cost. -/
def oneStepCost (P : Game ι)
    (e : P.R) (s : P.State) (a : P.JointActionAt s) (who : ι) : ℝ :=
  P.cost s a who +
    P.discount who * expect (P.transition s a) (fun s' => e s' who)

/-- Equation (6), at one state-player coordinate. -/
def fCoord (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)] [DecidableEq ι]
    (x : P.X) (s : P.State) (who : ι)
    (y : stdSimplex ℝ (P.Act s who)) (e : P.R) : ℝ :=
  expect (pmfPi (Function.update (fun i => P.actionPMF x s i) who
    ((stdSimplexEquiv (α := P.Act s who)).symm y)))
    (fun a => P.oneStepCost e s a who)

/-- Equation (6), assembled as the vector function `f(x,y,e)`. -/
def f (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)] [DecidableEq ι]
    (x y : P.X) (e : P.R) : P.R :=
  fun s who => P.fCoord x s who (y (s, who)) e

/-- Equation (4): `e(x)` is the value vector generated by `x`. -/
def IsValueVector (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)] [DecidableEq ι]
    (x : P.X) (e : P.R) : Prop :=
  P.f x x e = e

/-- Equation (5), equivalently `x ∈ φ(x)`: no player can lower cost by
changing one statewise mixed action. -/
def IsEquilibriumPoint (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)] [DecidableEq ι]
    (x : P.X) (e : P.R) : Prop :=
  P.IsValueVector x e ∧
    ∀ s who (y : stdSimplex ℝ (P.Act s who)),
      P.fCoord x s who (x (s, who)) e ≤ P.fCoord x s who y e

/-- The largest player discount, Fink's common contraction coefficient
`α = max_h α_h`. -/
def maxDiscount (P : Game ι) [Fintype ι] [Nonempty ι] : ℝ :=
  Finset.sup' Finset.univ Finset.univ_nonempty P.discount

/-- The largest discount as a nonnegative Lipschitz constant. -/
def maxDiscountNNReal (P : Game ι) [Fintype ι] [Nonempty ι] : ℝ≥0 :=
  ⟨P.maxDiscount, by
    obtain ⟨i⟩ := ‹Nonempty ι›
    exact (P.discount_pos i).le.trans
      (Finset.le_sup' (f := P.discount) (Finset.mem_univ i))⟩

theorem discount_le_maxDiscount
    (P : Game ι) [Fintype ι] [Nonempty ι] (who : ι) :
    P.discount who ≤ P.maxDiscount :=
  Finset.le_sup' (f := P.discount) (Finset.mem_univ who)

theorem maxDiscount_lt_one
    (P : Game ι) [Fintype ι] [Nonempty ι] : P.maxDiscount < 1 := by
  simp [maxDiscount, Finset.sup'_lt_iff, P.discount_lt_one]

theorem maxDiscountNNReal_lt_one
    (P : Game ι) [Fintype ι] [Nonempty ι] :
    P.maxDiscountNNReal < 1 :=
  P.maxDiscount_lt_one

theorem one_sub_discount_pos (P : Game ι) (who : ι) :
    0 < 1 - P.discount who :=
  sub_pos.mpr (P.discount_lt_one who)

theorem one_sub_discount_ne (P : Game ι) (who : ι) :
    1 - P.discount who ≠ 0 :=
  ne_of_gt (P.one_sub_discount_pos who)

/-- Finite-coordinate form of equation (6). -/
theorem fCoord_eq_sum
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.X) (s : P.State) (who : ι)
    (y : stdSimplex ℝ (P.Act s who)) (e : P.R) :
    P.fCoord x s who y e =
      ∑ a : P.JointActionAt s,
        (y (a who) *
          ∏ i ∈ Finset.univ.erase who, x (s, i) (a i)) *
            P.oneStepCost e s a who := by
  classical
  unfold fCoord
  rw [expect_eq_sum]
  apply Finset.sum_congr rfl
  intro a _
  congr 1
  rw [pmfPi_apply_update_family, ENNReal.toReal_mul,
    ENNReal.toReal_prod]
  simp [actionPMF_apply_toReal, stdSimplexEquiv_symm_apply]

/-- Property (a): `f` is continuous in all three finite-dimensional
variables. -/
theorem property_a_continuous
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)] :
    Continuous (fun q : P.X × P.X × P.R => P.f q.1 q.2.1 q.2.2) := by
  classical
  apply continuous_pi
  intro s
  apply continuous_pi
  intro who
  unfold f
  simp_rw [P.fCoord_eq_sum]
  unfold oneStepCost
  simp_rw [expect_eq_sum]
  apply continuous_finsetSum Finset.univ
  intro a _
  apply Continuous.mul
  · apply Continuous.mul
    · exact (continuous_apply (a who)).comp
        (continuous_subtype_val.comp
          ((continuous_apply (s, who)).comp
            (continuous_fst.comp continuous_snd)))
    · apply continuous_finsetProd (Finset.univ.erase who)
      intro i _
      exact (continuous_apply (a i)).comp
        (continuous_subtype_val.comp
          ((continuous_apply (s, i)).comp continuous_fst))
  · apply Continuous.add
    · exact continuous_const
    · apply Continuous.mul
      · exact continuous_const
      · apply continuous_finsetSum Finset.univ
        intro s' _
        apply Continuous.mul
        · exact continuous_const
        · exact (continuous_apply who).comp
            ((continuous_apply s').comp
              (continuous_snd.comp continuous_snd))

/-- One coordinate of `f` is jointly continuous in the baseline profile and
continuation vector when the deviating mixed action is fixed. -/
theorem continuous_fCoord
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)]
    (s : P.State) (who : ι) (y : stdSimplex ℝ (P.Act s who)) :
    Continuous (fun q : P.X × P.R => P.fCoord q.1 s who y q.2) := by
  classical
  simp_rw [P.fCoord_eq_sum]
  unfold oneStepCost
  simp_rw [expect_eq_sum]
  apply continuous_finsetSum Finset.univ
  intro a _
  apply Continuous.mul
  · apply Continuous.mul
    · exact continuous_const
    · apply continuous_finsetProd (Finset.univ.erase who)
      intro i _
      exact (continuous_apply (a i)).comp
        (continuous_subtype_val.comp
          ((continuous_apply (s, i)).comp continuous_fst))
  · apply Continuous.add
    · exact continuous_const
    · apply Continuous.mul
      · exact continuous_const
      · apply continuous_finsetSum Finset.univ
        intro s' _
        apply Continuous.mul
        · exact continuous_const
        · exact (continuous_apply who).comp
            ((continuous_apply s').comp continuous_snd)

/-- With the baseline profile and continuation vector fixed, one coordinate
of `f` is continuous in the deviating mixed action. -/
theorem continuous_fCoord_deviation
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.X) (s : P.State) (who : ι) (e : P.R) :
    Continuous (fun y : stdSimplex ℝ (P.Act s who) =>
      P.fCoord x s who y e) := by
  classical
  simp_rw [P.fCoord_eq_sum]
  apply continuous_finsetSum Finset.univ
  intro a _
  apply Continuous.mul
  · apply Continuous.mul
    · exact (continuous_apply (a who)).comp continuous_subtype_val
    · exact continuous_const
  · exact continuous_const

/-- Property (b): one coordinate of `f` changes by at most `α_h` times the
sup-distance between continuation vectors. -/
theorem property_b
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.X) (s : P.State) (who : ι)
    (y : stdSimplex ℝ (P.Act s who)) (v u : P.R) :
    |P.fCoord x s who y v - P.fCoord x s who y u| ≤
      P.discount who * dist v u := by
  unfold fCoord oneStepCost
  rw [← expect_sub]
  refine abs_expect_le_of_abs_le _ _ (fun a => ?_)
  rw [add_sub_add_left_eq_sub, ← mul_sub, abs_mul,
    abs_of_nonneg (P.discount_pos who).le]
  apply mul_le_mul_of_nonneg_left _ (P.discount_pos who).le
  rw [← expect_sub]
  refine abs_expect_le_of_abs_le _ _ (fun s' => ?_)
  rw [← Real.dist_eq]
  exact (dist_le_pi_dist (v s') (u s') who).trans
    (dist_le_pi_dist v u s')

/-- The pure mixed action used in the finite minimum defining `T_x`. -/
def pureAction (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)]
    {s : P.State} {who : ι} (a : P.Act s who) :
    stdSimplex ℝ (P.Act s who) :=
  stdSimplexEquiv (PMF.pure a)

/-- Property (c): `f` is linear in the deviating mixed action. -/
theorem property_c
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.X) (s : P.State) (who : ι)
    (y : stdSimplex ℝ (P.Act s who)) (v : P.R) :
    P.fCoord x s who y v =
      wsum y (fun a => P.fCoord x s who (P.pureAction a) v) := by
  unfold fCoord
  rw [pmfPi_update_bind, expect_bind,
    expect_stdSimplexEquiv_symm_eq_wsum]
  simp [pureAction]

/-- The fixed-profile evaluation operator used in Lemma 1. -/
def valueOperator
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.X) (v : P.R) : P.R :=
  P.f x x v

/-- The fixed-profile operator is a contraction. -/
theorem contractingWith_valueOperator
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    (x : P.X) :
    ContractingWith P.maxDiscountNNReal (P.valueOperator x) := by
  refine ⟨P.maxDiscountNNReal_lt_one,
    LipschitzWith.of_dist_le_mul (fun v u => ?_)⟩
  rw [dist_pi_le_iff (by positivity)]
  intro s
  rw [dist_pi_le_iff (by positivity)]
  intro who
  rw [Real.dist_eq]
  change |P.fCoord x s who (x (s, who)) v -
      P.fCoord x s who (x (s, who)) u| ≤
    (P.maxDiscountNNReal : ℝ) * dist v u
  calc
    |P.fCoord x s who (x (s, who)) v -
        P.fCoord x s who (x (s, who)) u|
        ≤ P.discount who * dist v u :=
          P.property_b x s who (x (s, who)) v u
    _ ≤ P.maxDiscount * dist v u :=
      mul_le_mul_of_nonneg_right (P.discount_le_maxDiscount who) dist_nonneg
    _ = (P.maxDiscountNNReal : ℝ) * dist v u := rfl

/-- **Lemma 1.** For every stationary mixed profile `x`, equation (4) has a
unique solution. -/
theorem lemma_1
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    (x : P.X) : ∃! e : P.R, P.IsValueVector x e := by
  have hc := P.contractingWith_valueOperator x
  let e := ContractingWith.fixedPoint (P.valueOperator x) hc
  refine ⟨e, ?_, ?_⟩
  · change P.valueOperator x e = e
    exact hc.fixedPoint_isFixedPt
  · intro u hu
    change P.valueOperator x u = u at hu
    exact hc.fixedPoint_unique hu

/-- Equation (8): Fink's optimality operator `T_x`.  The finite minimum is
written as the negative of a finite maximum. -/
def T
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)] [∀ s i, Nonempty (P.Act s i)]
    (x : P.X) (v : P.R) : P.R :=
  fun s who =>
    -Finset.sup' Finset.univ Finset.univ_nonempty
      (fun a : P.Act s who => -P.fCoord x s who (P.pureAction a) v)

/-- The finite pure minimum is below every mixed action. -/
theorem T_le_fCoord
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)] [∀ s i, Nonempty (P.Act s i)]
    (x : P.X) (v : P.R) (s : P.State) (who : ι)
    (y : stdSimplex ℝ (P.Act s who)) :
    P.T x v s who ≤ P.fCoord x s who y v := by
  rw [P.property_c]
  calc
    P.T x v s who = wsum y (fun _ => P.T x v s who) :=
      (wsum_const y _).symm
    _ ≤ wsum y
        (fun a => P.fCoord x s who (P.pureAction a) v) := by
      apply wsum_le_wsum
      intro a
      unfold T
      have h := Finset.le_sup'
        (f := fun b : P.Act s who =>
          -P.fCoord x s who (P.pureAction b) v)
        (Finset.mem_univ a)
      linarith

/-- The finite minimum is attained by a pure action. -/
theorem exists_pure_fCoord_eq_T
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)] [∀ s i, Nonempty (P.Act s i)]
    (x : P.X) (v : P.R) (s : P.State) (who : ι) :
    ∃ a : P.Act s who,
      P.fCoord x s who (P.pureAction a) v = P.T x v s who := by
  obtain ⟨a, -, ha⟩ :=
    Finset.exists_mem_eq_sup' Finset.univ_nonempty
      (fun a : P.Act s who =>
        -P.fCoord x s who (P.pureAction a) v)
  refine ⟨a, ?_⟩
  unfold T
  rw [ha]
  ring

/-- The optimality operator is jointly continuous in the profile and
continuation vector. -/
theorem continuous_T
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)] [∀ s i, Nonempty (P.Act s i)] :
    Continuous (fun q : P.X × P.R => P.T q.1 q.2) := by
  classical
  apply continuous_pi
  intro s
  apply continuous_pi
  intro who
  change Continuous (fun q : P.X × P.R =>
    -Finset.sup' Finset.univ Finset.univ_nonempty
      (fun a : P.Act s who =>
        -P.fCoord q.1 s who (P.pureAction a) q.2))
  apply Continuous.neg
  apply Continuous.finset_sup'_apply Finset.univ_nonempty
  intro a _
  exact (P.continuous_fCoord s who (P.pureAction a)).neg

/-- **Theorem 1.** For every `x ∈ X`, `T_x` is a contraction of `R`. -/
theorem theorem_1
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)]
    (x : P.X) : ContractingWith P.maxDiscountNNReal (P.T x) := by
  refine ⟨P.maxDiscountNNReal_lt_one,
    LipschitzWith.of_dist_le_mul (fun v u => ?_)⟩
  rw [dist_pi_le_iff (by positivity)]
  intro s
  rw [dist_pi_le_iff (by positivity)]
  intro who
  rw [Real.dist_eq]
  have hcoord :
      |P.T x v s who - P.T x u s who| ≤
        P.discount who * dist v u := by
    unfold T
    have h := Math.Finset.abs_sup'_sub_sup'_le_const
      (indices := (Finset.univ : Finset (P.Act s who)))
      Finset.univ_nonempty
      (fun a => -P.fCoord x s who (P.pureAction a) v)
      (fun a => -P.fCoord x s who (P.pureAction a) u)
      (bound := P.discount who * dist v u)
      (fun a _ => by
        have hb := P.property_b x s who (P.pureAction a) v u
        simpa only [neg_sub_neg, abs_sub_comm] using hb)
    simpa only [neg_sub_neg, abs_sub_comm] using h
  calc
    |P.T x v s who - P.T x u s who|
        ≤ P.discount who * dist v u := hcoord
    _ ≤ P.maxDiscount * dist v u :=
      mul_le_mul_of_nonneg_right (P.discount_le_maxDiscount who) dist_nonneg
    _ = (P.maxDiscountNNReal : ℝ) * dist v u := rfl

/-- **Corollary 1.** For every `x ∈ X`, `T_x` has a unique fixed point. -/
theorem corollary_1
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)]
    (x : P.X) : ∃! v : P.R, P.T x v = v := by
  have hc := P.theorem_1 x
  exact ⟨ContractingWith.fixedPoint (P.T x) hc,
    hc.fixedPoint_isFixedPt,
    fun v hv => hc.fixedPoint_unique hv⟩

/-- **Corollary 2.** The family `{T_x | x ∈ X}` is equicontinuous.  This is
its metric epsilon-delta form. -/
theorem corollary_2
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)] :
    ∀ ε : ℝ, 0 < ε → ∃ δ : ℝ, 0 < δ ∧
      ∀ (x : P.X) (u v : P.R), dist u v < δ →
        dist (P.T x u) (P.T x v) < ε := by
  intro ε hε
  refine ⟨ε, hε, ?_⟩
  intro x u v huv
  have hL := (P.theorem_1 x).toLipschitzWith.dist_le_mul u v
  have hα1 : (P.maxDiscountNNReal : ℝ) < 1 := by
    change P.maxDiscount < 1
    exact P.maxDiscount_lt_one
  have hdist : 0 ≤ dist u v := dist_nonneg
  calc
    dist (P.T x u) (P.T x v)
        ≤ (P.maxDiscountNNReal : ℝ) * dist u v := hL
    _ ≤ (1 : ℝ) * dist u v :=
      mul_le_mul_of_nonneg_right hα1.le hdist
    _ < (1 : ℝ) * ε := mul_lt_mul_of_pos_left huv zero_lt_one
    _ = ε := one_mul ε

/-- Equation (9): the single-valued optimal value `β(x)`. -/
def beta
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)]
    (x : P.X) : P.R :=
  ContractingWith.fixedPoint (P.T x) (P.theorem_1 x)

@[simp] theorem T_beta
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)] (x : P.X) :
    P.T x (P.beta x) = P.beta x :=
  (P.theorem_1 x).fixedPoint_isFixedPt

/-- Equation (10): Fink's best-response correspondence `φ`. -/
def phi
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)]
    (x : P.X) : Set P.X :=
  {y | P.f x y (P.beta x) = P.beta x}

/-- Every fiber `φ(x)` is nonempty. -/
theorem phi_nonempty
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)] (x : P.X) :
    (P.phi x).Nonempty := by
  have hmin : ∀ p : P.Agent,
      ∃ a : P.AgentAction p,
        P.fCoord x p.1 p.2 (P.pureAction a) (P.beta x) =
          P.T x (P.beta x) p.1 p.2 := by
    intro p
    exact P.exists_pure_fCoord_eq_T x (P.beta x) p.1 p.2
  choose a ha using hmin
  let y : P.X := fun p => P.pureAction (a p)
  refine ⟨y, ?_⟩
  unfold phi
  funext s who
  change P.fCoord x s who (P.pureAction (a (s, who))) (P.beta x) =
    P.beta x s who
  rw [ha (s, who)]
  exact congrFun (congrFun (P.T_beta x) s) who

/-- Convexity of `φ(x)`, stated by closure under simplex segments. -/
theorem phi_segment
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)]
    (x y z : P.X) (hy : y ∈ P.phi x) (hz : z ∈ P.phi x)
    (t : ℝ) (ht0 : 0 ≤ t) (ht1 : t ≤ 1) :
    (fun p => stdSimplex.mix t ht0 ht1 (y p) (z p)) ∈ P.phi x := by
  unfold phi at hy hz ⊢
  funext s who
  have hyc := congrFun (congrFun hy s) who
  have hzc := congrFun (congrFun hz s) who
  change P.fCoord x s who (y (s, who)) (P.beta x) =
    P.beta x s who at hyc
  change P.fCoord x s who (z (s, who)) (P.beta x) =
    P.beta x s who at hzc
  change P.fCoord x s who
      (stdSimplex.mix t ht0 ht1 (y (s, who)) (z (s, who)))
      (P.beta x) = P.beta x s who
  calc
    P.fCoord x s who
        (stdSimplex.mix t ht0 ht1 (y (s, who)) (z (s, who)))
        (P.beta x)
        = wsum (stdSimplex.mix t ht0 ht1
            (y (s, who)) (z (s, who)))
            (fun a => P.fCoord x s who (P.pureAction a) (P.beta x)) :=
          P.property_c x s who _ (P.beta x)
    _ = t * wsum (y (s, who))
          (fun a => P.fCoord x s who (P.pureAction a) (P.beta x)) +
        (1 - t) * wsum (z (s, who))
          (fun a => P.fCoord x s who (P.pureAction a) (P.beta x)) := by
          rw [wsum_mix]
    _ = t * P.fCoord x s who (y (s, who)) (P.beta x) +
        (1 - t) * P.fCoord x s who (z (s, who)) (P.beta x) := by
          rw [← P.property_c, ← P.property_c]
    _ = P.beta x s who := by rw [hyc, hzc]; ring

/-- Closedness of each fiber `φ(x)`. -/
theorem phi_isClosed
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)] (x : P.X) :
    IsClosed (P.phi x) := by
  have hset : P.phi x =
      ⋂ s : P.State, ⋂ who : ι,
        {y : P.X |
          P.fCoord x s who (y (s, who)) (P.beta x) = P.beta x s who} := by
    ext y
    constructor
    · intro hy
      change P.f x y (P.beta x) = P.beta x at hy
      rw [Set.mem_iInter₂]
      intro s who
      exact congrFun (congrFun hy s) who
    · intro hy
      change P.f x y (P.beta x) = P.beta x
      funext s who
      exact Set.mem_iInter₂.mp hy s who
  rw [hset]
  apply isClosed_iInter
  intro s
  apply isClosed_iInter
  intro who
  exact isClosed_eq
    ((P.continuous_fCoord_deviation x s who (P.beta x)).comp
      (continuous_apply (s, who)))
    continuous_const

/-- A common absolute bound for the finite cost table. -/
def costBound
    (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)] : ℝ := by
  letI : ∀ s, Fintype (P.JointActionAt s) :=
    fun s => Fintype.ofFinite (P.JointActionAt s)
  exact ∑ s : P.State, ∑ a : P.JointActionAt s, ∑ who : ι,
    |P.cost s a who|

theorem costBound_nonneg
    (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)] : 0 ≤ P.costBound := by
  letI : ∀ s, Fintype (P.JointActionAt s) :=
    fun s => Fintype.ofFinite (P.JointActionAt s)
  unfold costBound
  exact Finset.sum_nonneg fun _ _ =>
    Finset.sum_nonneg fun _ _ =>
      Finset.sum_nonneg fun _ _ => abs_nonneg _

theorem abs_cost_le_costBound
    (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)]
    (s : P.State) (a : P.JointActionAt s) (who : ι) :
    |P.cost s a who| ≤ P.costBound := by
  classical
  letI : ∀ s, Fintype (P.JointActionAt s) :=
    fun s => Fintype.ofFinite (P.JointActionAt s)
  unfold costBound
  calc
    |P.cost s a who| ≤ ∑ who' : ι, |P.cost s a who'| := by
      exact Finset.single_le_sum
        (f := fun who' : ι => |P.cost s a who'|)
        (fun _ _ => abs_nonneg _) (Finset.mem_univ who)
    _ ≤ ∑ a' : P.JointActionAt s, ∑ who' : ι, |P.cost s a' who'| := by
      exact Finset.single_le_sum
        (f := fun a' : P.JointActionAt s =>
          ∑ who' : ι, |P.cost s a' who'|)
        (fun _ _ => Finset.sum_nonneg fun _ _ => abs_nonneg _)
        (Finset.mem_univ a)
    _ ≤ ∑ s' : P.State,
        ∑ a' : P.JointActionAt s', ∑ who' : ι, |P.cost s' a' who'| := by
      exact Finset.single_le_sum
        (f := fun s' : P.State =>
          ∑ a' : P.JointActionAt s',
            ∑ who' : ι, |P.cost s' a' who'|)
        (fun _ _ => Finset.sum_nonneg fun _ _ =>
          Finset.sum_nonneg fun _ _ => abs_nonneg _)
        (Finset.mem_univ s)

theorem abs_fCoord_zero_le_costBound
    (P : Game ι) [Fintype P.State] [Fintype ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    (x : P.X) (s : P.State) (who : ι)
    (y : stdSimplex ℝ (P.Act s who)) :
    |P.fCoord x s who y (0 : P.R)| ≤ P.costBound := by
  unfold fCoord
  refine abs_expect_le_of_abs_le _ _ (fun a => ?_)
  have h := P.abs_cost_le_costBound s a who
  simpa [oneStepCost] using h

theorem dist_zero_T_zero_le_costBound
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)] (x : P.X) :
    dist (0 : P.R) (P.T x 0) ≤ P.costBound := by
  rw [dist_pi_le_iff P.costBound_nonneg]
  intro s
  rw [dist_pi_le_iff P.costBound_nonneg]
  intro who
  rw [Real.dist_eq]
  simp only [Pi.zero_apply, zero_sub, abs_neg]
  obtain ⟨a, ha⟩ := P.exists_pure_fCoord_eq_T x 0 s who
  rw [← ha]
  exact P.abs_fCoord_zero_le_costBound x s who (P.pureAction a)

/-- **Lemma 2.** The range of `β(x)` is bounded. -/
theorem lemma_2
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)] :
    ∃ B : ℝ, ∀ (x : P.X) (s : P.State) (who : ι),
      |P.beta x s who| ≤ B := by
  let B : ℝ := P.costBound /
    (1 - (P.maxDiscountNNReal : ℝ))
  refine ⟨B, ?_⟩
  intro x s who
  have hα : (P.maxDiscountNNReal : ℝ) < 1 := by
    change P.maxDiscount < 1
    exact P.maxDiscount_lt_one
  have hden : 0 < 1 - (P.maxDiscountNNReal : ℝ) := sub_pos.mpr hα
  have hfixed :
      dist (0 : P.R) (P.beta x) ≤
        dist (0 : P.R) (P.T x 0) /
          (1 - (P.maxDiscountNNReal : ℝ)) := by
    simpa [beta] using
      (P.theorem_1 x).dist_fixedPoint_le (0 : P.R)
  have hglobal : dist (0 : P.R) (P.beta x) ≤ B := by
    exact hfixed.trans
      ((div_le_div_iff_of_pos_right hden).2
        (P.dist_zero_T_zero_le_costBound x))
  calc
    |P.beta x s who| = dist ((0 : P.R) s who) (P.beta x s who) := by
      simp [Real.dist_eq]
    _ ≤ dist ((0 : P.R) s) (P.beta x s) :=
      dist_le_pi_dist ((0 : P.R) s) (P.beta x s) who
    _ ≤ dist (0 : P.R) (P.beta x) :=
      dist_le_pi_dist (0 : P.R) (P.beta x) s
    _ ≤ B := hglobal

/-- Fink's notation `S_v(x)=T_x v`. -/
abbrev S
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)] [∀ s i, Nonempty (P.Act s i)]
    (v : P.R) (x : P.X) : P.R :=
  P.T x v

/-- A compact cube containing all continuation vectors with coordinatewise
absolute value at most `B`. -/
def valueCube (P : Game ι) (B : ℝ) : Set P.R :=
  Set.Icc (fun _ _ => -B) (fun _ _ => B)

set_option maxHeartbeats 800000 in
theorem valueCube_isCompact
    (P : Game ι) [Fintype P.State] [Fintype ι] (B : ℝ) :
    IsCompact (P.valueCube B) := by
  exact isCompact_Icc

set_option maxHeartbeats 800000 in
/-- **Lemma 3, first part.** For fixed `v`, `S_v` is continuous on `X`. -/
theorem lemma_3_continuous
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)] [∀ s i, Nonempty (P.Act s i)]
    (v : P.R) : Continuous (P.S v) := by
  change Continuous (fun x : P.X => P.T x v)
  have hpair : Continuous (fun x : P.X => (x, v)) :=
    continuous_id.prodMk continuous_const
  exact P.continuous_T.comp hpair

set_option maxHeartbeats 800000 in
/-- **Lemma 3, second part.** On every bounded value cube, the family
`{S_v}` is equicontinuous.  `TendstoUniformly` is the paper's uniform-in-`v`
formulation. -/
theorem lemma_3_equicontinuous
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)] [∀ s i, Nonempty (P.Act s i)]
    (B : ℝ) (x : P.X) :
    TendstoUniformly
      (fun x' (v : {v : P.R // v ∈ P.valueCube B}) => P.S v.1 x')
      (fun v => P.S v.1 x) (𝓝 x) := by
  change TendstoUniformly
    (fun x' (v : {v : P.R // v ∈ P.valueCube B}) => P.T x' v.1)
    (fun v => P.T x v.1) (𝓝 x)
  letI : CompactSpace {v : P.R // v ∈ P.valueCube B} :=
    isCompact_iff_compactSpace.mp (P.valueCube_isCompact B)
  exact Continuous.tendstoUniformly
    (fun x' (v : {v : P.R // v ∈ P.valueCube B}) => P.T x' v.1)
    (P.continuous_T.comp
      (continuous_fst.prodMk (continuous_subtype_val.comp continuous_snd))) x

set_option maxHeartbeats 800000 in
/-- The fixed point `β(x)` depends continuously on the profile.  This is the
uniform-contraction parameter theorem specialized to Fink's `T_x`. -/
theorem continuous_beta
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)] : Continuous P.beta := by
  rw [continuous_iff_continuousAt]
  intro x
  rw [Metric.continuousAt_iff]
  intro ε hε
  have hα : (P.maxDiscountNNReal : ℝ) < 1 := by
    change P.maxDiscount < 1
    exact P.maxDiscount_lt_one
  have hden : 0 < 1 - (P.maxDiscountNNReal : ℝ) := sub_pos.mpr hα
  have hcont : ContinuousAt (P.S (P.beta x)) x :=
    (P.lemma_3_continuous (P.beta x)).continuousAt
  rw [Metric.continuousAt_iff] at hcont
  obtain ⟨δ, hδ, hδbound⟩ :=
    hcont (ε * (1 - (P.maxDiscountNNReal : ℝ))) (mul_pos hε hden)
  refine ⟨δ, hδ, ?_⟩
  intro x' hx'
  have hres :
      dist (P.T x' (P.beta x)) (P.beta x) <
        ε * (1 - (P.maxDiscountNNReal : ℝ)) := by
    simpa [S, P.T_beta x] using hδbound hx'
  have hfixed :
      dist (P.beta x) (P.beta x') ≤
        dist (P.beta x) (P.T x' (P.beta x)) /
          (1 - (P.maxDiscountNNReal : ℝ)) :=
    (P.theorem_1 x').dist_le_of_fixedPoint
      (P.beta x) (P.T_beta x')
  calc
    dist (P.beta x') (P.beta x) = dist (P.beta x) (P.beta x') :=
      dist_comm _ _
    _ ≤ dist (P.beta x) (P.T x' (P.beta x)) /
          (1 - (P.maxDiscountNNReal : ℝ)) := hfixed
    _ = dist (P.T x' (P.beta x)) (P.beta x) /
          (1 - (P.maxDiscountNNReal : ℝ)) := by rw [dist_comm]
    _ < (ε * (1 - (P.maxDiscountNNReal : ℝ))) /
          (1 - (P.maxDiscountNNReal : ℝ)) :=
      (div_lt_div_iff_of_pos_right hden).2 hres
    _ = ε := by field_simp [ne_of_gt hden]

set_option maxHeartbeats 800000 in
/-- **Lemma 4.** The graph of `β` is sequentially closed. -/
theorem lemma_4
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)]
    {xn : ℕ → P.X} {x : P.X} {v₀ : P.R}
    (hx : Tendsto xn atTop (𝓝 x))
    (hv : Tendsto (fun n => P.beta (xn n)) atTop (𝓝 v₀)) :
    P.beta x = v₀ := by
  have hβ : Tendsto (fun n => P.beta (xn n)) atTop (𝓝 (P.beta x)) :=
    P.continuous_beta.continuousAt.tendsto.comp hx
  exact tendsto_nhds_unique hβ hv

set_option maxHeartbeats 800000 in
/-- **Lemma 5.** The graph of the best-response correspondence `φ` is
sequentially closed. -/
theorem lemma_5
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)]
    {xn yn : ℕ → P.X} {x y : P.X}
    (hx : Tendsto xn atTop (𝓝 x)) (hy : Tendsto yn atTop (𝓝 y))
    (hphi : ∀ n, yn n ∈ P.phi (xn n)) :
    y ∈ P.phi x := by
  have hβ : Tendsto (fun n => P.beta (xn n)) atTop (𝓝 (P.beta x)) :=
    P.continuous_beta.continuousAt.tendsto.comp hx
  have htriple : Tendsto
      (fun n => (xn n, yn n, P.beta (xn n))) atTop
      (𝓝 (x, y, P.beta x)) :=
    hx.prodMk_nhds (hy.prodMk_nhds hβ)
  have hf : Tendsto
      (fun n => P.f (xn n) (yn n) (P.beta (xn n))) atTop
      (𝓝 (P.f x y (P.beta x))) :=
    P.property_a_continuous.continuousAt.tendsto.comp htriple
  have heq :
      (fun n => P.f (xn n) (yn n) (P.beta (xn n))) =
        fun n => P.beta (xn n) := by
    funext n
    simpa [phi] using hphi n
  rw [heq] at hf
  have hlimit : P.f x y (P.beta x) = P.beta x :=
    tendsto_nhds_unique hf hβ
  simpa [phi] using hlimit

/-! ## Internal contingent-plan adapter for Theorem 2 -/

/-- A state-independent pure action in the production game is a complete
contingent plan, one paper action for every state. -/
abbrev AmbientAct (P : Game ι) (i : ι) := ∀ s, P.Act s i

/-- The reward game used by the reusable production theorem.  It evaluates a
contingent plan only at the current state and negates the paper's cost. -/
abbrev rewardGame (P : Game ι) : StochasticGame ι where
  State := P.State
  Act := P.AmbientAct
  stagePayoff := fun s a who => -P.cost s (fun i => a i s) who
  transition := fun s a => P.transition s (fun i => a i s)
  discount := 0
  discount_nonneg := le_rfl
  discount_lt_one := zero_lt_one

/-- The current-state marginal of a production stationary profile. -/
def effectiveMixedAction
    (P : Game ι) [Fintype ι]
    (x : P.rewardGame.StationaryMixedProfile)
    (s : P.State) (i : ι) : PMF (P.Act s i) :=
  (x s i).map (fun plan => plan s)

/-- The literal paper profile induced by all current-state marginals. -/
def effectiveProfile
    (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.rewardGame.StationaryMixedProfile) : P.X :=
  fun p => stdSimplexEquiv (P.effectiveMixedAction x p.1 p.2)

@[simp] theorem actionPMF_effectiveProfile
    (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.rewardGame.StationaryMixedProfile) (s : P.State) (i : ι) :
    P.actionPMF (P.effectiveProfile x) s i = P.effectiveMixedAction x s i := by
  exact (stdSimplexEquiv (α := P.Act s i)).symm_apply_apply _

/-- Extend one local action to a complete contingent plan using fixed actions
at every other state. -/
def extendAction (P : Game ι) (s : P.State) (i : ι)
    (a : P.Act s i) : P.AmbientAct i := by
  classical
  exact fun t =>
    if h : t = s then h.symm ▸ a else Classical.choice (P.act_nonempty t i)

@[simp] theorem extendAction_apply_same
    (P : Game ι) (s : P.State) (i : ι) (a : P.Act s i) :
    P.extendAction s i a s = a := by
  classical
  simp [extendAction]

/-- Lift a local mixed action to a production-game mixed contingent plan. -/
def liftMixedAction
    (P : Game ι) (s : P.State) (i : ι) (y : PMF (P.Act s i)) :
    PMF (P.AmbientAct i) :=
  y.map (P.extendAction s i)

@[simp] theorem map_liftMixedAction_eval
    (P : Game ι) (s : P.State) (i : ι) (y : PMF (P.Act s i)) :
    (P.liftMixedAction s i y).map (fun plan => plan s) = y := by
  rw [liftMixedAction, PMF.map_comp]
  rw [show (fun plan => plan s) ∘ P.extendAction s i = id by
    funext a
    exact P.extendAction_apply_same s i a]
  exact PMF.map_id y

theorem map_update_eval
    (P : Game ι) [Fintype ι] [DecidableEq ι]
    (m : ∀ i, PMF (P.AmbientAct i)) (s : P.State) (who : ι)
    (y : PMF (P.Act s who)) :
    (fun i => ((Function.update m who (P.liftMixedAction s who y)) i).map
      (fun plan => plan s)) =
      Function.update (fun i => (m i).map (fun plan => plan s)) who y := by
  classical
  funext i
  by_cases hi : i = who
  · subst i
    simp
  · simp [Function.update_of_ne hi]

/-- Fink's unnormalized cost value encoded as a normalized reward value. -/
def normalizedRewardValue (P : Game ι) (e : P.R) : P.R :=
  fun s who => -(1 - P.discount who) * e s who

/-- Marginalization of independent contingent plans commutes with their
product distribution. -/
theorem pmfPi_map_eval
    (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)]
    (m : ∀ i, PMF (P.AmbientAct i)) (s : P.State) :
    (pmfPi m).map (fun a => fun i => a i s) =
      pmfPi (fun i => (m i).map (fun plan => plan s)) := by
  exact pmfPi_push_coordwise m (fun i plan => plan s)

/-- The production auxiliary payoff is exactly the negative scaled paper
cost expression after taking current-state marginals. -/
theorem reward_discountedAuxEU_eq_fCoord
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)]
    (m : ∀ i, PMF (P.AmbientAct i)) (e : P.R)
    (s : P.State) (who : ι) :
    P.rewardGame.discountedAuxEU (P.discount who)
        (P.normalizedRewardValue e) s m who =
      -(1 - P.discount who) *
        expect (pmfPi (fun i => (m i).map (fun plan => plan s)))
          (fun a => P.oneStepCost e s a who) := by
  change
    expect (pmfPi m)
      (fun a =>
        (1 - P.discount who) *
            (-P.cost s (fun i => a i s) who) +
          P.discount who *
            expect (P.transition s (fun i => a i s))
              (fun s' => -(1 - P.discount who) * e s' who)) = _
  simp_rw [expect_const_mul]
  calc
    expect (pmfPi m)
        (fun a =>
          (1 - P.discount who) *
              (-P.cost s (fun i => a i s) who) +
            P.discount who *
              (-(1 - P.discount who) *
                expect (P.transition s (fun i => a i s))
                  (fun s' => e s' who)))
        = expect (pmfPi m)
            (fun a => -(1 - P.discount who) *
              P.oneStepCost e s (fun i => a i s) who) := by
            apply congrArg (expect (pmfPi m))
            funext a
            unfold oneStepCost
            ring
    _ = -(1 - P.discount who) *
          expect (pmfPi m)
            (fun a => P.oneStepCost e s (fun i => a i s) who) := by
          rw [expect_const_mul]
    _ = -(1 - P.discount who) *
          expect ((pmfPi m).map (fun a => fun i => a i s))
            (fun a => P.oneStepCost e s a who) := by
          rw [expect_map]
    _ = -(1 - P.discount who) *
          expect (pmfPi (fun i => (m i).map (fun plan => plan s)))
            (fun a => P.oneStepCost e s a who) := by
          rw [P.pmfPi_map_eval m s]

/-- The bridge specialized to the current-state marginals of a stationary
production profile. -/
theorem reward_discountedAuxEU_eq_fCoord_effectiveProfile
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.rewardGame.StationaryMixedProfile) (e : P.R)
    (s : P.State) (who : ι) :
    P.rewardGame.discountedAuxEU (P.discount who)
        (P.normalizedRewardValue e) s (x s) who =
      -(1 - P.discount who) *
        P.fCoord (P.effectiveProfile x) s who
          (P.effectiveProfile x (s, who)) e := by
  rw [P.reward_discountedAuxEU_eq_fCoord (x s) e s who]
  apply congrArg (fun z : ℝ => -(1 - P.discount who) * z)
  unfold fCoord
  have hbase :
      (fun i => P.actionPMF (P.effectiveProfile x) s i) =
        fun i => P.effectiveMixedAction x s i := by
    funext i
    exact P.actionPMF_effectiveProfile x s i
  have hown :
      (stdSimplexEquiv (α := P.Act s who)).symm
          (P.effectiveProfile x (s, who)) =
        P.effectiveMixedAction x s who := by
    exact (stdSimplexEquiv (α := P.Act s who)).symm_apply_apply _
  have hmarg :
      (fun i => (x s i).map (fun plan => plan s)) =
        fun i => P.effectiveMixedAction x s i := rfl
  have hupdate :
      Function.update (fun i => P.effectiveMixedAction x s i) who
          (P.effectiveMixedAction x s who) =
        fun i => P.effectiveMixedAction x s i := by
    funext i
    by_cases hi : i = who
    · subst i
      simp
    · simp [Function.update_of_ne hi]
  rw [hmarg, hbase, hown, hupdate]

/-- The bridge specialized to a literal one-state deviation lifted to a
contingent plan. -/
theorem reward_discountedAuxEU_lift_eq_fCoord
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.rewardGame.StationaryMixedProfile) (e : P.R)
    (s : P.State) (who : ι)
    (y : stdSimplex ℝ (P.Act s who)) :
    P.rewardGame.discountedAuxEU (P.discount who)
        (P.normalizedRewardValue e) s
        (Function.update (x s) who
          (P.liftMixedAction s who
            ((stdSimplexEquiv (α := P.Act s who)).symm y))) who =
      -(1 - P.discount who) *
        P.fCoord (P.effectiveProfile x) s who y e := by
  let d : PMF (P.Act s who) :=
    (stdSimplexEquiv (α := P.Act s who)).symm y
  let m' : ∀ i, PMF (P.AmbientAct i) :=
    Function.update (x s) who (P.liftMixedAction s who d)
  change P.rewardGame.discountedAuxEU (P.discount who)
      (P.normalizedRewardValue e) s m' who = _
  calc
    _ = -(1 - P.discount who) *
        expect (pmfPi (fun i => (m' i).map (fun plan => plan s)))
          (fun a => P.oneStepCost e s a who) :=
      P.reward_discountedAuxEU_eq_fCoord m' e s who
    _ = -(1 - P.discount who) *
        expect (pmfPi
          (Function.update (fun i => P.effectiveMixedAction x s i) who d))
          (fun a => P.oneStepCost e s a who) := by
      apply congrArg (fun z : ℝ => -(1 - P.discount who) * z)
      apply congrArg (fun μ =>
        expect μ (fun a => P.oneStepCost e s a who))
      apply congrArg pmfPi
      dsimp [m']
      rw [P.map_update_eval]
      rfl
    _ = -(1 - P.discount who) *
        P.fCoord (P.effectiveProfile x) s who y e := by
      apply congrArg (fun z : ℝ => -(1 - P.discount who) * z)
      unfold fCoord
      have hbase :
          (fun i => P.actionPMF (P.effectiveProfile x) s i) =
            fun i => P.effectiveMixedAction x s i := by
        funext i
        exact P.actionPMF_effectiveProfile x s i
      rw [hbase]
      rfl

/-- The production reward table is bounded by the literal cost-table bound. -/
theorem abs_rewardGame_stagePayoff_le_costBound
    (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)]
    (s : P.State) (a : P.rewardGame.JointAct) (who : ι) :
    |P.rewardGame.stagePayoff s a who| ≤ P.costBound := by
  have h := P.abs_cost_le_costBound s (fun i => a i s) who
  simpa [rewardGame] using h

/-- **Theorem 2.** There are `x ∈ X` and `v ∈ R` such that
`v=f(x,x,v)=min_y f(x,y,v)`, equivalently `x ∈ φ(x)`.  The returned profile
is on the paper's literal state-dependent action sets. -/
theorem theorem_2
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)] :
    ∃ (x : P.X) (e : P.R), P.IsEquilibriumPoint x e := by
  letI : ∀ i, Fintype (P.AmbientAct i) :=
    fun i => Fintype.ofFinite (P.AmbientAct i)
  letI : Finite P.rewardGame.State := inferInstanceAs (Finite P.State)
  letI : ∀ i, Finite (P.rewardGame.Act i) :=
    fun i => inferInstanceAs (Finite (P.AmbientAct i))
  letI : ∀ i, Nonempty (P.rewardGame.Act i) :=
    fun i => inferInstanceAs (Nonempty (P.AmbientAct i))
  obtain ⟨m, V, hcert⟩ :=
    P.rewardGame.exists_isPlayerDiscountedStationaryBellmanEq
      P.discount P.costBound P.costBound_nonneg
      (fun who => (P.discount_pos who).le)
      (fun who => (P.discount_lt_one who).le)
      P.abs_rewardGame_stagePayoff_le_costBound
  let e : P.R := fun s who => -V s who / (1 - P.discount who)
  let x : P.X := P.effectiveProfile m
  have hencode : P.normalizedRewardValue e = V := by
    funext s who
    dsimp [normalizedRewardValue, e]
    field_simp [P.one_sub_discount_ne who]
  refine ⟨x, e, ?_, ?_⟩
  · unfold IsValueVector
    funext s who
    have hbridge :=
      P.reward_discountedAuxEU_eq_fCoord_effectiveProfile m e s who
    rw [hencode, hcert.2 s who] at hbridge
    change P.fCoord x s who (x (s, who)) e = e s who
    dsimp [x, e]
    apply (eq_div_iff (P.one_sub_discount_ne who)).2
    nlinarith [hbridge]
  · intro s who y
    have hnash := hcert.1 s who
      (P.liftMixedAction s who
        ((stdSimplexEquiv (α := P.Act s who)).symm y))
    rw [← hencode] at hnash
    rw [P.reward_discountedAuxEU_lift_eq_fCoord m e s who y,
      P.reward_discountedAuxEU_eq_fCoord_effectiveProfile m e s who] at hnash
    change P.fCoord x s who (x (s, who)) e ≤ P.fCoord x s who y e
    dsimp [x]
    nlinarith [P.one_sub_discount_pos who]

/-!
## Closing remarks

Fink observes after Theorem 2 that Lemmas 2 and 4 make `β` continuous, hence
its range is compact and connected.  He then sketches two extensions: to a
denumerable state set with uniformly bounded costs by replacing `R` by the
bounded-sequence space, and to arbitrary action cardinalities by replacing
`min` with `inf`, yielding ε-effective strategies.  The finite theorem above
does not silently strengthen those sketches: the closing paragraph does not
state the topology and compactness hypotheses required for a unique
infinite-action Lean theorem.  The comparisons with Shapley's two-player
result and the one-player dynamic-programming case are bibliographic remarks.
-/

end Game

end Literature.Fink1964
