import UniformEquilibrium.ProofView.Concepts.Stochastic.Equilibrium.Discounted.FinkHeterogeneous
import MathUE.Finset.SupNonexpansive
import Mathlib.Topology.UniformSpace.HeineCantor

/-!
# A. M. Fink, *Equilibrium in a Stochastic n-Person Game* (1964)

A. M. Fink, “Equilibrium in a Stochastic n-Person Game,”
*Journal of Science of the Hiroshima University, Series A-I* **28** (1964),
89–93. DOI: `10.32917/hmj/1206139508`.

This is a paper-order audit.  The paper's action set `J^h(i)` is represented
literally by `Game.Act i h`; no padded action appears in the reader-facing
strategy space `Game.X`.  The only padding is the internal contingent-plan
adapter `Game.rewardGame`, used to invoke the reusable player-dependent Fink
fixed-point theorem in the proof of Theorem 2.  The marginalization lemmas below identify the required transfer back to the
literal state-dependent action sets.  The final reward/cost bridge and Theorem 2
are stated explicitly; until their proofs are discharged, those conclusions remain
`sorry`-backed rather than checked.
-/

noncomputable section

namespace Literature.Fink1964

open GameTheory
open GameTheory.StochasticGame
open Filter Set
open Math.Probability
open Math.PMFProduct
open Math.ProbabilityMassFunction
open scoped NNReal Topology

/-- The finite stochastic cost game on pages 89--90. -/
structure Game (ι : Type) where
  State : Type
  state_nonempty : Nonempty State
  Act : State → ι → Type
  act_nonempty : ∀ s i, Nonempty (Act s i)
  cost : (s : State) → (∀ i, Act s i) → ι → ℝ
  transition : (s : State) → (∀ i, Act s i) → PMF State
  discount : ι → ℝ
  discount_pos : ∀ i, 0 < discount i
  discount_lt_one : ∀ i, discount i < 1

variable {ι : Type}

namespace Game

instance instNonemptyState (P : Game ι) : Nonempty P.State := P.state_nonempty

instance instNonemptyAct (P : Game ι) (s : P.State) (i : ι) :
    Nonempty (P.Act s i) := P.act_nonempty s i

/-- The paper's state-player coordinates. -/
abbrev Agent (P : Game ι) := P.State × ι

/-- The paper's action set `J^h(i)` at a state-player coordinate. -/
abbrev AgentAction (P : Game ι) (p : P.Agent) := P.Act p.1 p.2

/-- The compact product `X` of all state-player mixed-action simplices. -/
abbrev X (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)] :=
  MixedSimplex P.Agent P.AgentAction

/-- The value space `R`, with the sup metric inherited from the finite pi type. -/
abbrev R (P : Game ι) := P.State → Payoff ι

/-- A literal joint action at state `s`. -/
abbrev JointActionAt (P : Game ι) (s : P.State) := ∀ i, P.Act s i

/-- The PMF represented by one simplex coordinate. -/
def actionPMF (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.X) (s : P.State) (i : ι) : PMF (P.Act s i) :=
  (stdSimplexEquiv (α := P.Act s i)).symm (x (s, i))

@[simp] theorem actionPMF_apply_toReal
    (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.X) (s : P.State) (i : ι) (a : P.Act s i) :
    ((P.actionPMF x s i) a).toReal = x (s, i) a := by
  simp [actionPMF, stdSimplexEquiv_symm_apply]

/-- Equation (3)'s one-stage cost plus discounted continuation cost. -/
def oneStepCost (P : Game ι)
    (e : P.R) (s : P.State) (a : P.JointActionAt s) (who : ι) : ℝ :=
  P.cost s a who +
    P.discount who * expect (P.transition s a) (fun s' => e s' who)

/-- Equation (6), at one state-player coordinate. -/
def fCoord (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)] [DecidableEq ι]
    (x : P.X) (s : P.State) (who : ι)
    (y : stdSimplex ℝ (P.Act s who)) (e : P.R) : ℝ :=
  expect (pmfPi (Function.update (fun i => P.actionPMF x s i) who
    ((stdSimplexEquiv (α := P.Act s who)).symm y)))
    (fun a => P.oneStepCost e s a who)

/-- Equation (6), assembled as the vector function `f(x,y,e)`. -/
def f (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)] [DecidableEq ι]
    (x y : P.X) (e : P.R) : P.R :=
  fun s who => P.fCoord x s who (y (s, who)) e

/-- Equation (4): `e(x)` is the value vector generated by `x`. -/
def IsValueVector (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)] [DecidableEq ι]
    (x : P.X) (e : P.R) : Prop :=
  P.f x x e = e

/-- Equation (5), equivalently `x ∈ φ(x)`: no player can lower cost by
changing one statewise mixed action. -/
def IsEquilibriumPoint (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)] [DecidableEq ι]
    (x : P.X) (e : P.R) : Prop :=
  P.IsValueVector x e ∧
    ∀ s who (y : stdSimplex ℝ (P.Act s who)),
      P.fCoord x s who (x (s, who)) e ≤ P.fCoord x s who y e

/-- The largest player discount, Fink's common contraction coefficient
`α = max_h α_h`. -/
def maxDiscount (P : Game ι) [Fintype ι] [Nonempty ι] : ℝ :=
  Finset.sup' Finset.univ Finset.univ_nonempty P.discount

/-- The largest discount as a nonnegative Lipschitz constant. -/
def maxDiscountNNReal (P : Game ι) [Fintype ι] [Nonempty ι] : ℝ≥0 :=
  ⟨P.maxDiscount, by
    obtain ⟨i⟩ := ‹Nonempty ι›
    exact (P.discount_pos i).le.trans
      (Finset.le_sup' (f := P.discount) (Finset.mem_univ i))⟩

theorem discount_le_maxDiscount
    (P : Game ι) [Fintype ι] [Nonempty ι] (who : ι) :
    P.discount who ≤ P.maxDiscount :=
  Finset.le_sup' (f := P.discount) (Finset.mem_univ who)

theorem maxDiscount_lt_one
    (P : Game ι) [Fintype ι] [Nonempty ι] : P.maxDiscount < 1 := by
  simp [maxDiscount, Finset.sup'_lt_iff, P.discount_lt_one]

theorem maxDiscountNNReal_lt_one
    (P : Game ι) [Fintype ι] [Nonempty ι] :
    P.maxDiscountNNReal < 1 :=
  P.maxDiscount_lt_one

/-- Property (a): `f` is continuous in all three finite-dimensional
variables. -/
theorem property_a_continuous
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)] :
    Continuous (fun q : P.X × P.X × P.R => P.f q.1 q.2.1 q.2.2) := by
  classical
  unfold f fCoord oneStepCost actionPMF
  simp_rw [expect_eq_sum, pmfPi_apply, ENNReal.toReal_prod]
  simp only [stdSimplexEquiv_symm_apply, ofVector_toReal]
  fun_prop

/-- Property (b): one coordinate of `f` changes by at most `α_h` times the
sup-distance between continuation vectors. -/
theorem property_b
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.X) (s : P.State) (who : ι)
    (y : stdSimplex ℝ (P.Act s who)) (v u : P.R) :
    |P.fCoord x s who y v - P.fCoord x s who y u| ≤
      P.discount who * dist v u := by
  unfold fCoord oneStepCost
  rw [← expect_sub]
  refine abs_expect_le_of_abs_le _ _ (fun a => ?_)
  rw [add_sub_add_left_eq_sub, ← mul_sub, abs_mul,
    abs_of_nonneg (P.discount_pos who).le]
  apply mul_le_mul_of_nonneg_left _ (P.discount_pos who).le
  rw [← expect_sub]
  refine abs_expect_le_of_abs_le _ _ (fun s' => ?_)
  rw [← Real.dist_eq]
  exact (dist_le_pi_dist (v s') (u s') who).trans
    (dist_le_pi_dist v u s')

/-- The pure mixed action used in the finite minimum defining `T_x`. -/
def pureAction (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)]
    {s : P.State} {who : ι} (a : P.Act s who) :
    stdSimplex ℝ (P.Act s who) :=
  stdSimplexEquiv (PMF.pure a)

/-- Property (c): `f` is linear in the deviating mixed action. -/
theorem property_c
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.X) (s : P.State) (who : ι)
    (y : stdSimplex ℝ (P.Act s who)) (v : P.R) :
    P.fCoord x s who y v =
      wsum y (fun a => P.fCoord x s who (P.pureAction a) v) := by
  unfold fCoord
  rw [pmfPi_update_bind, expect_bind,
    expect_stdSimplexEquiv_symm_eq_wsum]
  simp [pureAction]

/-- The fixed-profile evaluation operator used in Lemma 1. -/
def valueOperator
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.X) (v : P.R) : P.R :=
  P.f x x v

/-- The fixed-profile operator is a contraction. -/
theorem contractingWith_valueOperator
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    (x : P.X) :
    ContractingWith P.maxDiscountNNReal (P.valueOperator x) := by
  refine ⟨P.maxDiscountNNReal_lt_one,
    LipschitzWith.of_dist_le_mul (fun v u => ?_)⟩
  rw [dist_pi_le_iff (by positivity)]
  intro s
  rw [dist_pi_le_iff (by positivity)]
  intro who
  rw [Real.dist_eq]
  change |P.fCoord x s who (x (s, who)) v -
      P.fCoord x s who (x (s, who)) u| ≤
    (P.maxDiscountNNReal : ℝ) * dist v u
  calc
    |P.fCoord x s who (x (s, who)) v -
        P.fCoord x s who (x (s, who)) u|
        ≤ P.discount who * dist v u :=
          P.property_b x s who (x (s, who)) v u
    _ ≤ P.maxDiscount * dist v u :=
      mul_le_mul_of_nonneg_right (P.discount_le_maxDiscount who) dist_nonneg
    _ = (P.maxDiscountNNReal : ℝ) * dist v u := rfl

/-- **Lemma 1.** For every stationary mixed profile `x`, equation (4) has a
unique solution. -/
theorem lemma_1
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    (x : P.X) : ∃! e : P.R, P.IsValueVector x e := by
  have hc := P.contractingWith_valueOperator x
  let e := ContractingWith.fixedPoint (P.valueOperator x) hc
  refine ⟨e, ?_, ?_⟩
  · change P.valueOperator x e = e
    exact hc.fixedPoint_isFixedPt
  · intro u hu
    change P.valueOperator x u = u at hu
    exact hc.fixedPoint_unique hu

/-- Equation (8): Fink's optimality operator `T_x`.  The finite minimum is
written as the negative of a finite maximum. -/
def T
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)] [∀ s i, Nonempty (P.Act s i)]
    (x : P.X) (v : P.R) : P.R :=
  fun s who =>
    -Finset.sup' Finset.univ Finset.univ_nonempty
      (fun a : P.Act s who => -P.fCoord x s who (P.pureAction a) v)

/-- The finite pure minimum is below every mixed action. -/
theorem T_le_fCoord
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)] [∀ s i, Nonempty (P.Act s i)]
    (x : P.X) (v : P.R) (s : P.State) (who : ι)
    (y : stdSimplex ℝ (P.Act s who)) :
    P.T x v s who ≤ P.fCoord x s who y v := by
  rw [P.property_c]
  calc
    P.T x v s who = wsum y (fun _ => P.T x v s who) :=
      (wsum_const y _).symm
    _ ≤ wsum y
        (fun a => P.fCoord x s who (P.pureAction a) v) := by
      apply wsum_le_wsum
      intro a
      unfold T
      have h := Finset.le_sup'
        (f := fun b : P.Act s who =>
          -P.fCoord x s who (P.pureAction b) v)
        (Finset.mem_univ a)
      linarith

/-- The finite minimum is attained by a pure action. -/
theorem exists_pure_fCoord_eq_T
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)] [∀ s i, Nonempty (P.Act s i)]
    (x : P.X) (v : P.R) (s : P.State) (who : ι) :
    ∃ a : P.Act s who,
      P.fCoord x s who (P.pureAction a) v = P.T x v s who := by
  obtain ⟨a, -, ha⟩ :=
    Finset.exists_mem_eq_sup' Finset.univ_nonempty
      (fun a : P.Act s who =>
        -P.fCoord x s who (P.pureAction a) v)
  refine ⟨a, ?_⟩
  unfold T
  rw [ha]
  ring

/-- **Theorem 1.** For every `x ∈ X`, `T_x` is a contraction of `R`. -/
theorem theorem_1
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)]
    (x : P.X) : ContractingWith P.maxDiscountNNReal (P.T x) := by
  refine ⟨P.maxDiscountNNReal_lt_one,
    LipschitzWith.of_dist_le_mul (fun v u => ?_)⟩
  rw [dist_pi_le_iff (by positivity)]
  intro s
  rw [dist_pi_le_iff (by positivity)]
  intro who
  rw [Real.dist_eq]
  have hcoord :
      |P.T x v s who - P.T x u s who| ≤
        P.discount who * dist v u := by
    unfold T
    have h := Math.Finset.abs_sup'_sub_sup'_le_const
      (indices := (Finset.univ : Finset (P.Act s who)))
      Finset.univ_nonempty
      (fun a => -P.fCoord x s who (P.pureAction a) v)
      (fun a => -P.fCoord x s who (P.pureAction a) u)
      (bound := P.discount who * dist v u)
      (fun a _ => by
        simpa [abs_sub_comm] using
          P.property_b x s who (P.pureAction a) v u)
    simpa [abs_sub_comm] using h
  calc
    |P.T x v s who - P.T x u s who|
        ≤ P.discount who * dist v u := hcoord
    _ ≤ P.maxDiscount * dist v u :=
      mul_le_mul_of_nonneg_right (P.discount_le_maxDiscount who) dist_nonneg
    _ = (P.maxDiscountNNReal : ℝ) * dist v u := rfl

/-- **Corollary 1.** For every `x ∈ X`, `T_x` has a unique fixed point. -/
theorem corollary_1
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)]
    (x : P.X) : ∃! v : P.R, P.T x v = v := by
  have hc := P.theorem_1 x
  exact ⟨ContractingWith.fixedPoint (P.T x) hc,
    hc.fixedPoint_isFixedPt,
    fun v hv => hc.fixedPoint_unique hv⟩

/-- **Corollary 2.** The family `{T_x | x ∈ X}` is equicontinuous.  This is
its metric epsilon-delta form. -/
theorem corollary_2
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)] :
    ∀ ε : ℝ, 0 < ε → ∃ δ : ℝ, 0 < δ ∧
      ∀ (x : P.X) (u v : P.R), dist u v < δ →
        dist (P.T x u) (P.T x v) < ε := by
  intro ε hε
  refine ⟨ε, hε, ?_⟩
  intro x u v huv
  have hL := (P.theorem_1 x).toLipschitzWith.dist_le_mul u v
  have hα0 : 0 ≤ (P.maxDiscountNNReal : ℝ) :=
    P.maxDiscountNNReal.property
  have hα1 : (P.maxDiscountNNReal : ℝ) < 1 := by
    change P.maxDiscount < 1
    exact P.maxDiscount_lt_one
  calc
    dist (P.T x u) (P.T x v)
        ≤ (P.maxDiscountNNReal : ℝ) * dist u v := hL
    _ < (1 : ℝ) * ε := by nlinarith [dist_nonneg]
    _ = ε := one_mul ε

/-- Equation (9): the single-valued optimal value `β(x)`. -/
def beta
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)]
    (x : P.X) : P.R :=
  ContractingWith.fixedPoint (P.T x) (P.theorem_1 x)

@[simp] theorem T_beta
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)] (x : P.X) :
    P.T x (P.beta x) = P.beta x :=
  (P.theorem_1 x).fixedPoint_isFixedPt

/-- Equation (10): Fink's best-response correspondence `φ`. -/
def phi
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)]
    (x : P.X) : Set P.X :=
  {y | P.f x y (P.beta x) = P.beta x}

/-- Every fiber `φ(x)` is nonempty. -/
theorem phi_nonempty
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)] (x : P.X) :
    (P.phi x).Nonempty := by
  have hmin : ∀ p : P.Agent,
      ∃ a : P.AgentAction p,
        P.fCoord x p.1 p.2 (P.pureAction a) (P.beta x) =
          P.T x (P.beta x) p.1 p.2 := by
    intro p
    exact P.exists_pure_fCoord_eq_T x (P.beta x) p.1 p.2
  choose a ha using hmin
  let y : P.X := fun p => P.pureAction (a p)
  refine ⟨y, ?_⟩
  unfold phi
  funext s who
  change P.fCoord x s who (P.pureAction (a (s, who))) (P.beta x) =
    P.beta x s who
  rw [ha (s, who)]
  exact congrFun (congrFun (P.T_beta x) s) who

/-- Convexity of `φ(x)`, stated by closure under simplex segments. -/
theorem phi_segment
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)]
    (x y z : P.X) (hy : y ∈ P.phi x) (hz : z ∈ P.phi x)
    (t : ℝ) (ht0 : 0 ≤ t) (ht1 : t ≤ 1) :
    (fun p => stdSimplex.mix t ht0 ht1 (y p) (z p)) ∈ P.phi x := by
  unfold phi at hy hz ⊢
  funext s who
  have hyc := congrFun (congrFun hy s) who
  have hzc := congrFun (congrFun hz s) who
  change P.fCoord x s who (y (s, who)) (P.beta x) =
    P.beta x s who at hyc
  change P.fCoord x s who (z (s, who)) (P.beta x) =
    P.beta x s who at hzc
  change P.fCoord x s who
      (stdSimplex.mix t ht0 ht1 (y (s, who)) (z (s, who)))
      (P.beta x) = P.beta x s who
  calc
    P.fCoord x s who
        (stdSimplex.mix t ht0 ht1 (y (s, who)) (z (s, who)))
        (P.beta x)
        = wsum (stdSimplex.mix t ht0 ht1
            (y (s, who)) (z (s, who)))
            (fun a => P.fCoord x s who (P.pureAction a) (P.beta x)) :=
          P.property_c x s who _ (P.beta x)
    _ = t * wsum (y (s, who))
          (fun a => P.fCoord x s who (P.pureAction a) (P.beta x)) +
        (1 - t) * wsum (z (s, who))
          (fun a => P.fCoord x s who (P.pureAction a) (P.beta x)) := by
          rw [wsum_mix]
    _ = t * P.fCoord x s who (y (s, who)) (P.beta x) +
        (1 - t) * P.fCoord x s who (z (s, who)) (P.beta x) := by
          rw [← P.property_c, ← P.property_c]
    _ = P.beta x s who := by rw [hyc, hzc]; ring

/-- Closedness of each fiber `φ(x)`. -/
theorem phi_isClosed
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)] (x : P.X) :
    IsClosed (P.phi x) := by
  unfold phi
  have hcont : Continuous (fun y : P.X => P.f x y (P.beta x)) := by
    exact P.property_a_continuous.comp
      (continuous_const.prodMk
        (continuous_id.prodMk continuous_const))
  exact isClosed_eq hcont continuous_const

/-- A uniform finite bound on the cost table. -/
def costBound
    (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)] : ℝ := by
  classical
  exact ∑ s : P.State,
    letI : ∀ i, Fintype (P.Act s i) := fun i => inferInstance
    ∑ a : P.JointActionAt s, ∑ who : ι, |P.cost s a who|

/-- **Lemma 2.** The range of `β` is bounded. -/
theorem lemma_2
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)] :
    ∃ B : ℝ, ∀ (x : P.X) (s : P.State) (who : ι),
      |P.beta x s who| ≤ B := by
  sorry

/-- Fink's notation `S_v(x)=T_x v`. -/
def S
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)] [∀ s i, Nonempty (P.Act s i)]
    (v : P.R) (x : P.X) : P.R :=
  P.T x v

/-- A compact cube containing all continuation vectors with coordinatewise
absolute value at most `B`. -/
def valueCube (P : Game ι) (B : ℝ) : Set P.R :=
  Set.Icc (fun _ _ => -B) (fun _ _ => B)

theorem valueCube_isCompact
    (P : Game ι) [Fintype P.State] [Fintype ι] (B : ℝ) :
    IsCompact (P.valueCube B) :=
  isCompact_Icc

/-- **Lemma 3, first part.** For fixed `v`, `S_v` is continuous on `X`. -/
theorem lemma_3_continuous
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)] [∀ s i, Nonempty (P.Act s i)]
    (v : P.R) : Continuous (P.S v) := by
  sorry

/-- **Lemma 3, second part.** On every bounded value cube, the family
`{S_v}` is equicontinuous.  `TendstoUniformly` is the paper's uniform-in-`v`
formulation. -/
theorem lemma_3_equicontinuous
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)] [∀ s i, Nonempty (P.Act s i)]
    (B : ℝ) (x : P.X) :
    TendstoUniformly
      (fun x' (v : {v : P.R // v ∈ P.valueCube B}) => P.S v.1 x')
      (fun v => P.S v.1 x) (𝓝 x) := by
  sorry

/-- **Lemma 4.** The graph of `β` is sequentially closed. -/
theorem lemma_4
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)]
    {xn : ℕ → P.X} {x : P.X} {v₀ : P.R}
    (hx : Tendsto xn atTop (𝓝 x))
    (hv : Tendsto (fun n => P.beta (xn n)) atTop (𝓝 v₀)) :
    P.beta x = v₀ := by
  sorry

/-- **Lemma 5.** The graph of the best-response correspondence `φ` is
sequentially closed. -/
theorem lemma_5
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)]
    [∀ s i, Nonempty (P.Act s i)]
    {xn yn : ℕ → P.X} {x y : P.X}
    (hx : Tendsto xn atTop (𝓝 x)) (hy : Tendsto yn atTop (𝓝 y))
    (hphi : ∀ n, yn n ∈ P.phi (xn n)) :
    y ∈ P.phi x := by
  sorry

/-! ## Internal contingent-plan adapter for Theorem 2 -/

/-- A state-independent pure action in the production game is a complete
contingent plan, one paper action for every state. -/
abbrev AmbientAct (P : Game ι) (i : ι) := ∀ s, P.Act s i

/-- The reward game used by the reusable production theorem.  It evaluates a
contingent plan only at the current state and negates the paper's cost. -/
def rewardGame (P : Game ι) : StochasticGame ι where
  State := P.State
  Act := P.AmbientAct
  stagePayoff := fun s a who => -P.cost s (fun i => a i s) who
  transition := fun s a => P.transition s (fun i => a i s)
  discount := 0
  discount_nonneg := le_rfl
  discount_lt_one := zero_lt_one

/-- The current-state marginal of a production stationary profile. -/
def effectiveMixedAction
    (P : Game ι) [Fintype ι]
    (x : P.rewardGame.StationaryMixedProfile)
    (s : P.State) (i : ι) : PMF (P.Act s i) :=
  (x s i).map (fun plan => plan s)

/-- The literal paper profile induced by all current-state marginals. -/
def effectiveProfile
    (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.rewardGame.StationaryMixedProfile) : P.X :=
  fun p => stdSimplexEquiv (P.effectiveMixedAction x p.1 p.2)

@[simp] theorem actionPMF_effectiveProfile
    (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)]
    (x : P.rewardGame.StationaryMixedProfile) (s : P.State) (i : ι) :
    P.actionPMF (P.effectiveProfile x) s i = P.effectiveMixedAction x s i := by
  exact (stdSimplexEquiv (α := P.Act s i)).symm_apply_apply _

/-- Extend one local action to a complete contingent plan using fixed actions
at every other state. -/
def extendAction (P : Game ι) (s : P.State) (i : ι)
    (a : P.Act s i) : P.AmbientAct i := by
  classical
  exact fun t =>
    if h : t = s then h.symm ▸ a else Classical.choice (P.act_nonempty t i)

@[simp] theorem extendAction_apply_same
    (P : Game ι) (s : P.State) (i : ι) (a : P.Act s i) :
    P.extendAction s i a s = a := by
  classical
  simp [extendAction]

/-- Lift a local mixed action to a production-game mixed contingent plan. -/
def liftMixedAction
    (P : Game ι) (s : P.State) (i : ι) (y : PMF (P.Act s i)) :
    PMF (P.AmbientAct i) :=
  y.map (P.extendAction s i)

/-- Fink's unnormalized cost value encoded as a normalized reward value. -/
def normalizedRewardValue (P : Game ι) (e : P.R) : P.R :=
  fun s who => -(1 - P.discount who) * e s who

/-- A finite bound on the production reward table.  Since a contingent plan
is evaluated only at the current state, the literal table bound suffices. -/
def rewardBound
    (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)] : ℝ :=
  P.costBound

/-- Marginalization of independent contingent plans commutes with their
product distribution. -/
theorem pmfPi_map_eval
    (P : Game ι) [Fintype P.State] [Fintype ι]
    [∀ s i, Fintype (P.Act s i)]
    (m : ∀ i, PMF (P.AmbientAct i)) (s : P.State) :
    (pmfPi m).map (fun a => fun i => a i s) =
      pmfPi (fun i => (m i).map (fun plan => plan s)) := by
  exact pmfPi_push_coordwise m (fun i plan => plan s)

/-- The production auxiliary payoff is exactly the negative scaled paper
cost expression after taking current-state marginals. -/
theorem reward_discountedAuxEU_eq_fCoord
    (P : Game ι) [Fintype P.State] [Fintype ι] [DecidableEq ι]
    [∀ s i, Fintype (P.Act s i)]
    (m : ∀ i, PMF (P.AmbientAct i)) (e : P.R)
    (s : P.State) (who : ι) :
    P.rewardGame.discountedAuxEU (P.discount who)
        (P.normalizedRewardValue e) s m who =
      -(1 - P.discount who) *
        expect (pmfPi (fun i => (m i).map (fun plan => plan s)))
          (fun a => P.oneStepCost e s a who) := by
  sorry

/-- **Theorem 2.** There are `x ∈ X` and `v ∈ R` such that
`v=f(x,x,v)=min_y f(x,y,v)`, equivalently `x ∈ φ(x)`.  The returned profile
is on the paper's literal state-dependent action sets. -/
theorem theorem_2
    (P : Game ι) [Fintype P.State] [Fintype ι] [Nonempty ι]
    [DecidableEq ι] [∀ s i, Fintype (P.Act s i)] :
    ∃ (x : P.X) (e : P.R), P.IsEquilibriumPoint x e := by
  sorry

/-!
## Closing remarks

Fink observes after Theorem 2 that Lemmas 2 and 4 make `β` continuous, hence
its range is compact and connected.  He then sketches two extensions: to a
denumerable state set with uniformly bounded costs by replacing `R` by the
bounded-sequence space, and to arbitrary action cardinalities by replacing
`min` with `inf`, yielding ε-effective strategies.  The finite paper theorem
above does not silently strengthen those sketches: the closing paragraph does
not state the topology and compactness hypotheses required for a unique
infinite-action Lean theorem.  The comparisons with Shapley's two-player
result and the one-player dynamic-programming case are bibliographic remarks.
-/

end Game

end Literature.Fink1964
