import UniformEquilibrium.Quitting.Classification.Existence.SolanVieilleSequenceExtraction
import UniformEquilibrium.Quitting.Classification.SoloExitPreferenceExistence
import UniformEquilibrium.Quitting.Terminal.TargetTail.TerminalUniformization
import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.SoloExitPreferenceScreen
import UniformEquilibrium.Quitting.Examples.SolanVieilleBoundaryTable
import UniformEquilibrium.Quitting.Examples.BlockPair.FourPlayerPairedSingletonPeriodTwo
import UniformEquilibrium.Quitting.Examples.BlockPair.FourPlayerPairedSingletonPeriodTwoStationary
import UniformEquilibrium.Quitting.Stationary.RegretDichotomy
import MathUE.Topology.CompactSerialRelation

noncomputable section

/-!
# E. Solan and N. Vieille, “Quitting Games” (2001)

Primary locator: [Mathematics of Operations Research 26 (2001), 265--285]
(DOI `10.1287/moor.26.2.265.10549`).  The paper was read in its original
notation.  This file is an ordered paper record, rather than a catalogue of
claims: paper definitions and theorem statements occur in the order in which
they occur in the paper.  The strategy, tail, cyclic-profile, and payoff
process notions needed below are defined locally so that their quantifiers are
not weakened by an available production adapter.

The paper uses a finite player set `N`, a payoff vector `r_S` for every
nonempty quitting coalition `S`, and actions `c^i` and `q^i`.  The game ends at
the first stage at which the quitting coalition is nonempty; if it never ends,
the payoff is zero.  A paper profile is a sequence of mixed action vectors,
conditional on survival to the corresponding stage.
-/

namespace Literature.SolanAndVieille2001

open GameTheory StochasticGame MeasureTheory Filter

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-! ## Paper-local profile vocabulary -/

/- A root sequence is the stage-indexed mixed action profile `x_n`. -/
abbrev PaperRootSequence := ℕ → ι → PMF Bool

/- `paperProfile reward roots = (x₀,x₁,...)`, with `xₙ = roots n`. -/
def paperProfile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : PaperRootSequence (ι := ι)) :
    (quittingGame reward).BehaviorProfile :=
  quittingRootSequenceProfile reward roots 0

/- `paperTailProfile reward roots start = (x_start,x_{start+1},...)`. -/
def paperTailProfile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : PaperRootSequence (ι := ι)) (start : ℕ) :
    (quittingGame reward).BehaviorProfile :=
  quittingRootSequenceProfile reward roots start

/- Cyclicity: `∃ p > 0, ∀ n, roots (n+p) = roots n`. -/
def paperCyclicRootSequence (roots : PaperRootSequence (ι := ι)) : Prop :=
  ∃ period : ℕ, 0 < period ∧ ∀ time, roots (time + period) = roots time

/- A cyclic profile is a profile generated by a cyclic root sequence. -/
def paperCyclicProfile
    (_reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : PaperRootSequence (ι := ι)) : Prop :=
  paperCyclicRootSequence roots

/- A tail terminates when its limiting survival mass is zero. -/
def paperTerminating
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : PaperRootSequence (ι := ι)) (start : ℕ) : Prop :=
  quittingLiveMassLimit reward (paperTailProfile reward roots start) = 0

/-! ## Section 1: The model and the main result -/

/- **Definition 1.1 (paper statement).**  A profile `x` is an
`ε`-equilibrium when, for every player `i` and every strategy `y^i`,
`γ^i(x) ≥ γ^i(x^{-i}, y^i) - ε`.  It is a subgame-perfect `ε`-equilibrium
when every tail `(x_n,x_{n+1},...)` is an `ε`-equilibrium.  The payoff vector
`γ(x)` is an `ε`-equilibrium payoff.

In the current development, the paper's terminal payoff and the first half
of this definition are exactly represented by `IsεAsymptoticNash`; the
subgame-perfect tail quantifier is intentionally not replaced by the weaker
root-level predicate. -/

def paperEpsilonEquilibrium
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (ε : ℝ) (profile : (quittingGame reward).BehaviorProfile) : Prop :=
  (quittingGame reward).IsεAsymptoticNash
    (quittingTerminalPayoff reward) ε profile

/- `payoff` is an `ε`-equilibrium payoff iff some profile realizes it. -/
def paperEpsilonEquilibriumPayoff
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (ε : ℝ) (payoff : Payoff ι) : Prop :=
  ∃ profile, paperEpsilonEquilibrium reward ε profile ∧
    quittingTerminalPayoff reward profile = payoff

/- Every tail of the root sequence is an `ε`-equilibrium. -/
def paperSubgamePerfectEpsilonEquilibrium
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : PaperRootSequence (ι := ι)) (ε : ℝ) : Prop :=
  ∀ start, paperEpsilonEquilibrium reward ε
    (paperTailProfile reward roots start)

/- **Theorem 1.2 (paper statement).**  Every quitting game satisfying

* A.1: `r_{ {i} }^i = 1` for every player `i`; and
* A.2: `r_S^i ≤ 1` for every nonempty `S` containing `i`,

has a cyclic subgame-perfect `ε`-equilibrium (for every `ε > 0`).  “Cyclic”
means that the sequence of mixed action vectors is periodic from its first
stage.  The cyclic and subgame-perfect qualifiers are part of the paper
theorem and are not silently dropped in the checked adapter below. -/

/- The following is the exact paper hypothesis, with the paper's stronger
conclusion recorded above.  It is useful as a checked scope predicate. -/
/- A.1 and A.2: `r_{ {i} }^i = 1` and `r_S^i ≤ 1` when `i ∈ S`. -/
def paperAssumptions
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) : Prop :=
  QuittingUnitSoloExit reward ∧ QuittingCappedJointExit reward

/- Theorem 1.2, as a proposition retaining cyclicity and subgame perfection. -/
def paperTheorem1_2 : Prop :=
  ∀ (reward : {S : Finset ι // S.Nonempty} → Payoff ι),
    paperAssumptions reward → ∀ ε : ℝ, 0 < ε →
      ∃ roots : PaperRootSequence (ι := ι),
        paperCyclicProfile reward roots ∧
          paperSubgamePerfectEpsilonEquilibrium reward roots ε

/- Theorem 1.2: `∀ ε>0, ∃` cyclic subgame-perfect `ε`-equilibrium. -/
theorem theorem1_2 : paperTheorem1_2 (ι := ι) := by
  intro reward hassumptions ε hε
  rcases hassumptions with ⟨hunit, hcap⟩
  cases isEmpty_or_nonempty ι with
  | inl hempty =>
      let roots : PaperRootSequence (ι := ι) := fun _ _ => PMF.pure false
      refine ⟨roots, ⟨1, by norm_num, fun _ => rfl⟩, ?_⟩
      intro _start who
      exact isEmptyElim who
  | inr hnonempty =>
      letI : Nonempty ι := hnonempty
      obtain ⟨roots, period, hperiod, hperiodic, hsubgame⟩ :=
        exists_cyclic_subgamePerfectTerminalNash_of_soloExitPreference
          hunit hcap hε
      exact ⟨roots, ⟨period, hperiod, hperiodic⟩, hsubgame⟩

/-! ## Section 2.1: The one-shot game -/

/- **Definition 2.1 (paper statement).**  For a continuation payoff
`w ∈ ℝ^N`, `G(w)` is the one-shot game in which a nonempty quitting coalition
receives `r_S` and the empty coalition receives `w`.  If `x ∈ [0,1]^N` is a
mixed action profile, `p(x) = 1 - ∏_i x^i` is the termination probability and
`⟨G(w),x⟩` is the corresponding expected payoff.  A profile `x` is a perfect
`ε`-equilibrium of `G(w)` when it is an `ε`-equilibrium and, for every player
`i` and every action `a`,
`|⟨G(w), x^{-i},a⟩ - ⟨G(w),x⟩| ≤ ε`.

The one-shot object is not identified with a whole quitting-game behavior
profile here: doing so would change the paper's continuation-payoff
parameterization. -/

/- `p(root) = 1 - ∏ᵢ root i(continue)`. -/
def paperOneShotTerminationProbability (root : ι → PMF Bool) : ℝ :=
  quittingRootAbsorptionMass root

/- `paperOneShotExpectedPayoff` is `⟨G(w),root⟩`. -/
def paperOneShotExpectedPayoff
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (continuationValue : Payoff ι) (root : ι → PMF Bool) : Payoff ι :=
  quittingRootSuccessorPayoff reward continuationValue root

/- Perfect `ε`-equilibrium: neither endpoint beats the row value by more
than `ε`, and every endpoint used with positive probability is within `ε`
from below.  This is the support-sensitive condition in Definition 2.1. -/
def paperOneShotPerfectEpsilonEquilibrium
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (continuationValue : Payoff ι) (ε : ℝ)
    (root : ι → PMF Bool) : Prop :=
  QuittingRowεPerfect reward continuationValue root ε

/-! ## Section 2.2: the proof -/

/- **Lemma 2.2 (paper statement).**  Let `x=(x_n)` be a profile.  If every
tail `(x_n,x_{n+1},...)` is terminating and every `x_n` is a perfect
`ε`-equilibrium of `G(γ(x_{n+1},x_{n+2},...))`, then either `x` is an
`ε^(1/6)`-equilibrium or there is a stationary `ε^(1/6)`-equilibrium. -/

def paperPerfectRootAt
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : PaperRootSequence (ι := ι)) (ε : ℝ) (start : ℕ) : Prop :=
  paperOneShotPerfectEpsilonEquilibrium reward
    (quittingTerminalPayoff reward (paperTailProfile reward roots (start + 1)))
    ε (roots start)

/- The stationary profile generated by the fixed root `root`. -/
def paperStationaryProfile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) : (quittingGame reward).BehaviorProfile :=
  paperProfile reward (fun _ => root)

/- Quantitative checked form of Lemma 2.2.  The paper writes the row
error and output error as powers of one small parameter.  The formal theorem
records the invariant content: every positive output tolerance admits a
positive row tolerance.  Proposition 2.4 supplies the uniform absorption
floor used here. -/
def paperLemma2_2 : Prop :=
  ∀ (reward : {S : Finset ι // S.Nonempty} → Payoff ι),
    QuittingUnitSoloExit reward → ∀ εout : ℝ, 0 < εout →
      ∃ εrow : ℝ, 0 < εrow ∧
        ∀ (roots : PaperRootSequence (ι := ι)) (δ : ℝ), 0 < δ →
          (∀ start, δ ≤ paperOneShotTerminationProbability (roots start)) →
          (∀ start, paperPerfectRootAt reward roots εrow start) →
            (∀ start, paperEpsilonEquilibrium reward εout
              (paperTailProfile reward roots start)) ∨
            ∃ root, paperEpsilonEquilibrium reward εout
              (paperStationaryProfile reward root)

/- Lemma 2.2: calibrated perfect rows give the sequence-or-stationary
dichotomy, uniformly after every restart. -/
theorem lemma2_2 : paperLemma2_2 (ι := ι) := by
  intro reward hunit εout hεout
  obtain ⟨εrow, hεrow, hdichotomy⟩ :=
    quittingPerfectSequenceSubgameDichotomy_of_soloExitPreference
      hunit εout hεout
  refine ⟨εrow, hεrow, ?_⟩
  intro roots δ hδ hfloor hperfect
  simpa [paperOneShotTerminationProbability, paperPerfectRootAt,
    paperOneShotPerfectEpsilonEquilibrium, paperEpsilonEquilibrium,
    paperTailProfile, paperStationaryProfile, paperProfile,
    quittingStationaryProfile, StochasticGame.stationaryBehaviorProfile] using
      hdichotomy roots δ hδ hfloor hperfect

/- **Lemma 2.3 (paper statement).**  Let `K` be compact and let
`ψ : K → K` be upper-semicontinuous with nonempty values.  There is a
sequence `k_1,k_2,...` in `K` such that `k_i ∈ ψ(k_{i+1})` for every `i`.
The paper applies this to the correspondence of perfect one-shot
equilibria whose termination probability is at least `ε`. -/

/- Closed graph of the correspondence on `K`.  For compact-valued
correspondences into a Hausdorff compact set this is the form of upper
semicontinuity consumed by the inverse-limit argument. -/
def paperUpperSemicontinuous {α : Type*} [TopologicalSpace α]
    (K : Set α) (ψ : α → Set α) : Prop :=
  IsClosed {pair : α × α |
    pair.1 ∈ K ∧ pair.2 ∈ K ∧ pair.1 ∈ ψ pair.2}

/- Lemma 2.3: a nonempty compact predecessor-serial closed relation admits a
backward chain.  Requiring predecessors to lie in `K` is the codomain clause
of the paper's notation `ψ : K → K`. -/
def paperLemma2_3Claim : Prop :=
  ∀ (α : Type*) [TopologicalSpace α] [T2Space α]
    (K : Set α), K.Nonempty → IsCompact K →
    ∀ ψ : α → Set α,
      (∀ tail ∈ K, ∃ current, current ∈ K ∧ current ∈ ψ tail) →
      paperUpperSemicontinuous K ψ →
        ∃ sequence : ℕ → α,
          (∀ i, sequence i ∈ K) ∧
            ∀ i, sequence i ∈ ψ (sequence (i + 1))

/- Lemma 2.3: compact serial relations admit an infinite backward chain. -/
theorem lemma2_3 : paperLemma2_3Claim := by
  intro α _ _ K hnonempty hcompact ψ hserial hclosed
  let system : Math.Topology.CompactSerialRelation α :=
    { box := K
      relation := fun current tail => current ∈ ψ tail
      box_nonempty := hnonempty
      box_compact := hcompact
      relationGraph_closed := hclosed
      predecessor_exists := hserial }
  simpa [system] using system.exists_infiniteChain

/- **Proposition 2.4 (paper statement).**  If there is a compact set `W` of
continuation payoffs for which that correspondence has nonempty values, then
the quitting game has an `(ρε)^(1/6)`-equilibrium, where `ρ` is twice the
largest absolute terminal payoff and `ε` is the termination-probability
cutoff.  The constructed profile is in fact subgame-perfect; the stationary
alternative in Lemma 2.2 is also retained in the statement. -/

/- Successor values in `W` generated by perfect roots with absorption at
least `δ`.  The correspondence is value-valued: the current value is the
successor payoff obtained from the supplied continuation value. -/
def paperOneShotCorrespondence
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (W : Set (Payoff ι)) (εrow δ : ℝ)
    (continuation : Payoff ι) : Set (Payoff ι) :=
  {current | current ∈ W ∧ ∃ root : ι → PMF Bool,
      paperOneShotPerfectEpsilonEquilibrium reward continuation εrow root ∧
      δ ≤ quittingRootAbsorptionMass root ∧
      quittingRootSuccessorPayoff reward continuation root = current}

/- Checked compact-correspondence form of Proposition 2.4.  The source's
power-law parameter choice is represented by the positive calibration
`εrow` returned for a requested output error `εout`. -/
def paperProposition2_4Claim : Prop :=
  ∀ (reward : {S : Finset ι // S.Nonempty} → Payoff ι),
    QuittingUnitSoloExit reward → ∀ εout : ℝ, 0 < εout →
      ∃ εrow : ℝ, 0 < εrow ∧
        ∀ (W : Set (Payoff ι)) (δ R : ℝ),
          W.Nonempty → IsCompact W → 0 < δ → δ ≤ 1 → 0 ≤ R →
          (∀ S who, |reward S who| ≤ R) →
          (∀ value ∈ W, ∀ who, |value who| ≤ R) →
          paperUpperSemicontinuous W
            (paperOneShotCorrespondence reward W εrow δ) →
          (∀ continuation ∈ W,
            (paperOneShotCorrespondence reward W εrow δ continuation).Nonempty) →
            ∃ roots : PaperRootSequence (ι := ι),
              paperSubgamePerfectEpsilonEquilibrium reward roots εout

/- Proposition 2.4: compact serial successor values compile to a
subgame-perfect approximate equilibrium (or the stationary repair, encoded
as a period-one root sequence). -/
theorem proposition2_4 : paperProposition2_4Claim (ι := ι) := by
  intro reward hunit εout hεout
  obtain ⟨εrow, hεrow, hdichotomy⟩ :=
    quittingPerfectSequenceSubgameDichotomy_of_soloExitPreference
      hunit εout hεout
  refine ⟨εrow, hεrow, ?_⟩
  intro W δ R hWnonempty hWcompact hδ hδone hR hrewards hWbound
    hclosed hserial
  obtain ⟨plan, hplanW, hplanRelation⟩ :=
    (lemma2_3 (α := Payoff ι)) W hWnonempty hWcompact
      (paperOneShotCorrespondence reward W εrow δ) hserial hclosed
  have hrootExists : ∀ n, ∃ root : ι → PMF Bool,
      QuittingRowεPerfect reward (plan (n + 1)) root εrow ∧
      δ ≤ quittingRootAbsorptionMass root ∧
      quittingRootSuccessorPayoff reward (plan (n + 1)) root = plan n := by
    intro n
    have hrel : plan n ∈ W ∧ ∃ root : ι → PMF Bool,
        QuittingRowεPerfect reward (plan (n + 1)) root εrow ∧
        δ ≤ quittingRootAbsorptionMass root ∧
        quittingRootSuccessorPayoff reward (plan (n + 1)) root = plan n := by
      simpa [paperOneShotCorrespondence,
        paperOneShotPerfectEpsilonEquilibrium] using hplanRelation n
    exact hrel.2
  choose roots hperfect hfloor hsuccessor using hrootExists
  have hcontinue : ∀ n,
      quittingStationaryContinueMass (roots n) ≤ 1 - δ := by
    intro n
    have h := hfloor n
    unfold quittingRootAbsorptionMass at h
    linarith
  have hclose : ∀ n who,
      |plan n who -
        quittingRootSuccessorPayoff reward (plan (n + 1)) (roots n) who| ≤ 0 := by
    intro n who
    rw [hsuccessor n]
    simp
  have happrox :=
    abs_terminalValue_sub_successor_le_of_approximate_chain
      reward roots plan hR hδ hδone (by norm_num) hrewards
      (fun n who => hWbound (plan n) (hplanW n) who)
      hcontinue hclose
  have hactual : ∀ n,
      quittingRootSequenceTailVector reward roots n = plan n := by
    intro n
    funext who
    have hzero :
        |quittingRootSequenceTerminalValue reward roots who n -
          quittingRootSuccessorPayoff reward (plan (n + 1)) (roots n) who| = 0 :=
      le_antisymm (happrox n who) (abs_nonneg _)
    calc
      quittingRootSequenceTailVector reward roots n who =
          quittingRootSuccessorPayoff reward (plan (n + 1)) (roots n) who := by
            exact sub_eq_zero.mp (abs_eq_zero.mp hzero)
      _ = plan n who := congrFun (hsuccessor n) who
  have hperfectActual : ∀ n, QuittingRowεPerfect reward
      (quittingRootSequenceTailVector reward roots (n + 1)) (roots n) εrow := by
    intro n
    rw [hactual (n + 1)]
    exact hperfect n
  rcases hdichotomy roots δ hδ hfloor hperfectActual with hsequence | hstationary
  · exact ⟨roots, hsequence⟩
  · obtain ⟨root, hroot⟩ := hstationary
    refine ⟨fun _ => root, fun start => ?_⟩
    simpa [paperEpsilonEquilibrium, paperTailProfile,
      quittingRootSequenceProfile, quittingStationaryProfile,
      StochasticGame.stationaryBehaviorProfile] using hroot

/- **Lemma 2.5 (paper statement).**  Under A.1 and A.2, define
`W = {w ∈ [-ρ,ρ]^N | w^i ≤ 1 for some i}`.  If `u ∈ W` and `x` is an
equilibrium of `G(u)` with `x ≠ (1,...,1)`, then some player `i` has
`x^i < 1` and `⟨G(u),x⟩^i ≤ 1`.  Consequently the perfect-equilibrium
correspondence used in Proposition 2.4 has nonempty values on `W`. -/

def paperW (ρ : ℝ) : Set (Payoff ι) :=
  {value | (∀ who, |value who| ≤ ρ) ∧ ∃ who, value who ≤ 1}

/- Lemma 2.5's payoff-set/root conclusion under A.1 and A.2. -/
def paperLemma2_5 : Prop :=
  ∀ (reward : {S : Finset ι // S.Nonempty} → Payoff ι),
    paperAssumptions reward → ∀ ρ : ℝ, ∀ value ∈ paperW (ι := ι) ρ,
    ∀ root, IsεQuittingRootNash reward value 0 root →
      root ≠ quittingAllContinueRoot →
        ∃ who, root who ≠ PMF.pure false ∧
          quittingRootExpectedPayoff reward value root who ≤ 1

/- Lemma 2.5: a non-all-continue root has a player payoff at most `1`. -/
theorem lemma2_5 : paperLemma2_5 (ι := ι) := by
  intro reward hassumptions ρ value _hvalue root hnash hnotAllContinue
  rcases hassumptions with ⟨_hunit, hcap⟩
  have hexists : ∃ who, root who ≠ PMF.pure false := by
    by_contra hnone
    push Not at hnone
    apply hnotAllContinue
    funext who
    simpa [quittingAllContinueRoot] using hnone who
  obtain ⟨who, hwho⟩ := hexists
  have hquit : root who true ≠ 0 := by
    intro hzero
    apply hwho
    apply Math.ProbabilityMassFunction.eq_pure_false_of_apply_true_toReal_eq_zero
    simpa [hzero]
  have hendpoint : IsεQuittingRootEndpointNash reward value 0 root :=
    (isZeroQuittingRootEndpointNash_iff_isZeroQuittingRootNash
      reward value root).2 hnash
  refine ⟨who, hwho, ?_⟩
  rw [quittingRootSuccessorPayoff_eq_quitPayoff_of_isZeroEndpointNash
    hendpoint who hquit]
  exact quittingRootQuitPayoff_le_one_of_cappedJointExit
    hcap value root who

/- **Lemma 2.6 (paper statement).**  This is the detailed main-lemma
estimate.  For the block decomposition generated by the condition that the
conditional probability of termination in each block is at least
`ε^a` (with the paper's fixed `a,b` and small-`ε` inequalities), either a
player has two type-I blocks separated by more than `1/ε`, yielding an
`ε^(1/6)`-equilibrium payoff and a stationary `ε^(1/6)`-equilibrium, or the
profile is an `ε^(1/6)`-equilibrium.  The paper's Claims 1 and 2 bound,
respectively, the accumulated deviation payoff and the probability of
reaching late blocks.  These estimates depend on the paper's conditional
block notation and are not encoded as a weaker root-level theorem. -/

/- The paper's detailed Lemma 2.6 is the block proof of Lemma 2.2. -/
def paperLemma2_6 : Prop := paperLemma2_2 (ι := ι)

/- Lemma 2.6: the detailed block estimate used by the main lemma. -/
theorem lemma2_6 : paperLemma2_6 (ι := ι) := by
  exact lemma2_2

/- **Lemma 2.7 (paper statement).**  For independent Bernoulli sequences
`(X_n)` and `(Y_n)`, with first-success times `S_1,S_2` and
`T=min(S_1,S_2)`, if `P(T≤N)>0`, then
`P(S_1≤N)-P(T≤N) ≤ P(S_1≤N)P(S_2≤N)` and
`|P(S_1=n|S_1≤N)-P(S_1=n|T≤N)| ≤ 2P(S_2≤N)`.
This is the probability estimate used in the proof of Lemma 2.6. -/

/- The event that the first-success time equals `n`. -/
def paperFirstSuccessEvent {Ω : Type*}
  (first : Ω → ℕ) (n : ℕ) : Set Ω := {ω | first ω = n}

/- `{first ≤ N}`. -/
def paperAtMostEvent {Ω : Type*}
    (first : Ω → ℕ) (N : ℕ) : Set Ω := {ω | first ω ≤ N}

/- `P(first=n | first≤N)`, represented by its probability ratio. -/
def paperConditionalFirstSuccess {Ω : Type*}
    (probability : Set Ω → ℝ) (first : Ω → ℕ) (n N : ℕ) : ℝ :=
  probability (paperFirstSuccessEvent first n) /
    probability (paperAtMostEvent first N)

/- Lemma 2.7's first-success estimate for two independent clocks. -/
def paperLemma2_7 : Prop :=
  ∀ (Ω : Type*) (probability : Set Ω → ℝ)
    (first₁ first₂ : Ω → ℕ) (N : ℕ),
    (∀ n m, probability (paperAtMostEvent first₁ n ∩
        paperAtMostEvent first₂ m) =
      probability (paperAtMostEvent first₁ n) *
        probability (paperAtMostEvent first₂ m)) →
    probability (paperAtMostEvent (fun ω => min (first₁ ω) (first₂ ω)) N) > 0 →
      probability (paperAtMostEvent first₁ N) -
          probability (paperAtMostEvent
            (fun ω => min (first₁ ω) (first₂ ω)) N) ≤
        probability (paperAtMostEvent first₁ N) *
          probability (paperAtMostEvent first₂ N) ∧
      ∀ n, |paperConditionalFirstSuccess probability first₁ n N -
          probability (paperFirstSuccessEvent first₁ n) /
            probability (paperAtMostEvent
              (fun ω => min (first₁ ω) (first₂ ω)) N)| ≤
        2 * probability (paperAtMostEvent first₂ N)

/- Lemma 2.7: the two first-success probability inequalities. -/
theorem lemma2_7 : paperLemma2_7 := by
  sorry

/-! ## Proposition 2.13: terminal equilibrium implies uniform equilibrium -/

/- **Proposition 2.13 (paper statement).**  If `x` is an `ε`-equilibrium
for the terminal payoff, then, for every `ε' > ε`, `x` is a uniform
`ε'`-equilibrium: in every sufficiently long finite-horizon average game,
no unilateral deviation gains more than `ε'`.  This is a profile-level
statement; it does not assert that a fixed profile is an equilibrium payoff
for all accuracies. -/

/- Proposition 2.13: terminal `ε`-Nash implies uniform `ε'`-Nash for `ε<ε'`. -/
theorem terminalNash_isUniformEquilibrium
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    {ε ε' : ℝ} (herror : ε < ε')
    (hnash : paperEpsilonEquilibrium reward ε profile) :
    (quittingGame reward).IsUniformεEquilibrium none ε' profile :=
  quittingGame_isUniformεEquilibrium_of_terminalNash
    reward profile herror hnash

/-! ## Theorem 1.2: checked weaker adapter -/

/- The next proposition deliberately omits the paper's cyclic and
subgame-perfect conclusion.  It is the currently checked equilibrium-
existence half, not a formalization of Theorem 1.2 itself. -/
/- The weaker checked conclusion: uniform `ε`-equilibrium existence. -/
def UniformεEquilibriumUnderSoloExitAssumptionsClaim : Prop :=
  QuittingCappedJointExitUniformεExistence ι

/- Checked adapter: existence under the weaker production assumptions. -/
/- The checked production adapter proves the weaker existence proposition. -/
theorem uniformεEquilibriumUnderSoloExitAssumptionsClaim_holds :
    UniformεEquilibriumUnderSoloExitAssumptionsClaim (ι := ι) :=
  quittingCappedJointExitUniformεExistence_holds

/- Existence adapter: the weaker checked claim supplies a uniform payoff. -/
theorem exists_uniformEquilibriumPayoff_of_claim
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (hunit : QuittingUnitSoloExit reward)
    (hcapped : QuittingCappedJointExit reward) :
    ∃ payoff : Payoff ι,
      (quittingGame reward).IsUniformEquilibriumPayoff none payoff :=
  exists_uniformEquilibriumPayoff_of_soloExitPreference hunit hcapped

/-! ## Section 2.4: general payoff processes -/

/- **Theorem 2.8 (paper statement).**  Let `(r_n)` be a bounded random
payoff process converging almost surely to `r_∞`, and assume the paper
versions of A.1 and A.2 hold almost surely.  If `ρ = ess sup_{n≥1} ||r_n||`
is finite, then for every `ε>0` the resulting quitting game has an
`ε`-equilibrium.  The paper constructs the profile by choosing a sufficiently
late finite block and applying backward induction.  The local process below
supplies the paper's random-payoff and conditional-expectation interface. -/

/- Paper data: bounded `r_n(ω) → r_∞(ω)` a.s., with an adapted profile
and its conditional expected-payoff evaluator. -/
structure PaperPayoffProcess (ι : Type) [Fintype ι] [DecidableEq ι] where
  Ω : Type
  measurableSpace : MeasurableSpace Ω
  μ : @Measure Ω measurableSpace
  payoff : ℕ → Ω → ({S : Finset ι // S.Nonempty} → Payoff ι)
  limit : Ω → ({S : Finset ι // S.Nonempty} → Payoff ι)
  bounded : ∃ M, ∀ n ω S who, |payoff n ω S who| ≤ M
  converges : ∀ᵐ ω ∂μ, ∀ S who,
    Tendsto (fun n => payoff n ω S who) atTop (nhds (limit ω S who))
  adapted : (ℕ → ι → Ω → PMF Bool) → Prop
  expectedPayoff : (ℕ → ι → Ω → PMF Bool) → Payoff ι

/- A behavioral profile for a `PaperPayoffProcess`. -/
abbrev PaperProcessProfile (process : PaperPayoffProcess ι) :=
  ℕ → ι → process.Ω → PMF Bool

/- Almost surely, A.1 holds for singleton exits and A.2 for every coalition. -/
def paperProcessAssumptions (process : PaperPayoffProcess ι) : Prop :=
    ∀ᵐ ω ∂process.μ, ∀ n i,
      process.payoff n ω (quittingSingletonTerminal i) i = 1 ∧
        process.limit ω (quittingSingletonTerminal i) i = 1 ∧
        ∀ S, i ∈ S.1 →
          process.payoff n ω S i ≤ 1 ∧ process.limit ω S i ≤ 1

/- The paper process evaluator admits no unilateral gain greater than `ε`. -/
def paperProcessEpsilonEquilibrium
    (process : PaperPayoffProcess ι)
    (profile : PaperProcessProfile process) (ε : ℝ) : Prop :=
  ∀ who (deviation : ℕ → process.Ω → PMF Bool),
    process.expectedPayoff profile who + ε ≥
      process.expectedPayoff
        (fun time => Function.update (profile time) who (deviation time)) who

/- Existence of an adapted `ε`-equilibrium for every `ε>0`. -/
def paperTheorem2_8 : Prop :=
  ∀ (process : PaperPayoffProcess ι), paperProcessAssumptions process →
    ∀ ε : ℝ, 0 < ε → ∃ profile : PaperProcessProfile process,
      process.adapted profile ∧
        paperProcessEpsilonEquilibrium process profile ε

/- Theorem 2.8 for the paper-local process/evaluator structure. -/
theorem theorem2_8 : paperTheorem2_8 (ι := ι) := by
  sorry

/-! ## Section 3: the four-player example -/

/- The paper's Figure 2 gives the complete four-player terminal table and
the symmetry identities
`r^1(a,b,c,d)=r^2(b,a,d,c)`,
`r^1(a,b,c,d)=r^4(c,d,b,a)`, and
`r^2(a,b,c,d)=r^3(c,d,b,a)`.
It defines a period-two cyclic profile: at odd stages players 2 and 4 continue
with probability one while players 1 and 3 continue with probability `1/√2`;
at even stages the roles are reversed.  Its two phase payoffs are
`(√2,1,√2,1)` and `(1,√2,1,√2)` in the paper's displayed ordering.
The paper proves that no stationary equilibrium exists, and that no
stationary `ε`-equilibrium exists for sufficiently small `ε`; the latter
argument is the paper's Section 3.3 “No perturbed ε-equilibrium” proof. -/

/- The exact even/odd mixed roots shown in Figure 2. -/
def paperFigure2PhaseRootCondition
    (roots : PaperRootSequence (ι := Fin 4)) : Prop :=
  ∀ time, (time % 2 = 0 →
    roots time 1 = PMF.pure false ∧ roots time 3 = PMF.pure false ∧
      (roots time 0 false).toReal = (Real.sqrt 2)⁻¹ ∧
      (roots time 2 false).toReal = (Real.sqrt 2)⁻¹) ∧
    (time % 2 = 1 →
      roots time 0 = PMF.pure false ∧ roots time 2 = PMF.pure false ∧
        (roots time 1 false).toReal = (Real.sqrt 2)⁻¹ ∧
        (roots time 3 false).toReal = (Real.sqrt 2)⁻¹)

/- Figure 2's period-two root pattern. -/
def paperFigure2CyclicProfileClaim : Prop :=
  ∃ roots : PaperRootSequence (ι := Fin 4),
    paperCyclicRootSequence roots ∧ paperFigure2PhaseRootCondition roots

/- The Figure 2 cyclic profile is an `ε`-equilibrium for every `ε>0`. -/
def paperFigure2CyclicEquilibriumClaim : Prop :=
  ∀ ε : ℝ, 0 < ε → ∃ roots : PaperRootSequence (ι := Fin 4),
    paperCyclicRootSequence roots ∧ paperFigure2PhaseRootCondition roots ∧
      paperEpsilonEquilibrium
        SolanVieilleBoundary.boundaryReward ε
        (paperProfile SolanVieilleBoundary.boundaryReward roots)

/- Figure 2 has no stationary equilibrium. -/
/- No stationary root profile is an equilibrium in the Figure 2 game. -/
def paperFigure2NoStationaryEquilibriumClaim : Prop :=
  ¬ ∃ root : Fin 4 → PMF Bool,
    paperEpsilonEquilibrium
      SolanVieilleBoundary.boundaryReward 0
      (paperStationaryProfile SolanVieilleBoundary.boundaryReward root)

/- No sufficiently small equilibrium can keep every quitting probability small. -/
def paperFigure2NoPerturbedEpsilonClaim : Prop :=
  ∃ ε₀ : ℝ, 0 < ε₀ ∧ ∀ ε, 0 < ε → ε < ε₀ →
    ¬ ∃ root : Fin 4 → PMF Bool,
      (∀ player, (root player true).toReal ≤ ε) ∧
      paperEpsilonEquilibrium SolanVieilleBoundary.boundaryReward ε
        (paperStationaryProfile SolanVieilleBoundary.boundaryReward root)

/- Figure 2: the displayed root sequence is period two. -/
theorem figure2_cyclic_profile : paperFigure2CyclicProfileClaim := by
  sorry

/- Figure 2: the period-two profile is an `ε`-equilibrium for each `ε>0`. -/
theorem figure2_cyclic_equilibrium : paperFigure2CyclicEquilibriumClaim := by
  sorry

/- Figure 2: no stationary equilibrium exists. -/
theorem figure2_no_stationary_equilibrium :
    paperFigure2NoStationaryEquilibriumClaim := by
  sorry

/- Figure 2: sufficiently small perturbed `ε`-equilibria do not exist. -/
theorem figure2_no_perturbed_epsilon : paperFigure2NoPerturbedEpsilonClaim := by
  sorry

/- The supplied Figure 2 reward table satisfies A.1 and A.2. -/
theorem boundaryReward_paper_assumptions :
    QuittingUnitSoloExit SolanVieilleBoundary.boundaryReward ∧
      QuittingCappedJointExit SolanVieilleBoundary.boundaryReward :=
  ⟨SolanVieilleBoundary.boundaryReward_unitSoloExit,
    SolanVieilleBoundary.boundaryReward_cappedJointExit⟩

end Literature.SolanAndVieille2001
