import MathUE.Topology.CompactSerialRelation
import UniformEquilibrium.Quitting.Classification.Existence.PerfectSequenceExtraction
import UniformEquilibrium.Quitting.Classification.SoloExitPreferenceExistence
import UniformEquilibrium.Quitting.Examples.SolanVieilleBoundaryTable
import UniformEquilibrium.Quitting.Terminal.TargetTail.TerminalUniformization

noncomputable section

/-!
# E. Solan and N. Vieille, “Quitting Games” (2001)

Eilon Solan and Nicolas Vieille, “Quitting Games,” *Mathematics of
Operations Research* **26**(2), 265--285 (2001), DOI
`10.1287/moor.26.2.265.10549`.

This file follows the published journal paper in order and terminology. The
paper uses a finite player set `N`, terminal payoff vectors `r_S` for every
nonempty quitting coalition `S`, and actions `c^i` and `q^i`. A profile is a
time-indexed sequence of mixed action vectors conditional on survival. The
game pays zero if nobody ever quits.

Unproved source claims remain `sorry`. Checked production reformulations are
kept separate from the exact source statements and never replace them.
-/

namespace Literature.SolanAndVieille2001

open GameTheory StochasticGame MeasureTheory Filter Set

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-! ## 1. The model and the main results -/

/-- The paper's profile `x = (x_n)`: a mixed action vector after every
surviving stage. `false` is Continue and `true` is Quit. -/
abbrev RootSequence := ℕ → ι → PMF Bool

/-- The behavior profile generated by a paper root sequence. -/
def profile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : RootSequence (ι := ι)) :
    (quittingGame reward).BehaviorProfile :=
  quittingRootSequenceProfile reward roots 0

/-- The paper's tail `x_n = (x_n,x_{n+1},...)`. -/
def tailProfile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : RootSequence (ι := ι)) (start : ℕ) :
    (quittingGame reward).BehaviorProfile :=
  quittingRootSequenceProfile reward roots start

/-- A profile terminates when absorption occurs almost surely. -/
def terminating
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : RootSequence (ι := ι)) (start : ℕ) : Prop :=
  quittingLiveMassLimit reward (tailProfile reward roots start) = 0

/-- Cyclicity in the paper: the mixed action vectors are periodic from the
first stage. -/
def cyclicRootSequence (roots : RootSequence (ι := ι)) : Prop :=
  ∃ period : ℕ, 0 < period ∧ ∀ time, roots (time + period) = roots time

/-- A stationary root sequence. -/
def stationaryRootSequence
    (roots : RootSequence (ι := ι)) : Prop :=
  ∀ time, roots time = roots 0

/-- The stationary profile generated by one mixed action vector. -/
def stationaryProfile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) : (quittingGame reward).BehaviorProfile :=
  quittingStationaryProfile reward root

/-- A root is pure when every player uses a pure action. -/
def pureRoot (root : ι → PMF Bool) : Prop :=
  ∀ who, root who = PMF.pure false ∨ root who = PMF.pure true

/-- **Definition 1.1.** A profile is an `ε`-equilibrium when no unilateral
strategy gains more than `ε` in the terminal-payoff game. -/
def epsilonEquilibrium
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (ε : ℝ) (profile : (quittingGame reward).BehaviorProfile) : Prop :=
  (quittingGame reward).IsεAsymptoticNash
    (quittingTerminalPayoff reward) ε profile

/-- **Definition 1.1.** An `ε`-equilibrium payoff is realized by an
`ε`-equilibrium profile. -/
def epsilonEquilibriumPayoff
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (ε : ℝ) (payoff : Payoff ι) : Prop :=
  ∃ profile, epsilonEquilibrium reward ε profile ∧
    quittingTerminalPayoff reward profile = payoff

/-- **Definition 1.1.** Subgame perfection requires every surviving tail to
be an `ε`-equilibrium. -/
def subgamePerfectEpsilonEquilibrium
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : RootSequence (ι := ι)) (ε : ℝ) : Prop :=
  ∀ start, epsilonEquilibrium reward ε
    (tailProfile reward roots start)

/-- Assumptions A.1 and A.2 of Theorem 1.2. -/
def assumptions
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) : Prop :=
  QuittingUnitSoloExit reward ∧ QuittingCappedJointExit reward

/-- **Theorem 1.2.** Every quitting game satisfying A.1 and A.2 has a cyclic
subgame-perfect `ε`-equilibrium for every `ε > 0`. -/
def Theorem1_2 : Prop :=
  ∀ (reward : {S : Finset ι // S.Nonempty} → Payoff ι),
    assumptions reward → ∀ ε : ℝ, 0 < ε →
      ∃ roots : RootSequence (ι := ι),
        cyclicRootSequence roots ∧
          subgamePerfectEpsilonEquilibrium reward roots ε

/-- Theorem 1.2, checked against the exact cyclic and every-tail conclusion. -/
theorem theorem1_2 : Theorem1_2 (ι := ι) := by
  intro reward hassumptions ε hε
  rcases hassumptions with ⟨hunit, hcap⟩
  cases isEmpty_or_nonempty ι with
  | inl _ =>
      let roots : RootSequence (ι := ι) := fun _ _ => PMF.pure false
      refine ⟨roots, ⟨1, by norm_num, fun _ => rfl⟩, ?_⟩
      intro _start who
      exact isEmptyElim who
  | inr hnonempty =>
      letI : Nonempty ι := hnonempty
      obtain ⟨roots, period, hperiod, hperiodic, hsubgame⟩ :=
        exists_cyclic_subgamePerfectTerminalNash_of_soloExitPreference
          hunit hcap hε
      exact ⟨roots, ⟨period, hperiod, hperiodic⟩, hsubgame⟩

/-- A symmetric quitting table depends only on coalition size and on whether
the observed player belongs to the quitting coalition. -/
def symmetricReward
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) : Prop :=
  ∃ quitterPayoff nonquitterPayoff : ℕ → ℝ,
    ∀ terminal who,
      reward terminal who =
        if who ∈ terminal.1 then quitterPayoff terminal.1.card
        else nonquitterPayoff terminal.1.card

/-- **Theorem 1.3.** Every symmetric quitting game has a pure stationary
zero-equilibrium. -/
def Theorem1_3 : Prop :=
  ∀ (reward : {S : Finset ι // S.Nonempty} → Payoff ι),
    symmetricReward reward →
      ∃ root : ι → PMF Bool, pureRoot root ∧
        epsilonEquilibrium reward 0 (stationaryProfile reward root)

theorem theorem1_3 : Theorem1_3 (ι := ι) := by
  sorry

/-! ### Example 1: a symmetric game without symmetric approximate equilibria -/

/-- The two-player symmetric terminal table in Example 1: a sole quitter
gets `1`, the other player gets `2`, and simultaneous quitters get `1`. -/
def example1Reward
    (terminal : {S : Finset (Fin 2) // S.Nonempty}) : Payoff (Fin 2) :=
  fun who => if who ∈ terminal.1 then 1 else 2

/-- A symmetric profile uses the same mixed action for both players at every
stage. -/
def symmetricRootSequence
    (roots : RootSequence (ι := Fin 2)) : Prop :=
  ∀ time first second, roots time first = roots time second

/-- **Example 1.** If `ε + 2√ε < 1/2`, the displayed symmetric game has no
symmetric `ε`-equilibrium. -/
def Example1Claim : Prop :=
  ∀ ε : ℝ, 0 ≤ ε → ε + 2 * Real.sqrt ε < 1 / 2 →
    ¬ ∃ roots : RootSequence (ι := Fin 2),
      symmetricRootSequence roots ∧
        epsilonEquilibrium example1Reward ε
          (profile example1Reward roots)

theorem example1 : Example1Claim := by
  sorry

/-! ## 2. Existence result -/

/-! ### 2.1. The one-shot game -/

/-- The one-shot absorption probability `p(x)`. -/
def oneShotTerminationProbability (root : ι → PMF Bool) : ℝ :=
  quittingRootAbsorptionMass root

/-- The one-shot payoff `⟨G(w),x⟩`. -/
def oneShotExpectedPayoff
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (continuationValue : Payoff ι) (root : ι → PMF Bool) : Payoff ι :=
  quittingRootSuccessorPayoff reward continuationValue root

/-- **Definition 2.1.** A one-shot root is a perfect `ε`-equilibrium when
every action in each player's support is within `ε` of every pure reply. -/
def oneShotPerfectEpsilonEquilibrium
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (continuationValue : Payoff ι) (ε : ℝ)
    (root : ι → PMF Bool) : Prop :=
  ∀ who action, root who action ≠ 0 → ∀ alternative,
    quittingRootExpectedPayoff reward continuationValue
        (Function.update root who (PMF.pure alternative)) who ≤
      quittingRootExpectedPayoff reward continuationValue
          (Function.update root who (PMF.pure action)) who + ε

/-! ### 2.2. The three propositions implying Theorem 1.2 -/

/-- Twice the maximal absolute terminal payoff, the paper's `ρ`. -/
def rho
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) : ℝ :=
  2 * quittingRewardBound reward

/-- The paper's special continuation set
`W = {w ∈ [-ρ,ρ]^N | w^i ≤ 1 for some i}`. -/
def W
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :
    Set (Payoff ι) :=
  {value | (∀ who, |value who| ≤ rho reward) ∧
    ∃ who, value who ≤ 1}

/-- The value-valued correspondence `ψ`: perfect `ρε` roots with absorption
at least `ε`, whose produced value remains in `W`. -/
def oneShotCorrespondence
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (W : Set (Payoff ι)) (ε : ℝ) (continuation : Payoff ι) :
    Set (Payoff ι) :=
  {current | current ∈ W ∧ ∃ root : ι → PMF Bool,
    oneShotPerfectEpsilonEquilibrium reward continuation
      (rho reward * ε) root ∧
    ε ≤ oneShotTerminationProbability root ∧
    oneShotExpectedPayoff reward continuation root = current}

/-- **Proposition 2.2.** Under A.1, if every `w ∈ W` has an equilibrium
which is either all-Continue or has a positive-probability quitter receiving
at most `1`, then `ψ` has nonempty values for all sufficiently small
positive `ε`. -/
def Proposition2_2 : Prop :=
  ∀ (reward : {S : Finset ι // S.Nonempty} → Payoff ι),
    QuittingUnitSoloExit reward →
    (∀ value ∈ W reward, ∃ root : ι → PMF Bool,
      IsεQuittingRootNash reward value 0 root ∧
        (root = quittingAllContinueRoot ∨
          ∃ who, (root who false).toReal < 1 ∧
            oneShotExpectedPayoff reward value root who ≤ 1)) →
    ∃ ε₀ : ℝ, 0 < ε₀ ∧ ∀ ε : ℝ, 0 < ε → ε < ε₀ →
      ∀ value ∈ W reward,
        (oneShotCorrespondence reward (W reward) ε value).Nonempty

theorem proposition2_2 : Proposition2_2 (ι := ι) := by
  sorry

/-- **Proposition 2.3.** If `ψ` has nonempty values on a compact `W`, there
is a cyclic profile whose every tail terminates and whose rows are perfect
`(ρ+2)ε`-equilibria against their actual next-tail values. -/
def Proposition2_3 : Prop :=
  ∀ (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (W : Set (Payoff ι)) (ε : ℝ),
    0 < ε → W.Nonempty → IsCompact W →
    (∀ value ∈ W,
      (oneShotCorrespondence reward W ε value).Nonempty) →
      ∃ roots : RootSequence (ι := ι),
        cyclicRootSequence roots ∧
        (∀ start, terminating reward roots start) ∧
        ∀ start, oneShotPerfectEpsilonEquilibrium reward
          (quittingRootSequenceTailVector reward roots (start + 1))
          ((rho reward + 2) * ε) (roots start)

theorem proposition2_3 : Proposition2_3 (ι := ι) := by
  sorry

/-- **Proposition 2.4.** Under A.1 and for sufficiently small `ε`, a profile
with terminating tails and rows that are perfect `ε`-equilibria against the
actual next-tail values is either a subgame-perfect `ε^(1/6)`-equilibrium or
yields a stationary `ε^(1/6)`-equilibrium. -/
def Proposition2_4 : Prop :=
  ∀ (reward : {S : Finset ι // S.Nonempty} → Payoff ι),
    QuittingUnitSoloExit reward →
    ∃ ε₀ : ℝ, 0 < ε₀ ∧
      ∀ (roots : RootSequence (ι := ι)) (ε : ℝ),
        0 < ε → ε < ε₀ →
        (∀ start, terminating reward roots start) →
        (∀ start, oneShotPerfectEpsilonEquilibrium reward
          (quittingRootSequenceTailVector reward roots (start + 1))
          ε (roots start)) →
          subgamePerfectEpsilonEquilibrium reward roots
              (ε ^ (1 / 6 : ℝ)) ∨
            ∃ root : ι → PMF Bool,
              epsilonEquilibrium reward (ε ^ (1 / 6 : ℝ))
                (stationaryProfile reward root)

theorem proposition2_4 : Proposition2_4 (ι := ι) := by
  sorry

/-! ### 2.4. The correspondence lemma and noncyclic construction -/

/-- Upper semicontinuity in the paper's neighborhood formulation. -/
def upperSemicontinuous {α : Type*} [TopologicalSpace α]
    (K : Set α) (ψ : α → Set α) : Prop :=
  ∀ x ∈ K, ∀ U : Set α, IsOpen U → ψ x ⊆ U →
    ∃ V : Set α, IsOpen V ∧ x ∈ V ∧ ∀ y ∈ V ∩ K, ψ y ⊆ U

/-- **Lemma 2.5.** A nonempty-valued upper-semicontinuous correspondence
`φ : K → K` on a nonempty compact space admits an inverse iterative chain
`k_i ∈ φ(k_{i+1})`. -/
def Lemma2_5 : Prop :=
  ∀ (α : Type*) [TopologicalSpace α] (K : Set α),
    K.Nonempty → IsCompact K →
    ∀ ψ : α → Set α,
      (∀ x ∈ K, (ψ x).Nonempty ∧ ψ x ⊆ K) →
      upperSemicontinuous K ψ →
        ∃ sequence : ℕ → α,
          (∀ i, sequence i ∈ K) ∧
          ∀ i, sequence i ∈ ψ (sequence (i + 1))

theorem lemma2_5 : Lemma2_5 := by
  sorry

/-- The two-player terminal table in Example 2. Player 1 gets `2` only when
Player 2 quits alone; every other terminal coordinate is `1`. -/
def example2Reward
    (terminal : {S : Finset (Fin 2) // S.Nonempty}) : Payoff (Fin 2) :=
  fun who => if who = 0 ∧ terminal.1 = {1} then 2 else 1

/-- The profile of Example 2: Player 1 continues with probability `1-η`,
while Player 2 continues at paper stage `n+1` with probability
`1-ε/2^(n+1)`. -/
def example2ProfileCondition
    (roots : RootSequence (ι := Fin 2)) (ε η : ℝ) : Prop :=
  ∀ n,
    (roots n 0 false).toReal = 1 - η ∧
    (roots n 1 false).toReal = 1 - ε / (2 : ℝ) ^ (n + 1)

/-- A cyclic sequence formed by repeating finitely many stages of another
root sequence. -/
def repeatsFiniteStageSelection
    (source repeated : RootSequence (ι := ι)) : Prop :=
  cyclicRootSequence repeated ∧
    ∀ time, ∃ sourceTime, repeated time = source sourceTime

/-- **Example 2.** For `η > ε`, the displayed profile is subgame-perfect
`ε`, but no cyclic repetition of finitely many of its stages is a
`1/2`-equilibrium. -/
def Example2Claim : Prop :=
  ∀ ε η : ℝ, 0 < ε → ε < η → η < 1 →
    ∀ roots : RootSequence (ι := Fin 2),
      example2ProfileCondition roots ε η →
      subgamePerfectEpsilonEquilibrium example2Reward roots ε ∧
      ∀ repeated : RootSequence (ι := Fin 2),
        repeatsFiniteStageSelection roots repeated →
        ¬ epsilonEquilibrium example2Reward (1 / 2)
          (profile example2Reward repeated)

theorem example2 : Example2Claim := by
  sorry

/-! ### 2.5. Proof of the main proposition -/

/-- **Proposition 2.6.** The paper restates Proposition 2.4 before its block
proof. -/
def Proposition2_6 : Prop := Proposition2_4 (ι := ι)

theorem proposition2_6 : Proposition2_6 (ι := ι) := by
  exact proposition2_4

/-! **Facts 1--3 (paper).** If `u` is bounded in absolute value by `ρ`, then
`|𝔼[u]| ≤ ρ ℙ(Aᶜ) + supₐ∈ᴬ |u(a)|`. For every profile `y` and stage
`n`, its payoff decomposes into absorption before `n` and the surviving
tail payoff. Finally, the payoff from forcing player `i` to Quit is
independent of the one-shot continuation vector `w` and equals the quitting-
game payoff of that pure deviation. -/

/-- The probability that some opponent of `who` quits in a block. -/
def opponentBlockTerminationProbability
    (roots : RootSequence (ι := ι)) (who : ι)
    (start length : ℕ) : ℝ :=
  1 - ∏ time ∈ Finset.range length,
    (1 - quittingRootOpponentAbsorptionMass (roots (start + time)) who)

/-- **Definition 2.7.** A block is Type I for player `i` when the probability
that another player quits in it is at least `ε^b`; otherwise it is Type II. -/
def blockTypeI
    (roots : RootSequence (ι := ι)) (who : ι)
    (start length : ℕ) (ε b : ℝ) : Prop :=
  ε ^ b ≤ opponentBlockTerminationProbability roots who start length

/-- Probability of absorption in a finite block under the prescribed
profile. -/
def blockTerminationProbability
    (roots : RootSequence (ι := ι)) (start length : ℕ) : ℝ :=
  1 - quittingJointSurvivalWeight roots start length

/-- Probability that the first absorption in a block occurs while `who`
continues, so that some opponent is in the quitting coalition. -/
def opponentFirstAbsorptionProbability
    (roots : RootSequence (ι := ι)) (who : ι)
    (start length : ℕ) : ℝ :=
  ∑ time ∈ Finset.range length,
    quittingJointSurvivalWeight roots start time *
      (roots (start + time) who false).toReal *
        quittingRootOpponentAbsorptionMass (roots (start + time)) who

/-- Probability that the first absorption in a block contains `who`. -/
def ownerFirstAbsorptionProbability
    (roots : RootSequence (ι := ι)) (who : ι)
    (start length : ℕ) : ℝ :=
  ∑ time ∈ Finset.range length,
    quittingJointSurvivalWeight roots start time *
      (roots (start + time) who true).toReal

/-- Conditional payoff when the first absorption in the block contains
`who`. This is the paper's `u₁`. -/
def ownerConditionalBlockPayoff
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : RootSequence (ι := ι)) (who : ι)
    (start length : ℕ) : ℝ :=
  (∑ time ∈ Finset.range length,
      quittingJointSurvivalWeight roots start time *
        (roots (start + time) who true).toReal *
          quittingRootQuitPayoff reward 0 (roots (start + time)) who) /
    ownerFirstAbsorptionProbability roots who start length

/-- Conditional payoff when an opponent causes the first absorption in the
block under the prescribed profile. This is `u₂`. -/
def opponentConditionalBlockPayoff
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : RootSequence (ι := ι)) (who : ι)
    (start length : ℕ) : ℝ :=
  (∑ time ∈ Finset.range length,
      quittingJointSurvivalWeight roots start time *
        (roots (start + time) who false).toReal *
          quittingRootAbsorbingContribution reward
            (Function.update (roots (start + time)) who (PMF.pure false)) who) /
    opponentFirstAbsorptionProbability roots who start length

/-- The opponent-absorption conditional payoff after forcing `who` to
Continue. This is the paper's `u₂*`. -/
def forcedContinueOpponentConditionalBlockPayoff
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : RootSequence (ι := ι)) (who : ι)
    (start length : ℕ) : ℝ :=
  let forced := fun time =>
    Function.update (roots time) who (PMF.pure false)
  (∑ time ∈ Finset.range length,
      quittingJointSurvivalWeight forced start time *
        quittingRootAbsorbingContribution reward
          (forced (start + time)) who) /
    opponentBlockTerminationProbability roots who start length

/-- The roots obtained when `who` continues until `cutoff` and then resumes
the prescribed profile. -/
def continueUntilRoots
    (roots : RootSequence (ι := ι)) (who : ι) (cutoff : ℕ) :
    RootSequence (ι := ι) :=
  fun time => if time < cutoff then
    Function.update (roots time) who (PMF.pure false)
  else roots time

/-- The actual proof context of Lemmas 2.8--2.12 in the regularly-scattered
case. It retains the paper's root sequence, block endpoints, pure deviation,
and all enclosing hypotheses instead of treating `π₂`, `u₂`, and `X_k` as
unconstrained real variables. -/
structure MainEstimateContext (ι : Type) [Fintype ι] [DecidableEq ι] where
  reward : {S : Finset ι // S.Nonempty} → Payoff ι
  roots : RootSequence (ι := ι)
  who : ι
  ε : ℝ
  ρ : ℝ
  a : ℝ
  b : ℝ
  exponent : ℝ
  localStart : ℕ
  localLength : ℕ
  blockStart : ℕ → ℕ
  quitTime : Option ℕ
  rho_eq : ρ = rho reward
  unitSoloExit : QuittingUnitSoloExit reward
  tailsTerminate : ∀ start, terminating reward roots start
  rowsPerfect : ∀ time, oneShotPerfectEpsilonEquilibrium reward
    (quittingRootSequenceTailVector reward roots (time + 1)) ε (roots time)
  blockStart_zero : blockStart 0 = 0
  blockStart_strictMono : StrictMono blockStart
  blockAbsorbs : ∀ block,
    ε ^ a ≤ blockTerminationProbability roots (blockStart block)
      (blockStart (block + 1) - blockStart block)
  typeI_regular : ∀ block, ∃ later : ℕ,
    block ≤ later ∧ (later : ℝ) - block ≤ 1 / ε ^ exponent ∧
      blockTypeI roots who (blockStart later)
        (blockStart (later + 1) - blockStart later) ε b

/-- The exponent and local-window restrictions fixed before the block
argument. -/
def MainEstimateContext.Admissible
    (data : MainEstimateContext ι) : Prop :=
  0 < data.ε ∧ data.ε < 1 ∧ 0 ≤ data.ρ ∧
  1 / 5 < data.a ∧ data.a < data.exponent ∧
  1 / 5 < data.b - data.exponent ∧
  1 / 5 < 1 - data.b - data.exponent ∧
  0 < ownerFirstAbsorptionProbability data.roots data.who
      data.localStart data.localLength ∧
  blockTerminationProbability data.roots data.localStart
      data.localLength < data.ε ^ data.a

/-- The paper's `π₂`. -/
def MainEstimateContext.π₂
    (data : MainEstimateContext ι) : ℝ :=
  opponentFirstAbsorptionProbability data.roots data.who
    data.localStart data.localLength

/-- The paper's `π₂*`. -/
def MainEstimateContext.π₂star
    (data : MainEstimateContext ι) : ℝ :=
  opponentBlockTerminationProbability data.roots data.who
    data.localStart data.localLength

/-- The paper's `u₁`. -/
def MainEstimateContext.u₁
    (data : MainEstimateContext ι) : ℝ :=
  ownerConditionalBlockPayoff data.reward data.roots data.who
    data.localStart data.localLength

/-- The paper's `u₂`. -/
def MainEstimateContext.u₂
    (data : MainEstimateContext ι) : ℝ :=
  opponentConditionalBlockPayoff data.reward data.roots data.who
    data.localStart data.localLength

/-- The paper's `u₂*`. -/
def MainEstimateContext.u₂star
    (data : MainEstimateContext ι) : ℝ :=
  forcedContinueOpponentConditionalBlockPayoff data.reward data.roots
    data.who data.localStart data.localLength

/-- The paper's `E_{x^{-i},c^i}[X_k]`. -/
def MainEstimateContext.blockExpectation
    (data : MainEstimateContext ι) (block : ℕ) : ℝ :=
  quittingRootSequenceTerminalValue data.reward
    (continueUntilRoots data.roots data.who (data.blockStart block))
    data.who 0

/-- **Lemma 2.8.** `|π₂-π₂*| ≤ ε^a π₂*`. -/
def Lemma2_8 : Prop :=
  ∀ (ι : Type) [Fintype ι] [DecidableEq ι]
    (data : MainEstimateContext ι), data.Admissible →
      |data.π₂ - data.π₂star| ≤ data.ε ^ data.a * data.π₂star

theorem lemma2_8 : Lemma2_8 := by
  sorry

/-- **Lemma 2.9.** `|u₂-u₂*| ≤ 2ρ ε^a`. -/
def Lemma2_9 : Prop :=
  ∀ (ι : Type) [Fintype ι] [DecidableEq ι]
    (data : MainEstimateContext ι), data.Admissible →
      |data.u₂ - data.u₂star| ≤ 2 * data.ρ * data.ε ^ data.a

theorem lemma2_9 : Lemma2_9 := by
  sorry

/-- **Lemma 2.10.**
`|γⁱ(x_{n₂-1})-u₁| ≤ 4ρNπ₂* + ε`. -/
def Lemma2_10 : Prop :=
  ∀ (ι : Type) [Fintype ι] [DecidableEq ι]
    (data : MainEstimateContext ι), data.Admissible →
      |quittingRootSequenceTailVector data.reward data.roots
          (data.localStart + data.localLength) data.who - data.u₁| ≤
        4 * data.ρ * Fintype.card ι * data.π₂star + data.ε

theorem lemma2_10 : Lemma2_10 := by
  sorry

/-- **Lemma 2.11.** A pure deviation payoff is bounded by the supremum of
the block continuation expectations plus `ε + 2ρ ε^a`. -/
def Lemma2_11 : Prop :=
  ∀ (ι : Type) [Fintype ι] [DecidableEq ι]
    (data : MainEstimateContext ι), data.Admissible →
      quittingRootSequenceHazardTerminalValue data.reward data.roots data.who
          (quittingPureTimeHazard data.quitTime) 0 ≤
        sSup (Set.range data.blockExpectation) +
          data.ε + 2 * data.ρ * data.ε ^ data.a

theorem lemma2_11 : Lemma2_11 := by
  sorry

/-- **Lemma 2.12.** The block expectation supremum is at most the current
payoff plus `2ε^(1-b-e) + 7ρNε^a`. -/
def Lemma2_12 : Prop :=
  ∀ (ι : Type) [Fintype ι] [DecidableEq ι]
    (data : MainEstimateContext ι), data.Admissible →
      sSup (Set.range data.blockExpectation) ≤
        quittingRootSequenceTerminalValue data.reward data.roots data.who 0 +
          2 * data.ε ^ (1 - data.b - data.exponent) +
          7 * data.ρ * Fintype.card ι * data.ε ^ data.a

theorem lemma2_12 : Lemma2_12 := by
  sorry

/-! ### 2.6. Equilibrium and uniformity -/

/-- The paper's uniform `ε`-equilibrium: the profile is an `ε`-equilibrium
for every sufficiently long finite-average payoff. -/
def uniformEpsilonEquilibrium
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (ε : ℝ) (profile : (quittingGame reward).BehaviorProfile) : Prop :=
  (quittingGame reward).IsUniformεEquilibrium none ε profile

/-- **Proposition 2.13.** A terminal `ε`-equilibrium is a uniform
`ε'`-equilibrium whenever `ε < ε'`. -/
theorem proposition2_13
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    {ε ε' : ℝ} (herror : ε < ε')
    (hnash : epsilonEquilibrium reward ε profile) :
    uniformEpsilonEquilibrium reward ε' profile :=
  quittingGame_isUniformεEquilibrium_of_terminalNash
    reward profile herror hnash

/-! ### 2.7. General payoff processes -/

/-- The random payoff process of Theorem 2.14. -/
structure PayoffProcess (ι : Type) [Fintype ι] [DecidableEq ι] where
  Ω : Type
  measurableSpace : MeasurableSpace Ω
  μ : @Measure Ω measurableSpace
  probability : IsProbabilityMeasure μ
  payoff : ℕ → Ω → ({S : Finset ι // S.Nonempty} → Payoff ι)
  limit : Ω → ({S : Finset ι // S.Nonempty} → Payoff ι)
  payoff_measurable : ∀ n terminal who,
    Measurable (fun ω => payoff n ω terminal who)
  limit_measurable : ∀ terminal who,
    Measurable (fun ω => limit ω terminal who)
  integrableEnvelope : ∃ bound : Ω → ℝ,
    Integrable bound μ ∧ ∀ n ω terminal who,
      |payoff n ω terminal who| ≤ bound ω
  converges : ∀ᵐ ω ∂μ, ∀ terminal who,
    Tendsto (fun n => payoff n ω terminal who) atTop
      (nhds (limit ω terminal who))

/-- A behavioral profile for a paper payoff process. -/
abbrev ProcessProfile (process : PayoffProcess ι) :=
  ℕ → ι → process.Ω → PMF Bool

/-- The paper's natural filtration `ℱₙ = σ(rₚ : p < n)`. Repository
time zero represents paper stage one. -/
@[reducible] def processFiltration
    (process : PayoffProcess ι) (time : ℕ) :
    MeasurableSpace process.Ω :=
  ⨆ previous : Fin time, ⨆ terminal, ⨆ who,
    MeasurableSpace.comap
      (fun ω => process.payoff previous ω terminal who) inferInstance

/-- Adaptedness to the natural-information filtration of the payoff
process. -/
def processAdapted
    (process : PayoffProcess ι)
    (profile : ProcessProfile process) : Prop :=
  ∀ time who action,
    Measurable[processFiltration process time]
      (fun ω => (profile time who ω action).toReal)

/-- The expected payoff at the first nonempty quitting coalition. The
summand is survival through the preceding stages times the current absorbing
reward contribution; nontermination contributes zero. -/
def processExpectedPayoff
    (process : PayoffProcess ι)
    (profile : ProcessProfile process) : Payoff ι :=
  fun who => ∫ ω,
    ∑' time,
      quittingJointSurvivalWeight
          (fun stage player => profile stage player ω) 0 time *
        quittingRootAbsorbingContribution (process.payoff time ω)
          (fun player => profile time player ω) who ∂process.μ

/-- The limit process satisfies A.1 and A.2 almost surely. -/
def processAssumptions (process : PayoffProcess ι) : Prop :=
  ∀ᵐ ω ∂process.μ, ∀ who,
    process.limit ω (quittingSingletonTerminal who) who = 1 ∧
      ∀ terminal, who ∈ terminal.1 → process.limit ω terminal who ≤ 1

/-- No adapted unilateral deviation improves the process payoff by more than
`ε`. -/
def processEpsilonEquilibrium
    (process : PayoffProcess ι)
    (profile : ProcessProfile process) (ε : ℝ) : Prop :=
  ∀ who (deviation : ℕ → process.Ω → PMF Bool),
    processAdapted process
      (fun time => Function.update (profile time) who (deviation time)) →
    processExpectedPayoff process profile who + ε ≥
      processExpectedPayoff process
        (fun time => Function.update (profile time) who (deviation time)) who

/-- **Theorem 2.14.** If the payoff process converges almost surely, has an
integrable uniform envelope, and its limit satisfies A.1 and A.2 almost
surely, then it admits an `ε`-equilibrium for every `ε > 0`. -/
def Theorem2_14 : Prop :=
  ∀ (process : PayoffProcess ι), processAssumptions process →
    ∀ ε : ℝ, 0 < ε → ∃ profile : ProcessProfile process,
      processAdapted process profile ∧
        processEpsilonEquilibrium process profile ε

theorem theorem2_14 : Theorem2_14 (ι := ι) := by
  sorry

/-! ## 3. The four-player example -/

/-- The quartic appearing in Equation (30). -/
def figure2Polynomial (h : ℝ) : ℝ :=
  h ^ 4 + 3 * h ^ 3 - 2 * h ^ 2 - 9 * h + 4

/-- The exact period-two roots in Section 3. Lean time zero represents the
paper's first odd stage. The mixing parameters are `x=1/h` and `z=1/g`. -/
def figure2PhaseRootCondition
    (g h : ℝ) (roots : RootSequence (ι := Fin 4)) : Prop :=
  1 < g ∧ 1 < h ∧ h < 2 ∧ g = 3 / (4 - h ^ 2) ∧
  figure2Polynomial h = 0 ∧
  ∀ time,
    (time % 2 = 0 →
      roots time 1 = PMF.pure false ∧
      roots time 3 = PMF.pure false ∧
      (roots time 0 false).toReal = 1 / h ∧
      (roots time 2 false).toReal = 1 / g) ∧
    (time % 2 = 1 →
      roots time 0 = PMF.pure false ∧
      roots time 2 = PMF.pure false ∧
      (roots time 1 false).toReal = 1 / h ∧
      (roots time 3 false).toReal = 1 / g)

/-- Section 3's displayed profile is a period-two equilibrium. -/
def Figure2CyclicEquilibriumClaim : Prop :=
  ∃ g h : ℝ, ∃ roots : RootSequence (ι := Fin 4),
    cyclicRootSequence roots ∧
    figure2PhaseRootCondition g h roots ∧
    epsilonEquilibrium SolanVieilleBoundary.boundaryReward 0
      (profile SolanVieilleBoundary.boundaryReward roots)

theorem figure2_cyclic_equilibrium :
    Figure2CyclicEquilibriumClaim := by
  sorry

/-- The Figure 2 game has no stationary `ε`-equilibrium for all sufficiently
small positive `ε`. The paper states this result and refers elsewhere for the
omitted technical details. -/
def Figure2NoStationaryEpsilonClaim : Prop :=
  ∃ ε₀ : ℝ, 0 < ε₀ ∧ ∀ ε, 0 < ε → ε < ε₀ →
    ¬ ∃ root : Fin 4 → PMF Bool,
      epsilonEquilibrium SolanVieilleBoundary.boundaryReward ε
        (stationaryProfile SolanVieilleBoundary.boundaryReward root)

theorem figure2_no_stationary_epsilon :
    Figure2NoStationaryEpsilonClaim := by
  sorry

/-- The Figure 2 game has no `ε`-equilibrium whose time-dependent mixed root
stays `ε`-close to all-Continue at every stage. This is not restricted to
stationary roots. -/
def Figure2NoPerturbedEpsilonClaim : Prop :=
  ∃ ε₀ : ℝ, 0 < ε₀ ∧ ∀ ε, 0 < ε → ε < ε₀ →
    ¬ ∃ roots : RootSequence (ι := Fin 4),
      (∀ time player,
        |(roots time player false).toReal - 1| < ε) ∧
      epsilonEquilibrium SolanVieilleBoundary.boundaryReward ε
        (profile SolanVieilleBoundary.boundaryReward roots)

theorem figure2_no_perturbed_epsilon :
    Figure2NoPerturbedEpsilonClaim := by
  sorry

/-- The repository's Figure 2 terminal table satisfies A.1 and A.2. -/
theorem boundaryReward_assumptions :
    assumptions SolanVieilleBoundary.boundaryReward :=
  ⟨SolanVieilleBoundary.boundaryReward_unitSoloExit,
    SolanVieilleBoundary.boundaryReward_cappedJointExit⟩

/-! ## Appendix: the independent-clock estimate -/

/-- A finitely additive real-valued probability interface sufficient for the
paper's finite event calculation. -/
structure Probability (Ω : Type*) where
  prob : Set Ω → ℝ
  empty : prob ∅ = 0
  univ : prob Set.univ = 1
  nonneg : ∀ event, 0 ≤ prob event
  add_of_disjoint : ∀ first second,
    Disjoint first second →
      prob (first ∪ second) = prob first + prob second

/-- The first `true` value of a finite Boolean clock, or infinity if the
clock has no success. -/
def firstSuccessTime {N : ℕ} { Ω : Type* }
    (bits : Fin N → Ω → Bool) (ω : Ω) : WithTop ℕ :=
  if hsuccess : (Finset.univ.filter fun n => bits n ω = true).Nonempty then
    ((Finset.univ.filter fun n => bits n ω = true).min' hsuccess : ℕ)
  else ⊤

/-- Mutual independence of the two finite families of Bernoulli variables,
expressed by factorization of every joint atom. -/
def independentBernoulliSequences {N : ℕ} { Ω : Type* }
    (probability : Probability Ω)
    (first second : Fin N → Ω → Bool) : Prop :=
  ∀ firstValues secondValues : Fin N → Bool,
    probability.prob
        {ω | (∀ n, first n ω = firstValues n) ∧
          ∀ n, second n ω = secondValues n} =
      (∏ n, probability.prob {ω | first n ω = firstValues n}) *
        ∏ n, probability.prob {ω | second n ω = secondValues n}

/-- The event that a first-success time is strictly before `N`. -/
def beforeEvent {Ω : Type*}
    (first : Ω → WithTop ℕ) (N : ℕ) : Set Ω :=
  {ω | first ω < N}

/-- The event that the first clock succeeds at `n`. -/
def firstAtEvent {Ω : Type*}
    (first : Ω → WithTop ℕ) (n : ℕ) : Set Ω :=
  {ω | first ω = n}

/-- `T < N` in Appendix Lemma 3.1: the first clock succeeds before `N` and
strictly before the second clock. -/
def firstBeforeSecondEvent {Ω : Type*}
    (first₁ first₂ : Ω → WithTop ℕ) (N : ℕ) : Set Ω :=
  {ω | first₁ ω < N ∧ first₁ ω < first₂ ω}

/-- **Appendix Lemma 3.1.** For independent first-success clocks, the loss
from requiring clock 1 to ring before clock 2 is bounded by the product of
their success probabilities, and the two conditional first-clock laws are
within `2 P(S₂<N)` in `ℓ¹`. -/
def Lemma3_1 : Prop :=
  ∀ (Ω : Type*) (probability : Probability Ω) (N : ℕ)
    (firstBits secondBits : Fin N → Ω → Bool),
    independentBernoulliSequences probability firstBits secondBits →
    let first₁ := firstSuccessTime firstBits
    let first₂ := firstSuccessTime secondBits
    0 < probability.prob
      (firstBeforeSecondEvent first₁ first₂ N) →
      probability.prob (beforeEvent first₁ N) -
          probability.prob
            (firstBeforeSecondEvent first₁ first₂ N) ≤
        probability.prob (beforeEvent first₁ N) *
          probability.prob (beforeEvent first₂ N) ∧
      (∑ n ∈ Finset.range N,
        |probability.prob (firstAtEvent first₁ n) /
            probability.prob (beforeEvent first₁ N) -
          probability.prob
              (firstAtEvent first₁ n ∩
                firstBeforeSecondEvent first₁ first₂ N) /
            probability.prob
              (firstBeforeSecondEvent first₁ first₂ N)|) ≤
        2 * probability.prob (beforeEvent first₂ N)

theorem lemma3_1 : Lemma3_1 := by
  sorry

/-! ## Checked downstream correspondences -/

/-- The exact Theorem 1.2 profile also supplies the weaker integrated
profile-level existence interface. -/
theorem uniformεEquilibriumUnderSoloExitAssumptionsClaim_holds :
    QuittingCappedJointExitUniformεExistence ι :=
  quittingCappedJointExitUniformεExistence_holds

/-- The integrated existence interface supplies one fixed uniform-equilibrium
payoff target. -/
theorem exists_uniformEquilibriumPayoff_of_claim
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (hunit : QuittingUnitSoloExit reward)
    (hcapped : QuittingCappedJointExit reward) :
    ∃ payoff : Payoff ι,
      (quittingGame reward).IsUniformEquilibriumPayoff none payoff :=
  exists_uniformEquilibriumPayoff_of_soloExitPreference hunit hcapped

end Literature.SolanAndVieille2001
