import MathUE.Topology.CompactSerialRelation
import UniformEquilibrium.Quitting.Classification.Existence.PerfectSequenceExtraction
import UniformEquilibrium.Quitting.Classification.SoloExitPreferenceExistence
import UniformEquilibrium.Quitting.Cycles.PeriodicJointSurvival
import UniformEquilibrium.Quitting.Examples.SolanVieilleBoundaryEquilibrium
import UniformEquilibrium.Quitting.Paths.SureExitSet
import UniformEquilibrium.Quitting.Terminal.TargetTail.TerminalUniformization

noncomputable section

/-!
# E. Solan and N. Vieille, “Quitting Games” (2001)

Eilon Solan and Nicolas Vieille, “Quitting Games,” *Mathematics of
Operations Research* **26**(2), 265--285 (2001), DOI
`10.1287/moor.26.2.265.10549`.

This file follows the published journal paper in order and terminology. The
paper uses a finite player set `N`, terminal payoff vectors `r_S` for every
nonempty quitting coalition `S`, and actions `c^i` and `q^i`. A profile is a
time-indexed sequence of mixed action vectors conditional on survival. The
game pays zero if nobody ever quits.

Unproved source claims remain `sorry`. Checked production reformulations are
kept separate from the exact source statements and never replace them.
-/

namespace Literature.SolanAndVieille2001

open GameTheory StochasticGame MeasureTheory Filter Set
open GameTheory.QuittingSureSetOwnerRepair

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-! ## 1. The model and the main results -/

/-- The paper's profile `x = (x_n)`: a mixed action vector after every
surviving stage. `false` is Continue and `true` is Quit. -/
abbrev RootSequence := ℕ → ι → PMF Bool

/-- The behavior profile generated by a paper root sequence. -/
def profile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : RootSequence (ι := ι)) :
    (quittingGame reward).BehaviorProfile :=
  quittingRootSequenceProfile reward roots 0

/-- The paper's tail `x_n = (x_n,x_{n+1},...)`. -/
def tailProfile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : RootSequence (ι := ι)) (start : ℕ) :
    (quittingGame reward).BehaviorProfile :=
  quittingRootSequenceProfile reward roots start

/-- A profile terminates when absorption occurs almost surely. -/
def terminating
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : RootSequence (ι := ι)) (start : ℕ) : Prop :=
  quittingLiveMassLimit reward (tailProfile reward roots start) = 0

/-- Cyclicity in the paper: the mixed action vectors are periodic from the
first stage. -/
def cyclicRootSequence (roots : RootSequence (ι := ι)) : Prop :=
  ∃ period : ℕ, 0 < period ∧ ∀ time, roots (time + period) = roots time

/-- A stationary root sequence. -/
def stationaryRootSequence
    (roots : RootSequence (ι := ι)) : Prop :=
  ∀ time, roots time = roots 0

/-- The stationary profile generated by one mixed action vector. -/
def stationaryProfile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) : (quittingGame reward).BehaviorProfile :=
  quittingStationaryProfile reward root

/-- A root is pure when every player uses a pure action. -/
def pureRoot (root : ι → PMF Bool) : Prop :=
  ∀ who, root who = PMF.pure false ∨ root who = PMF.pure true

/-- **Definition 1.1.** A profile is an `ε`-equilibrium when no unilateral
strategy gains more than `ε` in the terminal-payoff game. -/
def epsilonEquilibrium
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (ε : ℝ) (profile : (quittingGame reward).BehaviorProfile) : Prop :=
  (quittingGame reward).IsεAsymptoticNash
    (quittingTerminalPayoff reward) ε profile

/-- **Definition 1.1.** An `ε`-equilibrium payoff is realized by an
`ε`-equilibrium profile. -/
def epsilonEquilibriumPayoff
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (ε : ℝ) (payoff : Payoff ι) : Prop :=
  ∃ profile, epsilonEquilibrium reward ε profile ∧
    quittingTerminalPayoff reward profile = payoff

/-- **Definition 1.1.** Subgame perfection requires every surviving tail to
be an `ε`-equilibrium. -/
def subgamePerfectEpsilonEquilibrium
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : RootSequence (ι := ι)) (ε : ℝ) : Prop :=
  ∀ start, epsilonEquilibrium reward ε
    (tailProfile reward roots start)

/-- Assumptions A.1 and A.2 of Theorem 1.2. -/
def assumptions
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) : Prop :=
  QuittingUnitSoloExit reward ∧ QuittingCappedJointExit reward

/-- **Theorem 1.2.** Every quitting game satisfying A.1 and A.2 has a cyclic
subgame-perfect `ε`-equilibrium for every `ε > 0`. -/
def Theorem1_2 : Prop :=
  ∀ (reward : {S : Finset ι // S.Nonempty} → Payoff ι),
    assumptions reward → ∀ ε : ℝ, 0 < ε →
      ∃ roots : RootSequence (ι := ι),
        cyclicRootSequence roots ∧
          subgamePerfectEpsilonEquilibrium reward roots ε

/-- Theorem 1.2, checked against the exact cyclic and every-tail conclusion. -/
theorem theorem1_2 : Theorem1_2 (ι := ι) := by
  intro reward hassumptions ε hε
  rcases hassumptions with ⟨hunit, hcap⟩
  cases isEmpty_or_nonempty ι with
  | inl _ =>
      let roots : RootSequence (ι := ι) := fun _ _ => PMF.pure false
      refine ⟨roots, ⟨1, by norm_num, fun _ => rfl⟩, ?_⟩
      intro _start who
      exact isEmptyElim who
  | inr hnonempty =>
      letI : Nonempty ι := hnonempty
      obtain ⟨roots, period, hperiod, hperiodic, hsubgame⟩ :=
        exists_cyclic_subgamePerfectTerminalNash_of_soloExitPreference
          hunit hcap hε
      exact ⟨roots, ⟨period, hperiod, hperiodic⟩, hsubgame⟩

/-- A symmetric quitting table depends only on coalition size and on whether
the observed player belongs to the quitting coalition. -/
def symmetricReward
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) : Prop :=
  ∃ quitterPayoff nonquitterPayoff : ℕ → ℝ,
    ∀ terminal who,
      reward terminal who =
        if who ∈ terminal.1 then quitterPayoff terminal.1.card
        else nonquitterPayoff terminal.1.card

/-- **Theorem 1.3.** Every symmetric quitting game has a pure stationary
zero-equilibrium. -/
def Theorem1_3 : Prop :=
  ∀ (reward : {S : Finset ι // S.Nonempty} → Payoff ι),
    symmetricReward reward →
      ∃ root : ι → PMF Bool, pureRoot root ∧
        epsilonEquilibrium reward 0 (stationaryProfile reward root)

private theorem exists_symmetricExitCard
    (players : ℕ) (quitterPayoff nonquitterPayoff : ℕ → ℝ)
    (hplayers : 0 < players) :
    ∃ card : ℕ,
      1 ≤ card ∧ card ≤ players ∧
        (card = 1 ∨
          nonquitterPayoff (card - 1) ≤ quitterPayoff card) ∧
        (card = players ∨
          quitterPayoff (card + 1) ≤ nonquitterPayoff card) := by
  let boundary : ℕ → Prop := fun card ↦
    1 ≤ card ∧ card ≤ players ∧
      (card = players ∨
        quitterPayoff (card + 1) ≤ nonquitterPayoff card)
  have hexists : ∃ card, boundary card := by
    exact ⟨players, hplayers, le_rfl, Or.inl rfl⟩
  let card := Nat.find hexists
  have hcard := Nat.find_spec hexists
  refine ⟨card, hcard.1, hcard.2.1, ?_, hcard.2.2⟩
  by_cases hcardOne : card = 1
  · exact Or.inl hcardOne
  · right
    have hpredLt : card - 1 < card := by omega
    have hpredNot := Nat.find_min hexists hpredLt
    have hpredOne : 1 ≤ card - 1 := by omega
    have hpredPlayers : card - 1 ≤ players := by omega
    have hpredNe : card - 1 ≠ players := by omega
    have hnotLe : ¬ quitterPayoff ((card - 1) + 1) ≤
        nonquitterPayoff (card - 1) := by
      intro hle
      exact hpredNot ⟨hpredOne, hpredPlayers, Or.inr hle⟩
    have hsucc : (card - 1) + 1 = card := by omega
    rw [hsucc] at hnotLe
    exact le_of_lt (lt_of_not_ge hnotLe)

theorem theorem1_3 : Theorem1_3 (ι := ι) := by
  intro reward hsymmetry
  obtain ⟨quitterPayoff, nonquitterPayoff, hreward⟩ := hsymmetry
  by_cases hplayers : Fintype.card ι = 0
  · haveI : IsEmpty ι := Fintype.card_eq_zero_iff.mp hplayers
    let root : ι → PMF Bool := fun who ↦ isEmptyElim who
    refine ⟨root, fun who ↦ isEmptyElim who, ?_⟩
    intro who
    exact isEmptyElim who
  · have hplayersPos : 0 < Fintype.card ι := Nat.pos_of_ne_zero hplayers
    by_cases hsolo : quitterPayoff 1 ≤ 0
    · refine ⟨quittingPureSetRoot ∅, ?_, ?_⟩
      · intro who
        exact Or.inl (by simp [quittingPureSetRoot, quittingSetAction])
      · exact (isεAsymptoticNash_pureSetRoot_iff_isQuittingSureExitSet
          reward ∅).mpr
          ((isQuittingSureExitSet_empty_iff reward).mpr fun who ↦ by
            rw [quittingSoloReward, hreward]
            simp
            exact hsolo)
    · obtain ⟨card, hcardOne, hcardPlayers, hmember, houtsider⟩ :=
        exists_symmetricExitCard (Fintype.card ι) quitterPayoff
          nonquitterPayoff hplayersPos
      obtain ⟨exitSet, -, hexitCard⟩ :=
        Finset.exists_subset_card_eq (s := (Finset.univ : Finset ι))
          hcardPlayers
      have hexitNonempty : exitSet.Nonempty :=
        Finset.card_pos.mp (by omega)
      refine ⟨quittingPureSetRoot exitSet, ?_, ?_⟩
      · intro who
        by_cases hwho : who ∈ exitSet
        · exact Or.inr (by simp [quittingPureSetRoot, quittingSetAction, hwho])
        · exact Or.inl (by simp [quittingPureSetRoot, quittingSetAction, hwho])
      · apply (isεAsymptoticNash_pureSetRoot_iff_isQuittingSureExitSet
          reward exitSet).mpr
        constructor
        · intro member hmemberSet
          rw [quittingSetReward_of_nonempty reward hexitNonempty,
            hreward]
          simp only [hmemberSet, ↓reduceIte]
          by_cases herase : (exitSet.erase member).Nonempty
          · rw [quittingSetReward_of_nonempty reward herase, hreward]
            simp only [Finset.mem_erase, ne_eq, not_true_eq_false]
            rw [Finset.card_erase_of_mem hmemberSet, hexitCard]
            exact hmember.resolve_left fun hcardEq ↦ by
              have heraseCard := Finset.card_erase_of_mem hmemberSet
              have herasePos := Finset.card_pos.mpr herase
              rw [hexitCard, hcardEq] at heraseCard
              omega
          · have heraseEmpty : exitSet.erase member = ∅ :=
              Finset.not_nonempty_iff_eq_empty.mp herase
            have hcardEq : card = 1 := by
              have := Finset.card_erase_of_mem hmemberSet
              rw [heraseEmpty, Finset.card_empty, hexitCard] at this
              omega
            simp [quittingSetReward, heraseEmpty]
            rw [hexitCard, hcardEq]
            exact le_of_lt (lt_of_not_ge hsolo)
        · intro outsider houtsiderSet
          rw [quittingSetReward_of_nonempty reward hexitNonempty, hreward]
          simp only [houtsiderSet, ↓reduceIte]
          have hinsertNonempty : (insert outsider exitSet).Nonempty :=
            Finset.insert_nonempty outsider exitSet
          rw [quittingSetReward_of_nonempty reward hinsertNonempty, hreward]
          simp only [Finset.mem_insert, true_or, ↓reduceIte]
          rw [Finset.card_insert_of_notMem houtsiderSet, hexitCard]
          exact houtsider.resolve_left fun h ↦ by
            apply houtsiderSet
            have hexitUniv : exitSet = Finset.univ :=
              exitSet.card_eq_iff_eq_univ.mp (hexitCard.trans h)
            rw [hexitUniv]
            simp

/-! ### Example 1: a symmetric game without symmetric approximate equilibria -/

/-- The two-player symmetric terminal table in Example 1: a sole quitter
gets `1`, the other player gets `2`, and simultaneous quitters get `1`. -/
def example1Reward
    (terminal : {S : Finset (Fin 2) // S.Nonempty}) : Payoff (Fin 2) :=
  fun who => if who ∈ terminal.1 then 1 else 2

/-- A symmetric profile uses the same mixed action for both players at every
stage. -/
def symmetricRootSequence
    (roots : RootSequence (ι := Fin 2)) : Prop :=
  ∀ time first second, roots time first = roots time second

/-- **Example 1.** If `ε + 2√ε < 1/2`, the displayed symmetric game has no
symmetric `ε`-equilibrium. -/
def Example1Claim : Prop :=
  ∀ ε : ℝ, 0 ≤ ε → ε + 2 * Real.sqrt ε < 1 / 2 →
    ¬ ∃ roots : RootSequence (ι := Fin 2),
      symmetricRootSequence roots ∧
        epsilonEquilibrium example1Reward ε
          (profile example1Reward roots)

theorem example1 : Example1Claim := by
  sorry

/-! ## 2. Existence result -/

/-! ### 2.1. The one-shot game -/

/-- The one-shot absorption probability `p(x)`. -/
def oneShotTerminationProbability (root : ι → PMF Bool) : ℝ :=
  quittingRootAbsorptionMass root

/-- The one-shot payoff `⟨G(w),x⟩`. -/
def oneShotExpectedPayoff
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (continuationValue : Payoff ι) (root : ι → PMF Bool) : Payoff ι :=
  quittingRootSuccessorPayoff reward continuationValue root

/-- **Definition 2.1.** A one-shot root is a perfect `ε`-equilibrium when
every action in each player's support is within `ε` of every pure reply. -/
def oneShotPerfectEpsilonEquilibrium
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (continuationValue : Payoff ι) (ε : ℝ)
    (root : ι → PMF Bool) : Prop :=
  ∀ who action, root who action ≠ 0 → ∀ alternative,
    quittingRootExpectedPayoff reward continuationValue
        (Function.update root who (PMF.pure alternative)) who ≤
      quittingRootExpectedPayoff reward continuationValue
          (Function.update root who (PMF.pure action)) who + ε

/-! ### 2.2. The three propositions implying Theorem 1.2 -/

/-- Twice the maximal absolute terminal payoff, the paper's `ρ`. -/
def rho
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) : ℝ :=
  2 * quittingRewardBound reward

/-- The paper's special continuation set
`W = {w ∈ [-ρ,ρ]^N | w^i ≤ 1 for some i}`. -/
def W
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :
    Set (Payoff ι) :=
  {value | (∀ who, |value who| ≤ rho reward) ∧
    ∃ who, value who ≤ 1}

/-- The value-valued correspondence `ψ`: perfect `ρε` roots with absorption
at least `ε`, whose produced value remains in `W`. -/
def oneShotCorrespondence
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (W : Set (Payoff ι)) (ε : ℝ) (continuation : Payoff ι) :
    Set (Payoff ι) :=
  {current | current ∈ W ∧ ∃ root : ι → PMF Bool,
    oneShotPerfectEpsilonEquilibrium reward continuation
      (rho reward * ε) root ∧
    ε ≤ oneShotTerminationProbability root ∧
    oneShotExpectedPayoff reward continuation root = current}

/-- **Proposition 2.2.** Under A.1, if every `w ∈ W` has an equilibrium
which is either all-Continue or has a positive-probability quitter receiving
at most `1`, then `ψ` has nonempty values for all sufficiently small
positive `ε`. -/
def Proposition2_2 : Prop :=
  ∀ (reward : {S : Finset ι // S.Nonempty} → Payoff ι),
    QuittingUnitSoloExit reward →
    (∀ value ∈ W reward, ∃ root : ι → PMF Bool,
      IsεQuittingRootNash reward value 0 root ∧
        (root = quittingAllContinueRoot ∨
          ∃ who, (root who false).toReal < 1 ∧
            oneShotExpectedPayoff reward value root who ≤ 1)) →
    ∃ ε₀ : ℝ, 0 < ε₀ ∧ ∀ ε : ℝ, 0 < ε → ε < ε₀ →
      ∀ value ∈ W reward,
        (oneShotCorrespondence reward (W reward) ε value).Nonempty

theorem proposition2_2 : Proposition2_2 (ι := ι) := by
  classical
  intro reward hunit hexact
  refine ⟨1, by norm_num, ?_⟩
  intro ε hε0 hε1 value hvalue
  obtain ⟨base, hbaseNash, hbaseShape⟩ := hexact value hvalue
  have hbaseEndpoint :
      IsεQuittingRootEndpointNash reward value 0 base :=
    (isZeroQuittingRootEndpointNash_iff_isZeroQuittingRootNash
      reward value base).2 hbaseNash
  obtain ⟨chosen, hchosen, hbaseLow⟩ : ∃ chosen : ι,
      ((base chosen true).toReal = 1 ∨
        quittingRootQuitPayoff reward value base chosen =
          quittingRootContinuePayoff reward value base chosen) ∧
      oneShotExpectedPayoff reward value base chosen ≤ 1 := by
    rcases hbaseShape with hcontinue | ⟨chosen, hcontinueLt, hlow⟩
    · obtain ⟨chosen, hlow⟩ := hvalue.2
      refine ⟨chosen, Or.inr ?_, ?_⟩
      · have hquitLe :=
          quittingRootQuitPayoff_le_successorPayoff_of_isZeroEndpointNash
            hbaseEndpoint chosen
        rw [hcontinue, quittingRootQuitPayoff_allContinueRoot,
          quittingRootSuccessorPayoff_allContinueRoot_eq] at hquitLe
        have hsolo : reward (quittingSingletonTerminal chosen) chosen = 1 :=
          hunit chosen
        rw [hcontinue, quittingRootQuitPayoff_allContinueRoot,
          quittingRootContinuePayoff_allContinueRoot, hsolo]
        linarith
      · rwa [hcontinue, oneShotExpectedPayoff,
          quittingRootSuccessorPayoff_allContinueRoot_eq]
    · have hsum :=
          quittingRoot_continueProbability_add_quitProbability base chosen
      have hquitPos : 0 < (base chosen true).toReal := by linarith
      have hquitNe : base chosen true ≠ 0 :=
        ENNReal.toReal_ne_zero.mp (ne_of_gt hquitPos) |>.1
      by_cases hcontinueZero : (base chosen false).toReal = 0
      · refine ⟨chosen, Or.inl ?_, hlow⟩
        linarith
      · refine ⟨chosen, Or.inr ?_, hlow⟩
        have hcontinuePos : 0 < (base chosen false).toReal :=
          lt_of_le_of_ne ENNReal.toReal_nonneg (Ne.symm hcontinueZero)
        have hcontinueNe : base chosen false ≠ 0 :=
          ENNReal.toReal_ne_zero.mp (ne_of_gt hcontinuePos) |>.1
        have hquitEq :=
          quittingRootSuccessorPayoff_eq_quitPayoff_of_isZeroEndpointNash
            hbaseEndpoint chosen hquitNe
        have hcontinueEq :=
          quittingRootSuccessorPayoff_eq_continuePayoff_of_isZeroEndpointNash
            hbaseEndpoint chosen hcontinueNe
        exact hquitEq.symm.trans hcontinueEq
  set q := (base chosen true).toReal with hqdef
  have hq0 : 0 ≤ q := ENNReal.toReal_nonneg
  have hq1 : q ≤ 1 := by
    have hle := ENNReal.toReal_mono ENNReal.one_ne_top
      ((base chosen).coe_le_one true)
    simpa using hle
  set q' := ε + (1 - ε) * q with hq'def
  have hq'0 : 0 ≤ q' := by nlinarith
  have hq'1 : q' ≤ 1 := by nlinarith
  have hεq' : ε ≤ q' := by nlinarith
  set coin := quittingHazardCoin q' hq'0 hq'1 with hcoindef
  set perturbed := Function.update base chosen coin with hperturbed
  have hcoinTrue : (coin true).toReal = q' := by
    rw [hcoindef, quittingHazardCoin_true_toReal]
  have hcoinFalse : (coin false).toReal = 1 - q' := by
    rw [hcoindef, quittingHazardCoin_false_toReal]
  have hperturbedChosen : perturbed chosen = coin := by
    rw [hperturbed, Function.update_self]
  have hperturbedOther : ∀ who, who ≠ chosen → perturbed who = base who := by
    intro who hne
    rw [hperturbed, Function.update_of_ne hne]
  have hchosenEndpoints :
      quittingRootQuitPayoff reward value perturbed chosen =
          quittingRootQuitPayoff reward value base chosen ∧
        quittingRootContinuePayoff reward value perturbed chosen =
          quittingRootContinuePayoff reward value base chosen := by
    constructor
    · unfold quittingRootQuitPayoff
      rw [hperturbed, Function.update_idem]
    · unfold quittingRootContinuePayoff
      rw [hperturbed, Function.update_idem]
  have hcurrentLow :
      oneShotExpectedPayoff reward value perturbed chosen ≤ 1 := by
    rw [oneShotExpectedPayoff,
      quittingRootSuccessorPayoff_eq_endpointMix, hperturbedChosen,
      hcoinTrue, hcoinFalse, hchosenEndpoints.1, hchosenEndpoints.2]
    rcases hchosen with hpure | hindifferent
    · have hqOne : q = 1 := hqdef.symm.trans hpure
      have hq'One : q' = 1 := by rw [hq'def, hqOne]; ring
      rw [hq'One]
      have hquitEq :=
        quittingRootSuccessorPayoff_eq_quitPayoff_of_isZeroEndpointNash
          hbaseEndpoint chosen
          (ENNReal.toReal_ne_zero.mp (by rw [← hqdef, hpure]; norm_num) |>.1)
      norm_num
      rw [← hquitEq]
      exact hbaseLow
    · rw [hindifferent]
      have hbaseEq : oneShotExpectedPayoff reward value base chosen =
          quittingRootContinuePayoff reward value base chosen := by
        rw [oneShotExpectedPayoff,
          quittingRootSuccessorPayoff_eq_endpointMix, hindifferent]
        have hsum :=
          quittingRoot_continueProbability_add_quitProbability base chosen
        calc
          (base chosen true).toReal *
                quittingRootContinuePayoff reward value base chosen +
              (base chosen false).toReal *
                quittingRootContinuePayoff reward value base chosen =
            ((base chosen false).toReal + (base chosen true).toReal) *
              quittingRootContinuePayoff reward value base chosen := by ring
          _ = quittingRootContinuePayoff reward value base chosen := by
            rw [hsum, one_mul]
      calc
        q' * quittingRootContinuePayoff reward value base chosen +
            (1 - q') * quittingRootContinuePayoff reward value base chosen =
          quittingRootContinuePayoff reward value base chosen := by ring
        _ = oneShotExpectedPayoff reward value base chosen := hbaseEq.symm
        _ ≤ 1 := hbaseLow
  have hendpointAffine : ∀ (who : ι), who ≠ chosen → ∀ action : Bool,
      quittingRootExpectedPayoff reward value
          (Function.update perturbed who (PMF.pure action)) who =
        ε * quittingRootExpectedPayoff reward value
            (Function.update (Function.update base who (PMF.pure action))
              chosen (PMF.pure true)) who +
          (1 - ε) * quittingRootExpectedPayoff reward value
            (Function.update base who (PMF.pure action)) who := by
    intro who hne action
    have hcomm : Function.update perturbed who (PMF.pure action) =
        Function.update (Function.update base who (PMF.pure action)) chosen coin := by
      rw [hperturbed]
      exact Function.update_comm (Ne.symm hne) coin (PMF.pure action) base
    have hbaseChosen :
        Function.update base who (PMF.pure action) chosen = base chosen :=
      Function.update_of_ne (Ne.symm hne) (PMF.pure action) base
    have hbaseMix :=
      quittingRootExpectedPayoff_update_coord_eq_mix reward value
        (Function.update base who (PMF.pure action)) chosen (base chosen) who
    have hreplace :
        Function.update (Function.update base who (PMF.pure action)) chosen
            (base chosen) =
          Function.update base who (PMF.pure action) := by
      funext player
      by_cases hplayer : player = chosen
      · subst player
        rw [Function.update_self, hbaseChosen]
      · rw [Function.update_of_ne hplayer]
    rw [hreplace] at hbaseMix
    rw [hcomm,
      quittingRootExpectedPayoff_update_coord_eq_mix reward value
        (Function.update base who (PMF.pure action)) chosen coin who,
      hbaseMix, hcoinTrue, hcoinFalse]
    have hbaseFalse : (base chosen false).toReal = 1 - q := by
      have hsum :=
        quittingRoot_continueProbability_add_quitProbability base chosen
      rw [← hqdef] at hsum
      linarith
    rw [← hqdef, hbaseFalse, hq'def]
    ring
  have hsureBound : ∀ (who : ι) (action : Bool),
      |quittingRootExpectedPayoff reward value
          (Function.update (Function.update base who (PMF.pure action))
            chosen (PMF.pure true)) who| ≤ quittingRewardBound reward := by
    intro who action
    let forced := Function.update (Function.update base who (PMF.pure action))
      chosen (PMF.pure true)
    have hsure : QuittingRootHasSureQuitter forced :=
      quittingRootHasSureQuitter_update_pure_true
        (Function.update base who (PMF.pure action)) chosen
    rw [quittingRootExpectedPayoff_eq_of_hasSureQuitter reward forced hsure
      value (0 : Payoff ι) who]
    exact abs_quittingRootExpectedPayoff_le_bound reward (0 : Payoff ι)
      forced who (abs_reward_le_quittingRewardBound reward) (by
        intro player
        simpa using quittingRewardBound_nonneg reward)
  have hperfect : oneShotPerfectEpsilonEquilibrium reward value
      (rho reward * ε) perturbed := by
    intro who action hsupport alternative
    by_cases hwho : who = chosen
    · subst hwho
      rw [hperturbed, Function.update_idem, Function.update_idem]
      rcases hchosen with hpure | hindifferent
      · have hqOne : q = 1 := hqdef.symm.trans hpure
        have hq'One : q' = 1 := by rw [hq'def, hqOne]; ring
        have hcoinPure : coin = PMF.pure true := by
          ext observed
          cases observed <;>
            simp [hcoindef, quittingHazardCoin, PMF.ofFintype_apply, hq'One]
        rw [hperturbedChosen, hcoinPure] at hsupport
        have haction : action = true :=
          (PMF.mem_support_pure_iff true action).mp hsupport
        subst haction
        have hbaseQuit : base who true ≠ 0 :=
          ENNReal.toReal_ne_zero.mp (by rw [← hqdef, hpure]; norm_num) |>.1
        have hquitEq :=
          quittingRootSuccessorPayoff_eq_quitPayoff_of_isZeroEndpointNash
            hbaseEndpoint who hbaseQuit
        have hdeviation := hbaseNash who (PMF.pure alternative)
        have htol : 0 ≤ rho reward * ε :=
          mul_nonneg (mul_nonneg (by norm_num)
            (quittingRewardBound_nonneg reward)) hε0.le
        calc
          quittingRootExpectedPayoff reward value
              (Function.update base who (PMF.pure alternative)) who ≤
            quittingRootSuccessorPayoff reward value base who := by
              change quittingRootExpectedPayoff reward value
                (Function.update base who (PMF.pure alternative)) who ≤
                  quittingRootExpectedPayoff reward value base who
              linarith
          _ = quittingRootExpectedPayoff reward value
              (Function.update base who (PMF.pure true)) who := hquitEq
          _ ≤ _ + rho reward * ε := le_add_of_nonneg_right htol
      · have hactionsEq : ∀ first second : Bool,
            quittingRootExpectedPayoff reward value
                (Function.update base who (PMF.pure first)) who =
              quittingRootExpectedPayoff reward value
                (Function.update base who (PMF.pure second)) who := by
          intro first second
          cases first <;> cases second
          · rfl
          · exact hindifferent.symm
          · exact hindifferent
          · rfl
        rw [hactionsEq alternative action]
        exact le_add_of_nonneg_right
          (mul_nonneg (mul_nonneg (by norm_num)
            (quittingRewardBound_nonneg reward)) hε0.le)
    · rw [hperturbedOther who hwho] at hsupport
      rw [hendpointAffine who hwho alternative,
        hendpointAffine who hwho action]
      have hbase := hbaseNash who (PMF.pure alternative)
      have hsupportedEq :
          quittingRootExpectedPayoff reward value
              (Function.update base who (PMF.pure action)) who =
            quittingRootExpectedPayoff reward value base who := by
        cases action
        · exact
            (quittingRootSuccessorPayoff_eq_continuePayoff_of_isZeroEndpointNash
              hbaseEndpoint who hsupport).symm
        · exact
            (quittingRootSuccessorPayoff_eq_quitPayoff_of_isZeroEndpointNash
              hbaseEndpoint who hsupport).symm
      rw [hsupportedEq] at *
      have haltBound := hsureBound who alternative
      have hactBound := hsureBound who action
      have halt := abs_le.mp haltBound
      have hact := abs_le.mp hactBound
      rw [rho]
      nlinarith [hbase]
  refine ⟨oneShotExpectedPayoff reward value perturbed, ?_, perturbed,
    hperfect, ?_, rfl⟩
  · constructor
    · intro who
      exact (abs_quittingRootExpectedPayoff_le_bound reward value perturbed who
        (fun terminal player ↦
          (abs_reward_le_quittingRewardBound reward terminal player).trans
            (by unfold rho; nlinarith [quittingRewardBound_nonneg reward]))
        hvalue.1)
    · exact ⟨chosen, hcurrentLow⟩
  · have hmassLe : quittingStationaryContinueMass perturbed ≤
        (perturbed chosen false).toReal :=
      quittingStationaryContinueMass_le_ownContinueProbability perturbed chosen
    unfold oneShotTerminationProbability quittingRootAbsorptionMass
    rw [hperturbedChosen, hcoinFalse] at hmassLe
    linarith

/-- **Proposition 2.3.** If `ψ` has nonempty values on a compact `W`, there
is a cyclic profile whose every tail terminates and whose rows are perfect
`(ρ+2)ε`-equilibria against their actual next-tail values. -/
def Proposition2_3 : Prop :=
  ∀ (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (W : Set (Payoff ι)) (ε : ℝ),
    0 < ε → W.Nonempty → IsCompact W →
    (∀ value ∈ W,
      (oneShotCorrespondence reward W ε value).Nonempty) →
      ∃ roots : RootSequence (ι := ι),
        cyclicRootSequence roots ∧
        (∀ start, terminating reward roots start) ∧
        ∀ start, oneShotPerfectEpsilonEquilibrium reward
          (quittingRootSequenceTailVector reward roots (start + 1))
          ((rho reward + 2) * ε) (roots start)

/-- Moving the continuation vector coordinatewise by at most `c` widens the
paper's support-perfect tolerance by at most `2c`: both compared pure-action
payoffs are `1`-Lipschitz in that player's continuation coordinate. -/
private theorem oneShotPerfectEpsilonEquilibrium_of_continuation_close
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    {first second : Payoff ι} {ε c : ℝ} {root : ι → PMF Bool}
    (hperfect : oneShotPerfectEpsilonEquilibrium reward first ε root)
    (hc : 0 ≤ c) (hclose : ∀ who, |first who - second who| ≤ c) :
    oneShotPerfectEpsilonEquilibrium reward second (ε + 2 * c) root := by
  intro who action hsupport alternative
  have hfirst := hperfect who action hsupport alternative
  have halt := abs_quittingRootExpectedPayoff_sub_of_tail_close reward
    second first (Function.update root who (PMF.pure alternative)) who hc
    (by rw [abs_sub_comm]; exact hclose who)
  have hact := abs_quittingRootExpectedPayoff_sub_of_tail_close reward
    second first (Function.update root who (PMF.pure action)) who hc
    (by rw [abs_sub_comm]; exact hclose who)
  have haltBounds := abs_le.mp halt
  have hactBounds := abs_le.mp hact
  linarith

theorem proposition2_3 : Proposition2_3 (ι := ι) := by
  classical
  intro reward carrier ε hε hcarrierNonempty hcarrierCompact hcorrespondence
  -- Nonemptiness of the correspondence forces the advertised absorption
  -- floor to lie in the probability interval.
  obtain ⟨anchor, hanchor⟩ := hcarrierNonempty
  obtain ⟨anchorCurrent, -, anchorRoot, -, hanchorFloor, -⟩ :=
    hcorrespondence anchor hanchor
  have hε1 : ε ≤ 1 := by
    have hmass0 := quittingStationaryContinueMass_nonneg anchorRoot
    unfold oneShotTerminationProbability quittingRootAbsorptionMass at hanchorFloor
    linarith
  set η := ε ^ 2 with hηdef
  have hη0 : 0 < η := by positivity
  -- Choose a correspondence root at every carrier point.
  have hrowExists : ∀ tail : Payoff ι, ∃ root : ι → PMF Bool,
      tail ∈ carrier →
        oneShotPerfectEpsilonEquilibrium reward tail (rho reward * ε) root ∧
          ε ≤ quittingRootAbsorptionMass root ∧
          quittingRootSuccessorPayoff reward tail root ∈ carrier := by
    intro tail
    by_cases htail : tail ∈ carrier
    · obtain ⟨current, hcurrent, root, hperfect, hfloor, hvalue⟩ :=
        hcorrespondence tail htail
      refine ⟨root, fun _ ↦ ⟨hperfect, hfloor, ?_⟩⟩
      change oneShotExpectedPayoff reward tail root ∈ carrier
      rw [hvalue]
      exact hcurrent
    · exact ⟨fun _ ↦ PMF.pure false, fun hcontra ↦ absurd hcontra htail⟩
  choose rowOf hrowOf using hrowExists
  -- Give every mesh key a representative carrier point whenever that key
  -- is realized; unrealized keys use one harmless anchor.
  have hrepExists : ∀ key : ι → ℤ, ∃ tail : Payoff ι,
      tail ∈ carrier ∧
        ((∃ tail' ∈ carrier, ∀ who, ⌊tail' who / η⌋ = key who) →
          ∀ who, ⌊tail who / η⌋ = key who) := by
    intro key
    by_cases hkey : ∃ tail' ∈ carrier, ∀ who, ⌊tail' who / η⌋ = key who
    · obtain ⟨tail, htail, htailKey⟩ := hkey
      exact ⟨tail, htail, fun _ ↦ htailKey⟩
    · exact ⟨anchor, hanchor, fun hcontra ↦ absurd hcontra hkey⟩
  choose rep hrepCarrier hrepKey using hrepExists
  -- Compactness supplies a common coordinate bound, hence only finitely
  -- many mesh keys can be produced.
  obtain ⟨radius, hradius⟩ :=
    hcarrierCompact.isBounded.subset_closedBall (0 : Payoff ι)
  set R := max (quittingRewardBound reward) (max 0 radius) with hRdef
  have hR0 : 0 ≤ R := le_trans (le_max_left 0 radius)
    (le_max_right (quittingRewardBound reward) (max 0 radius))
  have hcarrierBound : ∀ tail ∈ carrier, ∀ who, |tail who| ≤ R := by
    intro tail htail who
    have hnorm : ‖tail‖ ≤ radius :=
      mem_closedBall_zero_iff.mp (hradius htail)
    have hcoordinate : |tail who| ≤ ‖tail‖ := by
      rw [← Real.norm_eq_abs, Pi.norm_def]
      exact_mod_cast Finset.le_sup (f := fun player ↦ ‖tail player‖₊)
        (Finset.mem_univ who)
    exact hcoordinate.trans (hnorm.trans
      (le_trans (le_max_right 0 radius)
        (le_max_right (quittingRewardBound reward) (max 0 radius))))
  set dynamics : (ι → ℤ) → (ι → ℤ) := fun key who ↦
    ⌊quittingRootSuccessorPayoff reward (rep key) (rowOf (rep key)) who / η⌋
    with hdynamics
  have hdynamicsBound : ∀ key who,
      |quittingRootSuccessorPayoff reward (rep key) (rowOf (rep key)) who| ≤
        R := by
    intro key who
    exact hcarrierBound _
      ((hrowOf (rep key) (hrepCarrier key)).2.2) who
  have hdynamicsRange : ∀ key, dynamics key ∈
      {boundedKey : ι → ℤ |
        ∀ who, boundedKey who ∈ Set.Icc ⌊(-R) / η⌋ ⌊R / η⌋} := by
    intro key who
    obtain ⟨hlower, hupper⟩ := abs_le.mp (hdynamicsBound key who)
    constructor
    · exact Int.floor_le_floor (by gcongr)
    · exact Int.floor_le_floor (by gcongr)
  have hkeyRangeFinite :
      ({boundedKey : ι → ℤ |
        ∀ who, boundedKey who ∈ Set.Icc ⌊(-R) / η⌋ ⌊R / η⌋}).Finite := by
    apply Set.Finite.subset
      (Set.Finite.pi fun _ : ι ↦ Set.finite_Icc ⌊(-R) / η⌋ ⌊R / η⌋)
    intro key hkey
    rw [Set.mem_pi]
    exact fun who _ ↦ hkey who
  obtain ⟨period, keyChain, hperiod, hkeyPeriodic, hkeyChain⟩ :=
    Math.exists_periodic_backward_orbit dynamics (fun _ ↦ 0)
      hkeyRangeFinite hdynamicsRange
  set plan : ℕ → Payoff ι := fun n ↦ rep (keyChain n) with hplan
  set roots : RootSequence (ι := ι) :=
    fun n ↦ rowOf (plan (n + 1)) with hroots
  have hplanCarrier : ∀ n, plan n ∈ carrier :=
    fun n ↦ hrepCarrier (keyChain n)
  have hrowSpec : ∀ n,
      oneShotPerfectEpsilonEquilibrium reward (plan (n + 1))
          (rho reward * ε) (roots n) ∧
        ε ≤ quittingRootAbsorptionMass (roots n) ∧
        quittingRootSuccessorPayoff reward (plan (n + 1)) (roots n) ∈
          carrier :=
    fun n ↦ hrowOf (plan (n + 1)) (hplanCarrier (n + 1))
  have hvalueKey : ∀ n who,
      ⌊quittingRootSuccessorPayoff reward (plan (n + 1))
          (roots n) who / η⌋ = keyChain n who := by
    intro n who
    have h := congrFun (hkeyChain n) who
    rw [hdynamics] at h
    rw [hroots, hplan]
    exact h.symm
  have hplanKey : ∀ n who, ⌊plan n who / η⌋ = keyChain n who := by
    intro n who
    apply hrepKey (keyChain n)
    exact ⟨quittingRootSuccessorPayoff reward (plan (n + 1)) (roots n),
      (hrowSpec n).2.2, hvalueKey n⟩
  have hclose : ∀ n who,
      |plan n who -
        quittingRootSuccessorPayoff reward (plan (n + 1)) (roots n) who| ≤
        η := by
    intro n who
    exact Math.abs_sub_le_of_floor_div_eq hη0
      ((hplanKey n who).trans (hvalueKey n who).symm)
  have hmass : ∀ n,
      quittingStationaryContinueMass (roots n) ≤ 1 - ε := by
    intro n
    have hfloor := (hrowSpec n).2.1
    unfold quittingRootAbsorptionMass at hfloor
    linarith
  have hrewardBound : ∀ terminal player, |reward terminal player| ≤ R := by
    intro terminal player
    exact (abs_reward_le_quittingRewardBound reward terminal player).trans
      (le_max_left _ _)
  have hplanBound : ∀ n who, |plan n who| ≤ R :=
    fun n who ↦ hcarrierBound (plan n) (hplanCarrier n) who
  have hcontraction :=
    abs_terminalValue_sub_successor_le_of_approximate_chain_sharp reward
      roots plan hR0 hε hε1 hη0.le hrewardBound hplanBound hmass hclose
  have hrootsPeriodic : ∀ n, roots (n + period) = roots n := by
    intro n
    simp only [hroots, hplan]
    rw [show n + period + 1 = (n + 1) + period by omega,
      hkeyPeriodic (n + 1)]
  refine ⟨roots, ⟨period, hperiod, hrootsPeriodic⟩, ?_, ?_⟩
  · intro start
    unfold terminating tailProfile
    rw [quittingLiveMassLimit_rootSequence_eq_jointSurvivalLimit]
    apply quittingJointSurvivalLimit_eq_zero_of_periodic roots
      hrootsPeriodic (date := 0) (Nat.zero_lt_of_lt hperiod)
    have hfloor := (hrowSpec start).2.1
    unfold quittingRootAbsorptionMass at hfloor
    simpa using (show quittingStationaryContinueMass (roots start) < 1 by
      linarith)
  · intro start
    have hplanActual : ∀ who,
        |plan (start + 1) who -
          quittingRootSequenceTailVector reward roots (start + 1) who| ≤ ε := by
      intro who
      have hstepClose := hclose (start + 1) who
      have hstepContraction := hcontraction (start + 1) who
      rw [abs_sub_comm] at hstepContraction
      calc
        |plan (start + 1) who -
            quittingRootSequenceTailVector reward roots (start + 1) who| ≤
          |plan (start + 1) who -
              quittingRootSuccessorPayoff reward (plan (start + 2))
                (roots (start + 1)) who| +
            |quittingRootSuccessorPayoff reward (plan (start + 2))
                (roots (start + 1)) who -
              quittingRootSequenceTailVector reward roots (start + 1) who| :=
          abs_sub_le _ _ _
        _ ≤ η + (1 - ε) * η / ε :=
          add_le_add hstepClose hstepContraction
        _ = ε := by
          rw [hηdef]
          field_simp [hε.ne']
          ring
    have htransfer :=
      oneShotPerfectEpsilonEquilibrium_of_continuation_close
        (hrowSpec start).1 hε.le hplanActual
    convert htransfer using 1
    ring

/-- **Proposition 2.4.** Under A.1 and for sufficiently small `ε`, a profile
with terminating tails and rows that are perfect `ε`-equilibria against the
actual next-tail values is either a subgame-perfect `ε^(1/6)`-equilibrium or
yields a stationary `ε^(1/6)`-equilibrium. -/
def Proposition2_4 : Prop :=
  ∀ (reward : {S : Finset ι // S.Nonempty} → Payoff ι),
    QuittingUnitSoloExit reward →
    ∃ ε₀ : ℝ, 0 < ε₀ ∧
      ∀ (roots : RootSequence (ι := ι)) (ε : ℝ),
        0 < ε → ε < ε₀ →
        (∀ start, terminating reward roots start) →
        (∀ start, oneShotPerfectEpsilonEquilibrium reward
          (quittingRootSequenceTailVector reward roots (start + 1))
          ε (roots start)) →
          subgamePerfectEpsilonEquilibrium reward roots
              (ε ^ (1 / 6 : ℝ)) ∨
            ∃ root : ι → PMF Bool,
              epsilonEquilibrium reward (ε ^ (1 / 6 : ℝ))
                (stationaryProfile reward root)

theorem proposition2_4 : Proposition2_4 (ι := ι) := by
  sorry

/-! ### 2.4. The correspondence lemma and noncyclic construction -/

/-- Upper semicontinuity in the paper's neighborhood formulation. -/
def upperSemicontinuous {α : Type*} [TopologicalSpace α]
    (K : Set α) (ψ : α → Set α) : Prop :=
  ∀ x ∈ K, ∀ U : Set α, IsOpen U → ψ x ⊆ U →
    ∃ V : Set α, IsOpen V ∧ x ∈ V ∧ ∀ y ∈ V ∩ K, ψ y ⊆ U

/-- **Lemma 2.5.** A nonempty compact-valued upper-semicontinuous
correspondence `φ : K → K` on a nonempty compact Hausdorff space admits an
inverse iterative chain `k_i ∈ φ(k_{i+1})`.

The paper works with a compact subset of Euclidean space and calls `φ` a
correspondence.  We expose the otherwise implicit Hausdorff and closed-value
hypotheses: without closed values, upper semicontinuity in the displayed
neighborhood formulation does not provide the closed graph used by the
compact inverse-limit argument. -/
def Lemma2_5 : Prop :=
  ∀ (α : Type*) [TopologicalSpace α] [T2Space α] (K : Set α),
    K.Nonempty → IsCompact K →
    ∀ ψ : α → Set α,
      (∀ x ∈ K, (ψ x).Nonempty ∧ ψ x ⊆ K) →
      (∀ x ∈ K, IsClosed (ψ x)) →
      upperSemicontinuous K ψ →
        ∃ sequence : ℕ → α,
          (∀ i, sequence i ∈ K) ∧
          ∀ i, sequence i ∈ ψ (sequence (i + 1))

theorem lemma2_5 : Lemma2_5 := by
  intro α _ _ K hKnonempty hKcompact ψ hψnonempty hψclosed hψusc
  let relation : α → α → Prop := fun current tail ↦ current ∈ ψ tail
  have hgraph : IsClosed
      {pair : α × α |
        pair.1 ∈ K ∧ pair.2 ∈ K ∧ relation pair.1 pair.2} := by
    rw [← isOpen_compl_iff]
    apply isOpen_iff_forall_mem_open.mpr
    rintro ⟨current, tail⟩ houtside
    by_cases hcurrentK : current ∈ K
    · by_cases htailK : tail ∈ K
      · have hedge : current ∉ ψ tail := by
          intro hedge
          exact houtside ⟨hcurrentK, htailK, hedge⟩
        have hψcompact : IsCompact (ψ tail) :=
          hKcompact.of_isClosed_subset (hψclosed tail htailK)
            (hψnonempty tail htailK).2
        obtain ⟨imageNhd, currentNhd, himageOpen, hcurrentOpen,
            himage, hcurrent, hdisjoint⟩ :=
          hψcompact.separation_of_notMem hedge
        obtain ⟨tailNhd, htailOpen, htailMem, hnearby⟩ :=
          hψusc tail htailK imageNhd himageOpen himage
        refine ⟨currentNhd ×ˢ tailNhd, ?_,
          hcurrentOpen.prod htailOpen, ⟨hcurrent, htailMem⟩⟩
        rintro ⟨current', tail'⟩ ⟨hcurrent', htail'⟩
        simp only [Set.mem_compl_iff, Set.mem_setOf_eq]
        rintro ⟨_, htailK', hrelation⟩
        exact Set.disjoint_left.1 hdisjoint
          (hnearby tail' ⟨htail', htailK'⟩ hrelation) hcurrent'
      · refine ⟨Set.univ ×ˢ Kᶜ, ?_,
          isOpen_univ.prod hKcompact.isClosed.isOpen_compl,
          ⟨Set.mem_univ current, htailK⟩⟩
        rintro ⟨current', tail'⟩ ⟨_, htail'⟩
        simp only [Set.mem_compl_iff, Set.mem_setOf_eq]
        exact fun h ↦ htail' h.2.1
    · refine ⟨Kᶜ ×ˢ Set.univ, ?_,
        hKcompact.isClosed.isOpen_compl.prod isOpen_univ,
        ⟨hcurrentK, Set.mem_univ tail⟩⟩
      rintro ⟨current', tail'⟩ ⟨hcurrent', _⟩
      simp only [Set.mem_compl_iff, Set.mem_setOf_eq]
      exact fun h ↦ hcurrent' h.1
  let system : Math.Topology.CompactSerialRelation α := {
    box := K
    relation := relation
    box_nonempty := hKnonempty
    box_compact := hKcompact
    relationGraph_closed := hgraph
    predecessor_exists := fun tail htail ↦
      ⟨Classical.choose (hψnonempty tail htail).1,
        (hψnonempty tail htail).2
          (Classical.choose_spec (hψnonempty tail htail).1),
        Classical.choose_spec (hψnonempty tail htail).1⟩ }
  simpa only [system, relation] using system.exists_infiniteChain

/-- The two-player terminal table in Example 2. Player 1 gets `2` only when
Player 2 quits alone; every other terminal coordinate is `1`. -/
def example2Reward
    (terminal : {S : Finset (Fin 2) // S.Nonempty}) : Payoff (Fin 2) :=
  fun who => if who = 0 ∧ terminal.1 = {1} then 2 else 1

/-- The profile of Example 2: Player 1 continues with probability `1-η`,
while Player 2 continues at paper stage `n+1` with probability
`1-ε/2^(n+1)`. -/
def example2ProfileCondition
    (roots : RootSequence (ι := Fin 2)) (ε η : ℝ) : Prop :=
  ∀ n,
    (roots n 0 false).toReal = 1 - η ∧
    (roots n 1 false).toReal = 1 - ε / (2 : ℝ) ^ (n + 1)

/-- A cyclic sequence formed by repeating finitely many stages of another
root sequence. -/
def repeatsFiniteStageSelection
    (source repeated : RootSequence (ι := ι)) : Prop :=
  cyclicRootSequence repeated ∧
    ∀ time, ∃ sourceTime, repeated time = source sourceTime

/-- **Example 2.** For `η > ε`, the displayed profile is subgame-perfect
`ε`, but no cyclic repetition of finitely many of its stages is a
`1/2`-equilibrium. -/
def Example2Claim : Prop :=
  ∀ ε η : ℝ, 0 < ε → ε < η → η < 1 →
    ∀ roots : RootSequence (ι := Fin 2),
      example2ProfileCondition roots ε η →
      subgamePerfectEpsilonEquilibrium example2Reward roots ε ∧
      ∀ repeated : RootSequence (ι := Fin 2),
        repeatsFiniteStageSelection roots repeated →
        ¬ epsilonEquilibrium example2Reward (1 / 2)
          (profile example2Reward repeated)

theorem example2 : Example2Claim := by
  sorry

/-! ### 2.5. Proof of the main proposition -/

/-- **Proposition 2.6.** The paper restates Proposition 2.4 before its block
proof. -/
def Proposition2_6 : Prop := Proposition2_4 (ι := ι)

theorem proposition2_6 : Proposition2_6 (ι := ι) := by
  exact proposition2_4

/-! **Facts 1--3 (paper).** If `u` is bounded in absolute value by `ρ`, then
`|𝔼[u]| ≤ ρ ℙ(Aᶜ) + supₐ∈ᴬ |u(a)|`. For every profile `y` and stage
`n`, its payoff decomposes into absorption before `n` and the surviving
tail payoff. Finally, the payoff from forcing player `i` to Quit is
independent of the one-shot continuation vector `w` and equals the quitting-
game payoff of that pure deviation. -/

/-- The probability that some opponent of `who` quits in a block. -/
def opponentBlockTerminationProbability
    (roots : RootSequence (ι := ι)) (who : ι)
    (start length : ℕ) : ℝ :=
  1 - ∏ time ∈ Finset.range length,
    (1 - quittingRootOpponentAbsorptionMass (roots (start + time)) who)

/-- **Definition 2.7.** A block is Type I for player `i` when the probability
that another player quits in it is at least `ε^b`; otherwise it is Type II. -/
def blockTypeI
    (roots : RootSequence (ι := ι)) (who : ι)
    (start length : ℕ) (ε b : ℝ) : Prop :=
  ε ^ b ≤ opponentBlockTerminationProbability roots who start length

/-- Probability of absorption in a finite block under the prescribed
profile. -/
def blockTerminationProbability
    (roots : RootSequence (ι := ι)) (start length : ℕ) : ℝ :=
  1 - quittingJointSurvivalWeight roots start length

/-- Probability that the first absorption in a block occurs while `who`
continues, so that some opponent is in the quitting coalition. -/
def opponentFirstAbsorptionProbability
    (roots : RootSequence (ι := ι)) (who : ι)
    (start length : ℕ) : ℝ :=
  ∑ time ∈ Finset.range length,
    quittingJointSurvivalWeight roots start time *
      (roots (start + time) who false).toReal *
        quittingRootOpponentAbsorptionMass (roots (start + time)) who

/-- Probability that the first absorption in a block contains `who`. -/
def ownerFirstAbsorptionProbability
    (roots : RootSequence (ι := ι)) (who : ι)
    (start length : ℕ) : ℝ :=
  ∑ time ∈ Finset.range length,
    quittingJointSurvivalWeight roots start time *
      (roots (start + time) who true).toReal

/-- Conditional payoff when the first absorption in the block contains
`who`. This is the paper's `u₁`. -/
def ownerConditionalBlockPayoff
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : RootSequence (ι := ι)) (who : ι)
    (start length : ℕ) : ℝ :=
  (∑ time ∈ Finset.range length,
      quittingJointSurvivalWeight roots start time *
        (roots (start + time) who true).toReal *
          quittingRootQuitPayoff reward 0 (roots (start + time)) who) /
    ownerFirstAbsorptionProbability roots who start length

/-- Conditional payoff when an opponent causes the first absorption in the
block under the prescribed profile. This is `u₂`. -/
def opponentConditionalBlockPayoff
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : RootSequence (ι := ι)) (who : ι)
    (start length : ℕ) : ℝ :=
  (∑ time ∈ Finset.range length,
      quittingJointSurvivalWeight roots start time *
        (roots (start + time) who false).toReal *
          quittingRootAbsorbingContribution reward
            (Function.update (roots (start + time)) who (PMF.pure false)) who) /
    opponentFirstAbsorptionProbability roots who start length

/-- The opponent-absorption conditional payoff after forcing `who` to
Continue. This is the paper's `u₂*`. -/
def forcedContinueOpponentConditionalBlockPayoff
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : RootSequence (ι := ι)) (who : ι)
    (start length : ℕ) : ℝ :=
  let forced := fun time =>
    Function.update (roots time) who (PMF.pure false)
  (∑ time ∈ Finset.range length,
      quittingJointSurvivalWeight forced start time *
        quittingRootAbsorbingContribution reward
          (forced (start + time)) who) /
    opponentBlockTerminationProbability roots who start length

/-- The roots obtained when `who` continues until `cutoff` and then resumes
the prescribed profile. -/
def continueUntilRoots
    (roots : RootSequence (ι := ι)) (who : ι) (cutoff : ℕ) :
    RootSequence (ι := ι) :=
  fun time => if time < cutoff then
    Function.update (roots time) who (PMF.pure false)
  else roots time

/-- The actual proof context of Lemmas 2.8--2.12 in the regularly-scattered
case. It retains the paper's root sequence, block endpoints, pure deviation,
and all enclosing hypotheses instead of treating `π₂`, `u₂`, and `X_k` as
unconstrained real variables. -/
structure MainEstimateContext (ι : Type) [Fintype ι] [DecidableEq ι] where
  reward : {S : Finset ι // S.Nonempty} → Payoff ι
  roots : RootSequence (ι := ι)
  who : ι
  ε : ℝ
  ρ : ℝ
  a : ℝ
  b : ℝ
  exponent : ℝ
  localStart : ℕ
  localLength : ℕ
  blockStart : ℕ → ℕ
  quitTime : Option ℕ
  rho_eq : ρ = rho reward
  unitSoloExit : QuittingUnitSoloExit reward
  tailsTerminate : ∀ start, terminating reward roots start
  rowsPerfect : ∀ time, oneShotPerfectEpsilonEquilibrium reward
    (quittingRootSequenceTailVector reward roots (time + 1)) ε (roots time)
  blockStart_zero : blockStart 0 = 0
  blockStart_strictMono : StrictMono blockStart
  blockAbsorbs : ∀ block,
    ε ^ a ≤ blockTerminationProbability roots (blockStart block)
      (blockStart (block + 1) - blockStart block)
  typeI_regular : ∀ block, ∃ later : ℕ,
    block ≤ later ∧ (later : ℝ) - block ≤ 1 / ε ^ exponent ∧
      blockTypeI roots who (blockStart later)
        (blockStart (later + 1) - blockStart later) ε b

/-- The exponent and local-window restrictions fixed before the block
argument. -/
def MainEstimateContext.Admissible
    (data : MainEstimateContext ι) : Prop :=
  0 < data.ε ∧ data.ε < 1 ∧ 0 ≤ data.ρ ∧
  1 / 5 < data.a ∧ data.a < data.exponent ∧
  1 / 5 < data.b - data.exponent ∧
  1 / 5 < 1 - data.b - data.exponent ∧
  0 < ownerFirstAbsorptionProbability data.roots data.who
      data.localStart data.localLength ∧
  blockTerminationProbability data.roots data.localStart
      data.localLength < data.ε ^ data.a

/-- The paper's `π₂`. -/
def MainEstimateContext.π₂
    (data : MainEstimateContext ι) : ℝ :=
  opponentFirstAbsorptionProbability data.roots data.who
    data.localStart data.localLength

/-- The paper's `π₂*`. -/
def MainEstimateContext.π₂star
    (data : MainEstimateContext ι) : ℝ :=
  opponentBlockTerminationProbability data.roots data.who
    data.localStart data.localLength

/-- The paper's `u₁`. -/
def MainEstimateContext.u₁
    (data : MainEstimateContext ι) : ℝ :=
  ownerConditionalBlockPayoff data.reward data.roots data.who
    data.localStart data.localLength

/-- The paper's `u₂`. -/
def MainEstimateContext.u₂
    (data : MainEstimateContext ι) : ℝ :=
  opponentConditionalBlockPayoff data.reward data.roots data.who
    data.localStart data.localLength

/-- The paper's `u₂*`. -/
def MainEstimateContext.u₂star
    (data : MainEstimateContext ι) : ℝ :=
  forcedContinueOpponentConditionalBlockPayoff data.reward data.roots
    data.who data.localStart data.localLength

/-- The paper's `E_{x^{-i},c^i}[X_k]`. -/
def MainEstimateContext.blockExpectation
    (data : MainEstimateContext ι) (block : ℕ) : ℝ :=
  quittingRootSequenceTerminalValue data.reward
    (continueUntilRoots data.roots data.who (data.blockStart block))
    data.who 0

/-- **Lemma 2.8.** `|π₂-π₂*| ≤ ε^a π₂*`. -/
def Lemma2_8 : Prop :=
  ∀ (ι : Type) [Fintype ι] [DecidableEq ι]
    (data : MainEstimateContext ι), data.Admissible →
      |data.π₂ - data.π₂star| ≤ data.ε ^ data.a * data.π₂star

theorem lemma2_8 : Lemma2_8 := by
  sorry

/-- **Lemma 2.9.** `|u₂-u₂*| ≤ 2ρ ε^a`. -/
def Lemma2_9 : Prop :=
  ∀ (ι : Type) [Fintype ι] [DecidableEq ι]
    (data : MainEstimateContext ι), data.Admissible →
      |data.u₂ - data.u₂star| ≤ 2 * data.ρ * data.ε ^ data.a

theorem lemma2_9 : Lemma2_9 := by
  sorry

/-- **Lemma 2.10.**
`|γⁱ(x_{n₂-1})-u₁| ≤ 4ρNπ₂* + ε`. -/
def Lemma2_10 : Prop :=
  ∀ (ι : Type) [Fintype ι] [DecidableEq ι]
    (data : MainEstimateContext ι), data.Admissible →
      |quittingRootSequenceTailVector data.reward data.roots
          (data.localStart + data.localLength) data.who - data.u₁| ≤
        4 * data.ρ * Fintype.card ι * data.π₂star + data.ε

theorem lemma2_10 : Lemma2_10 := by
  sorry

/-- **Lemma 2.11.** A pure deviation payoff is bounded by the supremum of
the block continuation expectations plus `ε + 2ρ ε^a`. -/
def Lemma2_11 : Prop :=
  ∀ (ι : Type) [Fintype ι] [DecidableEq ι]
    (data : MainEstimateContext ι), data.Admissible →
      quittingRootSequenceHazardTerminalValue data.reward data.roots data.who
          (quittingPureTimeHazard data.quitTime) 0 ≤
        sSup (Set.range data.blockExpectation) +
          data.ε + 2 * data.ρ * data.ε ^ data.a

theorem lemma2_11 : Lemma2_11 := by
  sorry

/-- **Lemma 2.12.** The block expectation supremum is at most the current
payoff plus `2ε^(1-b-e) + 7ρNε^a`. -/
def Lemma2_12 : Prop :=
  ∀ (ι : Type) [Fintype ι] [DecidableEq ι]
    (data : MainEstimateContext ι), data.Admissible →
      sSup (Set.range data.blockExpectation) ≤
        quittingRootSequenceTerminalValue data.reward data.roots data.who 0 +
          2 * data.ε ^ (1 - data.b - data.exponent) +
          7 * data.ρ * Fintype.card ι * data.ε ^ data.a

theorem lemma2_12 : Lemma2_12 := by
  sorry

/-! ### 2.6. Equilibrium and uniformity -/

/-- The paper's uniform `ε`-equilibrium: the profile is an `ε`-equilibrium
for every sufficiently long finite-average payoff. -/
def uniformEpsilonEquilibrium
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (ε : ℝ) (profile : (quittingGame reward).BehaviorProfile) : Prop :=
  (quittingGame reward).IsUniformεEquilibrium none ε profile

/-- **Proposition 2.13.** A terminal `ε`-equilibrium is a uniform
`ε'`-equilibrium whenever `ε < ε'`. -/
theorem proposition2_13
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    {ε ε' : ℝ} (herror : ε < ε')
    (hnash : epsilonEquilibrium reward ε profile) :
    uniformEpsilonEquilibrium reward ε' profile :=
  quittingGame_isUniformεEquilibrium_of_terminalNash
    reward profile herror hnash

/-! ### 2.7. General payoff processes -/

/-- The random payoff process of Theorem 2.14. -/
structure PayoffProcess (ι : Type) [Fintype ι] [DecidableEq ι] where
  Ω : Type
  measurableSpace : MeasurableSpace Ω
  μ : @Measure Ω measurableSpace
  probability : IsProbabilityMeasure μ
  payoff : ℕ → Ω → ({S : Finset ι // S.Nonempty} → Payoff ι)
  limit : Ω → ({S : Finset ι // S.Nonempty} → Payoff ι)
  payoff_measurable : ∀ n terminal who,
    Measurable (fun ω => payoff n ω terminal who)
  limit_measurable : ∀ terminal who,
    Measurable (fun ω => limit ω terminal who)
  integrableEnvelope : ∃ bound : Ω → ℝ,
    Integrable bound μ ∧ ∀ n ω terminal who,
      |payoff n ω terminal who| ≤ bound ω
  converges : ∀ᵐ ω ∂μ, ∀ terminal who,
    Tendsto (fun n => payoff n ω terminal who) atTop
      (nhds (limit ω terminal who))

/-- A behavioral profile for a paper payoff process. -/
abbrev ProcessProfile (process : PayoffProcess ι) :=
  ℕ → ι → process.Ω → PMF Bool

/-- The paper's natural filtration `ℱₙ = σ(rₚ : p < n)`. Repository
time zero represents paper stage one. -/
@[reducible] def processFiltration
    (process : PayoffProcess ι) (time : ℕ) :
    MeasurableSpace process.Ω :=
  ⨆ previous : Fin time, ⨆ terminal, ⨆ who,
    MeasurableSpace.comap
      (fun ω => process.payoff previous ω terminal who) inferInstance

/-- Adaptedness to the natural-information filtration of the payoff
process. -/
def processAdapted
    (process : PayoffProcess ι)
    (profile : ProcessProfile process) : Prop :=
  ∀ time who action,
    Measurable[processFiltration process time]
      (fun ω => (profile time who ω action).toReal)

/-- The expected payoff at the first nonempty quitting coalition. The
summand is survival through the preceding stages times the current absorbing
reward contribution; nontermination contributes zero. -/
def processExpectedPayoff
    (process : PayoffProcess ι)
    (profile : ProcessProfile process) : Payoff ι :=
  fun who => ∫ ω,
    ∑' time,
      quittingJointSurvivalWeight
          (fun stage player => profile stage player ω) 0 time *
        quittingRootAbsorbingContribution (process.payoff time ω)
          (fun player => profile time player ω) who ∂process.μ

/-- The limit process satisfies A.1 and A.2 almost surely. -/
def processAssumptions (process : PayoffProcess ι) : Prop :=
  ∀ᵐ ω ∂process.μ, ∀ who,
    process.limit ω (quittingSingletonTerminal who) who = 1 ∧
      ∀ terminal, who ∈ terminal.1 → process.limit ω terminal who ≤ 1

/-- No adapted unilateral deviation improves the process payoff by more than
`ε`. -/
def processEpsilonEquilibrium
    (process : PayoffProcess ι)
    (profile : ProcessProfile process) (ε : ℝ) : Prop :=
  ∀ who (deviation : ℕ → process.Ω → PMF Bool),
    processAdapted process
      (fun time => Function.update (profile time) who (deviation time)) →
    processExpectedPayoff process profile who + ε ≥
      processExpectedPayoff process
        (fun time => Function.update (profile time) who (deviation time)) who

/-- **Theorem 2.14.** If the payoff process converges almost surely, has an
integrable uniform envelope, and its limit satisfies A.1 and A.2 almost
surely, then it admits an `ε`-equilibrium for every `ε > 0`. -/
def Theorem2_14 : Prop :=
  ∀ (process : PayoffProcess ι), processAssumptions process →
    ∀ ε : ℝ, 0 < ε → ∃ profile : ProcessProfile process,
      processAdapted process profile ∧
        processEpsilonEquilibrium process profile ε

theorem theorem2_14 : Theorem2_14 (ι := ι) := by
  sorry

/-! ## 3. The four-player example -/

/-- The quartic selecting the corrected primary continuation probability. -/
def figure2Polynomial (a : ℝ) : ℝ :=
  44 * a ^ 4 - 7 * a ^ 3 - 26 * a ^ 2 + a + 3

/-- The paper's printed symmetric probability fails player 4's displayed
Bellman equation. With `p = 1 / √2`, the Figure 2 table gives player 4 the
one-step value `4p(1-p) + p²`, which is strictly below `√2`. -/
theorem printedFigure2_playerFour_bellman_mismatch :
    let p : ℝ := 1 / Real.sqrt 2
    4 * p * (1 - p) + p ^ 2 < Real.sqrt 2 := by
  dsimp only
  have hsqrtPos : 0 < Real.sqrt (2 : ℝ) := Real.sqrt_pos.2 (by norm_num)
  have hsqrtSq : Real.sqrt (2 : ℝ) ^ 2 = 2 :=
    Real.sq_sqrt (by norm_num)
  field_simp [hsqrtPos.ne']
  nlinarith

/-- The exact period-two roots for the Figure 2 terminal table. The symmetric
`1 / √2` probabilities printed in the paper do not satisfy that table's
Bellman equations: the two active players must instead use the distinct
continuation probabilities `a` and `b` selected below. -/
def figure2PhaseRootCondition
    (a b : ℝ) (roots : RootSequence (ι := Fin 4)) : Prop :=
  0 < a ∧ a < 1 ∧ 0 < b ∧ b < 1 ∧
  b = (4 * a ^ 2 - 1) / (3 * a ^ 2) ∧
  figure2Polynomial a = 0 ∧
  ∀ time,
    (time % 2 = 0 →
      roots time 1 = PMF.pure false ∧
      roots time 3 = PMF.pure false ∧
      (roots time 0 false).toReal = a ∧
      (roots time 2 false).toReal = b) ∧
    (time % 2 = 1 →
      roots time 0 = PMF.pure false ∧
      roots time 2 = PMF.pure false ∧
      (roots time 1 false).toReal = a ∧
      (roots time 3 false).toReal = b)

/-- The corrected Figure 2 profile is a period-two equilibrium. -/
def Figure2CyclicEquilibriumClaim : Prop :=
  ∃ a b : ℝ, ∃ roots : RootSequence (ι := Fin 4),
    cyclicRootSequence roots ∧
    figure2PhaseRootCondition a b roots ∧
    epsilonEquilibrium SolanVieilleBoundary.boundaryReward 0
      (profile SolanVieilleBoundary.boundaryReward roots)

theorem figure2_cyclic_equilibrium :
    Figure2CyclicEquilibriumClaim := by
  let a := FourPlayerPairedSingleton.periodTwoParameter
  let b := FourPlayerPairedSingleton.periodTwoSecondary
  let cycle : Fin 2 → Fin 4 → PMF Bool :=
    ![FourPlayerPairedSingleton.oddRoot,
      FourPlayerPairedSingleton.evenRoot]
  let roots : RootSequence (ι := Fin 4) :=
    quittingCyclicRootSequence cycle 0
  refine ⟨a, b, roots, ?_, ?_, ?_⟩
  · refine ⟨2, by norm_num, ?_⟩
    intro time
    unfold roots quittingCyclicRootSequence quittingCyclicOrbit
    congr 2
    omega
  · refine ⟨FourPlayerPairedSingleton.periodTwoParameter_pos,
      FourPlayerPairedSingleton.periodTwoParameter_lt_one,
      FourPlayerPairedSingleton.periodTwoSecondary_pos,
      FourPlayerPairedSingleton.periodTwoSecondary_lt_one, rfl, ?_, ?_⟩
    · exact FourPlayerPairedSingleton.periodTwoParameter_root
    · intro time
      unfold roots quittingCyclicRootSequence quittingCyclicOrbit cycle
      have hmod : time % 2 = 0 ∨ time % 2 = 1 := by omega
      rcases hmod with hzero | hone
      · constructor
        · intro _
          simp [hzero, a, b,
            FourPlayerPairedSingleton.oddRoot]
        · omega
      · constructor
        · omega
        · intro _
          simp [hone, a, b,
            FourPlayerPairedSingleton.evenRoot]
  · change epsilonEquilibrium SolanVieilleBoundary.boundaryReward 0
      (quittingRootSequenceProfile SolanVieilleBoundary.boundaryReward roots 0)
    have hcycle : cycle = quittingCyclicContinuationBlockCycle 1
        FourPlayerPairedSingleton.periodTwoBlock := by
      funext stage
      symm
      exact FourPlayerPairedSingleton.quittingCyclicContinuationBlockCycle_periodTwoBlock
        stage
    have hprofile : quittingRootSequenceProfile
        SolanVieilleBoundary.boundaryReward roots 0 =
        FourPlayerPairedSingleton.periodTwoProfile := by
      unfold roots FourPlayerPairedSingleton.periodTwoProfile
        quittingCyclicContinuationBlockProfile quittingCyclicBehaviorProfile
      rw [hcycle]
    rw [hprofile]
    exact FourPlayerPairedSingleton.periodTwoProfile_isExactTerminalNash

/-- The Figure 2 game has no stationary `ε`-equilibrium for all sufficiently
small positive `ε`. The paper states this result and refers elsewhere for the
omitted technical details. -/
def Figure2NoStationaryEpsilonClaim : Prop :=
  ∃ ε₀ : ℝ, 0 < ε₀ ∧ ∀ ε, 0 < ε → ε < ε₀ →
    ¬ ∃ root : Fin 4 → PMF Bool,
      epsilonEquilibrium SolanVieilleBoundary.boundaryReward ε
        (stationaryProfile SolanVieilleBoundary.boundaryReward root)

theorem figure2_no_stationary_epsilon :
    Figure2NoStationaryEpsilonClaim := by
  sorry

/-- The Figure 2 game has no `ε`-equilibrium whose time-dependent mixed root
stays `ε`-close to all-Continue at every stage. This is not restricted to
stationary roots. -/
def Figure2NoPerturbedEpsilonClaim : Prop :=
  ∃ ε₀ : ℝ, 0 < ε₀ ∧ ∀ ε, 0 < ε → ε < ε₀ →
    ¬ ∃ roots : RootSequence (ι := Fin 4),
      (∀ time player,
        |(roots time player false).toReal - 1| < ε) ∧
      epsilonEquilibrium SolanVieilleBoundary.boundaryReward ε
        (profile SolanVieilleBoundary.boundaryReward roots)

theorem figure2_no_perturbed_epsilon :
    Figure2NoPerturbedEpsilonClaim := by
  sorry

/-- The repository's Figure 2 terminal table satisfies A.1 and A.2. -/
theorem boundaryReward_assumptions :
    assumptions SolanVieilleBoundary.boundaryReward :=
  ⟨SolanVieilleBoundary.boundaryReward_unitSoloExit,
    SolanVieilleBoundary.boundaryReward_cappedJointExit⟩

/-! ## Appendix: the independent-clock estimate -/

/-- A finitely additive real-valued probability interface sufficient for the
paper's finite event calculation. -/
structure Probability (Ω : Type*) where
  prob : Set Ω → ℝ
  empty : prob ∅ = 0
  univ : prob Set.univ = 1
  nonneg : ∀ event, 0 ≤ prob event
  add_of_disjoint : ∀ first second,
    Disjoint first second →
      prob (first ∪ second) = prob first + prob second

/-- The first `true` coordinate of a finite Boolean vector, or infinity if
the vector has no success. -/
def firstSuccessVector {N : ℕ} (bits : Fin N → Bool) : WithTop ℕ :=
  if hsuccess : (Finset.univ.filter fun n => bits n = true).Nonempty then
    ((Finset.univ.filter fun n => bits n = true).min' hsuccess : ℕ)
  else ⊤

/-- The first `true` value of a finite Boolean clock, or infinity if the
clock has no success. -/
def firstSuccessTime {N : ℕ} { Ω : Type* }
    (bits : Fin N → Ω → Bool) (ω : Ω) : WithTop ℕ :=
  firstSuccessVector (fun n ↦ bits n ω)

/-- Mutual independence of the two finite Bernoulli vectors. This is the
part of the paper's independence hypothesis used by the clock estimate. -/
def independentBernoulliSequences {N : ℕ} { Ω : Type* }
    (probability : Probability Ω)
    (first second : Fin N → Ω → Bool) : Prop :=
  ∀ firstValues secondValues : Set (Fin N → Bool),
    probability.prob
        {ω | (fun n ↦ first n ω) ∈ firstValues ∧
          (fun n ↦ second n ω) ∈ secondValues} =
      probability.prob {ω | (fun n ↦ first n ω) ∈ firstValues} *
        probability.prob {ω | (fun n ↦ second n ω) ∈ secondValues}

/-- The event that a first-success time is strictly before `N`. -/
def beforeEvent {Ω : Type*}
    (first : Ω → WithTop ℕ) (N : ℕ) : Set Ω :=
  {ω | first ω < N}

/-- The event that the first clock succeeds at `n`. -/
def firstAtEvent {Ω : Type*}
    (first : Ω → WithTop ℕ) (n : ℕ) : Set Ω :=
  {ω | first ω = n}

/-- `T < N` in Appendix Lemma 3.1: the first clock succeeds before `N` and
strictly before the second clock. -/
def firstBeforeSecondEvent {Ω : Type*}
    (first₁ first₂ : Ω → WithTop ℕ) (N : ℕ) : Set Ω :=
  {ω | first₁ ω < N ∧ first₁ ω < first₂ ω}

private theorem Probability.mono { Ω : Type* } (probability : Probability Ω)
    {first second : Set Ω} (hsubset : first ⊆ second) :
    probability.prob first ≤ probability.prob second := by
  have hdecomp : second = first ∪ (second \ first) := by
    ext ω
    constructor
    · intro hω
      by_cases hfirst : ω ∈ first
      · exact Or.inl hfirst
      · exact Or.inr ⟨hω, hfirst⟩
    · rintro (hfirst | hrest)
      · exact hsubset hfirst
      · exact hrest.1
  have hdisjoint : Disjoint first (second \ first) := by
    exact Set.disjoint_left.2 fun _ hfirst hrest ↦ hrest.2 hfirst
  rw [hdecomp, probability.add_of_disjoint first (second \ first) hdisjoint]
  exact le_add_of_nonneg_right (probability.nonneg _)

private theorem Probability.prob_diff { Ω : Type* }
    (probability : Probability Ω) {first second : Set Ω}
    (hsubset : first ⊆ second) :
    probability.prob (second \ first) =
      probability.prob second - probability.prob first := by
  have hdecomp : second = first ∪ (second \ first) := by
    ext ω
    constructor
    · intro hω
      by_cases hfirst : ω ∈ first
      · exact Or.inl hfirst
      · exact Or.inr ⟨hω, hfirst⟩
    · rintro (hfirst | hrest)
      · exact hsubset hfirst
      · exact hrest.1
  have hdisjoint : Disjoint first (second \ first) := by
    exact Set.disjoint_left.2 fun _ hfirst hrest ↦ hrest.2 hfirst
  have hadd : probability.prob second =
      probability.prob first + probability.prob (second \ first) := by
    calc
      probability.prob second = probability.prob (first ∪ (second \ first)) :=
        congrArg probability.prob hdecomp
      _ = probability.prob first + probability.prob (second \ first) :=
        probability.add_of_disjoint first (second \ first) hdisjoint
  linarith

private theorem Probability.prob_biUnion_finset { Ω κ : Type* }
    (probability : Probability Ω) (indices : Finset κ)
    (events : κ → Set Ω)
    (hdisjoint : Set.PairwiseDisjoint (↑indices) events) :
    probability.prob (⋃ index ∈ indices, events index) =
      ∑ index ∈ indices, probability.prob (events index) := by
  classical
  induction indices using Finset.induction with
  | empty => simp [probability.empty]
  | insert index indices hindex ih =>
      simp only [Finset.mem_insert, iUnion_iUnion_eq_or_left, hindex,
        not_false_eq_true, Finset.sum_insert]
      rw [probability.add_of_disjoint, ih]
      · exact hdisjoint.subset (by simp)
      · simp only [Set.disjoint_iUnion_right]
        exact fun other hother ↦ hdisjoint (by simp) (by simp [hother]) (by aesop)

private theorem firstAtEvent_pairwiseDisjoint { Ω : Type* }
    (first : Ω → WithTop ℕ) (indices : Finset ℕ) :
    Set.PairwiseDisjoint (↑indices) (firstAtEvent first) := by
  intro firstIndex _ secondIndex _ hne
  exact Set.disjoint_left.2 fun ω hfirst hsecond ↦
    hne (by exact_mod_cast hfirst.symm.trans hsecond)

private theorem firstAtEvent_inter_pairwiseDisjoint { Ω : Type* }
    (first : Ω → WithTop ℕ) (event : Set Ω) (indices : Finset ℕ) :
    Set.PairwiseDisjoint (↑indices)
      (fun index ↦ firstAtEvent first index ∩ event) := by
  intro firstIndex hfirst secondIndex hsecond hne
  exact (firstAtEvent_pairwiseDisjoint first indices hfirst hsecond hne).mono
    inter_subset_left inter_subset_left

private theorem iUnion_firstAtEvent_range { Ω : Type* }
    (first : Ω → WithTop ℕ) (N : ℕ) :
    (⋃ index ∈ Finset.range N, firstAtEvent first index) =
      beforeEvent first N := by
  ext ω
  simp only [Set.mem_iUnion, Finset.mem_range, firstAtEvent, beforeEvent,
    Set.mem_setOf_eq]
  constructor
  · rintro ⟨index, ⟨hindex, heq⟩⟩
    rw [heq]
    exact_mod_cast hindex
  · intro hbefore
    cases hvalue : first ω with
    | top => simp [hvalue] at hbefore
    | coe index =>
        refine ⟨index, ?_, ?_⟩
        · simpa [hvalue] using hbefore
        · rfl

private theorem iUnion_firstAtEvent_inter_range { Ω : Type* }
    (first : Ω → WithTop ℕ) (event : Set Ω) (N : ℕ)
    (hsubset : event ⊆ beforeEvent first N) :
    (⋃ index ∈ Finset.range N, firstAtEvent first index ∩ event) = event := by
  ext ω
  constructor
  · simp only [Set.mem_iUnion, Set.mem_inter_iff]
    rintro ⟨index, ⟨_, ⟨_, hω⟩⟩⟩
    exact hω
  · intro hω
    have hbefore := hsubset hω
    have hunion : ω ∈ ⋃ index ∈ Finset.range N,
        firstAtEvent first index := by
      rw [iUnion_firstAtEvent_range]
      exact hbefore
    simp only [Set.mem_iUnion] at hunion ⊢
    obtain ⟨index, hindex, hfirst⟩ := hunion
    exact ⟨index, hindex, hfirst, hω⟩

/-- **Appendix Lemma 3.1.** For independent first-success clocks, the loss
from requiring clock 1 to ring before clock 2 is bounded by the product of
their success probabilities, and the two conditional first-clock laws are
within `2 P(S₂<N)` in `ℓ¹`. -/
def Lemma3_1 : Prop :=
  ∀ (Ω : Type*) (probability : Probability Ω) (N : ℕ)
    (firstBits secondBits : Fin N → Ω → Bool),
    independentBernoulliSequences probability firstBits secondBits →
    let first₁ := firstSuccessTime firstBits
    let first₂ := firstSuccessTime secondBits
    0 < probability.prob
      (firstBeforeSecondEvent first₁ first₂ N) →
      probability.prob (beforeEvent first₁ N) -
          probability.prob
            (firstBeforeSecondEvent first₁ first₂ N) ≤
        probability.prob (beforeEvent first₁ N) *
          probability.prob (beforeEvent first₂ N) ∧
      (∑ n ∈ Finset.range N,
        |probability.prob (firstAtEvent first₁ n) /
            probability.prob (beforeEvent first₁ N) -
          probability.prob
              (firstAtEvent first₁ n ∩
                firstBeforeSecondEvent first₁ first₂ N) /
            probability.prob
              (firstBeforeSecondEvent first₁ first₂ N)|) ≤
        2 * probability.prob (beforeEvent first₂ N)

theorem lemma3_1 : Lemma3_1 := by
  intro Ω probability N firstBits secondBits hindependence
  dsimp only
  intro hjointPos
  let first₁ := firstSuccessTime firstBits
  let first₂ := firstSuccessTime secondBits
  let firstBefore := beforeEvent first₁ N
  let secondBefore := beforeEvent first₂ N
  let ordered := firstBeforeSecondEvent first₁ first₂ N
  have horderedSubset : ordered ⊆ firstBefore := by
    intro ω hω
    exact hω.1
  have hfailureSubset : firstBefore \ ordered ⊆
      firstBefore ∩ secondBefore := by
    rintro ω ⟨hfirst, hnotOrdered⟩
    refine ⟨hfirst, ?_⟩
    have hnotLt : ¬ first₁ ω < first₂ ω := by
      intro hlt
      exact hnotOrdered ⟨hfirst, hlt⟩
    exact lt_of_le_of_lt (le_of_not_gt hnotLt) hfirst
  let firstVectorEvent : Set (Fin N → Bool) :=
    {values | firstSuccessVector values < N}
  let secondVectorEvent : Set (Fin N → Bool) :=
    {values | firstSuccessVector values < N}
  have hindependentBefore :
      probability.prob (firstBefore ∩ secondBefore) =
        probability.prob firstBefore * probability.prob secondBefore := by
    have hfactor := hindependence firstVectorEvent secondVectorEvent
    exact hfactor
  have hfailure : probability.prob firstBefore -
        probability.prob ordered ≤
      probability.prob firstBefore * probability.prob secondBefore := by
    rw [← probability.prob_diff horderedSubset]
    exact (probability.mono hfailureSubset).trans_eq hindependentBefore
  refine ⟨hfailure, ?_⟩
  let firstMass : ℕ → ℝ := fun index ↦
    probability.prob (firstAtEvent first₁ index)
  let orderedMass : ℕ → ℝ := fun index ↦
    probability.prob (firstAtEvent first₁ index ∩ ordered)
  let total := probability.prob firstBefore
  let orderedTotal := probability.prob ordered
  let loss := total - orderedTotal
  have htotalPos : 0 < total :=
    lt_of_lt_of_le hjointPos (probability.mono horderedSubset)
  have horderedTotalPos : 0 < orderedTotal := hjointPos
  have hlossNonneg : 0 ≤ loss := by
    exact sub_nonneg.mpr (probability.mono horderedSubset)
  have hfirstMassNonneg (index : ℕ) : 0 ≤ firstMass index :=
    probability.nonneg _
  have horderedMassNonneg (index : ℕ) : 0 ≤ orderedMass index :=
    probability.nonneg _
  have horderedMassLe (index : ℕ) :
      orderedMass index ≤ firstMass index := by
    exact probability.mono inter_subset_left
  have hsumFirst : ∑ index ∈ Finset.range N, firstMass index = total := by
    unfold firstMass total firstBefore
    rw [← probability.prob_biUnion_finset (Finset.range N)
      (firstAtEvent first₁) (firstAtEvent_pairwiseDisjoint first₁ _)]
    rw [iUnion_firstAtEvent_range]
  have hsumOrdered :
      ∑ index ∈ Finset.range N, orderedMass index = orderedTotal := by
    unfold orderedMass orderedTotal
    rw [← probability.prob_biUnion_finset (Finset.range N)
      (fun index ↦ firstAtEvent first₁ index ∩ ordered)
      (firstAtEvent_inter_pairwiseDisjoint first₁ ordered _)]
    rw [iUnion_firstAtEvent_inter_range first₁ ordered N horderedSubset]
  have hpoint (index : ℕ) :
      |firstMass index / total - orderedMass index / orderedTotal| ≤
        (orderedTotal * (firstMass index - orderedMass index) +
          orderedMass index * loss) / (total * orderedTotal) := by
    have htotalNe : total ≠ 0 := ne_of_gt htotalPos
    have horderedNe : orderedTotal ≠ 0 := ne_of_gt horderedTotalPos
    have hdiffNonneg : 0 ≤ firstMass index - orderedMass index :=
      sub_nonneg.mpr (horderedMassLe index)
    have hidentity : firstMass index / total -
        orderedMass index / orderedTotal =
        (orderedTotal * (firstMass index - orderedMass index) -
          orderedMass index * loss) / (total * orderedTotal) := by
      field_simp [htotalNe, horderedNe]
      unfold loss
      ring
    rw [hidentity, abs_div, abs_of_pos (mul_pos htotalPos horderedTotalPos)]
    apply div_le_div_of_nonneg_right _ (mul_pos htotalPos horderedTotalPos).le
    exact (abs_sub _ _).trans (by
      rw [abs_of_nonneg (mul_nonneg horderedTotalPos.le hdiffNonneg),
        abs_of_nonneg (mul_nonneg (horderedMassNonneg index) hlossNonneg)])
  calc
    ∑ index ∈ Finset.range N,
        |firstMass index / total - orderedMass index / orderedTotal| ≤
        ∑ index ∈ Finset.range N,
          (orderedTotal * (firstMass index - orderedMass index) +
            orderedMass index * loss) / (total * orderedTotal) := by
      exact Finset.sum_le_sum fun index _ ↦ hpoint index
    _ = 2 * loss / total := by
      rw [← Finset.sum_div, Finset.sum_add_distrib, ← Finset.mul_sum,
        ← Finset.sum_mul, Finset.sum_sub_distrib, hsumFirst, hsumOrdered]
      field_simp [ne_of_gt htotalPos, ne_of_gt horderedTotalPos]
      unfold loss
      ring
    _ ≤ 2 * probability.prob secondBefore := by
      rw [div_le_iff₀ htotalPos]
      have hlossBound : loss ≤
          total * probability.prob secondBefore := by
        exact hfailure
      nlinarith [probability.nonneg secondBefore]

/-! ## Checked downstream correspondences -/

/-- The exact Theorem 1.2 profile also supplies the weaker integrated
profile-level existence interface. -/
theorem uniformεEquilibriumUnderSoloExitAssumptionsClaim_holds :
    QuittingCappedJointExitUniformεExistence ι :=
  quittingCappedJointExitUniformεExistence_holds

/-- The integrated existence interface supplies one fixed uniform-equilibrium
payoff target. -/
theorem exists_uniformEquilibriumPayoff_of_claim
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (hunit : QuittingUnitSoloExit reward)
    (hcapped : QuittingCappedJointExit reward) :
    ∃ payoff : Payoff ι,
      (quittingGame reward).IsUniformEquilibriumPayoff none payoff :=
  exists_uniformEquilibriumPayoff_of_soloExitPreference hunit hcapped

end Literature.SolanAndVieille2001
