/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import MathUE.Probability.OneSidedDebtShadowing
import UniformEquilibrium.Quitting.Boundary.Exceptional.InfiniteLTG
import UniformEquilibrium.Quitting.Cycles.SoloPeriodicBlockCompiler
import UniformEquilibrium.Quitting.Root.TerminalSemanticPair
import UniformEquilibrium.Quitting.Terminal.ExploitabilityGap

/-!
# Generated-secant two-discount shadowing in quitting games

This file instantiates the coupled backward-recursion theorem on an executable
quitting root sequence.  Candidate prescribed values and debts are compared
with the literal terminal semantic pair of every reached tail.  Thus the
direct debt defect below is a one-stage Bellman defect at the actual successor
candidate; it is not a chord between frozen stopping laws.

The prescribed and best-response recursions are unrolled separately.  This
removes singleton purification and discounted owner excess from the semantic
compiler.  Those devices may still be useful upstream, but static reset-cube
cancellation still does not supply the chronological suffix estimates used
here.
-/

noncomputable section

namespace GameTheory

open Filter StochasticGame Math.Probability Math.PMFProduct
open scoped BigOperators Topology

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- Two candidate semantic caps at the same root have an exact generated
secant bounded by the deleted-player Continue mass.  The statement permits
the maximizing Quit/Continue branch to switch. -/
theorem exists_quittingTerminalSemanticPrefix_secant
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) (first second : QuittingTerminalSemanticPair ι)
    (who : ι) :
    ∃ secant : ℝ,
      0 ≤ secant ∧ secant ≤ quittingRootOpponentContinueMass root who ∧
      (quittingTerminalSemanticPrefix reward root second).2 who -
          (quittingTerminalSemanticPrefix reward root first).2 who =
        secant * (second.2 who - first.2 who) := by
  let stop := quittingRootQuitPayoff reward (0 : Payoff ι) root who
  let immediate := quittingRootAbsorbingContribution reward
    (Function.update root who (PMF.pure false)) who
  let slope := quittingRootOpponentContinueMass root who
  have hform : ∀ pair : QuittingTerminalSemanticPair ι,
      (quittingTerminalSemanticPrefix reward root pair).2 who =
        max stop (immediate + slope * pair.2 who) := by
    intro pair
    unfold quittingTerminalSemanticPrefix
    dsimp only
    rw [quittingRootQuitPayoff_continuation_invariant
      reward pair.1 (0 : Payoff ι) root who]
    unfold quittingRootContinuePayoff
    rw [quittingRootExpectedPayoff_eq_absorbingContribution_add]
    simp only [Function.update_self]
    rfl
  obtain ⟨secant, hsecant0, hsecantSlope, hsecant⟩ :=
    Math.exists_max_const_add_mul_secant stop immediate slope
      (first.2 who) (second.2 who)
      (quittingRootOpponentContinueMass_nonneg root who)
  refine ⟨secant, hsecant0, hsecantSlope, ?_⟩
  simpa only [hform] using hsecant

/-- Executable product roots together with candidate prescribed values,
nonnegative debts, and a generated Bellman secant selection. -/
structure QuittingChronologicalDebtData (ι : Type) where
  /-- The product root executed at each live stage. -/
  roots : ℕ → ι → PMF Bool
  /-- Candidate prescribed-payoff tails. -/
  prescribed : ℕ → Payoff ι
  /-- Candidate nonnegative debt tails. -/
  debt : ℕ → Payoff ι
  /-- Secants generated by comparing the actual and candidate Snell tails. -/
  secant : ℕ → Payoff ι

namespace QuittingChronologicalDebtData

variable (data : QuittingChronologicalDebtData ι)

/-- The singleton-purified product root executed at `time`. -/
def root (time : ℕ) : ι → PMF Bool :=
  data.roots time

/-- The literal prescribed/envelope pair of the executable tail beginning at
`time`. -/
def semanticPair
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) (time : ℕ) :
    QuittingTerminalSemanticPair ι :=
  quittingTerminalSemanticPair reward
    (quittingRootSequenceProfile reward data.root time)

/-- The candidate successor pair `(u^{t+1},u^{t+1}+d^{t+1})`. -/
def candidateSuccessorPair (time : ℕ) : QuittingTerminalSemanticPair ι :=
  (data.prescribed (time + 1),
    fun who ↦ data.prescribed (time + 1) who + data.debt (time + 1) who)

/-- The prescribed-payoff defect at one reached stage. -/
def prescribedDefect
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (time : ℕ) : Payoff ι :=
  fun who ↦ data.prescribed time who -
    (quittingTerminalSemanticPrefix reward (data.root time)
      (data.candidateSuccessorPair time)).1 who

/-- The direct one-stage debt defect at the actual candidate successor.
This is the chronological quantity charged by the compiler. -/
def directDebtDefect
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (time : ℕ) : Payoff ι :=
  fun who ↦ data.debt time who -
    quittingTerminalSemanticDebt
      (quittingTerminalSemanticPrefix reward (data.root time)
        (data.candidateSuccessorPair time)) who

/-- Error between the actual prescribed tail and its candidate. -/
def prescribedError
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (time : ℕ) : Payoff ι :=
  fun who ↦ (data.semanticPair reward time).1 who - data.prescribed time who

/-- Error between actual semantic debt and candidate debt. -/
def debtError
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (time : ℕ) : Payoff ι :=
  fun who ↦ quittingTerminalSemanticDebt (data.semanticPair reward time) who -
    data.debt time who

/-- Error between the actual best-response tail and the candidate cap
`u + d`. -/
def bestResponseError
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (time : ℕ) : Payoff ι :=
  fun who ↦ (data.semanticPair reward time).2 who -
    (data.prescribed time who + data.debt time who)

/-- Debt error is exactly best-response error minus prescribed error. -/
theorem debtError_eq_bestResponseError_sub_prescribedError
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (time : ℕ) (who : ι) :
    data.debtError reward time who =
      data.bestResponseError reward time who -
        data.prescribedError reward time who := by
  unfold debtError bestResponseError prescribedError
    quittingTerminalSemanticDebt
  ring

/-- Reached terminal semantic pairs obey literal chronological prefixing. -/
theorem semanticPair_eq_prefix
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) (time : ℕ) :
    data.semanticPair reward time =
      quittingTerminalSemanticPrefix reward (data.root time)
        (data.semanticPair reward (time + 1)) := by
  unfold semanticPair
  rw [quittingRootSequenceProfile_eq_rootThenContinuation,
    quittingTerminalSemanticPair_rootThenContinuation]

end QuittingChronologicalDebtData

/-- The full conditional producer interface for one-sided chronological debt
shadowing.  Every field refers either to an executable tail or to a finite
weighted suffix of its generated secants. -/
structure QuittingChronologicalDebtShadowingCertificate
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (eta : ℝ) where
  data : QuittingChronologicalDebtData ι
  /-- The requested shadowing accuracy is positive. -/
  eta_pos : 0 < eta
  /-- Candidate debts are nonnegative at every reached tail. -/
  debt_nonneg : ∀ time who, 0 ≤ data.debt time who
  /-- Candidate prescribed values are uniformly bounded. -/
  prescribed_bounded : ∃ bound : ℝ,
    ∀ time who, |data.prescribed time who| ≤ bound
  /-- Candidate debts are uniformly bounded. -/
  debt_bounded : ∃ bound : ℝ, ∀ time who, |data.debt time who| ≤ bound
  /-- Generated secants are nonnegative. -/
  secant_nonneg : ∀ time who, 0 ≤ data.secant time who
  /-- A generated secant is at most the deleted-player Continue mass. -/
  secant_le_opponentContinue : ∀ time who,
    data.secant time who ≤
      quittingRootOpponentContinueMass (data.root time) who
  /-- The secant identity comparing the actual Snell tail with the candidate
  successor pair. -/
  secant_generated : ∀ time who,
    (data.semanticPair reward time).2 who -
        (quittingTerminalSemanticPrefix reward (data.root time)
          (data.candidateSuccessorPair time)).2 who =
      data.secant time who *
        ((data.semanticPair reward (time + 1)).2 who -
          (data.candidateSuccessorPair time).2 who)
  /-- Every finite suffix has prescribed-defect discrepancy at most `eta`. -/
  prescribed_discrepancy : ∀ who start length,
    |∑ offset ∈ Finset.range length,
      data.prescribedDefect reward (start + offset) who| ≤ eta
  /-- The generated secants see asymptotically at most `eta` adverse direct
  debt forcing on every suffix. -/
  adverse_direct_forcing : ∀ who start slack, 0 < slack →
    ∀ᶠ length in atTop,
      -∑ offset ∈ Finset.range length,
        Math.survivalProduct (fun time ↦ data.secant time who) start offset *
          data.directDebtDefect reward (start + offset) who ≤ eta + slack
  /-- Joint survival vanishes on every tail. -/
  joint_survival : ∀ start,
    Tendsto
      (Math.survivalProduct
        (fun time ↦ quittingStationaryContinueMass (data.root time)) start)
      atTop (nhds 0)
  /-- Deleted-player survival vanishes on every tail. -/
  opponent_survival : ∀ who start,
    Tendsto
      (Math.survivalProduct
        (fun time ↦ quittingRootOpponentContinueMass (data.root time) who)
        start) atTop (nhds 0)
  /-- Initial candidate debt is at most the requested accuracy. -/
  initial_debt_le : ∀ who, data.debt 0 who ≤ eta

namespace QuittingChronologicalDebtShadowingCertificate

variable {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
  {eta : ℝ}
  (certificate : QuittingChronologicalDebtShadowingCertificate reward eta)

private theorem secant_le_one (time : ℕ) (who : ι) :
    certificate.data.secant time who ≤ 1 :=
  (certificate.secant_le_opponentContinue time who).trans
    (quittingRootOpponentContinueMass_le_one _ _)

private theorem secant_survival (who : ι) (start : ℕ) :
    Tendsto
      (Math.survivalProduct (fun time ↦ certificate.data.secant time who) start)
      atTop (nhds 0) := by
  exact Math.tendsto_survivalProduct_zero_of_le
    (fun time ↦ certificate.data.secant time who)
    (fun time ↦ quittingRootOpponentContinueMass
      (certificate.data.root time) who) start
    (fun time ↦ certificate.secant_nonneg time who)
    (fun time ↦ certificate.secant_le_opponentContinue time who)
    (certificate.opponent_survival who start)

private theorem prescribedError_recursion (who : ι) (time : ℕ) :
    certificate.data.prescribedError reward time who =
      quittingStationaryContinueMass (certificate.data.root time) *
          certificate.data.prescribedError reward (time + 1) who -
        certificate.data.prescribedDefect reward time who := by
  have hpair := congrArg
    (fun pair : QuittingTerminalSemanticPair ι ↦ pair.1 who)
    (QuittingChronologicalDebtData.semanticPair_eq_prefix
      certificate.data reward time)
  unfold QuittingChronologicalDebtData.prescribedError
    QuittingChronologicalDebtData.prescribedDefect
  rw [hpair]
  unfold quittingTerminalSemanticPrefix
  dsimp only
  unfold quittingRootSuccessorPayoff
  rw [quittingRootExpectedPayoff_eq_absorbingContribution_add,
    quittingRootExpectedPayoff_eq_absorbingContribution_add]
  unfold QuittingChronologicalDebtData.candidateSuccessorPair
  dsimp only
  ring_nf

private theorem bestResponseError_recursion (who : ι) (time : ℕ) :
    certificate.data.bestResponseError reward time who =
      certificate.data.secant time who *
          certificate.data.bestResponseError reward (time + 1) who -
        (certificate.data.prescribedDefect reward time who +
          certificate.data.directDebtDefect reward time who) := by
  have hgenerated := certificate.secant_generated time who
  have hcurrentBest :
      (certificate.data.semanticPair reward time).2 who =
        (quittingTerminalSemanticPrefix reward (certificate.data.root time)
          (certificate.data.candidateSuccessorPair time)).2 who +
        certificate.data.secant time who *
          ((certificate.data.semanticPair reward (time + 1)).2 who -
            (certificate.data.candidateSuccessorPair time).2 who) := by
    linarith
  unfold QuittingChronologicalDebtData.bestResponseError
    QuittingChronologicalDebtData.prescribedDefect
    QuittingChronologicalDebtData.directDebtDefect
    quittingTerminalSemanticDebt
  rw [hcurrentBest]
  unfold QuittingChronologicalDebtData.candidateSuccessorPair
  dsimp only
  linarith

private theorem prescribedError_bounded (who : ι) :
    ∃ bound : ℝ,
      ∀ time, |certificate.data.prescribedError reward time who| ≤ bound := by
  obtain ⟨bound, hbound⟩ := certificate.prescribed_bounded
  refine ⟨quittingRewardBound reward + bound, fun time ↦ ?_⟩
  unfold QuittingChronologicalDebtData.prescribedError
  exact (abs_sub _ _).trans (add_le_add
    (abs_quittingTerminalPayoff_le_quittingRewardBound reward
      (quittingRootSequenceProfile reward certificate.data.root time) who)
    (hbound time who))

private theorem bestResponseError_bounded (who : ι) :
    ∃ bound : ℝ,
      ∀ time,
        |certificate.data.bestResponseError reward time who| ≤ bound := by
  obtain ⟨prescribedBound, hprescribedBound⟩ := certificate.prescribed_bounded
  obtain ⟨debtBound, hdebtBound⟩ := certificate.debt_bounded
  refine ⟨quittingRewardBound reward + prescribedBound + debtBound,
    fun time ↦ ?_⟩
  unfold QuittingChronologicalDebtData.bestResponseError
    QuittingChronologicalDebtData.semanticPair
  calc
    |quittingContinuationBestResponseValue reward
          (quittingRootSequenceProfile reward certificate.data.root time) who -
          (certificate.data.prescribed time who +
          certificate.data.debt time who)| ≤
        |quittingContinuationBestResponseValue reward
          (quittingRootSequenceProfile reward certificate.data.root time) who| +
        |certificate.data.prescribed time who| +
        |certificate.data.debt time who| := by
      calc
        _ ≤ |quittingContinuationBestResponseValue reward
              (quittingRootSequenceProfile reward certificate.data.root time)
              who| +
            |certificate.data.prescribed time who +
              certificate.data.debt time who| := abs_sub _ _
        _ ≤ |quittingContinuationBestResponseValue reward
              (quittingRootSequenceProfile reward certificate.data.root time)
              who| +
            (|certificate.data.prescribed time who| +
              |certificate.data.debt time who|) :=
          add_le_add (le_refl _) (abs_add_le _ _)
        _ = _ := by ring
    _ ≤ quittingRewardBound reward + prescribedBound + debtBound := by
      have hbest := abs_quittingContinuationBestResponseValue_le
        reward (quittingRootSequenceProfile reward certificate.data.root time)
        who (abs_reward_le_quittingRewardBound reward)
      exact add_le_add (add_le_add hbest (hprescribedBound time who))
        (hdebtBound time who)

private theorem bestResponseTerminal_tendsto_zero (who : ι) (start : ℕ) :
    Tendsto (fun length ↦
      Math.survivalProduct
          (fun time ↦ certificate.data.secant time who) start length *
        max (certificate.data.bestResponseError reward
          (start + length) who) 0) atTop (nhds 0) := by
  apply Math.tendsto_survivalProduct_mul_bounded_zero
    (fun time ↦ certificate.data.secant time who)
    (fun time ↦ max (certificate.data.bestResponseError reward time who) 0)
    start (certificate.secant_survival who start)
  obtain ⟨bound, hbound⟩ := certificate.bestResponseError_bounded who
  refine ⟨bound, fun time ↦ ?_⟩
  rw [abs_of_nonneg (le_max_right _ _)]
  exact max_le (le_abs_self _ |>.trans (hbound time))
    ((abs_nonneg _).trans (hbound time))

private theorem prescribedTerminal_tendsto_zero (who : ι) (start : ℕ) :
    Tendsto (fun length ↦
      Math.survivalProduct
          (fun time ↦ quittingStationaryContinueMass
            (certificate.data.root time)) start length *
        max (-certificate.data.prescribedError reward
          (start + length) who) 0) atTop (nhds 0) := by
  apply Math.tendsto_survivalProduct_mul_bounded_zero
    (fun time ↦ quittingStationaryContinueMass (certificate.data.root time))
    (fun time ↦ max (-certificate.data.prescribedError reward time who) 0)
    start (certificate.joint_survival start)
  obtain ⟨bound, hbound⟩ := certificate.prescribedError_bounded who
  refine ⟨bound, fun time ↦ ?_⟩
  rw [abs_of_nonneg (le_max_right _ _)]
  apply max_le
  · linarith [(abs_le.mp (hbound time)).1]
  · exact (abs_nonneg _).trans (hbound time)

/-- The literal semantic debt of every reached tail is shadowed from above by
the candidate debt with the universal forcing cost `3 * eta`. -/
theorem semanticDebt_le (who : ι) (start : ℕ) :
    quittingTerminalSemanticDebt
        (certificate.data.semanticPair reward start) who ≤
      certificate.data.debt start who + 3 * eta := by
  have hshadow := Math.twoDiscountDebtShadowing
    (fun time ↦ certificate.data.prescribedError reward time who)
    (fun time ↦ certificate.data.bestResponseError reward time who)
    (fun time ↦ certificate.data.prescribedDefect reward time who)
    (fun time ↦ certificate.data.directDebtDefect reward time who)
    (fun time ↦ quittingStationaryContinueMass (certificate.data.root time))
    (fun time ↦ certificate.data.secant time who)
    eta eta
    (fun time ↦ quittingStationaryContinueMass_nonneg _)
    (fun time ↦ quittingStationaryContinueMass_le_one _)
    (fun time ↦ certificate.secant_nonneg time who)
    (fun time ↦ certificate.secant_le_one time who)
    (fun time ↦ certificate.prescribedError_recursion who time)
    (fun time ↦ certificate.bestResponseError_recursion who time)
    (certificate.prescribed_discrepancy who)
    start
    (certificate.adverse_direct_forcing who start)
    (certificate.bestResponseTerminal_tendsto_zero who start)
    (certificate.prescribedTerminal_tendsto_zero who start)
  rw [← QuittingChronologicalDebtData.debtError_eq_bestResponseError_sub_prescribedError]
    at hshadow
  unfold QuittingChronologicalDebtData.debtError at hshadow
  linarith

/-- Initial exploitability is at most `4 * eta`. -/
theorem initial_semanticDebt_le (who : ι) :
    quittingTerminalSemanticDebt
        (certificate.data.semanticPair reward 0) who ≤
      4 * eta := by
  have hshadow := certificate.semanticDebt_le who 0
  have hinitial := certificate.initial_debt_le who
  linarith

/-- **Conditional chronological debt compiler.**  Executable forcing and
vanishing joint/opponent survival produce a terminal `4 * eta` equilibrium.
No singleton-purification or owner-excess hypothesis is used. -/
theorem isAsymptoticNash :
    (quittingGame reward).IsεAsymptoticNash
      (quittingTerminalPayoff reward) (4 * eta)
      (quittingRootSequenceProfile reward certificate.data.root 0) := by
  intro who deviation
  have hdeviation :=
    quittingTerminalPayoff_update_le_continuationBestResponseValue
      reward (quittingRootSequenceProfile reward certificate.data.root 0)
      who deviation
  have hdebt := certificate.initial_semanticDebt_le who
  unfold QuittingChronologicalDebtData.semanticPair
    quittingTerminalSemanticDebt at hdebt
  change quittingContinuationBestResponseValue reward
      (quittingRootSequenceProfile reward certificate.data.root 0) who -
        quittingTerminalPayoff reward
          (quittingRootSequenceProfile reward certificate.data.root 0) who ≤
      4 * eta at hdebt
  linarith

include certificate

/-- Any global terminal exploitability gap is bounded by the certificate's
quantitative `4 * eta` terminal Nash error.  No separate positivity
hypothesis on the gap is needed. -/
theorem terminalExploitabilityGap_le
    {gap : ℝ} (hexploit : HasTerminalExploitabilityGap reward gap) :
    gap ≤ 4 * eta := by
  obtain ⟨who, deviation, hgap⟩ :=
    hexploit (quittingRootSequenceProfile reward certificate.data.root 0)
  have hnash := certificate.isAsymptoticNash who deviation
  linarith

/-- A chronological certificate whose error is below a displayed terminal
exploitability gap contradicts that gap. -/
theorem not_hasTerminalExploitabilityGap_of_four_mul_eta_lt
    {gap : ℝ} (hsmall : 4 * eta < gap) :
    ¬ HasTerminalExploitabilityGap reward gap := by
  intro hexploit
  exact (not_lt_of_ge (certificate.terminalExploitabilityGap_le hexploit)) hsmall

end QuittingChronologicalDebtShadowingCertificate

/-- Chronological certificates at every positive accuracy produce terminal
approximate Nash profiles at every positive error and hence, by compact
terminal-payoff selection, one fixed uniform-equilibrium payoff. -/
theorem quittingGame_exists_uniformEquilibriumPayoff_of_chronologicalDebtShadowing_all_errors
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (hcertificates : ∀ eta : ℝ, 0 < eta →
      Nonempty (QuittingChronologicalDebtShadowingCertificate reward eta)) :
    ∃ payoff : Payoff ι,
      (quittingGame reward).IsUniformEquilibriumPayoff none payoff := by
  apply quittingGame_exists_uniformEquilibriumPayoff_of_terminalNash_all_errors
    reward
  intro epsilon hepsilon
  obtain ⟨certificate⟩ := hcertificates (epsilon / 4) (by positivity)
  refine ⟨quittingRootSequenceProfile reward certificate.data.root 0, ?_⟩
  convert certificate.isAsymptoticNash using 1
  ring

/-! ## Charged-circulation producer boundary

The source-matched frontier currently ends at
`QuittingCounterexampleStoppingLawFrontier.exists_sourceMatchedChattering`
and `exists_sourceMatchedChatteringResetCubeStar`.  Those results control
weighted chords from one frozen stopping-law source.  They do not construct
the executable `root` tails in `QuittingChronologicalDebtData`, and hence do
not prove `prescribed_discrepancy` or `adverse_direct_forcing` in the
certificate above.

Accordingly this module deliberately contains no implication from a flat
charged circulation to a chronological certificate.  Such an implication is
the remaining producer theorem.  The checked algebraic result
`Math.zero_sum_does_not_imply_nonpositive_adverse_survivalWeight` explains why
unweighted frozen endpoint cancellation alone cannot prove its weighted
direct-forcing clause.  This is a dependency boundary, not an impossibility
claim about quitting-game semantics.
-/

end GameTheory
