/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.Stationary.FullRateStationaryVerifier

/-!
# Stationary exploitability has a gap-or-escape dichotomy

At an actual stationary product profile `root` (a function `ι → PMF Bool`,
one marginal Continue/Quit distribution per player), player `who`'s
*positive stationary regret* is how much the exact full-rate unilateral cap
`quittingStationaryFullRateUnilateralCap` exceeds `who`'s prescribed terminal
payoff at the stationary profile generated by `root`, floored at zero.
`g_r(root)` is the playerwise maximum of this positive regret, and `δ_stat`
is the infimum of `g_r` over every stationary product profile, for a fixed
reward.

The dichotomy is that `δ_stat` -- a nonnegative real number -- is either
exactly zero or strictly positive, and each case has a corresponding
consequence:

* `δ_stat = 0`: for every `ε > 0` there is an actual stationary product
  profile whose stationary behavior profile is a terminal `ε`-Nash profile of
  `quittingGame reward`.  This direction routes through the exact verifier
  `isεAsymptoticNash_stationary_iff_fullRateUnilateralCap_le`.  The converse
  also holds -- `δ_stat = 0` **characterizes** stationary approximability,
  packaged as `quittingStationaryRegretInfimum_eq_zero_iff`.
* `δ_stat > 0`: *every* stationary product profile has some player whose
  positive regret is at least `δ_stat`.  This is packaged as a typed witness
  `QuittingStationaryRegretWitness` rather than a bare inequality, because
  its intended consumer is a negative-search filter over stationary
  candidates that needs the offending player, not just an existence claim.
  The filter's actual working tool is the contrapositive of the `δ_stat = 0`
  characterization: `quittingStationaryProfile_not_isεAsymptoticNash_of_regretInfimum_pos`,
  which rules out *any* stationary terminal `ε`-Nash profile once `ε < δ_stat`.

## Scope fence

A positive `δ_stat` excludes only *stationary product* profiles.  It says
nothing about cyclic, periodic, or arbitrary behavioral profiles, and it is
**not** a counterexample to equilibrium existence in any sense -- a
nonstationary equilibrium may perfectly well exist even when `δ_stat > 0`.
The offending player and regime (contracting vs. saturated opponents; see
`QuittingFullRateStationaryVerifier`) may vary from profile to profile.

`δ_stat` is a real infimum (`sInf`) over an in general infinite set of
profiles.  It need not be attained by any actual stationary profile, and no
declaration in this file assumes a minimizing profile exists.

## Main declarations

* `quittingStationaryPlayerPositiveRegret` -- one player's positive regret at
  one stationary product profile.
* `quittingStationaryMaxPositiveRegret` -- `g_r`, the playerwise maximum.
* `quittingStationaryRegretInfimum` -- `δ_stat`, the infimum of `g_r` over
  every stationary product profile.
* `quittingStationaryRegretInfimum_eq_zero_iff` -- `δ_stat = 0` iff stationary
  product profiles give terminal `ε`-Nash profiles at every accuracy.
* `quittingStationaryProfile_not_isεAsymptoticNash_of_regretInfimum_pos` --
  the no-ε-Nash corollary a negative-search filter consumes directly.
* `QuittingStationaryRegretWitness` -- the typed witness for the positive
  branch of the dichotomy.
* `quittingStationaryRegretWitness_regretInfimum` -- the unconditional
  existence of that witness at threshold `δ_stat`, for any root.

This module packages and verifies; it neither constructs nor searches for
stationary roots, and it supplies no uniform-equilibrium delivery theorem.
-/

noncomputable section

namespace GameTheory

open StochasticGame Math.Probability Math.PMFProduct

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-! ## Playerwise positive regret and its maximum -/

/-- Player `who`'s positive stationary regret at product profile `root`: the
amount by which the exact full-rate unilateral cap exceeds `who`'s prescribed
terminal payoff at the stationary profile generated by `root`, floored at
zero. -/
def quittingStationaryPlayerPositiveRegret
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) (who : ι) : ℝ :=
  max 0
    (quittingStationaryFullRateUnilateralCap reward root who -
      quittingTerminalPayoff reward
        (quittingStationaryProfile reward root) who)

/-- Positive regret is nonnegative by construction. -/
theorem quittingStationaryPlayerPositiveRegret_nonneg
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) (who : ι) :
    0 ≤ quittingStationaryPlayerPositiveRegret reward root who :=
  le_max_left 0 _

/-- `g_r(root)`: the maximum positive stationary regret over players, at the
stationary product profile `root`.  The nonempty-player assumption prevents
an artificial default value. -/
def quittingStationaryMaxPositiveRegret [Nonempty ι]
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) : ℝ :=
  Finset.univ.sup' Finset.univ_nonempty
    (quittingStationaryPlayerPositiveRegret reward root)

/-- `g_r` is nonnegative. -/
theorem quittingStationaryMaxPositiveRegret_nonneg [Nonempty ι]
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) :
    0 ≤ quittingStationaryMaxPositiveRegret reward root :=
  le_trans
    (quittingStationaryPlayerPositiveRegret_nonneg reward root (Classical.arbitrary ι))
    (Finset.le_sup' (quittingStationaryPlayerPositiveRegret reward root)
      (Finset.mem_univ (Classical.arbitrary ι)))

/-! ## The regret infimum `δ_stat` -/

/-- `δ_stat`: the infimum of `g_r` over every actual stationary product
profile, for a fixed reward.  This is a real `sInf`, so it need not be
attained by any actual profile; no declaration here assumes a minimizer
exists. -/
def quittingStationaryRegretInfimum [Nonempty ι]
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) : ℝ :=
  sInf (Set.range (quittingStationaryMaxPositiveRegret reward))

/-- The range of `g_r` is bounded below by zero, for any reward. -/
theorem bddBelow_range_quittingStationaryMaxPositiveRegret [Nonempty ι]
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :
    BddBelow (Set.range (quittingStationaryMaxPositiveRegret reward)) := by
  refine ⟨0, ?_⟩
  rintro x ⟨root, rfl⟩
  exact quittingStationaryMaxPositiveRegret_nonneg reward root

/-- The range of `g_r` is nonempty, for any reward: the all-quit profile
witnesses it.  Shared by `quittingStationaryRegretInfimum_nonneg` and
`exists_stationaryProfile_isεAsymptoticNash_of_regretInfimum_eq_zero`. -/
theorem quittingStationaryMaxPositiveRegret_range_nonempty [Nonempty ι]
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :
    (Set.range (quittingStationaryMaxPositiveRegret reward)).Nonempty :=
  ⟨quittingStationaryMaxPositiveRegret reward (fun _ => PMF.pure false),
    Set.mem_range_self _⟩

/-- `δ_stat` is nonnegative, since every value of `g_r` is nonnegative. -/
theorem quittingStationaryRegretInfimum_nonneg [Nonempty ι]
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :
    0 ≤ quittingStationaryRegretInfimum reward := by
  apply le_csInf (quittingStationaryMaxPositiveRegret_range_nonempty reward)
  rintro x ⟨root, rfl⟩
  exact quittingStationaryMaxPositiveRegret_nonneg reward root

/-- `δ_stat` is either exactly zero or strictly positive: the two branches of
the dichotomy are jointly exhaustive. -/
theorem quittingStationaryRegretInfimum_eq_zero_or_pos [Nonempty ι]
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :
    quittingStationaryRegretInfimum reward = 0 ∨
      0 < quittingStationaryRegretInfimum reward :=
  (eq_or_lt_of_le (quittingStationaryRegretInfimum_nonneg reward)).imp_left Eq.symm

/-! ## The gap-free branch: `δ_stat = 0` gives terminal `ε`-Nash profiles -/

/-- If a stationary product profile's `g_r` is at most `ε`, its stationary
behavior profile is a terminal `ε`-Nash profile.  Routes through the exact
verifier `isεAsymptoticNash_stationary_iff_fullRateUnilateralCap_le`. -/
theorem quittingStationaryProfile_isεAsymptoticNash_of_maxPositiveRegret_le
    [Nonempty ι] (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) {ε : ℝ}
    (hreg : quittingStationaryMaxPositiveRegret reward root ≤ ε) :
    (quittingGame reward).IsεAsymptoticNash
        (quittingTerminalPayoff reward) ε
        (quittingStationaryProfile reward root) := by
  rw [isεAsymptoticNash_stationary_iff_fullRateUnilateralCap_le]
  intro who
  have hle : quittingStationaryPlayerPositiveRegret reward root who ≤ ε :=
    le_trans
      (Finset.le_sup' (quittingStationaryPlayerPositiveRegret reward root)
        (Finset.mem_univ who))
      hreg
  have hsub :
      quittingStationaryFullRateUnilateralCap reward root who -
          quittingTerminalPayoff reward
            (quittingStationaryProfile reward root) who ≤ ε :=
    le_trans (le_max_right (0 : ℝ) _) hle
  linarith

/-- If `δ_stat = 0`, then for every `ε > 0` there is an actual stationary
product profile whose stationary behavior profile is a terminal `ε`-Nash
profile.  This is the "escape" branch of the dichotomy: repeated repair can
push exploitability below any fixed accuracy, even though no single
stationary profile need be exactly optimal (the infimum need not be
attained). -/
theorem exists_stationaryProfile_isεAsymptoticNash_of_regretInfimum_eq_zero
    [Nonempty ι] (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (hzero : quittingStationaryRegretInfimum reward = 0)
    {ε : ℝ} (hε : 0 < ε) :
    ∃ root : ι → PMF Bool,
      (quittingGame reward).IsεAsymptoticNash
        (quittingTerminalPayoff reward) ε
        (quittingStationaryProfile reward root) := by
  have hbdd := bddBelow_range_quittingStationaryMaxPositiveRegret reward
  have hne := quittingStationaryMaxPositiveRegret_range_nonempty reward
  have hlt : quittingStationaryRegretInfimum reward < ε := by
    rw [hzero]; exact hε
  obtain ⟨a, ⟨root, hroot⟩, ha⟩ := (csInf_lt_iff hbdd hne).mp hlt
  refine ⟨root, quittingStationaryProfile_isεAsymptoticNash_of_maxPositiveRegret_le
    reward root ?_⟩
  rw [hroot]
  exact ha.le

/-! ## The converse: `δ_stat = 0` characterizes stationary approximability -/

/-- The converse of `quittingStationaryProfile_isεAsymptoticNash_of_maxPositiveRegret_le`:
any stationary product profile whose stationary behavior profile is a
terminal `ε`-Nash profile has playerwise maximum positive regret at most
`max 0 ε` -- the nonnegative part of `ε`, since positive regret is itself
floored at zero. -/
theorem quittingStationaryMaxPositiveRegret_le_of_isεAsymptoticNash
    [Nonempty ι] (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) {ε : ℝ}
    (hnash : (quittingGame reward).IsεAsymptoticNash
        (quittingTerminalPayoff reward) ε
        (quittingStationaryProfile reward root)) :
    quittingStationaryMaxPositiveRegret reward root ≤ max 0 ε := by
  rw [isεAsymptoticNash_stationary_iff_fullRateUnilateralCap_le] at hnash
  unfold quittingStationaryMaxPositiveRegret
  apply Finset.sup'_le
  intro who _
  unfold quittingStationaryPlayerPositiveRegret
  exact max_le_max le_rfl (by linarith [hnash who])

/-- `δ_stat` is at most `max 0 ε` whenever some stationary product profile's
stationary behavior profile is a terminal `ε`-Nash profile. -/
theorem quittingStationaryRegretInfimum_le_of_isεAsymptoticNash
    [Nonempty ι] (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    {root : ι → PMF Bool} {ε : ℝ}
    (hnash : (quittingGame reward).IsεAsymptoticNash
        (quittingTerminalPayoff reward) ε
        (quittingStationaryProfile reward root)) :
    quittingStationaryRegretInfimum reward ≤ max 0 ε :=
  le_trans
    (csInf_le (bddBelow_range_quittingStationaryMaxPositiveRegret reward)
      (Set.mem_range_self root))
    (quittingStationaryMaxPositiveRegret_le_of_isεAsymptoticNash reward root hnash)

/-- The converse of
`exists_stationaryProfile_isεAsymptoticNash_of_regretInfimum_eq_zero`: if
stationary product profiles give terminal `ε`-Nash profiles at every
accuracy, then `δ_stat = 0`.  Routes through
`quittingStationaryRegretInfimum_le_of_isεAsymptoticNash`, applied at
`ε := δ_stat / 2` to a hypothetical positive `δ_stat`. -/
theorem quittingStationaryRegretInfimum_eq_zero_of_forall_exists_isεAsymptoticNash
    [Nonempty ι] (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (hex : ∀ ε > 0, ∃ root : ι → PMF Bool,
      (quittingGame reward).IsεAsymptoticNash
        (quittingTerminalPayoff reward) ε
        (quittingStationaryProfile reward root)) :
    quittingStationaryRegretInfimum reward = 0 := by
  apply le_antisymm _ (quittingStationaryRegretInfimum_nonneg reward)
  by_contra hle
  have hlt : 0 < quittingStationaryRegretInfimum reward := not_le.mp hle
  obtain ⟨root, hroot⟩ := hex (quittingStationaryRegretInfimum reward / 2) (by linarith)
  have hbound := quittingStationaryRegretInfimum_le_of_isεAsymptoticNash reward hroot
  rw [max_eq_right (by linarith : (0 : ℝ) ≤ quittingStationaryRegretInfimum reward / 2)]
    at hbound
  linarith

/-- `δ_stat = 0` characterizes stationary approximability: it holds exactly
when stationary product profiles give terminal `ε`-Nash profiles at every
accuracy.  Combines the escape branch
(`exists_stationaryProfile_isεAsymptoticNash_of_regretInfimum_eq_zero`) with
its converse
(`quittingStationaryRegretInfimum_eq_zero_of_forall_exists_isεAsymptoticNash`). -/
theorem quittingStationaryRegretInfimum_eq_zero_iff
    [Nonempty ι] (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :
    quittingStationaryRegretInfimum reward = 0 ↔
      ∀ ε > 0, ∃ root : ι → PMF Bool,
        (quittingGame reward).IsεAsymptoticNash
          (quittingTerminalPayoff reward) ε
          (quittingStationaryProfile reward root) := by
  constructor
  · intro hzero ε hε
    exact exists_stationaryProfile_isεAsymptoticNash_of_regretInfimum_eq_zero
      reward hzero hε
  · exact quittingStationaryRegretInfimum_eq_zero_of_forall_exists_isεAsymptoticNash reward

/-! ## The gap branch: `δ_stat > 0` gives a per-profile offending player -/

/-- A witness that some player's positive stationary regret at `root` is at
least a threshold `θ`.  Packaged as a structure, rather than a bare
existential, so a negative-search filter over stationary candidates can
consume the offending player directly. -/
structure QuittingStationaryRegretWitness
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) (θ : ℝ) : Type where
  /-- The player exhibiting regret at least `θ`. -/
  who : ι
  /-- The witnessing regret bound. -/
  regret_ge : θ ≤ quittingStationaryPlayerPositiveRegret reward root who

/-- Every stationary product profile has some player attaining `g_r`, hence
some player whose positive regret is at least any lower bound of `g_r` --
in particular `δ_stat`, unconditionally: the attaining player exists
regardless of the sign of `δ_stat`, so no positivity hypothesis is needed. -/
theorem quittingStationaryRegretWitness_regretInfimum
    [Nonempty ι] (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) :
    Nonempty (QuittingStationaryRegretWitness reward root
      (quittingStationaryRegretInfimum reward)) := by
  have hbdd := bddBelow_range_quittingStationaryMaxPositiveRegret reward
  have hle : quittingStationaryRegretInfimum reward ≤
      quittingStationaryMaxPositiveRegret reward root :=
    csInf_le hbdd (Set.mem_range_self root)
  unfold quittingStationaryMaxPositiveRegret at hle
  obtain ⟨who, -, hwho⟩ :=
    Finset.exists_mem_eq_sup' Finset.univ_nonempty
      (quittingStationaryPlayerPositiveRegret reward root)
  rw [hwho] at hle
  exact ⟨who, hle⟩

/-- Corollary of `quittingStationaryRegretWitness_regretInfimum` for the case
`δ_stat > 0`: the witness is then a *genuine* obstruction, not merely a
vacuous zero bound -- its offending player's positive regret is strictly
positive.  This is the one place `hpos` actually does proof work. -/
theorem quittingStationaryRegretWitness_pos_of_regretInfimum_pos
    [Nonempty ι] (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (hpos : 0 < quittingStationaryRegretInfimum reward)
    (root : ι → PMF Bool) :
    ∃ w : QuittingStationaryRegretWitness reward root
        (quittingStationaryRegretInfimum reward),
      0 < quittingStationaryPlayerPositiveRegret reward root w.who := by
  obtain ⟨w⟩ := quittingStationaryRegretWitness_regretInfimum reward root
  exact ⟨w, lt_of_lt_of_le hpos w.regret_ge⟩

/-- The corollary a negative-search filter actually needs: once `δ_stat > 0`,
*no* stationary product profile's stationary behavior profile is a terminal
`ε`-Nash profile for any `ε < δ_stat`.  Contrapositive of
`quittingStationaryRegretInfimum_le_of_isεAsymptoticNash` against
`max 0 ε < δ_stat`, which holds however the sign of `ε` falls relative to
zero. -/
theorem quittingStationaryProfile_not_isεAsymptoticNash_of_regretInfimum_pos
    [Nonempty ι] (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (hpos : 0 < quittingStationaryRegretInfimum reward)
    {ε : ℝ} (hε : ε < quittingStationaryRegretInfimum reward)
    (root : ι → PMF Bool) :
    ¬ (quittingGame reward).IsεAsymptoticNash
        (quittingTerminalPayoff reward) ε
        (quittingStationaryProfile reward root) := by
  intro hnash
  linarith [quittingStationaryRegretInfimum_le_of_isεAsymptoticNash reward hnash,
    max_lt hpos hε]

end GameTheory
