/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.Root.FirstBranch

/-!
# Stationary quitting profiles and their root games

This file isolates the profile-level necessity statement used in the
stationary branch of quitting-game extraction.  A stationary quitting profile
is exactly its own continuation after the all-continue root action.  Its
terminal payoff vector is therefore a fixed point of the finite root
continuation game.  Moreover, if the full stationary behavior profile is a
terminal `ε`-equilibrium, then its root product action is an `ε`-Nash action
of that finite game at the actual terminal continuation vector.

Only this one-way extraction is asserted.  Root optimality at the on-path
continuation vector does not imply global terminal optimality: a behavior
deviation may eliminate absorption.  The exact counterexample is formalized
in `QuittingLocalGlobalCounterexample`.

No compactness, stationary-regime subsequence, or absorption-path structure
is introduced here.
-/

noncomputable section

namespace GameTheory

open StochasticGame

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- The stationary behavior profile generated by one product root action. -/
def quittingStationaryProfile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) :
    (quittingGame reward).BehaviorProfile :=
  (quittingGame reward).stationaryBehaviorProfile root

omit [DecidableEq ι] in
/-- A stationary profile is the splice of its root with itself as the
all-continue continuation. -/
@[simp] theorem quittingRootThenContinuationProfile_stationary
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) :
    quittingRootThenContinuationProfile reward root
        (quittingStationaryProfile reward root) =
      quittingStationaryProfile reward root := by
  funext who time history
  cases time <;> rfl

omit [DecidableEq ι] in
/-- The terminal payoff vector of a stationary profile is an exact fixed
point of its finite root continuation game. -/
theorem quittingTerminalPayoff_stationary_eq_rootExpectedPayoff
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) (who : ι) :
    quittingTerminalPayoff reward
        (quittingStationaryProfile reward root) who =
      quittingRootExpectedPayoff reward
        (fun player => quittingTerminalPayoff reward
          (quittingStationaryProfile reward root) player)
        root who := by
  simpa using
    (quittingTerminalPayoff_rootThenContinuation_eq reward root
      (quittingStationaryProfile reward root) who)

/-- Any root marginal deviation can be embedded as a behavior deviation that
returns to the same stationary continuation after the first stage. -/
theorem quittingTerminalPayoff_stationary_rootDeviation_eq
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) (who : ι) (rootDeviation : PMF Bool) :
    let profile := quittingStationaryProfile reward root
    let continuationValue : Payoff ι := fun player =>
      quittingTerminalPayoff reward profile player
    let deviation := quittingRootAndContinuationDeviation reward
      rootDeviation (profile who)
    quittingTerminalPayoff reward
        (Function.update profile who deviation) who =
      quittingRootExpectedPayoff reward continuationValue
        (Function.update root who rootDeviation) who := by
  dsimp only
  have hfull :=
    quittingTerminalPayoff_update_rootAndContinuationDeviation_eq
      reward root (quittingStationaryProfile reward root) who
      rootDeviation (quittingStationaryProfile reward root who)
  simpa using hfull

/-- **Stationary root necessity.**  A terminal `ε`-Nash stationary profile
induces an `ε`-Nash action in the finite root game whose all-continue payoff
is its actual terminal payoff vector. -/
theorem isεQuittingRootNash_of_isεAsymptoticNash_stationary
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) (ε : ℝ)
    (hnash : (quittingGame reward).IsεAsymptoticNash
      (quittingTerminalPayoff reward) ε
      (quittingStationaryProfile reward root)) :
    IsεQuittingRootNash reward
      (fun player => quittingTerminalPayoff reward
        (quittingStationaryProfile reward root) player)
      ε root := by
  intro who rootDeviation
  let profile := quittingStationaryProfile reward root
  let continuationValue : Payoff ι := fun player =>
    quittingTerminalPayoff reward profile player
  let deviation := quittingRootAndContinuationDeviation reward
    rootDeviation (profile who)
  have hbehavior := hnash who deviation
  have hdeviation :
      quittingTerminalPayoff reward
          (Function.update profile who deviation) who =
        quittingRootExpectedPayoff reward continuationValue
          (Function.update root who rootDeviation) who := by
    simpa [profile, continuationValue, deviation] using
      (quittingTerminalPayoff_stationary_rootDeviation_eq
        reward root who rootDeviation)
  have hprescribed :
      quittingTerminalPayoff reward profile who =
        quittingRootExpectedPayoff reward continuationValue root who := by
    simpa [profile, continuationValue] using
      (quittingTerminalPayoff_stationary_eq_rootExpectedPayoff
        reward root who)
  rw [hdeviation, hprescribed] at hbehavior
  exact hbehavior

end GameTheory
