/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import Mathlib.MeasureTheory.Integral.Bochner.Basic
import UniformEquilibrium.Quitting.Boundary.Repair.JointComplementarity
import UniformEquilibrium.Quitting.Classification.SoloExitPreference
import UniformEquilibrium.Quitting.Stationary.Payoff

/-!
# Quitting games with an adapted payoff process

This module is the reusable semantic carrier for Solan--Vieille's random
payoff process.  At stage `n`, a common signal reveals the current quitting
table.  Actions are adapted to the natural filtration generated by the
tables, and the payoff is the expected reward at the first nonempty quitting
coalition; nontermination pays zero.
-/

noncomputable section

namespace GameTheory

open Filter MeasureTheory StochasticGame

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- An integrably dominated, almost surely convergent process of finite
quitting payoff tables. -/
structure QuittingPayoffProcess (ι : Type) [Fintype ι] [DecidableEq ι] where
  Ω : Type
  measurableSpace : MeasurableSpace Ω
  μ : @Measure Ω measurableSpace
  probability : IsProbabilityMeasure μ
  payoff : ℕ → Ω → ({S : Finset ι // S.Nonempty} → Payoff ι)
  limit : Ω → ({S : Finset ι // S.Nonempty} → Payoff ι)
  payoff_measurable : ∀ n terminal who,
    Measurable (fun ω => payoff n ω terminal who)
  limit_measurable : ∀ terminal who,
    Measurable (fun ω => limit ω terminal who)
  integrableEnvelope : ∃ bound : Ω → ℝ,
    Integrable bound μ ∧ ∀ n ω terminal who,
      |payoff n ω terminal who| ≤ bound ω
  converges : ∀ᵐ ω ∂μ, ∀ terminal who,
    Tendsto (fun n => payoff n ω terminal who) atTop
      (nhds (limit ω terminal who))

/-- A behavioral profile driven by the common payoff signal. -/
abbrev QuittingProcessProfile (process : QuittingPayoffProcess ι) :=
  ℕ → ι → process.Ω → PMF Bool

/-- The natural filtration generated by the tables through the current
stage. -/
@[reducible] def QuittingPayoffProcess.filtration
    (process : QuittingPayoffProcess ι) (time : ℕ) :
    MeasurableSpace process.Ω :=
  ⨆ previous : Fin (time + 1), ⨆ terminal, ⨆ who,
    MeasurableSpace.comap
      (fun ω => process.payoff previous ω terminal who) inferInstance

/-- A process profile is adapted when every action probability at stage
`time` is measurable with respect to the payoff history through `time`. -/
def QuittingPayoffProcess.Adapted
    (process : QuittingPayoffProcess ι)
    (profile : QuittingProcessProfile process) : Prop :=
  ∀ time who action,
    Measurable[process.filtration time]
      (fun ω => (profile time who ω action).toReal)

/-- Expected reward at the first nonempty quitting coalition. -/
def QuittingPayoffProcess.expectedPayoff
    (process : QuittingPayoffProcess ι)
    (profile : QuittingProcessProfile process) : Payoff ι :=
  fun who => ∫ ω,
    ∑' time,
      quittingJointSurvivalWeight
          (fun stage player => profile stage player ω) 0 time *
        quittingRootAbsorbingContribution (process.payoff time ω)
          (fun player => profile time player ω) who ∂process.μ

/-- No adapted unilateral deviation improves the process payoff by more than
`ε`. -/
def QuittingPayoffProcess.IsεEquilibrium
    (process : QuittingPayoffProcess ι)
    (profile : QuittingProcessProfile process) (ε : ℝ) : Prop :=
  ∀ who (deviation : ℕ → process.Ω → PMF Bool),
    process.Adapted
      (fun time => Function.update (profile time) who (deviation time)) →
    process.expectedPayoff profile who + ε ≥
      process.expectedPayoff
        (fun time => Function.update (profile time) who (deviation time)) who

/-- The limiting table obeys unit solo exit and capped joint exit almost
surely. -/
def QuittingPayoffProcess.SoloExitAssumptions
    (process : QuittingPayoffProcess ι) : Prop :=
  ∀ᵐ ω ∂process.μ,
    QuittingUnitSoloExit (process.limit ω) ∧
      QuittingCappedJointExit (process.limit ω)

/-- The natural payoff filtration is increasing. -/
theorem QuittingPayoffProcess.filtration_mono
    (process : QuittingPayoffProcess ι) : Monotone process.filtration := by
  intro earlier later hle
  apply iSup_le
  intro previous
  let embedded : Fin (later + 1) :=
    ⟨previous, lt_of_lt_of_le previous.isLt (Nat.succ_le_succ hle)⟩
  apply iSup_le
  intro terminal
  apply iSup_le
  intro who
  exact le_iSup_of_le embedded <|
    le_iSup_of_le terminal <| le_iSup_of_le who le_rfl

/-- The natural filtration is a sub-σ-algebra of the ambient measurable
space carried by the payoff process. -/
theorem QuittingPayoffProcess.filtration_le
    (process : QuittingPayoffProcess ι) (time : ℕ) :
    process.filtration time ≤ process.measurableSpace := by
  apply iSup_le
  intro previous
  apply iSup_le
  intro terminal
  apply iSup_le
  intro who
  exact measurable_iff_comap_le.mp
    (process.payoff_measurable previous terminal who)

/-- The current payoff coordinate is measurable in the current natural
filtration. -/
theorem QuittingPayoffProcess.payoff_measurable_filtration
    (process : QuittingPayoffProcess ι) (time : ℕ)
    (terminal : {S : Finset ι // S.Nonempty}) (who : ι) :
    Measurable[process.filtration time]
      (fun ω => process.payoff time ω terminal who) := by
  apply Measurable.of_comap_le
  exact le_iSup_of_le ⟨time, Nat.lt_succ_self time⟩ <|
    le_iSup_of_le terminal <| le_iSup_of_le who le_rfl

/-- The current payoff table, as one finite product, is measurable in the
current natural filtration. -/
theorem QuittingPayoffProcess.payoffTable_measurable_filtration
    (process : QuittingPayoffProcess ι) (time : ℕ) :
    Measurable[process.filtration time] (process.payoff time) := by
  letI : MeasurableSpace process.Ω := process.filtration time
  apply measurable_pi_lambda
  intro terminal
  apply measurable_pi_lambda
  intro who
  exact process.payoff_measurable_filtration time terminal who

/-- Every stage table is measurable in the ambient payoff-process space. -/
theorem QuittingPayoffProcess.payoffTable_measurable
    (process : QuittingPayoffProcess ι) (time : ℕ) :
    @Measurable process.Ω
      ({S : Finset ι // S.Nonempty} → Payoff ι)
      process.measurableSpace inferInstance (process.payoff time) := by
  letI : MeasurableSpace process.Ω := process.measurableSpace
  apply measurable_pi_lambda
  intro terminal
  apply measurable_pi_lambda
  intro who
  exact process.payoff_measurable time terminal who

/-- The limiting table is measurable in the ambient payoff-process space. -/
theorem QuittingPayoffProcess.limitTable_measurable
    (process : QuittingPayoffProcess ι) :
    @Measurable process.Ω
      ({S : Finset ι // S.Nonempty} → Payoff ι)
      process.measurableSpace inferInstance process.limit := by
  letI : MeasurableSpace process.Ω := process.measurableSpace
  apply measurable_pi_lambda
  intro terminal
  apply measurable_pi_lambda
  intro who
  exact process.limit_measurable terminal who

/-- Coordinatewise almost-sure convergence is convergence of the whole
finite payoff table in its product topology. -/
theorem QuittingPayoffProcess.ae_tendsto_payoffTable
    (process : QuittingPayoffProcess ι) :
    ∀ᵐ ω ∂process.μ,
      Tendsto (fun time => process.payoff time ω) atTop
        (nhds (process.limit ω)) := by
  filter_upwards [process.converges] with ω hω
  rw [tendsto_pi_nhds]
  intro terminal
  rw [tendsto_pi_nhds]
  intro who
  exact hω terminal who

end GameTheory
