/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Diagnostics.Quitting.CounterexampleRegime.StoppingLaw.SourceMatchedChronologicalData
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticPositiveSlopeCausalRegression
import UniformEquilibrium.Quitting.Cycles.BlockSurvival
import UniformEquilibrium.Quitting.Terminal.TailCompression.ElementaryTailSemanticReduction

/-!
# Survival of repeated source-matched root samples

A finite list of source-matched radial reset profiles can be sampled at
specified live times and repeated as an executable periodic root sequence.
If its one-period deleted-player Continue product is strictly below one for
every player, every deleted-player survival tail vanishes.  Joint survival
then vanishes by domination.

The strict contraction is a real producer hypothesis, not a consequence of a
favorable debt chord.  The final regression uses an existing literal
two-player quitting game: resetting the mover from sure Quit to `Never`
strictly decreases its semantic debt, while repetition of the reset endpoint
has zero opponent exposure and survival identically one.
-/

noncomputable section

namespace GameTheory

open Filter Math.Probability
open scoped Topology

variable {ι : Type} [Fintype ι] [DecidableEq ι]
variable {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
variable {witness : QuittingTerminalExploitabilityWitness reward}

namespace QuittingCounterexampleStoppingLawFrontier

/-- A finite cycle of complete product roots sampled from literal
source-matched radial reset profiles. -/
def sourceMatchedRadialSampledCycle
    (frontier : QuittingCounterexampleStoppingLawFrontier witness)
    {period : ℕ}
    (rank : ℕ) (weight : {who // who ∈ frontier.active} → ℝ)
    (hweight0 : ∀ mover, 0 ≤ weight mover)
    (hweight1 : ∀ mover, weight mover ≤ 1)
    (mover : Fin period → {who // who ∈ frontier.active})
    (sampleTime : Fin period → ℕ) (phase : Fin period) : ι → PMF Bool :=
  quittingProfileLiveRoot reward
    (frontier.sourceMatchedRadialResetProfile rank (mover phase)
      (weight (mover phase)) (hweight0 (mover phase))
      (hweight1 (mover phase))) (sampleTime phase)

/-- The periodic executable sequence generated by the sampled reset roots. -/
def sourceMatchedRadialRepeatedRoots
    (frontier : QuittingCounterexampleStoppingLawFrontier witness)
    {period : ℕ}
    (rank : ℕ) (weight : {who // who ∈ frontier.active} → ℝ)
    (hweight0 : ∀ mover, 0 ≤ weight mover)
    (hweight1 : ∀ mover, weight mover ≤ 1)
    (mover : Fin period → {who // who ∈ frontier.active})
    (sampleTime : Fin period → ℕ) (phase : Fin period) :
    ℕ → ι → PMF Bool :=
  quittingCyclicRootSequence
    (frontier.sourceMatchedRadialSampledCycle rank weight hweight0 hweight1
      mover sampleTime) phase

/-- Strict one-period deleted-player contraction makes every tail of the
repeated source-matched schedule vanish. -/
theorem sourceMatchedRadialRepeatedRoots_opponentSurvival
    (frontier : QuittingCounterexampleStoppingLawFrontier witness)
    {period : ℕ}
    (rank : ℕ) (weight : {who // who ∈ frontier.active} → ℝ)
    (hweight0 : ∀ mover, 0 ≤ weight mover)
    (hweight1 : ∀ mover, weight mover ≤ 1)
    (mover : Fin period → {who // who ∈ frontier.active})
    (sampleTime : Fin period → ℕ) (phase : Fin period)
    (hcontracts : ∀ who,
      (∏ cyclePhase : Fin period,
        quittingStationaryFixedOpponentsContinueMass
          (frontier.sourceMatchedRadialSampledCycle rank weight
            hweight0 hweight1 mover sampleTime cyclePhase) who) < 1)
    (who : ι) (start : ℕ) :
    Tendsto
      (Math.survivalProduct (fun time ↦
        quittingRootOpponentContinueMass
          (frontier.sourceMatchedRadialRepeatedRoots rank weight
            hweight0 hweight1 mover sampleTime phase time) who) start)
      atTop (nhds 0) := by
  let cycle := frontier.sourceMatchedRadialSampledCycle rank weight
    hweight0 hweight1 mover sampleTime
  let reachedPhase := quittingCyclicOrbit phase start
  have hzero := tendsto_zero_quittingOpponentSurvivalWeight_cyclicRootSequence
    cycle reachedPhase who (hcontracts who)
  have heq : ∀ fuel,
      quittingOpponentSurvivalWeight
          (frontier.sourceMatchedRadialRepeatedRoots rank weight
            hweight0 hweight1 mover sampleTime phase) who start fuel =
        quittingOpponentSurvivalWeight
          (quittingCyclicRootSequence cycle reachedPhase) who 0 fuel := by
    intro fuel
    change quittingOpponentSurvivalWeight
        (quittingCyclicRootSequence cycle phase) who start fuel = _
    rw [quittingOpponentSurvivalWeight_cyclicRootSequence,
      quittingOpponentSurvivalWeight_cyclicRootSequence]
    simp only [quittingCyclicOrbit_zero, reachedPhase, cycle]
  apply hzero.congr'
  filter_upwards [] with fuel
  rw [← heq fuel]
  rfl

/-- The same contraction hypothesis also kills joint survival on every tail.
-/
theorem sourceMatchedRadialRepeatedRoots_jointSurvival
    (frontier : QuittingCounterexampleStoppingLawFrontier witness)
    {period : ℕ} (hperiod : 0 < period)
    (rank : ℕ) (weight : {who // who ∈ frontier.active} → ℝ)
    (hweight0 : ∀ mover, 0 ≤ weight mover)
    (hweight1 : ∀ mover, weight mover ≤ 1)
    (mover : Fin period → {who // who ∈ frontier.active})
    (sampleTime : Fin period → ℕ) (phase : Fin period)
    (hcontracts : ∀ who,
      (∏ cyclePhase : Fin period,
        quittingStationaryFixedOpponentsContinueMass
          (frontier.sourceMatchedRadialSampledCycle rank weight
            hweight0 hweight1 mover sampleTime cyclePhase) who) < 1)
    (start : ℕ) :
    Tendsto
      (Math.survivalProduct (fun time ↦
        quittingStationaryContinueMass
          (frontier.sourceMatchedRadialRepeatedRoots rank weight
            hweight0 hweight1 mover sampleTime phase time)) start)
      atTop (nhds 0) := by
  let player : ι := (mover ⟨0, hperiod⟩).1
  apply Math.tendsto_survivalProduct_zero_of_le
    (fun time ↦ quittingStationaryContinueMass
      (frontier.sourceMatchedRadialRepeatedRoots rank weight
        hweight0 hweight1 mover sampleTime phase time))
    (fun time ↦ quittingRootOpponentContinueMass
      (frontier.sourceMatchedRadialRepeatedRoots rank weight
        hweight0 hweight1 mover sampleTime phase time) player)
    start
  · intro time
    exact quittingStationaryContinueMass_nonneg _
  · intro time
    exact quittingStationaryContinueMass_le_fixedOpponentsContinueMass _ player
  · exact frontier.sourceMatchedRadialRepeatedRoots_opponentSurvival
      rank weight hweight0 hweight1 mover sampleTime phase hcontracts
      player start

end QuittingCounterexampleStoppingLawFrontier

/-! ## A debt-improving reset can remove rather than create exposure -/

namespace PositiveSlopeCausalRegression

open QuittingSureSetOwnerRepair

/-- Repeating the literal `Never` reset endpoint exposes no opponent of the
observer at any stage. -/
theorem endpoint_opponentClockCharge_observer_zero (time : ℕ) :
    quittingOpponentClockCharge
        (quittingProfileLiveRoot PositiveSlopeCausalRegression.reward endpoint)
        observer time = 0 := by
  have hroot :
      quittingProfileLiveRoot PositiveSlopeCausalRegression.reward endpoint =
        fun _ _ ↦ PMF.pure false := by
    simp [endpoint, quittingPureSetRoot_empty]
  rw [hroot]
  simp [quittingOpponentClockCharge, quittingRootOpponentAbsorptionMass,
    quittingRootAbsorptionMass, quittingStationaryContinueMass,
    quittingAllContinueAction]

/-- Accordingly every finite deleted-player survival product at the reset
endpoint is exactly one. -/
theorem endpoint_opponentSurvivalWeight_observer_one
    (start fuel : ℕ) :
    quittingOpponentSurvivalWeight
        (quittingProfileLiveRoot PositiveSlopeCausalRegression.reward endpoint)
        observer start fuel = 1 := by
  unfold quittingOpponentSurvivalWeight
  apply Finset.prod_eq_one
  intro offset _
  have hzero := endpoint_opponentClockCharge_observer_zero (start + offset)
  rw [quittingOpponentClockCharge_eq_one_sub] at hzero
  linarith

/-- **Semantic no-go.**  A literal whole-stopping-law reset can strictly
decrease the mover's debt while its repeated endpoint has no opponent
exposure and hence no vanishing deleted-player survival. -/
theorem debt_decreasing_reset_does_not_force_opponentExposure :
    quittingTerminalSemanticDebt
          (quittingTerminalSemanticPair
            PositiveSlopeCausalRegression.reward endpoint) mover <
        quittingTerminalSemanticDebt
          (quittingTerminalSemanticPair
            PositiveSlopeCausalRegression.reward source) mover ∧
      (∀ time,
        quittingOpponentClockCharge
          (quittingProfileLiveRoot PositiveSlopeCausalRegression.reward endpoint)
          observer time = 0) ∧
      (∀ start fuel,
        quittingOpponentSurvivalWeight
          (quittingProfileLiveRoot PositiveSlopeCausalRegression.reward endpoint)
          observer start fuel = 1) := by
  refine ⟨?_, endpoint_opponentClockCharge_observer_zero,
    endpoint_opponentSurvivalWeight_observer_one⟩
  rw [endpoint_debt_mover, source_debt_mover]
  norm_num

/-- Replacing a profile by the root sequence read from its unique live spine
preserves its complete terminal semantic pair. -/
theorem terminalSemanticPair_rootSequence_profileLiveRoot
    (profile : (quittingGame
      PositiveSlopeCausalRegression.reward).BehaviorProfile) :
    quittingTerminalSemanticPair PositiveSlopeCausalRegression.reward
        (quittingRootSequenceProfile PositiveSlopeCausalRegression.reward
          (quittingProfileLiveRoot PositiveSlopeCausalRegression.reward profile)
          0) =
      quittingTerminalSemanticPair PositiveSlopeCausalRegression.reward
        profile := by
  apply Prod.ext
  · funext who
    exact (quittingTerminalPayoff_eq_rootSequence_profileLiveRoot
      PositiveSlopeCausalRegression.reward profile who).symm
  · funext who
    change quittingContinuationBestResponseValue
        PositiveSlopeCausalRegression.reward
          (quittingRootSequenceProfile PositiveSlopeCausalRegression.reward
            (quittingProfileLiveRoot PositiveSlopeCausalRegression.reward
              profile) 0) who =
      quittingContinuationBestResponseValue
        PositiveSlopeCausalRegression.reward profile who
    simpa [quittingRootSequenceBestResponseValue] using
      (quittingContinuationBestResponseValue_eq_rootSequence_profileLiveRoot
        PositiveSlopeCausalRegression.reward profile who).symm

/-- **Candidate-tail obstruction.**  Choosing the literal reached-tail debt
makes both chronological forcings zero, but it merely copies the source's
positive exploitability into the initial candidate debt.  Thus the exact-data
constructor cannot supply the non-tautological small-initial-debt field. -/
theorem exact_source_has_zero_forcing_but_unit_initialDebt :
    let roots := quittingProfileLiveRoot PositiveSlopeCausalRegression.reward
      source
    let data := QuittingChronologicalDebtData.exactOfRoots
      PositiveSlopeCausalRegression.reward roots
    data.debt 0 mover = 1 ∧
      (∀ time, data.prescribedDefect
        PositiveSlopeCausalRegression.reward time = 0) ∧
      (∀ time, data.directDebtDefect
        PositiveSlopeCausalRegression.reward time = 0) := by
  dsimp only
  constructor
  · rw [QuittingChronologicalDebtData.exactOfRoots_debt,
      QuittingChronologicalDebtData.exactOfRoots_semanticPair,
      terminalSemanticPair_rootSequence_profileLiveRoot, source_debt_mover]
  · exact ⟨QuittingChronologicalDebtData.exactOfRoots_prescribedDefect
      PositiveSlopeCausalRegression.reward _,
      QuittingChronologicalDebtData.exactOfRoots_directDebtDefect
        PositiveSlopeCausalRegression.reward _⟩

end PositiveSlopeCausalRegression

end GameTheory
