#!/usr/bin/env python3
"""Generate the canned tables used by the sequencer's offline mock mode.

Tables are read (read-only) from the experiment results file; nothing here is
a claim about them, and mock mode never records anything.

Run:  python3 Games/games/sequencer/tools/gen_mockdata.py
Writes: Games/games/sequencer/mockdata.js
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent.parent.parent
REF = (
    REPO
    / "Experiments"
    / "singleton_collision_candidate_search"
    / "singleton_collision_candidate_search.py"
)

spec = importlib.util.spec_from_file_location("ref_search", REF)
ref = importlib.util.module_from_spec(spec)
assert spec.loader is not None
sys.modules["ref_search"] = ref
spec.loader.exec_module(ref)

results = json.loads((REF.parent / "results.json").read_text(encoding="utf-8"))


def rows(table) -> list[list[float]]:
    return [list(row) for row in table]


curated = [
    {
        "id": "curated:solan-vieille-seed",
        "name": "Solan-Vieille seed",
        "table": rows(ref.seed_table()),
        "known_score": results["seed_table"]["battery"]["score"],
        "note": (
            "Solan-Vieille 2001, Section 3. A period-two two-quitter pattern "
            "on {1,3} and {2,4} is known to settle it."
        ),
    }
]
for chain in results["chains"]:
    best = chain["best"]
    curated.append(
        {
            "id": f"curated:chain-{chain['seed']}",
            "name": f"chain-{chain['seed']} best",
            "table": rows(ref.table_from_json(best["table"])),
            "known_score": best["deep_reattack"]["score"],
            "note": (
                f"Hill-climbing chain seed {chain['seed']}; search-time score "
                f"{best['search_score']:.6f}, deep re-attack score "
                f"{best['deep_reattack']['score']:.6g} "
                f"(binding {best['deep_reattack']['binding_attack']})."
            ),
        }
    )

candidates = []
for index, chain in enumerate(results["chains"]):
    best = chain["best"]
    candidates.append(
        {
            "id": f"mock-candidate-{chain['seed']}",
            "created": "2026-01-01T00:00:00Z",
            "table": rows(ref.table_from_json(best["table"])),
            "game": "mock",
            "session": "00000000-0000-0000-0000-000000000000",
            "provenance": {"note": "canned mock record, not a real submission"},
            "evaluation": {
                "score": best["search_score"],
                "binding_attack": best["binding_attack"],
                "level": "standard",
            },
            "tier": "survivor-standard",
            "status": "proposed",
            "killed_by": None,
        }
    )

payload = {"curated": curated, "candidates": candidates}
lines = [
    "// Generated by tools/gen_mockdata.py -- do not edit by hand.",
    "// Canned payloads for offline mock mode (?mock=1). Tables are read from",
    "// Experiments/singleton_collision_candidate_search/results.json; scores",
    "// are that run's recorded numbers, reproduced here for demo only.",
    "export const MOCK_CURATED = [",
]
for entry in payload["curated"]:
    lines.append(" " + json.dumps(entry, separators=(",", ":")) + ",")
lines.append("];")
lines.append("export const MOCK_CANDIDATES = [")
for entry in payload["candidates"]:
    lines.append(" " + json.dumps(entry, separators=(",", ":")) + ",")
lines.append("];")
out = HERE.parent / "mockdata.js"
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {out}: {len(curated)} curated, {len(candidates)} candidates")
