/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.Punishment.ZeroSoloDisjunct
import UniformEquilibrium.Conjecture.UniformExistenceConjecture

/-!
# The finite-quitting conjecture

Every finite quitting game is conjectured to have a uniform-equilibrium
payoff. This file records the conjecture as a definition of a proposition and
does not assume a proof.

## What reaches the target

`exists_uniformEquilibriumPayoff_of_zeroSolo_or_admissibleCycle` proves that a
weight has a uniform-equilibrium payoff as soon as it is zero-solo *or* admits
an admissible absorbing cyclic continuation block.  Both implications are
theorems, with no gap in the deviation class — the consumed predicate
quantifies over all behavior strategies.

Those two cases are **not** exhaustive.
`not_forall_isQuittingZeroSolo_or_hasAdmissibleAbsorbingQuittingCycle` in
`UniformEquilibrium/Quitting/Boundary/Repair/DisjunctionCounterexample.lean`
refutes the disjunction outright, on
the two-coordinate weight quoted in the conjecture's own docstring below.  So
the conjecture remains a separate open proposition rather than being reduced
to a false completeness premise.

What is proved about exhaustiveness is weaker and precisely scoped:
`quittingCycle_zeroSolo_or_admissible_or_isolatedNegative` gives a
**three**-branch disjunction — zero-solo, admissible, or isolated-negative —
exhaustive over weights that admit *some* absorbing complementary cycle.  Its
branches are not mutually exclusive, the third has no sufficiency theorem, and
weights admitting no absorbing cycle at all lie outside its scope.

The truncated-ledger route is likewise only conditional.  Packages at every
positive tolerance still compile to a uniform-equilibrium payoff, but the
universal producer proposition is false even for `Bool`: a solved
zero-solo game has no such package at accuracy `1/2`.  The canonical boundary
module records a persistent-live zero-solo branch versus a supplied package
producer without claiming that this disjunction is exhaustive.

## External status of the target

Two-player quitting games are settled, and three-player quitting games follow
from Solan, *Three-Player Absorbing Games*, Math. Oper. Res. 24(3):669-698
(1999) (uniform equilibrium payoff, unconditional on payoff sign; verified
against Solan's own doctoral dissertation, the MOR journal PDF itself
unread); the open range is `n ≥ 4`.
There is a published characterization — Ashkenazi-Golan--Krasikov--Rainer--Solan,
Math. Program. 203 (2024), Theorem 3.4, after Simon (2007) and
Solan--Vieille (2001) — of when a quitting game has `ε`-equilibria for every
`ε > 0`, as a disjunction of three conditions on *strategies* rather than on
the weight.  It is not consumed here, and it is not the same trichotomy as the
one above.

One expert belief is on record against the target, and its provenance matters.
Simon, arXiv:2310.04217 (2023), writes in its Conclusion: "Also we believe
there is a counter-example for quitting games."  That is the whole of it --
one clause, no argument, no sketch, no player count -- and **the paper
carrying it was withdrawn by its author in October 2023 as flawed**.  What was
withdrawn is a proof, not an intuition, so the belief survives; it should be
weighted as an unargued sentence in a retracted preprint.  The paper's own
non-existence method does not transport here: it needs a rich action set to
carry a quadratic penalty, a control player who observes a declaration within
the stage, and an enormous cumulative-sum state space.  A quitting game has
two actions per player, one live state, and no observable but termination.

The same author's considered estimate, argued rather than asserted, points the
other way about scale.  In *The challenge of non-zero-sum stochastic games*,
IJGT 45(1) 191--204 (2016), reasoning from the cycle structure of the directed
graph of who inspires whom to quit: "it is difficult to find quitting game
counter-examples with only four players, as any directed graph on four
vertices has a very limited structure of proper cycles.  Only with five
vertices can we find a good structure of proper cycles.  However ... we would
expect a counter-example, should it exist, to have at least six players.  We
think that eight player quitting games are much more promising, but because of
the extreme number of cases generated by higher dimensions we expect a
confirmation of a counter-example to be possible only with the help of
computers."  So the operative forecast is that nothing below roughly six
players is expected to break, and that any break needs machine search.  That
is a fence on the counterexample lane, not a reason to expect the conjecture
to fail.

The statement definition means *not proved here*, not *believed true*.

## Scope

This is the conjecture for finite **quitting** games, a strict subclass of
finite stochastic games with one live state. Discharging it would **not**
discharge `uniformDeviationCapConstructorConjecture` in
`UniformExistenceConjecture.lean`, the general finite-stochastic-game problem,
for which no reduction to quitting games is known.  The implication that does
hold, from the general problem to this one, is
`quittingGame_exists_uniformEquilibriumPayoff_of_general` below.

## Open declarations

`quittingUniformEquilibriumPayoffConjecture` is the open statement in this
file. `uniformDeviationCapConstructorConjecture` records the distinct general
finite-stochastic-game problem. Neither is a theorem declaration.
-/

noncomputable section

namespace GameTheory

open StochasticGame

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- **The finite-quitting uniform-equilibrium conjecture.**

Every finite quitting game has a uniform-equilibrium payoff.

This is an open statement definition. It covers quitting games only;
the general finite-stochastic-game problem is
`uniformDeviationCapConstructorConjecture` in
`UniformExistenceConjecture.lean`
and does not follow from this.

**Do not attempt to derive this from
`exists_uniformEquilibriumPayoff_of_zeroSolo_or_admissibleCycle`.**  That
reduction is sound, but its hypothesis is *not* satisfied by every weight, so it
cannot discharge this conjecture on its own.  Witness, for `ι = Bool`:

    r({1}) = (1, -1),   r({2}) = (1, -1),   r({1,2}) = (0, 1).

Here `r₁({1}) = 1 > 0`, so the weight is not zero-solo.  It does admit
absorbing cyclic continuation blocks — for instance the single row where
coordinate `2` quits with probability one, against the value `(1, -1)`, at which
coordinate `1` has gap `-1 ≤ 0` and coordinate `2` is exactly indifferent.  But
every absorbing complementary cycle for this weight has coordinate `1` silent at
every phase, so the deleted survival product at coordinate `2` is `1`; since
`r₂({2}) = -1 < 0`, the mismatch there is `1` and no cycle is admissible.

All of that is machine-checked in
`UniformEquilibrium/Quitting/Boundary/Repair/DisjunctionCounterexample.lean`,
whose
`not_forall_isQuittingZeroSolo_or_hasAdmissibleAbsorbingQuittingCycle` refutes
the disjunction outright; this paragraph is a summary of that file, not a hand
argument.

`QuittingTwoPlayerExistence.quittingGame_exists_uniformEquilibriumPayoff_twoPlayer`
proves that this weight has a uniform-equilibrium payoff even though the table
lies outside the cycle carrier. Any complete carrier needs an additional branch
covering weights of this shape rather than an exhaustiveness proof for the
existing two. -/
def quittingUniformEquilibriumPayoffConjecture
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :
    Prop :=
  ∃ payoff : Payoff ι,
    (quittingGame reward).IsUniformEquilibriumPayoff none payoff

/-- The general conjecture implies this one, since a quitting game *is* a
finite stochastic game.

The direction that actually holds between this conjecture and the
general one, recorded so the relation between them is a theorem rather than a
remark.  The converse fails to be available: no reduction from arbitrary finite
stochastic games to quitting games is known, which is why
`quittingUniformEquilibriumPayoffConjecture` is recorded independently rather
than being derived from this. Discharging the quitting conjecture directly, by
means special to one live state, is the point of stating it separately. -/
theorem quittingGame_exists_uniformEquilibriumPayoff_of_general
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (hgeneral : ∀ (G : StochasticGame ι) [Finite G.State]
      [∀ i, Finite (G.Act i)] [∀ i, Nonempty (G.Act i)] (s₀ : G.State),
      ∃ v : Payoff ι, G.IsUniformEquilibriumPayoff s₀ v) :
    ∃ payoff : Payoff ι,
      (quittingGame reward).IsUniformEquilibriumPayoff none payoff := by
  haveI : Finite (quittingGame reward).State :=
    inferInstanceAs (Finite (Option {S : Finset ι // S.Nonempty}))
  haveI : ∀ i : ι, Finite ((quittingGame reward).Act i) :=
    fun _ => inferInstanceAs (Finite Bool)
  haveI : ∀ i : ι, Nonempty ((quittingGame reward).Act i) :=
    fun _ => inferInstanceAs (Nonempty Bool)
  exact hgeneral (quittingGame reward) none

end GameTheory
