/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
-/

import UniformEquilibrium.Diagnostics.FiniteMixedNashSupport
import UniformEquilibrium.Diagnostics.Uniform.Consequences
import UniformEquilibrium.Diagnostics.Uniform.PaddedDuplicateLotterySeparation
import UniformEquilibrium.Diagnostics.Uniform.HiddenFiberSpanCounterexample
import UniformEquilibrium.Diagnostics.Uniform.NonexistenceCertificate
import UniformEquilibrium.Diagnostics.PrivateRecommendationTargetAbsorbingLift
import UniformEquilibrium.Diagnostics.Quitting.All
import UniformEquilibrium.Diagnostics.Quitting.FiniteMenuBoundaryRegressions
import UniformEquilibrium.Diagnostics.Quitting.SinglePivotFiniteMenuRegression
import UniformEquilibrium.Diagnostics.Quitting.SinglePivotSignedNormalRegression
import UniformEquilibrium.Diagnostics.Quitting.SinglePivotNonNormalRegression
import UniformEquilibrium.Diagnostics.Quitting.SummableTailAndSingletonGapBoundaries
import UniformEquilibrium.Diagnostics.Quitting.FinFourSinglePivotActualSource
import UniformEquilibrium.Diagnostics.Quitting.FinFourSinglePivotNormalization
import UniformEquilibrium.Diagnostics.Quitting.TwoClockFiniteMenuRegression
import UniformEquilibrium.Diagnostics.Quitting.FiniteMenuSignedZeroBoundaryRegression
import UniformEquilibrium.Diagnostics.Quitting.SignedFourCycleMatrixFixtures
import UniformEquilibrium.Diagnostics.Quitting.SignedFourCycleMatrixRegimeOpenness
import UniformEquilibrium.Diagnostics.Quitting.SignedFourCycleRawSpectralFixtures
import UniformEquilibrium.Diagnostics.Quitting.SignedFourCycleNeighborhoodFixtures
import UniformEquilibrium.Diagnostics.Quitting.SignedFourCycleNeighborhood
import UniformEquilibrium.Diagnostics.Quitting.SignedFourCycleValueFixtures
import UniformEquilibrium.Diagnostics.Quitting.SignedFourCycleCoarseNonNash
import UniformEquilibrium.Diagnostics.Quitting.TwoPlayerNegativeFiniteMenuBoundary
import UniformEquilibrium.Diagnostics.Quitting.PivotRepairSignedThirdEndpoint
import UniformEquilibrium.Diagnostics.Quitting.PivotRepairNonattainedZeroLP
import UniformEquilibrium.Diagnostics.Quitting.PivotRepairNonattainedAllLaws
import UniformEquilibrium.Diagnostics.Quitting.PivotRepairRationalFixture
import UniformEquilibrium.Diagnostics.Quitting.PivotRepairRationalLowerBound
import UniformEquilibrium.Diagnostics.Quitting.PivotRepairRationalOptimizer
import UniformEquilibrium.Diagnostics.Quitting.PivotRepairRationalOptimality
import UniformEquilibrium.Diagnostics.Quitting.PivotRepairRationalResponseCoefficients
import UniformEquilibrium.Diagnostics.Quitting.PivotRepairRationalSequentialReplacement
import UniformEquilibrium.Diagnostics.Quitting.AbsorptionWeightedZeroChargeRampBoundary
import UniformEquilibrium.Diagnostics.Quitting.AbsorptionWeightedRareInferiorActionBoundary
import UniformEquilibrium.Diagnostics.Quitting.FinFourActualPrefixHazard
import UniformEquilibrium.Diagnostics.Quitting.LateResetChildCapPinExit

/-!
# Integrated diagnostics umbrella

This umbrella owns the exhaustive diagnostics inventory.  Production modules
should import the narrow declaration files they use; `UniformEquilibrium` is
the production umbrella and deliberately does not pull this inventory in.
-/
