/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.Examples.BlockPair.FourPlayerPairedSingleton
import UniformEquilibrium.Quitting.Examples.BlockPair.FourPlayerPairedSingletonTripleInverse
import UniformEquilibrium.Quitting.Examples.BlockPair.FourPlayerPairedSingletonPeriodTwo
import UniformEquilibrium.Quitting.Examples.BlockPair.FourPlayerPairedSingletonBlockCertificate
import UniformEquilibrium.Quitting.Examples.BlockPair.FourPlayerPairedSingletonPeriodTwoStationary
import UniformEquilibrium.Quitting.Examples.BlockPair.FourPlayerPairedSingletonLCP
import UniformEquilibrium.Quitting.Examples.BlockPair.FourPlayerPairedSingletonResidualHard
import UniformEquilibrium.Quitting.Examples.BlockPair.K11LocalValue
import UniformEquilibrium.Quitting.Examples.BlockPair.K11OpponentLocalValue
import UniformEquilibrium.Quitting.Examples.BlockPair.K11ActiveEquationInterval
import UniformEquilibrium.Quitting.Examples.BlockPair.PredecessorComposition
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedResponseQuotientMatrix
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedResponseQuotientClass
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedResponseQuotientAnnulus
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedResponseQuotientSameProfile
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedResponseQuotientCoordinates
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedResponseQuotientAsymmetry
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedAdditiveStationaryBoundary
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedCubicStationaryExample
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedCubicRewardClasses
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedCubicDeterministicObstruction
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedCubicActiveJacobian
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedCubicLocalPersistence
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedCubicLocalPersistenceStrategic
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedCollisionRewardExistence
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedCollisionRewardBoundary
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedCollisionRewardFiniteCalendar
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedCollisionRewardCalibration
import UniformEquilibrium.Quitting.Examples.BlockPair.PairedCollisionRewardHorizon

/-!
# Four-player block-pair examples

This umbrella exports the exact algebraic and game-theoretic results for the
four-player block-pair examples, including the paired-singleton stationary
and period-two completions and the supporting period-eleven algebra.
-/
