/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.Examples.BlockPair.K11System
import Mathlib.Data.Fintype.Fin
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.Ring

/-!
# Exact predecessor charts for the block-pair game

This file begins the low-dimensional chart formalization.
The one-phase indifference functions are defined directly from the public
terminal table.  Their expanded forms are then used to prove exact rational
predecessor formulas for support masks 9 and 10.
-/

noncomputable section

namespace GameTheory.BlockPairCharts

open BlockPairK11

/-- A computation-friendly presentation of the public terminal table.  The
fallback rows are unreachable for `QuitterMask` and `Player`; they make the
helper total on naturals. -/
def terminalRewardNat : ℕ → ℕ → ℚ
  | 0, _ => 0
  | 1, 0 => -2
  | 1, 1 => 8
  | 1, _ => 0
  | 2, 0 => 4
  | 2, 1 => 2
  | 2, _ => 0
  | 3, 0 => -5
  | 3, 1 => -1
  | 3, 2 => -1
  | 3, _ => 2
  | 4, 0 => -4
  | 4, 1 => 0
  | 4, 2 => 2
  | 4, _ => 8
  | 5, 0 => 0
  | 5, 1 => 4
  | 5, 2 => 0
  | 5, _ => -4
  | 6, 0 => -7
  | 6, 1 => 0
  | 6, 2 => 6
  | 6, _ => 3
  | 7, 0 => -6
  | 7, 1 => 1
  | 7, 2 => -1
  | 7, _ => -3
  | 8, 0 => -4
  | 8, 1 => 0
  | 8, 2 => 8
  | 8, _ => 2
  | 9, 0 => -6
  | 9, 1 => 3
  | 9, 2 => 5
  | 9, _ => 6
  | 10, 0 => -2
  | 10, 1 => 6
  | 10, 2 => 1
  | 10, _ => 2
  | 11, 0 => -8
  | 11, 1 => 3
  | 11, 2 => 1
  | 11, _ => 4
  | 12, 0 => 1
  | 12, 1 => 0
  | 12, 2 => 3
  | 12, _ => 2
  | 13, 0 => -7
  | 13, 1 => -3
  | 13, 2 => 0
  | 13, _ => 0
  | 14, 0 => -2
  | 14, 1 => 0
  | 14, 2 => 6
  | 14, _ => 0
  | 15, 0 => -10
  | 15, 1 => -6
  | 15, 2 => 1
  | 15, _ => -1
  | _, _ => 0

/-- `terminalRewardNat` is exactly the public terminal table on its finite
domain. -/
@[simp] theorem terminalTable_eq_terminalRewardNat
    (mask : QuitterMask) (who : Player) :
    terminalTable mask who = terminalRewardNat mask.val who.val := by
  fin_cases mask <;> fin_cases who <;> decide

def realSum : {count : ℕ} → (Fin count → ℝ) → ℝ
  | 0, _ => 0
  | count + 1, term =>
      realSum (fun index ↦ term index.castSucc) + term (Fin.last count)

def realProduct : {count : ℕ} → (Fin count → ℝ) → ℝ
  | 0, _ => 1
  | count + 1, factor =>
      realProduct (fun index ↦ factor index.castSucc) *
        factor (Fin.last count)

def actionFactor (hazard : Player → ℝ) (mask : QuitterMask)
    (omitted : Option Player) (player : Player) : ℝ :=
  if omitted = some player then 1
  else if maskHasPlayer mask player then hazard player
  else 1 - hazard player

def maskProbability (hazard : Player → ℝ) (mask : QuitterMask)
    (omitted : Option Player := none) : ℝ :=
  realProduct fun player : Player ↦
    actionFactor hazard mask omitted player

/-- Payoff from quitting now against fixed opponent hazards. -/
def opponentQuitValue (hazard : Player → ℝ) (who : Player) : ℝ :=
  realSum fun mask : QuitterMask ↦
    if maskHasPlayer mask who then 0
    else
      (terminalTable (maskWithPlayer mask who) who : ℝ) *
        maskProbability hazard mask (some who)

/-- Absorbing payoff generated by the opponents when `who` continues. -/
def opponentAbsorbingContribution
    (hazard : Player → ℝ) (who : Player) : ℝ :=
  realSum fun mask : QuitterMask ↦
    if mask.val = 0 || maskHasPlayer mask who then 0
    else
      (terminalTable mask who : ℝ) *
        maskProbability hazard mask (some who)

def opponentSurvival (hazard : Player → ℝ) (who : Player) : ℝ :=
  maskProbability hazard 0 (some who)

/-- The one-phase predecessor value obtained by continuing at the current
phase and then receiving `successor` if every opponent also continues. -/
def predecessorValue (hazard successor : Player → ℝ) (who : Player) : ℝ :=
  opponentAbsorbingContribution hazard who +
    opponentSurvival hazard who * successor who

/-- One-phase quit-minus-continue difference at successor value `successor`. -/
def difference (hazard successor : Player → ℝ) (who : Player) : ℝ :=
  opponentQuitValue hazard who - predecessorValue hazard successor who

theorem predecessorValue_eq_quit_of_difference_eq_zero
    {hazard successor : Player → ℝ} {who : Player}
    (hzero : difference hazard successor who = 0) :
    predecessorValue hazard successor who = opponentQuitValue hazard who := by
  exact (sub_eq_zero.mp hzero).symm

/-- Expanded indifference polynomials from the terminal table. -/
def expandedDifference (hazard successor : Player → ℝ) :
    Player → ℝ := ![
  successor 0 * hazard 1 * hazard 2 * hazard 3
    - successor 0 * hazard 1 * hazard 2
    - successor 0 * hazard 1 * hazard 3
    + successor 0 * hazard 1
    - successor 0 * hazard 2 * hazard 3
    + successor 0 * hazard 2 + successor 0 * hazard 3 - successor 0
    + 4 * hazard 1 * hazard 2 + 3 * hazard 1 * hazard 3
    - 7 * hazard 1 - 12 * hazard 2 * hazard 3
    + 6 * hazard 2 - 2,
  successor 1 * hazard 0 * hazard 2 * hazard 3
    - successor 1 * hazard 0 * hazard 2
    - successor 1 * hazard 0 * hazard 3
    + successor 1 * hazard 0
    - successor 1 * hazard 2 * hazard 3
    + successor 1 * hazard 2 + successor 1 * hazard 3 - successor 1
    - 5 * hazard 0 * hazard 2 * hazard 3
    + 8 * hazard 0 * hazard 2 + 5 * hazard 0 * hazard 3
    - 11 * hazard 0 - 4 * hazard 2 * hazard 3
    - 2 * hazard 2 + 4 * hazard 3 + 2,
  successor 2 * hazard 0 * hazard 1 * hazard 3
    - successor 2 * hazard 0 * hazard 1
    - successor 2 * hazard 0 * hazard 3
    + successor 2 * hazard 0
    - successor 2 * hazard 1 * hazard 3
    + successor 2 * hazard 1 + successor 2 * hazard 3 - successor 2
    - hazard 0 * hazard 1 * hazard 3 - 4 * hazard 0 * hazard 1
    + 2 * hazard 0 * hazard 3 - 2 * hazard 0
    + 6 * hazard 1 * hazard 3 + 4 * hazard 1
    - 7 * hazard 3 + 2,
  successor 3 * hazard 0 * hazard 1 * hazard 2
    - successor 3 * hazard 0 * hazard 1
    - successor 3 * hazard 0 * hazard 2
    + successor 3 * hazard 0
    - successor 3 * hazard 1 * hazard 2
    + successor 3 * hazard 1 + successor 3 * hazard 2 - successor 3
    - hazard 0 * hazard 1 * hazard 2 - 4 * hazard 0 * hazard 1
    + 6 * hazard 0 * hazard 2 + 4 * hazard 0
    + 3 * hazard 1 * hazard 2 - 8 * hazard 2 + 2
]

/-- Direct finite expansion of the terminal table gives the four chart
polynomials used in the support-transition analysis. -/
theorem difference_eq_expanded
    (hazard successor : Player → ℝ) (who : Player) :
    difference hazard successor who =
      expandedDifference hazard successor who := by
  fin_cases who <;>
    simp +decide [difference, predecessorValue, opponentQuitValue,
      opponentAbsorbingContribution, opponentSurvival, maskProbability,
      actionFactor, realSum, realProduct, maskWithPlayer,
      expandedDifference, terminalRewardNat] <;>
    ring

/-- Rational support-9 hazard chart, with active players 0 and 3. -/
def supportNineHazard (successor : Player → ℝ) : Player → ℝ := ![
  (successor 3 - 2) / (successor 3 + 4),
  0,
  0,
  1 + 2 / successor 0
]

/-- The explicit predecessor-value chart for support mask 9. -/
def supportNineValue (successor : Player → ℝ) : Player → ℝ :=
  let e := supportNineHazard successor 0
  let h := supportNineHazard successor 3
  ![
    -2 - 4 * h,
    e * (8 - 5 * h) + (1 - e) * (1 - h) * successor 1,
    h * (8 - 3 * e) + (1 - e) * (1 - h) * successor 2,
    2 + 4 * e
  ]

/-- The direct one-phase expectation agrees with the mask-9 predecessor
chart, before using active indifference to simplify its active coordinates. -/
theorem supportNine_predecessorValue
    (successor : Player → ℝ)
    (hzero : successor 0 ≠ 0)
    (hthree : successor 3 + 4 ≠ 0) :
    predecessorValue (supportNineHazard successor) successor =
      supportNineValue successor := by
  funext who
  fin_cases who <;>
    simp +decide [predecessorValue, opponentAbsorbingContribution,
      opponentSurvival, maskProbability, actionFactor, realSum, realProduct,
      supportNineHazard, supportNineValue, terminalRewardNat] <;>
    field_simp <;> ring

theorem supportNine_active
    (successor : Player → ℝ)
    (hzero : successor 0 ≠ 0)
    (hthree : successor 3 + 4 ≠ 0) :
    difference (supportNineHazard successor) successor 0 = 0 ∧
      difference (supportNineHazard successor) successor 3 = 0 := by
  rw [difference_eq_expanded, difference_eq_expanded]
  constructor <;>
    simp [expandedDifference, supportNineHazard] <;>
    field_simp <;> ring

theorem supportNine_active_values
    (successor : Player → ℝ)
    (hzero : successor 0 ≠ 0)
    (hthree : successor 3 + 4 ≠ 0) :
    supportNineValue successor 0 = -6 - 8 / successor 0 ∧
      supportNineValue successor 3 =
        6 * successor 3 / (successor 3 + 4) := by
  constructor <;>
    simp [supportNineValue, supportNineHazard] <;>
    field_simp <;> ring

/-- Rational support-10 hazard chart, with active players 1 and 3. -/
def supportTenHazard (successor : Player → ℝ) : Player → ℝ := ![
  0,
  (successor 3 - 2) / successor 3,
  0,
  (successor 1 - 2) / (successor 1 + 4)
]

/-- The explicit predecessor-value chart for support mask 10. -/
def supportTenValue (successor : Player → ℝ) : Player → ℝ :=
  let b := supportTenHazard successor 1
  let d := supportTenHazard successor 3
  let survival := (1 - b) * (1 - d)
  ![
    4 * b - 4 * d - 2 * b * d + survival * successor 0,
    2 * b + 4 * b * d + survival * successor 1,
    8 * d - 7 * b * d + survival * successor 2,
    2 * d + survival * successor 3
  ]

/-- The direct one-phase expectation agrees with the mask-10 predecessor
chart. -/
theorem supportTen_predecessorValue
    (successor : Player → ℝ)
    (hone : successor 1 + 4 ≠ 0)
    (hthree : successor 3 ≠ 0) :
    predecessorValue (supportTenHazard successor) successor =
      supportTenValue successor := by
  funext who
  fin_cases who <;>
    simp +decide [predecessorValue, opponentAbsorbingContribution,
      opponentSurvival, maskProbability, actionFactor, realSum, realProduct,
      supportTenHazard, supportTenValue, terminalRewardNat] <;>
    field_simp <;> ring

theorem supportTen_active
    (successor : Player → ℝ)
    (hone : successor 1 + 4 ≠ 0)
    (hthree : successor 3 ≠ 0) :
    difference (supportTenHazard successor) successor 1 = 0 ∧
      difference (supportTenHazard successor) successor 3 = 0 := by
  rw [difference_eq_expanded, difference_eq_expanded]
  constructor <;>
    simp [expandedDifference, supportTenHazard] <;>
    field_simp <;> ring

theorem supportTen_active_values
    (successor : Player → ℝ)
    (hone : successor 1 + 4 ≠ 0)
    (hthree : successor 3 ≠ 0) :
    supportTenValue successor 1 =
        6 * successor 1 / (successor 1 + 4) ∧
      supportTenValue successor 3 = 2 := by
  constructor <;>
    simp [supportTenValue, supportTenHazard] <;>
    field_simp <;> ring

/-! ## Three-player rational charts -/

/-- The middle denominator in the support-7 triangular solve. -/
def supportSevenMiddle (successor : Player → ℝ) : ℝ :=
  3 * successor 0 + 5 * successor 2 + 8

/-- The final coefficient in the support-7 triangular solve. -/
def supportSevenCoefficient (successor : Player → ℝ) : ℝ :=
  18 * successor 0 - successor 1 * successor 2 - 22 * successor 1 +
    38 * successor 2 + 224

/-- Rational support-7 hazard chart, with active players 0, 1, and 2. -/
def supportSevenHazard (successor : Player → ℝ) : Player → ℝ := ![
  -((successor 1 - 2) * (successor 2 + 22)) /
    supportSevenCoefficient successor,
  (successor 2 - 2) / (successor 2 + 4),
  3 * (2 * successor 0 + 3 * successor 2 - 2) /
    (2 * supportSevenMiddle successor),
  0
]

/-- The exact predecessor-value chart for support mask 7. -/
def supportSevenValue (successor : Player → ℝ) : Player → ℝ :=
  let x₀ := supportSevenHazard successor 0
  let x₁ := supportSevenHazard successor 1
  let x₂ := supportSevenHazard successor 2
  let survival := (1 - x₀) * (1 - x₁) * (1 - x₂)
  ![
    -3 * x₁ * x₂ - 3 * x₁ + 2 * x₂ - 2,
    4 * x₀ * x₂ - 3 * x₀ - 2 * x₂ + 2,
    -5 * x₀ * x₁ - 2 * x₀ + 4 * x₁ + 2,
    4 * x₀ * x₁ * x₂ + 2 * x₀ * x₁ - 12 * x₀ * x₂ -
      5 * x₁ * x₂ + 8 * x₂ + survival * successor 3
  ]

theorem supportSeven_active
    (successor : Player → ℝ)
    (htwo : successor 2 + 4 ≠ 0)
    (hmiddle : supportSevenMiddle successor ≠ 0)
    (hcoefficient : supportSevenCoefficient successor ≠ 0) :
    difference (supportSevenHazard successor) successor 0 = 0 ∧
      difference (supportSevenHazard successor) successor 1 = 0 ∧
      difference (supportSevenHazard successor) successor 2 = 0 := by
  constructor
  · rw [difference_eq_expanded]
    simp [expandedDifference, supportSevenHazard]
    field_simp
    simp only [supportSevenMiddle]
    ring
  constructor
  · rw [difference_eq_expanded]
    simp [expandedDifference, supportSevenHazard]
    field_simp
    simp only [supportSevenMiddle, supportSevenCoefficient]
    ring
  · rw [difference_eq_expanded]
    simp [expandedDifference, supportSevenHazard]
    field_simp
    simp only [supportSevenCoefficient]
    ring

/-- The terminal-table expectation agrees with formula (38) on the rational
support-7 denominator domain. -/
theorem supportSeven_predecessorValue
    (successor : Player → ℝ)
    (htwo : successor 2 + 4 ≠ 0)
    (hmiddle : supportSevenMiddle successor ≠ 0)
    (hcoefficient : supportSevenCoefficient successor ≠ 0) :
    predecessorValue (supportSevenHazard successor) successor =
      supportSevenValue successor := by
  funext who
  fin_cases who <;>
    simp +decide [predecessorValue, opponentAbsorbingContribution,
      opponentSurvival, maskProbability, actionFactor, realSum, realProduct,
      supportSevenHazard, supportSevenValue,
      terminalRewardNat] <;>
    field_simp <;>
    simp only [supportSevenMiddle, supportSevenCoefficient] <;>
    ring

/-- The middle denominator in the support-14 triangular solve. -/
def supportFourteenMiddle (successor : Player → ℝ) : ℝ :=
  5 * successor 1 + 3 * successor 2 + 2

/-- The numerator of player 2's support-14 hazard. -/
def supportFourteenNumerator (successor : Player → ℝ) : ℝ :=
  5 * successor 1 * successor 3 - 20 * successor 1 -
    12 * successor 2 + 26 * successor 3 - 8

/-- The final coefficient in the support-14 triangular solve. -/
def supportFourteenCoefficient (successor : Player → ℝ) : ℝ :=
  5 * successor 1 * successor 3 - 65 * successor 1 -
    30 * successor 2 + 26 * successor 3 - 98

/-- Rational support-14 hazard chart, with active players 1, 2, and 3. -/
def supportFourteenHazard (successor : Player → ℝ) : Player → ℝ := ![
  0,
  (5 * successor 1 + 6 * successor 2 - 22) /
    (2 * supportFourteenMiddle successor),
  supportFourteenNumerator successor / supportFourteenCoefficient successor,
  (successor 1 - 2) / (successor 1 + 4)
]

/-- The exact predecessor-value chart for support mask 14. -/
def supportFourteenValue (successor : Player → ℝ) : Player → ℝ :=
  let x₁ := supportFourteenHazard successor 1
  let x₂ := supportFourteenHazard successor 2
  let x₃ := supportFourteenHazard successor 3
  let survival := (1 - x₁) * (1 - x₂) * (1 - x₃)
  ![
    2 * x₁ * x₂ * x₃ - 7 * x₁ * x₂ - 2 * x₁ * x₃ + 4 * x₁ +
      9 * x₂ * x₃ - 4 * x₂ - 4 * x₃ + survival * successor 0,
    2 * (1 - x₂) * (2 * x₃ + 1),
    -x₁ * x₃ + 4 * x₁ + x₃ + 2,
    2 * (1 - x₁ * x₂)
  ]

theorem supportFourteen_active
    (successor : Player → ℝ)
    (hone : successor 1 + 4 ≠ 0)
    (hmiddle : supportFourteenMiddle successor ≠ 0)
    (hcoefficient : supportFourteenCoefficient successor ≠ 0) :
    difference (supportFourteenHazard successor) successor 1 = 0 ∧
      difference (supportFourteenHazard successor) successor 2 = 0 ∧
      difference (supportFourteenHazard successor) successor 3 = 0 := by
  constructor
  · rw [difference_eq_expanded]
    simp [expandedDifference, supportFourteenHazard]
    field_simp
    simp only [supportFourteenNumerator, supportFourteenCoefficient]
    ring
  constructor
  · rw [difference_eq_expanded]
    simp [expandedDifference, supportFourteenHazard]
    field_simp
    simp only [supportFourteenMiddle]
    ring
  · rw [difference_eq_expanded]
    simp [expandedDifference, supportFourteenHazard]
    field_simp
    simp only [supportFourteenMiddle, supportFourteenNumerator,
      supportFourteenCoefficient]
    ring

/-- The terminal-table expectation agrees with formula (39) on the rational
support-14 denominator domain. -/
theorem supportFourteen_predecessorValue
    (successor : Player → ℝ)
    (hone : successor 1 + 4 ≠ 0)
    (hmiddle : supportFourteenMiddle successor ≠ 0)
    (hcoefficient : supportFourteenCoefficient successor ≠ 0) :
    predecessorValue (supportFourteenHazard successor) successor =
      supportFourteenValue successor := by
  funext who
  fin_cases who <;>
    simp +decide [predecessorValue, opponentAbsorbingContribution,
      opponentSurvival, maskProbability, actionFactor, realSum, realProduct,
      supportFourteenHazard, supportFourteenValue,
      terminalRewardNat] <;>
    field_simp <;>
    simp only [supportFourteenMiddle, supportFourteenNumerator,
      supportFourteenCoefficient] <;>
    ring

/-! ## Quadratic three-player charts -/

/-- Denominator of player 0's hazard in the support-13 chart. -/
def supportThirteenZeroDenominator
    (successor : Player → ℝ) (z : ℝ) : ℝ :=
  (successor 2 - 2) * (z - 1)

/-- Denominator of player 2's hazard in the support-13 chart. -/
def supportThirteenTwoDenominator
    (successor : Player → ℝ) (z : ℝ) : ℝ :=
  successor 0 * z - successor 0 + 12 * z - 6

def supportThirteenA (successor : Player → ℝ) : ℝ :=
  2 * successor 0 * successor 2 - 29 * successor 0 +
    36 * successor 2 - 30 * successor 3 - 192

def supportThirteenB (successor : Player → ℝ) : ℝ :=
  -4 * successor 0 * successor 2 + 33 * successor 0 -
    52 * successor 2 + 10 * successor 3 + 194

def supportThirteenC (successor : Player → ℝ) : ℝ :=
  2 * successor 0 * successor 2 - 4 * successor 0 +
    16 * successor 2 - 32

/-- The quadratic compatibility polynomial for support mask 13. -/
def supportThirteenPolynomial
    (successor : Player → ℝ) (z : ℝ) : ℝ :=
  supportThirteenA successor * z ^ 2 +
    supportThirteenB successor * z + supportThirteenC successor

/-- The support-13 hazards on the sheet parameterized by `z = x₃`. -/
def supportThirteenHazard
    (successor : Player → ℝ) (z : ℝ) : Player → ℝ := ![
  (successor 2 * z - successor 2 - 7 * z + 2) /
    supportThirteenZeroDenominator successor z,
  0,
  (successor 0 * z - successor 0 - 2) /
    supportThirteenTwoDenominator successor z,
  z
]

theorem supportThirteen_zero_two_active
    (successor : Player → ℝ) (z : ℝ)
    (hzero : supportThirteenZeroDenominator successor z ≠ 0)
    (htwo : supportThirteenTwoDenominator successor z ≠ 0) :
    difference (supportThirteenHazard successor z) successor 0 = 0 ∧
      difference (supportThirteenHazard successor z) successor 2 = 0 := by
  constructor
  · rw [difference_eq_expanded]
    simp [expandedDifference, supportThirteenHazard]
    field_simp
    simp only [supportThirteenTwoDenominator]
    ring
  · rw [difference_eq_expanded]
    simp [expandedDifference, supportThirteenHazard]
    field_simp
    simp only [supportThirteenZeroDenominator]
    ring

/-- After solving the first two active equations, the third is exactly the
quadratic compatibility equation (40). -/
theorem supportThirteen_difference_three
    (successor : Player → ℝ) (z : ℝ)
    (hzero : supportThirteenZeroDenominator successor z ≠ 0)
    (htwo : supportThirteenTwoDenominator successor z ≠ 0) :
    difference (supportThirteenHazard successor z) successor 3 =
      2 * supportThirteenPolynomial successor z /
        (supportThirteenZeroDenominator successor z *
          supportThirteenTwoDenominator successor z) := by
  rw [difference_eq_expanded]
  simp [expandedDifference, supportThirteenHazard]
  field_simp
  simp only [supportThirteenZeroDenominator,
    supportThirteenTwoDenominator, supportThirteenPolynomial,
    supportThirteenA, supportThirteenB, supportThirteenC]
  ring

theorem supportThirteen_active
    (successor : Player → ℝ) (z : ℝ)
    (hzero : supportThirteenZeroDenominator successor z ≠ 0)
    (htwo : supportThirteenTwoDenominator successor z ≠ 0)
    (hpolynomial : supportThirteenPolynomial successor z = 0) :
    difference (supportThirteenHazard successor z) successor 0 = 0 ∧
      difference (supportThirteenHazard successor z) successor 2 = 0 ∧
      difference (supportThirteenHazard successor z) successor 3 = 0 := by
  obtain ⟨hactiveZero, hactiveTwo⟩ :=
    supportThirteen_zero_two_active successor z hzero htwo
  refine ⟨hactiveZero, hactiveTwo, ?_⟩
  rw [supportThirteen_difference_three successor z hzero htwo,
    hpolynomial]
  simp

/-- The exact predecessor-value chart for support mask 13. -/
def supportThirteenValue
    (successor : Player → ℝ) (z : ℝ) : Player → ℝ :=
  let x₀ := supportThirteenHazard successor z 0
  let x₂ := supportThirteenHazard successor z 2
  let survival := (1 - x₀) * (1 - x₂) * (1 - z)
  ![
    -3 * x₂ * z + 2 * x₂ - 4 * z - 2,
    -x₀ * (2 * x₂ * z + 4 * x₂ + 5 * z - 8) +
      survival * successor 1,
    (1 - x₀) * (z + 2),
    2 * (1 + 2 * x₀ - 3 * x₀ * x₂)
  ]

/-- On a root of `P₁₃`, the terminal-table expectation agrees with the
algebraic predecessor chart (42). -/
theorem supportThirteen_predecessorValue
    (successor : Player → ℝ) (z : ℝ)
    (hzero : supportThirteenZeroDenominator successor z ≠ 0)
    (htwo : supportThirteenTwoDenominator successor z ≠ 0)
    (hpolynomial : supportThirteenPolynomial successor z = 0) :
    predecessorValue (supportThirteenHazard successor z) successor =
      supportThirteenValue successor z := by
  have hactive := supportThirteen_active successor z hzero htwo hpolynomial
  funext who
  fin_cases who
  · change predecessorValue (supportThirteenHazard successor z) successor 0 =
      supportThirteenValue successor z 0
    rw [predecessorValue_eq_quit_of_difference_eq_zero hactive.1]
    simp +decide [opponentQuitValue, maskProbability, actionFactor, realSum,
      realProduct, maskWithPlayer, supportThirteenHazard, supportThirteenValue,
      terminalRewardNat]
    ring
  · change predecessorValue (supportThirteenHazard successor z) successor 1 =
      supportThirteenValue successor z 1
    simp +decide [predecessorValue, opponentAbsorbingContribution,
      opponentSurvival, maskProbability, actionFactor, realSum, realProduct,
      supportThirteenHazard, supportThirteenValue, terminalRewardNat]
    ring
  · change predecessorValue (supportThirteenHazard successor z) successor 2 =
      supportThirteenValue successor z 2
    rw [predecessorValue_eq_quit_of_difference_eq_zero hactive.2.1]
    simp +decide [opponentQuitValue, maskProbability, actionFactor, realSum,
      realProduct, maskWithPlayer, supportThirteenHazard, supportThirteenValue,
      terminalRewardNat]
    ring
  · change predecessorValue (supportThirteenHazard successor z) successor 3 =
      supportThirteenValue successor z 3
    rw [predecessorValue_eq_quit_of_difference_eq_zero hactive.2.2]
    simp +decide [opponentQuitValue, maskProbability, actionFactor, realSum,
      realProduct, maskWithPlayer, supportThirteenHazard, supportThirteenValue,
      terminalRewardNat]
    ring

/-- The denominator controlled by player 0's successor coordinate in the
support-11 chart. -/
def supportElevenZeroDenominator
    (successor : Player → ℝ) (z : ℝ) : ℝ :=
  successor 0 * z - successor 0 - 3 * z + 7

/-- The denominator controlled by player 1's successor coordinate in the
support-11 chart. -/
def supportElevenOneDenominator
    (successor : Player → ℝ) (z : ℝ) : ℝ :=
  successor 1 * z - successor 1 - 5 * z + 11

def supportElevenA (successor : Player → ℝ) : ℝ :=
  2 * successor 0 * successor 1 - 10 * successor 0 -
    18 * successor 1 - 27 * successor 3 - 18

def supportElevenB (successor : Player → ℝ) : ℝ :=
  -4 * successor 0 * successor 1 + 32 * successor 0 +
    68 * successor 1 + 108 * successor 3 - 16

def supportElevenC (successor : Player → ℝ) : ℝ :=
  2 * successor 0 * successor 1 - 22 * successor 0 -
    50 * successor 1 - 81 * successor 3 + 226

/-- The quadratic compatibility polynomial for support mask 11. -/
def supportElevenPolynomial
    (successor : Player → ℝ) (z : ℝ) : ℝ :=
  supportElevenA successor * z ^ 2 +
    supportElevenB successor * z + supportElevenC successor

/-- The support-11 hazards on the sheet parameterized by `z = x₃`. -/
def supportElevenHazard
    (successor : Player → ℝ) (z : ℝ) : Player → ℝ := ![
  (successor 1 * z - successor 1 + 4 * z + 2) /
    supportElevenOneDenominator successor z,
  (successor 0 * z - successor 0 - 2) /
    supportElevenZeroDenominator successor z,
  0,
  z
]

theorem supportEleven_zero_one_active
    (successor : Player → ℝ) (z : ℝ)
    (hzero : supportElevenZeroDenominator successor z ≠ 0)
    (hone : supportElevenOneDenominator successor z ≠ 0) :
    difference (supportElevenHazard successor z) successor 0 = 0 ∧
      difference (supportElevenHazard successor z) successor 1 = 0 := by
  constructor
  · rw [difference_eq_expanded]
    simp [expandedDifference, supportElevenHazard]
    field_simp
    simp only [supportElevenZeroDenominator]
    ring
  · rw [difference_eq_expanded]
    simp [expandedDifference, supportElevenHazard]
    field_simp
    simp only [supportElevenOneDenominator]
    ring

/-- After solving the first two active equations, the third is exactly the
quadratic compatibility equation (43). -/
theorem supportEleven_difference_three
    (successor : Player → ℝ) (z : ℝ)
    (hzero : supportElevenZeroDenominator successor z ≠ 0)
    (hone : supportElevenOneDenominator successor z ≠ 0) :
    difference (supportElevenHazard successor z) successor 3 =
      supportElevenPolynomial successor z /
        (supportElevenZeroDenominator successor z *
          supportElevenOneDenominator successor z) := by
  rw [difference_eq_expanded]
  simp [expandedDifference, supportElevenHazard]
  field_simp
  simp only [supportElevenZeroDenominator, supportElevenOneDenominator,
    supportElevenPolynomial, supportElevenA, supportElevenB, supportElevenC]
  ring

theorem supportEleven_active
    (successor : Player → ℝ) (z : ℝ)
    (hzero : supportElevenZeroDenominator successor z ≠ 0)
    (hone : supportElevenOneDenominator successor z ≠ 0)
    (hpolynomial : supportElevenPolynomial successor z = 0) :
    difference (supportElevenHazard successor z) successor 0 = 0 ∧
      difference (supportElevenHazard successor z) successor 1 = 0 ∧
      difference (supportElevenHazard successor z) successor 3 = 0 := by
  obtain ⟨hactiveZero, hactiveOne⟩ :=
    supportEleven_zero_one_active successor z hzero hone
  refine ⟨hactiveZero, hactiveOne, ?_⟩
  rw [supportEleven_difference_three successor z hzero hone, hpolynomial]
  simp

/-- The exact predecessor-value chart for support mask 11. -/
def supportElevenValue
    (successor : Player → ℝ) (z : ℝ) : Player → ℝ :=
  let x₀ := supportElevenHazard successor z 0
  let x₁ := supportElevenHazard successor z 1
  let survival := (1 - x₀) * (1 - x₁) * (1 - z)
  ![
    x₁ * z - 3 * x₁ - 4 * z - 2,
    -3 * x₀ + 4 * z + 2,
    4 * x₀ * x₁ * z - x₀ * x₁ - 3 * x₀ * z -
      7 * x₁ * z + 8 * z + survival * successor 2,
    2 * (1 + 2 * x₀ - x₀ * x₁)
  ]

/-- On a root of `P₁₁`, the terminal-table expectation agrees with the
algebraic predecessor chart (45). -/
theorem supportEleven_predecessorValue
    (successor : Player → ℝ) (z : ℝ)
    (hzero : supportElevenZeroDenominator successor z ≠ 0)
    (hone : supportElevenOneDenominator successor z ≠ 0)
    (hpolynomial : supportElevenPolynomial successor z = 0) :
    predecessorValue (supportElevenHazard successor z) successor =
      supportElevenValue successor z := by
  have hactive := supportEleven_active successor z hzero hone hpolynomial
  funext who
  fin_cases who
  · change predecessorValue (supportElevenHazard successor z) successor 0 =
      supportElevenValue successor z 0
    rw [predecessorValue_eq_quit_of_difference_eq_zero hactive.1]
    simp +decide [opponentQuitValue, maskProbability, actionFactor, realSum,
      realProduct, maskWithPlayer, supportElevenHazard, supportElevenValue,
      terminalRewardNat]
    ring
  · change predecessorValue (supportElevenHazard successor z) successor 1 =
      supportElevenValue successor z 1
    rw [predecessorValue_eq_quit_of_difference_eq_zero hactive.2.1]
    simp +decide [opponentQuitValue, maskProbability, actionFactor, realSum,
      realProduct, maskWithPlayer, supportElevenHazard, supportElevenValue,
      terminalRewardNat]
    ring
  · change predecessorValue (supportElevenHazard successor z) successor 2 =
      supportElevenValue successor z 2
    simp +decide [predecessorValue, opponentAbsorbingContribution,
      opponentSurvival, maskProbability, actionFactor, realSum, realProduct,
      supportElevenHazard, supportElevenValue, terminalRewardNat]
    ring
  · change predecessorValue (supportElevenHazard successor z) successor 3 =
      supportElevenValue successor z 3
    rw [predecessorValue_eq_quit_of_difference_eq_zero hactive.2.2]
    simp +decide [opponentQuitValue, maskProbability, actionFactor, realSum,
      realProduct, maskWithPlayer, supportElevenHazard, supportElevenValue,
      terminalRewardNat]
    ring

end GameTheory.BlockPairCharts
