/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.Cycles.PhaseSwitchResiduals
import UniformEquilibrium.Quitting.Cycles.BehaviorPureTimeExtremality
import UniformEquilibrium.Quitting.Boundary.Exceptional.TailProfileAdapter

/-!
# Elementary terminal caps for quitting tails

This file isolates the three elementary suffixes used by finite tail
compression.  A cap is attached after an arbitrary finite word of behavioral
product roots.  It either stops jointly at its first stage, stops through one
distinguished player at its first stage, or never stops.  Both sure-stopping
caps continue surely after their first stage; this convention is strategically
important because it leaves a deviator's terminal continuation unpinned.

The file also records the survival trichotomy underlying the eventual
selection among these three shapes.  For an arbitrary root sequence, joint
survival either has positive limit, or it dies and at most one deleted-player
(opponent-only) clock has positive limit.  No compactness, exact-denominator
grammar, or stationarity is used.

The final sections verify the complete co-realized terminal semantics of the
`never` suffix itself: prescribed value zero and all-behavior best-response
value `max 0` the singleton reward.  Generic prefix-stability estimates then
give the full ordinary zero-survival case: a sure-joint cap has prescribed
error at most `2 M S_N` and player-`i` all-behavior envelope error at most
`2 M χ_i(N)`, with convergence and one simultaneous finite-player cutoff.
The positive joint-survival branch is proved only in the prescribed
coordinate, with error `M * (S_N - S_∞)`.  Its best-response estimate and the
unique-deleted-clock sure-solo branch are deliberately not asserted here.
-/

noncomputable section

namespace GameTheory

open StochasticGame Filter Math.Probability Math.PMFProduct

variable {ι : Type}

/-! ## Cap grammar -/

/-- The three elementary suffixes used by quitting-tail compression. -/
inductive QuittingElementaryTailCap (ι : Type)
  | sureJoint
  | sureSolo (owner : ι)
  | never

/-- A one-shot suffix generated by `root`: use `root` at stage zero and then
continue surely forever. -/
def quittingOneShotTailRoots (root : ι → PMF Bool) : ℕ → ι → PMF Bool
  | 0 => root
  | _ + 1 => quittingAllContinueRoot

/-- The root at which every player quits surely. -/
def quittingSureJointRoot : ι → PMF Bool :=
  fun _ => PMF.pure true

variable [DecidableEq ι]

/-- The root at which exactly `owner` quits surely. -/
def quittingSureSoloRoot (owner : ι) : ι → PMF Bool :=
  Function.update quittingAllContinueRoot owner (PMF.pure true)

/-- Root sequence realizing an elementary cap from its own stage zero.  Sure
caps are one-shot, while `never` is all-Continue at every stage. -/
def quittingElementaryCapRoots :
    QuittingElementaryTailCap ι → ℕ → ι → PMF Bool
  | .sureJoint => quittingOneShotTailRoots quittingSureJointRoot
  | .sureSolo owner => quittingOneShotTailRoots (quittingSureSoloRoot owner)
  | .never => fun _ => quittingAllContinueRoot

/-- Attach an elementary suffix at `cutoff`, preserving an arbitrary
behavioral product-root word strictly before the cutoff. -/
def quittingElementaryTailRoots
    (roots : ℕ → ι → PMF Bool) (cutoff : ℕ)
    (cap : QuittingElementaryTailCap ι) : ℕ → ι → PMF Bool :=
  quittingPhaseSwitchRoots roots (quittingElementaryCapRoots cap) cutoff

omit [DecidableEq ι] in
@[simp] theorem quittingOneShotTailRoots_zero (root : ι → PMF Bool) :
    quittingOneShotTailRoots root 0 = root :=
  rfl

omit [DecidableEq ι] in
@[simp] theorem quittingOneShotTailRoots_succ
    (root : ι → PMF Bool) (time : ℕ) :
    quittingOneShotTailRoots root (time + 1) = quittingAllContinueRoot :=
  rfl

/-- Every elementary repair matches the supplied finite word exactly. -/
theorem quittingElementaryTailRoots_of_lt
    (roots : ℕ → ι → PMF Bool) (cap : QuittingElementaryTailCap ι)
    {cutoff time : ℕ} (htime : time < cutoff) :
    quittingElementaryTailRoots roots cutoff cap time = roots time :=
  quittingPhaseSwitchRoots_of_lt roots _ htime

@[simp] theorem quittingElementaryTailRoots_add
    (roots : ℕ → ι → PMF Bool) (cutoff offset : ℕ)
    (cap : QuittingElementaryTailCap ι) :
    quittingElementaryTailRoots roots cutoff cap (cutoff + offset) =
      quittingElementaryCapRoots cap offset :=
  quittingPhaseSwitchRoots_add roots _ cutoff offset

/-- Every sure cap leaves a free all-Continue continuation after its certain
terminal stage. -/
theorem quittingElementaryTailRoots_sureJoint_add_succ
    (roots : ℕ → ι → PMF Bool) (cutoff offset : ℕ) :
    quittingElementaryTailRoots roots cutoff (.sureJoint) (cutoff + 1 + offset) =
      quittingAllContinueRoot := by
  rw [show cutoff + 1 + offset = cutoff + (offset + 1) by omega,
    quittingElementaryTailRoots_add]
  rfl

/-- The same free-continuation law for a sure-solo cap. -/
theorem quittingElementaryTailRoots_sureSolo_add_succ
    (roots : ℕ → ι → PMF Bool) (cutoff offset : ℕ) (owner : ι) :
    quittingElementaryTailRoots roots cutoff (.sureSolo owner)
        (cutoff + 1 + offset) = quittingAllContinueRoot := by
  rw [show cutoff + 1 + offset = cutoff + (offset + 1) by omega,
    quittingElementaryTailRoots_add]
  rfl

@[simp] theorem quittingElementaryTailRoots_never
    (roots : ℕ → ι → PMF Bool) (cutoff : ℕ) :
    quittingElementaryTailRoots roots cutoff (.never) =
      quittingTruncatedRoots roots cutoff :=
  rfl

@[simp] theorem quittingSureSoloRoot_owner (owner : ι) :
    quittingSureSoloRoot owner owner = PMF.pure true := by
  simp [quittingSureSoloRoot]

theorem quittingSureSoloRoot_of_ne {owner player : ι}
    (hne : player ≠ owner) :
    quittingSureSoloRoot owner player = PMF.pure false := by
  simp [quittingSureSoloRoot, quittingAllContinueRoot, hne]

omit [DecidableEq ι] in
@[simp] theorem quittingSureJointRoot_apply (player : ι) :
    quittingSureJointRoot player = PMF.pure true :=
  rfl

/-! ## Canonical survival limits -/

variable [Fintype ι]

/-- Limiting joint survival probability of a behavioral root sequence. -/
def quittingJointSurvivalLimit
    (roots : ℕ → ι → PMF Bool) (start : ℕ := 0) : ℝ :=
  ⨅ fuel, quittingJointSurvivalWeight roots start fuel

/-- Limiting probability that every opponent of `who` continues.  This is
the deleted-`who` clock. -/
def quittingOpponentSurvivalLimit
    (roots : ℕ → ι → PMF Bool) (who : ι) (start : ℕ := 0) : ℝ :=
  ⨅ fuel, quittingOpponentSurvivalWeight roots who start fuel

omit [DecidableEq ι] in
theorem tendsto_quittingJointSurvivalLimit
    (roots : ℕ → ι → PMF Bool) (start : ℕ) :
    Tendsto (quittingJointSurvivalWeight roots start) atTop
      (nhds (quittingJointSurvivalLimit roots start)) := by
  unfold quittingJointSurvivalLimit
  apply tendsto_atTop_ciInf (antitone_quittingJointSurvivalWeight roots start)
  refine ⟨0, ?_⟩
  rintro _ ⟨fuel, rfl⟩
  exact quittingJointSurvivalWeight_nonneg roots start fuel

theorem tendsto_quittingOpponentSurvivalLimit
    (roots : ℕ → ι → PMF Bool) (who : ι) (start : ℕ) :
    Tendsto (quittingOpponentSurvivalWeight roots who start) atTop
      (nhds (quittingOpponentSurvivalLimit roots who start)) := by
  unfold quittingOpponentSurvivalLimit
  apply tendsto_atTop_ciInf
    (antitone_quittingOpponentSurvivalWeight roots who start)
  refine ⟨0, ?_⟩
  rintro _ ⟨fuel, rfl⟩
  exact quittingOpponentSurvivalWeight_nonneg roots who start fuel

omit [DecidableEq ι] in
theorem quittingJointSurvivalLimit_nonneg
    (roots : ℕ → ι → PMF Bool) (start : ℕ) :
    0 ≤ quittingJointSurvivalLimit roots start := by
  unfold quittingJointSurvivalLimit
  exact le_ciInf fun fuel =>
    quittingJointSurvivalWeight_nonneg roots start fuel

theorem quittingOpponentSurvivalLimit_nonneg
    (roots : ℕ → ι → PMF Bool) (who : ι) (start : ℕ) :
    0 ≤ quittingOpponentSurvivalLimit roots who start := by
  unfold quittingOpponentSurvivalLimit
  exact le_ciInf fun fuel =>
    quittingOpponentSurvivalWeight_nonneg roots who start fuel

omit [DecidableEq ι] in
/-- Root-sequence joint survival is exactly the live mass of the generated
behavior profile. -/
@[simp] theorem quittingJointSurvivalWeight_eq_liveMass_rootSequence
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) : ∀ fuel,
    quittingJointSurvivalWeight roots 0 fuel =
      quittingLiveMass reward (quittingRootSequenceProfile reward roots 0) fuel := by
  intro fuel
  induction fuel with
  | zero =>
      simp [quittingJointSurvivalWeight, quittingFiniteContinueWeight]
  | succ fuel ih =>
      rw [quittingJointSurvivalWeight_succ, quittingLiveMass_succ, ih]
      congr 1

/-- Root-level survival trichotomy.  When total survival dies, either every
deleted-player clock dies or there is a unique player whose deleted clock has
positive limit.  The result is for arbitrary behavioral root words. -/
theorem quittingSurvivalLimit_trichotomy
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) :
    0 < quittingJointSurvivalLimit roots 0 ∨
      (quittingJointSurvivalLimit roots 0 = 0 ∧
        ((∀ who, quittingOpponentSurvivalLimit roots who 0 = 0) ∨
          ∃! owner, 0 < quittingOpponentSurvivalLimit roots owner 0)) := by
  classical
  let profile := quittingRootSequenceProfile reward roots 0
  by_cases hjoint : quittingJointSurvivalLimit roots 0 = 0
  · right
    refine ⟨hjoint, ?_⟩
    by_cases hall : ∀ who, quittingOpponentSurvivalLimit roots who 0 = 0
    · exact Or.inl hall
    · right
      push Not at hall
      obtain ⟨owner, howner⟩ := hall
      have hownerPos : 0 < quittingOpponentSurvivalLimit roots owner 0 :=
        lt_of_le_of_ne (quittingOpponentSurvivalLimit_nonneg roots owner 0)
          (Ne.symm howner)
      refine ⟨owner, hownerPos, ?_⟩
      intro other hotherPos
      have htotal : Tendsto (quittingLiveMass reward profile) atTop (nhds 0) := by
        have hfunctions : quittingLiveMass reward profile =
            quittingJointSurvivalWeight roots 0 := by
          funext fuel
          exact (quittingJointSurvivalWeight_eq_liveMass_rootSequence
            reward roots fuel).symm
        rw [hfunctions]
        simpa [hjoint] using tendsto_quittingJointSurvivalLimit roots 0
      apply eq_of_quittingOpponentSurvivalWeight_not_tendsto_zero
        reward profile htotal
      · have hnot : ¬Tendsto
            (quittingOpponentSurvivalWeight roots other 0) atTop (nhds 0) := by
          intro hzero
          exact (ne_of_gt hotherPos)
            (tendsto_nhds_unique
              (tendsto_quittingOpponentSurvivalLimit roots other 0) hzero)
        simpa [profile] using hnot
      · have hnot : ¬Tendsto
            (quittingOpponentSurvivalWeight roots owner 0) atTop (nhds 0) := by
          intro hzero
          exact (ne_of_gt hownerPos)
            (tendsto_nhds_unique
              (tendsto_quittingOpponentSurvivalLimit roots owner 0) hzero)
        simpa [profile] using hnot
  · left
    exact lt_of_le_of_ne (quittingJointSurvivalLimit_nonneg roots 0)
      (Ne.symm hjoint)

/-! ## Exact co-realized semantics of the Never cap -/

/-- Best-response envelope of a root sequence, over all behavioral
deviations of `who`. -/
def quittingRootSequenceBestResponseValue
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (who : ι) : ℝ :=
  quittingContinuationBestResponseValue reward
    (quittingRootSequenceProfile reward roots 0) who

@[simp] theorem quittingRootSequenceTerminalValue_elementaryCap_never
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) (who : ι) :
    quittingRootSequenceTerminalValue reward
        (quittingElementaryCapRoots (.never : QuittingElementaryTailCap ι))
        who 0 = 0 := by
  apply quittingRootSequenceTerminalValue_eq_zero_of_allContinue_from
    reward _ who 0
  intro time _
  rfl

/-- The `never` cap realizes the exact all-behavior deviation envelope, not
merely the pure-time envelope.  Thus its co-realized semantic pair is
`(0, max 0 qᵢ)` for every player. -/
theorem quittingRootSequenceBestResponseValue_elementaryCap_never
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) (who : ι)
    {M : ℝ} (hM : 0 ≤ M)
    (hreward : ∀ terminal player, |reward terminal player| ≤ M) :
    quittingRootSequenceBestResponseValue reward
        (quittingElementaryCapRoots (.never : QuittingElementaryTailCap ι)) who =
      max 0 (reward (quittingSingletonTerminal who) who) := by
  let profile := quittingAlwaysContinueProfile reward
  have hprofile : quittingRootSequenceProfile reward
      (quittingElementaryCapRoots (.never : QuittingElementaryTailCap ι)) 0 =
      profile := rfl
  have hbounded : BddAbove (Set.range fun deviation :
      (quittingGame reward).BehaviorStrategy who =>
        quittingTerminalPayoff reward
          (Function.update profile who deviation) who) :=
    bddAbove_range_quittingTerminalPayoff_update
      reward profile who hM hreward
  unfold quittingRootSequenceBestResponseValue
    quittingContinuationBestResponseValue
  rw [hprofile]
  apply le_antisymm
  · apply csSup_le
    · exact ⟨_, ⟨profile who, rfl⟩⟩
    · rintro _ ⟨deviation, rfl⟩
      exact quittingTerminalPayoff_update_quittingAlwaysContinue_le_max
        reward who deviation
  · apply max_le
    · apply le_csSup hbounded
      refine ⟨profile who, ?_⟩
      change quittingTerminalPayoff reward
        (Function.update profile who (profile who)) who = 0
      rw [Function.update_eq_self]
      dsimp [profile]
      rw [quittingTerminalPayoff_quittingAlwaysContinue]
    · apply le_csSup hbounded
      refine ⟨quittingAlwaysQuitStrategy reward who, ?_⟩
      change quittingTerminalPayoff reward
        (Function.update profile who
          (quittingAlwaysQuitStrategy reward who)) who = _
      dsimp [profile]
      rw [quittingTerminalPayoff_update_quittingAlwaysQuitStrategy]

/-! ## Generic prefix stability -/

omit [DecidableEq ι] in
/-- Two root sequences with the same finite prefix have prescribed terminal
values within `2M` times the probability of reaching the unmatched tail. -/
theorem abs_quittingRootSequenceTerminalValue_sub_le_of_prefix_eq
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (x y : ℕ → ι → PMF Bool) (who : ι) (cutoff : ℕ)
    {M : ℝ} (hM : 0 ≤ M)
    (hreward : ∀ terminal player, |reward terminal player| ≤ M)
    (hprefix : ∀ time, time < cutoff → x time = y time) :
    |quittingRootSequenceTerminalValue reward x who 0 -
        quittingRootSequenceTerminalValue reward y who 0| ≤
      2 * M * quittingJointSurvivalWeight y 0 cutoff := by
  have hscaled :=
    quittingRootSequenceTerminalValue_sub_eq_jointSurvivalWeight_mul
      reward x y who cutoff hprefix
  have hx := abs_quittingRootSequenceTerminalValue_le
    reward x who cutoff hM hreward
  have hy := abs_quittingRootSequenceTerminalValue_le
    reward y who cutoff hM hreward
  have htail :
      |quittingRootSequenceTerminalValue reward x who cutoff -
          quittingRootSequenceTerminalValue reward y who cutoff| ≤ 2 * M := by
    calc
      |quittingRootSequenceTerminalValue reward x who cutoff -
          quittingRootSequenceTerminalValue reward y who cutoff| ≤
          |quittingRootSequenceTerminalValue reward x who cutoff| +
            |quittingRootSequenceTerminalValue reward y who cutoff| :=
        abs_sub _ _
      _ ≤ M + M := add_le_add hx hy
      _ = 2 * M := by ring
  rw [hscaled, abs_mul,
    abs_of_nonneg (quittingJointSurvivalWeight_nonneg y 0 cutoff)]
  calc
    quittingJointSurvivalWeight y 0 cutoff *
        |quittingRootSequenceTerminalValue reward x who cutoff -
          quittingRootSequenceTerminalValue reward y who cutoff| ≤
      quittingJointSurvivalWeight y 0 cutoff * (2 * M) :=
        mul_le_mul_of_nonneg_left htail
          (quittingJointSurvivalWeight_nonneg y 0 cutoff)
    _ = 2 * M * quittingJointSurvivalWeight y 0 cutoff := by ring

/-- Pointwise deviation stability uses the deleted-player clock.  The same
hazard is evaluated against both opponent words; changing the deviator's own
marginal cannot alter opponent survival. -/
theorem abs_quittingRootSequenceHazardTerminalValue_sub_le_of_prefix_eq
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (x y : ℕ → ι → PMF Bool) (who : ι) (hazard : ℕ → PMF Bool)
    (cutoff : ℕ) {M : ℝ} (hM : 0 ≤ M)
    (hreward : ∀ terminal player, |reward terminal player| ≤ M)
    (hprefix : ∀ time, time < cutoff → x time = y time) :
    |quittingRootSequenceHazardTerminalValue reward x who hazard 0 -
        quittingRootSequenceHazardTerminalValue reward y who hazard 0| ≤
      2 * M * quittingOpponentSurvivalWeight y who 0 cutoff := by
  have hupdatePrefix : ∀ time, time < cutoff →
      quittingRootSequenceUpdate x who hazard time =
        quittingRootSequenceUpdate y who hazard time := by
    intro time htime
    unfold quittingRootSequenceUpdate
    rw [hprefix time htime]
  have hbound := abs_quittingRootSequenceTerminalValue_sub_le_of_prefix_eq
    reward (quittingRootSequenceUpdate x who hazard)
      (quittingRootSequenceUpdate y who hazard) who cutoff hM hreward
      hupdatePrefix
  calc
    |quittingRootSequenceHazardTerminalValue reward x who hazard 0 -
        quittingRootSequenceHazardTerminalValue reward y who hazard 0| ≤
      2 * M * quittingJointSurvivalWeight
        (quittingRootSequenceUpdate y who hazard) 0 cutoff := by
          simpa [quittingRootSequenceHazardTerminalValue] using hbound
    _ ≤ 2 * M * quittingOpponentSurvivalWeight y who 0 cutoff :=
      mul_le_mul_of_nonneg_left
        (quittingJointSurvivalWeight_update_le_quittingOpponentSurvivalWeight
          y who hazard 0 cutoff)
        (mul_nonneg (by norm_num) hM)

/-- The hazard estimate is exactly a pointwise estimate for arbitrary
behavior strategies, via the live-path collapse. -/
theorem abs_quittingTerminalPayoff_update_rootSequence_sub_le_of_prefix_eq
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (x y : ℕ → ι → PMF Bool) (who : ι)
    (deviation : (quittingGame reward).BehaviorStrategy who)
    (cutoff : ℕ) {M : ℝ} (hM : 0 ≤ M)
    (hreward : ∀ terminal player, |reward terminal player| ≤ M)
    (hprefix : ∀ time, time < cutoff → x time = y time) :
    |quittingTerminalPayoff reward
          (Function.update (quittingRootSequenceProfile reward x 0) who
            deviation) who -
        quittingTerminalPayoff reward
          (Function.update (quittingRootSequenceProfile reward y 0) who
            deviation) who| ≤
      2 * M * quittingOpponentSurvivalWeight y who 0 cutoff := by
  rw [quittingTerminalPayoff_update_eq_rootSequenceHazardTerminalValue,
    quittingTerminalPayoff_update_eq_rootSequenceHazardTerminalValue,
    quittingProfileLiveRoot_quittingRootSequenceProfile_zero,
    quittingProfileLiveRoot_quittingRootSequenceProfile_zero]
  exact abs_quittingRootSequenceHazardTerminalValue_sub_le_of_prefix_eq
    reward x y who (quittingBehaviorLiveHazard reward deviation) cutoff
      hM hreward hprefix

/-- Suprema over all behavior deviations inherit the same deleted-clock
prefix estimate.  This is an envelope statement, not a prescribed-value
proxy. -/
theorem abs_quittingRootSequenceBestResponseValue_sub_le_of_prefix_eq
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (x y : ℕ → ι → PMF Bool) (who : ι) (cutoff : ℕ)
    {M : ℝ} (hM : 0 ≤ M)
    (hreward : ∀ terminal player, |reward terminal player| ≤ M)
    (hprefix : ∀ time, time < cutoff → x time = y time) :
    |quittingRootSequenceBestResponseValue reward x who -
        quittingRootSequenceBestResponseValue reward y who| ≤
      2 * M * quittingOpponentSurvivalWeight y who 0 cutoff := by
  let xProfile := quittingRootSequenceProfile reward x 0
  let yProfile := quittingRootSequenceProfile reward y 0
  let error := 2 * M * quittingOpponentSurvivalWeight y who 0 cutoff
  have hpoint : ∀ deviation : (quittingGame reward).BehaviorStrategy who,
      |quittingTerminalPayoff reward
          (Function.update xProfile who deviation) who -
        quittingTerminalPayoff reward
          (Function.update yProfile who deviation) who| ≤ error := by
    intro deviation
    dsimp [xProfile, yProfile, error]
    exact abs_quittingTerminalPayoff_update_rootSequence_sub_le_of_prefix_eq
      reward x y who deviation cutoff hM hreward hprefix
  have hxy : quittingContinuationBestResponseValue reward xProfile who ≤
      quittingContinuationBestResponseValue reward yProfile who + error := by
    unfold quittingContinuationBestResponseValue
    apply csSup_le
    · exact ⟨_, ⟨xProfile who, rfl⟩⟩
    · rintro _ ⟨deviation, rfl⟩
      have hy := quittingTerminalPayoff_update_le_continuationBestResponseValue
        reward yProfile who deviation hM hreward
      unfold quittingContinuationBestResponseValue at hy
      have hp := hpoint deviation
      linarith [le_abs_self
        (quittingTerminalPayoff reward
            (Function.update xProfile who deviation) who -
          quittingTerminalPayoff reward
            (Function.update yProfile who deviation) who)]
  have hyx : quittingContinuationBestResponseValue reward yProfile who ≤
      quittingContinuationBestResponseValue reward xProfile who + error := by
    unfold quittingContinuationBestResponseValue
    apply csSup_le
    · exact ⟨_, ⟨yProfile who, rfl⟩⟩
    · rintro _ ⟨deviation, rfl⟩
      have hx := quittingTerminalPayoff_update_le_continuationBestResponseValue
        reward xProfile who deviation hM hreward
      unfold quittingContinuationBestResponseValue at hx
      have hp := hpoint deviation
      linarith [neg_le_abs
        (quittingTerminalPayoff reward
            (Function.update xProfile who deviation) who -
          quittingTerminalPayoff reward
            (Function.update yProfile who deviation) who)]
  change |quittingContinuationBestResponseValue reward xProfile who -
      quittingContinuationBestResponseValue reward yProfile who| ≤ error
  rw [abs_le]
  constructor <;> linarith

/-! ## Zero-survival compression by a sure-joint cap -/

/-- An elementary cap does not change joint survival through its matching
prefix. -/
@[simp] theorem quittingJointSurvivalWeight_elementaryTailRoots_plan
    (roots : ℕ → ι → PMF Bool) (cutoff : ℕ)
    (cap : QuittingElementaryTailCap ι) :
    quittingJointSurvivalWeight
        (quittingElementaryTailRoots roots cutoff cap) 0 cutoff =
      quittingJointSurvivalWeight roots 0 cutoff := by
  exact quittingJointSurvivalWeight_quittingPhaseSwitchRoots_plan
    roots (quittingElementaryCapRoots cap) cutoff

/-- An elementary cap likewise does not change any deleted-player clock
through its matching prefix. -/
@[simp] theorem quittingOpponentSurvivalWeight_elementaryTailRoots_plan
    (roots : ℕ → ι → PMF Bool) (cutoff : ℕ)
    (cap : QuittingElementaryTailCap ι) (who : ι) :
    quittingOpponentSurvivalWeight
        (quittingElementaryTailRoots roots cutoff cap) who 0 cutoff =
      quittingOpponentSurvivalWeight roots who 0 cutoff := by
  exact quittingOpponentSurvivalWeight_quittingPhaseSwitchRoots_plan
    roots (quittingElementaryCapRoots cap) cutoff who

/-- Prescribed-value error for the finite prefix capped by sure joint exit. -/
theorem abs_quittingRootSequenceTerminalValue_sub_elementarySureJoint_le
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (who : ι) (cutoff : ℕ)
    {M : ℝ} (hM : 0 ≤ M)
    (hreward : ∀ terminal player, |reward terminal player| ≤ M) :
    |quittingRootSequenceTerminalValue reward roots who 0 -
        quittingRootSequenceTerminalValue reward
          (quittingElementaryTailRoots roots cutoff (.sureJoint)) who 0| ≤
      2 * M * quittingJointSurvivalWeight roots 0 cutoff := by
  simpa using
    (abs_quittingRootSequenceTerminalValue_sub_le_of_prefix_eq
      reward roots (quittingElementaryTailRoots roots cutoff (.sureJoint))
      who cutoff hM hreward fun time htime =>
        (quittingElementaryTailRoots_of_lt roots (.sureJoint) htime).symm)

/-- All-behavior best-response-envelope error for the same sure-joint
compression.  The scale is the player's deleted clock, not joint survival. -/
theorem abs_quittingRootSequenceBestResponseValue_sub_elementarySureJoint_le
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (who : ι) (cutoff : ℕ)
    {M : ℝ} (hM : 0 ≤ M)
    (hreward : ∀ terminal player, |reward terminal player| ≤ M) :
    |quittingRootSequenceBestResponseValue reward roots who -
        quittingRootSequenceBestResponseValue reward
          (quittingElementaryTailRoots roots cutoff (.sureJoint)) who| ≤
      2 * M * quittingOpponentSurvivalWeight roots who 0 cutoff := by
  simpa using
    (abs_quittingRootSequenceBestResponseValue_sub_le_of_prefix_eq
      reward roots (quittingElementaryTailRoots roots cutoff (.sureJoint))
      who cutoff hM hreward fun time htime =>
        (quittingElementaryTailRoots_of_lt roots (.sureJoint) htime).symm)

/-- If full survival tends to zero, sure-joint capped prefixes converge in
every prescribed coordinate. -/
theorem tendsto_quittingRootSequenceTerminalValue_elementarySureJoint
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (who : ι)
    {M : ℝ} (hM : 0 ≤ M)
    (hreward : ∀ terminal player, |reward terminal player| ≤ M)
    (hzero : quittingJointSurvivalLimit roots 0 = 0) :
    Tendsto (fun cutoff => quittingRootSequenceTerminalValue reward
        (quittingElementaryTailRoots roots cutoff (.sureJoint)) who 0)
      atTop (nhds (quittingRootSequenceTerminalValue reward roots who 0)) := by
  have hmajorant : Tendsto (fun cutoff =>
      2 * M * quittingJointSurvivalWeight roots 0 cutoff) atTop (nhds 0) := by
    have hscaled :=
      (tendsto_quittingJointSurvivalLimit roots 0).const_mul (2 * M)
    simpa [hzero] using hscaled
  rw [Metric.tendsto_atTop]
  intro ε hε
  obtain ⟨threshold, hthreshold⟩ :=
    (Metric.tendsto_atTop.mp hmajorant) ε hε
  refine ⟨threshold, fun cutoff hcutoff => ?_⟩
  have hbound :=
    abs_quittingRootSequenceTerminalValue_sub_elementarySureJoint_le
      reward roots who cutoff hM hreward
  have hmajorantClose := hthreshold cutoff hcutoff
  rw [Real.dist_eq, sub_zero, abs_of_nonneg] at hmajorantClose
  · rw [Real.dist_eq]
    exact lt_of_le_of_lt (by simpa [abs_sub_comm] using hbound) hmajorantClose
  · exact mul_nonneg (mul_nonneg (by norm_num) hM)
      (quittingJointSurvivalWeight_nonneg roots 0 cutoff)

/-- If `who`'s deleted clock tends to zero, the sure-joint capped prefixes
converge in that player's all-behavior best-response envelope. -/
theorem tendsto_quittingRootSequenceBestResponseValue_elementarySureJoint
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (who : ι)
    {M : ℝ} (hM : 0 ≤ M)
    (hreward : ∀ terminal player, |reward terminal player| ≤ M)
    (hzero : quittingOpponentSurvivalLimit roots who 0 = 0) :
    Tendsto (fun cutoff => quittingRootSequenceBestResponseValue reward
        (quittingElementaryTailRoots roots cutoff (.sureJoint)) who)
      atTop (nhds (quittingRootSequenceBestResponseValue reward roots who)) := by
  have hmajorant : Tendsto (fun cutoff =>
      2 * M * quittingOpponentSurvivalWeight roots who 0 cutoff)
      atTop (nhds 0) := by
    have hscaled :=
      (tendsto_quittingOpponentSurvivalLimit roots who 0).const_mul (2 * M)
    simpa [hzero] using hscaled
  rw [Metric.tendsto_atTop]
  intro ε hε
  obtain ⟨threshold, hthreshold⟩ :=
    (Metric.tendsto_atTop.mp hmajorant) ε hε
  refine ⟨threshold, fun cutoff hcutoff => ?_⟩
  have hbound :=
    abs_quittingRootSequenceBestResponseValue_sub_elementarySureJoint_le
      reward roots who cutoff hM hreward
  have hmajorantClose := hthreshold cutoff hcutoff
  rw [Real.dist_eq, sub_zero, abs_of_nonneg] at hmajorantClose
  · rw [Real.dist_eq]
    exact lt_of_le_of_lt (by simpa [abs_sub_comm] using hbound) hmajorantClose
  · exact mul_nonneg (mul_nonneg (by norm_num) hM)
      (quittingOpponentSurvivalWeight_nonneg roots who 0 cutoff)

/-- Finite-player simultaneous selection in the ordinary zero-survival
branch: one cutoff approximates every prescribed coordinate and every
all-behavior best-response envelope. -/
theorem exists_elementarySureJoint_terminalPair_close
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool)
    {M ε : ℝ} (hM : 0 ≤ M) (hε : 0 < ε)
    (hreward : ∀ terminal player, |reward terminal player| ≤ M)
    (hjoint : quittingJointSurvivalLimit roots 0 = 0)
    (hopponent : ∀ who, quittingOpponentSurvivalLimit roots who 0 = 0) :
    ∃ cutoff,
      (∀ who,
        |quittingRootSequenceTerminalValue reward roots who 0 -
          quittingRootSequenceTerminalValue reward
            (quittingElementaryTailRoots roots cutoff (.sureJoint)) who 0| < ε) ∧
      (∀ who,
        |quittingRootSequenceBestResponseValue reward roots who -
          quittingRootSequenceBestResponseValue reward
            (quittingElementaryTailRoots roots cutoff (.sureJoint)) who| < ε) := by
  have hprescribed : ∀ᶠ cutoff : ℕ in atTop, ∀ who,
      |quittingRootSequenceTerminalValue reward roots who 0 -
        quittingRootSequenceTerminalValue reward
          (quittingElementaryTailRoots roots cutoff (.sureJoint)) who 0| < ε := by
    apply Filter.eventually_all.mpr
    intro who
    obtain ⟨threshold, hthreshold⟩ := Metric.tendsto_atTop.mp
      (tendsto_quittingRootSequenceTerminalValue_elementarySureJoint
        reward roots who hM hreward hjoint) ε hε
    exact eventually_atTop.mpr ⟨threshold, fun cutoff hcutoff => by
      simpa [Real.dist_eq, abs_sub_comm] using hthreshold cutoff hcutoff⟩
  have henvelope : ∀ᶠ cutoff : ℕ in atTop, ∀ who,
      |quittingRootSequenceBestResponseValue reward roots who -
        quittingRootSequenceBestResponseValue reward
          (quittingElementaryTailRoots roots cutoff (.sureJoint)) who| < ε := by
    apply Filter.eventually_all.mpr
    intro who
    obtain ⟨threshold, hthreshold⟩ := Metric.tendsto_atTop.mp
      (tendsto_quittingRootSequenceBestResponseValue_elementarySureJoint
        reward roots who hM hreward (hopponent who)) ε hε
    exact eventually_atTop.mpr ⟨threshold, fun cutoff hcutoff => by
      simpa [Real.dist_eq, abs_sub_comm] using hthreshold cutoff hcutoff⟩
  obtain ⟨threshold, hthreshold⟩ :=
    eventually_atTop.mp (hprescribed.and henvelope)
  exact ⟨threshold, hthreshold threshold le_rfl⟩

/-! ## Positive-survival compression: prescribed coordinate -/

/-- In the positive joint-survival branch, replacing the tail after `cutoff`
by `Never` changes the prescribed terminal payoff by at most the reward bound
times the joint survival still lost after that cutoff. -/
theorem abs_quittingRootSequenceTerminalValue_sub_elementaryNever_le
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (who : ι) (cutoff : ℕ)
    {M : ℝ}
    (hreward : ∀ terminal player, |reward terminal player| ≤ M)
    (hpositive : 0 < quittingJointSurvivalLimit roots 0) :
    |quittingRootSequenceTerminalValue reward roots who 0 -
        quittingRootSequenceTerminalValue reward
          (quittingElementaryTailRoots roots cutoff (.never)) who 0| ≤
      M * (quittingJointSurvivalWeight roots 0 cutoff -
        quittingJointSurvivalLimit roots 0) := by
  let limit := quittingJointSurvivalLimit roots 0
  let prefixWeight := quittingJointSurvivalWeight roots 0 cutoff
  let tailProfile := quittingRootSequenceProfile reward roots cutoff
  have hlimit : Tendsto (quittingJointSurvivalWeight roots 0) atTop
      (nhds limit) := tendsto_quittingJointSurvivalLimit roots 0
  have hprefixLower : limit ≤ prefixWeight :=
    le_quittingJointSurvivalWeight_of_tendsto roots 0 hlimit cutoff
  have hprefixPos : 0 < prefixWeight := hpositive.trans_le hprefixLower
  have htailSurvival : Tendsto
      (quittingJointSurvivalWeight roots cutoff) atTop
      (nhds (limit / prefixWeight)) := by
    simpa [limit, prefixWeight] using
      (tendsto_quittingJointSurvivalWeight_tail_of_tendsto
        roots 0 hlimit hpositive cutoff)
  have hliveFunction : quittingLiveMass reward tailProfile =
      quittingJointSurvivalWeight roots cutoff := by
    funext fuel
    calc
      quittingLiveMass reward tailProfile fuel =
          quittingLiveMass reward
            (quittingRootSequenceProfile reward
              (fun time => roots (cutoff + time)) 0) fuel := by
            dsimp [tailProfile]
            rw [quittingRootSequenceProfile_eq_shift]
      _ = quittingJointSurvivalWeight
          (fun time => roots (cutoff + time)) 0 fuel :=
            (quittingJointSurvivalWeight_eq_liveMass_rootSequence reward
              (fun time => roots (cutoff + time)) fuel).symm
      _ = quittingJointSurvivalWeight roots cutoff fuel :=
            (quittingJointSurvivalWeight_eq_shift roots cutoff fuel).symm
  have hliveLimit : quittingLiveMassLimit reward tailProfile =
      limit / prefixWeight := by
    apply tendsto_nhds_unique (tendsto_quittingLiveMass reward tailProfile)
    rw [hliveFunction]
    exact htailSurvival
  have htailBound :
      |quittingRootSequenceTerminalValue reward roots who cutoff| ≤
        M * (1 - limit / prefixWeight) := by
    unfold quittingRootSequenceTerminalValue
    rw [show quittingRootSequenceProfile reward roots cutoff = tailProfile from rfl]
    simpa [hliveLimit] using
      (abs_quittingTerminalPayoff_le_absorbedMass
        reward tailProfile who hreward)
  let capped := quittingElementaryTailRoots roots cutoff (.never)
  have hcappedTail :
      quittingRootSequenceTerminalValue reward capped who cutoff = 0 := by
    apply quittingRootSequenceTerminalValue_eq_zero_of_allContinue_from
      reward capped who cutoff
    intro time htime
    dsimp [capped]
    rw [quittingTruncatedRoots_of_le roots htime]
  have hprefixCapped :
      quittingJointSurvivalWeight capped 0 cutoff = prefixWeight := by
    dsimp [capped, prefixWeight]
    rw [quittingJointSurvivalWeight_quittingTruncatedRoots
      roots cutoff cutoff le_rfl]
  have hscaled := quittingRootSequenceTerminalValue_sub_eq_jointSurvivalWeight_mul
    reward roots capped who cutoff
    (fun time htime =>
      (quittingElementaryTailRoots_of_lt roots (.never) htime).symm)
  rw [hcappedTail, sub_zero, hprefixCapped] at hscaled
  calc
    |quittingRootSequenceTerminalValue reward roots who 0 -
        quittingRootSequenceTerminalValue reward capped who 0| =
        prefixWeight *
          |quittingRootSequenceTerminalValue reward roots who cutoff| := by
          rw [hscaled, abs_mul, abs_of_pos hprefixPos]
    _ ≤ prefixWeight * (M * (1 - limit / prefixWeight)) :=
      mul_le_mul_of_nonneg_left htailBound hprefixPos.le
    _ = M * (prefixWeight - limit) := by
      field_simp [hprefixPos.ne']

/-- Consequently, positive-survival tails are approximated in prescribed
terminal value by their finite prefixes capped with `Never`. -/
theorem tendsto_quittingRootSequenceTerminalValue_elementaryNever
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (who : ι)
    {M : ℝ} (hM : 0 ≤ M)
    (hreward : ∀ terminal player, |reward terminal player| ≤ M)
    (hpositive : 0 < quittingJointSurvivalLimit roots 0) :
    Tendsto (fun cutoff => quittingRootSequenceTerminalValue reward
        (quittingElementaryTailRoots roots cutoff (.never)) who 0)
      atTop (nhds (quittingRootSequenceTerminalValue reward roots who 0)) := by
  have hmajorant : Tendsto (fun cutoff =>
      M * (quittingJointSurvivalWeight roots 0 cutoff -
        quittingJointSurvivalLimit roots 0)) atTop (nhds 0) := by
    have hsub := (tendsto_quittingJointSurvivalLimit roots 0).sub
      (tendsto_const_nhds : Tendsto
        (fun _ : ℕ => quittingJointSurvivalLimit roots 0) atTop
        (nhds (quittingJointSurvivalLimit roots 0)))
    simpa using hsub.const_mul M
  rw [Metric.tendsto_atTop]
  intro ε hε
  obtain ⟨threshold, hthreshold⟩ :=
    (Metric.tendsto_atTop.mp hmajorant) ε hε
  refine ⟨threshold, fun cutoff hcutoff => ?_⟩
  have hbound := abs_quittingRootSequenceTerminalValue_sub_elementaryNever_le
    reward roots who cutoff hreward hpositive
  have hmajorantClose := hthreshold cutoff hcutoff
  rw [Real.dist_eq, sub_zero, abs_of_nonneg] at hmajorantClose
  · rw [Real.dist_eq]
    exact lt_of_le_of_lt (by simpa [abs_sub_comm] using hbound) hmajorantClose
  · exact mul_nonneg hM (sub_nonneg.mpr
      (le_quittingJointSurvivalWeight_of_tendsto roots 0
        (tendsto_quittingJointSurvivalLimit roots 0) cutoff))

end GameTheory
