import MathUE.ProbabilityMassFunction.BoundedSupportAverage
import UniformEquilibrium.Quitting.Paths.BehaviorStoppingPayoff
import UniformEquilibrium.Quitting.Paths.PureTimeDeadlineRank
import UniformEquilibrium.Quitting.Root.TerminalDebtPrefix

/-!
# Supported pure-time replacements of behavioral strategies

This module selects a pure stopping time from a behavioral strategy's actual
stopping-law support without decreasing the mover's prescribed payoff.  It
also records the literal unilateral-replacement ancestry.  It makes no claim
about nonmover caps, total debt, minimum preservation, chronology, or
equilibrium.
-/

noncomputable section

namespace GameTheory

open Math.Probability Math.ProbabilityMassFunction

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- One literal unilateral replacement between arbitrary behavioral profiles. -/
def IsQuittingBehaviorUnilateralReplacement
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    (first second : (quittingGame reward).BehaviorProfile) : Prop :=
  ∃ (who : ι) (replacement : (quittingGame reward).BehaviorStrategy who),
    second = Function.update first who replacement

/-- Finite ancestry generated by literal unilateral behavioral replacements. -/
def IsQuittingBehaviorReplacementAncestry
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    (first second : (quittingGame reward).BehaviorProfile) : Prop :=
  Relation.ReflTransGen IsQuittingBehaviorUnilateralReplacement first second

/-- Replacing one behavioral coordinate is one literal ancestry step. -/
theorem isQuittingBehaviorReplacementAncestry_update
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    (profile : (quittingGame reward).BehaviorProfile) (who : ι)
    (replacement : (quittingGame reward).BehaviorStrategy who) :
    IsQuittingBehaviorReplacementAncestry profile
      (Function.update profile who replacement) :=
  Relation.ReflTransGen.single ⟨who, replacement, rfl⟩

/-- A finite canonical pure-time ancestry is also a finite ancestry of the
corresponding behavioral profiles. -/
theorem isQuittingBehaviorReplacementAncestry_pureTimeProfileBehavior
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    {first second : QuittingPureTimeProfile ι}
    (hancestry : IsQuittingPureTimeReplacementAncestry first second) :
    IsQuittingBehaviorReplacementAncestry
      (quittingPureTimeProfileBehavior reward first)
      (quittingPureTimeProfileBehavior reward second) := by
  induction hancestry using Relation.ReflTransGen.head_induction_on with
  | refl => exact Relation.ReflTransGen.refl
  | @head first middle hstep _ ih =>
      obtain ⟨who, replacement, rfl⟩ := hstep
      have hbehavior : IsQuittingBehaviorUnilateralReplacement
          (quittingPureTimeProfileBehavior reward first)
          (quittingPureTimeProfileBehavior reward
            (Function.update first who replacement)) := by
        refine ⟨who, quittingPureTimeBehaviorStrategy reward who replacement, ?_⟩
        exact quittingPureTimeProfileBehavior_update
          reward first who replacement
      exact (Relation.ReflTransGen.single hbehavior).trans ih

/-- A prescribed arbitrary stopping law has a positive-support pure clock whose
payoff is at least the prescribed payoff.  This is not cap attainment. -/
theorem exists_support_pureTime_payoff_ge_prescribed
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) (who : ι) :
    ∃ choice : Option ℕ,
      choice ∈ (quittingBehaviorStoppingLaw reward (profile who)).support ∧
      quittingTerminalPayoff reward profile who ≤
        quittingTerminalPayoff reward
          (Function.update profile who
            (quittingPureTimeBehaviorStrategy reward who choice)) who := by
  let value : Option ℕ → ℝ :=
    fun choice => quittingTerminalPayoff reward
      (Function.update profile who
        (quittingPureTimeBehaviorStrategy reward who choice)) who
  have hvalue : ∀ choice, |value choice| ≤ quittingRewardBound reward := by
    intro choice
    dsimp only [value]
    exact abs_quittingTerminalPayoff_le_quittingRewardBound reward _ who
  obtain ⟨choice, hsupport, haverage⟩ :=
    exists_mem_support_expect_le
      (quittingBehaviorStoppingLaw reward (profile who)) value hvalue
  have hprescribed : quittingTerminalPayoff reward profile who =
      expect (quittingBehaviorStoppingLaw reward (profile who)) value := by
    have hdisintegration :=
      quittingTerminalPayoff_update_eq_expect_stoppingLaw_pureTime
        reward profile who (profile who)
    rw [Function.update_eq_self] at hdisintegration
    exact hdisintegration
  refine ⟨choice, hsupport, ?_⟩
  rw [hprescribed]
  simpa only [value] using haverage

/-- The supported pure-clock replacement weakly lowers the mover's own debt;
no statement is made about any other debt coordinate. -/
theorem exists_support_pureTimeReplacement_ownDebt_le
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) (who : ι) :
    ∃ choice : Option ℕ,
      choice ∈ (quittingBehaviorStoppingLaw reward (profile who)).support ∧
      IsQuittingBehaviorReplacementAncestry profile
        (Function.update profile who
          (quittingPureTimeBehaviorStrategy reward who choice)) ∧
      quittingTerminalDeviationDebt reward
          (Function.update profile who
            (quittingPureTimeBehaviorStrategy reward who choice)) who ≤
        quittingTerminalDeviationDebt reward profile who := by
  obtain ⟨choice, hsupport, hpayoff⟩ :=
    exists_support_pureTime_payoff_ge_prescribed reward profile who
  refine ⟨choice, hsupport,
    isQuittingBehaviorReplacementAncestry_update profile who _, ?_⟩
  unfold quittingTerminalDeviationDebt
  rw [quittingContinuationBestResponseValue_update_self]
  linarith

end GameTheory
