/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import MathUE.PMFProduct.Update
import MathUE.ProbabilityMassFunction.GeneralTotalVariation
import UniformEquilibrium.Quitting.Paths.BehaviorStoppingPayoff
import UniformEquilibrium.Quitting.Root.TerminalOutcome

/-!
# Counterfactual stopping-law hierarchy

Independent stopping-time marginals determine a labelled first-stopping law.
Pure interventions replace a finite set of marginals.  This file records the
one-coordinate replacement compiler and its sharp finite-player order bound.

The state is counterfactual: the intervened labels remain visible.  It is not
a suffix state, a conditional continuation law, or an AKRS path limit.
-/

noncomputable section

namespace GameTheory

open Math Probability

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- `none` is later than every finite stopping date. -/
def quittingStoppingTimeValue : Option Nat -> WithTop Nat
  | none => ⊤
  | some time => time

/-- Earliest date in a pure stopping-time profile. -/
def quittingEarliestStoppingValue (times : ι -> Option Nat) : WithTop Nat :=
  Finset.univ.inf fun who => quittingStoppingTimeValue (times who)

/-- Labels attaining the earliest date.  When every label is `Never`, this is
all of `univ`; the terminal outcome below separately records `Never`. -/
def quittingEarliestStoppingCoalition (times : ι -> Option Nat) : Finset ι :=
  Finset.univ.filter fun who =>
    quittingStoppingTimeValue (times who) = quittingEarliestStoppingValue times

omit [DecidableEq ι] in
theorem quittingEarliestStoppingCoalition_nonempty [Nonempty ι]
    (times : ι -> Option Nat) :
    (quittingEarliestStoppingCoalition times).Nonempty := by
  obtain ⟨who, -, hwho⟩ := Finset.exists_mem_eq_inf
    (Finset.univ : Finset ι) Finset.univ_nonempty
    (fun i => quittingStoppingTimeValue (times i))
  exact ⟨who, by
    simp only [quittingEarliestStoppingCoalition, Finset.mem_filter,
      Finset.mem_univ, true_and]
    exact hwho.symm⟩

/-- Labelled first-stopping outcome of a pure stopping-time profile. -/
def quittingFirstStoppingOutcome [Nonempty ι]
    (times : ι -> Option Nat) : QuittingTerminalOutcome ι :=
  if quittingEarliestStoppingValue times = ⊤ then none
  else some ⟨quittingEarliestStoppingCoalition times,
    quittingEarliestStoppingCoalition_nonempty times⟩

omit [DecidableEq ι] in
@[simp] theorem quittingFirstStoppingOutcome_all_never [Nonempty ι] :
    quittingFirstStoppingOutcome (fun _ : ι => none) = none := by
  simp [quittingFirstStoppingOutcome, quittingEarliestStoppingValue,
    quittingStoppingTimeValue]

/-- A pure intervention pins the stopping dates in `carrier`. -/
structure QuittingStoppingIntervention (ι : Type) [DecidableEq ι] where
  carrier : Finset ι
  stoppingTime : ι -> Option Nat

namespace QuittingStoppingIntervention

variable (intervention : QuittingStoppingIntervention ι)

/-- Apply a pure intervention to marginal stopping laws. -/
def applyLaws (laws : ι -> PMF (Option Nat)) : ι -> PMF (Option Nat) :=
  fun who => if who ∈ intervention.carrier then
    PMF.pure (intervention.stoppingTime who) else laws who

/-- Apply the same intervention to a pure stopping-time profile. -/
def applyTimes (times : ι -> Option Nat) : ι -> Option Nat :=
  fun who => if who ∈ intervention.carrier then
    intervention.stoppingTime who else times who

/-- Extend an intervention by pinning one further coordinate. -/
def insert (who : ι) (time : Option Nat) : QuittingStoppingIntervention ι where
  carrier := Insert.insert who intervention.carrier
  stoppingTime := Function.update intervention.stoppingTime who time

omit [Fintype ι] in
@[simp] theorem applyLaws_of_mem (laws : ι -> PMF (Option Nat))
    {who : ι} (hwho : who ∈ intervention.carrier) :
    intervention.applyLaws laws who =
      PMF.pure (intervention.stoppingTime who) := by
  simp [applyLaws, hwho]

omit [Fintype ι] in
@[simp] theorem applyLaws_of_not_mem (laws : ι -> PMF (Option Nat))
    {who : ι} (hwho : who ∉ intervention.carrier) :
    intervention.applyLaws laws who = laws who := by
  simp [applyLaws, hwho]

omit [Fintype ι] in
theorem applyLaws_pure (times : ι -> Option Nat) :
    intervention.applyLaws (fun who => PMF.pure (times who)) =
      fun who => PMF.pure (intervention.applyTimes times who) := by
  funext who
  by_cases hwho : who ∈ intervention.carrier <;>
    simp [applyLaws, applyTimes, hwho]

end QuittingStoppingIntervention

/-- The labelled terminal law generated by independent stopping marginals. -/
def quittingIndependentTerminalOutcomeLaw [Nonempty ι]
    (laws : ι -> PMF (Option Nat)) : PMF (QuittingTerminalOutcome ι) :=
  (Math.PMFProduct.pmfPi laws).map quittingFirstStoppingOutcome

/-- The terminal law after a finite pure intervention. -/
def quittingCounterfactualOutcomeLaw [Nonempty ι]
    (laws : ι -> PMF (Option Nat))
    (intervention : QuittingStoppingIntervention ι) :
    PMF (QuittingTerminalOutcome ι) :=
  quittingIndependentTerminalOutcomeLaw (intervention.applyLaws laws)

omit [DecidableEq ι] in
theorem quittingIndependentTerminalOutcomeLaw_pure [Nonempty ι]
    (times : ι -> Option Nat) :
    quittingIndependentTerminalOutcomeLaw (fun who => PMF.pure (times who)) =
      PMF.pure (quittingFirstStoppingOutcome times) := by
  rw [quittingIndependentTerminalOutcomeLaw, Math.PMFProduct.pmfPi_pure,
    PMF.pure_map]

theorem quittingCounterfactualOutcomeLaw_pure [Nonempty ι]
    (times : ι -> Option Nat)
    (intervention : QuittingStoppingIntervention ι) :
    quittingCounterfactualOutcomeLaw
        (fun who => PMF.pure (times who)) intervention =
      PMF.pure (quittingFirstStoppingOutcome (intervention.applyTimes times)) := by
  rw [quittingCounterfactualOutcomeLaw,
    intervention.applyLaws_pure,
    quittingIndependentTerminalOutcomeLaw_pure]

omit [Fintype ι] in
private theorem applyLaws_update_of_not_mem
    (laws : ι -> PMF (Option Nat))
    (intervention : QuittingStoppingIntervention ι)
    {who : ι} (replacement : PMF (Option Nat))
    (hwho : who ∉ intervention.carrier) :
    intervention.applyLaws (Function.update laws who replacement) =
      Function.update (intervention.applyLaws laws) who replacement := by
  funext other
  by_cases hother : other = who
  · subst other
    simp [QuittingStoppingIntervention.applyLaws, hwho]
  · by_cases hcarrier : other ∈ intervention.carrier <;>
      simp [QuittingStoppingIntervention.applyLaws, hcarrier, hother]

omit [Fintype ι] in
private theorem applyLaws_insert_eq_update
    (laws : ι -> PMF (Option Nat))
    (intervention : QuittingStoppingIntervention ι)
    {who : ι} (time : Option Nat) :
    (intervention.insert who time).applyLaws laws =
      Function.update (intervention.applyLaws laws) who (PMF.pure time) := by
  funext other
  by_cases hother : other = who
  · subst other
    simp [QuittingStoppingIntervention.applyLaws,
      QuittingStoppingIntervention.insert]
  · by_cases hcarrier : other ∈ intervention.carrier <;>
      simp [QuittingStoppingIntervention.applyLaws,
        QuittingStoppingIntervention.insert, hcarrier, hother]

/-- One arbitrary marginal replacement is a mixture of pure extensions of
the current counterfactual intervention. -/
theorem quittingCounterfactualOutcomeLaw_update_eq_bind [Nonempty ι]
    (laws : ι -> PMF (Option Nat))
    (intervention : QuittingStoppingIntervention ι)
    {who : ι} (replacement : PMF (Option Nat))
    (hwho : who ∉ intervention.carrier) :
    quittingCounterfactualOutcomeLaw
        (Function.update laws who replacement) intervention =
      replacement.bind fun time =>
        quittingCounterfactualOutcomeLaw laws (intervention.insert who time) := by
  rw [quittingCounterfactualOutcomeLaw,
    applyLaws_update_of_not_mem laws intervention replacement hwho,
    quittingIndependentTerminalOutcomeLaw,
    Math.PMFProduct.pmfPi_update_bind,
    PMF.map_bind]
  congr 1
  funext time
  rw [quittingCounterfactualOutcomeLaw,
    applyLaws_insert_eq_update laws intervention time,
    quittingIndependentTerminalOutcomeLaw]

/-- Replacing a coordinate already fixed by the intervention changes nothing. -/
theorem quittingCounterfactualOutcomeLaw_update_of_mem [Nonempty ι]
    (laws : ι -> PMF (Option Nat))
    (intervention : QuittingStoppingIntervention ι)
    {who : ι} (replacement : PMF (Option Nat))
    (hwho : who ∈ intervention.carrier) :
    quittingCounterfactualOutcomeLaw
        (Function.update laws who replacement) intervention =
      quittingCounterfactualOutcomeLaw laws intervention := by
  have hfamily :
      intervention.applyLaws (Function.update laws who replacement) =
        intervention.applyLaws laws := by
    funext other
    by_cases hcarrier : other ∈ intervention.carrier
    · simp [QuittingStoppingIntervention.applyLaws, hcarrier]
    · have hother : other ≠ who := fun heq => hcarrier (heq ▸ hwho)
      simp [QuittingStoppingIntervention.applyLaws, hcarrier, hother]
  change quittingIndependentTerminalOutcomeLaw
      (intervention.applyLaws (Function.update laws who replacement)) =
    quittingIndependentTerminalOutcomeLaw (intervention.applyLaws laws)
  rw [hfamily]

/-- Quantitative replacement compiler: an unpinned marginal perturbation is
contracted from general TV to the finite terminal-law TV. -/
theorem pmfTV_quittingCounterfactualOutcomeLaw_update_le [Nonempty ι]
    (laws : ι -> PMF (Option Nat))
    (intervention : QuittingStoppingIntervention ι)
    {who : ι} (first second : PMF (Option Nat))
    (hwho : who ∉ intervention.carrier) :
    pmfTV
        (quittingCounterfactualOutcomeLaw
          (Function.update laws who first) intervention)
        (quittingCounterfactualOutcomeLaw
          (Function.update laws who second) intervention) <=
      pmfGeneralTV first second := by
  rw [quittingCounterfactualOutcomeLaw_update_eq_bind
      laws intervention first hwho,
    quittingCounterfactualOutcomeLaw_update_eq_bind
      laws intervention second hwho]
  exact Math.Probability.pmfTV_bind_le_pmfGeneralTV
    (fun time => quittingCounterfactualOutcomeLaw laws
      (intervention.insert who time)) first second

/-- Interventions of cardinality at most `order`. -/
abbrev QuittingCounterfactualQuery (ι : Type) [DecidableEq ι]
    (order : Nat) :=
  {intervention : QuittingStoppingIntervention ι //
    intervention.carrier.card <= order}

/-- The complete labelled counterfactual terminal-law state at one order. -/
def quittingCounterfactualState [Nonempty ι] (order : Nat)
    (laws : ι -> PMF (Option Nat)) :
    QuittingCounterfactualQuery ι order -> PMF (QuittingTerminalOutcome ι) :=
  fun query => quittingCounterfactualOutcomeLaw laws query.1

namespace QuittingStoppingIntervention

/-- Empty pure intervention. -/
def empty : QuittingStoppingIntervention ι where
  carrier := ∅
  stoppingTime := fun _ => none

/-- Pin one displayed player to one pure stopping time. -/
def pureTime (who : ι) (time : Option Nat) :
    QuittingStoppingIntervention ι where
  carrier := {who}
  stoppingTime := fun _ => time

end QuittingStoppingIntervention

/-- Expected value of an arbitrary terminal observable after an intervention. -/
def quittingCounterfactualExpectedValue [Nonempty ι]
    (laws : ι -> PMF (Option Nat))
    (intervention : QuittingStoppingIntervention ι)
    (value : QuittingTerminalOutcome ι -> Real) : Real :=
  expect (quittingCounterfactualOutcomeLaw laws intervention) value

/-- Current value is the empty-intervention coordinate. -/
def quittingCounterfactualCurrentValue [Nonempty ι]
    (laws : ι -> PMF (Option Nat))
    (value : QuittingTerminalOutcome ι -> Real) : Real :=
  quittingCounterfactualExpectedValue laws
    QuittingStoppingIntervention.empty value

/-- Pure-time payoff menu read from singleton intervention coordinates. -/
def quittingCounterfactualPureTimeValue [Nonempty ι]
    (laws : ι -> PMF (Option Nat)) (who : ι) (time : Option Nat)
    (value : QuittingTerminalOutcome ι -> Real) : Real :=
  quittingCounterfactualExpectedValue laws
    (QuittingStoppingIntervention.pureTime who time) value

/-- Supremum of one player's pure-time terminal-observable menu. -/
def quittingCounterfactualPureTimeCap [Nonempty ι]
    (laws : ι -> PMF (Option Nat)) (who : ι)
    (value : QuittingTerminalOutcome ι -> Real) : Real :=
  sSup (Set.range fun time : Option Nat =>
    quittingCounterfactualPureTimeValue laws who time value)

/-- Equality of order-one states determines the current expected value of
every terminal observable. -/
theorem quittingCounterfactualState_one_determines_currentValue
    [Nonempty ι] {first second : ι -> PMF (Option Nat)}
    (hstate : quittingCounterfactualState 1 first =
      quittingCounterfactualState 1 second)
    (value : QuittingTerminalOutcome ι -> Real) :
    quittingCounterfactualCurrentValue first value =
      quittingCounterfactualCurrentValue second value := by
  have hlaw := congrFun hstate
    (⟨QuittingStoppingIntervention.empty, by
      simp [QuittingStoppingIntervention.empty]⟩ :
      QuittingCounterfactualQuery ι 1)
  exact congrArg (fun law => expect law value) hlaw

/-- Equality of order-one states determines every pure-time menu entry. -/
theorem quittingCounterfactualState_one_determines_pureTimeValue
    [Nonempty ι] {first second : ι -> PMF (Option Nat)}
    (hstate : quittingCounterfactualState 1 first =
      quittingCounterfactualState 1 second)
    (who : ι) (time : Option Nat)
    (value : QuittingTerminalOutcome ι -> Real) :
    quittingCounterfactualPureTimeValue first who time value =
      quittingCounterfactualPureTimeValue second who time value := by
  have hlaw := congrFun hstate
    (⟨QuittingStoppingIntervention.pureTime who time, by
      simp [QuittingStoppingIntervention.pureTime]⟩ :
      QuittingCounterfactualQuery ι 1)
  exact congrArg (fun law => expect law value) hlaw

/-- Equality of order-one states determines every pure-time cap. -/
theorem quittingCounterfactualState_one_determines_pureTimeCap
    [Nonempty ι] {first second : ι -> PMF (Option Nat)}
    (hstate : quittingCounterfactualState 1 first =
      quittingCounterfactualState 1 second)
    (who : ι) (value : QuittingTerminalOutcome ι -> Real) :
    quittingCounterfactualPureTimeCap first who value =
      quittingCounterfactualPureTimeCap second who value := by
  unfold quittingCounterfactualPureTimeCap
  congr 2
  funext time
  exact quittingCounterfactualState_one_determines_pureTimeValue
    hstate who time value

/-- Literal order-one current-value and pure-time-cap projection package. -/
theorem quittingCounterfactualState_one_determines_value_and_caps
    [Nonempty ι] {first second : ι -> PMF (Option Nat)}
    (hstate : quittingCounterfactualState 1 first =
      quittingCounterfactualState 1 second)
    (value : QuittingTerminalOutcome ι -> Real) :
    quittingCounterfactualCurrentValue first value =
        quittingCounterfactualCurrentValue second value ∧
      forall who, quittingCounterfactualPureTimeCap first who value =
        quittingCounterfactualPureTimeCap second who value := by
  exact ⟨quittingCounterfactualState_one_determines_currentValue hstate value,
    fun who =>
      quittingCounterfactualState_one_determines_pureTimeCap
        hstate who value⟩

/-- Tuple of independent first-stopping laws induced by an actual behavior
profile on the live spine. -/
def quittingBehaviorStoppingLaws
    (reward : {S : Finset ι // S.Nonempty} -> Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) :
    ι -> PMF (Option Nat) :=
  fun who => quittingBehaviorStoppingLaw reward (profile who)

/-- Behavioral replacement is coordinate overwrite on stopping-law tuples. -/
theorem quittingBehaviorStoppingLaws_update
    (reward : {S : Finset ι // S.Nonempty} -> Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) (who : ι)
    (deviation : (quittingGame reward).BehaviorStrategy who) :
    quittingBehaviorStoppingLaws reward
        (Function.update profile who deviation) =
      Function.update (quittingBehaviorStoppingLaws reward profile) who
        (quittingBehaviorStoppingLaw reward deviation) := by
  funext other
  by_cases hother : other = who
  · subst other
    simp [quittingBehaviorStoppingLaws]
  · simp [quittingBehaviorStoppingLaws, hother]

/-- Counterfactual stopping-law state attached to an actual behavior profile.
This is a stopping-law adapter, not a literal-suffix construction. -/
def quittingBehaviorCounterfactualState [Nonempty ι]
    (reward : {S : Finset ι // S.Nonempty} -> Payoff ι)
    (order : Nat) (profile : (quittingGame reward).BehaviorProfile) :=
  quittingCounterfactualState order
    (quittingBehaviorStoppingLaws reward profile)

/-- Behavioral replacement feeds exactly the corresponding marginal overwrite
into the abstract counterfactual state. -/
theorem quittingBehaviorCounterfactualState_update [Nonempty ι]
    (reward : {S : Finset ι // S.Nonempty} -> Payoff ι)
    (order : Nat) (profile : (quittingGame reward).BehaviorProfile)
    (who : ι) (deviation : (quittingGame reward).BehaviorStrategy who) :
    quittingBehaviorCounterfactualState reward order
        (Function.update profile who deviation) =
      quittingCounterfactualState order
        (Function.update (quittingBehaviorStoppingLaws reward profile) who
          (quittingBehaviorStoppingLaw reward deviation)) := by
  rw [quittingBehaviorCounterfactualState,
    quittingBehaviorStoppingLaws_update]

/-- Pure-time payoff menu against one fixed actual opponent profile. -/
def quittingBehaviorPureTimePayoff
    (reward : {S : Finset ι // S.Nonempty} -> Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    (who : ι) (time : Option Nat) : Real :=
  quittingTerminalPayoff reward
    (Function.update profile who
      (quittingPureTimeBehaviorStrategy reward who time)) who

/-- An actual unilateral behavioral payoff is the stopping-law expectation of
the pure-time payoff menu. -/
theorem quittingTerminalPayoff_update_eq_expect_behaviorStoppingLaws
    (reward : {S : Finset ι // S.Nonempty} -> Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) (who : ι)
    (deviation : (quittingGame reward).BehaviorStrategy who) :
    quittingTerminalPayoff reward
        (Function.update profile who deviation) who =
      expect (quittingBehaviorStoppingLaws reward
        (Function.update profile who deviation) who)
        (quittingBehaviorPureTimePayoff reward profile who) := by
  calc
    _ = expect (quittingBehaviorStoppingLaw reward deviation)
        (quittingBehaviorPureTimePayoff reward profile who) := by
      change quittingTerminalPayoff reward
          (Function.update profile who deviation) who =
        expect (quittingBehaviorStoppingLaw reward deviation)
          (fun choice => quittingTerminalPayoff reward
            (Function.update profile who
              (quittingPureTimeBehaviorStrategy reward who choice)) who)
      exact quittingTerminalPayoff_update_eq_expect_stoppingLaw_pureTime
        reward profile who deviation
    _ = _ := by
      rw [show quittingBehaviorStoppingLaws reward
          (Function.update profile who deviation) who =
          quittingBehaviorStoppingLaw reward deviation by
        simp [quittingBehaviorStoppingLaws]]

/-- Prescribed payoff is the same stopping-law expectation with the prescribed
coordinate of the behavior adapter. -/
theorem quittingTerminalPayoff_eq_expect_behaviorStoppingLaws
    (reward : {S : Finset ι // S.Nonempty} -> Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) (who : ι) :
    quittingTerminalPayoff reward profile who =
      expect (quittingBehaviorStoppingLaws reward profile who)
        (quittingBehaviorPureTimePayoff reward profile who) := by
  simpa using
    quittingTerminalPayoff_update_eq_expect_behaviorStoppingLaws
      reward profile who (profile who)

/-- Complete behavioral deviation cap against one actual profile. -/
def quittingBehaviorDeviationPayoffCap
    (reward : {S : Finset ι // S.Nonempty} -> Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) (who : ι) : Real :=
  sSup (Set.range fun deviation :
      (quittingGame reward).BehaviorStrategy who =>
    quittingTerminalPayoff reward
      (Function.update profile who deviation) who)

/-- Pure-time payoff cap against one actual profile. -/
def quittingBehaviorPureTimePayoffCap
    (reward : {S : Finset ι // S.Nonempty} -> Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) (who : ι) : Real :=
  sSup (Set.range (quittingBehaviorPureTimePayoff reward profile who))

/-- The pure-time projection is literally the unrestricted behavioral cap. -/
theorem quittingBehaviorDeviationPayoffCap_eq_pureTime
    (reward : {S : Finset ι // S.Nonempty} -> Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) (who : ι) :
    quittingBehaviorDeviationPayoffCap reward profile who =
      quittingBehaviorPureTimePayoffCap reward profile who := by
  exact sSup_range_quittingTerminalPayoff_update_eq_pureTime
    reward profile who

/-- An order is replacement determining when equality of its counterfactual
states persists after every one-coordinate marginal replacement. -/
def QuittingCounterfactualReplacementDetermining [Nonempty ι]
    (order : Nat) : Prop :=
  forall first second : ι -> PMF (Option Nat),
    quittingCounterfactualState order first =
        quittingCounterfactualState order second ->
    forall who replacement,
      quittingCounterfactualState order
          (Function.update first who replacement) =
        quittingCounterfactualState order
          (Function.update second who replacement)

/-- Every order at least `card ι - 1` is closed under one arbitrary marginal
replacement. -/
theorem quittingCounterfactualReplacementDetermining_of_card_sub_one_le
    [Nonempty ι] {order : Nat} (horder : Fintype.card ι - 1 <= order) :
    QuittingCounterfactualReplacementDetermining (ι := ι) order := by
  intro first second hstate who replacement
  funext query
  change quittingCounterfactualOutcomeLaw
      (Function.update first who replacement) query.1 =
    quittingCounterfactualOutcomeLaw
      (Function.update second who replacement) query.1
  by_cases hwho : who ∈ query.1.carrier
  · rw [quittingCounterfactualOutcomeLaw_update_of_mem
        first query.1 replacement hwho,
      quittingCounterfactualOutcomeLaw_update_of_mem
        second query.1 replacement hwho]
    exact congrFun hstate query
  · by_cases hcard : query.1.carrier.card < Fintype.card ι - 1
    · rw [quittingCounterfactualOutcomeLaw_update_eq_bind
          first query.1 replacement hwho,
        quittingCounterfactualOutcomeLaw_update_eq_bind
          second query.1 replacement hwho]
      congr 1
      funext time
      exact congrFun hstate ⟨query.1.insert who time, by
        have hinsert : (query.1.insert who time).carrier.card <=
            Fintype.card ι - 1 := by
          simpa [QuittingStoppingIntervention.insert, hwho] using hcard
        exact hinsert.trans horder⟩
    · have hsubset :
          query.1.carrier ⊆ (Finset.univ : Finset ι).erase who := by
        intro other hother
        simp only [Finset.mem_erase, Finset.mem_univ, and_true]
        exact fun heq => hwho (heq ▸ hother)
      have hcardErase :
          ((Finset.univ : Finset ι).erase who).card = Fintype.card ι - 1 := by
        simp
      have hcardLe : query.1.carrier.card <= Fintype.card ι - 1 := by
        rw [← hcardErase]
        exact Finset.card_le_card hsubset
      have hcardEq : query.1.carrier.card = Fintype.card ι - 1 :=
        Nat.le_antisymm hcardLe (Nat.le_of_not_gt hcard)
      have hcarrier :
          query.1.carrier = (Finset.univ : Finset ι).erase who :=
        Finset.eq_of_subset_of_card_le hsubset (by simp [hcardErase, hcardEq])
      change quittingIndependentTerminalOutcomeLaw
          (query.1.applyLaws (Function.update first who replacement)) =
        quittingIndependentTerminalOutcomeLaw
          (query.1.applyLaws (Function.update second who replacement))
      congr 1
      funext other
      by_cases hother : other = who
      · subst other
        simp [QuittingStoppingIntervention.applyLaws, hwho]
      · have hotherCarrier : other ∈ query.1.carrier := by
          rw [hcarrier]
          simp [hother]
        simp [QuittingStoppingIntervention.applyLaws, hotherCarrier]

/-- Counterfactual laws through all but one label determine the same-order
state after one arbitrary marginal replacement. -/
theorem quittingCounterfactualReplacementDetermining_card_sub_one
    [Nonempty ι] :
    QuittingCounterfactualReplacementDetermining
      (ι := ι) (Fintype.card ι - 1) :=
  quittingCounterfactualReplacementDetermining_of_card_sub_one_le le_rfl

private theorem quittingFirstStoppingOutcome_eq_of_hidden_masked
    [Nonempty ι] (first second : ι -> Option Nat)
    {hidden blocker : ι}
    (hagree : forall other, other ≠ hidden -> first other = second other)
    (hfirst : quittingStoppingTimeValue (first blocker) <
      quittingStoppingTimeValue (first hidden))
    (hsecond : quittingStoppingTimeValue (second blocker) <
      quittingStoppingTimeValue (second hidden)) :
    quittingFirstStoppingOutcome first = quittingFirstStoppingOutcome second := by
  have hmin : quittingEarliestStoppingValue first =
      quittingEarliestStoppingValue second := by
    apply le_antisymm
    · obtain ⟨other, -, hother⟩ := Finset.exists_mem_eq_inf
        (Finset.univ : Finset ι) Finset.univ_nonempty
        (fun i => quittingStoppingTimeValue (second i))
      have hotherNe : other ≠ hidden := by
        intro heq
        subst other
        have hle := Finset.inf_le
          (f := fun i => quittingStoppingTimeValue (second i))
          (Finset.mem_univ blocker)
        rw [hother] at hle
        exact (not_lt_of_ge hle) hsecond
      have hle := Finset.inf_le
        (f := fun i => quittingStoppingTimeValue (first i))
        (Finset.mem_univ other)
      rw [hagree other hotherNe, ← hother] at hle
      exact hle
    · obtain ⟨other, -, hother⟩ := Finset.exists_mem_eq_inf
        (Finset.univ : Finset ι) Finset.univ_nonempty
        (fun i => quittingStoppingTimeValue (first i))
      have hotherNe : other ≠ hidden := by
        intro heq
        subst other
        have hle := Finset.inf_le
          (f := fun i => quittingStoppingTimeValue (first i))
          (Finset.mem_univ blocker)
        rw [hother] at hle
        exact (not_lt_of_ge hle) hfirst
      have hle := Finset.inf_le
        (f := fun i => quittingStoppingTimeValue (second i))
        (Finset.mem_univ other)
      rw [← hagree other hotherNe, ← hother] at hle
      exact hle
  have hcoalition : quittingEarliestStoppingCoalition first =
      quittingEarliestStoppingCoalition second := by
    ext other
    simp only [quittingEarliestStoppingCoalition, Finset.mem_filter,
      Finset.mem_univ, true_and]
    by_cases hother : other = hidden
    · subst other
      have hfirstLe := Finset.inf_le
        (f := fun i => quittingStoppingTimeValue (first i))
        (Finset.mem_univ blocker)
      have hsecondLe := Finset.inf_le
        (f := fun i => quittingStoppingTimeValue (second i))
        (Finset.mem_univ blocker)
      constructor <;> intro heq
      · rw [heq] at hfirst
        exact ((not_lt_of_ge hfirstLe) hfirst).elim
      · rw [heq] at hsecond
        exact ((not_lt_of_ge hsecondLe) hsecond).elim
    · rw [hagree other hother, hmin]
  unfold quittingFirstStoppingOutcome
  by_cases htop : quittingEarliestStoppingValue first = ⊤
  · have htopSecond : quittingEarliestStoppingValue second = ⊤ := by
      rw [← hmin]
      exact htop
    simp [htop, htopSecond]
  · have htopSecond : quittingEarliestStoppingValue second ≠ ⊤ := by
      intro heq
      apply htop
      rw [hmin]
      exact heq
    rw [if_neg htop, if_neg htopSecond]
    apply congrArg some
    exact Subtype.ext hcoalition

/-- Deterministic source with one hidden date between an early blocker set and
all remaining dates. -/
def quittingCounterfactualEarlyHiddenTimes
    (hidden : ι) (blockers : Finset ι) : ι -> Option Nat :=
  fun who => if who = hidden then some 1 else
    if who ∈ blockers then some 0 else some 2

/-- Companion source obtained by delaying the hidden date. -/
def quittingCounterfactualDelayedHiddenTimes
    (blockers : Finset ι) : ι -> Option Nat :=
  fun who => if who ∈ blockers then some 0 else some 2

omit [Fintype ι] in
private theorem counterfactual_hidden_profiles_agree_off
    {hidden other : ι} {blockers : Finset ι}
    (hother : other ≠ hidden) :
    quittingCounterfactualEarlyHiddenTimes hidden blockers other =
      quittingCounterfactualDelayedHiddenTimes blockers other := by
  simp [quittingCounterfactualEarlyHiddenTimes,
    quittingCounterfactualDelayedHiddenTimes, hother]

private theorem counterfactual_hidden_profiles_state_eq
    [Nonempty ι] {order : Nat} {hidden : ι} {blockers : Finset ι}
    (hhidden : hidden ∉ blockers) (hcard : blockers.card = order + 1) :
    quittingCounterfactualState order
        (fun who => PMF.pure
          (quittingCounterfactualEarlyHiddenTimes hidden blockers who)) =
      quittingCounterfactualState order
        (fun who => PMF.pure
          (quittingCounterfactualDelayedHiddenTimes blockers who)) := by
  funext query
  change quittingCounterfactualOutcomeLaw
      (fun who => PMF.pure
        (quittingCounterfactualEarlyHiddenTimes hidden blockers who)) query.1 =
    quittingCounterfactualOutcomeLaw
      (fun who => PMF.pure
        (quittingCounterfactualDelayedHiddenTimes blockers who)) query.1
  rw [quittingCounterfactualOutcomeLaw_pure,
    quittingCounterfactualOutcomeLaw_pure]
  congr 1
  by_cases hqueryHidden : hidden ∈ query.1.carrier
  · congr 1
    funext other
    by_cases hotherCarrier : other ∈ query.1.carrier
    · simp [QuittingStoppingIntervention.applyTimes, hotherCarrier]
    · have hother : other ≠ hidden := fun heq =>
        hotherCarrier (heq ▸ hqueryHidden)
      simp [QuittingStoppingIntervention.applyTimes, hotherCarrier,
        counterfactual_hidden_profiles_agree_off hother]
  · have hcardLt : query.1.carrier.card < blockers.card := by omega
    obtain ⟨blocker, hblocker, hblockerQuery⟩ :=
      Finset.exists_mem_notMem_of_card_lt_card hcardLt
    have hblockerNe : blocker ≠ hidden := fun heq =>
      hhidden (heq ▸ hblocker)
    apply quittingFirstStoppingOutcome_eq_of_hidden_masked
      (hidden := hidden) (blocker := blocker)
    · intro other hother
      by_cases hotherCarrier : other ∈ query.1.carrier
      · simp [QuittingStoppingIntervention.applyTimes, hotherCarrier]
      · simp [QuittingStoppingIntervention.applyTimes, hotherCarrier,
          counterfactual_hidden_profiles_agree_off hother]
    · simp [QuittingStoppingIntervention.applyTimes, hblockerQuery,
        hqueryHidden, quittingCounterfactualEarlyHiddenTimes,
        hblocker, hblockerNe, quittingStoppingTimeValue]
    · simp [QuittingStoppingIntervention.applyTimes, hblockerQuery,
        hqueryHidden, quittingCounterfactualDelayedHiddenTimes,
        hblocker, hhidden, quittingStoppingTimeValue]

private theorem quittingFirstStoppingOutcome_hidden_one_other_two
    [Nonempty ι] (hidden : ι) :
    quittingFirstStoppingOutcome
        (fun who : ι => if who = hidden then some 1 else some 2) =
      some ⟨{hidden}, Finset.singleton_nonempty hidden⟩ := by
  let times : ι -> Option Nat := fun who =>
    if who = hidden then some 1 else some 2
  have hmin : quittingEarliestStoppingValue times = 1 := by
    apply le_antisymm
    · exact (Finset.inf_le (f := fun who =>
        quittingStoppingTimeValue (times who))
        (Finset.mem_univ hidden)).trans_eq (by simp [times,
          quittingStoppingTimeValue])
    · apply Finset.le_inf
      intro who _
      by_cases hwho : who = hidden <;>
        simp [times, hwho, quittingStoppingTimeValue]
  have hcoalition : quittingEarliestStoppingCoalition times = {hidden} := by
    ext who
    by_cases hwho : who = hidden <;>
      simp [quittingEarliestStoppingCoalition, hmin, times, hwho,
        quittingStoppingTimeValue]
  change quittingFirstStoppingOutcome times = _
  unfold quittingFirstStoppingOutcome
  rw [if_neg (by simp [hmin])]
  apply congrArg some
  exact Subtype.ext hcoalition

omit [DecidableEq ι] in
private theorem quittingFirstStoppingOutcome_all_two
    [Nonempty ι] (witness : ι) :
    quittingFirstStoppingOutcome (fun _ : ι => some 2) =
      some ⟨Finset.univ, Finset.univ_nonempty⟩ := by
  let times : ι -> Option Nat := fun _ => some 2
  have hmin : quittingEarliestStoppingValue times = 2 := by
    apply le_antisymm
    · exact (Finset.inf_le (f := fun who =>
        quittingStoppingTimeValue (times who))
        (Finset.mem_univ witness)).trans_eq (by simp [times,
          quittingStoppingTimeValue])
    · apply Finset.le_inf
      intro who _
      simp [times, quittingStoppingTimeValue]
  have hcoalition : quittingEarliestStoppingCoalition times = Finset.univ := by
    ext who
    simp [quittingEarliestStoppingCoalition, hmin, times,
      quittingStoppingTimeValue]
  change quittingFirstStoppingOutcome times = _
  unfold quittingFirstStoppingOutcome
  rw [if_neg (by simp [hmin])]
  apply congrArg some
  exact Subtype.ext hcoalition

private theorem not_quittingCounterfactualReplacementDetermining_of_blockers
    [Nonempty ι] {order : Nat} {hidden : ι} {blockers : Finset ι}
    (hhidden : hidden ∉ blockers) (hcard : blockers.card = order + 1) :
    ¬QuittingCounterfactualReplacementDetermining (ι := ι) order := by
  let firstTimes := quittingCounterfactualEarlyHiddenTimes hidden blockers
  let secondTimes := quittingCounterfactualDelayedHiddenTimes blockers
  let firstLaws : ι -> PMF (Option Nat) := fun who => PMF.pure (firstTimes who)
  let secondLaws : ι -> PMF (Option Nat) := fun who => PMF.pure (secondTimes who)
  have hstate : quittingCounterfactualState order firstLaws =
      quittingCounterfactualState order secondLaws := by
    exact counterfactual_hidden_profiles_state_eq hhidden hcard
  have hblockers : blockers.Nonempty := Finset.card_pos.mp (by omega)
  obtain ⟨selected, hselected⟩ := hblockers
  have hselectedNe : selected ≠ hidden := fun heq =>
    hhidden (heq ▸ hselected)
  let intervention : QuittingStoppingIntervention ι :=
    { carrier := blockers.erase selected
      stoppingTime := fun _ => some 2 }
  have hinterventionCard : intervention.carrier.card <= order := by
    simp [intervention, Finset.card_erase_of_mem hselected, hcard]
  let query : QuittingCounterfactualQuery ι order :=
    ⟨intervention, hinterventionCard⟩
  intro hdetermining
  have hsuccess := hdetermining firstLaws secondLaws hstate selected
    (PMF.pure (some 2))
  have heq := congrFun hsuccess query
  change quittingCounterfactualOutcomeLaw
      (Function.update firstLaws selected (PMF.pure (some 2))) intervention =
    quittingCounterfactualOutcomeLaw
      (Function.update secondLaws selected (PMF.pure (some 2))) intervention at heq
  have hfirstUpdate :
      Function.update firstLaws selected (PMF.pure (some 2)) =
        fun who => PMF.pure ((Function.update firstTimes selected (some 2)) who) := by
    funext who
    by_cases hwho : who = selected <;>
      simp [firstLaws, hwho]
  have hsecondUpdate :
      Function.update secondLaws selected (PMF.pure (some 2)) =
        fun who => PMF.pure ((Function.update secondTimes selected (some 2)) who) := by
    funext who
    by_cases hwho : who = selected <;>
      simp [secondLaws, hwho]
  rw [hfirstUpdate, hsecondUpdate,
    quittingCounterfactualOutcomeLaw_pure,
    quittingCounterfactualOutcomeLaw_pure] at heq
  have hfirstApplied :
      intervention.applyTimes (Function.update firstTimes selected (some 2)) =
        fun who => if who = hidden then some 1 else some 2 := by
    funext who
    by_cases hwhoHidden : who = hidden
    · subst who
      have hhiddenCarrier : hidden ∉ intervention.carrier := by
        simp [intervention, hhidden]
      simp [QuittingStoppingIntervention.applyTimes, hhiddenCarrier,
        firstTimes, quittingCounterfactualEarlyHiddenTimes,
        Ne.symm hselectedNe]
    · by_cases hwhoCarrier : who ∈ intervention.carrier
      · simp [QuittingStoppingIntervention.applyTimes, hwhoCarrier,
          hwhoHidden, intervention]
      · by_cases hwhoSelected : who = selected
        · subst who
          simp [QuittingStoppingIntervention.applyTimes, intervention,
            hselected, hselectedNe]
        · have hwhoBlockers : who ∉ blockers := by
            intro hmem
            exact hwhoCarrier (by
              simp [intervention, hmem, hwhoSelected])
          simp [QuittingStoppingIntervention.applyTimes, hwhoCarrier,
            hwhoHidden, hwhoSelected, firstTimes,
            quittingCounterfactualEarlyHiddenTimes, hwhoBlockers]
  have hsecondApplied :
      intervention.applyTimes (Function.update secondTimes selected (some 2)) =
        fun _ : ι => some 2 := by
    funext who
    by_cases hwhoCarrier : who ∈ intervention.carrier
    · simp [QuittingStoppingIntervention.applyTimes, hwhoCarrier, intervention]
    · by_cases hwhoSelected : who = selected
      · subst who
        simp [QuittingStoppingIntervention.applyTimes, intervention, hselected]
      · have hwhoBlockers : who ∉ blockers := by
          intro hmem
          exact hwhoCarrier (by
            simp [intervention, hmem, hwhoSelected])
        simp [QuittingStoppingIntervention.applyTimes, hwhoCarrier,
          hwhoSelected, secondTimes,
          quittingCounterfactualDelayedHiddenTimes, hwhoBlockers]
  rw [hfirstApplied, hsecondApplied,
    quittingFirstStoppingOutcome_hidden_one_other_two hidden,
    quittingFirstStoppingOutcome_all_two selected] at heq
  have houtcomeNe :
      (some ⟨{hidden}, Finset.singleton_nonempty hidden⟩ :
          QuittingTerminalOutcome ι) ≠
        some ⟨Finset.univ, Finset.univ_nonempty⟩ := by
    intro houtcome
    have hsubtype := Option.some.inj houtcome
    have hfinset : ({hidden} : Finset ι) = Finset.univ :=
      congrArg Subtype.val hsubtype
    have hmem : selected ∈ ({hidden} : Finset ι) := by
      rw [hfinset]
      exact Finset.mem_univ selected
    exact hselectedNe (Finset.mem_singleton.mp hmem)
  have hmass := congrArg
    (fun law : PMF (QuittingTerminalOutcome ι) =>
      law (some ⟨{hidden}, Finset.singleton_nonempty hidden⟩)) heq
  simp [PMF.pure_apply, houtcomeNe] at hmass

/-- Every order at most `card ι - 2` admits a deterministic masking
counterexample to one-coordinate replacement closure. -/
theorem not_quittingCounterfactualReplacementDetermining_of_le_card_sub_two
    [Nonempty ι] {order : Nat} (hplayers : 2 <= Fintype.card ι)
    (horder : order <= Fintype.card ι - 2) :
    ¬QuittingCounterfactualReplacementDetermining (ι := ι) order := by
  let hidden : ι := Classical.choice inferInstance
  have hsize : order + 1 <= ((Finset.univ : Finset ι).erase hidden).card := by
    simp only [Finset.card_erase_of_mem (Finset.mem_univ hidden),
      Finset.card_univ]
    omega
  obtain ⟨blockers, hblockersSubset, hblockersCard⟩ :=
    Finset.exists_subset_card_eq hsize
  have hhidden : hidden ∉ blockers := by
    intro hmem
    exact (Finset.mem_erase.mp (hblockersSubset hmem)).1 rfl
  exact not_quittingCounterfactualReplacementDetermining_of_blockers
    hhidden hblockersCard

/-- Exact unrestricted-order characterization of replacement closure. -/
theorem quittingCounterfactualReplacementDetermining_iff [Nonempty ι]
    {order : Nat} :
    QuittingCounterfactualReplacementDetermining (ι := ι) order ↔
      Fintype.card ι - 1 <= order := by
  constructor
  · intro hdetermining
    by_contra hnot
    have hplayers : 2 <= Fintype.card ι := by omega
    have horder : order <= Fintype.card ι - 2 := by omega
    exact
      (not_quittingCounterfactualReplacementDetermining_of_le_card_sub_two
        hplayers horder) hdetermining
  · exact quittingCounterfactualReplacementDetermining_of_card_sub_one_le

/-- The labelled pure-intervention hierarchy has exact replacement threshold
`card ι - 1`: that order is closed, and every smaller admissible order is not. -/
theorem quittingCounterfactualReplacementDetermining_sharp [Nonempty ι] :
    2 <= Fintype.card ι ->
      QuittingCounterfactualReplacementDetermining
        (ι := ι) (Fintype.card ι - 1) ∧
      forall order, order <= Fintype.card ι - 2 ->
        ¬QuittingCounterfactualReplacementDetermining (ι := ι) order := by
  intro hplayers
  exact ⟨quittingCounterfactualReplacementDetermining_card_sub_one,
    fun _ horder =>
      not_quittingCounterfactualReplacementDetermining_of_le_card_sub_two
        hplayers horder⟩

end GameTheory
