/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.Cycles.BlockSurvival
import UniformEquilibrium.Quitting.Cycles.PeriodicFiniteHorizonRate

/-!
# A nonperiodic exact-path compiler for quitting games

This file is the game-facing consumer for graph-directed quitting paths.  Its
input is a supplied time-indexed sequence of product roots and bounded values.
There is no periodicity hypothesis.  Exact Bellman policy evaluation, exact
one-root Nash inequalities, and a uniform aligned block contraction compile
to:

* exact selection of the supplied initial value by terminal play;
* an exact terminal Nash profile;
* expected opponent-live time at most `K / (1-rho)`; and
* explicit `O(1/N)` finite-horizon Nash and delivery bounds.

The compact graph-directed pullback which produces such paths is deliberately
kept in a separate layer.
-/

noncomputable section

namespace GameTheory

open StochasticGame Filter Math.Probability Math.PMFProduct

variable {K : ℕ} {ι : Type} [Fintype ι] [DecidableEq ι]

/-- History-independent behavior profile generated by an arbitrary infinite
root path. -/
def quittingInfinitePathProfile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) :
    (quittingGame reward).BehaviorProfile :=
  quittingRootSequenceProfile reward roots 0

omit [DecidableEq ι] in
@[simp] theorem quittingProfileLiveRoot_infinitePathProfile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) :
    quittingProfileLiveRoot reward
        (quittingInfinitePathProfile reward roots) = roots := by
  funext time who
  simp [quittingProfileLiveRoot, quittingInfinitePathProfile,
    quittingRootSequenceProfile]

omit [DecidableEq ι] in
@[simp] theorem quittingTerminalPayoff_infinitePathProfile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) :
    quittingTerminalPayoff reward
        (quittingInfinitePathProfile reward roots) =
      fun who ↦ quittingRootSequenceTerminalValue reward roots who 0 := by
  rfl

/-! ## Selection of a bounded Bellman path -/

/-- Iterating a homogeneous one-step difference estimate produces the exact
opponent-survival prefix weight. -/
theorem abs_pathDifference_le_survival_mul
    (roots : ℕ → ι → PMF Bool) (who : ι)
    (difference : ℕ → ℝ)
    (hstep : ∀ time,
      |difference time| ≤
        quittingFixedOpponentsContinueMass roots who time *
          |difference (time + 1)|) :
    ∀ start fuel,
      |difference start| ≤
        quittingOpponentSurvivalWeight roots who start fuel *
          |difference (start + fuel)| := by
  intro start fuel
  induction fuel generalizing start with
  | zero => simp [quittingOpponentSurvivalWeight]
  | succ fuel ih =>
      have hfirst := hstep start
      have htail := ih (start + 1)
      have hmass0 := quittingStationaryContinueMass_nonneg
        (Function.update (roots start) who (PMF.pure false))
      have hscaled := mul_le_mul_of_nonneg_left htail hmass0
      calc
        |difference start| ≤
            quittingFixedOpponentsContinueMass roots who start *
              |difference (start + 1)| := hfirst
        _ ≤ quittingFixedOpponentsContinueMass roots who start *
            (quittingOpponentSurvivalWeight roots who (start + 1) fuel *
              |difference (start + 1 + fuel)|) := hscaled
        _ = quittingOpponentSurvivalWeight roots who start fuel.succ *
            |difference (start + fuel.succ)| := by
          rw [show fuel.succ = 1 + fuel by omega,
            quittingOpponentSurvivalWeight_add]
          simp [quittingOpponentSurvivalWeight]
          ring_nf

/-- Uniformly bounded exact Bellman values are uniquely selected by the
terminal root-sequence payoff once every playerwise opponent-survival tail
vanishes from every start. -/
theorem
    eq_quittingRootSequenceTerminalValue_of_exact_bounded_path_of_survival_tendsto_zero
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool)
    (value : ℕ → Payoff ι)
    {bound : ℝ}
    (hsurvival : ∀ who start,
      Tendsto (quittingOpponentSurvivalWeight roots who start)
        atTop (nhds 0))
    (hbound0 : 0 ≤ bound)
    (hreward : ∀ terminal who, |reward terminal who| ≤ bound)
    (hvalueBound : ∀ time who, |value time who| ≤ bound)
    (hpolicy : ∀ time,
      value time = quittingRootSuccessorPayoff reward
        (value (time + 1)) (roots time)) :
    ∀ time,
      value time =
        fun who ↦ quittingRootSequenceTerminalValue reward roots who time := by
  intro time
  funext who
  let terminal : ℕ → ℝ :=
    fun liveTime ↦
      quittingRootSequenceTerminalValue reward roots who liveTime
  let difference : ℕ → ℝ :=
    fun liveTime ↦ value liveTime who - terminal liveTime
  have hstep : ∀ liveTime,
      |difference liveTime| ≤
        quittingFixedOpponentsContinueMass roots who liveTime *
          |difference (liveTime + 1)| := by
    intro liveTime
    have hvalue := congrFun (hpolicy liveTime) who
    have hterminal :=
      quittingRootSequenceTerminalValue_eq_rootSuccessorPayoff
        reward roots who liveTime
    dsimp only [difference, terminal]
    rw [hvalue, hterminal]
    exact
      abs_quittingRootSuccessorPayoff_sub_le_fixedOpponentsContinueMass_mul
        reward (value (liveTime + 1))
          (fun _ ↦ quittingRootSequenceTerminalValue reward roots who
            (liveTime + 1))
          (roots liveTime) who
  have hiterate := abs_pathDifference_le_survival_mul
    roots who difference hstep time
  have htailBound : ∀ fuel,
      |difference (time + fuel)| ≤ 2 * bound := by
    intro fuel
    have hvalue := hvalueBound (time + fuel) who
    have hterminal := abs_quittingTerminalPayoff_le reward
      (quittingRootSequenceProfile reward roots (time + fuel)) who
      hbound0 hreward
    dsimp only [difference, terminal,
      quittingRootSequenceTerminalValue] at hterminal ⊢
    exact (abs_sub _ _).trans (by linarith)
  have hbound : ∀ fuel,
      |difference time| ≤
        quittingOpponentSurvivalWeight roots who time fuel *
          (2 * bound) := by
    intro fuel
    exact (hiterate fuel).trans
      (mul_le_mul_of_nonneg_left (htailBound fuel)
        (quittingOpponentSurvivalWeight_nonneg roots who time fuel))
  have hsurvivalWho := hsurvival who time
  have htendsto : Tendsto (fun fuel ↦
      quittingOpponentSurvivalWeight roots who time fuel * (2 * bound))
      atTop (nhds 0) := by
    simpa using hsurvivalWho.mul_const (2 * bound)
  have hzero : |difference time| ≤ 0 :=
    ge_of_tendsto' htendsto hbound
  have hdifference : difference time = 0 :=
    abs_eq_zero.mp (le_antisymm hzero (abs_nonneg _))
  dsimp only [difference, terminal] at hdifference
  exact sub_eq_zero.mp hdifference

/-- Uniform block contraction is a quantitative sufficient condition for the
qualitative Bellman-path selection theorem. -/
theorem eq_quittingRootSequenceTerminalValue_of_exact_bounded_path
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool)
    (value : ℕ → Payoff ι)
    {rho bound : ℝ}
    (hK : 0 < K)
    (hblock : IsQuittingOpponentBlockContraction roots K rho)
    (hrho0 : 0 ≤ rho) (hrho1 : rho < 1)
    (hbound0 : 0 ≤ bound)
    (hreward : ∀ terminal who, |reward terminal who| ≤ bound)
    (hvalueBound : ∀ time who, |value time who| ≤ bound)
    (hpolicy : ∀ time,
      value time = quittingRootSuccessorPayoff reward
        (value (time + 1)) (roots time)) :
    ∀ time,
      value time =
        fun who ↦ quittingRootSequenceTerminalValue reward roots who time := by
  exact
    eq_quittingRootSequenceTerminalValue_of_exact_bounded_path_of_survival_tendsto_zero
      reward roots value
        (fun who start ↦
          tendsto_zero_quittingOpponentSurvivalWeight_of_blockContraction
            roots hK hblock hrho0 hrho1 who start)
        hbound0 hreward hvalueBound hpolicy

/-! ## Exact terminal Nash compilation -/

/-- Exact root Nash along the selected path makes the actual terminal
prescribed Bellman residual vanish at every live time. -/
theorem quittingPrescribedOneStepResidual_infinitePath_eq_zero
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool)
    (value : ℕ → Payoff ι)
    (hselected : ∀ time,
      value time =
        fun who ↦ quittingRootSequenceTerminalValue reward roots who time)
    (hnash : ∀ time,
      IsεQuittingRootNash reward (value (time + 1)) 0 (roots time))
    (who : ι) (time : ℕ) :
    quittingPrescribedOneStepResidual reward roots who
        (quittingRootSequenceTerminalValue reward roots who) time = 0 := by
  let prescribed := quittingRootSequenceTerminalValue reward roots who
  have hrootNash : ∀ liveTime (deviation : PMF Bool),
      quittingRootExpectedPayoff reward
          (fun _ ↦ prescribed (liveTime + 1))
          (Function.update (roots liveTime) who deviation) who ≤
        quittingRootExpectedPayoff reward
            (fun _ ↦ prescribed (liveTime + 1))
            (roots liveTime) who + 0 := by
    intro liveTime deviation
    have htail : value (liveTime + 1) who =
        prescribed (liveTime + 1) := by
      exact congrFun (hselected (liveTime + 1)) who
    have hdeviationEq := quittingRootExpectedPayoff_continuation_congr
      reward (value (liveTime + 1))
        (fun _ ↦ prescribed (liveTime + 1))
        (Function.update (roots liveTime) who deviation) who htail
    have hrootEq := quittingRootExpectedPayoff_continuation_congr
      reward (value (liveTime + 1))
        (fun _ ↦ prescribed (liveTime + 1))
        (roots liveTime) who htail
    have hlocal := hnash liveTime who deviation
    rw [← hdeviationEq, ← hrootEq]
    exact hlocal
  exact quittingPrescribedOneStepResidual_eq_zero_of_isZeroRootNash
    reward roots who prescribed
      (isQuittingLivePrescribedValue_quittingRootSequenceTerminalValue
        reward roots who)
      hrootNash time

/-- A bounded exact Bellman/Nash path whose playerwise opponent-survival
clocks vanish from every start compiles to an exact terminal Nash profile and
delivers its supplied initial value. -/
theorem
    infinitePath_isZeroAsymptoticNash_and_delivers_of_survival_tendsto_zero
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool)
    (value : ℕ → Payoff ι)
    {bound : ℝ}
    (hsurvival : ∀ who start,
      Tendsto (quittingOpponentSurvivalWeight roots who start)
        atTop (nhds 0))
    (hbound0 : 0 ≤ bound)
    (hreward : ∀ terminal who, |reward terminal who| ≤ bound)
    (hvalueBound : ∀ time who, |value time who| ≤ bound)
    (hpolicy : ∀ time,
      value time = quittingRootSuccessorPayoff reward
        (value (time + 1)) (roots time))
    (hnash : ∀ time,
      IsεQuittingRootNash reward (value (time + 1)) 0 (roots time)) :
    (quittingGame reward).IsεAsymptoticNash
        (quittingTerminalPayoff reward) 0
        (quittingInfinitePathProfile reward roots) ∧
      quittingTerminalPayoff reward
          (quittingInfinitePathProfile reward roots) = value 0 := by
  have hselected :=
    eq_quittingRootSequenceTerminalValue_of_exact_bounded_path_of_survival_tendsto_zero
      reward roots value hsurvival hbound0 hreward hvalueBound hpolicy
  have hdelivery : quittingTerminalPayoff reward
      (quittingInfinitePathProfile reward roots) = value 0 := by
    funext who
    rw [quittingTerminalPayoff_infinitePathProfile]
    exact (congrFun (hselected 0) who).symm
  constructor
  · intro who deviation
    let prescribed := quittingRootSequenceTerminalValue reward roots who
    have hresidual : ∀ time,
        quittingPrescribedOneStepResidual reward roots who prescribed time =
          0 := by
      intro time
      exact quittingPrescribedOneStepResidual_infinitePath_eq_zero
        reward roots value hselected hnash who time
    have hsummable : Summable (fun time ↦
        quittingOpponentSurvivalWeight roots who 0 time *
          quittingPrescribedOneStepResidual reward roots who prescribed
            time) := by
      simpa only [hresidual, mul_zero] using
        (summable_zero : Summable (fun _ : ℕ ↦ (0 : ℝ)))
    have hsurvivalWho := hsurvival who 0
    have hgap :=
      quittingRootSequenceHazardTerminalGap_le_tsum_residual_of_survival_zero
        reward roots who (quittingBehaviorLiveHazard reward deviation)
          bound hbound0 hreward hsurvivalWho hsummable
    have hsum : (∑' time,
        quittingOpponentSurvivalWeight roots who 0 time *
          quittingPrescribedOneStepResidual reward roots who prescribed
            time) = 0 := by
      simp only [hresidual, mul_zero, tsum_zero]
    rw [hsum] at hgap
    have hdeviation :=
      quittingTerminalPayoff_update_eq_rootSequenceHazardTerminalValue
        reward (quittingInfinitePathProfile reward roots) who deviation
    rw [quittingProfileLiveRoot_infinitePathProfile] at hdeviation
    rw [hdeviation, quittingTerminalPayoff_infinitePathProfile]
    linarith
  · exact hdelivery

/-- Uniform block contraction supplies the qualitative tail hypothesis, hence
compiles a bounded exact Bellman/Nash path to exact terminal Nash play. -/
theorem infinitePath_isZeroAsymptoticNash_and_delivers
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool)
    (value : ℕ → Payoff ι)
    {rho bound : ℝ}
    (hK : 0 < K)
    (hblock : IsQuittingOpponentBlockContraction roots K rho)
    (hrho0 : 0 ≤ rho) (hrho1 : rho < 1)
    (hbound0 : 0 ≤ bound)
    (hreward : ∀ terminal who, |reward terminal who| ≤ bound)
    (hvalueBound : ∀ time who, |value time who| ≤ bound)
    (hpolicy : ∀ time,
      value time = quittingRootSuccessorPayoff reward
        (value (time + 1)) (roots time))
    (hnash : ∀ time,
      IsεQuittingRootNash reward (value (time + 1)) 0 (roots time)) :
    (quittingGame reward).IsεAsymptoticNash
        (quittingTerminalPayoff reward) 0
        (quittingInfinitePathProfile reward roots) ∧
      quittingTerminalPayoff reward
          (quittingInfinitePathProfile reward roots) = value 0 := by
  exact
    infinitePath_isZeroAsymptoticNash_and_delivers_of_survival_tendsto_zero
      reward roots value
        (fun who start ↦
          tendsto_zero_quittingOpponentSurvivalWeight_of_blockContraction
            roots hK hblock hrho0 hrho1 who start)
        hbound0 hreward hvalueBound hpolicy hnash

/-- Qualitative fixed-payoff corollary.  No common block rate is required:
bounded exact Bellman/Nash play selects `value 0`, and if every playerwise
opponent clock dies (possibly at a different, non-uniform rate), terminal
uniformization plus Cesàro payoff convergence makes `value 0` a uniform
equilibrium payoff. -/
theorem
    infinitePath_isUniformEquilibriumPayoff_of_survival_tendsto_zero
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool)
    (value : ℕ → Payoff ι)
    {bound : ℝ}
    (hsurvival : ∀ who start,
      Tendsto (quittingOpponentSurvivalWeight roots who start)
        atTop (nhds 0))
    (hbound0 : 0 ≤ bound)
    (hreward : ∀ terminal who, |reward terminal who| ≤ bound)
    (hvalueBound : ∀ time who, |value time who| ≤ bound)
    (hpolicy : ∀ time,
      value time = quittingRootSuccessorPayoff reward
        (value (time + 1)) (roots time))
    (hnash : ∀ time,
      IsεQuittingRootNash reward (value (time + 1)) 0 (roots time)) :
    (quittingGame reward).IsUniformEquilibriumPayoff none (value 0) := by
  let profile := quittingInfinitePathProfile reward roots
  have hcompiled :=
    infinitePath_isZeroAsymptoticNash_and_delivers_of_survival_tendsto_zero
      reward roots value hsurvival hbound0 hreward hvalueBound hpolicy hnash
  have hterminalNash : (quittingGame reward).IsεAsymptoticNash
      (quittingTerminalPayoff reward) 0 profile := by
    simpa only [profile] using hcompiled.1
  have hterminalValue : quittingTerminalPayoff reward profile = value 0 := by
    simpa only [profile] using hcompiled.2
  intro ε hε
  have huniform : (quittingGame reward).IsUniformεEquilibrium
      none ε profile :=
    quittingGame_isUniformεEquilibrium_of_terminalNash
      reward profile hε hterminalNash bound hbound0 hreward
  obtain ⟨nashThreshold, hnashThreshold⟩ := huniform
  have heventuallyDelivery : ∀ᶠ horizon : ℕ in atTop, ∀ who,
      |(quittingGame reward).finiteAveragePayoff none horizon profile who -
          value 0 who| ≤ ε := by
    apply Filter.eventually_all.mpr
    intro who
    have hball :=
      (tendsto_finiteAveragePayoff_quittingGame reward profile who).eventually
        (Metric.ball_mem_nhds
          (quittingTerminalPayoff reward profile who) hε)
    filter_upwards [hball] with horizon hhorizon
    have hvalue := congrFun hterminalValue who
    rw [hvalue] at hhorizon
    simpa [Metric.mem_ball, Real.dist_eq] using hhorizon.le
  obtain ⟨deliveryThreshold, hdeliveryThreshold⟩ :=
    Filter.eventually_atTop.1 heventuallyDelivery
  refine ⟨profile, max nashThreshold deliveryThreshold,
    fun horizon hhorizon ↦ ?_⟩
  constructor
  · exact hnashThreshold horizon
      (le_trans (Nat.le_max_left _ _) hhorizon)
  · exact hdeliveryThreshold horizon
      (le_trans (Nat.le_max_right _ _) hhorizon)

/-! ## Explicit finite-horizon transfer -/

/-- The opponent-live Cesàro clock of an infinite root path is the normalized
finite prefix of its opponent-survival weights. -/
theorem quittingOpponentLiveCesaro_infinitePathProfile_eq
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (who : ι) (horizon : ℕ) :
    quittingOpponentLiveCesaro reward
        (quittingInfinitePathProfile reward roots) who horizon =
      (horizon : ℝ)⁻¹ * ∑ time ∈ Finset.range horizon,
        quittingOpponentSurvivalWeight roots who 0 time := by
  unfold quittingOpponentLiveCesaro
  congr 1
  apply Finset.sum_congr rfl
  intro time _
  have hweight :=
    quittingOpponentSurvivalWeight_profileLiveRoot_eq_liveMass
      reward (quittingInfinitePathProfile reward roots) who time
  rw [quittingProfileLiveRoot_infinitePathProfile] at hweight
  simpa using hweight.symm

/-- Uniform block contraction gives the nonperiodic opponent-live boundary
`K / ((1-rho) * horizon)`. -/
theorem quittingOpponentLiveCesaro_infinitePathProfile_le
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool)
    {rho : ℝ}
    (hK : 0 < K)
    (hblock : IsQuittingOpponentBlockContraction roots K rho)
    (hrho0 : 0 ≤ rho) (hrho1 : rho < 1)
    (who : ι) (horizon : ℕ) :
    quittingOpponentLiveCesaro reward
        (quittingInfinitePathProfile reward roots) who horizon ≤
      ((K : ℝ) / (1 - rho)) / (horizon : ℝ) := by
  rw [quittingOpponentLiveCesaro_infinitePathProfile_eq]
  have hsum := sum_quittingOpponentSurvivalWeight_aligned_le
    roots hK hblock hrho0 hrho1 0 who horizon
  calc
    (horizon : ℝ)⁻¹ * ∑ time ∈ Finset.range horizon,
          quittingOpponentSurvivalWeight roots who 0 time ≤
        (horizon : ℝ)⁻¹ * ((K : ℝ) / (1 - rho)) := by
      simpa using mul_le_mul_of_nonneg_left hsum (by positivity)
    _ = ((K : ℝ) / (1 - rho)) / (horizon : ℝ) := by ring

/-- The expected opponent-live time of the compiled path obeys the same
geometric block budget. -/
theorem quittingExpectedOpponentLiveTime_infinitePath_le
    (roots : ℕ → ι → PMF Bool)
    {rho : ℝ}
    (hK : 0 < K)
    (hblock : IsQuittingOpponentBlockContraction roots K rho)
    (hrho0 : 0 ≤ rho) (hrho1 : rho < 1)
    (who : ι) :
    quittingExpectedOpponentLiveTime roots who 0 ≤
      (K : ℝ) / (1 - rho) := by
  simpa using quittingExpectedOpponentLiveTime_aligned_le
    roots hK hblock hrho0 hrho1 0 who

/-- A bounded exact Bellman/Nash path with uniform block contraction compiles
at every positive horizon `N` to Nash error
`2 * bound * K / ((1-rho) * N)`, while its payoff is within the corresponding
one-boundary error of the supplied initial value. -/
theorem infinitePath_isHorizonNash_and_delivers
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool)
    (value : ℕ → Payoff ι)
    {rho bound : ℝ} {N : ℕ}
    (hK : 0 < K)
    (hblock : IsQuittingOpponentBlockContraction roots K rho)
    (hrho0 : 0 ≤ rho) (hrho1 : rho < 1)
    (hbound0 : 0 ≤ bound)
    (hreward : ∀ terminal who, |reward terminal who| ≤ bound)
    (hvalueBound : ∀ time who, |value time who| ≤ bound)
    (hpolicy : ∀ time,
      value time = quittingRootSuccessorPayoff reward
        (value (time + 1)) (roots time))
    (hnash : ∀ time,
      IsεQuittingRootNash reward (value (time + 1)) 0 (roots time))
    (hN : 0 < N) :
    (quittingGame reward).IsεHorizonNash none N
        (2 * bound * (K : ℝ) / ((1 - rho) * (N : ℝ)))
        (quittingInfinitePathProfile reward roots) ∧
      ∀ who,
        |(quittingGame reward).finiteAveragePayoff none N
              (quittingInfinitePathProfile reward roots) who -
            value 0 who| ≤
          bound * (K : ℝ) / ((1 - rho) * (N : ℝ)) := by
  let profile := quittingInfinitePathProfile reward roots
  let clockBudget := (K : ℝ) / ((1 - rho) * (N : ℝ))
  let boundaryError := bound * clockBudget
  have hgap : 1 - rho ≠ 0 := by linarith
  have hNreal : (N : ℝ) ≠ 0 := by
    exact_mod_cast (Nat.ne_of_gt hN)
  have hterminal := infinitePath_isZeroAsymptoticNash_and_delivers
    reward roots value hK hblock hrho0 hrho1 hbound0 hreward
      hvalueBound hpolicy hnash
  have hterminalNash : (quittingGame reward).IsεAsymptoticNash
      (quittingTerminalPayoff reward) 0 profile := by
    simpa only [profile] using hterminal.1
  have hterminalValue : quittingTerminalPayoff reward profile = value 0 := by
    simpa only [profile] using hterminal.2
  have hclock : ∀ who,
      quittingOpponentLiveCesaro reward profile who N ≤ clockBudget := by
    intro who
    have hraw := quittingOpponentLiveCesaro_infinitePathProfile_le
      reward roots hK hblock hrho0 hrho1 who N
    have hrewrite : ((K : ℝ) / (1 - rho)) / (N : ℝ) =
        clockBudget := by
      dsimp only [clockBudget]
      field_simp
    simpa only [profile] using hraw.trans_eq hrewrite
  have hdelivery : ∀ who,
      |(quittingGame reward).finiteAveragePayoff none N profile who -
          quittingTerminalPayoff reward profile who| ≤ boundaryError := by
    intro who
    have htail :=
      abs_finiteAveragePayoff_sub_terminal_le_opponentLiveCesaro
        reward profile who N hN bound hbound0
          (fun terminal ↦ hreward terminal who)
    have hscaled := mul_le_mul_of_nonneg_left (hclock who) hbound0
    exact htail.trans (by
      simpa only [boundaryError] using hscaled)
  have hdeviation : ∀ who
      (deviation : (quittingGame reward).BehaviorStrategy who),
      (quittingGame reward).finiteAveragePayoff none N
          (Function.update profile who deviation) who ≤
        quittingTerminalPayoff reward
            (Function.update profile who deviation) who + boundaryError := by
    intro who deviation
    have hfinite :=
      finiteAveragePayoff_update_le_terminal_add_opponentLiveCesaro'
        reward profile who deviation N hN bound hbound0
          (fun terminal ↦ hreward terminal who)
    have hscaled := mul_le_mul_of_nonneg_left (hclock who) hbound0
    exact hfinite.trans (add_le_add (le_refl _) (by
      simpa only [boundaryError] using hscaled))
  have hfinite :=
    hterminalNash.isεHorizonNash_of_explicitBounds hdelivery hdeviation
  constructor
  · have herror : 0 + boundaryError + boundaryError =
        2 * bound * (K : ℝ) / ((1 - rho) * (N : ℝ)) := by
      dsimp only [boundaryError, clockBudget]
      ring
    rw [herror] at hfinite
    simpa only [profile] using hfinite
  · intro who
    have hown := hdelivery who
    rw [hterminalValue] at hown
    have herror : boundaryError =
        bound * (K : ℝ) / ((1 - rho) * (N : ℝ)) := by
      dsimp only [boundaryError, clockBudget]
      ring
    rw [herror] at hown
    simpa only [profile] using hown

end GameTheory
