import UniformEquilibrium.Quitting.Paths.PureTimeDeadlineProfile

/-!
# Literal pure-time replacement ancestry and deadline-rank induction

This layer records only unilateral replacement ancestry.  It does not call an
erasure profitable or best; game-semantic hypotheses are supplied by later
minimum-fibre consumers.
-/

noncomputable section

namespace GameTheory

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- One literal unilateral replacement of a canonical pure-time profile. -/
def IsQuittingPureTimeUnilateralReplacement
    (first second : QuittingPureTimeProfile ι) : Prop :=
  ∃ (who : ι) (replacement : Option ℕ),
    second = Function.update first who replacement

/-- Finite ancestry generated by literal unilateral pure-time replacements. -/
def IsQuittingPureTimeReplacementAncestry
    (first second : QuittingPureTimeProfile ι) : Prop :=
  Relation.ReflTransGen IsQuittingPureTimeUnilateralReplacement first second

omit [Fintype ι] in
theorem isQuittingPureTimeUnilateralReplacement_update
    (times : QuittingPureTimeProfile ι) (who : ι)
    (replacement : Option ℕ) :
    IsQuittingPureTimeUnilateralReplacement times
      (Function.update times who replacement) := by
  exact ⟨who, replacement, rfl⟩

omit [Fintype ι] in
theorem isQuittingPureTimeReplacementAncestry_update
    (times : QuittingPureTimeProfile ι) (who : ι)
    (replacement : Option ℕ) :
    IsQuittingPureTimeReplacementAncestry times
      (Function.update times who replacement) :=
  Relation.ReflTransGen.single
    (isQuittingPureTimeUnilateralReplacement_update times who replacement)

/-- Replacing one displayed quitter by `Never` literally erases it from that
date's coalition. -/
theorem quittingPureTimeCoalitionAt_update_none_eq_erase
    (times : QuittingPureTimeProfile ι) (who : ι) (time : ℕ) :
    quittingPureTimeCoalitionAt (Function.update times who none) time =
      (quittingPureTimeCoalitionAt times time).erase who := by
  rw [quittingPureTimeCoalitionAt_update, if_neg (by simp)]

/-- A distinct retained anchor survives one neutral anchored erasure. -/
theorem mem_quittingPureTimeCoalitionAt_update_none_of_ne
    (times : QuittingPureTimeProfile ι) {anchor owner : ι} {time : ℕ}
    (hanchor : anchor ∈ quittingPureTimeCoalitionAt times time)
    (hne : anchor ≠ owner) :
    anchor ∈ quittingPureTimeCoalitionAt
      (Function.update times owner none) time := by
  rw [quittingPureTimeCoalitionAt_update_none_eq_erase]
  exact Finset.mem_erase.mpr ⟨hne, hanchor⟩

/-- Simultaneously written endpoint of finitely many neutral `Never`
replacements.  Its ancestry is serialized below, not this definition. -/
def quittingPureTimeErasePlayers
    (times : QuittingPureTimeProfile ι) (players : Finset ι) :
    QuittingPureTimeProfile ι :=
  fun who => if who ∈ players then none else times who

omit [Fintype ι] in
@[simp] theorem quittingPureTimeErasePlayers_apply_of_mem
    (times : QuittingPureTimeProfile ι) (players : Finset ι) {who : ι}
    (hwho : who ∈ players) :
    quittingPureTimeErasePlayers times players who = none := by
  simp [quittingPureTimeErasePlayers, hwho]

omit [Fintype ι] in
@[simp] theorem quittingPureTimeErasePlayers_apply_of_not_mem
    (times : QuittingPureTimeProfile ι) (players : Finset ι) {who : ι}
    (hwho : who ∉ players) :
    quittingPureTimeErasePlayers times players who = times who := by
  simp [quittingPureTimeErasePlayers, hwho]

omit [Fintype ι] in
/-- The simultaneous endpoint has a finite literal unilateral-replacement
ancestry, one neutral `Never` update per selected player. -/
theorem isQuittingPureTimeReplacementAncestry_erasePlayers
    (times : QuittingPureTimeProfile ι) (players : Finset ι) :
    IsQuittingPureTimeReplacementAncestry times
      (quittingPureTimeErasePlayers times players) := by
  induction players using Finset.induction_on with
  | empty =>
      have heq : quittingPureTimeErasePlayers times ∅ = times := by
        funext who
        simp [quittingPureTimeErasePlayers]
      rw [heq]
      exact Relation.ReflTransGen.refl
  | @insert player players hnot ih =>
      have hupdate : quittingPureTimeErasePlayers times (insert player players) =
          Function.update (quittingPureTimeErasePlayers times players)
            player none := by
        funext who
        by_cases hwho : who = player
        · subst who
          simp [quittingPureTimeErasePlayers]
        · simp [quittingPureTimeErasePlayers, hwho]
      rw [hupdate]
      exact ih.tail
        (isQuittingPureTimeUnilateralReplacement_update
          (quittingPureTimeErasePlayers times players) player none)

/-- Erasing players deletes exactly those players from every displayed-date
coalition. -/
theorem quittingPureTimeCoalitionAt_erasePlayers
    (times : QuittingPureTimeProfile ι) (players : Finset ι) (time : ℕ) :
    quittingPureTimeCoalitionAt
        (quittingPureTimeErasePlayers times players) time =
      quittingPureTimeCoalitionAt times time \ players := by
  ext who
  by_cases hwho : who ∈ players <;>
    simp [quittingPureTimeCoalitionAt, quittingPureTimeErasePlayers, hwho]

/-- Neutral `Never` erasures introduce no new finite deadline. -/
theorem quittingPureTimeDeadlineRank_erasePlayers_le
    (times : QuittingPureTimeProfile ι) (players : Finset ι) :
    quittingPureTimeDeadlineRank (quittingPureTimeErasePlayers times players) ≤
      quittingPureTimeDeadlineRank times := by
  unfold quittingPureTimeDeadlineRank
  apply Finset.card_le_card
  intro time htime
  obtain ⟨who, hwho⟩ :=
    (mem_quittingPureTimeDeadlineSupport_iff _ time).1 htime
  have hwhoNot : who ∉ players := by
    intro hmem
    rw [quittingPureTimeErasePlayers_apply_of_mem times players hmem] at hwho
    simp at hwho
  apply (mem_quittingPureTimeDeadlineSupport_iff times time).2
  exact ⟨who, by
    rw [quittingPureTimeErasePlayers_apply_of_not_mem times players hwhoNot] at hwho
    exact hwho⟩

/-- Erasing every member of one displayed coalition except a retained anchor
leaves exactly that singleton coalition and records literal ancestry. -/
theorem exists_anchorErase_ancestry_coalitionAt_eq_singleton
    (times : QuittingPureTimeProfile ι) (anchor : ι) (time : ℕ)
    (hanchor : anchor ∈ quittingPureTimeCoalitionAt times time) :
    ∃ target,
      IsQuittingPureTimeReplacementAncestry times target ∧
      quittingPureTimeCoalitionAt target time = {anchor} := by
  let players := (quittingPureTimeCoalitionAt times time).erase anchor
  refine ⟨quittingPureTimeErasePlayers times players,
    isQuittingPureTimeReplacementAncestry_erasePlayers times players, ?_⟩
  rw [quittingPureTimeCoalitionAt_erasePlayers]
  ext who
  simp only [players, Finset.mem_sdiff, Finset.mem_erase,
    Finset.mem_singleton]
  constructor
  · rintro ⟨hmem, hnot⟩
    by_contra hne
    exact hnot ⟨hne, hmem⟩
  · rintro rfl
    exact ⟨hanchor, by simp⟩

/-- Abstract well-founded deadline-rank descent.  If every non-exit minimum
has a literal replacement to a minimum of strictly smaller deadline rank,
then a finite replacement ancestry reaches an exit. -/
theorem exists_pureTimeReplacementAncestry_of_deadlineRank_descent
    (Minimum Exit : QuittingPureTimeProfile ι → Prop)
    (hstep : ∀ current, Minimum current →
      Exit current ∨
        ∃ next,
          IsQuittingPureTimeUnilateralReplacement current next ∧
          Minimum next ∧
          quittingPureTimeDeadlineRank next <
            quittingPureTimeDeadlineRank current)
    (initial : QuittingPureTimeProfile ι) (hminimum : Minimum initial) :
    ∃ target,
      IsQuittingPureTimeReplacementAncestry initial target ∧ Exit target := by
  induction hrankEq : quittingPureTimeDeadlineRank initial using
      Nat.strong_induction_on generalizing initial with
  | h rank ih =>
      rcases hstep initial hminimum with hexit | ⟨next, hnext, hminimumNext, hrank⟩
      · exact ⟨initial, Relation.ReflTransGen.refl, hexit⟩
      · obtain ⟨target, hancestry, hexit⟩ :=
          ih (quittingPureTimeDeadlineRank next) (by
            rw [← hrankEq]
            exact hrank) next hminimumNext rfl
        exact ⟨target,
          (Relation.ReflTransGen.single hnext).trans hancestry, hexit⟩

/-- The same well-founded induction when one descent round already packages a
finite neutral replacement ancestry. -/
theorem exists_pureTimeReplacementAncestry_of_ancestry_deadlineRank_descent
    (Minimum Exit : QuittingPureTimeProfile ι → Prop)
    (hstep : ∀ current, Minimum current →
      Exit current ∨
        ∃ next,
          IsQuittingPureTimeReplacementAncestry current next ∧
          Minimum next ∧
          quittingPureTimeDeadlineRank next <
            quittingPureTimeDeadlineRank current)
    (initial : QuittingPureTimeProfile ι) (hminimum : Minimum initial) :
    ∃ target,
      IsQuittingPureTimeReplacementAncestry initial target ∧ Exit target := by
  induction hrankEq : quittingPureTimeDeadlineRank initial using
      Nat.strong_induction_on generalizing initial with
  | h rank ih =>
      rcases hstep initial hminimum with hexit | ⟨next, hnext, hminimumNext, hrank⟩
      · exact ⟨initial, Relation.ReflTransGen.refl, hexit⟩
      · obtain ⟨target, hancestry, hexit⟩ :=
          ih (quittingPureTimeDeadlineRank next) (by
            rw [← hrankEq]
            exact hrank) next hminimumNext rfl
        exact ⟨target, hnext.trans hancestry, hexit⟩

end GameTheory
