/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.Boundary.Exceptional.BellmanTail

/-!
# Terminal payoff of a supplied quitting root sequence

A sequence of product roots defines a history-independent behavior profile.
The finite zero-boundary root recursion is exactly that profile's expected
stage payoff at the cutoff.  Consequently the finite root payoffs converge
to the existing terminal payoff selected by the stochastic-game API.
-/

noncomputable section

namespace GameTheory

open StochasticGame Filter Math.Probability Math.PMFProduct

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- History-independent behavior profile generated by a root sequence,
starting at a supplied live time. -/
def quittingRootSequenceProfile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (start : ℕ) :
    (quittingGame reward).BehaviorProfile :=
  fun player time _ => roots (start + time) player

/-- Replacing one coordinate of every root by a supplied hazard sequence. -/
def quittingRootSequenceUpdate
    (roots : ℕ → ι → PMF Bool) (who : ι)
    (hazard : ℕ → PMF Bool) (time : ℕ) : ι → PMF Bool :=
  Function.update (roots time) who (hazard time)

omit [DecidableEq ι] in
/-- Shifting a root-sequence profile by one completed stage advances its
starting live time, independently of the realized root action. -/
theorem shiftProfile_quittingRootSequenceProfile
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (start : ℕ)
    (action : ι → Bool) :
    (quittingGame reward).shiftProfile
        (quittingRootSequenceProfile reward roots start) (none, action) =
      quittingRootSequenceProfile reward roots (start + 1) := by
  funext player time history
  simp [StochasticGame.shiftProfile, quittingRootSequenceProfile,
    Nat.add_comm, Nat.add_left_comm]

/-- The finite root recursion equals the cutoff expected stage payoff of
the corresponding history-independent profile. -/
theorem quittingFiniteRootPayoff_eq_expectedStagePayoff_rootSequence
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (who : ι)
    (hazard : ℕ → PMF Bool) :
    ∀ start fuel,
      quittingFiniteRootPayoff reward roots who hazard start fuel =
        (quittingGame reward).expectedStagePayoff
          (quittingRootSequenceProfile reward
            (quittingRootSequenceUpdate roots who hazard) start)
          none fuel who := by
  intro start fuel
  induction fuel generalizing start with
  | zero =>
      rw [quittingFiniteRootPayoff]
      unfold StochasticGame.expectedStagePayoff
      rw [(quittingGame reward).histDist_zero, expect_pure,
        stageEUAt_quittingGame_eq_stateReward]
      rfl
  | succ fuel ih =>
      rw [quittingFiniteRootPayoff,
        expectedStagePayoff_succ_quittingGame_eq_rootContinuation]
      unfold quittingRootExpectedPayoff
      change
        expect (pmfPi (Function.update (roots start) who (hazard start)))
            (fun action => quittingRootPayoff reward
              (fun _ => quittingFiniteRootPayoff reward roots who hazard
                (start + 1) fuel) action who) =
          expect (pmfPi (Function.update (roots start) who (hazard start)))
            (fun action =>
              if h : (quittingQuitters action).Nonempty then
                reward ⟨quittingQuitters action, h⟩ who
              else
                (quittingGame reward).expectedStagePayoff
                  ((quittingGame reward).shiftProfile
                    (quittingRootSequenceProfile reward
                      (quittingRootSequenceUpdate roots who hazard) start)
                    (none, action)) none fuel who)
      apply congrArg (expect
        (pmfPi (Function.update (roots start) who (hazard start))))
      funext action
      by_cases hquit : (quittingQuitters action).Nonempty
      · simp [quittingRootPayoff, hquit]
      · rw [dif_neg hquit, quittingRootPayoff]
        simp only [hquit, ↓reduceDIte]
        rw [shiftProfile_quittingRootSequenceProfile]
        simpa [quittingRootSequenceUpdate] using ih (start + 1)

/-- Finite root payoffs converge to the terminal payoff of the generated
root-sequence profile. -/
theorem tendsto_quittingFiniteRootPayoff_terminal
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (who : ι)
    (hazard : ℕ → PMF Bool) (start : ℕ) :
    Tendsto (fun fuel =>
      quittingFiniteRootPayoff reward roots who hazard start fuel)
      atTop (nhds (quittingTerminalPayoff reward
        (quittingRootSequenceProfile reward
          (quittingRootSequenceUpdate roots who hazard) start) who)) := by
  simpa only [quittingFiniteRootPayoff_eq_expectedStagePayoff_rootSequence]
    using tendsto_expectedStagePayoff_quittingGame reward
      (quittingRootSequenceProfile reward
        (quittingRootSequenceUpdate roots who hazard) start) who

end GameTheory
