/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.Paths.LiveTail
import UniformEquilibrium.Quitting.Root.TerminalSemanticPair

/-!
# Terminal reward moments of the semantic carrier

The prescribed coordinate of every executable terminal semantic pair is a
mixture of the finitely many coalition reward vectors and the zero payoff of
Never.  This remains true in the attainable semantic closure because the
finite reward-moment polytope is compact.

For a rational reward table, membership in this polytope is an exact finite
linear feasibility problem over one simplex variable per terminal coalition
plus Never.  This is a necessary carrier-realizability condition; it makes no
claim that an arbitrary feasible terminal-outcome law is generated by a
behavior profile.
-/

noncomputable section

namespace GameTheory

open Set StochasticGame
open scoped Topology

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- Terminal outcomes consist of Never and one atom for every nonempty
quitting coalition. -/
abbrev QuittingTerminalOutcome (ι : Type) :=
  Option {S : Finset ι // S.Nonempty}

/-- Reward vector attached to a terminal outcome; Never pays zero. -/
def quittingTerminalOutcomeReward
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :
    QuittingTerminalOutcome ι → Payoff ι
  | none => 0
  | some terminal => reward terminal

/-- The terminal outcome law generated by an executable behavior profile. -/
def quittingTerminalOutcomeMass
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) :
    QuittingTerminalOutcome ι → ℝ
  | none => quittingLiveMassLimit reward profile
  | some terminal => quittingAbsorbedMassLimit reward profile terminal

omit [DecidableEq ι] in
/-- Finite-time absorption masses are nonnegative. -/
theorem quittingAbsorbedMass_nonneg_terminalMoment
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) (time : ℕ)
    (terminal : {S : Finset ι // S.Nonempty}) :
    0 ≤ quittingAbsorbedMass reward profile time terminal := by
  unfold quittingAbsorbedMass StochasticGame.expectedStateValue
  apply Math.Probability.expect_nonneg
  intro history
  by_cases hs : history.2 = some terminal <;>
    simp [quittingAbsorbedIndicator, hs]

omit [DecidableEq ι] in
/-- Every executable terminal outcome law belongs to the standard simplex. -/
theorem quittingTerminalOutcomeMass_mem_stdSimplex
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) :
    quittingTerminalOutcomeMass reward profile ∈
      stdSimplex ℝ (QuittingTerminalOutcome ι) := by
  constructor
  · intro outcome
    cases outcome with
    | none => exact quittingLiveMassLimit_nonneg reward profile
    | some terminal =>
        exact (quittingAbsorbedMass_nonneg_terminalMoment
          reward profile 0 terminal).trans
            (quittingAbsorbedMass_le_limit reward profile 0 terminal)
  · simpa [quittingTerminalOutcomeMass] using
      quittingLiveMassLimit_add_sum_absorbedMassLimit reward profile

/-- Barycentric evaluation of one terminal-outcome law. -/
def quittingTerminalRewardMoment
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (mass : QuittingTerminalOutcome ι → ℝ) : Payoff ι :=
  fun who => ∑ outcome,
    mass outcome * quittingTerminalOutcomeReward reward outcome who

/-- The finite reward-moment polytope. -/
def quittingTerminalRewardMomentSet
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) : Set (Payoff ι) :=
  quittingTerminalRewardMoment reward ''
    stdSimplex ℝ (QuittingTerminalOutcome ι)

omit [DecidableEq ι] in
/-- Barycentric reward evaluation is continuous in the finite outcome law. -/
theorem continuous_quittingTerminalRewardMoment
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :
    Continuous (quittingTerminalRewardMoment reward) := by
  apply continuous_pi
  intro who
  apply continuous_finsetSum
  intro outcome _
  exact (continuous_apply outcome).mul continuous_const

omit [DecidableEq ι] in
/-- The finite reward-moment set is compact. -/
theorem quittingTerminalRewardMomentSet_isCompact
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :
    IsCompact (quittingTerminalRewardMomentSet reward) := by
  exact (isCompact_stdSimplex ℝ (QuittingTerminalOutcome ι)).image
    (continuous_quittingTerminalRewardMoment reward)

omit [DecidableEq ι] in
/-- An executable terminal payoff is exactly its finite outcome moment. -/
theorem quittingTerminalRewardMoment_outcomeMass
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) :
    quittingTerminalRewardMoment reward
        (quittingTerminalOutcomeMass reward profile) =
      quittingTerminalPayoff reward profile := by
  funext who
  simp [quittingTerminalRewardMoment, quittingTerminalOutcomeMass,
    quittingTerminalOutcomeReward, quittingTerminalPayoff]

omit [DecidableEq ι] in
/-- Every executable prescribed terminal payoff lies in the reward-moment
polytope. -/
theorem quittingTerminalPayoff_mem_rewardMomentSet
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) :
    quittingTerminalPayoff reward profile ∈
      quittingTerminalRewardMomentSet reward := by
  refine ⟨quittingTerminalOutcomeMass reward profile,
    quittingTerminalOutcomeMass_mem_stdSimplex reward profile, ?_⟩
  exact quittingTerminalRewardMoment_outcomeMass reward profile

/-- The prescribed coordinate of every point in the attainable semantic
closure lies in the finite reward-moment polytope. -/
theorem quittingTerminalSemanticCarrier_prescribed_mem_rewardMomentSet
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (pair : QuittingTerminalSemanticPair ι)
    (hpair : pair ∈ quittingTerminalSemanticCarrier reward) :
    pair.1 ∈ quittingTerminalRewardMomentSet reward := by
  change pair ∈ {candidate : QuittingTerminalSemanticPair ι |
    candidate.1 ∈ quittingTerminalRewardMomentSet reward}
  apply (closure_minimal ?_ ?_) hpair
  · rintro candidate ⟨profile, rfl⟩
    exact quittingTerminalPayoff_mem_rewardMomentSet reward profile
  · exact (quittingTerminalRewardMomentSet_isCompact reward).isClosed.preimage
      continuous_fst

end GameTheory
