/-
Copyright (c) 2026 UniformEquilibrium contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: UniformEquilibrium contributors
-/

import
  UniformEquilibrium.Diagnostics.Quitting.Collision.SingletonPacket.PunishmentNormalAtomicCollisionHandoff
import
  UniformEquilibrium.Diagnostics.Quitting.Collision.Toggles.LargePersistentBaseDeletionAdapter
import
  UniformEquilibrium.Diagnostics.Quitting.Collision.Toggles.LargeBaseStationarySemanticHandoff
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticNegativeVertexGerm
import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticResetIncidenceReturn

/-!
# Stationary two-debtor handoff from a four-player leave--join chain

Force the middle label of a quantitative leave--join chain to Quit, force the
fourth label to Continue, and select an exact Nash point of the induced binary
game played by the leaving and joining labels.  The resulting stationary
profile has a quantitative joiner hazard, a fixed pair-or-triple terminal
atom, and zero unrestricted behavioral debt in both free coordinates.

Terminal exploitability is therefore localized to the two remaining labels
and decoded into a paid first-disagreement row on this literal stationary
profile.  This is a source for the paid-return route, not a Bellman return or
a uniform-equilibrium construction.
-/

noncomputable section

namespace GameTheory

open Math.Probability Math.PMFProduct
open QuittingSureSetOwnerRepair

/-- The two free labels of the constrained leave--join game. -/
def finFourLeaveJoinFree (leaver joiner : Fin 4) : Finset (Fin 4) :=
  {leaver, joiner}

/-- The ambient product root selected from the constrained binary game. -/
def finFourLeaveJoinRoot
    (spectator leaver joiner : Fin 4)
    (point : mixedPolytope
      (quittingBinaryForm (finFourLeaveJoinFree leaver joiner)).sig) :
    Fin 4 → PMF Bool :=
  quittingPersistentBaseRoot {spectator}
    (finFourLeaveJoinFree leaver joiner) point

/-- The literal stationary behavior profile generated by the selected root. -/
def finFourLeaveJoinProfile
    (reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4))
    (spectator leaver joiner : Fin 4)
    (point : mixedPolytope
      (quittingBinaryForm (finFourLeaveJoinFree leaver joiner)).sig) :
    (quittingGame reward).BehaviorProfile :=
  quittingStationaryProfile reward
    (finFourLeaveJoinRoot spectator leaver joiner point)

/-- The actual prescribed/envelope pair of the selected stationary profile. -/
def finFourLeaveJoinSemanticPair
    (reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4))
    (spectator leaver joiner : Fin 4)
    (point : mixedPolytope
      (quittingBinaryForm (finFourLeaveJoinFree leaver joiner)).sig) :
    QuittingTerminalSemanticPair (Fin 4) :=
  quittingTerminalSemanticPair reward
    (finFourLeaveJoinProfile reward spectator leaver joiner point)

/-- Players with strictly positive unrestricted behavioral debt at the
selected stationary profile. -/
def finFourLeaveJoinPositiveDebtSupport
    (reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4))
    (spectator leaver joiner : Fin 4)
    (point : mixedPolytope
      (quittingBinaryForm (finFourLeaveJoinFree leaver joiner)).sig) :
    Finset (Fin 4) :=
  Finset.univ.filter fun who =>
    0 < (finFourLeaveJoinSemanticPair reward spectator leaver joiner point).2 who -
      (finFourLeaveJoinSemanticPair reward spectator leaver joiner point).1 who

/-- Data retained by the quantitative stationary handoff. -/
structure FinFourLeaveJoinStationaryTwoDebtorHandoff
    (reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4))
    (witness : QuittingTerminalExploitabilityWitness reward)
    (M : ℝ) (leaver spectator joiner fourth : Fin 4) where
  point : mixedPolytope
    (quittingBinaryForm (finFourLeaveJoinFree leaver joiner)).sig
  point_mem : point ∈ quittingPersistentBaseNashSet reward {spectator}
    (finFourLeaveJoinFree leaver joiner)
  alpha_pos : 0 < witness.terminalGap / (witness.terminalGap + 2 * M)
  alpha_le_one : witness.terminalGap / (witness.terminalGap + 2 * M) ≤ 1
  joiner_hazard_lower :
    witness.terminalGap / (witness.terminalGap + 2 * M) ≤
      ((finFourLeaveJoinRoot spectator leaver joiner point) joiner true).toReal
  pair_terminal_mass :
    quittingTerminalOutcomeMass reward
        (finFourLeaveJoinProfile reward spectator leaver joiner point)
        (some ⟨{spectator, joiner}, by simp⟩) =
      (1 - ((finFourLeaveJoinRoot spectator leaver joiner point)
          leaver true).toReal) *
        ((finFourLeaveJoinRoot spectator leaver joiner point) joiner true).toReal
  triple_terminal_mass :
    quittingTerminalOutcomeMass reward
        (finFourLeaveJoinProfile reward spectator leaver joiner point)
        (some ⟨{leaver, spectator, joiner}, by simp⟩) =
      ((finFourLeaveJoinRoot spectator leaver joiner point)
          leaver true).toReal *
        ((finFourLeaveJoinRoot spectator leaver joiner point) joiner true).toReal
  containing_mass_eq_joiner_hazard :
    quittingTerminalOutcomeMass reward
          (finFourLeaveJoinProfile reward spectator leaver joiner point)
          (some ⟨{spectator, joiner}, by simp⟩) +
        quittingTerminalOutcomeMass reward
          (finFourLeaveJoinProfile reward spectator leaver joiner point)
          (some ⟨{leaver, spectator, joiner}, by simp⟩) =
      ((finFourLeaveJoinRoot spectator leaver joiner point) joiner true).toReal
  heavy_atom :
    witness.terminalGap / (2 * (witness.terminalGap + 2 * M)) ≤
        quittingTerminalOutcomeMass reward
          (finFourLeaveJoinProfile reward spectator leaver joiner point)
          (some ⟨{spectator, joiner}, by simp⟩) ∨
      witness.terminalGap / (2 * (witness.terminalGap + 2 * M)) ≤
        quittingTerminalOutcomeMass reward
          (finFourLeaveJoinProfile reward spectator leaver joiner point)
          (some ⟨{leaver, spectator, joiner}, by simp⟩)
  leaver_solved :
    let pair := finFourLeaveJoinSemanticPair reward spectator leaver joiner point
    pair.2 leaver = pair.1 leaver ∧
      quittingPunishmentValue reward leaver ≤ pair.1 leaver
  joiner_solved :
    let pair := finFourLeaveJoinSemanticPair reward spectator leaver joiner point
    pair.2 joiner = pair.1 joiner ∧
      quittingPunishmentValue reward joiner ≤ pair.1 joiner
  positiveDebtSupport_nonempty :
    (finFourLeaveJoinPositiveDebtSupport reward spectator leaver joiner point).Nonempty
  positiveDebtSupport_subset :
    finFourLeaveJoinPositiveDebtSupport reward spectator leaver joiner point ⊆
      {spectator, fourth}
  positiveDebtSupport_card_le_two :
    (finFourLeaveJoinPositiveDebtSupport reward spectator leaver joiner point).card ≤ 2
  debtor : Fin 4
  debtor_mem : debtor ∈ ({spectator, fourth} : Finset (Fin 4))
  debtor_gap :
    witness.terminalGap ≤
      (finFourLeaveJoinSemanticPair reward spectator leaver joiner point).2 debtor -
        (finFourLeaveJoinSemanticPair reward spectator leaver joiner point).1 debtor
  paid_row : Nonempty (QuittingPaidFirstDisagreementRow reward
    (finFourLeaveJoinProfile reward spectator leaver joiner point)
      debtor witness.terminalGap)

private theorem quittingRootEndpointDifference_zero_pureSetRoot
    (reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4))
    (coalition : Finset (Fin 4)) (who : Fin 4)
    (herase : (coalition.erase who).Nonempty) :
    quittingRootEndpointDifference reward 0
        (quittingPureSetRoot coalition) who =
      quittingSetReward reward (insert who coalition) who -
        quittingSetReward reward (coalition.erase who) who := by
  rw [quittingRootEndpointDifference,
    quittingRootQuitPayoff_pureSetRoot_eq_insert,
    quittingRootContinuePayoff_pureSetRoot_eq_erase_of_nonempty
      (0 : Payoff (Fin 4)) coalition who herase]

/-- A quantitative leave--join chain on four distinct labels constructs the
stationary handoff with two solved coordinates and at most two debtors. -/
theorem nonempty_finFourLeaveJoinStationaryTwoDebtorHandoff
    {reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4)}
    (witness : QuittingTerminalExploitabilityWitness reward)
    (M : ℝ)
    (hbound : ∀ terminal who, |reward terminal who| ≤ M)
    (leaver spectator joiner fourth : Fin 4)
    (hleaverSpectator : leaver ≠ spectator)
    (hleaverJoiner : leaver ≠ joiner)
    (hleaverFourth : leaver ≠ fourth)
    (hspectatorJoiner : spectator ≠ joiner)
    (hspectatorFourth : spectator ≠ fourth)
    (hjoinerFourth : joiner ≠ fourth)
    (hleave : quittingSetReward reward {leaver, spectator} leaver +
        witness.terminalGap ≤
      quittingSetReward reward {spectator} leaver)
    (hjoin : quittingSetReward reward {spectator} joiner +
        witness.terminalGap ≤
      quittingSetReward reward {spectator, joiner} joiner) :
    Nonempty (FinFourLeaveJoinStationaryTwoDebtorHandoff reward witness M
      leaver spectator joiner fourth) := by
  have hM := quittingRewardCoordinateBound_nonneg_of_player reward leaver hbound
  let free := finFourLeaveJoinFree leaver joiner
  have hdisjoint : Disjoint ({spectator} : Finset (Fin 4)) free := by
    simp [free, finFourLeaveJoinFree, hleaverSpectator.symm,
      hspectatorJoiner]
  obtain ⟨point, hpoint⟩ :=
    quittingPersistentBaseNashSet_nonempty reward {spectator} free
  let root := finFourLeaveJoinRoot spectator leaver joiner point
  let profile := finFourLeaveJoinProfile reward spectator leaver joiner point
  let pair := finFourLeaveJoinSemanticPair reward spectator leaver joiner point
  let x := (root leaver true).toReal
  let y := (root joiner true).toReal
  have hrootSpectator : root spectator = PMF.pure true := by
    exact quittingPersistentBaseRoot_apply_of_mem_base
      {spectator} free point (by simp)
  have hrootFourth : root fourth = PMF.pure false := by
    apply quittingPersistentBaseRoot_apply_of_outside
    simp [finFourLeaveJoinFree, hleaverFourth.symm,
      hspectatorFourth.symm, hjoinerFourth.symm]
  have hpairDisjoint : Disjoint ({leaver, spectator} : Finset (Fin 4))
      {joiner, fourth} := by
    simp [hleaverJoiner.symm, hleaverFourth.symm,
      hspectatorJoiner.symm, hspectatorFourth.symm]
  have hunionCard :
      (({leaver, spectator} : Finset (Fin 4)) ∪ {joiner, fourth}).card = 4 := by
    rw [Finset.card_union_of_disjoint hpairDisjoint,
      Finset.card_pair hleaverSpectator,
      Finset.card_pair hjoinerFourth]
  have hunion :
      ({leaver, spectator} : Finset (Fin 4)) ∪ {joiner, fourth} =
        Finset.univ := by
    apply Finset.eq_univ_of_card
    simpa using hunionCard
  have hexhaust : ∀ who : Fin 4,
      who = leaver ∨ who = spectator ∨ who = joiner ∨ who = fourth := by
    intro who
    have hmem : who ∈
        ({leaver, spectator} : Finset (Fin 4)) ∪ {joiner, fourth} := by
      rw [hunion]
      exact Finset.mem_univ who
    simp only [Finset.mem_union, Finset.mem_insert,
      Finset.mem_singleton] at hmem
    rcases hmem with (h | h) | h | h
    · exact Or.inl h
    · exact Or.inr (Or.inl h)
    · exact Or.inr (Or.inr (Or.inl h))
    · exact Or.inr (Or.inr (Or.inr h))
  have hrootFF :
      Function.update
          (Function.update root joiner (PMF.pure false))
          leaver (PMF.pure false) =
        quittingPureSetRoot ({spectator} : Finset (Fin 4)) := by
    funext who
    rcases hexhaust who with h | h | h | h <;> subst who <;>
      simp [hrootSpectator, hrootFourth, quittingPureSetRoot,
        quittingSetAction, hleaverSpectator, hleaverSpectator.symm,
        hleaverJoiner.symm, hleaverFourth.symm, hspectatorJoiner,
        hspectatorJoiner.symm, hspectatorFourth.symm,
        hjoinerFourth.symm]
  have hrootFT :
      Function.update
          (Function.update root joiner (PMF.pure true))
          leaver (PMF.pure false) =
        quittingPureSetRoot ({spectator, joiner} : Finset (Fin 4)) := by
    funext who
    rcases hexhaust who with h | h | h | h <;> subst who <;>
      simp [hrootSpectator, hrootFourth, quittingPureSetRoot,
        quittingSetAction, hleaverSpectator, hleaverSpectator.symm,
        hleaverJoiner, hleaverJoiner.symm, hleaverFourth.symm,
        hspectatorJoiner, hspectatorJoiner.symm,
        hspectatorFourth.symm, hjoinerFourth.symm]
  have hrootCF :
      Function.update
          (Function.update root joiner (PMF.pure false))
          leaver (PMF.pure true) =
        quittingPureSetRoot ({leaver, spectator} : Finset (Fin 4)) := by
    funext who
    rcases hexhaust who with h | h | h | h <;> subst who <;>
      simp [hrootSpectator, hrootFourth, quittingPureSetRoot,
        quittingSetAction, hleaverSpectator, hleaverSpectator.symm,
        hleaverJoiner.symm, hleaverFourth.symm, hspectatorJoiner,
        hspectatorJoiner.symm, hspectatorFourth.symm,
        hjoinerFourth.symm]
  have hrootCT :
      Function.update
          (Function.update root joiner (PMF.pure true))
          leaver (PMF.pure true) =
        quittingPureSetRoot
          ({leaver, spectator, joiner} : Finset (Fin 4)) := by
    funext who
    rcases hexhaust who with h | h | h | h <;> subst who <;>
      simp [hrootSpectator, hrootFourth, quittingPureSetRoot,
        quittingSetAction, hleaverSpectator, hleaverSpectator.symm,
        hleaverJoiner, hleaverJoiner.symm, hleaverFourth.symm,
        hspectatorJoiner, hspectatorJoiner.symm,
        hspectatorFourth.symm, hjoinerFourth.symm]
  let alpha : Bool → ℝ := fun action =>
    quittingRootEndpointDifference reward 0
      (Function.update root joiner (PMF.pure action)) leaver
  let beta : Bool → ℝ := fun action =>
    quittingRootEndpointDifference reward 0
      (Function.update root leaver (PMF.pure action)) joiner
  have halphaFalse : alpha false =
      quittingSetReward reward {leaver, spectator} leaver -
        quittingSetReward reward {spectator} leaver := by
    dsimp only [alpha]
    rw [← quittingRootEndpointDifference_update_self reward 0
      (Function.update root joiner (PMF.pure false)) leaver (PMF.pure false),
      hrootFF,
      quittingRootEndpointDifference_zero_pureSetRoot]
    · simp [hleaverSpectator]
    · simp [hleaverSpectator]
  have halphaTrue : alpha true =
      quittingSetReward reward {leaver, spectator, joiner} leaver -
        quittingSetReward reward {spectator, joiner} leaver := by
    dsimp only [alpha]
    rw [← quittingRootEndpointDifference_update_self reward 0
      (Function.update root joiner (PMF.pure true)) leaver (PMF.pure true),
      hrootCT,
      quittingRootEndpointDifference_zero_pureSetRoot]
    · simp [hleaverSpectator, hleaverJoiner]
    · simp [hleaverSpectator, hleaverJoiner]
  have hbetaFalse : beta false =
      quittingSetReward reward {spectator, joiner} joiner -
        quittingSetReward reward {spectator} joiner := by
    dsimp only [beta]
    rw [← quittingRootEndpointDifference_update_self reward 0
      (Function.update root leaver (PMF.pure false)) joiner (PMF.pure false)]
    have hcomm :
        Function.update
            (Function.update root leaver (PMF.pure false))
            joiner (PMF.pure false) =
          Function.update
            (Function.update root joiner (PMF.pure false))
            leaver (PMF.pure false) := by
      exact Function.update_comm hleaverJoiner (PMF.pure false)
        (PMF.pure false) root
    rw [hcomm, hrootFF,
      quittingRootEndpointDifference_zero_pureSetRoot]
    · simp [hspectatorJoiner.symm,
        quittingSetReward, Finset.pair_comm]
    · simp [hspectatorJoiner.symm]
  have hnash := isBinaryDifferenceNash_of_mem_quittingPersistentBaseNashSet_pair
    reward {spectator} free (by simp) hdisjoint point hpoint
      (first := leaver) (second := joiner)
      (by simp [free, finFourLeaveJoinFree])
      (by simp [free, finFourLeaveJoinFree]) hleaverJoiner
  change IsBinaryDifferenceNash alpha beta x y at hnash
  rcases hnash with ⟨hx, hy, hcContinue, hcQuit, htContinue, htQuit⟩
  have halphaFalseBound : alpha false ≤ -witness.terminalGap := by
    rw [halphaFalse]
    linarith
  have htripleUpper :
      quittingSetReward reward {leaver, spectator, joiner} leaver ≤ M := by
    have h := (abs_le.mp
      (hbound ⟨{leaver, spectator, joiner}, by simp⟩ leaver)).2
    simpa [quittingSetReward] using h
  have hpairLower : -M ≤
      quittingSetReward reward {spectator, joiner} leaver := by
    have h := (abs_le.mp
      (hbound ⟨{spectator, joiner}, by simp⟩ leaver)).1
    simpa [quittingSetReward] using h
  have halphaTrueBound : alpha true ≤ 2 * M := by
    rw [halphaTrue]
    linarith
  have hsingletonLower : -M ≤
      quittingSetReward reward {spectator} joiner := by
    have h := (abs_le.mp
      (hbound ⟨{spectator}, by simp⟩ joiner)).1
    simpa [quittingSetReward] using h
  have hpairJoinerUpper :
      quittingSetReward reward {spectator, joiner} joiner ≤ M := by
    have h := (abs_le.mp
      (hbound ⟨{spectator, joiner}, by simp⟩ joiner)).2
    simpa [quittingSetReward] using h
  have hgapLe : witness.terminalGap ≤ 2 * M := by
    linarith
  have hdenom : 0 < witness.terminalGap + 2 * M := by
    exact add_pos_of_pos_of_nonneg witness.terminalGap_pos
      (mul_nonneg (by norm_num) hM)
  have halphaPos :
      0 < witness.terminalGap / (witness.terminalGap + 2 * M) :=
    div_pos witness.terminalGap_pos hdenom
  have halphaLeOne :
      witness.terminalGap / (witness.terminalGap + 2 * M) ≤ 1 := by
    apply (div_le_one hdenom).2
    linarith
  have hyLower :
      witness.terminalGap / (witness.terminalGap + 2 * M) ≤ y := by
    by_cases hxZero : x = 0
    · have hbetaAtZero :
          binarySecondDifference beta x = beta false := by
        simp [binarySecondDifference, hxZero]
      have hbetaPositive : witness.terminalGap ≤
          binarySecondDifference beta x := by
        rw [hbetaAtZero, hbetaFalse]
        linarith
      have hyOne : y = 1 := by
        nlinarith [hy.1, hy.2, witness.terminalGap_pos]
      rw [hyOne]
      exact halphaLeOne
    · have hxPos : 0 < x := lt_of_le_of_ne hx.1 (Ne.symm hxZero)
      have hfirstNonneg : 0 ≤ binaryFirstDifference alpha y := by
        nlinarith [hcQuit]
      have hweighted :
          0 ≤ -(1 - y) * witness.terminalGap + 2 * M * y := by
        dsimp only [binaryFirstDifference] at hfirstNonneg
        nlinarith [hy.1, hy.2]
      apply (div_le_iff₀ hdenom).2
      nlinarith
  have hcontinueMass : quittingStationaryContinueMass root = 0 :=
    quittingStationaryContinueMass_eq_zero_of_owner_eq_pure hrootSpectator
  have hterminalMass (terminal : {S : Finset (Fin 4) // S.Nonempty}) :
      quittingTerminalOutcomeMass reward profile (some terminal) =
        quittingRootCoalitionMass root terminal.val := by
    change quittingAbsorbedMassLimit reward profile terminal = _
    have hprefix := quittingAbsorbedMassLimit_rootThenContinuation
      reward root profile terminal
    have hsplice : quittingRootThenContinuationProfile reward root profile =
        profile := by
      change quittingRootThenContinuationProfile reward root
          (quittingStationaryProfile reward root) =
        quittingStationaryProfile reward root
      exact quittingRootThenContinuationProfile_stationary reward root
    rw [hsplice, hcontinueMass, zero_mul, add_zero] at hprefix
    exact hprefix
  have hpairComplement :
      ({spectator, joiner} : Finset (Fin 4))ᶜ = {leaver, fourth} := by
    ext who
    rcases hexhaust who with h | h | h | h <;> subst who <;>
      simp [hleaverSpectator, hleaverSpectator.symm, hleaverJoiner,
        hleaverJoiner.symm, hleaverFourth, hleaverFourth.symm,
        hspectatorJoiner, hspectatorJoiner.symm, hspectatorFourth,
        hspectatorFourth.symm, hjoinerFourth, hjoinerFourth.symm]
  have htripleComplement :
      ({leaver, spectator, joiner} : Finset (Fin 4))ᶜ = {fourth} := by
    ext who
    rcases hexhaust who with h | h | h | h <;> subst who <;>
      simp [hleaverSpectator, hleaverSpectator.symm, hleaverJoiner,
        hleaverJoiner.symm, hleaverFourth, hleaverFourth.symm,
        hspectatorJoiner, hspectatorJoiner.symm, hspectatorFourth,
        hspectatorFourth.symm, hjoinerFourth, hjoinerFourth.symm]
  have hpairRootMass :
      quittingRootCoalitionMass root {spectator, joiner} = (1 - x) * y := by
    unfold quittingRootCoalitionMass quittingRootQuitRates coalitionMass
    rw [hpairComplement]
    simp [x, y, hrootSpectator, hrootFourth, hleaverFourth,
      hspectatorJoiner]
    ring
  have htripleRootMass :
      quittingRootCoalitionMass root {leaver, spectator, joiner} = x * y := by
    unfold quittingRootCoalitionMass quittingRootQuitRates coalitionMass
    rw [htripleComplement]
    simp [x, y, hrootSpectator, hrootFourth, hleaverSpectator,
      hleaverJoiner, hspectatorJoiner]
  have hpairTerminal :
      quittingTerminalOutcomeMass reward profile
          (some ⟨{spectator, joiner}, by simp⟩) = (1 - x) * y := by
    rw [hterminalMass]
    exact hpairRootMass
  have htripleTerminal :
      quittingTerminalOutcomeMass reward profile
          (some ⟨{leaver, spectator, joiner}, by simp⟩) = x * y := by
    rw [hterminalMass]
    exact htripleRootMass
  have hcontainingMass :
      quittingTerminalOutcomeMass reward profile
            (some ⟨{spectator, joiner}, by simp⟩) +
          quittingTerminalOutcomeMass reward profile
            (some ⟨{leaver, spectator, joiner}, by simp⟩) = y := by
    rw [hpairTerminal, htripleTerminal]
    ring
  have hheavy :
      witness.terminalGap / (2 * (witness.terminalGap + 2 * M)) ≤
          quittingTerminalOutcomeMass reward profile
            (some ⟨{spectator, joiner}, by simp⟩) ∨
        witness.terminalGap / (2 * (witness.terminalGap + 2 * M)) ≤
          quittingTerminalOutcomeMass reward profile
            (some ⟨{leaver, spectator, joiner}, by simp⟩) := by
    have hhalf : witness.terminalGap / (2 * (witness.terminalGap + 2 * M)) =
        (witness.terminalGap / (witness.terminalGap + 2 * M)) / 2 := by
      field_simp
    rw [hhalf]
    by_cases hpairHeavy :
        (witness.terminalGap / (witness.terminalGap + 2 * M)) / 2 ≤
          quittingTerminalOutcomeMass reward profile
            (some ⟨{spectator, joiner}, by simp⟩)
    · exact Or.inl hpairHeavy
    · right
      nlinarith [hcontainingMass, hyLower]
  have hsemantic := singletonBase_inducedNash_floorExcess_semantics
    reward spectator free (by
      simp [free, finFourLeaveJoinFree, hleaverSpectator.symm,
        hspectatorJoiner]) point hpoint
      (delta := quittingSingletonBaseOwnerFloorExcess reward spectator root)
      le_rfl
  have hleaverSemantic := hsemantic.1 leaver
    (by simp [free, finFourLeaveJoinFree])
  have hjoinerSemantic := hsemantic.1 joiner
    (by simp [free, finFourLeaveJoinFree])
  have hleaverSolved : pair.2 leaver = pair.1 leaver ∧
      quittingPunishmentValue reward leaver ≤ pair.1 leaver := by
    constructor
    · change (quittingTerminalSemanticPair reward profile).2 leaver =
        quittingTerminalPayoff reward profile leaver
      rw [show profile = quittingStationaryProfile reward root by rfl,
        quittingTerminalSemanticPair_stationary_envelope_eq_cap]
      exact hleaverSemantic.1.symm
    · exact hleaverSemantic.2
  have hjoinerSolved : pair.2 joiner = pair.1 joiner ∧
      quittingPunishmentValue reward joiner ≤ pair.1 joiner := by
    constructor
    · change (quittingTerminalSemanticPair reward profile).2 joiner =
        quittingTerminalPayoff reward profile joiner
      rw [show profile = quittingStationaryProfile reward root by rfl,
        quittingTerminalSemanticPair_stationary_envelope_eq_cap]
      exact hjoinerSemantic.1.symm
    · exact hjoinerSemantic.2
  obtain ⟨debtor, deviation, hexploit⟩ :=
    witness.terminalExploitability profile
  have hdeviationCap := quittingTerminalPayoff_update_stationary_le_cap
    reward root debtor deviation
  have hdeviationCap' :
      quittingTerminalPayoff reward
          (Function.update profile debtor deviation) debtor ≤
        quittingStationaryUnilateralCap reward root debtor := by
    exact hdeviationCap
  have hexploit' :
      quittingTerminalPayoff reward (quittingStationaryProfile reward root) debtor +
          witness.terminalGap ≤
        quittingTerminalPayoff reward
          (Function.update (quittingStationaryProfile reward root)
            debtor deviation) debtor := by
    exact hexploit
  have hdebtorGap : witness.terminalGap ≤ pair.2 debtor - pair.1 debtor := by
    change witness.terminalGap ≤
      (quittingTerminalSemanticPair reward profile).2 debtor -
        quittingTerminalPayoff reward profile debtor
    rw [show profile = quittingStationaryProfile reward root by rfl,
      quittingTerminalSemanticPair_stationary_envelope_eq_cap]
    linarith [hexploit', hdeviationCap]
  have hdebtorNeLeaver : debtor ≠ leaver := by
    intro heq
    subst debtor
    rw [hleaverSolved.1] at hdebtorGap
    linarith [witness.terminalGap_pos]
  have hdebtorNeJoiner : debtor ≠ joiner := by
    intro heq
    subst debtor
    rw [hjoinerSolved.1] at hdebtorGap
    linarith [witness.terminalGap_pos]
  have hdebtorMem : debtor ∈ ({spectator, fourth} : Finset (Fin 4)) := by
    rcases hexhaust debtor with h | h | h | h
    · exact (hdebtorNeLeaver h).elim
    · simp [h]
    · exact (hdebtorNeJoiner h).elim
    · simp [h]
  have hpaid : Nonempty (QuittingPaidFirstDisagreementRow reward profile
      debtor witness.terminalGap) := by
    have hcapDebt : witness.terminalGap ≤
        quittingStationaryUnilateralCap reward root debtor -
          quittingTerminalPayoff reward profile debtor := by
      have hgap := hdebtorGap
      change witness.terminalGap ≤
        (quittingTerminalSemanticPair reward profile).2 debtor -
          quittingTerminalPayoff reward profile debtor at hgap
      rw [show profile = quittingStationaryProfile reward root by rfl,
        quittingTerminalSemanticPair_stationary_envelope_eq_cap] at hgap
      exact hgap
    rcases exists_oriented_quitNow_never_gap_of_stationary_cap_debt
        reward root debtor hcapDebt with hquit | hnever
    · obtain ⟨row, -, -⟩ :=
        exists_quittingPaidFirstDisagreementRow_of_pureTimePayoff_sub
          reward profile debtor none (some 0) witness.terminalGap
            witness.terminalGap_pos hquit
      exact ⟨row⟩
    · obtain ⟨row, -, -⟩ :=
        exists_quittingPaidFirstDisagreementRow_of_pureTimePayoff_sub
          reward profile debtor (some 0) none witness.terminalGap
            witness.terminalGap_pos hnever
      exact ⟨row⟩
  let support :=
    finFourLeaveJoinPositiveDebtSupport reward spectator leaver joiner point
  have hsupportSubset : support ⊆ ({spectator, fourth} : Finset (Fin 4)) := by
    intro who hwho
    have hpositive : 0 < pair.2 who - pair.1 who := by
      simpa [support, finFourLeaveJoinPositiveDebtSupport, pair] using hwho
    have hneLeaver : who ≠ leaver := by
      intro heq
      subst who
      rw [hleaverSolved.1] at hpositive
      linarith
    have hneJoiner : who ≠ joiner := by
      intro heq
      subst who
      rw [hjoinerSolved.1] at hpositive
      linarith
    rcases hexhaust who with h | h | h | h
    · exact (hneLeaver h).elim
    · simp [h]
    · exact (hneJoiner h).elim
    · simp [h]
  have hsupportNonempty : support.Nonempty := by
    refine ⟨debtor, ?_⟩
    simp only [support, finFourLeaveJoinPositiveDebtSupport,
      Finset.mem_filter, Finset.mem_univ, true_and]
    exact witness.terminalGap_pos.trans_le hdebtorGap
  have hsupportCard : support.card ≤ 2 := by
    exact (Finset.card_le_card hsupportSubset).trans (by
      rw [Finset.card_pair hspectatorFourth]
    )
  refine ⟨{
    point := point
    point_mem := hpoint
    alpha_pos := halphaPos
    alpha_le_one := halphaLeOne
    joiner_hazard_lower := hyLower
    pair_terminal_mass := hpairTerminal
    triple_terminal_mass := htripleTerminal
    containing_mass_eq_joiner_hazard := hcontainingMass
    heavy_atom := hheavy
    leaver_solved := hleaverSolved
    joiner_solved := hjoinerSolved
    positiveDebtSupport_nonempty := hsupportNonempty
    positiveDebtSupport_subset := hsupportSubset
    positiveDebtSupport_card_le_two := hsupportCard
    debtor := debtor
    debtor_mem := hdebtorMem
    debtor_gap := hdebtorGap
    paid_row := hpaid }⟩

private theorem exists_finFour_fourth_of_three_distinct
    (first second third : Fin 4)
    (hfirstSecond : first ≠ second)
    (hfirstThird : first ≠ third)
    (hsecondThird : second ≠ third) :
    ∃ fourth, fourth ∉ ({first, second, third} : Finset (Fin 4)) := by
  have hcard :
      ({first, second, third} : Finset (Fin 4)).card <
        (Finset.univ : Finset (Fin 4)).card := by
    simp [hfirstSecond, hfirstThird, hsecondThird]
  obtain ⟨fourth, -, hfourth⟩ :=
    Finset.exists_mem_notMem_of_card_lt_card hcard
  exact ⟨fourth, hfourth⟩

namespace FinFourQuantitativeFullSupportHardResidual

/-- The actual rooted-two source either retains its enlarged-pair outsider
join or constructs the stationary two-debtor handoff from its collider-leave
and third-label-join arm. -/
theorem ownerLeaveCollisionChain_outsiderJoin_or_stationaryTwoDebtorHandoff
    {reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4)}
    {bound : ℝ}
    (residual : FinFourQuantitativeFullSupportHardResidual reward bound)
    (M : ℝ)
    (hbound : ∀ terminal who, |reward terminal who| ≤ M)
    (certificate : QuittingImmediateSingletonCollision reward
      residual.witness.terminalGap)
    (chain :
      FinFourRootedTwoNextOwnerLeaveCollisionChain residual certificate) :
    (∃ outsider ∉
        ({chain.spectator, certificate.collider} : Finset (Fin 4)),
      quittingSetReward reward {chain.spectator, certificate.collider}
            outsider + residual.witness.terminalGap ≤
        quittingSetReward reward
          (insert outsider {chain.spectator, certificate.collider}) outsider) ∨
      ∃ joiner fourth,
        joiner ∉
            ({chain.spectator, certificate.collider} : Finset (Fin 4)) ∧
          fourth ∉
            ({certificate.collider, chain.spectator, joiner} :
              Finset (Fin 4)) ∧
          Nonempty (FinFourLeaveJoinStationaryTwoDebtorHandoff reward
            residual.witness M certificate.collider chain.spectator joiner
              fourth) := by
  rcases residual.ownerLeaveCollisionChain_outsiderJoin_or_thirdLabelHandoff
      certificate chain with houtside | hthird
  · exact Or.inl houtside
  · right
    obtain ⟨joiner, hjoiner, hleave, hjoin⟩ := hthird
    have hjoinerNe :
        joiner ≠ chain.spectator ∧ joiner ≠ certificate.collider := by
      simpa only [Finset.mem_insert, Finset.mem_singleton, not_or] using hjoiner
    obtain ⟨fourth, hfourth⟩ := exists_finFour_fourth_of_three_distinct
      certificate.collider chain.spectator joiner
        chain.spectator_ne_collider.symm hjoinerNe.2.symm
          hjoinerNe.1.symm
    have hfourthNe :
        fourth ≠ certificate.collider ∧
          fourth ≠ chain.spectator ∧ fourth ≠ joiner := by
      simpa only [Finset.mem_insert, Finset.mem_singleton, not_or] using hfourth
    have hleave' := hleave
    rw [Finset.pair_comm chain.spectator certificate.collider] at hleave'
    refine ⟨joiner, fourth, hjoiner, hfourth, ?_⟩
    exact nonempty_finFourLeaveJoinStationaryTwoDebtorHandoff
      residual.witness M hbound certificate.collider chain.spectator
        joiner fourth chain.spectator_ne_collider.symm hjoinerNe.2.symm
          hfourthNe.1.symm hjoinerNe.1.symm hfourthNe.2.1.symm
            hfourthNe.2.2.symm hleave' hjoin

end FinFourQuantitativeFullSupportHardResidual

end GameTheory
