/-
Copyright (c) 2026 UniformEquilibrium contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: UniformEquilibrium contributors
-/

import UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticFinFourSoloWallDispatch

/-!
# Pair-base stationary two-debtor handoff on four players

Force two prescribed players to Quit and select an exact Nash point of the
induced binary game played by the other two players.  A full-gap join from
the base forces a quantitative probability that at least one free player
also Quits.  One of the three resulting strict-superset atoms is therefore
heavy.  The two free coordinates are solved against unrestricted behavioral
deviations, so terminal exploitability is localized to the two base players
and yields a source-matched paid first-disagreement row.

The Nash point is selected afresh from the reward table.  No chronological
connection to a preceding terminal-semantic carrier is asserted.
-/

noncomputable section

namespace GameTheory

open Math.Probability Math.PMFProduct
open QuittingSureSetOwnerRepair

/-- The two free labels opposite a prescribed pair base. -/
def finFourPairBaseFree (joiner fourth : Fin 4) : Finset (Fin 4) :=
  {joiner, fourth}

/-- The ambient product root selected from the pair-base binary game. -/
def finFourPairBaseRoot
    (baseFirst baseSecond joiner fourth : Fin 4)
    (point : mixedPolytope
      (quittingBinaryForm (finFourPairBaseFree joiner fourth)).sig) :
    Fin 4 → PMF Bool :=
  quittingPersistentBaseRoot {baseFirst, baseSecond}
    (finFourPairBaseFree joiner fourth) point

/-- The stationary profile generated by the selected pair-base root. -/
def finFourPairBaseProfile
    (reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4))
    (baseFirst baseSecond joiner fourth : Fin 4)
    (point : mixedPolytope
      (quittingBinaryForm (finFourPairBaseFree joiner fourth)).sig) :
    (quittingGame reward).BehaviorProfile :=
  quittingStationaryProfile reward
    (finFourPairBaseRoot baseFirst baseSecond joiner fourth point)

/-- The prescribed/envelope semantic pair of the pair-base stationary source. -/
def finFourPairBaseSemanticPair
    (reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4))
    (baseFirst baseSecond joiner fourth : Fin 4)
    (point : mixedPolytope
      (quittingBinaryForm (finFourPairBaseFree joiner fourth)).sig) :
    QuittingTerminalSemanticPair (Fin 4) :=
  quittingTerminalSemanticPair reward
    (finFourPairBaseProfile reward baseFirst baseSecond joiner fourth point)

/-- Probability that at least one of the two free players Quits. -/
def finFourPairBaseFreeAbsorptionMass
    (baseFirst baseSecond joiner fourth : Fin 4)
    (point : mixedPolytope
      (quittingBinaryForm (finFourPairBaseFree joiner fourth)).sig) : ℝ :=
  let root := finFourPairBaseRoot baseFirst baseSecond joiner fourth point
  let x := (root joiner true).toReal
  let y := (root fourth true).toReal
  x + y - x * y

/-- Players with positive unrestricted behavioral debt at the source. -/
def finFourPairBasePositiveDebtSupport
    (reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4))
    (baseFirst baseSecond joiner fourth : Fin 4)
    (point : mixedPolytope
      (quittingBinaryForm (finFourPairBaseFree joiner fourth)).sig) :
    Finset (Fin 4) :=
  Finset.univ.filter fun who =>
    0 < (finFourPairBaseSemanticPair reward baseFirst baseSecond joiner fourth
          point).2 who -
      (finFourPairBaseSemanticPair reward baseFirst baseSecond joiner fourth
          point).1 who

/-- Data retained by the pair-base stationary handoff. -/
structure FinFourPairBaseStationaryTwoDebtorHandoff
    (reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4))
    (witness : QuittingTerminalExploitabilityWitness reward)
    (M : ℝ) (baseFirst baseSecond joiner fourth : Fin 4) where
  point : mixedPolytope
    (quittingBinaryForm (finFourPairBaseFree joiner fourth)).sig
  point_mem : point ∈ quittingPersistentBaseNashSet reward
    {baseFirst, baseSecond} (finFourPairBaseFree joiner fourth)
  alpha_pos : 0 < witness.terminalGap / (witness.terminalGap + 2 * M)
  alpha_le_one : witness.terminalGap / (witness.terminalGap + 2 * M) ≤ 1
  free_absorption_lower :
    witness.terminalGap / (witness.terminalGap + 2 * M) ≤
      finFourPairBaseFreeAbsorptionMass baseFirst baseSecond joiner fourth point
  strict_superset_mass_sum :
    quittingTerminalOutcomeMass reward
          (finFourPairBaseProfile reward baseFirst baseSecond joiner fourth point)
          (some ⟨{baseFirst, baseSecond, joiner}, by simp⟩) +
        quittingTerminalOutcomeMass reward
          (finFourPairBaseProfile reward baseFirst baseSecond joiner fourth point)
          (some ⟨{baseFirst, baseSecond, fourth}, by simp⟩) +
        quittingTerminalOutcomeMass reward
          (finFourPairBaseProfile reward baseFirst baseSecond joiner fourth point)
          (some ⟨{baseFirst, baseSecond, joiner, fourth}, by simp⟩) =
      finFourPairBaseFreeAbsorptionMass baseFirst baseSecond joiner fourth point
  atom : Finset (Fin 4)
  atom_nonempty : atom.Nonempty
  base_ssubset_atom : ({baseFirst, baseSecond} : Finset (Fin 4)) ⊂ atom
  atom_mass_lower :
    witness.terminalGap / (3 * (witness.terminalGap + 2 * M)) ≤
      quittingTerminalOutcomeMass reward
        (finFourPairBaseProfile reward baseFirst baseSecond joiner fourth point)
        (some ⟨atom, atom_nonempty⟩)
  atom_toggle :
    (∃ member ∈ atom,
      quittingSetReward reward atom member + witness.terminalGap ≤
        quittingSetReward reward (atom.erase member) member) ∨
      ∃ outsider ∉ atom,
        quittingSetReward reward atom outsider + witness.terminalGap ≤
          quittingSetReward reward (insert outsider atom) outsider
  joiner_solved :
    let pair := finFourPairBaseSemanticPair reward baseFirst baseSecond joiner
      fourth point
    pair.2 joiner = pair.1 joiner ∧
      quittingPunishmentValue reward joiner ≤ pair.1 joiner
  fourth_solved :
    let pair := finFourPairBaseSemanticPair reward baseFirst baseSecond joiner
      fourth point
    pair.2 fourth = pair.1 fourth ∧
      quittingPunishmentValue reward fourth ≤ pair.1 fourth
  positiveDebtSupport_nonempty :
    (finFourPairBasePositiveDebtSupport reward baseFirst baseSecond joiner fourth
      point).Nonempty
  positiveDebtSupport_subset :
    finFourPairBasePositiveDebtSupport reward baseFirst baseSecond joiner fourth
        point ⊆ {baseFirst, baseSecond}
  positiveDebtSupport_card_le_two :
    (finFourPairBasePositiveDebtSupport reward baseFirst baseSecond joiner fourth
      point).card ≤ 2
  debtor : Fin 4
  debtor_mem : debtor ∈ ({baseFirst, baseSecond} : Finset (Fin 4))
  debtor_gap :
    witness.terminalGap ≤
      (finFourPairBaseSemanticPair reward baseFirst baseSecond joiner fourth
          point).2 debtor -
        (finFourPairBaseSemanticPair reward baseFirst baseSecond joiner fourth
          point).1 debtor
  paid_row : Nonempty (QuittingPaidFirstDisagreementRow reward
    (finFourPairBaseProfile reward baseFirst baseSecond joiner fourth point)
      debtor witness.terminalGap)

private theorem pairBase_quittingRootEndpointDifference_zero_pureSetRoot
    (reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4))
    (coalition : Finset (Fin 4)) (who : Fin 4)
    (herase : (coalition.erase who).Nonempty) :
    quittingRootEndpointDifference reward 0
        (quittingPureSetRoot coalition) who =
      quittingSetReward reward (insert who coalition) who -
        quittingSetReward reward (coalition.erase who) who := by
  rw [quittingRootEndpointDifference,
    quittingRootQuitPayoff_pureSetRoot_eq_insert,
    quittingRootContinuePayoff_pureSetRoot_eq_erase_of_nonempty
      (0 : Payoff (Fin 4)) coalition who herase]

/-- A full-gap outsider join to a two-player base constructs an actual
stationary source with quantitative free absorption, a heavy strict-superset
atom, two solved free coordinates, base-supported debt, and a paid row. -/
theorem nonempty_finFourPairBaseStationaryTwoDebtorHandoff
    {reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4)}
    (witness : QuittingTerminalExploitabilityWitness reward)
    (M : ℝ) (hM : 0 ≤ M)
    (hbound : ∀ terminal who, |reward terminal who| ≤ M)
    (baseFirst baseSecond joiner fourth : Fin 4)
    (hbase : baseFirst ≠ baseSecond)
    (hfirstJoiner : baseFirst ≠ joiner)
    (hfirstFourth : baseFirst ≠ fourth)
    (hsecondJoiner : baseSecond ≠ joiner)
    (hsecondFourth : baseSecond ≠ fourth)
    (hjoinerFourth : joiner ≠ fourth)
    (hjoin : quittingSetReward reward {baseFirst, baseSecond} joiner +
        witness.terminalGap ≤
      quittingSetReward reward {baseFirst, baseSecond, joiner} joiner) :
    Nonempty (FinFourPairBaseStationaryTwoDebtorHandoff reward witness M
      baseFirst baseSecond joiner fourth) := by
  let base : Finset (Fin 4) := {baseFirst, baseSecond}
  let free := finFourPairBaseFree joiner fourth
  have hbaseNonempty : base.Nonempty := by simp [base]
  have hdisjoint : Disjoint base free := by
    simp [base, free, finFourPairBaseFree, hfirstJoiner.symm,
      hfirstFourth.symm, hsecondJoiner.symm, hsecondFourth.symm]
  obtain ⟨point, hpoint⟩ :=
    quittingPersistentBaseNashSet_nonempty reward base free
  let root := finFourPairBaseRoot baseFirst baseSecond joiner fourth point
  let profile :=
    finFourPairBaseProfile reward baseFirst baseSecond joiner fourth point
  let pair :=
    finFourPairBaseSemanticPair reward baseFirst baseSecond joiner fourth point
  let x := (root joiner true).toReal
  let y := (root fourth true).toReal
  have hjoinerFirst : joiner ≠ baseFirst := hfirstJoiner.symm
  have hfourthFirst : fourth ≠ baseFirst := hfirstFourth.symm
  have hjoinerSecond : joiner ≠ baseSecond := hsecondJoiner.symm
  have hfourthSecond : fourth ≠ baseSecond := hsecondFourth.symm
  have hfourthJoiner : fourth ≠ joiner := hjoinerFourth.symm
  have hrootFirst : root baseFirst = PMF.pure true := by
    exact quittingPersistentBaseRoot_apply_of_mem_base base free point (by
      simp [base])
  have hrootSecond : root baseSecond = PMF.pure true := by
    exact quittingPersistentBaseRoot_apply_of_mem_base base free point (by
      simp [base])
  have hbaseFreeUnion : base ∪ free = Finset.univ := by
    apply Finset.eq_univ_of_card
    rw [Finset.card_union_of_disjoint hdisjoint]
    simp [base, free, finFourPairBaseFree, hbase, hjoinerFourth]
  have hexhaust : ∀ who : Fin 4,
      who = baseFirst ∨ who = baseSecond ∨ who = joiner ∨ who = fourth := by
    intro who
    have hmem : who ∈ base ∪ free := by rw [hbaseFreeUnion]; simp
    rcases Finset.mem_union.mp hmem with hmem | hmem
    · have hcases : who = baseFirst ∨ who = baseSecond := by
        simpa only [base, Finset.mem_insert, Finset.mem_singleton] using hmem
      exact hcases.elim Or.inl (fun h ↦ Or.inr (Or.inl h))
    · have hcases : who = joiner ∨ who = fourth := by
        simpa only [free, finFourPairBaseFree, Finset.mem_insert,
          Finset.mem_singleton] using hmem
      exact hcases.elim (fun h ↦ Or.inr (Or.inr (Or.inl h)))
        (fun h ↦ Or.inr (Or.inr (Or.inr h)))
  have hrootBase :
      Function.update
          (Function.update root fourth (PMF.pure false))
          joiner (PMF.pure false) =
        quittingPureSetRoot base := by
    funext who
    rcases hexhaust who with h | h | h | h <;> subst who <;>
      simp_all [base, root, finFourPairBaseRoot, quittingPureSetRoot,
        quittingSetAction]
  have hrootJoiner :
      Function.update
          (Function.update root fourth (PMF.pure false))
          joiner (PMF.pure true) =
        quittingPureSetRoot {baseFirst, baseSecond, joiner} := by
    funext who
    rcases hexhaust who with h | h | h | h <;> subst who <;>
      simp_all [root, finFourPairBaseRoot, quittingPureSetRoot,
        quittingSetAction]
  have hrootFourth :
      Function.update
          (Function.update root fourth (PMF.pure true))
          joiner (PMF.pure false) =
        quittingPureSetRoot {baseFirst, baseSecond, fourth} := by
    funext who
    rcases hexhaust who with h | h | h | h <;> subst who <;>
      simp_all [root, finFourPairBaseRoot, quittingPureSetRoot,
        quittingSetAction]
  have hrootGrand :
      Function.update
          (Function.update root fourth (PMF.pure true))
          joiner (PMF.pure true) =
        quittingPureSetRoot
          {baseFirst, baseSecond, joiner, fourth} := by
    funext who
    rcases hexhaust who with h | h | h | h <;> subst who <;>
      simp_all [root, finFourPairBaseRoot, quittingPureSetRoot,
        quittingSetAction]
  let alpha : Bool → ℝ := fun action =>
    quittingRootEndpointDifference reward 0
      (Function.update root fourth (PMF.pure action)) joiner
  let beta : Bool → ℝ := fun action =>
    quittingRootEndpointDifference reward 0
      (Function.update root joiner (PMF.pure action)) fourth
  have hjoinerNotMemBase : joiner ∉ base := by
    simp [base, hjoinerFirst, hjoinerSecond]
  have hfourthNotMemBase : fourth ∉ base := by
    simp [base, hfourthFirst, hfourthSecond]
  have hjoinerInsertBase : insert joiner base =
      ({baseFirst, baseSecond, joiner} : Finset (Fin 4)) := by
    ext who
    simp only [base, Finset.mem_insert, Finset.mem_singleton]
    aesop
  have hfourthInsertBase : insert fourth base =
      ({baseFirst, baseSecond, fourth} : Finset (Fin 4)) := by
    ext who
    simp only [base, Finset.mem_insert, Finset.mem_singleton]
    aesop
  have halphaFalse : alpha false =
      quittingSetReward reward {baseFirst, baseSecond, joiner} joiner -
        quittingSetReward reward {baseFirst, baseSecond} joiner := by
    dsimp only [alpha]
    rw [← quittingRootEndpointDifference_update_self reward 0
      (Function.update root fourth (PMF.pure false)) joiner (PMF.pure false),
      hrootBase,
      pairBase_quittingRootEndpointDifference_zero_pureSetRoot]
    · rw [Finset.erase_eq_of_notMem hjoinerNotMemBase,
        hjoinerInsertBase]
    · rw [Finset.erase_eq_of_notMem hjoinerNotMemBase]
      exact hbaseNonempty
  have hjoinerEraseGrand :
      ({baseFirst, baseSecond, joiner, fourth} : Finset (Fin 4)).erase joiner =
        {baseFirst, baseSecond, fourth} := by
    ext who
    simp only [Finset.mem_erase, Finset.mem_insert, Finset.mem_singleton]
    constructor
    · rintro ⟨hne, h | h | h | h⟩
      · exact Or.inl h
      · exact Or.inr (Or.inl h)
      · exact (hne h).elim
      · exact Or.inr (Or.inr h)
    · rintro (h | h | h)
      · subst who
        exact ⟨hfirstJoiner, Or.inl rfl⟩
      · subst who
        exact ⟨hsecondJoiner, Or.inr (Or.inl rfl)⟩
      · subst who
        exact ⟨hfourthJoiner, Or.inr (Or.inr (Or.inr rfl))⟩
  have halphaTrue : alpha true =
      quittingSetReward reward {baseFirst, baseSecond, joiner, fourth} joiner -
        quittingSetReward reward {baseFirst, baseSecond, fourth} joiner := by
    dsimp only [alpha]
    rw [← quittingRootEndpointDifference_update_self reward 0
      (Function.update root fourth (PMF.pure true)) joiner (PMF.pure true),
      hrootGrand,
      pairBase_quittingRootEndpointDifference_zero_pureSetRoot]
    · rw [Finset.insert_eq_self.mpr (by simp), hjoinerEraseGrand]
    · rw [hjoinerEraseGrand]
      simp
  have hnash := isBinaryDifferenceNash_of_mem_quittingPersistentBaseNashSet_pair
    reward base free hbaseNonempty hdisjoint point hpoint
      (first := joiner) (second := fourth)
      (by simp [free, finFourPairBaseFree])
      (by simp [free, finFourPairBaseFree]) hjoinerFourth
  change IsBinaryDifferenceNash alpha beta x y at hnash
  rcases hnash with ⟨hx, hy, hcContinue, -, -, -⟩
  have halphaFalseLower : witness.terminalGap ≤ alpha false := by
    rw [halphaFalse]
    linarith
  have hgrandLower : -M ≤
      quittingSetReward reward {baseFirst, baseSecond, joiner, fourth} joiner := by
    have h := (abs_le.mp
      (hbound ⟨{baseFirst, baseSecond, joiner, fourth}, by simp⟩ joiner)).1
    simpa [quittingSetReward] using h
  have hotherTripleUpper :
      quittingSetReward reward {baseFirst, baseSecond, fourth} joiner ≤ M := by
    have h := (abs_le.mp
      (hbound ⟨{baseFirst, baseSecond, fourth}, by simp⟩ joiner)).2
    simpa [quittingSetReward] using h
  have halphaTrueLower : -2 * M ≤ alpha true := by
    rw [halphaTrue]
    linarith
  have hbaseLower : -M ≤
      quittingSetReward reward {baseFirst, baseSecond} joiner := by
    have h := (abs_le.mp
      (hbound ⟨{baseFirst, baseSecond}, by simp⟩ joiner)).1
    simpa [quittingSetReward] using h
  have hjoinTripleUpper :
      quittingSetReward reward {baseFirst, baseSecond, joiner} joiner ≤ M := by
    have h := (abs_le.mp
      (hbound ⟨{baseFirst, baseSecond, joiner}, by simp⟩ joiner)).2
    simpa [quittingSetReward] using h
  have hgapLe : witness.terminalGap ≤ 2 * M := by
    linarith
  have hdenom : 0 < witness.terminalGap + 2 * M := by
    exact add_pos_of_pos_of_nonneg witness.terminalGap_pos
      (mul_nonneg (by norm_num) hM)
  have halphaPos :
      0 < witness.terminalGap / (witness.terminalGap + 2 * M) :=
    div_pos witness.terminalGap_pos hdenom
  have halphaLeOne :
      witness.terminalGap / (witness.terminalGap + 2 * M) ≤ 1 := by
    apply (div_le_one hdenom).2
    linarith
  have habsorptionLower :
      witness.terminalGap / (witness.terminalGap + 2 * M) ≤
        x + y - x * y := by
    by_cases hxOne : x = 1
    · rw [hxOne]
      norm_num
      exact halphaLeOne
    · have hxLt : x < 1 := lt_of_le_of_ne hx.2 hxOne
      have hfirstNonpos : binaryFirstDifference alpha y ≤ 0 := by
        have hpositive : 0 < 1 - x := sub_pos.mpr hxLt
        nlinarith
      have hweighted :
          (1 - y) * witness.terminalGap + y * (-2 * M) ≤ 0 := by
        dsimp only [binaryFirstDifference] at hfirstNonpos
        nlinarith [hy.1, hy.2]
      have hyLower :
          witness.terminalGap / (witness.terminalGap + 2 * M) ≤ y := by
        apply (div_le_iff₀ hdenom).2
        nlinarith
      have hxy : 0 ≤ x * (1 - y) :=
        mul_nonneg hx.1 (sub_nonneg.mpr hy.2)
      nlinarith
  change witness.terminalGap / (witness.terminalGap + 2 * M) ≤
      finFourPairBaseFreeAbsorptionMass baseFirst baseSecond joiner fourth point
      at habsorptionLower
  have hcontinueMass : quittingStationaryContinueMass root = 0 :=
    quittingStationaryContinueMass_eq_zero_of_owner_eq_pure hrootFirst
  have hterminalMass (terminal : {S : Finset (Fin 4) // S.Nonempty}) :
      quittingTerminalOutcomeMass reward profile (some terminal) =
        quittingRootCoalitionMass root terminal.val := by
    change quittingAbsorbedMassLimit reward profile terminal = _
    have hprefix := quittingAbsorbedMassLimit_rootThenContinuation
      reward root profile terminal
    have hsplice : quittingRootThenContinuationProfile reward root profile =
        profile := by
      change quittingRootThenContinuationProfile reward root
          (quittingStationaryProfile reward root) =
        quittingStationaryProfile reward root
      exact quittingRootThenContinuationProfile_stationary reward root
    rw [hsplice, hcontinueMass, zero_mul, add_zero] at hprefix
    exact hprefix
  have htripleJoinerComplement :
      ({baseFirst, baseSecond, joiner} : Finset (Fin 4))ᶜ = {fourth} := by
    ext who
    rcases hexhaust who with h | h | h | h <;> subst who <;>
      simp [hbase, hbase.symm, hfirstJoiner, hfirstJoiner.symm,
        hfirstFourth, hfirstFourth.symm, hsecondJoiner,
        hsecondJoiner.symm, hsecondFourth, hsecondFourth.symm,
        hjoinerFourth, hjoinerFourth.symm]
  have htripleFourthComplement :
      ({baseFirst, baseSecond, fourth} : Finset (Fin 4))ᶜ = {joiner} := by
    ext who
    rcases hexhaust who with h | h | h | h <;> subst who <;>
      simp [hbase, hbase.symm, hfirstJoiner, hfirstJoiner.symm,
        hfirstFourth, hfirstFourth.symm, hsecondJoiner,
        hsecondJoiner.symm, hsecondFourth, hsecondFourth.symm,
        hjoinerFourth, hjoinerFourth.symm]
  have hgrandComplement :
      ({baseFirst, baseSecond, joiner, fourth} : Finset (Fin 4))ᶜ = ∅ := by
    rw [show ({baseFirst, baseSecond, joiner, fourth} : Finset (Fin 4)) =
        Finset.univ by
      apply Finset.eq_univ_of_card
      simp [hbase, hfirstJoiner, hfirstFourth, hsecondJoiner,
        hsecondFourth, hjoinerFourth]]
    simp
  have hjoinerRootMass :
      quittingRootCoalitionMass root {baseFirst, baseSecond, joiner} =
        x * (1 - y) := by
    unfold quittingRootCoalitionMass quittingRootQuitRates coalitionMass
    rw [htripleJoinerComplement]
    simp [x, y, hrootFirst, hrootSecond, hbase, hfirstJoiner,
      hsecondJoiner]
  have hfourthRootMass :
      quittingRootCoalitionMass root {baseFirst, baseSecond, fourth} =
        (1 - x) * y := by
    unfold quittingRootCoalitionMass quittingRootQuitRates coalitionMass
    rw [htripleFourthComplement]
    simp [x, y, hrootFirst, hrootSecond, hbase, hfirstFourth,
      hsecondFourth]
    ring
  have hgrandRootMass :
      quittingRootCoalitionMass root
          {baseFirst, baseSecond, joiner, fourth} = x * y := by
    unfold quittingRootCoalitionMass quittingRootQuitRates coalitionMass
    rw [hgrandComplement]
    simp [x, y, hrootFirst, hrootSecond, hbase, hfirstJoiner,
      hfirstFourth, hsecondJoiner, hsecondFourth, hjoinerFourth]
  have hjoinerTerminal :
      quittingTerminalOutcomeMass reward profile
          (some ⟨{baseFirst, baseSecond, joiner}, by simp⟩) =
        x * (1 - y) := by
    rw [hterminalMass]
    exact hjoinerRootMass
  have hfourthTerminal :
      quittingTerminalOutcomeMass reward profile
          (some ⟨{baseFirst, baseSecond, fourth}, by simp⟩) =
        (1 - x) * y := by
    rw [hterminalMass]
    exact hfourthRootMass
  have hgrandTerminal :
      quittingTerminalOutcomeMass reward profile
          (some ⟨{baseFirst, baseSecond, joiner, fourth}, by simp⟩) =
        x * y := by
    rw [hterminalMass]
    exact hgrandRootMass
  have hmassSum :
      quittingTerminalOutcomeMass reward profile
            (some ⟨{baseFirst, baseSecond, joiner}, by simp⟩) +
          quittingTerminalOutcomeMass reward profile
            (some ⟨{baseFirst, baseSecond, fourth}, by simp⟩) +
          quittingTerminalOutcomeMass reward profile
            (some ⟨{baseFirst, baseSecond, joiner, fourth}, by simp⟩) =
        finFourPairBaseFreeAbsorptionMass baseFirst baseSecond joiner fourth
          point := by
    rw [hjoinerTerminal, hfourthTerminal, hgrandTerminal]
    change x * (1 - y) + (1 - x) * y + x * y = x + y - x * y
    ring
  have hthird :
      witness.terminalGap / (3 * (witness.terminalGap + 2 * M)) =
        (witness.terminalGap / (witness.terminalGap + 2 * M)) / 3 := by
    field_simp
  let lower := witness.terminalGap /
    (3 * (witness.terminalGap + 2 * M))
  have hheavy :
      lower ≤ quittingTerminalOutcomeMass reward profile
          (some ⟨{baseFirst, baseSecond, joiner}, by simp⟩) ∨
        lower ≤ quittingTerminalOutcomeMass reward profile
          (some ⟨{baseFirst, baseSecond, fourth}, by simp⟩) ∨
        lower ≤ quittingTerminalOutcomeMass reward profile
          (some ⟨{baseFirst, baseSecond, joiner, fourth}, by simp⟩) := by
    have hlower : lower =
        (witness.terminalGap / (witness.terminalGap + 2 * M)) / 3 := by
      exact hthird
    rw [hlower]
    by_cases hfirst :
        (witness.terminalGap / (witness.terminalGap + 2 * M)) / 3 ≤
          quittingTerminalOutcomeMass reward profile
            (some ⟨{baseFirst, baseSecond, joiner}, by simp⟩)
    · exact Or.inl hfirst
    · right
      by_cases hsecond :
          (witness.terminalGap / (witness.terminalGap + 2 * M)) / 3 ≤
            quittingTerminalOutcomeMass reward profile
              (some ⟨{baseFirst, baseSecond, fourth}, by simp⟩)
      · exact Or.inl hsecond
      · right
        nlinarith [hmassSum, habsorptionLower]
  obtain ⟨atom, hatomNonempty, hbaseStrict, hatomMass⟩ :
      ∃ (atom : Finset (Fin 4)) (hatom : atom.Nonempty),
        ({baseFirst, baseSecond} : Finset (Fin 4)) ⊂ atom ∧
          lower ≤ quittingTerminalOutcomeMass reward profile
            (some ⟨atom, hatom⟩) := by
    rcases hheavy with hheavy | hheavy | hheavy
    · refine ⟨{baseFirst, baseSecond, joiner}, by simp, ?_, hheavy⟩
      rw [← hjoinerInsertBase]
      exact Finset.ssubset_insert hjoinerNotMemBase
    · refine ⟨{baseFirst, baseSecond, fourth}, by simp, ?_, hheavy⟩
      rw [← hfourthInsertBase]
      exact Finset.ssubset_insert hfourthNotMemBase
    · refine ⟨{baseFirst, baseSecond, joiner, fourth}, by simp, ?_,
          hheavy⟩
      apply lt_of_lt_of_le (Finset.ssubset_insert hjoinerNotMemBase)
      rw [hjoinerInsertBase]
      simp
  have hatomToggle := witness.exists_leave_or_join_gain atom
  have hsemantics := persistentBase_inducedNash_free_semantics
    base free hbaseNonempty hdisjoint point hpoint
  have hjoinerSemantic := hsemantics joiner
    (by simp [free, finFourPairBaseFree])
  have hfourthSemantic := hsemantics fourth
    (by simp [free, finFourPairBaseFree])
  have hjoinerSolved : pair.2 joiner = pair.1 joiner ∧
      quittingPunishmentValue reward joiner ≤ pair.1 joiner := by
    constructor
    · change (quittingTerminalSemanticPair reward profile).2 joiner =
        quittingTerminalPayoff reward profile joiner
      rw [show profile = quittingStationaryProfile reward root by rfl,
        quittingTerminalSemanticPair_stationary_envelope_eq_cap]
      exact hjoinerSemantic.1.symm
    · exact hjoinerSemantic.2
  have hfourthSolved : pair.2 fourth = pair.1 fourth ∧
      quittingPunishmentValue reward fourth ≤ pair.1 fourth := by
    constructor
    · change (quittingTerminalSemanticPair reward profile).2 fourth =
        quittingTerminalPayoff reward profile fourth
      rw [show profile = quittingStationaryProfile reward root by rfl,
        quittingTerminalSemanticPair_stationary_envelope_eq_cap]
      exact hfourthSemantic.1.symm
    · exact hfourthSemantic.2
  obtain ⟨debtor, deviation, hexploit⟩ :=
    witness.terminalExploitability profile
  have hdeviationCap := quittingTerminalPayoff_update_stationary_le_cap
    reward root debtor deviation
  have hdeviationCap' :
      quittingTerminalPayoff reward
          (Function.update (quittingStationaryProfile reward root)
            debtor deviation) debtor ≤
        quittingStationaryUnilateralCap reward root debtor := by
    exact hdeviationCap
  have hexploit' :
      quittingTerminalPayoff reward
          (quittingStationaryProfile reward root) debtor +
          witness.terminalGap ≤
        quittingTerminalPayoff reward
          (Function.update (quittingStationaryProfile reward root)
            debtor deviation) debtor := by
    exact hexploit
  have hdebtorGap : witness.terminalGap ≤ pair.2 debtor - pair.1 debtor := by
    change witness.terminalGap ≤
      (quittingTerminalSemanticPair reward profile).2 debtor -
        quittingTerminalPayoff reward profile debtor
    rw [show profile = quittingStationaryProfile reward root by rfl,
      quittingTerminalSemanticPair_stationary_envelope_eq_cap]
    linarith [hexploit', hdeviationCap']
  have hdebtorNeJoiner : debtor ≠ joiner := by
    intro heq
    subst debtor
    rw [hjoinerSolved.1] at hdebtorGap
    linarith [witness.terminalGap_pos]
  have hdebtorNeFourth : debtor ≠ fourth := by
    intro heq
    subst debtor
    rw [hfourthSolved.1] at hdebtorGap
    linarith [witness.terminalGap_pos]
  have hdebtorMem : debtor ∈ ({baseFirst, baseSecond} : Finset (Fin 4)) := by
    rcases hexhaust debtor with h | h | h | h
    · simp [h]
    · simp [h]
    · exact (hdebtorNeJoiner h).elim
    · exact (hdebtorNeFourth h).elim
  have hpaid : Nonempty (QuittingPaidFirstDisagreementRow reward profile
      debtor witness.terminalGap) := by
    have hcapDebt : witness.terminalGap ≤
        quittingStationaryUnilateralCap reward root debtor -
          quittingTerminalPayoff reward profile debtor := by
      have hgap := hdebtorGap
      change witness.terminalGap ≤
        (quittingTerminalSemanticPair reward profile).2 debtor -
          quittingTerminalPayoff reward profile debtor at hgap
      rw [show profile = quittingStationaryProfile reward root by rfl,
        quittingTerminalSemanticPair_stationary_envelope_eq_cap] at hgap
      exact hgap
    rcases exists_oriented_quitNow_never_gap_of_stationary_cap_debt
        reward root debtor hcapDebt with hquit | hnever
    · obtain ⟨row, -, -⟩ :=
        exists_quittingPaidFirstDisagreementRow_of_pureTimePayoff_sub
          reward profile debtor none (some 0) witness.terminalGap
            witness.terminalGap_pos hquit
      exact ⟨row⟩
    · obtain ⟨row, -, -⟩ :=
        exists_quittingPaidFirstDisagreementRow_of_pureTimePayoff_sub
          reward profile debtor (some 0) none witness.terminalGap
            witness.terminalGap_pos hnever
      exact ⟨row⟩
  let support := finFourPairBasePositiveDebtSupport reward baseFirst baseSecond
    joiner fourth point
  have hsupportSubset :
      support ⊆ ({baseFirst, baseSecond} : Finset (Fin 4)) := by
    intro who hwho
    have hpositive : 0 < pair.2 who - pair.1 who := by
      simpa [support, finFourPairBasePositiveDebtSupport, pair] using hwho
    have hneJoiner : who ≠ joiner := by
      intro heq
      subst who
      rw [hjoinerSolved.1] at hpositive
      linarith
    have hneFourth : who ≠ fourth := by
      intro heq
      subst who
      rw [hfourthSolved.1] at hpositive
      linarith
    rcases hexhaust who with h | h | h | h
    · simp [h]
    · simp [h]
    · exact (hneJoiner h).elim
    · exact (hneFourth h).elim
  have hsupportNonempty : support.Nonempty := by
    refine ⟨debtor, ?_⟩
    simp only [support, finFourPairBasePositiveDebtSupport,
      Finset.mem_filter, Finset.mem_univ, true_and]
    exact witness.terminalGap_pos.trans_le hdebtorGap
  have hsupportCard : support.card ≤ 2 := by
    exact (Finset.card_le_card hsupportSubset).trans (by
      rw [Finset.card_pair hbase])
  refine ⟨{
    point := point
    point_mem := by simpa [base, free] using hpoint
    alpha_pos := halphaPos
    alpha_le_one := halphaLeOne
    free_absorption_lower := habsorptionLower
    strict_superset_mass_sum := by simpa [profile] using hmassSum
    atom := atom
    atom_nonempty := hatomNonempty
    base_ssubset_atom := hbaseStrict
    atom_mass_lower := by simpa [lower, profile] using hatomMass
    atom_toggle := hatomToggle
    joiner_solved := hjoinerSolved
    fourth_solved := hfourthSolved
    positiveDebtSupport_nonempty := hsupportNonempty
    positiveDebtSupport_subset := hsupportSubset
    positiveDebtSupport_card_le_two := hsupportCard
    debtor := debtor
    debtor_mem := hdebtorMem
    debtor_gap := hdebtorGap
    paid_row := hpaid }⟩

end GameTheory
