/-
Copyright (c) 2026 UniformEquilibrium contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: UniformEquilibrium contributors
-/

import MathUE.Finset.PowersetBernoulliWeight
import UniformEquilibrium.Diagnostics.Quitting.Collision.SingletonPacket.PairBasePaidResetAlignment
import UniformEquilibrium.Diagnostics.Quitting.Collision.SingletonPacket.PunishmentNormalAtomicCollisionHandoff
import UniformEquilibrium.Quitting.Root.TerminalSemanticEqualityStratum

/-!
# Singleton-base same-law reset producer on four players

For every prescribed singleton owner in an actual quantitative `Fin 4` hard
residual, punishment normality supplies a distinct full-gap collider.  An exact
mixed Nash point on the complementary three-player face gives one literal
stationary profile on which all free coordinates are solved against arbitrary
behavioral deviations.  The terminal gap is therefore localized to the sure
singleton owner.

The collider gap also forces a quantitative probability of absorption outside
the singleton base.  One of the seven strict supersets is consequently heavy.
The same literal profile and complete terminal law carry the paid row, the
zero-debt collider, unit owner incidence, and the existing fixed-law reset
dispatch.  The dispatch may still stop at its all-Continue cap face.
-/

noncomputable section

namespace GameTheory

open Finset Set
open Math.Probability Math.PMFProduct
open QuittingSureSetOwnerRepair

/-- The three labels complementary to a prescribed singleton owner. -/
def finFourSingletonBaseFree (owner : Fin 4) : Finset (Fin 4) :=
  Finset.univ.erase owner

/-- The persistent singleton-base root selected from the induced Nash set. -/
def finFourSingletonBaseRoot
    (owner : Fin 4)
    (point : mixedPolytope
      (quittingBinaryForm (finFourSingletonBaseFree owner)).sig) :
    Fin 4 → PMF Bool :=
  quittingPersistentBaseRoot {owner} (finFourSingletonBaseFree owner) point

/-- The literal stationary profile generated by a singleton-base root. -/
def finFourSingletonBaseProfile
    (reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4))
    (owner : Fin 4)
    (point : mixedPolytope
      (quittingBinaryForm (finFourSingletonBaseFree owner)).sig) :
    (quittingGame reward).BehaviorProfile :=
  quittingStationaryProfile reward (finFourSingletonBaseRoot owner point)

/-- The actual semantic pair of a singleton-base stationary profile. -/
def finFourSingletonBaseSemanticPair
    (reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4))
    (owner : Fin 4)
    (point : mixedPolytope
      (quittingBinaryForm (finFourSingletonBaseFree owner)).sig) :
    QuittingTerminalSemanticPair (Fin 4) :=
  quittingTerminalSemanticPair reward
    (finFourSingletonBaseProfile reward owner point)

/-- Positive-debt support of the singleton-base stationary source. -/
def finFourSingletonBasePositiveDebtSupport
    (reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4))
    (owner : Fin 4)
    (point : mixedPolytope
      (quittingBinaryForm (finFourSingletonBaseFree owner)).sig) :
    Finset (Fin 4) :=
  Finset.univ.filter fun who ↦
    0 < quittingTerminalSemanticDebt
      (finFourSingletonBaseSemanticPair reward owner point) who

private theorem finFourSingletonBase_nonempty (owner : Fin 4) :
    ({owner} : Finset (Fin 4)).Nonempty := by simp

private theorem finFourSingletonBase_disjoint_free (owner : Fin 4) :
    Disjoint ({owner} : Finset (Fin 4))
      (finFourSingletonBaseFree owner) := by
  simp [finFourSingletonBaseFree]

private theorem finFourSingletonBaseFree_card (owner : Fin 4) :
    (finFourSingletonBaseFree owner).card = 3 := by
  simp [finFourSingletonBaseFree]

private theorem exists_finFour_two_labels_outside_pair
    (owner resetOwner : Fin 4) (hne : resetOwner ≠ owner) :
    ∃ first second : Fin 4,
      first ≠ owner ∧ first ≠ resetOwner ∧
      second ≠ owner ∧ second ≠ resetOwner ∧ first ≠ second ∧
      ∀ who : Fin 4,
        who = owner ∨ who = resetOwner ∨ who = first ∨ who = second := by
  fin_cases owner <;> fin_cases resetOwner <;> simp_all <;> decide

private theorem singletonBase_endpointDifference_zero_pureSetRoot
    (reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4))
    (coalition : Finset (Fin 4)) (who : Fin 4)
    (herase : (coalition.erase who).Nonempty) :
    quittingRootEndpointDifference reward 0
        (quittingPureSetRoot coalition) who =
      quittingSetReward reward (insert who coalition) who -
        quittingSetReward reward (coalition.erase who) who := by
  rw [quittingRootEndpointDifference,
    quittingRootQuitPayoff_pureSetRoot_eq_insert,
    quittingRootContinuePayoff_pureSetRoot_eq_erase_of_nonempty
      (0 : Payoff (Fin 4)) coalition who herase]

/-- Actual singleton-base data retaining the stationary source, its heavy
strict-superset atom, its unique paid debtor, and the same-law reset dispatch. -/
structure FinFourSingletonBaseSameLawResetProducer
    (reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4))
    (bound : ℝ)
    (residual : FinFourQuantitativeFullSupportHardResidual reward bound)
    (owner : Fin 4) where
  resetOwner : Fin 4
  resetOwner_ne_owner : resetOwner ≠ owner
  bound_pos : 0 < bound
  point : mixedPolytope
    (quittingBinaryForm (finFourSingletonBaseFree owner)).sig
  point_mem : point ∈ quittingPersistentBaseNashSet reward {owner}
    (finFourSingletonBaseFree owner)
  free_solved : ∀ who ∈ finFourSingletonBaseFree owner,
    quittingTerminalSemanticDebt
        (finFourSingletonBaseSemanticPair reward owner point) who = 0 ∧
      quittingPunishmentValue reward who ≤
        (finFourSingletonBaseSemanticPair reward owner point).1 who
  owner_gap : residual.witness.terminalGap ≤
    quittingTerminalSemanticDebt
      (finFourSingletonBaseSemanticPair reward owner point) owner
  positiveDebtSupport_eq :
    finFourSingletonBasePositiveDebtSupport reward owner point = {owner}
  paid_row : Nonempty (QuittingPaidFirstDisagreementRow reward
    (finFourSingletonBaseProfile reward owner point) owner
      residual.witness.terminalGap)
  free_absorption_lower :
    residual.witness.terminalGap /
        (residual.witness.terminalGap + 2 * bound) ≤
      1 - ∏ who ∈ finFourSingletonBaseFree owner,
        ((finFourSingletonBaseRoot owner point) who false).toReal
  atomFree : Finset (Fin 4)
  atomFree_nonempty : atomFree.Nonempty
  atomFree_subset : atomFree ⊆ finFourSingletonBaseFree owner
  atom_mass_lower :
    residual.witness.terminalGap /
        (7 * (residual.witness.terminalGap + 2 * bound)) ≤
      quittingTerminalOutcomeMass reward
        (finFourSingletonBaseProfile reward owner point)
        (some ⟨insert owner atomFree, Finset.insert_nonempty owner atomFree⟩)
  target_joint :
    (finFourSingletonBaseSemanticPair reward owner point,
      quittingTerminalOutcomeMass reward
        (finFourSingletonBaseProfile reward owner point)) ∈
      quittingTerminalSemanticLawCarrier reward
  reset_incidence :
    quittingTerminalOpponentIncidenceMass resetOwner owner
      (quittingTerminalOutcomeMass reward
        (finFourSingletonBaseProfile reward owner point)) = 1
  minimum : QuittingTerminalSemanticPair (Fin 4)
  minimum_mem : minimum ∈ quittingTerminalSemanticCarrier reward
  minimum_global : ∀ candidate ∈ quittingTerminalSemanticCarrier reward,
    quittingTerminalSemanticDebtSum minimum ≤
      quittingTerminalSemanticDebtSum candidate
  minimum_positive : 0 < quittingTerminalSemanticDebtSum minimum
  returned : QuittingTerminalSemanticPair (Fin 4)
  dispatch : QuittingFixedLawResetDispatch (reward := reward)
    minimum (finFourSingletonBaseSemanticPair reward owner point)
      (quittingTerminalOutcomeMass reward
        (finFourSingletonBaseProfile reward owner point))
      resetOwner owner returned

private theorem singletonBase_rootOpponentIncidence_eq_one_of_pureQuit
    {iota : Type} [Fintype iota] [DecidableEq iota]
    (root : iota → PMF Bool) (marked other : iota) (hne : other ≠ marked)
    (hother : root other = PMF.pure true) :
    quittingRootOpponentIncidenceMass marked other root = 1 := by
  have hcontinue : quittingStationaryContinueMass root = 0 :=
    quittingStationaryContinueMass_of_sureQuitter hother
  have hzero : ∀ terminal : {S : Finset iota // S.Nonempty},
      other ∉ terminal.val → quittingRootCoalitionMass root terminal.val = 0 := by
    intro terminal hnot
    have hupper := quittingRootCoalitionMass_le_continueProbability_of_not_mem
      root terminal.val other hnot
    rw [hother] at hupper
    norm_num at hupper
    exact le_antisymm hupper
      (MarkedAbsorptionCylinder.quittingRootCoalitionMass_nonneg
        root terminal.val)
  have hfilter :
      (∑ terminal ∈ (Finset.univ.filter fun terminal :
          {S : Finset iota // S.Nonempty} ↦ other ∈ terminal.val),
        quittingRootCoalitionMass root terminal.val) =
        ∑ terminal : {S : Finset iota // S.Nonempty},
          quittingRootCoalitionMass root terminal.val := by
    rw [Finset.sum_filter]
    apply Finset.sum_congr rfl
    intro terminal _
    by_cases hmem : other ∈ terminal.val
    · simp [hmem]
    · simp [hmem, hzero terminal hmem]
  unfold quittingRootOpponentIncidenceMass
  have hevent : (Finset.univ.filter fun terminal :
      {S : Finset iota // S.Nonempty} ↦
        other ∈ terminal.val ∧ other ≠ marked) =
      Finset.univ.filter fun terminal : {S : Finset iota // S.Nonempty} ↦
        other ∈ terminal.val := by
    ext terminal
    simp [hne]
  rw [hevent, hfilter]
  rw [← Finset.sum_subtype (Finset.univ.erase (∅ : Finset iota))
    (fun coalition ↦ by
      simp only [Finset.mem_erase, Finset.mem_univ, and_true]
      exact Finset.nonempty_iff_ne_empty.symm)
    (quittingRootCoalitionMass root)]
  rw [quittingRootCoalitionMass_sum_nonempty, hcontinue]
  norm_num

private theorem singletonBase_stationaryOutcome_incidence_eq_one_of_pureQuit
    {iota : Type} [Fintype iota] [DecidableEq iota]
    (reward : {S : Finset iota // S.Nonempty} → Payoff iota)
    (root : iota → PMF Bool) (marked other : iota) (hne : other ≠ marked)
    (hother : root other = PMF.pure true) :
    quittingTerminalOpponentIncidenceMass marked other
        (quittingTerminalOutcomeMass reward
          (quittingStationaryProfile reward root)) = 1 := by
  let profile := quittingStationaryProfile reward root
  let mass := quittingTerminalOutcomeMass reward profile
  have hcontinue : quittingStationaryContinueMass root = 0 :=
    quittingStationaryContinueMass_of_sureQuitter hother
  have hrootIncidence :
      quittingRootOpponentIncidenceMass marked other root = 1 :=
    singletonBase_rootOpponentIncidence_eq_one_of_pureQuit
      root marked other hne hother
  have hlaw : mass = quittingTerminalOutcomeLawPrefix root mass := by
    symm
    simpa only [mass, profile,
      quittingRootThenContinuationProfile_stationary] using
      (quittingTerminalOutcomeLawPrefix_outcomeMass reward root profile)
  change quittingTerminalOpponentIncidenceMass marked other mass = 1
  rw [hlaw, quittingTerminalOpponentIncidenceMass_lawPrefix,
    hrootIncidence, hcontinue]
  simp

/-- Every actual quantitative hard residual and every prescribed singleton
owner produce a one-debtor stationary source whose same complete law enters
the fixed-law reset dispatcher. -/
theorem FinFourQuantitativeFullSupportHardResidual.nonempty_singletonBaseSameLawResetProducer
    {reward : {S : Finset (Fin 4) // S.Nonempty} → Payoff (Fin 4)}
    {M : ℝ}
    (residual : FinFourQuantitativeFullSupportHardResidual reward M)
    (hbound : ∀ terminal who, |reward terminal who| ≤ M)
    (owner : Fin 4) :
    Nonempty (FinFourSingletonBaseSameLawResetProducer reward M residual
      owner) := by
  have hM := quittingRewardCoordinateBound_nonneg_of_player reward owner hbound
  obtain ⟨resetOwner, hresetNe, hcollision⟩ :=
    residual.exists_terminalGap_collision_at_singleton owner
  have hgapBound : residual.witness.terminalGap ≤ 2 * M :=
    terminalExploitabilityGap_le_two_mul_bound reward hbound
      residual.witness.terminalExploitability
  have hMpos : 0 < M := by
    linarith [residual.witness.terminalGap_pos]
  let base : Finset (Fin 4) := {owner}
  let free := finFourSingletonBaseFree owner
  have hbase : base.Nonempty := by simp [base]
  have hdisjoint : Disjoint base free := by
    simpa [base, free] using finFourSingletonBase_disjoint_free owner
  have hresetFree : resetOwner ∈ free := by
    simp [free, finFourSingletonBaseFree, hresetNe]
  obtain ⟨first, second, hfirstOwner, hfirstReset, hsecondOwner,
      hsecondReset, hfirstSecond, hexhaust⟩ :=
    exists_finFour_two_labels_outside_pair owner resetOwner hresetNe
  have hownerReset : owner ≠ resetOwner := Ne.symm hresetNe
  have hresetFirst : resetOwner ≠ first := Ne.symm hfirstReset
  have hresetSecond : resetOwner ≠ second := Ne.symm hsecondReset
  have hownerFirst : owner ≠ first := Ne.symm hfirstOwner
  have hownerSecond : owner ≠ second := Ne.symm hsecondOwner
  have hsecondFirst : second ≠ first := Ne.symm hfirstSecond
  have hfirstFree : first ∈ free := by
    simp [free, finFourSingletonBaseFree, hfirstOwner]
  have hsecondFree : second ∈ free := by
    simp [free, finFourSingletonBaseFree, hsecondOwner]
  obtain ⟨point, hpoint⟩ :=
    quittingPersistentBaseNashSet_nonempty reward base free
  let root := finFourSingletonBaseRoot owner point
  let profile := finFourSingletonBaseProfile reward owner point
  let pair := finFourSingletonBaseSemanticPair reward owner point
  let mass := quittingTerminalOutcomeMass reward profile
  have hrootDef : root = quittingPersistentBaseRoot base free point := by rfl
  have hprofileDef : profile = quittingStationaryProfile reward root := by rfl
  let x := (root resetOwner true).toReal
  let y := (root first true).toReal
  let z := (root second true).toReal
  have hrootOwner : root owner = PMF.pure true := by
    exact quittingPersistentBaseRoot_apply_of_mem_base base free point (by
      simp [base])
  have hrootContinue : quittingStationaryContinueMass root = 0 :=
    quittingStationaryContinueMass_of_sureQuitter hrootOwner
  have hfreeUnion : base ∪ free = Finset.univ := by
    ext who
    simp [base, free, finFourSingletonBaseFree]
  have hroot000 :
      Function.update
          (Function.update
            (Function.update root first (PMF.pure false))
              second (PMF.pure false))
          resetOwner (PMF.pure false) =
        quittingPureSetRoot {owner} := by
    funext who
    rcases hexhaust who with h | h | h | h <;> subst who <;>
      simp_all [root, finFourSingletonBaseRoot, base, free,
        quittingPureSetRoot, quittingSetAction]
  have hroot100 :
      Function.update
          (Function.update
            (Function.update root first (PMF.pure true))
              second (PMF.pure false))
          resetOwner (PMF.pure false) =
        quittingPureSetRoot {owner, first} := by
    funext who
    rcases hexhaust who with h | h | h | h <;> subst who <;>
      simp_all [root, finFourSingletonBaseRoot, base, free,
        quittingPureSetRoot, quittingSetAction]
  have hroot010 :
      Function.update
          (Function.update
            (Function.update root first (PMF.pure false))
              second (PMF.pure true))
          resetOwner (PMF.pure false) =
        quittingPureSetRoot {owner, second} := by
    funext who
    rcases hexhaust who with h | h | h | h <;> subst who <;>
      simp_all [root, finFourSingletonBaseRoot, base, free,
        quittingPureSetRoot, quittingSetAction]
  have hroot110 :
      Function.update
          (Function.update
            (Function.update root first (PMF.pure true))
              second (PMF.pure true))
          resetOwner (PMF.pure false) =
        quittingPureSetRoot {owner, first, second} := by
    funext who
    rcases hexhaust who with h | h | h | h <;> subst who <;>
      simp_all [root, finFourSingletonBaseRoot, base, free,
        quittingPureSetRoot, quittingSetAction]
  let endpoint : Bool → Bool → ℝ := fun firstAction secondAction ↦
    quittingRootEndpointDifference reward 0
      (Function.update
        (Function.update root first (PMF.pure firstAction))
        second (PMF.pure secondAction)) resetOwner
  have hendpointFF : residual.witness.terminalGap ≤ endpoint false false := by
    dsimp only [endpoint]
    rw [← quittingRootEndpointDifference_update_self reward 0
      (Function.update
        (Function.update root first (PMF.pure false))
        second (PMF.pure false)) resetOwner (PMF.pure false),
      hroot000,
      singletonBase_endpointDifference_zero_pureSetRoot reward {owner}
        resetOwner (by simp [hresetNe])]
    have herase : ({owner} : Finset (Fin 4)).erase resetOwner =
        {owner} := by simp [hresetNe]
    rw [herase, quittingSetReward_singleton_eq_soloReward,
      quittingSetReward_pair_left]
    rw [quittingSetReward_singleton_eq_soloReward,
      quittingSetReward_pair_right] at hcollision
    linarith
  have hendpointTF : -2 * M ≤ endpoint true false := by
    dsimp only [endpoint]
    rw [← quittingRootEndpointDifference_update_self reward 0
      (Function.update
        (Function.update root first (PMF.pure true))
        second (PMF.pure false)) resetOwner (PMF.pure false),
      hroot100,
      singletonBase_endpointDifference_zero_pureSetRoot reward
        {owner, first} resetOwner (by simp [hresetNe, hresetFirst])]
    have herase : ({owner, first} : Finset (Fin 4)).erase
        resetOwner = {owner, first} := by
        simp [hresetNe, hresetFirst]
    rw [herase]
    have hlower : -M ≤ quittingSetReward reward
        (insert resetOwner {owner, first}) resetOwner := by
      rw [quittingSetReward_of_nonempty reward (by simp)]
      exact (abs_le.mp (hbound _ resetOwner)).1
    have hupper : quittingSetReward reward {owner, first}
        resetOwner ≤ M := by
      rw [quittingSetReward_of_nonempty reward (by simp)]
      exact (abs_le.mp (hbound _ resetOwner)).2
    linarith
  have hendpointFT : -2 * M ≤ endpoint false true := by
    dsimp only [endpoint]
    rw [← quittingRootEndpointDifference_update_self reward 0
      (Function.update
        (Function.update root first (PMF.pure false))
        second (PMF.pure true)) resetOwner (PMF.pure false),
      hroot010,
      singletonBase_endpointDifference_zero_pureSetRoot reward
        {owner, second} resetOwner (by simp [hresetNe, hresetSecond])]
    have herase : ({owner, second} : Finset (Fin 4)).erase
        resetOwner = {owner, second} := by
        simp [hresetNe, hresetSecond]
    rw [herase]
    have hlower : -M ≤ quittingSetReward reward
        (insert resetOwner {owner, second}) resetOwner := by
      rw [quittingSetReward_of_nonempty reward (by simp)]
      exact (abs_le.mp (hbound _ resetOwner)).1
    have hupper : quittingSetReward reward {owner, second}
        resetOwner ≤ M := by
      rw [quittingSetReward_of_nonempty reward (by simp)]
      exact (abs_le.mp (hbound _ resetOwner)).2
    linarith
  have hendpointTT : -2 * M ≤ endpoint true true := by
    dsimp only [endpoint]
    rw [← quittingRootEndpointDifference_update_self reward 0
      (Function.update
        (Function.update root first (PMF.pure true))
        second (PMF.pure true)) resetOwner (PMF.pure false),
      hroot110,
      singletonBase_endpointDifference_zero_pureSetRoot reward
        {owner, first, second} resetOwner
          (by simp [hresetNe, hresetFirst, hresetSecond])]
    have herase : ({owner, first, second} : Finset (Fin 4)).erase
        resetOwner = {owner, first, second} := by
        simp [hresetNe, hresetFirst, hresetSecond]
    rw [herase]
    have hlower : -M ≤ quittingSetReward reward
        (insert resetOwner {owner, first, second}) resetOwner := by
      rw [quittingSetReward_of_nonempty reward (by simp)]
      exact (abs_le.mp (hbound _ resetOwner)).1
    have hupper : quittingSetReward reward {owner, first, second}
        resetOwner ≤ M := by
      rw [quittingSetReward_of_nonempty reward (by simp)]
      exact (abs_le.mp (hbound _ resetOwner)).2
    linarith
  have hx0 : 0 ≤ x := ENNReal.toReal_nonneg
  have hx1 : x ≤ 1 := by
    exact ENNReal.toReal_mono ENNReal.one_ne_top
      ((root resetOwner).coe_le_one true)
  have hy0 : 0 ≤ y := ENNReal.toReal_nonneg
  have hy1 : y ≤ 1 := by
    exact ENNReal.toReal_mono ENNReal.one_ne_top
      ((root first).coe_le_one true)
  have hz0 : 0 ≤ z := ENNReal.toReal_nonneg
  have hz1 : z ≤ 1 := by
    exact ENNReal.toReal_mono ENNReal.one_ne_top
      ((root second).coe_le_one true)
  have hdenom : 0 < residual.witness.terminalGap + 2 * M :=
    add_pos_of_pos_of_nonneg residual.witness.terminalGap_pos
      (mul_nonneg (by norm_num) hM)
  have hratioLeOne : residual.witness.terminalGap /
      (residual.witness.terminalGap + 2 * M) ≤ 1 := by
    apply (div_le_one hdenom).2
    linarith
  have hproduct := quittingRootEndpointDifference_eq_twoOpponentProduct
    reward 0 root hresetFirst hresetSecond hfirstSecond
  change quittingRootEndpointDifference reward 0 root resetOwner =
      binaryProductExpectation endpoint y z at hproduct
  have hpure := quittingPersistentBaseRoot_free_purePayoff_le
    reward base free hbase hdisjoint point hpoint resetOwner hresetFree
  have hsub := quittingRootQuitPayoff_sub_successorPayoff
    reward 0 root resetOwner
  have hcontinueEq : (root resetOwner false).toReal = 1 - x := by
    have hsum := quittingRoot_continueProbability_add_quitProbability
      root resetOwner
    linarith
  have hfreeEq : free = {resetOwner, first, second} := by
    apply Finset.Subset.antisymm
    · intro who hwho
      rcases hexhaust who with h | h | h | h
      · subst who
        exact (Finset.disjoint_left.mp hdisjoint (by simp [base]) hwho).elim
      · simp [h]
      · simp [h]
      · simp [h]
    · intro who hwho
      simp only [Finset.mem_insert, Finset.mem_singleton] at hwho
      rcases hwho with h | h | h <;> subst who
      · exact hresetFree
      · exact hfirstFree
      · exact hsecondFree
  have hfreeProduct :
      (∏ who ∈ free, (root who false).toReal) =
        (1 - x) * (1 - y) * (1 - z) := by
    rw [hfreeEq]
    simp [x, y, z, hresetFirst, hresetSecond, hfirstSecond,
      Math.PMFProduct.pmfBool_false_toReal]
    ring
  have hfreeAbsorptionLower :
      residual.witness.terminalGap /
          (residual.witness.terminalGap + 2 * M) ≤
        1 - ∏ who ∈ free, (root who false).toReal := by
    rw [hfreeProduct]
    by_cases hxOne : x = 1
    · rw [hxOne]
      norm_num
      exact hratioLeOne
    · have hxLt : x < 1 := lt_of_le_of_ne hx1 hxOne
      have hendpointNonpos :
          quittingRootEndpointDifference reward 0 root resetOwner ≤ 0 := by
        rw [hcontinueEq] at hsub
        have hregret : quittingRootQuitPayoff reward 0 root resetOwner -
            quittingRootSuccessorPayoff reward 0 root resetOwner ≤ 0 :=
          sub_nonpos.mpr hpure.1
        nlinarith
      rw [hproduct] at hendpointNonpos
      dsimp only [binaryProductExpectation] at hendpointNonpos
      have hff := mul_le_mul_of_nonneg_left hendpointFF
        (mul_nonneg (sub_nonneg.mpr hy1) (sub_nonneg.mpr hz1))
      have htf := mul_le_mul_of_nonneg_left hendpointTF
        (mul_nonneg hy0 (sub_nonneg.mpr hz1))
      have hft := mul_le_mul_of_nonneg_left hendpointFT
        (mul_nonneg (sub_nonneg.mpr hy1) hz0)
      have htt := mul_le_mul_of_nonneg_left hendpointTT
        (mul_nonneg hy0 hz0)
      have hweighted :
          (1 - y) * (1 - z) * residual.witness.terminalGap +
              y * (1 - z) * (-2 * M) +
              (1 - y) * z * (-2 * M) +
              y * z * (-2 * M) ≤ 0 := by
        nlinarith
      apply (div_le_iff₀ hdenom).2
      have hsurvival : 0 ≤ (1 - y) * (1 - z) :=
        mul_nonneg (sub_nonneg.mpr hy1) (sub_nonneg.mpr hz1)
      nlinarith
  have hterminalMass (terminal : {S : Finset (Fin 4) // S.Nonempty}) :
      mass (some terminal) = quittingRootCoalitionMass root terminal.val := by
    change quittingAbsorbedMassLimit reward profile terminal = _
    have hprefix := quittingAbsorbedMassLimit_rootThenContinuation
      reward root profile terminal
    have hsplice : quittingRootThenContinuationProfile reward root profile =
        profile := by
      change quittingRootThenContinuationProfile reward root
          (quittingStationaryProfile reward root) =
        quittingStationaryProfile reward root
      exact quittingRootThenContinuationProfile_stationary reward root
    rw [hsplice, hrootContinue, zero_mul, add_zero] at hprefix
    exact hprefix
  let rate : Fin 4 → ℝ := fun who ↦ (root who true).toReal
  have hrootAtomMass (atomFree : Finset (Fin 4))
      (hatomFree : atomFree ⊆ free) :
      quittingRootCoalitionMass root (insert owner atomFree) =
        Math.Finset.bernoulliWeight rate free atomFree := by
    have hownerNotMem : owner ∉ atomFree := by
      intro hmem
      have hownerFree := hatomFree hmem
      exact (Finset.disjoint_left.mp hdisjoint (by simp [base])
        hownerFree).elim
    have hcomplement : (insert owner atomFree : Finset (Fin 4))ᶜ =
        free \ atomFree := by
      ext who
      simp only [Finset.mem_compl, Finset.mem_insert,
        Finset.mem_sdiff]
      constructor
      · intro hnot
        have hneOwner : who ≠ owner := fun h ↦ hnot (Or.inl h)
        exact ⟨by simp [free, finFourSingletonBaseFree, hneOwner],
          fun hmem ↦ hnot (Or.inr hmem)⟩
      · rintro ⟨hfree, hnotMem⟩ (howner | hmem)
        · subst who
          exact (Finset.disjoint_left.mp hdisjoint (by simp [base])
            hfree).elim
        · exact hnotMem hmem
    unfold quittingRootCoalitionMass quittingRootQuitRates coalitionMass
      Math.Finset.bernoulliWeight
    rw [hcomplement, Finset.prod_insert hownerNotMem]
    simp [rate, hrootOwner]
  let indices : Finset (Finset (Fin 4)) := free.powerset.erase ∅
  let atomWeight : Finset (Fin 4) → ℝ := fun atomFree ↦
    mass (some ⟨insert owner atomFree,
      Finset.insert_nonempty owner atomFree⟩)
  have hweight (atomFree : Finset (Fin 4))
      (hatomFree : atomFree ∈ free.powerset) :
      atomWeight atomFree = Math.Finset.bernoulliWeight rate free atomFree := by
    rw [show atomWeight atomFree = mass
        (some ⟨insert owner atomFree,
          Finset.insert_nonempty owner atomFree⟩) by rfl,
      hterminalMass]
    exact hrootAtomMass atomFree (Finset.mem_powerset.mp hatomFree)
  have hindicesNonempty : indices.Nonempty := by
    refine ⟨{resetOwner}, ?_⟩
    simp [indices, hresetFree]
  have hindicesCard : indices.card = 7 := by
    dsimp only [indices]
    rw [Finset.card_erase_of_mem (by simp), Finset.card_powerset]
    rw [show free.card = 3 by
      simpa [free] using finFourSingletonBaseFree_card owner]
    norm_num
  have hsumWeight : (∑ atomFree ∈ indices, atomWeight atomFree) =
      1 - ∏ who ∈ free, (root who false).toReal := by
    have htotal := Math.Finset.sum_bernoulliWeight rate free
    have hemptyMem : (∅ : Finset (Fin 4)) ∈ free.powerset := by simp
    have hsplit := Finset.sum_erase_add free.powerset
      (Math.Finset.bernoulliWeight rate free) hemptyMem
    calc
      (∑ atomFree ∈ indices, atomWeight atomFree) =
          ∑ atomFree ∈ free.powerset.erase ∅,
            Math.Finset.bernoulliWeight rate free atomFree := by
              apply Finset.sum_congr rfl
              intro atomFree hatomFree
              apply hweight
              exact Finset.mem_of_mem_erase hatomFree
      _ = 1 - Math.Finset.bernoulliWeight rate free ∅ := by
        rw [← htotal]
        linarith
      _ = 1 - ∏ who ∈ free, (root who false).toReal := by
        simp [Math.Finset.bernoulliWeight, rate,
          Math.PMFProduct.pmfBool_false_toReal]
  obtain ⟨atomFree, hatomIndices, hatomMaximum⟩ :=
    Finset.exists_max_image indices atomWeight hindicesNonempty
  have hatomAverage : (∑ other ∈ indices, atomWeight other) ≤
      (indices.card : ℝ) * atomWeight atomFree := by
    simpa [nsmul_eq_mul] using indices.sum_le_card_nsmul atomWeight
      (atomWeight atomFree) hatomMaximum
  have hatomSubset : atomFree ⊆ free := by
    exact Finset.mem_powerset.mp
      (Finset.mem_of_mem_erase hatomIndices)
  have hatomNonempty : atomFree.Nonempty := by
    exact Finset.nonempty_iff_ne_empty.mpr
      (Finset.ne_of_mem_erase hatomIndices)
  have hatomMass : residual.witness.terminalGap /
        (7 * (residual.witness.terminalGap + 2 * M)) ≤
      atomWeight atomFree := by
    rw [hsumWeight] at hatomAverage
    rw [hindicesCard] at hatomAverage
    norm_num at hatomAverage
    have hscale : 7 * (residual.witness.terminalGap /
          (7 * (residual.witness.terminalGap + 2 * M))) =
        residual.witness.terminalGap /
          (residual.witness.terminalGap + 2 * M) := by
      field_simp
    nlinarith
  have hsemantics := persistentBase_inducedNash_free_semantics
    base free hbase hdisjoint point hpoint
  have hfreeSolved : ∀ who ∈ free,
      quittingTerminalSemanticDebt pair who = 0 ∧
        quittingPunishmentValue reward who ≤ pair.1 who := by
    intro who hwho
    have hsemantic := hsemantics who hwho
    constructor
    · unfold quittingTerminalSemanticDebt
      change (quittingTerminalSemanticPair reward profile).2 who -
          quittingTerminalPayoff reward profile who = 0
      rw [show profile = quittingStationaryProfile reward root by rfl,
        quittingTerminalSemanticPair_stationary_envelope_eq_cap]
      apply sub_eq_zero.mpr
      rw [hrootDef]
      exact hsemantic.1.symm
    · exact hsemantic.2
  obtain ⟨debtor, deviation, hexploit⟩ :=
    residual.witness.terminalExploitability profile
  have hdeviationCap := quittingTerminalPayoff_update_stationary_le_cap
    reward root debtor deviation
  have hdeviationCap' :
      quittingTerminalPayoff reward
          (Function.update profile debtor deviation) debtor ≤
        quittingStationaryUnilateralCap reward root debtor := by
    rw [hprofileDef]
    exact hdeviationCap
  have hdebtorGap : residual.witness.terminalGap ≤
      quittingTerminalSemanticDebt pair debtor := by
    change residual.witness.terminalGap ≤
      (quittingTerminalSemanticPair reward profile).2 debtor -
        quittingTerminalPayoff reward profile debtor
    rw [show profile = quittingStationaryProfile reward root by rfl,
      quittingTerminalSemanticPair_stationary_envelope_eq_cap]
    rw [← hprofileDef]
    linarith [hexploit, hdeviationCap']
  have hdebtorOwner : debtor = owner := by
    by_contra hne
    have hdebtorFree : debtor ∈ free := by
      simp [free, finFourSingletonBaseFree, hne]
    rw [(hfreeSolved debtor hdebtorFree).1] at hdebtorGap
    linarith [residual.witness.terminalGap_pos]
  subst debtor
  have hpaid : Nonempty (QuittingPaidFirstDisagreementRow reward profile
      owner residual.witness.terminalGap) := by
    have hcapDebt : residual.witness.terminalGap ≤
        quittingStationaryUnilateralCap reward root owner -
          quittingTerminalPayoff reward profile owner := by
      have hgap := hdebtorGap
      change residual.witness.terminalGap ≤
        (quittingTerminalSemanticPair reward profile).2 owner -
          quittingTerminalPayoff reward profile owner at hgap
      rw [show profile = quittingStationaryProfile reward root by rfl,
        quittingTerminalSemanticPair_stationary_envelope_eq_cap] at hgap
      exact hgap
    rcases exists_oriented_quitNow_never_gap_of_stationary_cap_debt
        reward root owner hcapDebt with hquit | hnever
    · obtain ⟨row, -, -⟩ :=
        exists_quittingPaidFirstDisagreementRow_of_pureTimePayoff_sub
          reward profile owner none (some 0)
            residual.witness.terminalGap
            residual.witness.terminalGap_pos hquit
      exact ⟨row⟩
    · obtain ⟨row, -, -⟩ :=
        exists_quittingPaidFirstDisagreementRow_of_pureTimePayoff_sub
          reward profile owner (some 0) none
            residual.witness.terminalGap
            residual.witness.terminalGap_pos hnever
      exact ⟨row⟩
  let support := finFourSingletonBasePositiveDebtSupport reward owner point
  have hsupportEq : support = {owner} := by
    ext who
    simp only [support, finFourSingletonBasePositiveDebtSupport,
      Finset.mem_filter, Finset.mem_univ, true_and,
      Finset.mem_singleton]
    constructor
    · intro hpositive
      by_contra hne
      have hwhoFree : who ∈ free := by
        simp [free, finFourSingletonBaseFree, hne]
      rw [(hfreeSolved who hwhoFree).1] at hpositive
      exact (lt_irrefl 0 hpositive)
    · intro heq
      subst who
      exact residual.witness.terminalGap_pos.trans_le hdebtorGap
  have hjoint : (pair, mass) ∈ quittingTerminalSemanticLawCarrier reward :=
    quittingTerminalSemanticLawPoint_mem_carrier reward profile
  have hincidence : quittingTerminalOpponentIncidenceMass resetOwner owner
      mass = 1 := by
    exact singletonBase_stationaryOutcome_incidence_eq_one_of_pureQuit
      reward root resetOwner owner hownerReset hrootOwner
  obtain ⟨minimum, minimumRoot, hminimumMem, _hminimumRoot,
      hminimum, hminimumCoordinate, _hminimumFace⟩ :=
    exists_positive_minimumTerminalSemanticDebt_face_of_no_uniformPayoff
      reward residual.witness.not_exists_uniformEquilibriumPayoff
  have hminimumPositive : 0 <
      quittingTerminalSemanticDebtSum minimum := by
    obtain ⟨positiveWho, hpositiveWho⟩ := hminimumCoordinate
    apply hpositiveWho.trans_le
    unfold quittingTerminalSemanticDebtSum
    exact Finset.single_le_sum
      (fun who _ ↦ quittingTerminalSemanticDebt_nonneg_of_mem_carrier
        reward hminimumMem who)
      (Finset.mem_univ positiveWho)
  obtain ⟨returned, hdispatch⟩ :=
    residual.witness.exists_fixedLawResetDispatch
      minimum pair mass resetOwner owner hminimum hminimumPositive
        hjoint (hfreeSolved resetOwner hresetFree).1 (by
          rw [hincidence]
          norm_num)
  refine ⟨{
    resetOwner := resetOwner
    resetOwner_ne_owner := hresetNe
    bound_pos := hMpos
    point := point
    point_mem := by simpa [base, free] using hpoint
    free_solved := by simpa [free] using hfreeSolved
    owner_gap := hdebtorGap
    positiveDebtSupport_eq := by simpa [support] using hsupportEq
    paid_row := by simpa [profile] using hpaid
    free_absorption_lower := by simpa [free, root] using hfreeAbsorptionLower
    atomFree := atomFree
    atomFree_nonempty := hatomNonempty
    atomFree_subset := by simpa [free] using hatomSubset
    atom_mass_lower := by
      simpa [atomWeight, mass, profile] using hatomMass
    target_joint := by simpa [pair, mass] using hjoint
    reset_incidence := by simpa [mass] using hincidence
    minimum := minimum
    minimum_mem := hminimumMem
    minimum_global := hminimum
    minimum_positive := hminimumPositive
    returned := returned
    dispatch := by simpa [pair, mass] using hdispatch } ⟩

end GameTheory
