/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import Mathlib

/-!
# Causal stopping weights form subprobability weights

Changing Continue to Quit at chronologically ordered rows gives causal
weights `lambda_k * product_{l < k} (1 - lambda_l)`.  This file records the
finite algebraic fact that these weights are nonnegative and have total mass
at most one.  Hence every resulting linear payoff is bounded above by any
common nonnegative upper bound for the signed one-row gains.  No converse
representation is asserted here.
-/

namespace Math
namespace Probability

/-- Chronological stopping weights generated by successive conditional Quit
fractions. -/
def causalQuitWeights : List ℝ → List ℝ
  | [] => []
  | probability :: tail =>
      probability ::
        (causalQuitWeights tail).map ((1 - probability) * ·)

@[simp] theorem length_causalQuitWeights (probabilities : List ℝ) :
    (causalQuitWeights probabilities).length = probabilities.length := by
  induction probabilities with
  | nil => rfl
  | cons probability tail ih => simp [causalQuitWeights, ih]

/-- Exact total stopping mass: one minus the probability of refusing every
marked row. -/
theorem sum_causalQuitWeights_eq_one_sub_prod
    (probabilities : List ℝ) :
    (causalQuitWeights probabilities).sum =
      1 - (probabilities.map (1 - ·)).prod := by
  induction probabilities with
  | nil => simp [causalQuitWeights]
  | cons probability tail ih =>
      have hscale :
          ((causalQuitWeights tail).map ((1 - probability) * ·)).sum =
            (1 - probability) * (causalQuitWeights tail).sum := by
        simpa using List.sum_map_mul_left
          (causalQuitWeights tail) id (1 - probability)
      simp only [causalQuitWeights, List.sum_cons, hscale, ih,
        List.map_cons, List.prod_cons]
      ring

/-- Admissible conditional probabilities generate nonnegative causal
weights. -/
theorem causalQuitWeights_nonneg
    (probabilities : List ℝ)
    (hprobability : ∀ probability ∈ probabilities,
      probability ∈ Set.Icc (0 : ℝ) 1) :
    ∀ weight ∈ causalQuitWeights probabilities, 0 ≤ weight := by
  induction probabilities with
  | nil => simp [causalQuitWeights]
  | cons probability tail ih =>
      have hp := hprobability probability (by simp)
      have htail : ∀ p ∈ tail, p ∈ Set.Icc (0 : ℝ) 1 := by
        intro p hpMem
        exact hprobability p (by simp [hpMem])
      intro weight hweight
      simp only [causalQuitWeights, List.mem_cons, List.mem_map] at hweight
      rcases hweight with rfl | ⟨oldWeight, holdWeight, rfl⟩
      · exact hp.1
      · exact mul_nonneg (sub_nonneg.mpr hp.2) (ih htail oldWeight holdWeight)

/-- Admissible causal weights have total mass at most one. -/
theorem sum_causalQuitWeights_le_one
    (probabilities : List ℝ)
    (hprobability : ∀ probability ∈ probabilities,
      probability ∈ Set.Icc (0 : ℝ) 1) :
    (causalQuitWeights probabilities).sum ≤ 1 := by
  rw [sum_causalQuitWeights_eq_one_sub_prod]
  have hfactor : ∀ factor ∈ probabilities.map (1 - ·), 0 ≤ factor := by
    intro factor hfactor
    obtain ⟨probability, hp, rfl⟩ := List.mem_map.mp hfactor
    exact sub_nonneg.mpr (hprobability probability hp).2
  have hprod : 0 ≤ (probabilities.map (1 - ·)).prod :=
    List.prod_nonneg hfactor
  linarith

private theorem zipWith_mul_sum_le_sum_mul
    (weights gains : List ℝ) (upper : ℝ)
    (hweights : ∀ weight ∈ weights, 0 ≤ weight)
    (hupperNonneg : 0 ≤ upper)
    (hgain : ∀ gain ∈ gains, gain ≤ upper) :
    (List.zipWith (· * ·) weights gains).sum ≤ weights.sum * upper := by
  induction weights generalizing gains with
  | nil => simp
  | cons weight weights ih =>
      cases gains with
      | nil =>
          simp only [List.zipWith_nil_right, List.sum_nil]
          have hw : 0 ≤ weight := hweights weight (by simp)
          have hws : 0 ≤ weights.sum :=
            List.sum_nonneg fun x hx => hweights x (by simp [hx])
          exact mul_nonneg (add_nonneg hw hws) hupperNonneg
      | cons gain gains =>
          simp only [List.zipWith_cons_cons, List.sum_cons]
          have hw : 0 ≤ weight := hweights weight (by simp)
          have hg : gain ≤ upper := hgain gain (by simp)
          have hweightsTail : ∀ x ∈ weights, 0 ≤ x := by
            intro x hx
            exact hweights x (by simp [hx])
          have hgainTail : ∀ x ∈ gains, x ≤ upper := by
            intro x hx
            exact hgain x (by simp [hx])
          have hih := ih gains hweightsTail hgainTail
          nlinarith

/-- Every causal linear payoff lies below a common nonnegative upper bound
for the signed one-row gains. -/
theorem zipWith_sum_le_of_causalQuitWeights
    (probabilities gains : List ℝ) (upper : ℝ)
    (hprobability : ∀ probability ∈ probabilities,
      probability ∈ Set.Icc (0 : ℝ) 1)
    (hupperNonneg : 0 ≤ upper)
    (hgain : ∀ gain ∈ gains, gain ≤ upper) :
    (List.zipWith (· * ·) (causalQuitWeights probabilities) gains).sum ≤
      upper := by
  have hweights := causalQuitWeights_nonneg probabilities hprobability
  have hsum := sum_causalQuitWeights_le_one probabilities hprobability
  have hzip := zipWith_mul_sum_le_sum_mul
    (causalQuitWeights probabilities) gains upper hweights hupperNonneg hgain
  nlinarith

end Probability
end Math
