/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import MathUE.Probability.DiscreteHazardStopping

/-!
# Convex mixtures of discrete stopping laws

A convex mixture of two stopping-time laws is again generated by a behavioral
hazard.  The conditional hazard is the mixed stopping mass divided by the
mixed survival mass.  This file records the exact survival, stopping-mass,
Never-mass, and PMF identities.
-/

noncomputable section

open scoped BigOperators

namespace Math.Probability.DiscreteHazard

open Filter Math.Probability Math.ProbabilityMassFunction

namespace ScalarHazard

variable (source target : ScalarHazard) (lambda : ℝ)

/-- Convexly mixed survival mass at a finite cutoff. -/
def mixedSurvival (cutoff : ℕ) : ℝ :=
  (1 - lambda) * source.survival 0 cutoff +
    lambda * target.survival 0 cutoff

/-- Convexly mixed stopping mass at one date. -/
def mixedStopMass (time : ℕ) : ℝ :=
  (1 - lambda) * source.stopMass time + lambda * target.stopMass time

theorem mixedSurvival_nonneg
    (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) (cutoff : ℕ) :
    0 ≤ mixedSurvival source target lambda cutoff := by
  exact add_nonneg
    (mul_nonneg (sub_nonneg.mpr hlambda1)
      (source.survival_nonneg 0 cutoff))
    (mul_nonneg hlambda0 (target.survival_nonneg 0 cutoff))

theorem mixedStopMass_nonneg
    (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) (time : ℕ) :
    0 ≤ mixedStopMass source target lambda time := by
  exact add_nonneg
    (mul_nonneg (sub_nonneg.mpr hlambda1) (source.stopMass_nonneg time))
    (mul_nonneg hlambda0 (target.stopMass_nonneg time))

theorem stopMass_le_survival (hazard : ScalarHazard) (time : ℕ) :
    hazard.stopMass time ≤ hazard.survival 0 time := by
  unfold stopMass
  exact mul_le_of_le_one_right (hazard.survival_nonneg 0 time)
    (hazard.stop_le_one time)

theorem mixedStopMass_le_mixedSurvival
    (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) (time : ℕ) :
    mixedStopMass source target lambda time ≤
      mixedSurvival source target lambda time := by
  exact add_le_add
    (mul_le_mul_of_nonneg_left (source.stopMass_le_survival time)
      (sub_nonneg.mpr hlambda1))
    (mul_le_mul_of_nonneg_left (target.stopMass_le_survival time) hlambda0)

theorem mixedStopMass_eq_survival_sub_succ (time : ℕ) :
    mixedStopMass source target lambda time =
      mixedSurvival source target lambda time -
        mixedSurvival source target lambda (time + 1) := by
  rw [mixedStopMass, mixedSurvival, mixedSurvival,
    source.stopMass_eq_survival_sub_succ,
    target.stopMass_eq_survival_sub_succ]
  ring

/-- The behavioral hazard whose stopping law is the requested convex
mixture.  On a zero-survival row its value is immaterial, and is set to zero. -/
def convexMix
    (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) : ScalarHazard where
  stop time := if mixedSurvival source target lambda time = 0 then 0
    else mixedStopMass source target lambda time /
      mixedSurvival source target lambda time
  stop_nonneg time := by
    split_ifs with hzero
    · exact le_rfl
    · exact div_nonneg
        (mixedStopMass_nonneg source target lambda hlambda0 hlambda1 time)
        (mixedSurvival_nonneg source target lambda hlambda0 hlambda1 time)
  stop_le_one time := by
    split_ifs with hzero
    · norm_num
    · exact (div_le_one
        ((mixedSurvival_nonneg source target lambda hlambda0 hlambda1 time).lt_of_ne'
          hzero)).2
        (mixedStopMass_le_mixedSurvival source target lambda
          hlambda0 hlambda1 time)

theorem convexMix_survival
    (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) (cutoff : ℕ) :
    (convexMix source target lambda hlambda0 hlambda1).survival 0 cutoff =
      mixedSurvival source target lambda cutoff := by
  induction cutoff with
  | zero =>
      simp [ScalarHazard.survival_zero, mixedSurvival]
  | succ cutoff ih =>
      rw [ScalarHazard.survival_succ, ih]
      simp only [Nat.zero_add]
      by_cases hzero : mixedSurvival source target lambda cutoff = 0
      · have hnextLe : mixedSurvival source target lambda (cutoff + 1) ≤
            mixedSurvival source target lambda cutoff := by
          rw [← sub_nonneg]
          rw [← mixedStopMass_eq_survival_sub_succ]
          exact mixedStopMass_nonneg source target lambda hlambda0 hlambda1 cutoff
        have hnextNonneg := mixedSurvival_nonneg source target lambda
          hlambda0 hlambda1 (cutoff + 1)
        have hnext : mixedSurvival source target lambda (cutoff + 1) = 0 := by
          linarith
        simp [convexMix, hzero, hnext]
      · rw [show (convexMix source target lambda hlambda0 hlambda1).stop cutoff =
            mixedStopMass source target lambda cutoff /
              mixedSurvival source target lambda cutoff by
          simp [convexMix, hzero]]
        rw [mixedStopMass_eq_survival_sub_succ]
        field_simp [hzero]
        ring

theorem convexMix_stopMass
    (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) (time : ℕ) :
    (convexMix source target lambda hlambda0 hlambda1).stopMass time =
      mixedStopMass source target lambda time := by
  rw [(convexMix source target lambda hlambda0 hlambda1).stopMass_eq_survival_sub_succ,
    convexMix_survival, convexMix_survival,
    ← mixedStopMass_eq_survival_sub_succ]

theorem convexMix_neverMass
    (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) :
    (convexMix source target lambda hlambda0 hlambda1).neverMass =
      (1 - lambda) * source.neverMass + lambda * target.neverMass := by
  have hsource := source.tendsto_survival_neverMass
  have htarget := target.tendsto_survival_neverMass
  have hmixed : Tendsto (mixedSurvival source target lambda) atTop
      (nhds ((1 - lambda) * source.neverMass + lambda * target.neverMass)) := by
    exact (tendsto_const_nhds.mul hsource).add (tendsto_const_nhds.mul htarget)
  have hconvex :=
    (convexMix source target lambda hlambda0 hlambda1).tendsto_survival_neverMass
  have hsurvival :
      (convexMix source target lambda hlambda0 hlambda1).survival 0 =
        mixedSurvival source target lambda := by
    funext cutoff
    exact convexMix_survival source target lambda hlambda0 hlambda1 cutoff
  rw [hsurvival] at hconvex
  exact tendsto_nhds_unique hconvex hmixed

end ScalarHazard

/-- A Boolean coin whose `true` probability is the supplied real number. -/
def booleanCoin (probability : ℝ) (hprobability0 : 0 ≤ probability)
    (hprobability1 : probability ≤ 1) : PMF Bool :=
  PMF.ofFintype
    (fun stop => if stop then ENNReal.ofReal probability
      else ENNReal.ofReal (1 - probability))
    (by
      rw [Fintype.sum_bool]
      simp only [if_true, if_false, Bool.false_eq_true]
      rw [← ENNReal.ofReal_add hprobability0 (sub_nonneg.mpr hprobability1)]
      norm_num)

@[simp] theorem booleanCoin_true_toReal
    (probability : ℝ) (hprobability0 : 0 ≤ probability)
    (hprobability1 : probability ≤ 1) :
    (booleanCoin probability hprobability0 hprobability1 true).toReal =
      probability := by
  simp [booleanCoin, PMF.ofFintype_apply, ENNReal.toReal_ofReal hprobability0]

@[simp] theorem booleanCoin_false_toReal
    (probability : ℝ) (hprobability0 : 0 ≤ probability)
    (hprobability1 : probability ≤ 1) :
    (booleanCoin probability hprobability0 hprobability1 false).toReal =
      1 - probability := by
  simp [booleanCoin, PMF.ofFintype_apply,
    ENNReal.toReal_ofReal (sub_nonneg.mpr hprobability1)]

/-- Scalar hazards are determined by their stopping-probability functions. -/
theorem ScalarHazard.eq_of_stop_eq (first second : ScalarHazard)
    (hstop : first.stop = second.stop) : first = second := by
  cases first with
  | mk firstStop firstNonneg firstLeOne =>
      cases second with
      | mk secondStop secondNonneg secondLeOne =>
          simp only at hstop
          cases hstop
          rfl

/-- Encode a scalar hazard as a Boolean coin hazard. -/
def ScalarHazard.toBoolean (hazard : ScalarHazard) : BooleanHazard :=
  fun time => booleanCoin (hazard.stop time)
    (hazard.stop_nonneg time) (hazard.stop_le_one time)

@[simp] theorem ScalarHazard.toScalar_toBoolean (hazard : ScalarHazard) :
    BooleanHazard.toScalar hazard.toBoolean = hazard := by
  apply ScalarHazard.eq_of_stop_eq
  funext time
  exact booleanCoin_true_toReal (hazard.stop time)
    (hazard.stop_nonneg time) (hazard.stop_le_one time)

/-- A Boolean presentation of the convex mixture hazard. -/
def BooleanHazard.convexMix
    (source target : BooleanHazard) (lambda : ℝ)
    (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) : BooleanHazard :=
  (ScalarHazard.convexMix source.toScalar target.toScalar lambda
    hlambda0 hlambda1).toBoolean

@[simp] theorem BooleanHazard.toScalar_convexMix
    (source target : BooleanHazard) (lambda : ℝ)
    (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) :
    (BooleanHazard.convexMix source target lambda hlambda0 hlambda1).toScalar =
      ScalarHazard.convexMix source.toScalar target.toScalar lambda
        hlambda0 hlambda1 := by
  simp [BooleanHazard.convexMix]

/-- The Bernoulli coin used to present a convex mixture as a PMF bind. -/
def mixtureCoin (lambda : ℝ) (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) :
    PMF Bool :=
  booleanCoin lambda hlambda0 hlambda1

@[simp] theorem mixtureCoin_true_toReal
    (lambda : ℝ) (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) :
    (mixtureCoin lambda hlambda0 hlambda1 true).toReal = lambda := by
  simp [mixtureCoin]

@[simp] theorem mixtureCoin_false_toReal
    (lambda : ℝ) (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) :
    (mixtureCoin lambda hlambda0 hlambda1 false).toReal = 1 - lambda := by
  have hsum := continue_add_stop
    (fun _ => mixtureCoin lambda hlambda0 hlambda1) 0
  change (mixtureCoin lambda hlambda0 hlambda1 false).toReal +
      (mixtureCoin lambda hlambda0 hlambda1 true).toReal = 1 at hsum
  rw [mixtureCoin_true_toReal] at hsum
  linarith

/-- The stopping law of the reconstructed hazard is exactly the convex PMF
mixture of the two input stopping laws. -/
theorem ScalarHazard.stoppingLaw_convexMix
    (source target : ScalarHazard) (lambda : ℝ)
    (hlambda0 : 0 ≤ lambda) (hlambda1 : lambda ≤ 1) :
    (ScalarHazard.convexMix source target lambda hlambda0 hlambda1).stoppingLaw =
      (mixtureCoin lambda hlambda0 hlambda1).bind
        (fun choose => if choose then target.stoppingLaw else source.stoppingLaw) := by
  apply Math.ProbabilityMassFunction.eq_of_forall_toReal_eq
  intro choice
  rw [Math.ProbabilityMassFunction.bind_apply_toReal_eq_sum]
  rw [Fintype.sum_bool]
  cases choice with
  | none =>
      simp [ScalarHazard.convexMix_neverMass source target lambda
        hlambda0 hlambda1, add_comm]
  | some time =>
      simp [ScalarHazard.convexMix_stopMass source target lambda
        hlambda0 hlambda1 time, ScalarHazard.mixedStopMass, add_comm]

end Math.Probability.DiscreteHazard
