/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import Mathlib.Probability.ProbabilityMassFunction.Integrals
import MathUE.Probability.HarmonicRecurrentCoreBound

/-!
# Finite path-law adapters

An infinite path law is often specified by its finite-coordinate cylinders,
whereas the finite probabilistic accounts in `MathUE` use the recursively
defined PMFs `adaptiveHistoryLaw`.  This file gives the generic bridge between
the two presentations on a finite observation alphabet.

The final result specializes the bridge to space-time Markov variation.  A
prefix containing `horizon + 1` states carries exactly `horizon` increments,
so its `ℝ≥0∞` path integral is the `ENNReal.ofReal` image of
`finiteExpectedSpaceTimeMarkovVariation`.
-/

namespace Math.Probability

open MeasureTheory
open scoped BigOperators ENNReal

noncomputable section

variable {Ω Path : Type*}

/-- Restrict a path observation to its first `horizon` coordinates. -/
def finitePathPrefix
    (observe : Path → ℕ → Ω) (horizon : ℕ) (path : Path) : Fin horizon → Ω :=
  fun time => observe path time

/-- An infinite law has the finite marginals generated by an adaptive PMF
recursion.  Measurability is retained explicitly because the source path
space need not be discrete. -/
structure HasAdaptiveFiniteMarginals
    [MeasurableSpace Path] [MeasurableSpace Ω]
    (law : Measure Path) (observe : Path → ℕ → Ω)
    (step : ∀ n, (Fin n → Ω) → PMF Ω) : Prop where
  measurable_prefix : ∀ horizon, Measurable (finitePathPrefix observe horizon)
  prefixLaw : ∀ horizon,
    law.map (finitePathPrefix observe horizon) =
      (adaptiveHistoryLaw step horizon).toMeasure

/-- Exact finite-cylinder masses identify the corresponding finite marginal
with the production adaptive-history PMF. -/
theorem hasAdaptiveFiniteMarginals_of_cylinder
    [Fintype Ω] [MeasurableSpace Path] [MeasurableSpace Ω]
    [MeasurableSingletonClass Ω]
    (law : Measure Path) (observe : Path → ℕ → Ω)
    (step : ∀ n, (Fin n → Ω) → PMF Ω)
    (measurable_prefix : ∀ horizon,
      Measurable (finitePathPrefix observe horizon))
    (cylinder : ∀ horizon (history : Fin horizon → Ω),
      law {path | finitePathPrefix observe horizon path = history} =
        adaptiveHistoryLaw step horizon history) :
    HasAdaptiveFiniteMarginals law observe step := by
  refine ⟨measurable_prefix, ?_⟩
  intro horizon
  apply Measure.ext_of_singleton
  intro history
  rw [Measure.map_apply (measurable_prefix horizon)
    (measurableSet_singleton history)]
  rw [PMF.toMeasure_apply_singleton _ _ (measurableSet_singleton history)]
  exact cylinder horizon history

namespace HasAdaptiveFiniteMarginals

/-- Integrating a nonnegative finite-prefix observable under the infinite
law is the `ENNReal.ofReal` image of its expectation under the matching PMF. -/
theorem lintegral_ofReal_comp_prefix_eq_ofReal_expect
    [Fintype Ω] [MeasurableSpace Path] [MeasurableSpace Ω]
    [MeasurableSingletonClass Ω]
    {law : Measure Path} {observe : Path → ℕ → Ω}
    {step : ∀ n, (Fin n → Ω) → PMF Ω}
    (marginals : HasAdaptiveFiniteMarginals law observe step)
    (horizon : ℕ) (observable : (Fin horizon → Ω) → ℝ)
    (observable_nonneg : ∀ history, 0 ≤ observable history) :
    (∫⁻ path,
        ENNReal.ofReal
          (observable (finitePathPrefix observe horizon path)) ∂law) =
      ENNReal.ofReal
        (expect (adaptiveHistoryLaw step horizon) observable) := by
  let projection := finitePathPrefix observe horizon
  let pmf := adaptiveHistoryLaw step horizon
  have hmeasurable : Measurable (fun history => ENNReal.ofReal (observable history)) :=
    measurable_of_finite _
  calc
    (∫⁻ path, ENNReal.ofReal (observable (projection path)) ∂law) =
        ∫⁻ history, ENNReal.ofReal (observable history) ∂law.map projection := by
      exact (lintegral_map hmeasurable (marginals.measurable_prefix horizon)).symm
    _ = ∫⁻ history, ENNReal.ofReal (observable history) ∂pmf.toMeasure := by
      rw [marginals.prefixLaw horizon]
    _ = ENNReal.ofReal (∫ history, observable history ∂pmf.toMeasure) := by
      rw [ofReal_integral_eq_lintegral_ofReal Integrable.of_finite
        (ae_of_all _ observable_nonneg)]
    _ = ENNReal.ofReal (expect pmf observable) := by
      congr 1
      rw [PMF.integral_eq_sum, expect_eq_sum]
      simp only [smul_eq_mul]

end HasAdaptiveFiniteMarginals

/-- The finite-state Markov recursion for a possibly time-dependent kernel. -/
def inhomogeneousMarkovStep
    (initial : Ω) (transition : ℕ → Ω → PMF Ω) :
    ∀ n, (Fin n → Ω) → PMF Ω
  | 0, _ => PMF.pure initial
  | n + 1, history => transition n (history (Fin.last n))

@[simp] theorem inhomogeneousMarkovStep_zero
    (initial : Ω) (transition : ℕ → Ω → PMF Ω)
    (history : Fin 0 → Ω) :
    inhomogeneousMarkovStep initial transition 0 history = PMF.pure initial := rfl

@[simp] theorem inhomogeneousMarkovStep_succ
    (initial : Ω) (transition : ℕ → Ω → PMF Ω)
    (n : ℕ) (history : Fin (n + 1) → Ω) :
    inhomogeneousMarkovStep initial transition (n + 1) history =
      transition n (history (Fin.last n)) := rfl

/-- Pointwise recursion for the adaptive finite-history law. -/
theorem adaptiveHistoryLaw_succ_apply
    (step : ∀ n, (Fin n → Ω) → PMF Ω)
    (n : ℕ) (history : Fin (n + 1) → Ω) :
    adaptiveHistoryLaw step (n + 1) history =
      adaptiveHistoryLaw step n (Fin.init history) *
        step n (Fin.init history) (history (Fin.last n)) := by
  classical
  rw [adaptiveHistoryLaw_succ, PMF.bind_apply]
  rw [tsum_eq_single (Fin.init history)]
  · rw [PMF.map_apply, tsum_eq_single (history (Fin.last n))]
    · simp
    · intro other hother
      rw [if_neg]
      intro heq
      apply hother
      simpa using (congrArg (fun extended => extended (Fin.last n)) heq).symm
  · intro other hother
    have hmap : (step n other).map (Fin.snoc other) history = 0 := by
      rw [PMF.map_apply]
      rw [ENNReal.tsum_eq_zero]
      intro successor
      rw [if_neg]
      intro heq
      apply hother
      have hinit := congrArg Fin.init heq
      simpa using hinit.symm
    rw [hmap, mul_zero]

/-- The point mass of a finite Markov-history PMF is its initial point mass
times the displayed transition product. -/
theorem adaptiveHistoryLaw_inhomogeneousMarkovStep_apply
    [Fintype Ω] (initial : Ω) (transition : ℕ → Ω → PMF Ω) :
    ∀ (horizon : ℕ) (history : Fin (horizon + 1) → Ω),
      adaptiveHistoryLaw (inhomogeneousMarkovStep initial transition)
          (horizon + 1) history =
        (PMF.pure initial) (history 0) *
          ∏ time : Fin horizon,
            transition time (history time.castSucc) (history time.succ) := by
  intro horizon
  induction horizon with
  | zero =>
      intro history
      rw [adaptiveHistoryLaw_succ_apply]
      have hempty : Fin.init history = fun i => Fin.elim0 i := Subsingleton.elim _ _
      simp [hempty]
  | succ horizon inductionHypothesis =>
      intro history
      rw [adaptiveHistoryLaw_succ_apply]
      rw [inductionHypothesis]
      rw [Fin.prod_univ_castSucc]
      simp only [inhomogeneousMarkovStep_succ]
      simp only [Fin.init, Fin.succ_castSucc, Fin.succ_last,
        Fin.castSucc_zero, Fin.val_castSucc, Fin.val_last]
      ring

/-- If the displayed finite history starts at the prescribed state, its PMF
mass is exactly the transition product. -/
theorem adaptiveHistoryLaw_inhomogeneousMarkovStep_apply_of_start
    [Fintype Ω] (initial : Ω) (transition : ℕ → Ω → PMF Ω)
    (horizon : ℕ) (history : Fin (horizon + 1) → Ω)
    (starts : history 0 = initial) :
    adaptiveHistoryLaw (inhomogeneousMarkovStep initial transition)
        (horizon + 1) history =
      ∏ time : Fin horizon,
        transition time (history time.castSucc) (history time.succ) := by
  rw [adaptiveHistoryLaw_inhomogeneousMarkovStep_apply]
  simp [starts]

/-- A displayed finite history with the wrong initial state has zero PMF
mass. -/
theorem adaptiveHistoryLaw_inhomogeneousMarkovStep_apply_of_ne_start
    [Fintype Ω] (initial : Ω) (transition : ℕ → Ω → PMF Ω)
    (horizon : ℕ) (history : Fin (horizon + 1) → Ω)
    (starts : history 0 ≠ initial) :
    adaptiveHistoryLaw (inhomogeneousMarkovStep initial transition)
        (horizon + 1) history = 0 := by
  rw [adaptiveHistoryLaw_inhomogeneousMarkovStep_apply]
  simp [starts]

/-- Real variation carried by a finite state prefix. -/
def finiteStatePathVariation
    (value : Ω → ℕ → ℝ) (horizon : ℕ)
    (history : Fin (horizon + 1) → Ω) : ℝ :=
  ∑ time : Fin horizon,
    |value (history time.succ) (time + 1) -
      value (history time.castSucc) time|

theorem finiteStatePathVariation_nonneg
    (value : Ω → ℕ → ℝ) (horizon : ℕ)
    (history : Fin (horizon + 1) → Ω) :
    0 ≤ finiteStatePathVariation value horizon history :=
  Finset.sum_nonneg fun _ _ => abs_nonneg _

/-- The production predictable-score recursion reads exactly the finite
state-prefix variation. -/
theorem predictableScoreSum_abs_spaceTimeMarkovScore_eq_finiteStatePathVariation
    (value : Ω → ℕ → ℝ) :
    ∀ (horizon : ℕ) (history : Fin (horizon + 1) → Ω),
      predictableScoreSum
          (fun n previous state => |spaceTimeMarkovScore value n previous state|)
          (horizon + 1) history =
        finiteStatePathVariation value horizon history := by
  intro horizon
  induction horizon with
  | zero =>
      intro history
      simp [predictableScoreSum, finiteStatePathVariation]
  | succ horizon inductionHypothesis =>
      intro history
      rw [predictableScoreSum]
      rw [inductionHypothesis]
      unfold finiteStatePathVariation
      rw [Fin.sum_univ_castSucc]
      simp only [spaceTimeMarkovScore_succ]
      simp only [Fin.init, Fin.succ_castSucc, Fin.succ_last]
      congr 1

/-- The finite production account is the expectation of the corresponding
finite-prefix variation. -/
theorem finiteExpectedSpaceTimeMarkovVariation_eq_expect_finiteStatePathVariation
    [Fintype Ω] (initial : Ω) (kernel : Ω → PMF Ω)
    (value : Ω → ℕ → ℝ) (horizon : ℕ) :
    finiteExpectedSpaceTimeMarkovVariation initial kernel value horizon =
      expect
        (adaptiveHistoryLaw
          (homogeneousMarkovStep initial kernel) (horizon + 1))
        (finiteStatePathVariation value horizon) := by
  rw [finiteExpectedSpaceTimeMarkovVariation]
  rw [expectedDecisionVariation_eq_expect_predictableScoreSum_abs]
  apply congrArg (expect
    (adaptiveHistoryLaw (homogeneousMarkovStep initial kernel) (horizon + 1)))
  funext history
  exact
    predictableScoreSum_abs_spaceTimeMarkovScore_eq_finiteStatePathVariation
      value horizon history

/-- The one-step space-time variation score read from an infinite path. -/
def spaceTimePathENNVariationScore
    (observe : Path → ℕ → Ω) (value : Ω → ℕ → ℝ)
    (time : ℕ) (path : Path) : ENNReal :=
  ENNReal.ofReal
    |value (observe path (time + 1)) (time + 1) -
      value (observe path time) time|

/-- Matching all finite marginals identifies finite path-law variation with
the `ENNReal.ofReal` image of the production finite PMF account. -/
theorem finiteExpectedENNVariation_spaceTime_eq_ofReal
    [Fintype Ω] [MeasurableSpace Path] [MeasurableSpace Ω]
    [MeasurableSingletonClass Ω]
    (law : Measure Path) (observe : Path → ℕ → Ω)
    (initial : Ω) (kernel : Ω → PMF Ω) (value : Ω → ℕ → ℝ)
    (marginals : HasAdaptiveFiniteMarginals law observe
      (homogeneousMarkovStep initial kernel))
    (horizon : ℕ) :
    finiteExpectedENNVariation law
        (spaceTimePathENNVariationScore observe value) horizon =
      ENNReal.ofReal
        (finiteExpectedSpaceTimeMarkovVariation
          initial kernel value horizon) := by
  rw [finiteExpectedENNVariation]
  have hpointwise :
      (fun path => ∑ time ∈ Finset.range horizon,
          spaceTimePathENNVariationScore observe value time path) =
        fun path => ENNReal.ofReal
          (finiteStatePathVariation value horizon
            (finitePathPrefix observe (horizon + 1) path)) := by
    funext path
    change
      (∑ time ∈ Finset.range horizon,
        ENNReal.ofReal
          |value (observe path (time + 1)) (time + 1) -
            value (observe path time) time|) =
        ENNReal.ofReal
          (∑ time : Fin horizon,
            |value (observe path (time + 1)) (time + 1) -
              value (observe path time) time|)
    calc
      (∑ time ∈ Finset.range horizon,
          ENNReal.ofReal
            |value (observe path (time + 1)) (time + 1) -
              value (observe path time) time|) =
          ∑ time : Fin horizon,
            ENNReal.ofReal
              |value (observe path (time + 1)) (time + 1) -
                value (observe path time) time| := by
        rw [Finset.sum_range]
      _ = ENNReal.ofReal
          (∑ time : Fin horizon,
            |value (observe path (time + 1)) (time + 1) -
              value (observe path time) time|) := by
        rw [ENNReal.ofReal_sum_of_nonneg]
        exact fun _ _ => abs_nonneg _
  rw [hpointwise]
  rw [marginals.lintegral_ofReal_comp_prefix_eq_ofReal_expect
    (horizon + 1) (finiteStatePathVariation value horizon)
    (finiteStatePathVariation_nonneg value horizon)]
  rw [← finiteExpectedSpaceTimeMarkovVariation_eq_expect_finiteStatePathVariation]

/-- Every one-step path variation is measurable once the corresponding
finite prefix projection is measurable. -/
theorem HasAdaptiveFiniteMarginals.measurable_spaceTimePathENNVariationScore
    [Fintype Ω] [MeasurableSpace Path] [MeasurableSpace Ω]
    [MeasurableSingletonClass Ω]
    {law : Measure Path} {observe : Path → ℕ → Ω}
    {step : ∀ n, (Fin n → Ω) → PMF Ω}
    (marginals : HasAdaptiveFiniteMarginals law observe step)
    (value : Ω → ℕ → ℝ) (time : ℕ) :
    Measurable (spaceTimePathENNVariationScore observe value time) := by
  let observable : (Fin (time + 2) → Ω) → ENNReal := fun history =>
    ENNReal.ofReal
      |value (history ⟨time + 1, by omega⟩) (time + 1) -
        value (history ⟨time, by omega⟩) time|
  have hfactor :
      spaceTimePathENNVariationScore observe value time =
        observable ∘ finitePathPrefix observe (time + 2) := by
    rfl
  rw [hfactor]
  exact (measurable_of_finite observable).comp
    (marginals.measurable_prefix (time + 2))

/-- Uniform finite production bounds pass through the marginal adapter and
monotone convergence to the infinite path-law variation. -/
theorem infiniteExpectedENNVariation_spaceTime_le_of_finite
    [Fintype Ω] [MeasurableSpace Path] [MeasurableSpace Ω]
    [MeasurableSingletonClass Ω]
    (law : Measure Path) (observe : Path → ℕ → Ω)
    (initial : Ω) (kernel : Ω → PMF Ω) (value : Ω → ℕ → ℝ)
    (marginals : HasAdaptiveFiniteMarginals law observe
      (homogeneousMarkovStep initial kernel))
    (bound : ENNReal)
    (finite_le : ∀ horizon,
      ENNReal.ofReal
          (finiteExpectedSpaceTimeMarkovVariation
            initial kernel value horizon) ≤ bound) :
    infiniteExpectedENNVariation law
        (spaceTimePathENNVariationScore observe value) ≤ bound := by
  apply infiniteExpectedENNVariation_le_of_finite law
    (spaceTimePathENNVariationScore observe value)
    (fun time =>
      (marginals.measurable_spaceTimePathENNVariationScore value time).aemeasurable)
    bound
  intro horizon
  rw [finiteExpectedENNVariation_spaceTime_eq_ofReal
    law observe initial kernel value marginals horizon]
  exact finite_le horizon

/-- A finite homogeneous Markov path law has finite total expected variation
for every unit-interval backward-harmonic value orbit.

The bound is kernel-dependent. This theorem does not assert Simon's sharper
state-cardinality estimate. -/
theorem infiniteExpectedENNVariation_spaceTime_ne_top_of_backwardHarmonic
    [Fintype Ω] [Nonempty Ω] [DecidableEq Ω]
    [MeasurableSpace Path] [MeasurableSpace Ω]
    [MeasurableSingletonClass Ω]
    (law : Measure Path) (observe : Path → ℕ → Ω)
    (initial : Ω) (kernel : Ω → PMF Ω) (value : Ω → ℕ → ℝ)
    (marginals : HasAdaptiveFiniteMarginals law observe
      (homogeneousMarkovStep initial kernel))
    (harmonic : IsUnitIntervalBackwardMarkovHarmonic kernel value) :
    infiniteExpectedENNVariation law
        (spaceTimePathENNVariationScore observe value) ≠ ⊤ := by
  obtain ⟨bound, _bound_nonneg, finite_le⟩ :=
    exists_kernelDependent_finiteExpectedVariation_bound kernel
  have total_le :
      infiniteExpectedENNVariation law
          (spaceTimePathENNVariationScore observe value) ≤
        ENNReal.ofReal bound := by
    apply infiniteExpectedENNVariation_spaceTime_le_of_finite
      law observe initial kernel value marginals
    intro horizon
    exact ENNReal.ofReal_le_ofReal (finite_le initial value harmonic horizon)
  exact ne_top_of_le_ne_top ENNReal.ofReal_ne_top total_le

end

end Math.Probability
