/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import MathUE.Probability.MarkovOccupation
import MathUE.Probability.RealizedAccountDeflation

/-!
# Bounded accounts from harmonic state potentials

A state potential gives a canonical account along every state path: its
balance at time `t` is the potential of the current state.  If the potential
is harmonic for a baseline kernel, the observed successor-versus-baseline
discrepancy is exactly the increment of that account.  This statement is
pathwise, so it remains valid for histories generated by arbitrary adaptive
comparison kernels.

Finite linear combinations use exactly the same coefficients on potentials,
observed charges, and accounts.  This is the accounting fact needed when a
processed direction has already been represented by primitive harmonic
directions.

The final one-state example records the sharp boundary.  Harmonicity cannot
identify an unrelated strategic charge with the state-potential increment:
on a one-state path every state-potential account is constant, so it cannot
realize the recurring charge `1`.
-/

namespace Math.Probability

noncomputable section

variable {Ω : Type*}

/-- The account obtained by evaluating a state potential along a path. -/
def statePotentialAccount
    (potential : Ω → ℝ) (path : ℕ → Ω) (t : ℕ) : ℝ :=
  potential (path t)

/-- The one-step increment of the state-potential account. -/
def statePotentialIncrement
    (potential : Ω → ℝ) (path : ℕ → Ω) (t : ℕ) : ℝ :=
  potential (path (t + 1)) - potential (path t)

/-- State-potential increments are realized by the corresponding account. -/
theorem statePotentialIncrement_isRealizedByAccount
    (potential : Ω → ℝ) (path : ℕ → Ω) :
    IsRealizedByAccount
      (statePotentialIncrement potential path)
      (statePotentialAccount potential path) := by
  intro t
  rfl

/-- A convenient finite bound for a state potential. -/
def finiteStatePotentialBound
    [Fintype Ω] (potential : Ω → ℝ) : ℝ :=
  ∑ state, |potential state|

/-- On a finite state space the canonical account is uniformly bounded. -/
theorem abs_statePotentialAccount_le_finiteStatePotentialBound
    [Fintype Ω]
    (potential : Ω → ℝ) (path : ℕ → Ω) (t : ℕ) :
    |statePotentialAccount potential path t| ≤
      finiteStatePotentialBound potential := by
  change |potential (path t)| ≤ ∑ state, |potential state|
  simpa using
    (Finset.single_le_sum
      (s := Finset.univ)
      (f := fun state => |potential state|)
      (fun state _ => abs_nonneg (potential state))
      (Finset.mem_univ (path t)))

/-- A harmonic potential turns the observed Markov discrepancy into the
exact increment of its state-potential account. -/
theorem markovPotentialDiscrepancy_eq_statePotentialIncrement_of_harmonic
    (baseline : Ω → PMF Ω) (potential : Ω → ℝ)
    (harmonic : ∀ state,
      expect (baseline state) potential = potential state)
    (path : ℕ → Ω) (t : ℕ) :
    markovPotentialDiscrepancy
        baseline potential (path t) (path (t + 1)) =
      statePotentialIncrement potential path t := by
  rw [markovPotentialDiscrepancy, statePotentialIncrement,
    harmonic (path t)]

/-- Consequently the observed discrepancies of a harmonic potential form a
bounded realized account along every path, including every adaptively
generated path. -/
theorem harmonicMarkovDiscrepancy_isRealizedByBoundedAccount
    [Fintype Ω]
    (baseline : Ω → PMF Ω) (potential : Ω → ℝ)
    (harmonic : ∀ state,
      expect (baseline state) potential = potential state)
    (path : ℕ → Ω) :
    (∀ t,
        |statePotentialAccount potential path t| ≤
          finiteStatePotentialBound potential) ∧
      IsRealizedByAccount
        (fun t =>
          markovPotentialDiscrepancy
            baseline potential (path t) (path (t + 1)))
        (statePotentialAccount potential path) := by
  constructor
  · exact
      abs_statePotentialAccount_le_finiteStatePotentialBound potential path
  · intro t
    change
      markovPotentialDiscrepancy
          baseline potential (path t) (path (t + 1)) =
        statePotentialAccount potential path (t + 1) -
          statePotentialAccount potential path t
    rw [
      markovPotentialDiscrepancy_eq_statePotentialIncrement_of_harmonic
        baseline potential harmonic path t]
    rfl

/-- The conditional mean of the same observed account increment is the
comparison-versus-baseline drift, with no change of coefficients. -/
theorem expect_statePotentialIncrement_eq_comparison_sub_baseline
    [Finite Ω]
    (baseline comparison : PMF Ω) (potential : Ω → ℝ)
    (source : Ω) :
    expect comparison
        (fun successor =>
          markovPotentialDiscrepancy
            (fun _ => baseline) potential source successor) =
      expect comparison potential - expect baseline potential := by
  simp only [markovPotentialDiscrepancy]
  rw [expect_sub, expect_const]

/-- Under harmonicity, the conditional expectation of the actual account
increment is exactly the predictable comparison-versus-baseline drift. -/
theorem expect_statePotentialIncrement_eq_comparisonDrift_of_harmonic
    [Finite Ω]
    (baseline : Ω → PMF Ω) (comparison : PMF Ω)
    (potential : Ω → ℝ)
    (harmonic : ∀ state,
      expect (baseline state) potential = potential state)
    (source : Ω) :
    expect comparison
        (fun successor =>
          potential successor - potential source) =
      expect comparison potential -
        expect (baseline source) potential := by
  rw [harmonic source, expect_sub, expect_const]

/-- Evaluation commutes with a finite linear combination using the original
coefficients. -/
theorem statePotentialAccount_finset_linearCombination
    {J : Type*} [Fintype J]
    (coefficient : J → ℝ) (potential : J → Ω → ℝ)
    (path : ℕ → Ω) (t : ℕ) :
    statePotentialAccount
        (fun state => ∑ j, coefficient j * potential j state)
        path t =
      ∑ j, coefficient j *
        statePotentialAccount (potential j) path t := by
  rfl

/-- The observed charge also commutes with the same finite linear
combination. -/
theorem statePotentialIncrement_finset_linearCombination
    {J : Type*} [Fintype J]
    (coefficient : J → ℝ) (potential : J → Ω → ℝ)
    (path : ℕ → Ω) (t : ℕ) :
    statePotentialIncrement
        (fun state => ∑ j, coefficient j * potential j state)
        path t =
      ∑ j, coefficient j *
        statePotentialIncrement (potential j) path t := by
  simp only [statePotentialIncrement, Finset.sum_sub_distrib, mul_sub]

namespace HarmonicStateAccountCounterexample

/-- The unique path on a one-state space. -/
def singletonPath : ℕ → PUnit := fun _ => PUnit.unit

/-- The unique one-state Markov kernel. -/
def singletonKernel : PUnit → PMF PUnit :=
  fun _ => PMF.pure PUnit.unit

/-- Every potential is harmonic under the unique one-state kernel. -/
theorem singleton_harmonic (potential : PUnit → ℝ) :
    ∀ state,
      expect (singletonKernel state) potential = potential state := by
  intro state
  cases state
  simp [singletonKernel]

/-- Every state-potential account on the singleton path has zero
increment. -/
theorem singleton_statePotentialIncrement_eq_zero
    (potential : PUnit → ℝ) (t : ℕ) :
    statePotentialIncrement potential singletonPath t = 0 := by
  simp [statePotentialIncrement, singletonPath]

/-- Therefore the recurring charge `1` cannot be identified with a
state-potential increment, even though every potential on the singleton
kernel is harmonic. -/
theorem not_exists_statePotential_realizing_constant_one :
    ¬ ∃ potential : PUnit → ℝ,
      ∀ t,
        (1 : ℝ) =
          statePotentialIncrement potential singletonPath t := by
  rintro ⟨potential, realizes⟩
  have hone := realizes 0
  rw [singleton_statePotentialIncrement_eq_zero] at hone
  norm_num at hone

/-- Even after spelling the desired charge as an endpoint-kernel
discrepancy, harmonicity cannot identify the unrelated recurring charge
`1`. -/
theorem not_exists_harmonicPotential_identifying_constant_one :
    ¬ ∃ potential : PUnit → ℝ,
      (∀ state,
        expect (singletonKernel state) potential = potential state) ∧
      ∀ t,
        (1 : ℝ) =
          markovPotentialDiscrepancy singletonKernel potential
            (singletonPath t) (singletonPath (t + 1)) := by
  rintro ⟨potential, harmonic, identifies⟩
  have hone := identifies 0
  rw [
    markovPotentialDiscrepancy_eq_statePotentialIncrement_of_harmonic
      singletonKernel potential harmonic singletonPath 0,
    singleton_statePotentialIncrement_eq_zero] at hone
  norm_num at hone

end HarmonicStateAccountCounterexample

end

end Math.Probability
