/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import MathUE.Probability.MarkovOccupation
import MathUE.Probability.DecisionVariationMaximalInequality
import MathUE.Probability.RealizedAccountDeflation

/-!
# Bounded accounts from harmonic state potentials

A state potential gives a canonical account along every state path: its
balance at time `t` is the potential of the current state.  If the potential
is harmonic for a baseline kernel, the observed successor-versus-baseline
discrepancy is exactly the increment of that account.  This statement is
pathwise, so it remains valid for histories generated by arbitrary adaptive
comparison kernels.

Finite linear combinations use exactly the same coefficients on potentials,
observed charges, and accounts.  This is the accounting fact needed when a
processed direction has already been represented by primitive harmonic
directions.

The final one-state example records the sharp boundary.  Harmonicity cannot
identify an unrelated strategic charge with the state-potential increment:
on a one-state path every state-potential account is constant, so it cannot
realize the recurring charge `1`.

The finite-horizon extension below is a conditional variation core for a
finite homogeneous Markov chain.  A supplied statewise escape/Poisson
potential certificate gives the sharp cardinality bound on expected
space-time variation.  This is the finite accounting step relevant to
Simon's Lemma 2; the escape/Poisson certificate itself and the infinite
adapter from Simon's return argument are not produced here, so that lemma
remains open.
-/

namespace Math.Probability

noncomputable section

variable {Ω : Type*}

/-- The account obtained by evaluating a state potential along a path. -/
def statePotentialAccount
    (potential : Ω → ℝ) (path : ℕ → Ω) (t : ℕ) : ℝ :=
  potential (path t)

/-- The one-step increment of the state-potential account. -/
def statePotentialIncrement
    (potential : Ω → ℝ) (path : ℕ → Ω) (t : ℕ) : ℝ :=
  potential (path (t + 1)) - potential (path t)

/-- State-potential increments are realized by the corresponding account. -/
theorem statePotentialIncrement_isRealizedByAccount
    (potential : Ω → ℝ) (path : ℕ → Ω) :
    IsRealizedByAccount
      (statePotentialIncrement potential path)
      (statePotentialAccount potential path) := by
  intro t
  rfl

/-- A convenient finite bound for a state potential. -/
def finiteStatePotentialBound
    [Fintype Ω] (potential : Ω → ℝ) : ℝ :=
  ∑ state, |potential state|

/-- On a finite state space the canonical account is uniformly bounded. -/
theorem abs_statePotentialAccount_le_finiteStatePotentialBound
    [Fintype Ω]
    (potential : Ω → ℝ) (path : ℕ → Ω) (t : ℕ) :
    |statePotentialAccount potential path t| ≤
      finiteStatePotentialBound potential := by
  change |potential (path t)| ≤ ∑ state, |potential state|
  simpa using
    (Finset.single_le_sum
      (s := Finset.univ)
      (f := fun state => |potential state|)
      (fun state _ => abs_nonneg (potential state))
      (Finset.mem_univ (path t)))

/-- A harmonic potential turns the observed Markov discrepancy into the
exact increment of its state-potential account. -/
theorem markovPotentialDiscrepancy_eq_statePotentialIncrement_of_harmonic
    (baseline : Ω → PMF Ω) (potential : Ω → ℝ)
    (harmonic : ∀ state,
      expect (baseline state) potential = potential state)
    (path : ℕ → Ω) (t : ℕ) :
    markovPotentialDiscrepancy
        baseline potential (path t) (path (t + 1)) =
      statePotentialIncrement potential path t := by
  rw [markovPotentialDiscrepancy, statePotentialIncrement,
    harmonic (path t)]

/-- Consequently the observed discrepancies of a harmonic potential form a
bounded realized account along every path, including every adaptively
generated path. -/
theorem harmonicMarkovDiscrepancy_isRealizedByBoundedAccount
    [Fintype Ω]
    (baseline : Ω → PMF Ω) (potential : Ω → ℝ)
    (harmonic : ∀ state,
      expect (baseline state) potential = potential state)
    (path : ℕ → Ω) :
    (∀ t,
        |statePotentialAccount potential path t| ≤
          finiteStatePotentialBound potential) ∧
      IsRealizedByAccount
        (fun t =>
          markovPotentialDiscrepancy
            baseline potential (path t) (path (t + 1)))
        (statePotentialAccount potential path) := by
  constructor
  · exact
      abs_statePotentialAccount_le_finiteStatePotentialBound potential path
  · intro t
    change
      markovPotentialDiscrepancy
          baseline potential (path t) (path (t + 1)) =
        statePotentialAccount potential path (t + 1) -
          statePotentialAccount potential path t
    rw [
      markovPotentialDiscrepancy_eq_statePotentialIncrement_of_harmonic
        baseline potential harmonic path t]
    rfl

/-- The conditional mean of the same observed account increment is the
comparison-versus-baseline drift, with no change of coefficients. -/
theorem expect_statePotentialIncrement_eq_comparison_sub_baseline
    [Finite Ω]
    (baseline comparison : PMF Ω) (potential : Ω → ℝ)
    (source : Ω) :
    expect comparison
        (fun successor =>
          markovPotentialDiscrepancy
            (fun _ => baseline) potential source successor) =
      expect comparison potential - expect baseline potential := by
  simp only [markovPotentialDiscrepancy]
  rw [expect_sub, expect_const]

/-- Under harmonicity, the conditional expectation of the actual account
increment is exactly the predictable comparison-versus-baseline drift. -/
theorem expect_statePotentialIncrement_eq_comparisonDrift_of_harmonic
    [Finite Ω]
    (baseline : Ω → PMF Ω) (comparison : PMF Ω)
    (potential : Ω → ℝ)
    (harmonic : ∀ state,
      expect (baseline state) potential = potential state)
    (source : Ω) :
    expect comparison
        (fun successor =>
          potential successor - potential source) =
      expect comparison potential -
        expect (baseline source) potential := by
  rw [harmonic source, expect_sub, expect_const]

/-- Evaluation commutes with a finite linear combination using the original
coefficients. -/
theorem statePotentialAccount_finset_linearCombination
    {J : Type*} [Fintype J]
    (coefficient : J → ℝ) (potential : J → Ω → ℝ)
    (path : ℕ → Ω) (t : ℕ) :
    statePotentialAccount
        (fun state => ∑ j, coefficient j * potential j state)
        path t =
      ∑ j, coefficient j *
        statePotentialAccount (potential j) path t := by
  rfl

/-- The observed charge also commutes with the same finite linear
combination. -/
theorem statePotentialIncrement_finset_linearCombination
    {J : Type*} [Fintype J]
    (coefficient : J → ℝ) (potential : J → Ω → ℝ)
    (path : ℕ → Ω) (t : ℕ) :
    statePotentialIncrement
        (fun state => ∑ j, coefficient j * potential j state)
        path t =
      ∑ j, coefficient j *
        statePotentialIncrement (potential j) path t := by
  simp only [statePotentialIncrement, Finset.sum_sub_distrib, mul_sub]

/-! ## Conditional finite-horizon variation for a homogeneous Markov chain

The definitions and centering identity below are unconditional.  The
cardinality bound is conditional on
`HasStatewiseMarkovVariationBudget`, which supplies the statewise escape
majorant and its Poisson drift.  It is not a construction of that certificate
from bounded harmonicity, nor an infinite-horizon or return-probability
adapter for Simon's Lemma 2. -/

/-- The history-dependent presentation of a time-homogeneous Markov kernel. -/
def homogeneousMarkovStep
    (initial : Ω) (kernel : Ω → PMF Ω) :
    ∀ n, (Fin n → Ω) → PMF Ω :=
  adaptiveMarkovStep initial
    (fun n history ↦ kernel (history (Fin.last n)))

@[simp] theorem homogeneousMarkovStep_zero
    (initial : Ω) (kernel : Ω → PMF Ω)
    (history : Fin 0 → Ω) :
    homogeneousMarkovStep initial kernel 0 history = PMF.pure initial := rfl

@[simp] theorem homogeneousMarkovStep_succ
    (initial : Ω) (kernel : Ω → PMF Ω)
    (n : ℕ) (history : Fin (n + 1) → Ω) :
    homogeneousMarkovStep initial kernel (n + 1) history =
      kernel (history (Fin.last n)) := rfl

/-- The increment of a space-time observable along one Markov transition.
The zeroth observation installs the initial state and carries no increment. -/
def spaceTimeMarkovScore
    (value : Ω → ℕ → ℝ) :
    ∀ n, (Fin n → Ω) → Ω → ℝ
  | 0, _, _ => 0
  | n + 1, history, successor =>
      value successor (n + 1) -
        value (history (Fin.last n)) n

@[simp] theorem spaceTimeMarkovScore_zero
    (value : Ω → ℕ → ℝ)
    (history : Fin 0 → Ω) (state : Ω) :
    spaceTimeMarkovScore value 0 history state = 0 := rfl

@[simp] theorem spaceTimeMarkovScore_succ
    (value : Ω → ℕ → ℝ)
    (n : ℕ) (history : Fin (n + 1) → Ω) (successor : Ω) :
    spaceTimeMarkovScore value (n + 1) history successor =
      value successor (n + 1) -
        value (history (Fin.last n)) n := rfl

/-- The space-time harmonic equation is exactly conditional centering of
the Markov score. -/
theorem expect_spaceTimeMarkovScore_eq_zero_of_harmonic
    [Finite Ω]
    (initial : Ω) (kernel : Ω → PMF Ω)
    (value : Ω → ℕ → ℝ)
    (harmonic : ∀ state time,
      value state time =
        expect (kernel state) (fun successor =>
          value successor (time + 1)))
    (n : ℕ) (history : Fin n → Ω) :
    expect (homogeneousMarkovStep initial kernel n history)
      (spaceTimeMarkovScore value n history) = 0 := by
  cases n with
  | zero => simp
  | succ n =>
      rw [homogeneousMarkovStep_succ]
      change
        expect (kernel (history (Fin.last n)))
            (fun successor => value successor (n + 1) -
              value (history (Fin.last n)) n) = 0
      rw [expect_sub, expect_const,
        ← harmonic (history (Fin.last n)) n]
      ring

/-- Expected total variation through the first `horizon` transitions of a
time-homogeneous finite Markov chain. -/
noncomputable def finiteExpectedSpaceTimeMarkovVariation
    (initial : Ω) (kernel : Ω → PMF Ω)
    (value : Ω → ℕ → ℝ) (horizon : ℕ) : ℝ :=
  expectedDecisionVariation
    (homogeneousMarkovStep initial kernel)
    (spaceTimeMarkovScore value)
    (horizon + 1)

theorem finiteExpectedSpaceTimeMarkovVariation_nonneg
    (initial : Ω) (kernel : Ω → PMF Ω)
    (value : Ω → ℕ → ℝ) (horizon : ℕ) :
    0 ≤ finiteExpectedSpaceTimeMarkovVariation
      initial kernel value horizon :=
  expectedDecisionVariation_nonneg
    (homogeneousMarkovStep initial kernel)
    (spaceTimeMarkovScore value)
    (horizon + 1)

theorem finiteExpectedSpaceTimeMarkovVariation_mono
    (initial : Ω) (kernel : Ω → PMF Ω)
    (value : Ω → ℕ → ℝ) {earlier later : ℕ}
    (hle : earlier ≤ later) :
    finiteExpectedSpaceTimeMarkovVariation
        initial kernel value earlier ≤
      finiteExpectedSpaceTimeMarkovVariation
        initial kernel value later :=
  expectedDecisionVariation_mono
    (homogeneousMarkovStep initial kernel)
    (spaceTimeMarkovScore value)
    (Nat.add_le_add_right hle 1)

/-- A statewise certificate for the finite homogeneous-chain variation
bound. `escape owner` dominates the conditional variation when the chain is
at `owner`. The corresponding indicator charge is a nonnegative Poisson
drift with at most one unit of initial potential.

This interface deliberately asks for those two facts as data. In particular,
it does not assert that bounded space-time harmonicity alone constructs the
escape potentials used in Simon's informal return-probability argument. -/
structure HasStatewiseMarkovVariationBudget
    [Fintype Ω]
    (initial : Ω) (kernel : Ω → PMF Ω)
    (value : Ω → ℕ → ℝ) where
  escape : Ω → ℝ
  potential : Ω → Ω → ℝ
  localVariation_le_escape : ∀ time state,
    expect (kernel state) (fun successor ↦
      |value successor (time + 1) - value state time|) ≤
        escape state
  potential_nonneg : ∀ owner state, 0 ≤ potential owner state
  escape_eq_drift_at_owner : ∀ owner,
    escape owner =
      potential owner owner -
        expect (kernel owner) (potential owner)
  zero_eq_drift_of_ne : ∀ owner state, state ≠ owner →
    0 = potential owner state -
      expect (kernel state) (potential owner)
  potential_initial_le_one : ∀ owner,
    potential owner initial ≤ 1

namespace HasStatewiseMarkovVariationBudget

variable [Fintype Ω]
  {initial : Ω} {kernel : Ω → PMF Ω}
  {value : Ω → ℕ → ℝ}

/-- The sum of all statewise potentials. -/
noncomputable def totalPotential
    (certificate :
      HasStatewiseMarkovVariationBudget initial kernel value)
    (state : Ω) : ℝ :=
  ∑ owner, certificate.potential owner state

theorem totalPotential_nonneg
    (certificate :
      HasStatewiseMarkovVariationBudget initial kernel value)
    (state : Ω) :
    0 ≤ certificate.totalPotential state :=
  Finset.sum_nonneg fun owner _ ↦
    certificate.potential_nonneg owner state

theorem totalPotential_initial_le_card
    (certificate :
      HasStatewiseMarkovVariationBudget initial kernel value) :
    certificate.totalPotential initial ≤ Fintype.card Ω := by
  calc
    certificate.totalPotential initial ≤ ∑ _owner : Ω, (1 : ℝ) :=
      Finset.sum_le_sum fun owner _ ↦
        certificate.potential_initial_le_one owner
    _ = Fintype.card Ω := by simp

theorem totalPotential_drift
    (certificate :
      HasStatewiseMarkovVariationBudget initial kernel value)
    (state : Ω) :
    certificate.totalPotential state -
        expect (kernel state) certificate.totalPotential =
      certificate.escape state := by
  change
    (∑ owner, certificate.potential owner state) -
        expect (kernel state)
          (fun next => ∑ owner, certificate.potential owner next) =
      certificate.escape state
  rw [← expect_sum_comm]
  rw [← Finset.sum_sub_distrib]
  rw [Finset.sum_eq_single state]
  · exact (certificate.escape_eq_drift_at_owner state).symm
  · intro owner _ howner
    exact (certificate.zero_eq_drift_of_ne owner state howner.symm).symm
  · simp

private theorem conditionalVariationSum_le_chargeSum
    (certificate :
      HasStatewiseMarkovVariationBudget initial kernel value)
    (horizon : ℕ) (history : Fin (horizon + 1) → Ω) :
    predictableConditionalMeanSum
        (homogeneousMarkovStep initial kernel)
        (fun n past successor ↦
          |spaceTimeMarkovScore value n past successor|)
        (horizon + 1) history ≤
      markovHistoryStateChargeSum certificate.escape horizon history := by
  induction horizon with
  | zero => simp [predictableConditionalMeanSum]
  | succ horizon ih =>
      rw [← Fin.snoc_init_self history]
      simp only [predictableConditionalMeanSum_snoc,
        markovHistoryStateChargeSum_snoc]
      exact add_le_add (ih (Fin.init history))
        (certificate.localVariation_le_escape horizon
          ((Fin.init history) (Fin.last horizon)))

/-- A supplied statewise escape/occupation certificate gives Simon's sharp
finite-state cardinality bound at every finite horizon.  Producing this
escape/Poisson certificate from Simon's hypotheses, and passing from these
finite bounds to his infinite return argument, remain open. -/
theorem finiteExpectedSpaceTimeMarkovVariation_le_card
    (certificate :
      HasStatewiseMarkovVariationBudget initial kernel value)
    (horizon : ℕ) :
    finiteExpectedSpaceTimeMarkovVariation
        initial kernel value horizon ≤
      Fintype.card Ω := by
  let step := homogeneousMarkovStep initial kernel
  let absScore := fun n history successor ↦
    |spaceTimeMarkovScore value n history successor|
  let law := adaptiveHistoryLaw step (horizon + 1)
  have hvariation :
      finiteExpectedSpaceTimeMarkovVariation
          initial kernel value horizon =
        expect law
          (predictableConditionalMeanSum step absScore (horizon + 1)) := by
    rw [finiteExpectedSpaceTimeMarkovVariation,
      expectedDecisionVariation_eq_expect_predictableScoreSum_abs,
      expect_predictableScoreSum_eq_expect_conditionalMeanSum]
  have hcharge : ∀ state,
      certificate.escape state =
        certificate.totalPotential state -
          expect (kernel state) certificate.totalPotential :=
    fun state ↦ (certificate.totalPotential_drift state).symm
  have hcenter : ∀ n history,
      expect (step n history)
        (adaptiveMarkovDiscrepancyScore
          kernel certificate.totalPotential n history) = 0 := by
    intro n history
    cases n with
    | zero => simp [step, homogeneousMarkovStep]
    | succ n =>
        simpa [step, homogeneousMarkovStep] using
          (expect_adaptiveMarkovDiscrepancyScore_succ
            initial kernel
            (fun n history ↦ kernel (history (Fin.last n)))
            certificate.totalPotential n history)
  have hoccupation :
      expect law
          (markovHistoryStateChargeSum certificate.escape horizon) ≤
        certificate.totalPotential initial := by
    have hbound := expect_markovHistoryStateChargeSum_le
      initial kernel
      (fun n history ↦ kernel (history (Fin.last n)))
      certificate.totalPotential certificate.escape
      certificate.totalPotential_nonneg hcharge horizon
    have hzero := expect_predictableScoreSum_eq_zero
      step
      (adaptiveMarkovDiscrepancyScore kernel certificate.totalPotential)
      hcenter (horizon + 1)
    rw [expect_predictableScoreSum_eq_expect_conditionalMeanSum] at hzero
    change
      expect law
          (markovHistoryStateChargeSum certificate.escape horizon) ≤
        certificate.totalPotential initial +
          expect law
            (predictableConditionalMeanSum step
              (adaptiveMarkovDiscrepancyScore
                kernel certificate.totalPotential)
              (horizon + 1)) at hbound
    rw [hzero, add_zero] at hbound
    exact hbound
  rw [hvariation]
  exact (expect_mono law _ _ fun history ↦
    certificate.conditionalVariationSum_le_chargeSum horizon history).trans
      (hoccupation.trans certificate.totalPotential_initial_le_card)

end HasStatewiseMarkovVariationBudget

namespace HarmonicStateAccountCounterexample

/-- The unique path on a one-state space. -/
def singletonPath : ℕ → PUnit := fun _ => PUnit.unit

/-- The unique one-state Markov kernel. -/
def singletonKernel : PUnit → PMF PUnit :=
  fun _ => PMF.pure PUnit.unit

/-- Every potential is harmonic under the unique one-state kernel. -/
theorem singleton_harmonic (potential : PUnit → ℝ) :
    ∀ state,
      expect (singletonKernel state) potential = potential state := by
  intro state
  cases state
  simp [singletonKernel]

/-- Every state-potential account on the singleton path has zero
increment. -/
theorem singleton_statePotentialIncrement_eq_zero
    (potential : PUnit → ℝ) (t : ℕ) :
    statePotentialIncrement potential singletonPath t = 0 := by
  simp [statePotentialIncrement, singletonPath]

/-- Therefore the recurring charge `1` cannot be identified with a
state-potential increment, even though every potential on the singleton
kernel is harmonic. -/
theorem not_exists_statePotential_realizing_constant_one :
    ¬ ∃ potential : PUnit → ℝ,
      ∀ t,
        (1 : ℝ) =
          statePotentialIncrement potential singletonPath t := by
  rintro ⟨potential, realizes⟩
  have hone := realizes 0
  rw [singleton_statePotentialIncrement_eq_zero] at hone
  norm_num at hone

/-- Even after spelling the desired charge as an endpoint-kernel
discrepancy, harmonicity cannot identify the unrelated recurring charge
`1`. -/
theorem not_exists_harmonicPotential_identifying_constant_one :
    ¬ ∃ potential : PUnit → ℝ,
      (∀ state,
        expect (singletonKernel state) potential = potential state) ∧
      ∀ t,
        (1 : ℝ) =
          markovPotentialDiscrepancy singletonKernel potential
            (singletonPath t) (singletonPath (t + 1)) := by
  rintro ⟨potential, harmonic, identifies⟩
  have hone := identifies 0
  rw [
    markovPotentialDiscrepancy_eq_statePotentialIncrement_of_harmonic
      singletonKernel potential harmonic singletonPath 0,
    singleton_statePotentialIncrement_eq_zero] at hone
  norm_num at hone

end HarmonicStateAccountCounterexample

end

end Math.Probability
