/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import MathUE.Probability.Adaptive

/-!
# Markov potential telescopes and occupation charges

A one-step Poisson equation for a baseline PMF kernel gives an exact pathwise
occupation/discrepancy identity along an arbitrary state sequence. No Markov
assumption on the observed sequence is required.
-/

namespace Math.Probability

noncomputable section

variable {Ω : Type*}

/-- One-step potential discrepancy between an observed successor and the
baseline conditional expectation at the source state. -/
def markovPotentialDiscrepancy
    (baseline : Ω → PMF Ω) (potential : Ω → ℝ)
    (source successor : Ω) : ℝ :=
  potential successor - expect (baseline source) potential

/-- Cumulative state charge over the first `T` sources of a state sequence. -/
def markovStateChargeSum
    (charge : Ω → ℝ) (path : ℕ → Ω) (T : ℕ) : ℝ :=
  ∑ t ∈ Finset.range T, charge (path t)

@[simp] theorem markovStateChargeSum_succ
    (charge : Ω → ℝ) (path : ℕ → Ω) (T : ℕ) :
    markovStateChargeSum charge path (T + 1) =
      markovStateChargeSum charge path T + charge (path T) := by
  simp [markovStateChargeSum, Finset.sum_range_succ]

/-- Cumulative observed-versus-baseline potential discrepancy over the first
`T` transitions of a state sequence. -/
def markovPotentialDiscrepancySum
    (baseline : Ω → PMF Ω) (potential : Ω → ℝ)
    (path : ℕ → Ω) (T : ℕ) : ℝ :=
  ∑ t ∈ Finset.range T,
    markovPotentialDiscrepancy baseline potential (path t) (path (t + 1))

/-- A Poisson equation for the baseline kernel telescopes pathwise along
every state sequence, including sequences generated by arbitrary
history-dependent comparison kernels. -/
theorem markovStateChargeSum_eq_potential_sub_add_discrepancy
    (baseline : Ω → PMF Ω) (potential charge : Ω → ℝ)
    (hcharge : ∀ s,
      charge s = potential s - expect (baseline s) potential)
    (path : ℕ → Ω) (T : ℕ) :
    markovStateChargeSum charge path T =
      potential (path 0) - potential (path T) +
        markovPotentialDiscrepancySum baseline potential path T := by
  rw [markovStateChargeSum, markovPotentialDiscrepancySum]
  calc
    (∑ t ∈ Finset.range T, charge (path t)) =
        (∑ t ∈ Finset.range T, (
          (potential (path t) - potential (path (t + 1))) +
            markovPotentialDiscrepancy
              baseline potential (path t) (path (t + 1)))) := by
      apply Finset.sum_congr rfl
      intro t _
      rw [hcharge]
      simp only [markovPotentialDiscrepancy]
      ring
    _ =
        (∑ t ∈ Finset.range T,
          (potential (path t) - potential (path (t + 1)))) +
        ∑ t ∈ Finset.range T,
          markovPotentialDiscrepancy
            baseline potential (path t) (path (t + 1)) := by
      rw [Finset.sum_add_distrib]
    _ = potential (path 0) - potential (path T) +
        ∑ t ∈ Finset.range T,
          markovPotentialDiscrepancy
            baseline potential (path t) (path (t + 1)) := by
      rw [Finset.sum_range_sub']

/-- For a nonnegative potential, cumulative state occupation is bounded by
the initial potential plus cumulative observed transition discrepancy. -/
theorem markovStateChargeSum_le_initial_add_discrepancy
    (baseline : Ω → PMF Ω) (potential charge : Ω → ℝ)
    (hpotential : ∀ s, 0 ≤ potential s)
    (hcharge : ∀ s,
      charge s = potential s - expect (baseline s) potential)
    (path : ℕ → Ω) (T : ℕ) :
    markovStateChargeSum charge path T ≤
      potential (path 0) +
        markovPotentialDiscrepancySum baseline potential path T := by
  rw [markovStateChargeSum_eq_potential_sub_add_discrepancy
    baseline potential charge hcharge]
  linarith [hpotential (path T)]

/-- Adaptive state process with a fixed initial state. At every later step,
the comparison kernel may depend on the complete state history. -/
def adaptiveMarkovStep
    (initial : Ω)
    (comparison : ∀ n, (Fin (n + 1) → Ω) → PMF Ω) :
    ∀ n, (Fin n → Ω) → PMF Ω
  | 0, _ => PMF.pure initial
  | n + 1, history => comparison n history

@[simp] theorem adaptiveMarkovStep_zero
    (initial : Ω)
    (comparison : ∀ n, (Fin (n + 1) → Ω) → PMF Ω)
    (history : Fin 0 → Ω) :
    adaptiveMarkovStep initial comparison 0 history = PMF.pure initial := rfl

@[simp] theorem adaptiveMarkovStep_succ
    (initial : Ω)
    (comparison : ∀ n, (Fin (n + 1) → Ω) → PMF Ω)
    (n : ℕ) (history : Fin (n + 1) → Ω) :
    adaptiveMarkovStep initial comparison (n + 1) history =
      comparison n history := rfl

/-- The predictable score whose noninitial terms are the observed
successor-versus-baseline potential discrepancies. -/
def adaptiveMarkovDiscrepancyScore
    (baseline : Ω → PMF Ω) (potential : Ω → ℝ) :
    ∀ n, (Fin n → Ω) → Ω → ℝ
  | 0, _, _ => 0
  | n + 1, history, successor =>
      markovPotentialDiscrepancy baseline potential
        (history (Fin.last n)) successor

@[simp] theorem adaptiveMarkovDiscrepancyScore_zero
    (baseline : Ω → PMF Ω) (potential : Ω → ℝ)
    (history : Fin 0 → Ω) (successor : Ω) :
    adaptiveMarkovDiscrepancyScore baseline potential 0 history successor = 0 :=
  rfl

@[simp] theorem adaptiveMarkovDiscrepancyScore_succ
    (baseline : Ω → PMF Ω) (potential : Ω → ℝ)
    (n : ℕ) (history : Fin (n + 1) → Ω) (successor : Ω) :
    adaptiveMarkovDiscrepancyScore baseline potential (n + 1) history successor =
      markovPotentialDiscrepancy baseline potential
        (history (Fin.last n)) successor := rfl

/-- State charge accumulated at every source in a finite history, excluding
the final state. This recursion is aligned with `Fin.snoc`. -/
def markovHistoryStateChargeSum
    (charge : Ω → ℝ) : ∀ T, (Fin (T + 1) → Ω) → ℝ
  | 0, _ => 0
  | T + 1, history =>
      markovHistoryStateChargeSum charge T (Fin.init history) +
        charge ((Fin.init history) (Fin.last T))

@[simp] theorem markovHistoryStateChargeSum_zero
    (charge : Ω → ℝ) (history : Fin 1 → Ω) :
    markovHistoryStateChargeSum charge 0 history = 0 := rfl

@[simp] theorem markovHistoryStateChargeSum_snoc
    (charge : Ω → ℝ) (T : ℕ)
    (history : Fin (T + 1) → Ω) (successor : Ω) :
    markovHistoryStateChargeSum charge (T + 1) (Fin.snoc history successor) =
      markovHistoryStateChargeSum charge T history +
        charge (history (Fin.last T)) := by
  simp [markovHistoryStateChargeSum]

/-- Finite-history form of the Markov potential telescope. The predictable
score contains exactly the transition discrepancies and has a zero initial
term. -/
theorem markovHistoryStateChargeSum_eq_potential_sub_add_score
    (baseline : Ω → PMF Ω) (potential charge : Ω → ℝ)
    (hcharge : ∀ s,
      charge s = potential s - expect (baseline s) potential)
    (T : ℕ) (history : Fin (T + 1) → Ω) :
    markovHistoryStateChargeSum charge T history =
      potential (history 0) - potential (history (Fin.last T)) +
        predictableScoreSum
          (adaptiveMarkovDiscrepancyScore baseline potential)
          (T + 1) history := by
  induction T with
  | zero =>
      simp [predictableScoreSum, adaptiveMarkovDiscrepancyScore]
  | succ T ih =>
      rw [← Fin.snoc_init_self history]
      simp only [markovHistoryStateChargeSum_snoc,
        predictableScoreSum_snoc, ih]
      rw [hcharge]
      simp [markovPotentialDiscrepancy]
      ring

/-- Under the fixed-initial adaptive Markov law, the first state remains the
given initial state at every positive history length. -/
theorem expect_adaptiveMarkov_initial
    [Finite Ω]
    (initial : Ω)
    (comparison : ∀ n, (Fin (n + 1) → Ω) → PMF Ω)
    (potential : Ω → ℝ) (T : ℕ) :
    expect
        (adaptiveHistoryLaw (adaptiveMarkovStep initial comparison) (T + 1))
        (fun history => potential (history 0)) =
      potential initial := by
  induction T with
  | zero =>
      rw [adaptiveHistoryLaw_succ, expect_bind]
      simp only [adaptiveHistoryLaw_zero, expect_pure, adaptiveMarkovStep_zero]
      rw [expect_map, expect_pure]
      rfl
  | succ T ih =>
      rw [adaptiveHistoryLaw_succ, expect_bind]
      have hfirst : (fun history =>
          expect
            ((adaptiveMarkovStep initial comparison (T + 1) history).map
              (Fin.snoc history))
            (fun (nextHistory : Fin (T + 2) → Ω) =>
              potential (nextHistory 0))) =
          fun history => potential (history 0) := by
        funext history
        rw [expect_map]
        simp
      rw [hfirst, ih]

/-- The conditional mean of the observed potential discrepancy is exactly
the comparison-kernel expectation minus the baseline-kernel expectation. -/
theorem expect_adaptiveMarkovDiscrepancyScore_succ
    [Finite Ω]
    (initial : Ω)
    (baseline : Ω → PMF Ω)
    (comparison : ∀ n, (Fin (n + 1) → Ω) → PMF Ω)
    (potential : Ω → ℝ)
    (n : ℕ) (history : Fin (n + 1) → Ω) :
    expect
        (adaptiveMarkovStep initial comparison (n + 1) history)
        (adaptiveMarkovDiscrepancyScore
          baseline potential (n + 1) history) =
      expect (comparison n history) potential -
        expect (baseline (history (Fin.last n))) potential := by
  rw [adaptiveMarkovStep_succ]
  change
    expect (comparison n history) (fun successor =>
      markovPotentialDiscrepancy baseline potential
        (history (Fin.last n)) successor) =
      expect (comparison n history) potential -
        expect (baseline (history (Fin.last n))) potential
  simp only [markovPotentialDiscrepancy]
  rw [expect_sub, expect_const]

/-- Expected adaptive occupation bound. The right-hand sum is the predictable
conditional mean of the observed transition discrepancy, namely the
comparison-kernel potential minus the baseline-kernel potential. -/
theorem expect_markovHistoryStateChargeSum_le
    [Finite Ω]
    (initial : Ω)
    (baseline : Ω → PMF Ω)
    (comparison : ∀ n, (Fin (n + 1) → Ω) → PMF Ω)
    (potential charge : Ω → ℝ)
    (hpotential : ∀ s, 0 ≤ potential s)
    (hcharge : ∀ s,
      charge s = potential s - expect (baseline s) potential)
    (T : ℕ) :
    expect
        (adaptiveHistoryLaw (adaptiveMarkovStep initial comparison) (T + 1))
        (markovHistoryStateChargeSum charge T) ≤
      potential initial +
        expect
          (adaptiveHistoryLaw
            (adaptiveMarkovStep initial comparison) (T + 1))
          (predictableConditionalMeanSum
            (adaptiveMarkovStep initial comparison)
            (adaptiveMarkovDiscrepancyScore baseline potential)
            (T + 1)) := by
  let step := adaptiveMarkovStep initial comparison
  let score := adaptiveMarkovDiscrepancyScore baseline potential
  let law := adaptiveHistoryLaw step (T + 1)
  calc
    expect law (markovHistoryStateChargeSum charge T) ≤
        expect law (fun history =>
          potential (history 0) +
            predictableScoreSum score (T + 1) history) := by
      apply expect_mono
      intro history
      rw [markovHistoryStateChargeSum_eq_potential_sub_add_score
        baseline potential charge hcharge]
      dsimp only [score]
      linarith [hpotential (history (Fin.last T))]
    _ = expect law (fun history => potential (history 0)) +
          expect law (predictableScoreSum score (T + 1)) := by
      rw [expect_add]
    _ = potential initial +
          expect law
            (predictableConditionalMeanSum step score (T + 1)) := by
      rw [expect_adaptiveMarkov_initial initial comparison potential T]
      congr 1
      exact expect_predictableScoreSum_eq_expect_conditionalMeanSum
        step score (T + 1)

/-- Numeric assembly for extending an incentive bound from a recurrent core
through a transient interface. The two occupation losses correspond to the
deviating and prescribed laws. This theorem deliberately takes the shadow-play
comparison inequalities as hypotheses: an occupation telescope alone does
not construct the required core interface. -/
theorem fullGameIncentiveGap_le_of_coreInterface
    {fullDeviation fullPrescribed coreDeviation corePrescribed : ℝ}
    {coreError payoffOscillation transientPotential discrepancyBudget : ℝ}
    {deviationOccupation prescribedOccupation horizon : ℝ}
    {deviationCost prescribedCost : ℝ}
    (horizon_pos : 0 < horizon)
    (payoffOscillation_nonneg : 0 ≤ payoffOscillation)
    (hfullDeviation :
      fullDeviation ≤
        coreDeviation +
          payoffOscillation * deviationOccupation / horizon +
          deviationCost)
    (hfullPrescribed :
      corePrescribed -
          payoffOscillation * prescribedOccupation / horizon -
          prescribedCost ≤
        fullPrescribed)
    (hcore : coreDeviation - corePrescribed ≤ coreError)
    (hdeviationOccupation :
      deviationOccupation ≤ transientPotential + discrepancyBudget)
    (hprescribedOccupation :
      prescribedOccupation ≤ transientPotential) :
    fullDeviation - fullPrescribed ≤
      coreError +
        payoffOscillation *
          (2 * transientPotential + discrepancyBudget) / horizon +
        deviationCost + prescribedCost := by
  have hdevScaled :
      payoffOscillation * deviationOccupation / horizon ≤
        payoffOscillation *
          (transientPotential + discrepancyBudget) / horizon := by
    apply div_le_div_of_nonneg_right _ horizon_pos.le
    exact mul_le_mul_of_nonneg_left
      hdeviationOccupation payoffOscillation_nonneg
  have hprescribedScaled :
      payoffOscillation * prescribedOccupation / horizon ≤
        payoffOscillation * transientPotential / horizon := by
    apply div_le_div_of_nonneg_right _ horizon_pos.le
    exact mul_le_mul_of_nonneg_left
      hprescribedOccupation payoffOscillation_nonneg
  calc
    fullDeviation - fullPrescribed ≤
        coreError +
          payoffOscillation *
            (transientPotential + discrepancyBudget) / horizon +
          payoffOscillation * transientPotential / horizon +
          deviationCost + prescribedCost := by
      linarith
    _ = coreError +
          payoffOscillation *
            (2 * transientPotential + discrepancyBudget) / horizon +
          deviationCost + prescribedCost := by
      ring

/-- Specialization of the core-interface bound to payoffs with oscillation at
most two, as under the normalization `|u| ≤ 1`. -/
theorem fullGameIncentiveGap_le_of_coreInterface_two
    {fullDeviation fullPrescribed coreDeviation corePrescribed : ℝ}
    {coreError transientPotential discrepancyBudget : ℝ}
    {deviationOccupation prescribedOccupation horizon : ℝ}
    {deviationCost prescribedCost : ℝ}
    (horizon_pos : 0 < horizon)
    (hfullDeviation :
      fullDeviation ≤
        coreDeviation + 2 * deviationOccupation / horizon + deviationCost)
    (hfullPrescribed :
      corePrescribed - 2 * prescribedOccupation / horizon - prescribedCost ≤
        fullPrescribed)
    (hcore : coreDeviation - corePrescribed ≤ coreError)
    (hdeviationOccupation :
      deviationOccupation ≤ transientPotential + discrepancyBudget)
    (hprescribedOccupation :
      prescribedOccupation ≤ transientPotential) :
    fullDeviation - fullPrescribed ≤
      coreError + (4 * transientPotential + 2 * discrepancyBudget) / horizon +
        deviationCost + prescribedCost := by
  have h := fullGameIncentiveGap_le_of_coreInterface
    horizon_pos (show (0 : ℝ) ≤ 2 by norm_num)
    hfullDeviation hfullPrescribed hcore
    hdeviationOccupation hprescribedOccupation
  convert h using 1
  all_goals ring

namespace CoreEntryCounterexample

/-- A transient state `none` and two absorbing recurrent states. -/
abbrev State := Option Bool

/-- The baseline enters the zero-payoff recurrent state. -/
def baseline : State → PMF State
  | none => PMF.pure (some false)
  | some recurrent => PMF.pure (some recurrent)

/-- The comparison differs only by entering the other recurrent state. -/
def comparison : State → PMF State
  | none => PMF.pure (some true)
  | some recurrent => PMF.pure (some recurrent)

/-- Hitting-time potential of the recurrent set. -/
def potential : State → ℝ
  | none => 1
  | some _ => 0

/-- Indicator charge of the transient state. -/
def transientCharge : State → ℝ
  | none => 1
  | some _ => 0

/-- Payoff is one only in the comparison-selected recurrent state. -/
def payoff : State → ℝ
  | some true => 1
  | _ => 0

/-- Prescribed state path under the baseline transition. -/
def prescribedPath : ℕ → State
  | 0 => none
  | _ + 1 => some false

/-- Deviating state path under the comparison transition. -/
def deviationPath : ℕ → State
  | 0 => none
  | _ + 1 => some true

/-- The hitting-time potential solves the transient Poisson equation. -/
theorem transientCharge_eq_potential_sub_expect_baseline (s : State) :
    transientCharge s =
      potential s - expect (baseline s) potential := by
  cases s <;> simp [transientCharge, potential, baseline]

/-- Changing the recurrent entry state has zero hitting-potential
discrepancy. -/
theorem comparison_potentialDiscrepancy_none_eq_zero :
    expect (comparison none) potential -
      expect (baseline none) potential = 0 := by
  simp [comparison, baseline, potential]

/-- The whole deviating path has zero observed hitting-potential discrepancy
against the baseline kernel. -/
theorem deviationPath_potentialDiscrepancySum_eq_zero (T : ℕ) :
    markovPotentialDiscrepancySum baseline potential deviationPath T = 0 := by
  induction T with
  | zero =>
      simp [markovPotentialDiscrepancySum]
  | succ T ih =>
      rw [markovPotentialDiscrepancySum,
        Finset.sum_range_succ, ← markovPotentialDiscrepancySum, ih, zero_add]
      cases T <;>
        simp [markovPotentialDiscrepancy, baseline, potential, deviationPath]

/-- The comparison-selected recurrent state pays one at every post-entry
stage. -/
theorem deviationPath_payoffSum_eq (T : ℕ) :
    markovStateChargeSum payoff deviationPath (T + 1) = T := by
  induction T with
  | zero =>
      simp [markovStateChargeSum, payoff, deviationPath]
  | succ T ih =>
      rw [markovStateChargeSum_succ, ih]
      simp only [deviationPath, payoff]
      push_cast
      ring

/-- The prescribed recurrent state has zero payoff at every stage. -/
theorem prescribedPath_payoffSum_eq_zero (T : ℕ) :
    markovStateChargeSum payoff prescribedPath T = 0 := by
  unfold markovStateChargeSum
  apply Finset.sum_eq_zero
  intro t _
  cases t <;> simp [payoff, prescribedPath]

/-- Nevertheless, over horizon `T+1` the comparison-selected recurrent state
creates payoff gap exactly `T`. -/
theorem payoffGap_eq (T : ℕ) :
    markovStateChargeSum payoff deviationPath (T + 1) -
        markovStateChargeSum payoff prescribedPath (T + 1) =
      T := by
  rw [deviationPath_payoffSum_eq, prescribedPath_payoffSum_eq_zero, sub_zero]

end CoreEntryCounterexample

end

end Math.Probability
