import
  UniformEquilibrium.Diagnostics.Quitting.TerminalSemanticConcentratedSingletonStrategicDispatch


namespace GameTheory.QuittingCounterexampleRegime


end GameTheory.QuittingCounterexampleRegime
