/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Architectures.PublicResponse.SplitDomainAsymptoticConverse

/-!
# Response-architecture configuration kernel law

The public history law generated by a finite response architecture contains
more information than its controller configuration law: actions remain in
the history.  Under prescribed play, however, projecting each history to the
architecture's current configuration gives exactly the iterated prescribed
configuration kernel.

This file proves that finite-horizon law, its expected-stage and finite-average
corollaries, and the resulting history-semantic route to the gain-bias
criterion's prescribed target harmonicity condition.
-/

noncomputable section

namespace GameTheory
namespace StochasticGame

open Filter Math.Probability
open Math.ProbabilityMassFunction
open scoped Topology

variable {ι : Type} {G : StochasticGame ι}

attribute [local instance] Fintype.ofFinite

namespace FiniteResponseArchitecture

variable {initial : G.State} (A : G.FiniteResponseArchitecture initial)

section PrescribedConfigurationLaw

variable [Fintype ι]

/-- The configuration marginal of the prescribed public-history law is the
iterated prescribed configuration kernel. -/
theorem map_configAt_histDist_prescribed : ∀ t : ℕ,
    (G.histDist A.phaseProfile.behaviorProfile initial t).map
        (A.configAt t) =
      Math.PMFIter.iter A.prescribedConfigDist t A.start := by
  intro t
  induction t with
  | zero =>
      rw [G.histDist_zero, PMF.pure_map, Math.PMFIter.iter_zero]
      rfl
  | succ t ih =>
      rw [G.histDist_succ, PMF.map_bind]
      change
        (G.histDist A.phaseProfile.behaviorProfile initial t).bind
            (fun h =>
              PMF.map (A.configAt (t + 1))
                ((G.stageActionDist A.phaseProfile.behaviorProfile h).bind
                fun act => (G.transition h.2 act).bind fun s' =>
                  PMF.pure
                    ((Fin.snoc h.1 (h.2, act), s') : G.Hist (t + 1)))) =
          Math.PMFIter.iter A.prescribedConfigDist (t + 1) A.start
      have hinner : ∀ h : G.Hist t,
          h ∈ (G.histDist A.phaseProfile.behaviorProfile initial t).support →
          PMF.map (A.configAt (t + 1))
              ((G.stageActionDist A.phaseProfile.behaviorProfile h).bind
                fun act => (G.transition h.2 act).bind fun s' =>
                  PMF.pure
                    ((Fin.snoc h.1 (h.2, act), s') : G.Hist (t + 1))) =
            A.prescribedConfigDist (A.configAt t h) := by
        intro h hh
        have hstate := A.publicState_configAt_of_mem_support
          A.phaseProfile.behaviorProfile h hh
        rw [PMF.map_bind, A.stageActionDist_prescribed h]
        unfold prescribedConfigDist
        congr 1
        funext act
        rw [PMF.map_bind, hstate]
        congr 1
        funext s'
        rw [PMF.pure_map]
        simpa using congrArg PMF.pure (A.configAt_snoc h act s')
      rw [bind_congr_on_support
        (G.histDist A.phaseProfile.behaviorProfile initial t) _ _ hinner]
      change
        (G.histDist A.phaseProfile.behaviorProfile initial t).bind
            (A.prescribedConfigDist ∘ A.configAt t) =
          Math.PMFIter.iter A.prescribedConfigDist (t + 1) A.start
      rw [← PMF.bind_map, ih, Math.PMFIter.iter_succ']

/-- Rebased form of `map_configAt_histDist_prescribed`: prescribed play from
an arbitrary configuration `z` starts the same configuration kernel at `z`.
-/
theorem map_configAt_histDist_prescribed_rebase (z : A.Config) (t : ℕ) :
    (G.histDist (A.rebase z).phaseProfile.behaviorProfile
        (A.publicState z) t).map ((A.rebase z).configAt t) =
      Math.PMFIter.iter A.prescribedConfigDist t z := by
  have hk : (A.rebase z).prescribedConfigDist =
      A.prescribedConfigDist := by rfl
  simpa only [hk] using (A.rebase z).map_configAt_histDist_prescribed t

/-- Calendar-`t` expected payoff under prescribed play is the expected
prescribed row payoff under the `t`-step configuration law. -/
theorem expectedStagePayoff_prescribed_eq_configIter (who : ι) (t : ℕ) :
    G.expectedStagePayoff A.phaseProfile.behaviorProfile initial t who =
      expect (Math.PMFIter.iter A.prescribedConfigDist t A.start)
        (fun z => A.prescribedStagePayoff z who) := by
  unfold StochasticGame.expectedStagePayoff
  calc
    expect (G.histDist A.phaseProfile.behaviorProfile initial t)
        (fun h => G.stageEUAt A.phaseProfile.behaviorProfile h who) =
        expect (G.histDist A.phaseProfile.behaviorProfile initial t)
          (fun h => A.prescribedStagePayoff (A.configAt t h) who) :=
      expect_congr_on_support _ _ _ fun h hh =>
        A.stageEUAt_prescribed who h
          (A.publicState_configAt_of_mem_support
            A.phaseProfile.behaviorProfile h hh)
    _ = expect
          ((G.histDist A.phaseProfile.behaviorProfile initial t).map
            (A.configAt t))
          (fun z => A.prescribedStagePayoff z who) := by
      rw [expect_map]
    _ = expect (Math.PMFIter.iter A.prescribedConfigDist t A.start)
          (fun z => A.prescribedStagePayoff z who) := by
      rw [A.map_configAt_histDist_prescribed t]

/-- Arbitrary-start form of the expected-stage configuration-kernel law. -/
theorem expectedStagePayoff_prescribed_rebase_eq_configIter
    (z : A.Config) (who : ι) (t : ℕ) :
    G.expectedStagePayoff (A.rebase z).phaseProfile.behaviorProfile
        (A.publicState z) t who =
      expect (Math.PMFIter.iter A.prescribedConfigDist t z)
        (fun y => A.prescribedStagePayoff y who) := by
  have hk : (A.rebase z).prescribedConfigDist =
      A.prescribedConfigDist := by rfl
  have hr : (A.rebase z).prescribedStagePayoff =
      A.prescribedStagePayoff := by rfl
  simpa only [hk, hr] using
    (A.rebase z).expectedStagePayoff_prescribed_eq_configIter who t

end PrescribedConfigurationLaw

section PrescribedFiniteAverageLaw

variable [Fintype ι] [Finite G.State] [∀ i, Finite (G.Act i)]

/-- The ordinary history-semantic finite average of a rebased architecture is
exactly its prescribed configuration-kernel Cesaro payoff. -/
theorem finiteAveragePayoff_prescribed_rebase_eq_configCesaro
    (z : A.Config) (who : ι) (T : ℕ) :
    G.finiteAveragePayoff (A.publicState z) T
        (A.rebase z).phaseProfile.behaviorProfile who =
      A.prescribedConfigCesaroPayoff who z T := by
  rw [G.finiteAveragePayoff_eq_sum_expectedStagePayoff]
  unfold prescribedConfigCesaroPayoff
  congr 1
  apply Finset.sum_congr rfl
  intro t _
  exact A.expectedStagePayoff_prescribed_rebase_eq_configIter z who t

/-- A history-level convergence claim therefore supplies the configuration
Cesaro convergence hypothesis used by the target converse. -/
theorem tendsto_prescribedConfigCesaroPayoff_of_finiteAverage
    (z : A.Config) (who : ι) (value : ℝ)
    (h : Tendsto (fun T : ℕ =>
      G.finiteAveragePayoff (A.publicState z) T
        (A.rebase z).phaseProfile.behaviorProfile who)
      atTop (nhds value)) :
    Tendsto (fun T : ℕ => A.prescribedConfigCesaroPayoff who z T)
      atTop (nhds value) := by
  simpa only [A.finiteAveragePayoff_prescribed_rebase_eq_configCesaro]
    using h

namespace SplitResponseDomain

variable [DecidableEq ι] {A : G.FiniteResponseArchitecture initial}

/-- History-semantic shifted delivery implies the gain-bias criterion's
prescribed target harmonicity condition on the full split delivery union. -/
theorem prescribedTargetHarmonic_of_tendsto_finiteAverage
    (D : A.SplitResponseDomain) {u : A.Config → Payoff ι}
    (hdelivery : ∀ (who : ι) (z : A.Config), D.delivery z →
      Tendsto (fun T : ℕ =>
        G.finiteAveragePayoff (A.publicState z) T
          (A.rebase z).phaseProfile.behaviorProfile who)
        atTop (nhds (u z who))) :
    ∀ (who : ι) (z : A.Config), D.delivery z →
      expect (A.prescribedConfigDist z) (fun y => u y who) = u z who := by
  apply D.prescribedTargetHarmonic_of_tendsto_configCesaro
  intro who z hz
  exact A.tendsto_prescribedConfigCesaroPayoff_of_finiteAverage z who
    (u z who) (hdelivery who z hz)

end SplitResponseDomain
end PrescribedFiniteAverageLaw

end FiniteResponseArchitecture
end StochasticGame
end GameTheory
