/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.AbsorptionPath.RealizedMarkedAbsorptionCylinder
import UniformEquilibrium.Quitting.AbsorptionPath.MarkedObstacleRecord
import UniformEquilibrium.Quitting.AbsorptionPath.MarkedAbsorptionCylinder
import UniformEquilibrium.Quitting.AbsorptionPath.MetrizableMarkedAbsorptionPath
import UniformEquilibrium.Quitting.AbsorptionPath.MetrizableMarkedAbsorptionDecoder
import UniformEquilibrium.Quitting.AbsorptionPath.MetrizableMarkedAbsorptionComposition
import UniformEquilibrium.Quitting.AbsorptionPath.CollisionConcentration
import UniformEquilibrium.Quitting.AbsorptionPath.NormalizedFiniteWindowOccupation
import UniformEquilibrium.Quitting.AbsorptionPath.DiscreteRootSequencePath
import UniformEquilibrium.Quitting.AbsorptionPath.FiniteRootSequenceCDFCut
import UniformEquilibrium.Quitting.AbsorptionPath.ChronologicalRootSequenceTail
import UniformEquilibrium.Quitting.AbsorptionPath.ChronologicalMarkedRootSequenceLaw
import UniformEquilibrium.Quitting.AbsorptionPath.ChronologicalMarkedRootSequenceJump
import UniformEquilibrium.Quitting.AbsorptionPath.ChronologicalMarkedRootSequenceJumpLimit
import UniformEquilibrium.Quitting.AbsorptionPath.ChronologicalMarkedRootSequenceCollision
import UniformEquilibrium.Quitting.AbsorptionPath.ChronologicalMarkedRootSequenceA4
import UniformEquilibrium.Quitting.AbsorptionPath.ClockGapA2
import UniformEquilibrium.Quitting.AbsorptionPath.RootSequenceAbsorbingCompletion
import UniformEquilibrium.Quitting.AbsorptionPath.RootSequenceAbsorbingCompletionDiagonal
import UniformEquilibrium.Quitting.AbsorptionPath.RootSequenceAbsorbingCompletionPath
import UniformEquilibrium.Quitting.AbsorptionPath.RootSequenceAbsorbingCompletionChronologicalLimit
import UniformEquilibrium.Quitting.AbsorptionPath.RootSequenceAbsorbingCompletionChronologicalA3
import UniformEquilibrium.Quitting.AbsorptionPath.RootSequenceAbsorbingCompletionChronologicalA4
import UniformEquilibrium.Quitting.AbsorptionPath.RootSequenceAbsorbingCompletionChronologicalJumpPerfection
import UniformEquilibrium.Quitting.AbsorptionPath.RootSequenceAbsorbingCompletionChronologicalSingletonLowerBound
import UniformEquilibrium.Quitting.AbsorptionPath.RootSequenceAbsorbingCompletionChronologicalPositiveSingletonRate
import UniformEquilibrium.Quitting.AbsorptionPath.AKRSPartition
import UniformEquilibrium.Quitting.AbsorptionPath.AKRSPartitionSmallCell
import UniformEquilibrium.Quitting.AbsorptionPath.AKRSPartitionDecoder
import UniformEquilibrium.Quitting.AbsorptionPath.AKRSSequentialPerfectionDecoder
import UniformEquilibrium.Quitting.AbsorptionPath.FiniteWindowRefusalReweighting
import UniformEquilibrium.Quitting.AbsorptionPath.PrincipalQDirection
import UniformEquilibrium.Quitting.AbsorptionPath.PrincipalQBoundaryDirection
import UniformEquilibrium.Quitting.AbsorptionPath.PrincipalQLocalArc
import UniformEquilibrium.Quitting.AbsorptionPath.PrincipalQClockChain
import UniformEquilibrium.Quitting.AbsorptionPath.PrincipalQClockOrbit
import UniformEquilibrium.Quitting.AbsorptionPath.PrincipalQClockEpoch
import UniformEquilibrium.Quitting.AbsorptionPath.PrincipalQClockEpochIteration
import UniformEquilibrium.Quitting.AbsorptionPath.PrincipalQClockReachability
import UniformEquilibrium.Quitting.AbsorptionPath.PrincipalQClockMassPath
import UniformEquilibrium.Quitting.AbsorptionPath.PrincipalQContinuousPath
import UniformEquilibrium.Quitting.AbsorptionPath.PunishmentNormalPathEmbedding
import UniformEquilibrium.Quitting.AbsorptionPath.SingletonPathRates
import UniformEquilibrium.Quitting.AbsorptionPath.SingletonPathSnell
import UniformEquilibrium.Quitting.AbsorptionPath.SingletonPathSnellTail
import UniformEquilibrium.Quitting.AbsorptionPath.PunishmentNormalPathSnell
import UniformEquilibrium.Quitting.AbsorptionPath.LogarithmicProductLaw
import UniformEquilibrium.Quitting.AbsorptionPath.LogarithmicProductDecoder
import UniformEquilibrium.Quitting.AbsorptionPath.LogarithmicPathBlockAdapter
import UniformEquilibrium.Quitting.AbsorptionPath.PunishmentNormalPathStrategicSnell
import UniformEquilibrium.Quitting.AbsorptionPath.PrincipalQBoundaryEulerChain
import UniformEquilibrium.Quitting.AbsorptionPath.PrincipalQViabilityCorrespondence
import UniformEquilibrium.Quitting.AbsorptionPath.PrincipalQSupportCorrespondence
import UniformEquilibrium.Quitting.AbsorptionPath.PrincipalQControlledTrajectory
import UniformEquilibrium.Quitting.AbsorptionPath.ContinuousPath
import UniformEquilibrium.Quitting.AbsorptionPath.LogarithmicBlockDiscretization
import UniformEquilibrium.Quitting.AbsorptionPath.SingletonContinuousPath
import UniformEquilibrium.Quitting.AbsorptionPath.HomogeneousContinuousPath

/-!
# Marked absorption-path semantic layer

Public entry point for the finite semantics used by the marked absorption-path
program.  `RealizedMarkedAbsorptionCylinder` retains the calibrated source and
exports exact coalition-mass accounting, bounded chronological samples, free
terminal-continuation evaluation, and same-source concatenation laws.
`MarkedObstacleRecord` forgets that source after encoding one stage while
retaining the factor, survival, Bellman, and obstacle coordinates needed by a
completed chronological graph.  `MarkedAbsorptionCylinder` is the finite
source-free graph: its complete carrier is associative, the realized encoder
commutes exactly with adjacent block concatenation, and semantic coherence is
preserved by exact-anchor splicing.

`MetrizableMarkedAbsorptionPath` closes one joint finite semantic encoding in
a compact metric target.  It retains the absorption law with `Never`, all
holonomy coordinates, both exact-D anchors, the terminal packet, entry debt,
and the full marked stage-coordinate graph.  Finite semantic points are
sequentially dense, every sequence has a convergent subsequence, and the
maximal Stone--Cech envelope maps continuously onto this semantic quotient.
The bounded decoder retracts its extended holonomy coordinates to the common
real coefficient box, agrees exactly on finite cylinders, and makes the
behavioral-tail repair value and obstacle cap continuous on the completion.

Completed composition is a closed ternary relation generated by correlated
finite exact seams.  Its compact six-coordinate relation records coherent
limits of finite associative diagrams.  It does not assert total composition
for every equal-anchor pair, uniqueness of result fibres, or amalgamation of
independently selected splice witnesses.  The stage hyperspace is an
extensional semantic graph rather than an ordered history, and the strategic
charged-replacement constructor remains a separate layer.

The source-retaining finite-window layer separately records exact singleton,
collision, and total absorption occupation before normalization.  Product-law
collision concentration controls its conditional singleton-mixture error, and
positive owner occupation supplies a literal active source phase.  Forcing one
player to Continue changes chronology from joint to opponent-only survival;
the resulting refusal reweighting has a division-free raw bound and a
normalized bound conditional on a positive deleted-absorption denominator.
-/
