/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import Mathlib.MeasureTheory.Measure.Portmanteau
import Mathlib.MeasureTheory.Measure.Prokhorov
import Mathlib.Probability.CDF
import Mathlib.Probability.ProbabilityMassFunction.Constructions
import MathUE.Probability.ClockGap
import UniformEquilibrium.Quitting.AbsorptionPath.DiscreteRootSequencePath
import UniformEquilibrium.Quitting.Bellman.Finite.NashBellmanSpine
import UniformEquilibrium.Quitting.Paths.SurvivalWindowLanding

/-!
# Chronological marked laws of finite root sequences

A root sequence which absorbs by a finite row defines a probability law on
marked absorption events.  An event records its absorption clock, current
root, bounded post-stage continuation vector, and a discrete nonempty
coalition.  The law uses the actual unconditional stage--coalition masses.

Coalition coordinates are decoded as cumulative distribution functions using
a cemetery clock outside `[0,1]`.  Weak limits retain the clock-domination
inequality A1.  This module does not assert A2--A4, convergence at every clock,
or sequential perfection.
-/

noncomputable section

namespace GameTheory.QuittingAbsorptionPath

open Filter Finset MeasureTheory Set
open scoped ENNReal Topology

variable {ι : Type} [Fintype ι] [DecidableEq ι] [Nonempty ι]

/-- A nonempty coalition equipped with an explicitly discrete topology. -/
structure QuittingChronologicalCoalitionMark (ι : Type) [Fintype ι] where
  coalition : {S : Finset ι // S.Nonempty}
deriving Fintype, DecidableEq

namespace QuittingChronologicalCoalitionMark

instance instTopologicalSpace : TopologicalSpace
    (QuittingChronologicalCoalitionMark ι) := ⊥

instance instDiscreteTopology : DiscreteTopology
    (QuittingChronologicalCoalitionMark ι) := ⟨rfl⟩

instance instMeasurableSpace : MeasurableSpace
    (QuittingChronologicalCoalitionMark ι) := borel _

instance instBorelSpace : BorelSpace
    (QuittingChronologicalCoalitionMark ι) := ⟨rfl⟩

/-- The marked-coalition wrapper is equivalent to the usual subtype. -/
def equiv : QuittingChronologicalCoalitionMark ι ≃
    {S : Finset ι // S.Nonempty} where
  toFun := coalition
  invFun := fun S ↦ ⟨S⟩
  left_inv := by rintro ⟨S⟩; rfl
  right_inv := by intro S; rfl

end QuittingChronologicalCoalitionMark

/-- The compact cube containing every continuation vector generated by the
fixed reward table. -/
abbrev QuittingChronologicalTailBox
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :=
  Set.Icc (fun _ : ι ↦ -(quittingRewardBound reward))
    (fun _ : ι ↦ quittingRewardBound reward)

/-- A compact chronological absorption event. -/
abbrev QuittingChronologicalEvent
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :=
  Set.Icc (0 : ℝ) 1 ×
    (QuittingRootSimplex ι ×
      (QuittingChronologicalTailBox reward ×
        QuittingChronologicalCoalitionMark ι))

/-- The clock carried by a chronological event. -/
def chronologicalEventClock
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    (event : QuittingChronologicalEvent reward) : ℝ :=
  event.1.1

/-- The root carried by a chronological event. -/
def chronologicalEventRoot
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    (event : QuittingChronologicalEvent reward) : QuittingRootSimplex ι :=
  event.2.1

/-- The post-stage continuation vector carried by a chronological event. -/
def chronologicalEventTail
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    (event : QuittingChronologicalEvent reward) : Payoff ι :=
  event.2.2.1.1

/-- The coalition carried by a chronological event. -/
def chronologicalEventCoalition
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    (event : QuittingChronologicalEvent reward) :
    {S : Finset ι // S.Nonempty} :=
  event.2.2.2.coalition

instance instCompactSpaceChronologicalProbabilityMeasure
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :
    CompactSpace (ProbabilityMeasure (QuittingChronologicalEvent reward)) :=
  instCompactSpaceProbabilityMeasure

namespace QuittingFiniteRootSequenceAbsorption

variable {roots : ℕ → ι → PMF Bool}

/-- Finite indices for all absorption events before the certified zero row. -/
abbrev ChronologicalIndex
    (certificate : QuittingFiniteRootSequenceAbsorption roots) :=
  Fin (certificate.cutoff + 1) × QuittingChronologicalCoalitionMark ι

/-- The real mass of one chronological index. -/
def chronologicalWeight
    (certificate : QuittingFiniteRootSequenceAbsorption roots)
    (index : certificate.ChronologicalIndex) : ℝ :=
  quittingRootSequenceStageCoalitionMass roots index.1 index.2.coalition

omit [Nonempty ι] in
theorem chronologicalWeight_nonneg
    (certificate : QuittingFiniteRootSequenceAbsorption roots)
    (index : certificate.ChronologicalIndex) :
    0 ≤ certificate.chronologicalWeight index :=
  quittingRootSequenceStageCoalitionMass_nonneg roots index.1 index.2.coalition

omit [Nonempty ι] in
theorem sum_chronologicalWeight
    (certificate : QuittingFiniteRootSequenceAbsorption roots) :
    ∑ index, certificate.chronologicalWeight index = 1 := by
  rw [Fintype.sum_prod_type]
  simp only [chronologicalWeight]
  have hmark (stage : Fin (certificate.cutoff + 1)) :
      (∑ mark : QuittingChronologicalCoalitionMark ι,
        quittingRootSequenceStageCoalitionMass roots stage mark.coalition) =
        ∑ coalition : {S : Finset ι // S.Nonempty},
          quittingRootSequenceStageCoalitionMass roots stage coalition := by
    exact Fintype.sum_equiv
      (QuittingChronologicalCoalitionMark.equiv (ι := ι)) _ _ (fun _ ↦ rfl)
  simp_rw [hmark]
  rw [show (∑ stage : Fin (certificate.cutoff + 1),
      ∑ coalition : {S : Finset ι // S.Nonempty},
        quittingRootSequenceStageCoalitionMass roots stage coalition) =
      ∑ stage ∈ Finset.range (certificate.cutoff + 1),
        ∑ coalition : {S : Finset ι // S.Nonempty},
          quittingRootSequenceStageCoalitionMass roots stage coalition from
    Fin.sum_univ_eq_sum_range
      (fun stage : ℕ ↦ ∑ coalition : {S : Finset ι // S.Nonempty},
        quittingRootSequenceStageCoalitionMass roots stage coalition)
      (certificate.cutoff + 1)]
  simp_rw [sum_quittingRootSequenceStageCoalitionMass]
  have htelescope (horizon : ℕ) :
      (∑ stage ∈ Finset.range horizon,
        (quittingRootSequenceSurvival roots stage -
          quittingRootSequenceSurvival roots (stage + 1))) =
        quittingRootSequenceSurvival roots 0 -
          quittingRootSequenceSurvival roots horizon := by
    induction horizon with
    | zero => simp
    | succ horizon ih =>
        rw [Finset.sum_range_succ, ih]
        ring
  rw [htelescope]
  simp [certificate.survival_zero]

omit [Nonempty ι] in
/-- The gap between consecutive clocks is exactly the total coalition mass
created at the earlier row.  This finite identity does not assert A2 for a
weak limit. -/
theorem clock_succ_sub_clock_eq_sum_stageCoalitionMass
    (stage : ℕ) :
    quittingRootSequenceClock roots (stage + 1) -
        quittingRootSequenceClock roots stage =
      ∑ coalition : {S : Finset ι // S.Nonempty},
        quittingRootSequenceStageCoalitionMass roots stage coalition := by
  rw [sum_quittingRootSequenceStageCoalitionMass]
  unfold quittingRootSequenceClock
  ring

/-- The finite probability law on chronological indices. -/
def chronologicalIndexPMF
    (certificate : QuittingFiniteRootSequenceAbsorption roots) :
    PMF certificate.ChronologicalIndex :=
  PMF.ofFintype
    (fun index ↦ ENNReal.ofReal (certificate.chronologicalWeight index))
    (by
      rw [← ENNReal.ofReal_one, ← certificate.sum_chronologicalWeight]
      exact (ENNReal.ofReal_sum_of_nonneg
        (fun index _ ↦ certificate.chronologicalWeight_nonneg index)).symm)

omit [Nonempty ι] in
@[simp] theorem chronologicalIndexPMF_toReal
    (certificate : QuittingFiniteRootSequenceAbsorption roots)
    (index : certificate.ChronologicalIndex) :
    (certificate.chronologicalIndexPMF index).toReal =
      certificate.chronologicalWeight index := by
  rw [chronologicalIndexPMF, PMF.ofFintype_apply]
  exact ENNReal.toReal_ofReal (certificate.chronologicalWeight_nonneg index)

omit [DecidableEq ι] [Nonempty ι] in
private theorem tail_mem_box
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) (stage : ℕ) :
    quittingRootSequenceTailVector reward roots (stage + 1) ∈
      QuittingChronologicalTailBox reward := by
  constructor <;> intro who
  · have h := abs_quittingRootSequenceTerminalValue_le reward roots who
      (stage + 1) (quittingRewardBound_nonneg reward)
      (abs_reward_le_quittingRewardBound reward)
    exact (neg_le_of_abs_le h)
  · exact (abs_le.mp (abs_quittingRootSequenceTerminalValue_le reward roots who
      (stage + 1) (quittingRewardBound_nonneg reward)
      (abs_reward_le_quittingRewardBound reward))).2

/-- The marked event represented by one finite stage--coalition index. -/
def chronologicalEventAt
    (certificate : QuittingFiniteRootSequenceAbsorption roots)
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (index : certificate.ChronologicalIndex) :
    QuittingChronologicalEvent reward :=
  (⟨quittingRootSequenceClock roots index.1,
      quittingRootSequenceClock_nonneg roots index.1,
      quittingRootSequenceClock_le_one roots index.1⟩,
    (fun who ↦ Math.ProbabilityMassFunction.stdSimplexEquiv
      (roots index.1 who)),
    ⟨quittingRootSequenceTailVector reward roots (index.1 + 1),
      tail_mem_box reward index.1⟩,
    index.2)

/-- The globally normalized chronological marked law. -/
def chronologicalLaw
    (certificate : QuittingFiniteRootSequenceAbsorption roots)
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :
    ProbabilityMeasure (QuittingChronologicalEvent reward) :=
  ⟨(PMF.map (certificate.chronologicalEventAt reward)
      certificate.chronologicalIndexPMF).toMeasure,
    PMF.toMeasure.isProbabilityMeasure _⟩

omit [DecidableEq ι] [Nonempty ι] in
@[simp] theorem chronologicalEventAt_clock
    (certificate : QuittingFiniteRootSequenceAbsorption roots)
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (index : certificate.ChronologicalIndex) :
    chronologicalEventClock (certificate.chronologicalEventAt reward index) =
      quittingRootSequenceClock roots index.1 := rfl

omit [DecidableEq ι] [Nonempty ι] in
@[simp] theorem chronologicalEventAt_coalition
    (certificate : QuittingFiniteRootSequenceAbsorption roots)
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (index : certificate.ChronologicalIndex) :
    chronologicalEventCoalition
        (certificate.chronologicalEventAt reward index) =
      index.2.coalition := rfl

omit [DecidableEq ι] [Nonempty ι] in
@[simp] theorem chronologicalEventAt_tail
    (certificate : QuittingFiniteRootSequenceAbsorption roots)
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (index : certificate.ChronologicalIndex) :
    chronologicalEventTail (certificate.chronologicalEventAt reward index) =
      quittingRootSequenceTailVector reward roots (index.1 + 1) := rfl

omit [DecidableEq ι] [Nonempty ι] in
/-- The root mark is literally the current finite row. -/
theorem quittingRootOfSimplex_chronologicalEventAt_root
    (certificate : QuittingFiniteRootSequenceAbsorption roots)
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (index : certificate.ChronologicalIndex) :
    quittingRootOfSimplex
        (chronologicalEventRoot
          (certificate.chronologicalEventAt reward index)) =
      roots index.1 := by
  funext who
  exact Math.ProbabilityMassFunction.stdSimplexEquiv.symm_apply_apply
    (roots index.1 who)

end QuittingFiniteRootSequenceAbsorption

/-! ## CDF decoding -/

variable {reward : {S : Finset ι // S.Nonempty} → Payoff ι}

/-- The event carries the selected coalition. -/
def chronologicalCoalitionEvent
    (coalition : {S : Finset ι // S.Nonempty}) :
    Set (QuittingChronologicalEvent reward) :=
  (fun event ↦ event.2.2.2) ⁻¹'
    ({⟨coalition⟩} : Set (QuittingChronologicalCoalitionMark ι))

/-- The event occurs no later than the selected clock. -/
def chronologicalClockEvent (time : ℝ) :
    Set (QuittingChronologicalEvent reward) :=
  {event | chronologicalEventClock event ≤ time}

/-- The event occurs no later than the selected clock and carries the
selected coalition. -/
def chronologicalClockCoalitionEvent
    (time : ℝ) (coalition : {S : Finset ι // S.Nonempty}) :
    Set (QuittingChronologicalEvent reward) :=
  chronologicalClockEvent time ∩ chronologicalCoalitionEvent coalition

omit [DecidableEq ι] [Nonempty ι] in
theorem continuous_chronologicalEventClock :
    Continuous (chronologicalEventClock :
      QuittingChronologicalEvent reward → ℝ) :=
  continuous_subtype_val.comp continuous_fst

/-- The pushforward of a chronological law by its literal absorption clock. -/
def chronologicalClockLaw
    (law : ProbabilityMeasure (QuittingChronologicalEvent reward)) :
    ProbabilityMeasure ℝ :=
  law.map (continuous_chronologicalEventClock
    (reward := reward)).measurable.aemeasurable

/-- The total clock CDF of a chronological marked law. -/
def chronologicalClockCDF
    (law : ProbabilityMeasure (QuittingChronologicalEvent reward)) : ℝ → ℝ :=
  ProbabilityTheory.cdf (chronologicalClockLaw law)

omit [DecidableEq ι] [Nonempty ι] in
/-- The total clock CDF is exactly the real mass of the chronological clock
event. -/
theorem chronologicalClockCDF_eq_clockEvent_real
    (law : ProbabilityMeasure (QuittingChronologicalEvent reward))
    (time : ℝ) :
    chronologicalClockCDF law time =
      (law : Measure (QuittingChronologicalEvent reward)).real
        (chronologicalClockEvent time) := by
  rw [chronologicalClockCDF, ProbabilityTheory.cdf_eq_real,
    ProbabilityMeasure.measureReal_eq_coe_coeFn]
  unfold chronologicalClockLaw
  rw [ProbabilityMeasure.map_apply _ _ measurableSet_Iic,
    ← ProbabilityMeasure.measureReal_eq_coe_coeFn]
  rfl

omit [DecidableEq ι] [Nonempty ι] in
/-- Weak limits of chronological laws with clock gaps retain the clock-gap
law. -/
theorem hasClockGap_chronologicalClockCDF_of_tendsto
    {index : Type*} {limitFilter : Filter index} [limitFilter.NeBot]
    {laws : index → ProbabilityMeasure (QuittingChronologicalEvent reward)}
    {law : ProbabilityMeasure (QuittingChronologicalEvent reward)}
    (hlaw : Tendsto laws limitFilter (𝓝 law))
    (hsource : ∀ rank, MathUE.HasClockGap
      (chronologicalClockCDF (laws rank))) :
    MathUE.HasClockGap (chronologicalClockCDF law) := by
  unfold chronologicalClockCDF chronologicalClockLaw at hsource ⊢
  apply MathUE.HasClockGap.cdf_of_tendsto
    (limitFilter := limitFilter)
  · exact ProbabilityMeasure.tendsto_map_of_tendsto_of_continuous
      laws law hlaw continuous_chronologicalEventClock
  · exact hsource

omit [DecidableEq ι] [Nonempty ι] in
theorem continuous_chronologicalEventMark :
    Continuous (fun event : QuittingChronologicalEvent reward ↦
      event.2.2.2) :=
  continuous_snd.comp (continuous_snd.comp continuous_snd)

omit [DecidableEq ι] [Nonempty ι] in
theorem isClopen_chronologicalCoalitionEvent
    (coalition : {S : Finset ι // S.Nonempty}) :
    IsClopen (chronologicalCoalitionEvent (reward := reward) coalition) := by
  have hsingleton : IsClopen
      ({⟨coalition⟩} : Set (QuittingChronologicalCoalitionMark ι)) :=
    ⟨isClosed_discrete _, isOpen_discrete _⟩
  exact hsingleton.preimage
    (continuous_chronologicalEventMark (reward := reward))

omit [DecidableEq ι] [Nonempty ι] in
theorem isClosed_chronologicalClockEvent (time : ℝ) :
    IsClosed (chronologicalClockEvent (reward := reward) time) := by
  exact isClosed_Iic.preimage continuous_chronologicalEventClock

omit [DecidableEq ι] [Nonempty ι] in
theorem measurableSet_chronologicalClockCoalitionEvent
    (time : ℝ) (coalition : {S : Finset ι // S.Nonempty}) :
    MeasurableSet
      (chronologicalClockCoalitionEvent (reward := reward) time coalition) :=
  ((isClosed_chronologicalClockEvent (reward := reward) time).measurableSet.inter
    (isClopen_chronologicalCoalitionEvent
      (reward := reward) coalition).1.measurableSet)

/-- A selected coalition retains its true clock; every other coalition is
sent to the cemetery time `2`, outside the path interval. -/
def chronologicalCoalitionClock
    (coalition : {S : Finset ι // S.Nonempty})
    (event : QuittingChronologicalEvent reward) : ℝ :=
  if event.2.2.2 = ⟨coalition⟩ then chronologicalEventClock event else 2

omit [Nonempty ι] in
theorem continuous_chronologicalCoalitionClock
    (coalition : {S : Finset ι // S.Nonempty}) :
    Continuous (chronologicalCoalitionClock
      (reward := reward) coalition) := by
  have hclopen : IsClopen
      {event : QuittingChronologicalEvent reward |
        event.2.2.2 = ⟨coalition⟩} := by
    change IsClopen (chronologicalCoalitionEvent coalition)
    exact isClopen_chronologicalCoalitionEvent coalition
  apply Continuous.if
  · intro event hevent
    rw [hclopen.frontier_eq] at hevent
    exact hevent.elim
  · exact continuous_chronologicalEventClock
  · exact continuous_const

/-- The one-dimensional law used to decode a coalition coordinate. -/
def chronologicalCoalitionClockLaw
    (law : ProbabilityMeasure (QuittingChronologicalEvent reward))
    (coalition : {S : Finset ι // S.Nonempty}) : ProbabilityMeasure ℝ :=
  law.map (continuous_chronologicalCoalitionClock
    (reward := reward) coalition).measurable.aemeasurable

/-- The CDF coordinate decoded from a chronological law. -/
def chronologicalCoalitionCDF
    (law : ProbabilityMeasure (QuittingChronologicalEvent reward))
    (coalition : {S : Finset ι // S.Nonempty}) : ℝ → ℝ :=
  ProbabilityTheory.cdf (chronologicalCoalitionClockLaw law coalition)

omit [Nonempty ι] in
/-- On the path interval, a decoded CDF coordinate is exactly the marked-law
mass below the clock. -/
theorem chronologicalCoalitionCDF_eq_clockCoalitionEvent_real
    (law : ProbabilityMeasure (QuittingChronologicalEvent reward))
    (coalition : {S : Finset ι // S.Nonempty}) {time : ℝ}
    (htime : time ≤ 1) :
    chronologicalCoalitionCDF law coalition time =
      (law : Measure (QuittingChronologicalEvent reward)).real
        (chronologicalClockCoalitionEvent time coalition) := by
  rw [chronologicalCoalitionCDF, ProbabilityTheory.cdf_eq_real,
    ProbabilityMeasure.measureReal_eq_coe_coeFn]
  unfold chronologicalCoalitionClockLaw
  rw [ProbabilityMeasure.map_apply _ _ measurableSet_Iic,
    ← ProbabilityMeasure.measureReal_eq_coe_coeFn]
  congr 1
  ext event
  unfold chronologicalClockCoalitionEvent chronologicalCoalitionClock
    chronologicalClockEvent chronologicalCoalitionEvent chronologicalEventClock
  simp only [Set.mem_preimage, Set.mem_Iic, Set.mem_inter_iff,
    Set.mem_singleton_iff]
  by_cases hmark : event.2.2.2 = ⟨coalition⟩
  · simp [hmark]
  · simp [hmark, show ¬(2 : ℝ) ≤ time by linarith]

omit [Nonempty ι] in
/-- At terminal clock one, the CDF coordinate is exactly the mass of its
clopen coalition fiber. -/
theorem chronologicalCoalitionCDF_one_eq_coalitionEvent_real
    (law : ProbabilityMeasure (QuittingChronologicalEvent reward))
    (coalition : {S : Finset ι // S.Nonempty}) :
    chronologicalCoalitionCDF law coalition 1 =
      (law : Measure (QuittingChronologicalEvent reward)).real
        (chronologicalCoalitionEvent coalition) := by
  rw [chronologicalCoalitionCDF_eq_clockCoalitionEvent_real law coalition le_rfl]
  congr 1
  ext event
  constructor
  · exact fun hevent ↦ hevent.2
  · intro hevent
    exact ⟨event.1.2.2, hevent⟩

omit [DecidableEq ι] [Nonempty ι] in
/-- Coalition marks partition the events below a fixed clock. -/
theorem sum_clockCoalitionEvent_real_eq_clockEvent_real
    (law : ProbabilityMeasure (QuittingChronologicalEvent reward))
    (time : ℝ) :
    (∑ coalition : {S : Finset ι // S.Nonempty},
      (law : Measure (QuittingChronologicalEvent reward)).real
        (chronologicalClockCoalitionEvent time coalition)) =
      (law : Measure (QuittingChronologicalEvent reward)).real
        (chronologicalClockEvent time) := by
  let events := fun coalition : {S : Finset ι // S.Nonempty} ↦
    chronologicalClockCoalitionEvent (reward := reward) time coalition
  have hdisjoint : Set.PairwiseDisjoint
      ((Finset.univ : Finset {S : Finset ι // S.Nonempty}) :
        Set {S : Finset ι // S.Nonempty}) events := by
    intro first _ second _ hne
    change Disjoint (events first) (events second)
    rw [Set.disjoint_left]
    intro event hfirst hsecond
    apply hne
    have hmark :
        (⟨first⟩ : QuittingChronologicalCoalitionMark ι) = ⟨second⟩ := by
      exact hfirst.2.symm.trans hsecond.2
    exact congrArg QuittingChronologicalCoalitionMark.coalition hmark
  have hunion :
      (⋃ coalition ∈ (Finset.univ :
        Finset {S : Finset ι // S.Nonempty}), events coalition) =
        chronologicalClockEvent time := by
    ext event
    simp only [Set.mem_iUnion, Finset.mem_univ, exists_const]
    constructor
    · rintro ⟨coalition, hcoalition⟩
      exact hcoalition.1
    · intro hclock
      refine ⟨event.2.2.2.coalition, hclock, ?_⟩
      change event.2.2.2 = ⟨event.2.2.2.coalition⟩
      cases event.2.2.2
      rfl
  have hmeasure := measure_biUnion_finset hdisjoint
    (fun coalition _ ↦
      (measurableSet_chronologicalClockCoalitionEvent
        (reward := reward) time coalition))
    (μ := (law : Measure (QuittingChronologicalEvent reward)))
  rw [hunion] at hmeasure
  unfold Measure.real
  calc
    (∑ coalition : {S : Finset ι // S.Nonempty},
        ((law : Measure (QuittingChronologicalEvent reward))
          (events coalition)).toReal) =
        (∑ coalition : {S : Finset ι // S.Nonempty},
          (law : Measure (QuittingChronologicalEvent reward))
            (events coalition)).toReal := by
      rw [ENNReal.toReal_sum]
      intro coalition _
      exact measure_ne_top _ _
    _ = ((law : Measure (QuittingChronologicalEvent reward))
        (chronologicalClockEvent time)).toReal :=
      congrArg ENNReal.toReal hmeasure.symm

namespace QuittingFiniteRootSequenceAbsorption

variable {roots : ℕ → ι → PMF Bool}

omit [Nonempty ι] in
/-- The finite chronological law recovers the literal post-jump step
coordinate of its source certificate. -/
theorem chronologicalLaw_clockCoalitionEvent_real_eq_value
    (certificate : QuittingFiniteRootSequenceAbsorption roots)
    (coalition : {S : Finset ι // S.Nonempty}) (time : ℝ) :
    (certificate.chronologicalLaw reward :
        Measure (QuittingChronologicalEvent reward)).real
          (chronologicalClockCoalitionEvent time coalition) =
      certificate.value time coalition := by
  change ((PMF.map (certificate.chronologicalEventAt reward)
    certificate.chronologicalIndexPMF).toMeasure
      (chronologicalClockCoalitionEvent time coalition)).toReal = _
  rw [PMF.toMeasure_map_apply _ _ _
    (measurable_of_finite _) (measurableSet_chronologicalClockCoalitionEvent
      time coalition)]
  rw [PMF.toMeasure_apply_fintype]
  rw [ENNReal.toReal_sum]
  · unfold value
    rw [show (∑ index : certificate.ChronologicalIndex,
        ((certificate.chronologicalEventAt reward ⁻¹'
          chronologicalClockCoalitionEvent time coalition).indicator
            certificate.chronologicalIndexPMF index).toReal) =
        ∑ stage : Fin (certificate.cutoff + 1),
          ∑ mark : QuittingChronologicalCoalitionMark ι,
            ((certificate.chronologicalEventAt reward ⁻¹'
              chronologicalClockCoalitionEvent time coalition).indicator
                certificate.chronologicalIndexPMF (stage, mark)).toReal by
      rw [Fintype.sum_prod_type]]
    rw [← Fin.sum_univ_eq_sum_range
      (fun stage : ℕ ↦
        if quittingRootSequenceClock roots stage ≤ time then
          quittingRootSequenceStageCoalitionMass roots stage coalition else 0)
      (certificate.cutoff + 1)]
    apply Finset.sum_congr rfl
    intro stage _
    rw [Fintype.sum_eq_single ⟨coalition⟩]
    · by_cases hclock : quittingRootSequenceClock roots stage ≤ time
      · simp [Set.indicator, chronologicalClockCoalitionEvent,
          chronologicalClockEvent, chronologicalCoalitionEvent,
          chronologicalEventClock, chronologicalEventAt, hclock,
          chronologicalWeight]
      · simp [Set.indicator, chronologicalClockCoalitionEvent,
          chronologicalClockEvent, chronologicalCoalitionEvent,
          chronologicalEventAt_clock, hclock]
    · intro mark hne
      have hcoalition : mark.coalition ≠ coalition := by
        intro heq
        apply hne
        cases mark
        simp_all
      simp [Set.indicator, chronologicalClockCoalitionEvent,
        chronologicalCoalitionEvent, chronologicalEventAt, hne]
  · intro index _
    simp only [Set.indicator]
    split
    · exact PMF.apply_ne_top certificate.chronologicalIndexPMF index
    · exact ENNReal.zero_ne_top

omit [Nonempty ι] in
/-- The total chronological clock-event mass is exactly the source finite
path total. -/
theorem chronologicalLaw_clockEvent_real_eq_pathTotal
    (certificate : QuittingFiniteRootSequenceAbsorption roots)
    (time : ℝ) :
    (certificate.chronologicalLaw reward :
        Measure (QuittingChronologicalEvent reward)).real
          (chronologicalClockEvent time) =
      pathTotal certificate.cadlagPath time := by
  rw [← sum_clockCoalitionEvent_real_eq_clockEvent_real]
  simp_rw [certificate.chronologicalLaw_clockCoalitionEvent_real_eq_value]
  rfl

omit [Nonempty ι] in
private theorem pathTotal_le_clock_of_lt
    (certificate : QuittingFiniteRootSequenceAbsorption roots)
    {time : ℝ} {stage : ℕ} (hstage : stage ≤ certificate.cutoff)
    (htime : time < quittingRootSequenceClock roots stage) :
    pathTotal certificate.cadlagPath time ≤
      quittingRootSequenceClock roots stage := by
  change (∑ coalition, ∑ earlier ∈ Finset.range (certificate.cutoff + 1),
    if quittingRootSequenceClock roots earlier ≤ time then
      quittingRootSequenceStageCoalitionMass roots earlier coalition else 0) ≤ _
  rw [Finset.sum_comm]
  have hsubset : Finset.range stage ⊆
      Finset.range (certificate.cutoff + 1) :=
    Finset.range_mono (by omega)
  calc
    (∑ earlier ∈ Finset.range (certificate.cutoff + 1),
        ∑ coalition,
          if quittingRootSequenceClock roots earlier ≤ time then
            quittingRootSequenceStageCoalitionMass roots earlier coalition else 0) =
        ∑ earlier ∈ Finset.range stage,
          ∑ coalition,
            if quittingRootSequenceClock roots earlier ≤ time then
              quittingRootSequenceStageCoalitionMass roots earlier coalition else 0 := by
      symm
      apply Finset.sum_subset hsubset
      intro earlier _ hnotEarlier
      have hearler : stage ≤ earlier := by
        simpa only [Finset.mem_range, not_lt] using hnotEarlier
      have hclock : quittingRootSequenceClock roots stage ≤
          quittingRootSequenceClock roots earlier :=
        monotone_quittingRootSequenceClock roots hearler
      simp [not_le_of_gt (htime.trans_le hclock)]
    _ ≤ ∑ earlier ∈ Finset.range stage,
        ∑ coalition,
          quittingRootSequenceStageCoalitionMass roots earlier coalition := by
      apply Finset.sum_le_sum
      intro earlier _
      apply Finset.sum_le_sum
      intro coalition _
      split
      · exact le_rfl
      · exact quittingRootSequenceStageCoalitionMass_nonneg
          roots earlier coalition
    _ = quittingRootSequenceClock roots stage := by
      rw [Finset.sum_comm]
      exact sum_quittingRootSequenceCumulativeCoalitionMass roots stage

omit [Nonempty ι] in
/-- The literal finite source clock gap: before the current total mass is
reached, moving the clock forward cannot change any coalition mass. -/
theorem pathTotal_eq_of_le_of_lt_pathTotal
    (certificate : QuittingFiniteRootSequenceAbsorption roots)
    {time later : ℝ} (htimeLater : time ≤ later)
    (hlaterGap : later < pathTotal certificate.cadlagPath time) :
    pathTotal certificate.cadlagPath later =
      pathTotal certificate.cadlagPath time := by
  unfold pathTotal
  apply Finset.sum_congr rfl
  intro coalition _
  change certificate.value later coalition = certificate.value time coalition
  unfold value
  apply Finset.sum_congr rfl
  intro stage hstage
  by_cases htimeClock : quittingRootSequenceClock roots stage ≤ time
  · rw [if_pos htimeClock, if_pos (htimeClock.trans htimeLater)]
  · have hlaterClock : ¬quittingRootSequenceClock roots stage ≤ later := by
      intro hclock
      have hstageLt : stage < certificate.cutoff + 1 :=
        Finset.mem_range.mp hstage
      have hstageLe : stage ≤ certificate.cutoff := by
        omega
      have htotalLe := certificate.pathTotal_le_clock_of_lt hstageLe
        (lt_of_not_ge htimeClock)
      linarith
    rw [if_neg htimeClock, if_neg hlaterClock]

omit [Nonempty ι] in
/-- The same canonical clock-gap law stated directly for the total CDF of
the finite chronological marked law. -/
theorem chronologicalLaw_clockEvent_real_eq_of_le_of_lt
    (certificate : QuittingFiniteRootSequenceAbsorption roots)
    {time later : ℝ} (htimeLater : time ≤ later)
    (hlaterGap : later <
      (certificate.chronologicalLaw reward :
        Measure (QuittingChronologicalEvent reward)).real
          (chronologicalClockEvent time)) :
    (certificate.chronologicalLaw reward :
        Measure (QuittingChronologicalEvent reward)).real
          (chronologicalClockEvent later) =
      (certificate.chronologicalLaw reward :
        Measure (QuittingChronologicalEvent reward)).real
          (chronologicalClockEvent time) := by
  simp_rw [certificate.chronologicalLaw_clockEvent_real_eq_pathTotal] at *
  exact certificate.pathTotal_eq_of_le_of_lt_pathTotal
    htimeLater hlaterGap

omit [Nonempty ι] in
/-- Every canonical finite chronological law has the global clock-gap
property. -/
theorem hasClockGap_chronologicalClockCDF
    (certificate : QuittingFiniteRootSequenceAbsorption roots) :
    MathUE.HasClockGap
      (chronologicalClockCDF (certificate.chronologicalLaw reward)) := by
  intro time later htimeLater hlaterGap
  simp_rw [chronologicalClockCDF_eq_clockEvent_real] at hlaterGap ⊢
  exact certificate.chronologicalLaw_clockEvent_real_eq_of_le_of_lt
    htimeLater hlaterGap

end QuittingFiniteRootSequenceAbsorption

/-- A chronological marked law decodes to a coordinatewise càdlàg path. -/
def chronologicalCadlagPath
    (law : ProbabilityMeasure (QuittingChronologicalEvent reward)) :
    CadlagPath (ι := ι) where
  value := fun time coalition ↦ chronologicalCoalitionCDF law coalition time
  leftValue := fun time coalition ↦
    Function.leftLim (chronologicalCoalitionCDF law coalition) time
  value_mem := by
    intro time _ coalition
    exact ⟨ProbabilityTheory.cdf_nonneg _ _,
      ProbabilityTheory.cdf_le_one _ _⟩
  monotone := by
    intro coalition first _ second _ hle
    exact ProbabilityTheory.monotone_cdf
      (chronologicalCoalitionClockLaw law coalition) hle
  right_continuous := by
    intro coalition time _
    apply (ProbabilityTheory.cdf _).right_continuous time |>.mono_left
    exact nhdsWithin_mono _ (by intro s hs; exact hs.1)
  left_limit := by
    intro coalition time _
    apply (ProbabilityTheory.monotone_cdf _).tendsto_leftLim time |>.mono_left
    apply nhdsWithin_mono
    intro s hs
    exact lt_of_le_of_ne hs.1.2 hs.2
  left_zero := by
    intro coalition
    apply leftLim_eq_of_tendsto
    apply tendsto_const_nhds.congr'
    filter_upwards [self_mem_nhdsWithin] with time htime
    rw [chronologicalCoalitionCDF, ProbabilityTheory.cdf_eq_real]
    have hzero :
        (chronologicalCoalitionClockLaw law coalition : Measure ℝ)
          (Set.Iic time) = (0 : ENNReal) := by
      have hempty :
          chronologicalCoalitionClock (reward := reward) coalition ⁻¹'
              Set.Iic time = ∅ := by
        ext event
        constructor
        · intro hle
          have hnonneg : 0 ≤ chronologicalCoalitionClock coalition event := by
            unfold chronologicalCoalitionClock
            split
            · exact event.1.2.1
            · norm_num
          exact (not_le_of_gt htime (hnonneg.trans hle)).elim
        · intro hempty
          exact hempty.elim
      calc
        (chronologicalCoalitionClockLaw law coalition : Measure ℝ)
            (Set.Iic time) =
            (law (chronologicalCoalitionClock coalition ⁻¹' Set.Iic time) :
              ENNReal) := by
          unfold chronologicalCoalitionClockLaw
          rw [← ProbabilityMeasure.ennreal_coeFn_eq_coeFn_toMeasure]
          exact congrArg (fun mass : NNReal ↦ (mass : ENNReal)) <|
            ProbabilityMeasure.map_apply law
              (continuous_chronologicalCoalitionClock
                (reward := reward) coalition).measurable.aemeasurable
              (A := Set.Iic time) measurableSet_Iic
        _ = 0 := by simp [hempty]
    exact (congrArg ENNReal.toReal hzero).symm

omit [Nonempty ι] in
/-- The total decoded path mass is exactly the marked-law mass below the
clock. -/
theorem pathTotal_chronologicalCadlagPath_eq_clockEvent_real
    (law : ProbabilityMeasure (QuittingChronologicalEvent reward))
    {time : ℝ} (htime : time ≤ 1) :
    pathTotal (chronologicalCadlagPath law) time =
      (law : Measure (QuittingChronologicalEvent reward)).real
        (chronologicalClockEvent time) := by
  unfold pathTotal chronologicalCadlagPath
  simp_rw [chronologicalCoalitionCDF_eq_clockCoalitionEvent_real
    law _ htime]
  exact sum_clockCoalitionEvent_real_eq_clockEvent_real law time

omit [Nonempty ι] in
/-- On the path interval, decoded total mass is the total clock CDF. -/
theorem pathTotal_chronologicalCadlagPath_eq_chronologicalClockCDF
    (law : ProbabilityMeasure (QuittingChronologicalEvent reward))
    {time : ℝ} (htime : time ≤ 1) :
    pathTotal (chronologicalCadlagPath law) time =
      chronologicalClockCDF law time := by
  rw [pathTotal_chronologicalCadlagPath_eq_clockEvent_real law htime,
    chronologicalClockCDF_eq_clockEvent_real]

namespace QuittingFiniteRootSequenceAbsorption

variable {roots : ℕ → ι → PMF Bool}

omit [Nonempty ι] in
/-- The decoded finite law is the original finite post-jump path on
`[0,1]`. -/
theorem chronologicalCadlagPath_value_eq
    (certificate : QuittingFiniteRootSequenceAbsorption roots)
    (time : ℝ) (htime : time ∈ Set.Icc (0 : ℝ) 1)
    (coalition : {S : Finset ι // S.Nonempty}) :
    (chronologicalCadlagPath (certificate.chronologicalLaw reward)).value
        time coalition = certificate.value time coalition := by
  change chronologicalCoalitionCDF
      (certificate.chronologicalLaw reward) coalition time = _
  rw [chronologicalCoalitionCDF_eq_clockCoalitionEvent_real _ _ htime.2]
  exact certificate.chronologicalLaw_clockCoalitionEvent_real_eq_value
    coalition time

end QuittingFiniteRootSequenceAbsorption

omit [Nonempty ι] in
/-- Weak limits of finite chronological laws retain clock domination, hence
the decoded càdlàg path satisfies absorption-path axiom A1. -/
theorem le_pathTotal_chronologicalCadlagPath_of_tendsto
    {roots : ℕ → ℕ → ι → PMF Bool}
    (certificates : ∀ rank,
      QuittingFiniteRootSequenceAbsorption (roots rank))
    (law : ProbabilityMeasure (QuittingChronologicalEvent reward))
    (hlaw : Tendsto
      (fun rank ↦ (certificates rank).chronologicalLaw reward)
      atTop (𝓝 law))
    (time : ℝ) (htime : time ∈ Set.Icc (0 : ℝ) 1) :
    time ≤ pathTotal (chronologicalCadlagPath law) time := by
  rw [pathTotal_chronologicalCadlagPath_eq_clockEvent_real law htime.2]
  let closedEvent := chronologicalClockEvent
    (reward := reward) time
  have hsource (rank : ℕ) :
      time ≤ ((certificates rank).chronologicalLaw reward :
        Measure (QuittingChronologicalEvent reward)).real closedEvent := by
    rw [← sum_clockCoalitionEvent_real_eq_clockEvent_real]
    simp_rw [(certificates rank).chronologicalLaw_clockCoalitionEvent_real_eq_value]
    change time ≤ pathTotal (certificates rank).cadlagPath time
    exact (certificates rank).le_pathTotal_cadlagPath htime
  have hsourceENNReal (rank : ℕ) :
      ENNReal.ofReal time ≤
        ((certificates rank).chronologicalLaw reward :
          Measure (QuittingChronologicalEvent reward)) closedEvent := by
    rw [← ENNReal.ofReal_toReal
      (measure_ne_top
        ((certificates rank).chronologicalLaw reward :
          Measure (QuittingChronologicalEvent reward)) closedEvent)]
    exact ENNReal.ofReal_le_ofReal (hsource rank)
  have hlower : ENNReal.ofReal time ≤
      Filter.limsup (fun rank ↦
        ((certificates rank).chronologicalLaw reward :
          Measure (QuittingChronologicalEvent reward)) closedEvent) atTop :=
    Filter.le_limsup_of_frequently_le
      (Filter.Frequently.of_forall hsourceENNReal)
  have hport := ProbabilityMeasure.limsup_measure_closed_le_of_tendsto
    hlaw (isClosed_chronologicalClockEvent (reward := reward) time)
  have hENNReal : ENNReal.ofReal time ≤
      (law : Measure (QuittingChronologicalEvent reward)) closedEvent :=
    hlower.trans hport
  unfold Measure.real
  change time ≤ ((law : Measure (QuittingChronologicalEvent reward))
    closedEvent).toReal
  calc
    time = (ENNReal.ofReal time).toReal :=
      (ENNReal.toReal_ofReal htime.1).symm
    _ ≤ ((law : Measure (QuittingChronologicalEvent reward))
        closedEvent).toReal :=
      (ENNReal.toReal_le_toReal ENNReal.ofReal_ne_top
        (measure_ne_top (law : Measure (QuittingChronologicalEvent reward))
          closedEvent)).2 hENNReal

end GameTheory.QuittingAbsorptionPath
