/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.AbsorptionPath.WeakPathConvergence

/-!
# Source boundary localization at a limit clock time

For a fixed clock time of a weak limit, evaluate each source path's total mass
at that time.  This produces a literal source partition boundary approaching
the limit time.  The source boundary can be either a continuous clock time or
a jump, and that alternative may vary with the source index.  At jump indices,
the normalized product row converges to all-Continue.
-/

noncomputable section

namespace GameTheory.QuittingAbsorptionPath

open Filter Set Math.PMFProduct Math.ProbabilityMassFunction
open scoped Topology

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- The product row attached to a partition boundary.  Continuous clock
boundaries carry the all-Continue row; jump boundaries carry their literal
normalized jump row. -/
def absorptionPathBoundaryRoot
    (path : AbsorptionPath (ι := ι)) (time : ℝ) : ι → PMF Bool := by
  classical
  exact if time ∈ pathJumps path.1 then absorptionPathJumpRoot path time
    else quittingAllContinueRoot

@[simp] theorem absorptionPathBoundaryRoot_of_mem_pathJumps
    (path : AbsorptionPath (ι := ι)) {time : ℝ}
    (htime : time ∈ pathJumps path.1) :
    absorptionPathBoundaryRoot path time =
      absorptionPathJumpRoot path time := by
  simp [absorptionPathBoundaryRoot, htime]

@[simp] theorem absorptionPathBoundaryRoot_of_not_mem_pathJumps
    (path : AbsorptionPath (ι := ι)) {time : ℝ}
    (htime : time ∉ pathJumps path.1) :
    absorptionPathBoundaryRoot path time = quittingAllContinueRoot := by
  simp [absorptionPathBoundaryRoot, htime]

/-- Literal source boundary data at a nonterminal limit clock time.  No fixed
choice between clock and jump source boundaries is imposed across indices. -/
structure LimitClockBoundarySourceApproximation
    (sequence : ℕ → AbsorptionPath (ι := ι))
    (limit : AbsorptionPath (ι := ι)) (time : ℝ) where
  sourceTimes : ℕ → ℝ
  source_boundary : ∀ index,
    sourceTimes index ∈ partitionBoundaryTimes (sequence index)
  eventually_source_total_lt_one :
    ∀ᶠ index in atTop,
      pathTotal (sequence index).1 (sourceTimes index) < 1
  times_tendsto : Tendsto sourceTimes atTop (nhds time)
  values_tendsto : ∀ coalition,
    Tendsto (fun index ↦
      (sequence index).1.value (sourceTimes index) coalition) atTop
      (nhds (limit.1.value time coalition))
  leftValues_tendsto : ∀ coalition,
    Tendsto (fun index ↦
      (sequence index).1.leftValue (sourceTimes index) coalition) atTop
      (nhds (limit.1.value time coalition))
  roots_tendsto : Tendsto (fun index ↦ quittingSimplexOfRoot
      (absorptionPathBoundaryRoot (sequence index) (sourceTimes index)))
    atTop (nhds (quittingSimplexOfRoot
      (quittingAllContinueRoot : ι → PMF Bool)))

private theorem limitClock_not_mem_pathJumps
    {limit : AbsorptionPath (ι := ι)} {time : ℝ}
    (htime : time ∈ pathTimes limit.1) :
    time ∉ pathJumps limit.1 := by
  intro hjump
  have hstrict := lt_pathTotal_of_mem_pathJumps limit hjump
  rw [htime.2] at hstrict
  exact (lt_irrefl time hstrict).elim

/-- A coordinate at a clock-interval point is no larger than its left limit
at the literal total-mass boundary generated by that point. -/
theorem value_le_leftValue_at_pathTotal_of_unitBounded
    (path : AbsorptionPath (ι := ι))
    (hbounded : HasUnitBoundedTotalMass path)
    {time : ℝ} (htime : time ∈ Icc (0 : ℝ) 1)
    (coalition : {S : Finset ι // S.Nonempty}) :
    path.1.value time coalition ≤
      path.1.leftValue (pathTotal path.1 time) coalition := by
  have htimeTotal : time ≤ pathTotal path.1 time :=
    path.property.1 time htime
  have htotalMem : pathTotal path.1 time ∈ Icc (0 : ℝ) 1 :=
    ⟨htime.1.trans htimeTotal, hbounded time htime⟩
  rcases htimeTotal.eq_or_lt with heq | hstrict
  · have hnotJump : time ∉ pathJumps path.1 := by
      intro hjump
      have hjumpStrict := lt_pathTotal_of_mem_pathJumps path hjump
      rw [← heq] at hjumpStrict
      exact (lt_irrefl time hjumpStrict).elim
    have hzero : pathJump path.1 time coalition = 0 := by
      by_contra hnonzero
      exact hnotJump ⟨htime, coalition, hnonzero⟩
    rw [← heq]
    unfold pathJump at hzero
    linarith
  · exact path.1.value_le_leftValue_of_lt coalition htime htotalMem hstrict

private theorem boundaryRoot_absorptionMass_eq
    (path : AbsorptionPath (ι := ι)) {time : ℝ}
    (hboundary : time ∈ partitionBoundaryTimes path) :
    quittingRootAbsorptionMass (absorptionPathBoundaryRoot path time) =
      (pathTotal path.1 time - time) / (1 - time) := by
  rcases hboundary with hjump | hclock
  · rw [absorptionPathBoundaryRoot_of_mem_pathJumps path hjump]
    calc
      quittingRootAbsorptionMass (absorptionPathJumpRoot path time) =
          ∑ coalition : {S : Finset ι // S.Nonempty},
            quittingRootCoalitionMass
              (absorptionPathJumpRoot path time) coalition.1 := by
        rw [quittingRootAbsorptionMass]
        rw [← quittingRootCoalitionMass_sum_nonempty]
        rw [← Finset.sum_subtype (Finset.univ.erase (∅ : Finset ι))]
        intro coalition
        simp [Finset.nonempty_iff_ne_empty]
      _ = ∑ coalition : {S : Finset ι // S.Nonempty},
          pathJump path.1 time coalition / (1 - time) := by
        apply Finset.sum_congr rfl
        intro coalition _
        exact (absorptionPathJumpRoot_relation path hjump coalition).symm
      _ = (∑ coalition : {S : Finset ι // S.Nonempty},
          pathJump path.1 time coalition) / (1 - time) := by
        rw [Finset.sum_div]
      _ = (pathTotal path.1 time - time) / (1 - time) := by
        rw [← pathTotal_sub_pathLeftTotal_eq_sum_pathJump,
          pathLeftTotal_eq_of_mem_pathJumps path hjump]
  · have hnotJump : time ∉ pathJumps path.1 := by
      intro hjump
      have hstrict := lt_pathTotal_of_mem_pathJumps path hjump
      rw [hclock.2] at hstrict
      exact (lt_irrefl time hstrict).elim
    rw [absorptionPathBoundaryRoot_of_not_mem_pathJumps path hnotJump,
      quittingRootAbsorptionMass,
      quittingStationaryContinueMass_allContinueRoot, hclock.2]
    simp

private theorem boundaryRoots_tendsto_allContinue
    {paths : ℕ → AbsorptionPath (ι := ι)}
    {limit : AbsorptionPath (ι := ι)}
    {sourceTimes : ℕ → ℝ} {time : ℝ}
    (hboundary : ∀ index,
      sourceTimes index ∈ partitionBoundaryTimes (paths index))
    (htimes : Tendsto sourceTimes atTop (nhds time))
    (hvalues : ∀ coalition,
      Tendsto (fun index ↦
        (paths index).1.value (sourceTimes index) coalition) atTop
        (nhds (limit.1.value time coalition)))
    (htotal : pathTotal limit.1 time = time)
    (htimeOne : time ≠ 1) :
    Tendsto (fun index ↦ quittingSimplexOfRoot
        (absorptionPathBoundaryRoot (paths index) (sourceTimes index)))
      atTop (nhds (quittingSimplexOfRoot
        (quittingAllContinueRoot : ι → PMF Bool))) := by
  have hsourceTotal : Tendsto (fun index ↦
      pathTotal (paths index).1 (sourceTimes index)) atTop
      (nhds (pathTotal limit.1 time)) := by
    unfold pathTotal
    exact tendsto_finsetSum Finset.univ fun coalition _ ↦ hvalues coalition
  have habsorption : Tendsto (fun index ↦
      quittingRootAbsorptionMass
        (absorptionPathBoundaryRoot (paths index) (sourceTimes index)))
      atTop (nhds 0) := by
    have hquotient :=
      (hsourceTotal.sub htimes).div (tendsto_const_nhds.sub htimes)
        (sub_ne_zero.mpr htimeOne.symm)
    simpa only [htotal, sub_self, zero_div] using
      hquotient.congr' (Filter.Eventually.of_forall fun index ↦
        (boundaryRoot_absorptionMass_eq (paths index)
          (hboundary index)).symm)
  apply tendsto_pi_nhds.2
  intro player
  rw [tendsto_subtype_rng]
  apply tendsto_pi_nhds.2
  intro action
  have hquit : Tendsto (fun index ↦
      ((absorptionPathBoundaryRoot (paths index) (sourceTimes index)
        player) true).toReal) atTop (nhds 0) := by
    apply squeeze_zero'
    · exact Filter.Eventually.of_forall fun index ↦ ENNReal.toReal_nonneg
    · exact Filter.Eventually.of_forall fun index ↦
        quittingQuitProbability_le_absorptionMass
          (absorptionPathBoundaryRoot (paths index) (sourceTimes index)) player
    · exact habsorption
  cases action with
  | false =>
      change Tendsto (fun index ↦
          ((absorptionPathBoundaryRoot (paths index) (sourceTimes index)
            player) false).toReal) atTop
        (nhds ((quittingAllContinueRoot player false).toReal))
      simpa [pmfBool_false_toReal, quittingAllContinueRoot] using
        (tendsto_const_nhds.sub hquit :
          Tendsto (fun index ↦ 1 -
            ((absorptionPathBoundaryRoot (paths index) (sourceTimes index)
              player) true).toReal) atTop (nhds (1 - 0)))
  | true =>
      change Tendsto (fun index ↦
          ((absorptionPathBoundaryRoot (paths index) (sourceTimes index)
            player) true).toReal) atTop
        (nhds ((quittingAllContinueRoot player true).toReal))
      simpa [quittingAllContinueRoot] using hquit

/-- Unit-bounded source paths and weak convergence produce a literal mixed
clock/jump boundary localization at every nonterminal limit clock time. -/
theorem nonempty_limitClockBoundarySourceApproximation
    {paths : ℕ → AbsorptionPath (ι := ι)}
    {limit : AbsorptionPath (ι := ι)}
    (hsourceBounded : ∀ index, HasUnitBoundedTotalMass (paths index))
    (hweak : WeaklyConvergesAbsorptionPaths paths limit)
    {time : ℝ} (htime : time ∈ pathTimes limit.1)
    (htimeOne : time ≠ 1) :
    Nonempty (LimitClockBoundarySourceApproximation paths limit time) := by
  let sourceTimes := fun index ↦ pathTotal (paths index).1 time
  have hnotJump : time ∉ pathJumps limit.1 :=
    limitClock_not_mem_pathJumps htime
  have htimesTendsto : Tendsto sourceTimes atTop (nhds time) := by
    rw [← htime.2]
    unfold sourceTimes pathTotal
    exact tendsto_finsetSum Finset.univ fun coalition _ ↦
      tendsto_pi_nhds.mp (hweak time htime.1 hnotJump) coalition
  have hsourceTimesMem (index : ℕ) :
      sourceTimes index ∈ Icc (0 : ℝ) 1 := by
    exact ⟨htime.1.1.trans ((paths index).property.1 time htime.1),
      hsourceBounded index time htime.1⟩
  have hsourceBoundary (index : ℕ) :
      sourceTimes index ∈ partitionBoundaryTimes (paths index) :=
    pathTotal_mem_partitionBoundaryTimes (paths index) (hsourceBounded index)
      htime.1
  have hvalues : ∀ coalition,
      Tendsto (fun index ↦
        (paths index).1.value (sourceTimes index) coalition) atTop
        (nhds (limit.1.value time coalition)) := by
    intro coalition
    exact hweak.value_tendsto_of_tendsto_fromAbove htime.1 htimeOne
      hnotJump hsourceTimesMem
      (fun index ↦ (paths index).property.1 time htime.1)
      htimesTendsto coalition
  have hleftValues : ∀ coalition,
      Tendsto (fun index ↦
        (paths index).1.leftValue (sourceTimes index) coalition) atTop
        (nhds (limit.1.value time coalition)) := by
    intro coalition
    exact tendsto_of_tendsto_of_tendsto_of_le_of_le
      (tendsto_pi_nhds.mp (hweak time htime.1 hnotJump) coalition)
      (hvalues coalition)
      (fun index ↦ value_le_leftValue_at_pathTotal_of_unitBounded (paths index)
        (hsourceBounded index) htime.1 coalition)
      (fun index ↦ (paths index).1.leftValue_le_value coalition
        (hsourceTimesMem index))
  have hsourceTotalTendsto : Tendsto (fun index ↦
      pathTotal (paths index).1 (sourceTimes index)) atTop (nhds time) := by
    rw [← htime.2]
    unfold pathTotal
    exact tendsto_finsetSum Finset.univ fun coalition _ ↦ hvalues coalition
  refine ⟨{
    sourceTimes := sourceTimes
    source_boundary := hsourceBoundary
    eventually_source_total_lt_one := ?_
    times_tendsto := htimesTendsto
    values_tendsto := hvalues
    leftValues_tendsto := hleftValues
    roots_tendsto := boundaryRoots_tendsto_allContinue hsourceBoundary
      htimesTendsto hvalues htime.2 htimeOne }⟩
  exact hsourceTotalTendsto.eventually (Iio_mem_nhds
    (lt_of_le_of_ne htime.1.2 htimeOne))

/-- Literal source boundaries approaching a clock time of an unbundled
càdlàg weak limit. -/
structure CadlagLimitClockBoundarySourceApproximation
    (sequence : ℕ → AbsorptionPath (ι := ι))
    (limit : CadlagPath (ι := ι)) (time : ℝ) where
  sourceTimes : ℕ → ℝ
  source_boundary : ∀ index,
    sourceTimes index ∈ partitionBoundaryTimes (sequence index)
  times_tendsto : Tendsto sourceTimes atTop (nhds time)
  leftValues_tendsto : ∀ coalition,
    Tendsto (fun index ↦
      (sequence index).1.leftValue (sourceTimes index) coalition) atTop
      (nhds (limit.value time coalition))

omit [DecidableEq ι] in
/-- Clock domination makes a fixed point of an unbundled càdlàg path a
continuity time. -/
theorem not_mem_pathJumps_of_clock_eq_pathTotal
    (path : CadlagPath (ι := ι))
    (hclock : ∀ point ∈ Icc (0 : ℝ) 1, point ≤ pathTotal path point)
    {time : ℝ} (htime : time ∈ Icc (0 : ℝ) 1)
    (hfixed : pathTotal path time = time) :
    time ∉ pathJumps path := by
  intro hjump
  have hleft : time ≤ pathLeftTotal path time :=
    clock_le_pathLeftTotal_of_clock_le_pathTotal path hclock htime
  have hstrict := pathLeftTotal_lt_pathTotal_of_mem_pathJumps path hjump
  rw [hfixed] at hstrict
  exact (not_lt_of_ge hleft hstrict).elim

/-- Unit-bounded source paths weakly converging to an unbundled
clock-dominating càdlàg path produce literal source boundaries at every
nonterminal fixed point. -/
theorem nonempty_cadlagLimitClockBoundarySourceApproximation
    {paths : ℕ → AbsorptionPath (ι := ι)}
    {limit : CadlagPath (ι := ι)}
    (hclock : ∀ point ∈ Icc (0 : ℝ) 1, point ≤ pathTotal limit point)
    (hsourceBounded : ∀ index, HasUnitBoundedTotalMass (paths index))
    (hweak : WeaklyConvergesAbsorptionPathsToCadlag paths limit)
    {time : ℝ} (htime : time ∈ pathTimes limit)
    (htimeOne : time ≠ 1) :
    Nonempty (CadlagLimitClockBoundarySourceApproximation paths limit time) := by
  let sourceTimes := fun index ↦ pathTotal (paths index).1 time
  have hnotJump : time ∉ pathJumps limit :=
    not_mem_pathJumps_of_clock_eq_pathTotal limit hclock htime.1 htime.2
  have htimesTendsto : Tendsto sourceTimes atTop (nhds time) := by
    rw [← htime.2]
    unfold sourceTimes pathTotal
    exact tendsto_finsetSum Finset.univ fun coalition _ ↦
      tendsto_pi_nhds.mp (hweak time htime.1 hnotJump) coalition
  have hsourceTimesMem (index : ℕ) :
      sourceTimes index ∈ Icc (0 : ℝ) 1 :=
    ⟨htime.1.1.trans ((paths index).property.1 time htime.1),
      hsourceBounded index time htime.1⟩
  have hsourceBoundary (index : ℕ) :
      sourceTimes index ∈ partitionBoundaryTimes (paths index) :=
    pathTotal_mem_partitionBoundaryTimes (paths index) (hsourceBounded index)
      htime.1
  have hvalues : ∀ coalition,
      Tendsto (fun index ↦
        (paths index).1.value (sourceTimes index) coalition) atTop
        (nhds (limit.value time coalition)) := by
    intro coalition
    exact hweak.value_tendsto_of_tendsto_fromAbove htime.1 htimeOne
      hnotJump hsourceTimesMem
      (fun index ↦ (paths index).property.1 time htime.1)
      htimesTendsto coalition
  have hleftValues : ∀ coalition,
      Tendsto (fun index ↦
        (paths index).1.leftValue (sourceTimes index) coalition) atTop
        (nhds (limit.value time coalition)) := by
    intro coalition
    exact tendsto_of_tendsto_of_tendsto_of_le_of_le
      (tendsto_pi_nhds.mp (hweak time htime.1 hnotJump) coalition)
      (hvalues coalition)
      (fun index ↦ value_le_leftValue_at_pathTotal_of_unitBounded (paths index)
        (hsourceBounded index) htime.1 coalition)
      (fun index ↦ (paths index).1.leftValue_le_value coalition
        (hsourceTimesMem index))
  exact ⟨{
    sourceTimes := sourceTimes
    source_boundary := hsourceBoundary
    times_tendsto := htimesTendsto
    leftValues_tendsto := hleftValues
  }⟩


end GameTheory.QuittingAbsorptionPath
