/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.AbsorptionPath.ContinuousPath
import UniformEquilibrium.Quitting.Classification.LCP.MatrixClasses

/-!
# Linear continuous absorption paths

A simplex distribution on players induces the continuous path that assigns
mass `t zᵢ` to the coalition in which only player `i` quits.  This module
computes its payoff and proves that a homogeneous singleton-LCP solution makes
the path sequentially zero-perfect.  It is the explicit homogeneous branch of
the continuous-path construction; no differential inclusion is used.
-/

noncomputable section

namespace GameTheory.QuittingAbsorptionPath

open Filter Math.LinearProgramming Set
open QuittingLCPClassification
open scoped Topology

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- Push a player distribution onto the singleton quitting coalitions. -/
def singletonCoalitionDistribution (weight : stdSimplex ℝ ι) :
    stdSimplex ℝ {S : Finset ι // S.Nonempty} where
  val coalition := ∑ owner,
    if coalition = quittingProjectiveSingletonTerminal owner then
      weight owner else 0
  property := by
    constructor
    · intro coalition
      apply Finset.sum_nonneg
      intro owner _
      split
      · exact weight.property.1 owner
      · exact le_rfl
    · rw [Finset.sum_comm]
      simp

/-- The linear singleton path generated by a player distribution. -/
def linearSingletonCadlagPath (weight : stdSimplex ℝ ι) :
    CadlagPath (ι := ι) where
  value t coalition := t * singletonCoalitionDistribution weight coalition
  leftValue t coalition := t * singletonCoalitionDistribution weight coalition
  value_mem := by
    intro t ht coalition
    constructor
    · exact mul_nonneg ht.1 (stdSimplex.zero_le _ _)
    · exact mul_le_one₀ ht.2 (stdSimplex.zero_le _ _)
        (stdSimplex.le_one _ _)
  monotone := by
    intro coalition s hs t ht hst
    exact mul_le_mul_of_nonneg_right hst (stdSimplex.zero_le _ _)
  right_continuous := by
    intro coalition t _
    exact (continuousAt_id.mul continuousAt_const).tendsto.mono_left inf_le_left
  left_limit := by
    intro coalition t _
    exact (continuousAt_id.mul continuousAt_const).tendsto.mono_left inf_le_left
  left_zero := by simp

@[simp] theorem pathTotal_linearSingletonCadlagPath
    (weight : stdSimplex ℝ ι) (t : ℝ) :
    pathTotal (linearSingletonCadlagPath weight) t = t := by
  simp [pathTotal, linearSingletonCadlagPath, ← Finset.mul_sum]

@[simp] theorem pathJump_linearSingletonCadlagPath
    (weight : stdSimplex ℝ ι) (t : ℝ)
    (coalition : {S : Finset ι // S.Nonempty}) :
    pathJump (linearSingletonCadlagPath weight) t coalition = 0 := by
  simp [pathJump, linearSingletonCadlagPath]

theorem pathTimes_linearSingletonCadlagPath (weight : stdSimplex ℝ ι) :
    pathTimes (linearSingletonCadlagPath weight) = Icc 0 1 := by
  ext t
  simp [pathTimes]

theorem pathJumps_linearSingletonCadlagPath (weight : stdSimplex ℝ ι) :
    pathJumps (linearSingletonCadlagPath weight) = ∅ := by
  ext t
  simp [pathJumps]

private theorem singletonCoalitionDistribution_eq_zero_of_card_ne_one
    (weight : stdSimplex ℝ ι)
    (coalition : {S : Finset ι // S.Nonempty}) (hcard : coalition.1.card ≠ 1) :
    singletonCoalitionDistribution weight coalition = 0 := by
  unfold singletonCoalitionDistribution
  apply Finset.sum_eq_zero
  intro owner _
  have hne : coalition ≠ quittingProjectiveSingletonTerminal owner := by
    intro heq
    apply hcard
    rw [congrArg (fun S => S.1.card) heq]
    simp [quittingProjectiveSingletonTerminal]
  simp [hne]

private theorem pathRightDerivative_linearSingletonCadlagPath
    (weight : stdSimplex ℝ ι) {t : ℝ} (ht : t < 1)
    (coalition : {S : Finset ι // S.Nonempty}) :
    pathRightDerivative (linearSingletonCadlagPath weight) t coalition =
      singletonCoalitionDistribution weight coalition := by
  letI : NeBot (nhdsWithin t (Ioo t 1)) := left_nhdsWithin_Ioo_neBot ht
  unfold pathRightDerivative linearSingletonCadlagPath
  have hquotient : ∀ᶠ s in nhdsWithin t (Ioo t 1),
      (s * singletonCoalitionDistribution weight coalition -
          t * singletonCoalitionDistribution weight coalition) / (s - t) =
        singletonCoalitionDistribution weight coalition := by
    filter_upwards [self_mem_nhdsWithin] with s hs
    have hne : s - t ≠ 0 := sub_ne_zero.mpr hs.1.ne'
    apply (div_eq_iff hne).2
    ring
  exact (Filter.liminf_congr hquotient).trans
    (Filter.liminf_const (singletonCoalitionDistribution weight coalition))

/-- The linear singleton path satisfies all four absorption-path conditions. -/
theorem isAbsorptionPath_linearSingletonCadlagPath
    (weight : stdSimplex ℝ ι) :
    IsAbsorptionPath (linearSingletonCadlagPath weight) := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · intro t ht
    simp
  · intro t ht
    have htime : t ∈ pathTimes (linearSingletonCadlagPath weight) := by
      rw [pathTimes_linearSingletonCadlagPath]
      exact ht.1
    exact (ht.2 (Or.inr htime)).elim
  · intro t ht
    rw [pathJumps_linearSingletonCadlagPath] at ht
    exact ht.elim
  · intro t ht hneOne coalition hderivative
    by_contra hcard
    apply hderivative
    rw [pathRightDerivative_linearSingletonCadlagPath weight (lt_of_le_of_ne
      ht.1.2 hneOne)]
    exact singletonCoalitionDistribution_eq_zero_of_card_ne_one
      weight coalition hcard

/-- The bundled linear singleton absorption path. -/
def linearSingletonAbsorptionPath (weight : stdSimplex ℝ ι) :
    AbsorptionPath (ι := ι) :=
  ⟨linearSingletonCadlagPath weight,
    isAbsorptionPath_linearSingletonCadlagPath weight⟩

/-- The linear singleton absorption path is continuous. -/
theorem linearSingletonAbsorptionPath_continuous
    (weight : stdSimplex ℝ ι) :
    IsContinuousAbsorptionPath (linearSingletonAbsorptionPath weight) := by
  exact pathTimes_linearSingletonCadlagPath weight

private theorem sum_singletonCoalitionDistribution_mul
    (weight : stdSimplex ℝ ι)
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) (who : ι) :
    (∑ coalition, singletonCoalitionDistribution weight coalition *
        reward coalition who) =
      ∑ owner, weight owner *
        reward (quittingProjectiveSingletonTerminal owner) who := by
  change (∑ coalition, (∑ owner,
      if coalition = quittingProjectiveSingletonTerminal owner then
        weight owner else 0) * reward coalition who) = _
  simp_rw [Finset.sum_mul]
  rw [Finset.sum_comm]
  simp

/-- Before terminal time, the payoff of a linear singleton path is the
constant singleton-payoff mixture generated by its player distribution. -/
theorem absorptionPathPayoff_linearSingletonAbsorptionPath
    (weight : stdSimplex ℝ ι)
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    {t : ℝ} (ht : t ∈ Icc (0 : ℝ) 1) (ht1 : t ≠ 1) :
    absorptionPathPayoff reward (linearSingletonAbsorptionPath weight) t =
      fun who => ∑ owner, weight owner *
        reward (quittingProjectiveSingletonTerminal owner) who := by
  rw [absorptionPathPayoff, if_pos ht]
  change (if pathTotal (linearSingletonCadlagPath weight) t < 1 then
      fun who => ((∑ coalition,
        ((linearSingletonCadlagPath weight).value 1 coalition -
          (linearSingletonCadlagPath weight).value t coalition) *
            reward coalition who)) /
              (1 - pathTotal (linearSingletonCadlagPath weight) t)
    else 0) = _
  rw [pathTotal_linearSingletonCadlagPath,
    if_pos (lt_of_le_of_ne ht.2 ht1)]
  funext who
  rw [show (∑ coalition,
      ((linearSingletonCadlagPath weight).value 1 coalition -
        (linearSingletonCadlagPath weight).value t coalition) *
          reward coalition who) =
      (1 - t) * ∑ coalition,
        singletonCoalitionDistribution weight coalition *
          reward coalition who by
    rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro coalition _
    change (1 * singletonCoalitionDistribution weight coalition -
      t * singletonCoalitionDistribution weight coalition) *
        reward coalition who = _
    ring]
  rw [sum_singletonCoalitionDistribution_mul]
  field_simp [sub_ne_zero.mpr ht1]

@[simp] theorem singletonCoalitionDistribution_singleton
    (weight : stdSimplex ℝ ι) (who : ι) :
    singletonCoalitionDistribution weight
        (quittingProjectiveSingletonTerminal who) = weight who := by
  change (∑ owner : ι, if quittingProjectiveSingletonTerminal who =
      quittingProjectiveSingletonTerminal owner then weight owner else 0) = _
  rw [Finset.sum_eq_single who]
  · simp
  · intro owner _ hne
    have hcoalition : quittingProjectiveSingletonTerminal who ≠
        quittingProjectiveSingletonTerminal owner := by
      intro heq
      apply hne
      have heq' : who = owner := by
        simpa [quittingProjectiveSingletonTerminal] using
          congrArg (fun S => S.1) heq
      exact heq'.symm
    simp [hcoalition]
  · simp

private theorem singletonPayoffMixture_eq_baseline_add_residual
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (weight : stdSimplex ℝ ι) (who : ι) :
    (∑ owner, weight owner *
        reward (quittingProjectiveSingletonTerminal owner) who) =
      reward (quittingProjectiveSingletonTerminal who) who +
        singletonLCPResidual (normalizedSoloMatrix reward) weight who := by
  rw [normalizedSoloMatrix_eq_projectiveLCPMatrix]
  simp only [singletonLCPResidual, wsum, dotProduct,
    quittingProjectiveLCPMatrix, mul_sub, Finset.sum_sub_distrib,
    ← Finset.sum_mul, stdSimplex.sum_eq_one, one_mul]
  ring

/-- A homogeneous singleton-LCP solution gives an explicit continuous,
sequentially zero-perfect absorption path. -/
theorem exists_continuous_zeroPerfect_of_homogeneous
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (homogeneous : HasHomogeneousSimplexSolution
      (normalizedSoloMatrix reward)) :
    ∃ path : AbsorptionPath (ι := ι),
      IsContinuousAbsorptionPath path ∧
        IsSequentiallyPerfectAbsorptionPath reward path 0 := by
  obtain ⟨weight, hresidual, hcomplementary⟩ := homogeneous
  refine ⟨linearSingletonAbsorptionPath weight,
    linearSingletonAbsorptionPath_continuous weight, ?_⟩
  intro who
  constructor
  · intro t ht
    change t ∈ pathJumps (linearSingletonCadlagPath weight) at ht
    rw [pathJumps_linearSingletonCadlagPath] at ht
    exact ht.elim
  · intro t ht ht1
    have htIcc : t ∈ Icc (0 : ℝ) 1 := by
      rw [← pathTimes_linearSingletonCadlagPath weight]
      exact ht
    have hpayoff := congrFun
      (absorptionPathPayoff_linearSingletonAbsorptionPath
        weight reward htIcc ht1) who
    rw [singletonPayoffMixture_eq_baseline_add_residual] at hpayoff
    constructor
    · change reward (quittingProjectiveSingletonTerminal who) who - 0 ≤ _
      rw [hpayoff]
      linarith [hresidual who]
    · intro hderivative
      have htlt : t < 1 := lt_of_le_of_ne htIcc.2 ht1
      change pathRightDerivative (linearSingletonCadlagPath weight) t
        (quittingProjectiveSingletonTerminal who) > 0 at hderivative
      rw [pathRightDerivative_linearSingletonCadlagPath weight htlt,
        singletonCoalitionDistribution_singleton] at hderivative
      have hzero : singletonLCPResidual
          (normalizedSoloMatrix reward) weight who = 0 :=
        (mul_eq_zero.mp (hcomplementary who)).resolve_left
          (ne_of_gt hderivative)
      rw [hpayoff, hzero]
      simp [quittingProjectiveSingletonTerminal]

end GameTheory.QuittingAbsorptionPath
