/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.AbsorptionPath.LogarithmicProductLaw
import UniformEquilibrium.Quitting.Classification.Existence.PerfectAbsorbingRootSequence
import UniformEquilibrium.Quitting.Classification.LCP.ProjectiveQBarBehavioralDecoder

/-!
# Fixed-target decoder for a supplied logarithmic rate/Snell certificate

The analytic producer is deliberately an explicit hypothesis.  It supplies
integrated block hazards, continuum singleton block laws, the sampled Bellman
values, and finite/Never deleted-clock Snell caps.  This file discharges the
remaining discretization: it constructs actual independent product roots,
compares their complete absorbing laws (including collisions), compares every
opponent-deleted law with its common survival atom retained, and produces the
fixed-target pure-time certificate consumed by the unrestricted behavioral
semantics.
-/

noncomputable section

namespace GameTheory

open Filter Math.PMFProduct Real StochasticGame
open scoped BigOperators Topology

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- Integrated opponent hazard in block `time`, after deleting `who`. -/
def logarithmicOpponentBlockHazard
    (A : ℕ → ι → ℝ) (who : ι) (time : ℕ) : ℝ :=
  ∑ other ∈ Finset.univ.erase who, A time other

/-- Continuum opponent-only ledger generated by supplied singleton block
masses. -/
def logarithmicSourceOpponentLedger
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (A : ℕ → ι → ℝ) (mass : ι → ℕ → ι → ℝ)
    (who : ι) (fuel : ℕ) : ℝ :=
  ∑ time ∈ Finset.range fuel,
    logarithmicDeletedSurvival
        (logarithmicOpponentBlockHazard A who) time *
      ∑ owner, mass who time owner *
        reward (quittingSingletonTerminal owner) who

/-- Exact block data required from the analytic rate/Snell producer.  The
fields about `fullMass` and `opponentMass` are probability-law facts, not
payoff comparison assumptions. -/
structure LogarithmicRateSnellCertificate
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (M h : ℝ) where
  h_pos : 0 < h
  M_nonneg : 0 ≤ M
  reward_bound : ∀ terminal player, |reward terminal player| ≤ M
  A : ℕ → ι → ℝ
  A_nonneg : ∀ time owner, 0 ≤ A time owner
  A_sum : ∀ time, ∑ owner, A time owner = h
  fullMass : ℕ → ι → ℝ
  fullMass_lower : ∀ time owner,
    exp (-h) * A time owner ≤ fullMass time owner
  fullMass_upper : ∀ time owner, fullMass time owner ≤ A time owner
  value : ℕ → Payoff ι
  value_bound : ∀ time who, |value time who| ≤ M
  value_bellman : ∀ time who,
    value time who =
      (∑ owner, fullMass time owner *
        reward (quittingSingletonTerminal owner) who) +
        exp (-h) * value (time + 1) who
  opponentMass : ι → ℕ → ι → ℝ
  opponentMass_self : ∀ who time, opponentMass who time who = 0
  opponentMass_lower : ∀ who time owner, owner ≠ who →
    exp (-logarithmicOpponentBlockHazard A who time) * A time owner ≤
      opponentMass who time owner
  opponentMass_upper : ∀ who time owner, owner ≠ who →
    opponentMass who time owner ≤ A time owner
  finiteQuit_cap : ∀ who time,
    logarithmicSourceOpponentLedger reward A opponentMass who time +
        logarithmicDeletedSurvival
            (logarithmicOpponentBlockHazard A who) time *
          reward (quittingSingletonTerminal who) who ≤
      value 0 who
  neverValue : Payoff ι
  tendsto_opponentLedger : ∀ who,
    Tendsto (fun fuel =>
      logarithmicSourceOpponentLedger reward A opponentMass who fuel)
      atTop (nhds (neverValue who))
  neverValue_le : ∀ who, neverValue who ≤ value 0 who

/-- Actual product roots constructed from the integrated block hazards. -/
def LogarithmicRateSnellCertificate.roots
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h) :
    ℕ → ι → PMF Bool :=
  fun time => logarithmicProductRoot (data.A time) (data.A_nonneg time)

/-- The history-independent behavioral profile generated by the product
roots. -/
def LogarithmicRateSnellCertificate.profile
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h) :
    (quittingGame reward).BehaviorProfile :=
  quittingRootSequenceProfile reward data.roots 0

/-- Full-law prescribed-payoff error. -/
def logarithmicPrescribedError (M h : ℝ) : ℝ :=
  M * (h + h ^ 2 / (2 * (1 - exp (-h))))

/-- Global opponent-only law error, including the separate collision at the
forced quitter's row. -/
def logarithmicPureTimeError (M h : ℝ) : ℝ :=
  M * h * (3 + exp h / 2)

theorem LogarithmicRateSnellCertificate.root_continueMass
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h) (time : ℕ) :
    quittingStationaryContinueMass (data.roots time) = exp (-h) := by
  rw [LogarithmicRateSnellCertificate.roots,
    quittingStationaryContinueMass_logarithmicProductRoot, data.A_sum]

theorem LogarithmicRateSnellCertificate.opponentHazard_nonneg
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h)
    (who : ι) (time : ℕ) :
    0 ≤ logarithmicOpponentBlockHazard data.A who time :=
  Finset.sum_nonneg fun owner _ => data.A_nonneg time owner

theorem LogarithmicRateSnellCertificate.opponentHazard_le
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h)
    (who : ι) (time : ℕ) :
    logarithmicOpponentBlockHazard data.A who time ≤ h := by
  have hsplit : data.A time who +
      logarithmicOpponentBlockHazard data.A who time = h := by
    calc
      data.A time who + logarithmicOpponentBlockHazard data.A who time =
          ∑ owner, data.A time owner := by
        unfold logarithmicOpponentBlockHazard
        rw [← Finset.sum_erase_add _ _ (Finset.mem_univ who)]
        ring
      _ = h := data.A_sum time
  linarith [data.A_nonneg time who]

theorem LogarithmicRateSnellCertificate.opponent_continueMass
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h)
    (who : ι) (time : ℕ) :
    quittingFixedOpponentsContinueMass data.roots who time =
      exp (-logarithmicOpponentBlockHazard data.A who time) := by
  exact quittingFixedOpponentsContinueMass_logarithmicProductRoot
    (data.A time) (data.A_nonneg time) who

/-- The actual deleted survival is definitionally the exponential survival
of the integrated opponent hazards. -/
theorem LogarithmicRateSnellCertificate.opponentSurvival_eq
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h)
    (who : ι) (fuel : ℕ) :
    quittingOpponentSurvivalWeight data.roots who 0 fuel =
      logarithmicDeletedSurvival
        (logarithmicOpponentBlockHazard data.A who) fuel := by
  induction fuel with
  | zero => simp [quittingOpponentSurvivalWeight]
  | succ fuel ih =>
      rw [quittingOpponentSurvivalWeight_zero_succ,
        logarithmicDeletedSurvival_succ, ih,
        data.opponent_continueMass]

/-- One actual full product row is close to its continuum singleton block
law. -/
theorem LogarithmicRateSnellCertificate.fullBlock_close
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h)
    (time : ℕ) (who : ι) :
    |quittingRootAbsorbingContribution reward (data.roots time) who -
        ∑ owner, data.fullMass time owner *
          reward (quittingSingletonTerminal owner) who| ≤
      M * (h * (1 - exp (-h)) + h ^ 2 / 2) := by
  exact abs_logarithmicProductRootContribution_sub_singletonLaw_le
    reward (data.A time) (data.fullMass time) (data.A_nonneg time)
      (data.A_sum time) (data.fullMass_lower time)
      (data.fullMass_upper time) data.reward_bound who

/-- One actual opponent-deleted product row is close to its continuum
opponent singleton block law. -/
theorem LogarithmicRateSnellCertificate.opponentBlock_close
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h)
    (who : ι) (time : ℕ) :
    |quittingFixedOpponentsContinueReward reward data.roots who time -
        ∑ owner, data.opponentMass who time owner *
          reward (quittingSingletonTerminal owner) who| ≤
      M * (logarithmicOpponentBlockHazard data.A who time *
          (1 - exp (-logarithmicOpponentBlockHazard data.A who time)) +
        logarithmicOpponentBlockHazard data.A who time ^ 2 / 2) := by
  exact abs_logarithmicProductOpponentContribution_sub_singletonLaw_le
    reward (data.A time) (data.opponentMass who time) who
      (data.A_nonneg time) (data.opponentMass_self who time) rfl
      (data.opponentMass_lower who time) (data.opponentMass_upper who time)
      data.reward_bound

/-- The terminal payoff of the actual product-root sequence is uniformly
close, from every block suffix, to the sampled continuum value. -/
theorem LogarithmicRateSnellCertificate.prescribedTerminal_close
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h)
    (time : ℕ) (who : ι) :
    |quittingRootSequenceTerminalValue reward data.roots who time -
        data.value time who| ≤ logarithmicPrescribedError M h := by
  let δ := 1 - exp (-h)
  let η := M * (h * (1 - exp (-h)) + h ^ 2 / 2)
  have hδ0 : 0 < δ := by
    dsimp only [δ]
    rw [sub_pos, exp_lt_one_iff]
    linarith [data.h_pos]
  have hδ1 : δ ≤ 1 := by
    dsimp only [δ]
    linarith [exp_pos (-h)]
  have hη0 : 0 ≤ η := by
    dsimp only [η]
    have hh0 := data.h_pos.le
    have hexp : 0 ≤ 1 - exp (-h) := hδ0.le
    have hfirst : 0 ≤ h * (1 - exp (-h)) := mul_nonneg hh0 hexp
    have hsecond : 0 ≤ h ^ 2 / 2 := by positivity
    exact mul_nonneg data.M_nonneg (add_nonneg hfirst hsecond)
  have hmass : ∀ stage,
      quittingStationaryContinueMass (data.roots stage) ≤ 1 - δ := by
    intro stage
    rw [data.root_continueMass]
    dsimp only [δ]
    linarith
  have hclose : ∀ stage player,
      |data.value stage player -
        quittingRootSuccessorPayoff reward (data.value (stage + 1))
          (data.roots stage) player| ≤ η := by
    intro stage player
    unfold quittingRootSuccessorPayoff
    rw [quittingRootExpectedPayoff_eq_absorbingContribution_add,
      data.root_continueMass, data.value_bellman]
    dsimp only [η]
    rw [show
      (∑ owner, data.fullMass stage owner *
          reward (quittingSingletonTerminal owner) player) +
          exp (-h) * data.value (stage + 1) player -
          (quittingRootAbsorbingContribution reward (data.roots stage) player +
            exp (-h) * data.value (stage + 1) player) =
        (∑ owner, data.fullMass stage owner *
          reward (quittingSingletonTerminal owner) player) -
          quittingRootAbsorbingContribution reward (data.roots stage) player by
        ring]
    rw [abs_sub_comm]
    exact data.fullBlock_close stage player
  have hcomparison :=
    abs_terminalValue_sub_successor_le_of_approximate_chain_sharp
      reward data.roots data.value data.M_nonneg hδ0 hδ1 hη0
      data.reward_bound data.value_bound hmass hclose time who
  have hformula : η / δ = logarithmicPrescribedError M h := by
    change (M * (h * δ + h ^ 2 / 2)) / δ =
      M * (h + h ^ 2 / (2 * δ))
    field_simp [ne_of_gt hδ0]
  have htriangle := abs_sub_le
    (quittingRootSequenceTerminalValue reward data.roots who time)
    (quittingRootSuccessorPayoff reward (data.value (time + 1))
      (data.roots time) who)
    (data.value time who)
  have hclose' := hclose time who
  rw [abs_sub_comm] at hclose'
  calc
    |quittingRootSequenceTerminalValue reward data.roots who time -
        data.value time who| ≤
      |quittingRootSequenceTerminalValue reward data.roots who time -
          quittingRootSuccessorPayoff reward (data.value (time + 1))
            (data.roots time) who| +
        |quittingRootSuccessorPayoff reward (data.value (time + 1))
            (data.roots time) who - data.value time who| := htriangle
    _ ≤ (1 - δ) * η / δ + η := add_le_add hcomparison hclose'
    _ = η / δ := by field_simp [ne_of_gt hδ0]; ring
    _ = logarithmicPrescribedError M h := hformula

/-- Prescribed payoff of the actual behavioral profile is close to the one
fixed target `value 0`. -/
theorem LogarithmicRateSnellCertificate.profile_prescribed_close
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h) (who : ι) :
    |quittingTerminalPayoff reward data.profile who - data.value 0 who| ≤
      logarithmicPrescribedError M h := by
  unfold LogarithmicRateSnellCertificate.profile
  rw [quittingTerminalPayoff_eq_rootSequence_profileLiveRoot,
    quittingProfileLiveRoot_quittingRootSequenceProfile_zero]
  exact data.prescribedTerminal_close 0 who

/-- Uniform finite-prefix comparison of the actual opponent-only ledger with
the supplied continuum ledger.  The estimate remains valid when deleted
survival has a positive limit. -/
theorem LogarithmicRateSnellCertificate.opponentLedger_close
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h)
    (who : ι) (fuel : ℕ) :
    |quittingLiveLedgerAccum reward data.roots who 0 fuel -
        logarithmicSourceOpponentLedger reward data.A data.opponentMass
          who fuel| ≤
      M * (h + h * exp h / 2) := by
  unfold quittingLiveLedgerAccum logarithmicSourceOpponentLedger
  simp only [Nat.zero_add]
  rw [← Finset.sum_sub_distrib]
  calc
    |∑ time ∈ Finset.range fuel,
        (quittingOpponentSurvivalWeight data.roots who 0 time *
            quittingFixedOpponentsContinueReward reward data.roots who time -
          logarithmicDeletedSurvival
              (logarithmicOpponentBlockHazard data.A who) time *
            ∑ owner, data.opponentMass who time owner *
              reward (quittingSingletonTerminal owner) who)| ≤
      ∑ time ∈ Finset.range fuel,
        |quittingOpponentSurvivalWeight data.roots who 0 time *
            quittingFixedOpponentsContinueReward reward data.roots who time -
          logarithmicDeletedSurvival
              (logarithmicOpponentBlockHazard data.A who) time *
            ∑ owner, data.opponentMass who time owner *
              reward (quittingSingletonTerminal owner) who| :=
      Finset.abs_sum_le_sum_abs _ _
    _ = ∑ time ∈ Finset.range fuel,
        logarithmicDeletedSurvival
            (logarithmicOpponentBlockHazard data.A who) time *
          |quittingFixedOpponentsContinueReward reward data.roots who time -
            ∑ owner, data.opponentMass who time owner *
              reward (quittingSingletonTerminal owner) who| := by
      apply Finset.sum_congr rfl
      intro time _
      rw [data.opponentSurvival_eq]
      rw [← mul_sub, abs_mul]
      rw [abs_of_nonneg (by
        unfold logarithmicDeletedSurvival
        exact exp_nonneg _)]
    _ ≤ ∑ time ∈ Finset.range fuel,
        logarithmicDeletedSurvival
            (logarithmicOpponentBlockHazard data.A who) time *
          (M * (logarithmicOpponentBlockHazard data.A who time *
              (1 - exp (-logarithmicOpponentBlockHazard data.A who time)) +
            logarithmicOpponentBlockHazard data.A who time ^ 2 / 2)) := by
      apply Finset.sum_le_sum
      intro time _
      exact mul_le_mul_of_nonneg_left (data.opponentBlock_close who time)
        (exp_nonneg _)
    _ = M * (∑ time ∈ Finset.range fuel,
        logarithmicDeletedSurvival
            (logarithmicOpponentBlockHazard data.A who) time *
          (logarithmicOpponentBlockHazard data.A who time *
              (1 - exp (-logarithmicOpponentBlockHazard data.A who time)) +
            logarithmicOpponentBlockHazard data.A who time ^ 2 / 2)) := by
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro time _
      ring
    _ ≤ M * (h + h * exp h / 2) := by
      exact mul_le_mul_of_nonneg_left
        (sum_logarithmicDeletedSurvival_mul_blockError_le
          (logarithmicOpponentBlockHazard data.A who)
          (data.opponentHazard_nonneg who)
          (data.opponentHazard_le who) fuel)
        data.M_nonneg

/-- The actual forced-Quit endpoint differs from the continuum solo endpoint
by at most `2 M h`, uniformly in the quitting date. -/
theorem LogarithmicRateSnellCertificate.forcedQuitEndpoint_close
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h)
    (who : ι) (time : ℕ) :
    |quittingFixedOpponentsQuitValue reward data.roots who time -
        reward (quittingSingletonTerminal who) who| ≤ 2 * M * h := by
  have hendpoint :=
    abs_quittingRootQuitPayoff_sub_singletonReward_le_two_mul_opponentAbsorptionMass
      reward (0 : Payoff ι) (data.roots time) who M data.reward_bound
  rw [quittingRootQuitPayoff_eq_fixedOpponentsQuitValue
    reward data.roots who (0 : Payoff ι) time] at hendpoint
  have habsorption :
      quittingRootOpponentAbsorptionMass (data.roots time) who =
        1 - exp (-logarithmicOpponentBlockHazard data.A who time) := by
    unfold quittingRootOpponentAbsorptionMass quittingRootAbsorptionMass
    change 1 - quittingFixedOpponentsContinueMass data.roots who time = _
    rw [data.opponent_continueMass]
  rw [habsorption] at hendpoint
  have hlocal :=
    (exp_neg_mul_le_one_sub_exp_neg_of_nonneg_of_le
      (data.opponentHazard_nonneg who time)
      (le_refl (logarithmicOpponentBlockHazard data.A who time))).2
  have hle : 1 - exp (-logarithmicOpponentBlockHazard data.A who time) ≤ h :=
    hlocal.trans (data.opponentHazard_le who time)
  exact hendpoint.trans
    (mul_le_mul_of_nonneg_left hle (mul_nonneg (by norm_num) data.M_nonneg))

/-- Every finite deterministic Quit time in the actual product profile is
bounded by the fixed target plus the global pure-time discretization error. -/
theorem LogarithmicRateSnellCertificate.finitePureTime_le
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h)
    (who : ι) (time : ℕ) :
    quittingRootSequencePureTimeTerminalValue reward data.roots who
        (some time) 0 ≤
      data.value 0 who + logarithmicPureTimeError M h := by
  rw [quittingRootSequencePureTimeTerminalValue_some_eq]
  let Q := logarithmicDeletedSurvival
    (logarithmicOpponentBlockHazard data.A who) time
  let actualLedger := quittingLiveLedgerAccum reward data.roots who 0 time
  let sourceLedger := logarithmicSourceOpponentLedger reward data.A
    data.opponentMass who time
  let actualQuit := quittingFixedOpponentsQuitValue reward data.roots who time
  let solo := reward (quittingSingletonTerminal who) who
  have hQ : quittingOpponentSurvivalWeight data.roots who 0 time = Q :=
    data.opponentSurvival_eq who time
  rw [hQ]
  have hledger := data.opponentLedger_close who time
  have hquit := data.forcedQuitEndpoint_close who time
  have hQ0 : 0 ≤ Q := exp_nonneg _
  have hQ1 : Q ≤ 1 := by
    rw [← hQ]
    exact quittingOpponentSurvivalWeight_le_one data.roots who 0 time
  have hcap := data.finiteQuit_cap who time
  change actualLedger + Q * actualQuit ≤
    data.value 0 who + logarithmicPureTimeError M h
  change |actualLedger - sourceLedger| ≤ _ at hledger
  change |actualQuit - solo| ≤ _ at hquit
  change sourceLedger + Q * solo ≤ data.value 0 who at hcap
  have hledgerUpper := (abs_le.mp hledger).2
  have hquitUpper := (abs_le.mp hquit).2
  have hscaledQuit := mul_le_mul_of_nonneg_left hquitUpper hQ0
  have herror0 : 0 ≤ 2 * M * h :=
    mul_nonneg (mul_nonneg (by norm_num) data.M_nonneg) data.h_pos.le
  have hendpointWeighted : Q * (actualQuit - solo) ≤ 2 * M * h :=
    hscaledQuit.trans (mul_le_of_le_one_left herror0 hQ1)
  have hdecomp : actualLedger + Q * actualQuit =
      (sourceLedger + Q * solo) + (actualLedger - sourceLedger) +
        Q * (actualQuit - solo) := by ring
  dsimp only [logarithmicPureTimeError]
  rw [hdecomp]
  calc
    _ ≤ data.value 0 who + M * (h + h * exp h / 2) + 2 * M * h :=
      add_le_add (add_le_add hcap hledgerUpper) hendpointWeighted
    _ = data.value 0 who + M * h * (3 + exp h / 2) := by ring

/-- The actual Never payoff is bounded by the same fixed target and the
opponent-law comparison error.  Positive limiting deleted survival is not
discarded: it is common to the two laws, and both terminal survival atoms pay
zero. -/
theorem LogarithmicRateSnellCertificate.neverPureTime_le
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h)
    (who : ι) :
    quittingRootSequencePureTimeTerminalValue reward data.roots who none 0 ≤
      data.value 0 who + logarithmicPureTimeError M h := by
  have htendsto :=
    (tendsto_quittingLiveLedgerAccum reward data.roots who).sub
      (data.tendsto_opponentLedger who)
  have habs : Tendsto (fun fuel =>
      |quittingLiveLedgerAccum reward data.roots who 0 fuel -
        logarithmicSourceOpponentLedger reward data.A data.opponentMass
          who fuel|) atTop
      (nhds |quittingRootSequencePureTimeTerminalValue reward data.roots who
        none 0 - data.neverValue who|) := htendsto.abs
  have hlimit :
      |quittingRootSequencePureTimeTerminalValue reward data.roots who none 0 -
        data.neverValue who| ≤ M * (h + h * exp h / 2) := by
    exact le_of_tendsto habs (Filter.Eventually.of_forall
      (data.opponentLedger_close who))
  have hupper := (abs_le.mp hlimit).2
  have hcap := data.neverValue_le who
  dsimp only [logarithmicPureTimeError]
  have hnonneg : 0 ≤ 2 * M * h :=
    mul_nonneg (mul_nonneg (by norm_num) data.M_nonneg) data.h_pos.le
  nlinarith

/-- Uniform finite/Never bound for the actual product profile. -/
theorem LogarithmicRateSnellCertificate.pureTime_le
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h)
    (who : ι) (quitTime : Option ℕ) :
    quittingTerminalPayoff reward
        (Function.update data.profile who
          (quittingPureTimeBehaviorStrategy reward who quitTime)) who ≤
      data.value 0 who + logarithmicPureTimeError M h := by
  unfold LogarithmicRateSnellCertificate.profile
  rw [quittingTerminalPayoff_update_pureTimeBehaviorStrategy,
    quittingProfileLiveRoot_quittingRootSequenceProfile_zero]
  cases quitTime with
  | none => exact data.neverPureTime_le who
  | some time => exact data.finitePureTime_le who time

/-- Total error paid by the prescribed full-law comparison and the uniform
pure-time opponent-law comparison. -/
def logarithmicProductDecoderError (M h : ℝ) : ℝ :=
  logarithmicPrescribedError M h + logarithmicPureTimeError M h

theorem LogarithmicRateSnellCertificate.prescribedError_nonneg
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h) :
    0 ≤ logarithmicPrescribedError M h := by
  unfold logarithmicPrescribedError
  have hdenom : 0 < 1 - exp (-h) := by
    rw [sub_pos, exp_lt_one_iff]
    linarith [data.h_pos]
  have hfrac : 0 ≤ h ^ 2 / (2 * (1 - exp (-h))) :=
    div_nonneg (sq_nonneg h) (mul_nonneg (by norm_num) hdenom.le)
  have hinside : 0 ≤ h + h ^ 2 / (2 * (1 - exp (-h))) :=
    add_nonneg data.h_pos.le hfrac
  exact mul_nonneg data.M_nonneg hinside

theorem LogarithmicRateSnellCertificate.pureTimeError_nonneg
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h) :
    0 ≤ logarithmicPureTimeError M h := by
  unfold logarithmicPureTimeError
  exact mul_nonneg (mul_nonneg data.M_nonneg data.h_pos.le)
    (add_nonneg (by norm_num) (div_nonneg (exp_nonneg h) (by norm_num)))

/-- The total decoder error has a denominator-free linear upper bound. -/
theorem LogarithmicRateSnellCertificate.decoderError_le_linear
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h) :
    logarithmicProductDecoderError M h ≤ M * h * (4 + exp h) := by
  have hδ : 0 < 1 - exp (-h) := by
    rw [sub_pos, exp_lt_one_iff]
    linarith [data.h_pos]
  have hsq := sq_div_two_le_collisionScale_mul_one_sub_exp_neg
    data.h_pos.le (le_refl h)
  have hratio : h ^ 2 / (2 * (1 - exp (-h))) ≤ h * exp h / 2 := by
    rw [div_le_iff₀ (mul_pos (by norm_num) hδ)]
    nlinarith
  unfold logarithmicProductDecoderError logarithmicPrescribedError
    logarithmicPureTimeError
  have hscaled := mul_le_mul_of_nonneg_left hratio data.M_nonneg
  nlinarith

/-- One supplied rate/Snell certificate gives an actual product behavioral
profile with a fixed-target pure-time approximation. -/
def LogarithmicRateSnellCertificate.pureTimeTargetApproximationAt
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι} {M h : ℝ}
    (data : LogarithmicRateSnellCertificate reward M h) :
    QuittingPureTimeTargetApproximationAt reward (data.value 0)
      (logarithmicProductDecoderError M h) where
  profile := data.profile
  prescribed_close := fun who =>
    (data.profile_prescribed_close who).trans
      (le_add_of_nonneg_right data.pureTimeError_nonneg)
  pureTime_le := fun who quitTime =>
    (data.pureTime_le who quitTime).trans
      (add_le_add (le_refl (data.value 0 who))
        (show logarithmicPureTimeError M h ≤
            logarithmicProductDecoderError M h by
          unfold logarithmicProductDecoderError
          exact le_add_of_nonneg_left data.prescribedError_nonneg))

/-- Cofinal fixed-target block certificates.  The small-error choice is kept
explicit so an analytic producer may choose any convenient logarithmic mesh,
while the target remains literally fixed. -/
structure LogarithmicRateSnellFamilyCertificate
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (target : Payoff ι) (M : ℝ) where
  cofinal : ∀ error : ℝ, 0 < error →
    ∃ h : ℝ, ∃ data : LogarithmicRateSnellCertificate reward M h,
      logarithmicProductDecoderError M h < error ∧ data.value 0 = target

/-- A source supplying the same fixed target at every positive logarithmic
mesh.  Unlike the cofinal interface, no quantitative smallness choice is
required from the analytic producer. -/
structure LogarithmicRateSnellAllMeshesCertificate
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (target : Payoff ι) (M : ℝ) where
  M_nonneg : 0 ≤ M
  certificate : ∀ h : ℝ, 0 < h →
    Nonempty (LogarithmicRateSnellCertificate reward M h)
  target_eq : ∀ h : ℝ, ∀ _h_pos : 0 < h,
    ∀ data : LogarithmicRateSnellCertificate reward M h,
      data.value 0 = target

/-- The explicit `O(h)` bound chooses a sufficiently fine positive mesh and
turns an all-mesh analytic source into the cofinal consumer interface. -/
theorem LogarithmicRateSnellAllMeshesCertificate.toCofinal
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    {target : Payoff ι} {M : ℝ}
    (family : LogarithmicRateSnellAllMeshesCertificate reward target M) :
    LogarithmicRateSnellFamilyCertificate reward target M where
  cofinal := by
    intro error herror
    let C := M * (4 + exp 1) + 1
    have hC : 0 < C := by
      dsimp only [C]
      have : 0 ≤ M * (4 + exp 1) :=
        mul_nonneg family.M_nonneg
          (add_nonneg (by norm_num) (exp_nonneg 1))
      linarith
    let h := min 1 (error / (2 * C))
    have hh : 0 < h := by
      dsimp only [h]
      exact lt_min one_pos (div_pos herror (mul_pos (by norm_num) hC))
    have hh1 : h ≤ 1 := min_le_left _ _
    obtain ⟨data⟩ := family.certificate h hh
    refine ⟨h, data, ?_, family.target_eq h hh data⟩
    have hexp : exp h ≤ exp 1 := (exp_le_exp).2 hh1
    have hlinear := data.decoderError_le_linear
    have hcoefficient : M * (4 + exp h) ≤ C := by
      dsimp only [C]
      have hscaled := mul_le_mul_of_nonneg_left
        (add_le_add_left hexp 4) family.M_nonneg
      linarith
    have hscaled := mul_le_mul_of_nonneg_left hcoefficient hh.le
    have hscaled' : M * h * (4 + exp h) ≤ h * C := by
      calc
        M * h * (4 + exp h) = h * (M * (4 + exp h)) := by ring
        _ ≤ h * C := hscaled
    have hratio : h ≤ error / (2 * C) := min_le_right _ _
    have hbudget : h * (2 * C) ≤ error :=
      (le_div_iff₀ (mul_pos (by norm_num) hC)).mp hratio
    have hstrict : h * C < error := by nlinarith [mul_pos hh hC]
    exact hlinear.trans_lt (hscaled'.trans_lt hstrict)

/-- The strongest direct fixed-target consumer: cofinally fine supplied
rate/Snell data produces the unrestricted-behavior pure-time certificate. -/
theorem LogarithmicRateSnellFamilyCertificate.toPureTimeTargetCertificate
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    {target : Payoff ι} {M : ℝ}
    (family : LogarithmicRateSnellFamilyCertificate reward target M) :
    QuittingPureTimeTargetApproximationCertificate reward target := by
  apply quittingPureTimeTargetApproximationCertificate_of_cofinal
  intro error herror
  obtain ⟨h, data, hsmall, htarget⟩ := family.cofinal error herror
  refine ⟨logarithmicProductDecoderError M h,
    add_nonneg data.prescribedError_nonneg data.pureTimeError_nonneg,
    hsmall, ?_⟩
  rw [← htarget]
  exact ⟨data.pureTimeTargetApproximationAt⟩

/-- Hence the same supplied family already establishes the fixed target as a
uniform-equilibrium payoff against arbitrary behavioral deviations. -/
theorem LogarithmicRateSnellFamilyCertificate.isUniformEquilibriumPayoff
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    {target : Payoff ι} {M : ℝ}
    (family : LogarithmicRateSnellFamilyCertificate reward target M) :
    (quittingGame reward).IsUniformEquilibriumPayoff none target :=
  family.toPureTimeTargetCertificate.isUniformEquilibriumPayoff

/-- All-positive-mesh source form of the fixed-target certificate consumer. -/
theorem LogarithmicRateSnellAllMeshesCertificate.toPureTimeTargetCertificate
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    {target : Payoff ι} {M : ℝ}
    (family : LogarithmicRateSnellAllMeshesCertificate reward target M) :
    QuittingPureTimeTargetApproximationCertificate reward target :=
  family.toCofinal.toPureTimeTargetCertificate

/-- All-positive-mesh source form of the final unrestricted-behavior
uniform-payoff consumer. -/
theorem LogarithmicRateSnellAllMeshesCertificate.isUniformEquilibriumPayoff
    {reward : {S : Finset ι // S.Nonempty} → Payoff ι}
    {target : Payoff ι} {M : ℝ}
    (family : LogarithmicRateSnellAllMeshesCertificate reward target M) :
    (quittingGame reward).IsUniformEquilibriumPayoff none target :=
  family.toPureTimeTargetCertificate.isUniformEquilibriumPayoff

end GameTheory
