/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.AbsorptionPath.MetrizableMarkedAbsorptionPath

/-!
# Completed composition of metrizable marked absorption paths

Completed composition is the closed ternary relation generated by correlated
finite exact seams.  Retaining outer path, inner path, and result jointly
avoids an unjustified choice of result from a projected pair.

A separate six-coordinate compact relation records limits of finite exactly
associative diagrams.  Each such diagram supplies the four expected splice
witnesses with one common result.  No total splice theorem for arbitrary
equal-anchor pairs, fibre uniqueness, or amalgamation of independently chosen
completed splice witnesses is asserted here.
-/

noncomputable section

namespace GameTheory
namespace MetrizableMarkedAbsorptionCompletion

open Filter Set StochasticGame
open Math.Probability Math.PMFProduct
open TopologicalSpace
open scoped Topology

variable {ι : Type} [Fintype ι] [DecidableEq ι] [Nonempty ι]
variable {reward : {S : Finset ι // S.Nonempty} → Payoff ι}

/-! ## Closed ternary composition and sequential exact-seam presentation -/

/-- Ambient triple `(outer, inner, result)`. -/
abbrev MetrizableCompositionTriple
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :=
  (MetrizableMarkedAbsorptionPath reward ×
    MetrizableMarkedAbsorptionPath reward) ×
      MetrizableMarkedAbsorptionPath reward

/-- Exact finite composition triple. -/
def finiteCompositionTriple (seam : FiniteExactSeam reward) :
    MetrizableCompositionTriple reward :=
  ((completeMetrizable seam.outer, completeMetrizable seam.inner),
    completeMetrizable seam.compose)

/-- Closed ternary graph of completed composition. -/
def metrizableCompositionRelation : Set (MetrizableCompositionTriple reward) :=
  closure (Set.range (finiteCompositionTriple (reward := reward)))

theorem metrizableCompositionRelation_isClosed :
    IsClosed (metrizableCompositionRelation (reward := reward)) :=
  isClosed_closure

theorem metrizableCompositionRelation_isCompact :
    IsCompact (metrizableCompositionRelation (reward := reward)) :=
  metrizableCompositionRelation_isClosed.isCompact

/-- A composition witness retains outer, inner, and result jointly. -/
abbrev MetrizableCompositionWitness
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :=
  {triple : MetrizableCompositionTriple reward //
    triple ∈ metrizableCompositionRelation (reward := reward)}

instance : CompactSpace (MetrizableCompositionWitness reward) :=
  isCompact_iff_compactSpace.mp metrizableCompositionRelation_isCompact

def completeCompositionWitness (seam : FiniteExactSeam reward) :
    MetrizableCompositionWitness reward :=
  ⟨finiteCompositionTriple seam,
    subset_closure (Set.mem_range_self seam)⟩

/-- Every completed composition witness is a sequential limit of finite
exact seams, with the result correlated at every index. -/
theorem exists_exactSeam_sequence_tendsto
    (witness : MetrizableCompositionWitness reward) :
    ∃ seams : ℕ → FiniteExactSeam reward,
      Tendsto (fun n => completeCompositionWitness (seams n))
        atTop (𝓝 witness) := by
  obtain ⟨triples, htriples, htendsto⟩ :=
    mem_closure_iff_seq_limit.mp witness.2
  choose seams hseams using htriples
  refine ⟨seams, tendsto_subtype_rng.mpr ?_⟩
  simpa only [completeCompositionWitness, hseams] using htendsto

/-- Exact anchor equality defines a closed relation on pairs in the concrete
metric carrier. -/
def metrizableAnchorSeamRelation : Set
    (MetrizableMarkedAbsorptionPath reward ×
      MetrizableMarkedAbsorptionPath reward) :=
  {pair | metrizableExitAnchor pair.1 = metrizableEntryAnchor pair.2}

theorem metrizableAnchorSeamRelation_isClosed :
    IsClosed (metrizableAnchorSeamRelation (reward := reward)) := by
  exact isClosed_eq
    (continuous_metrizableExitAnchor.comp continuous_fst)
    (continuous_metrizableEntryAnchor.comp continuous_snd)

theorem finiteCompositionTriple_has_exact_anchor
    (seam : FiniteExactSeam reward) :
    (finiteCompositionTriple seam).1 ∈
      metrizableAnchorSeamRelation (reward := reward) := by
  apply Subtype.ext
  exact seam.2

/-- Every completed composition has equal limiting exact-D anchors, and its
approximating sequence has literal anchor equality at every finite index.
This is a necessary seam law, not totality over all equal-anchor pairs. -/
theorem compositionWitness_has_exact_anchor
    (witness : MetrizableCompositionWitness reward) :
    witness.1.1 ∈ metrizableAnchorSeamRelation (reward := reward) := by
  have hclosed : IsClosed
      {triple : MetrizableCompositionTriple reward |
        triple.1 ∈ metrizableAnchorSeamRelation (reward := reward)} :=
    metrizableAnchorSeamRelation_isClosed.preimage (by fun_prop)
  apply closure_minimal _ hclosed witness.2
  rintro triple ⟨seam, rfl⟩
  exact finiteCompositionTriple_has_exact_anchor seam

/-! ## Compact relational associativity -/

/-- Three finite coherent cylinders with two adjacent exact seams. -/
abbrev FiniteComposableTriple
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :=
  {triple : (FiniteMarkedAbsorptionPath reward ×
      FiniteMarkedAbsorptionPath reward) ×
        FiniteMarkedAbsorptionPath reward //
    MarkedAbsorptionCylinder.IsComposable triple.1.1.1 triple.1.2.1 ∧
      MarkedAbsorptionCylinder.IsComposable triple.1.2.1 triple.2.1}

namespace FiniteComposableTriple

def first (triple : FiniteComposableTriple reward) := triple.1.1.1
def second (triple : FiniteComposableTriple reward) := triple.1.1.2
def third (triple : FiniteComposableTriple reward) := triple.1.2

def firstSecondSeam (triple : FiniteComposableTriple reward) :
    FiniteExactSeam reward :=
  ⟨(triple.first, triple.second), triple.2.1⟩

def secondThirdSeam (triple : FiniteComposableTriple reward) :
    FiniteExactSeam reward :=
  ⟨(triple.second, triple.third), triple.2.2⟩

def firstSecond (triple : FiniteComposableTriple reward) :
    FiniteMarkedAbsorptionPath reward := triple.firstSecondSeam.compose

def secondThird (triple : FiniteComposableTriple reward) :
    FiniteMarkedAbsorptionPath reward := triple.secondThirdSeam.compose

def leftSeam (triple : FiniteComposableTriple reward) :
    FiniteExactSeam reward :=
  ⟨(triple.firstSecond, triple.third), by
    change (triple.first.1.compose triple.second.1).exitAnchor =
      triple.third.1.entryAnchor
    rw [MarkedAbsorptionCylinder.exitAnchor_compose]
    exact triple.2.2⟩

def rightSeam (triple : FiniteComposableTriple reward) :
    FiniteExactSeam reward :=
  ⟨(triple.first, triple.secondThird), by
    change triple.first.1.exitAnchor =
      (triple.second.1.compose triple.third.1).entryAnchor
    rw [MarkedAbsorptionCylinder.entryAnchor_compose]
    exact triple.2.1⟩

def composite (triple : FiniteComposableTriple reward) :
    FiniteMarkedAbsorptionPath reward := triple.leftSeam.compose

theorem rightComposite_eq_composite (triple : FiniteComposableTriple reward) :
    triple.rightSeam.compose = triple.composite := by
  apply Subtype.ext
  exact (MarkedAbsorptionCylinder.compose_assoc
    triple.first.1 triple.second.1 triple.third.1).symm

end FiniteComposableTriple

/-- Six correlated coordinates `(a,b,c,ab,bc,abc)`. -/
abbrev MetrizableAssociativityTuple
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :=
  MetrizableMarkedAbsorptionPath reward ×
    (MetrizableMarkedAbsorptionPath reward ×
      (MetrizableMarkedAbsorptionPath reward ×
        (MetrizableMarkedAbsorptionPath reward ×
          (MetrizableMarkedAbsorptionPath reward ×
            MetrizableMarkedAbsorptionPath reward))))

def finiteAssociativityTuple (triple : FiniteComposableTriple reward) :
    MetrizableAssociativityTuple reward :=
  (completeMetrizable triple.first,
    (completeMetrizable triple.second,
      (completeMetrizable triple.third,
        (completeMetrizable triple.firstSecond,
          (completeMetrizable triple.secondThird,
            completeMetrizable triple.composite)))))

/-- Closure of finite exactly associative diagrams. -/
def metrizableAssociativityRelation :
    Set (MetrizableAssociativityTuple reward) :=
  closure (Set.range (finiteAssociativityTuple (reward := reward)))

abbrev MetrizableAssociativityWitness
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :=
  {diagram : MetrizableAssociativityTuple reward //
    diagram ∈ metrizableAssociativityRelation (reward := reward)}

instance : CompactSpace (MetrizableAssociativityWitness reward) :=
  isCompact_iff_compactSpace.mp isClosed_closure.isCompact

def completeAssociativityWitness (triple : FiniteComposableTriple reward) :
    MetrizableAssociativityWitness reward :=
  ⟨finiteAssociativityTuple triple,
    subset_closure (Set.mem_range_self triple)⟩

/-- Associativity diagrams too are sequential limits of finite diagrams. -/
theorem exists_associativity_sequence_tendsto
    (witness : MetrizableAssociativityWitness reward) :
    ∃ triples : ℕ → FiniteComposableTriple reward,
      Tendsto (fun n => completeAssociativityWitness (triples n))
        atTop (𝓝 witness) := by
  obtain ⟨diagrams, hdiagrams, htendsto⟩ :=
    mem_closure_iff_seq_limit.mp witness.2
  choose triples htriples using hdiagrams
  refine ⟨triples, tendsto_subtype_rng.mpr ?_⟩
  simpa only [completeAssociativityWitness, htriples] using htendsto

def associativityAB (diagram : MetrizableAssociativityTuple reward) :
    MetrizableCompositionTriple reward :=
  ((diagram.1, diagram.2.1), diagram.2.2.2.1)

def associativityBC (diagram : MetrizableAssociativityTuple reward) :
    MetrizableCompositionTriple reward :=
  ((diagram.2.1, diagram.2.2.1), diagram.2.2.2.2.1)

def associativityLeft (diagram : MetrizableAssociativityTuple reward) :
    MetrizableCompositionTriple reward :=
  ((diagram.2.2.2.1, diagram.2.2.1), diagram.2.2.2.2.2)

def associativityRight (diagram : MetrizableAssociativityTuple reward) :
    MetrizableCompositionTriple reward :=
  ((diagram.1, diagram.2.2.2.2.1), diagram.2.2.2.2.2)

theorem associativityWitness_ab_mem
    (witness : MetrizableAssociativityWitness reward) :
    associativityAB witness.1 ∈
      metrizableCompositionRelation (reward := reward) := by
  apply map_mem_closure (by unfold associativityAB; fun_prop) witness.2
  rintro diagram ⟨triple, rfl⟩
  exact ⟨triple.firstSecondSeam, rfl⟩

theorem associativityWitness_bc_mem
    (witness : MetrizableAssociativityWitness reward) :
    associativityBC witness.1 ∈
      metrizableCompositionRelation (reward := reward) := by
  apply map_mem_closure (by unfold associativityBC; fun_prop) witness.2
  rintro diagram ⟨triple, rfl⟩
  exact ⟨triple.secondThirdSeam, rfl⟩

theorem associativityWitness_left_mem
    (witness : MetrizableAssociativityWitness reward) :
    associativityLeft witness.1 ∈
      metrizableCompositionRelation (reward := reward) := by
  apply map_mem_closure (by unfold associativityLeft; fun_prop) witness.2
  rintro diagram ⟨triple, rfl⟩
  exact ⟨triple.leftSeam, rfl⟩

theorem associativityWitness_right_mem
    (witness : MetrizableAssociativityWitness reward) :
    associativityRight witness.1 ∈
      metrizableCompositionRelation (reward := reward) := by
  apply map_mem_closure (by unfold associativityRight; fun_prop) witness.2
  rintro diagram ⟨triple, rfl⟩
  refine ⟨triple.rightSeam, ?_⟩
  change
    ((completeMetrizable triple.first,
        completeMetrizable triple.secondThird),
      completeMetrizable triple.rightSeam.compose) =
    ((completeMetrizable triple.first,
        completeMetrizable triple.secondThird),
      completeMetrizable triple.composite)
  rw [triple.rightComposite_eq_composite]

/-- The two bracketings in a completed coherent associativity diagram share
one literal result coordinate.  The diagram records jointly approximable
splice witnesses; it does not assert amalgamation of arbitrary independently
chosen witnesses of the ternary relation. -/
theorem associativityWitness_common_composite
    (witness : MetrizableAssociativityWitness reward) :
    (associativityLeft witness.1).2 =
      (associativityRight witness.1).2 := rfl



end MetrizableMarkedAbsorptionCompletion
end GameTheory
