/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.AbsorptionPath.PrincipalQBoundaryDirection

/-!
# Local principal-Q arcs in the paper clock

An affine boundary segment with parameter `β` becomes an exact local arc for
the paper's clock after `β(t)=1-start/t`. Its scaled state has the nonsingular
balance

`t q(t) = start q(start) + (t-start) Rz`.

This is the local building block for adaptive polygonal approximations.
-/

noncomputable section

namespace GameTheory.QuittingLCPClassification

open Math.LinearProgramming Set

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- The affine parameter converting the paper clock to a boundary segment. -/
def principalQArcParameter (start time : ℝ) : ℝ :=
  1 - start / time

/-- The local paper-clock state generated by one fixed boundary direction. -/
def principalQLocalArcState (M : ι → ι → ℝ) (start : ℝ)
    (q : ι → ℝ) (direction : NonnegativeBoundaryDirection M q)
    (time : ℝ) : ι → ℝ := fun i =>
  (1 - principalQArcParameter start time) * q i +
    principalQArcParameter start time *
      singletonLCPResidual M direction.weight i

@[simp] theorem principalQArcParameter_start {start : ℝ} (hstart : start ≠ 0) :
    principalQArcParameter start start = 0 := by
  simp [principalQArcParameter, hstart]

/-- Up to `start/(1-α)`, the clock parameter runs from zero to at most `α`. -/
theorem principalQArcParameter_mem_Icc
    {start α time : ℝ} (hstart : 0 < start) (hαone : α < 1)
    (htime : time ∈ Icc start (start / (1 - α))) :
    principalQArcParameter start time ∈ Icc (0 : ℝ) α := by
  have htimePos : 0 < time := hstart.trans_le htime.1
  have honeMinusPos : 0 < 1 - α := sub_pos.mpr hαone
  constructor
  · unfold principalQArcParameter
    have hratio : start / time ≤ 1 := (div_le_one htimePos).2 htime.1
    linarith
  · unfold principalQArcParameter
    have hscaled : time * (1 - α) ≤ start := by
      apply (le_div_iff₀ honeMinusPos).mp
      simpa [mul_comm] using htime.2
    have hratio : 1 - α ≤ start / time := by
      exact (le_div_iff₀ htimePos).2 (by simpa [mul_comm] using hscaled)
    linarith

/-- Every positive affine segment length advances the paper clock strictly. -/
theorem principalQArc_start_lt_end
    {start α : ℝ} (hstart : 0 < start) (hα : 0 < α) (hαone : α < 1) :
    start < start / (1 - α) := by
  apply (lt_div_iff₀ (sub_pos.mpr hαone)).2
  nlinarith

omit [DecidableEq ι] in
/-- A feasible affine boundary segment stays feasible after the exact
paper-clock reparameterization. -/
theorem isNonnegativeBoundary_principalQLocalArcState
    {M : ι → ι → ℝ} {start α : ℝ} {q : ι → ℝ}
    (direction : NonnegativeBoundaryDirection M q)
    (hstart : 0 < start) (hαone : α < 1)
    (hsegment : ∀ β ∈ Icc (0 : ℝ) α, IsNonnegativeBoundary (fun i =>
      (1 - β) * q i + β * singletonLCPResidual M direction.weight i))
    {time : ℝ} (htime : time ∈ Icc start (start / (1 - α))) :
    IsNonnegativeBoundary
      (principalQLocalArcState M start q direction time) := by
  exact hsegment _ (principalQArcParameter_mem_Icc hstart hαone htime)

omit [DecidableEq ι] in
/-- The scaled local state satisfies the nonsingular cumulative-control
identity used in Step 3 of the paper. -/
theorem principalQLocalArcState_scaled_balance
    (M : ι → ι → ℝ) {start time : ℝ} (hstart : 0 < start)
    (htime : start ≤ time) (q : ι → ℝ)
    (direction : NonnegativeBoundaryDirection M q) :
    time • principalQLocalArcState M start q direction time =
      start • q + (time - start) • fun i =>
        singletonLCPResidual M direction.weight i := by
  have htimeNe : time ≠ 0 := ne_of_gt (hstart.trans_le htime)
  funext i
  change time * ((1 - principalQArcParameter start time) * q i +
      principalQArcParameter start time *
        singletonLCPResidual M direction.weight i) =
    start * q i + (time - start) *
      singletonLCPResidual M direction.weight i
  simp only [principalQArcParameter]
  field_simp [htimeNe]
  ring

/-- Complete principal-Q control on every face supplies a nontrivial exact
local boundary arc in the paper clock, below any prescribed affine mesh. -/
theorem exists_principalQLocalArc
    (M : ι → ι → ℝ) (hdiag : ∀ i, M i i = 0)
    (hQ : IsProjectiveQBarMatrix M) {start stepBound : ℝ}
    (hstart : 0 < start) (hstepBound : 0 < stepBound)
    (q : ι → ℝ) (hq : IsNonnegativeBoundary q) :
    ∃ (direction : NonnegativeBoundaryDirection M q) (α : ℝ),
      0 < α ∧ α < stepBound ∧ α < 1 ∧
      start < start / (1 - α) ∧
      ∀ time ∈ Icc start (start / (1 - α)),
        IsNonnegativeBoundary
          (principalQLocalArcState M start q direction time) := by
  obtain ⟨direction⟩ :=
    exists_nonnegativeBoundaryDirection M hdiag hQ q hq
  obtain ⟨α, hα, hαbound, hαone, hsegment⟩ :=
    direction.exists_boundary_segment hq hstepBound
  refine ⟨direction, α, hα, hαbound, hαone,
    principalQArc_start_lt_end hstart hα hαone, ?_⟩
  intro time htime
  exact isNonnegativeBoundary_principalQLocalArcState
    direction hstart hαone hsegment htime

omit [DecidableEq ι] in
/-- At the initial clock time the local arc starts at its prescribed state. -/
@[simp] theorem principalQLocalArcState_start
    (M : ι → ι → ℝ) {start : ℝ} (hstart : start ≠ 0)
    (q : ι → ℝ) (direction : NonnegativeBoundaryDirection M q) :
    principalQLocalArcState M start q direction start = q := by
  funext i
  simp [principalQLocalArcState, principalQArcParameter, hstart]

end GameTheory.QuittingLCPClassification
