import UniformEquilibrium.Quitting.Cycles.PeriodThreeClearedGap
import UniformEquilibrium.Quitting.Cycles.PlayerwisePositiveAffinePeriodicBlock

/-!
# Semantic data for exact period-three quitting blocks

This module packages the hypotheses of the cleared-gap periodic compiler.
The package records semantic game data: a probability-valued hazard word,
positive one-period absorption, exact endpoint complementarity, and strict
fixed-opponent contraction.
-/

noncomputable section

namespace GameTheory

open Math.Probability Math.ProbabilityMassFunction

variable {Player : Type} [Fintype Player] [DecidableEq Player]

/-- Semantic data sufficient for an exact unrestricted behavioral
uniform-equilibrium payoff generated by a period-three quitting block. -/
structure PeriodThreeClearedGapData
    (reward : {coalition : Finset Player // coalition.Nonempty} → Payoff Player) where
  hazard : Fin 3 → Player → ℝ
  hazard_nonneg : ∀ phase who, 0 ≤ hazard phase who
  hazard_le_one : ∀ phase who, hazard phase who ≤ 1
  absorptionPositive : 0 < quittingPeriodThreeAbsorptionDenominator hazard
  complementary : IsQuittingPeriodThreeClearedGapComplementary reward hazard
  fixedOpponentContracts : ∀ who,
    (∏ phase : Fin 3,
      quittingStationaryFixedOpponentsContinueMass
        (quittingBlockCycle hazard hazard_nonneg hazard_le_one phase) who) < 1

namespace PeriodThreeClearedGapData

/-- The root cycle encoded by period-three cleared-gap data. -/
def cycle
    {reward : {coalition : Finset Player // coalition.Nonempty} → Payoff Player}
    (data : PeriodThreeClearedGapData reward) :
    Fin 3 → Player → PMF Bool :=
  quittingBlockCycle data.hazard data.hazard_nonneg data.hazard_le_one

/-- The cyclic terminal payoff selected at a given initial phase. -/
def terminalPayoff
    {reward : {coalition : Finset Player // coalition.Nonempty} → Payoff Player}
    (data : PeriodThreeClearedGapData reward) (initial : Fin 3) : Payoff Player :=
  quittingCyclicTerminalValue reward data.cycle initial

/-- Period-three cleared-gap data compiles to a uniform-equilibrium payoff
against unrestricted behavioral deviations. -/
theorem isUniformEquilibriumPayoff
    {reward : {coalition : Finset Player // coalition.Nonempty} → Payoff Player}
    (data : PeriodThreeClearedGapData reward) (initial : Fin 3) :
    (quittingGame reward).IsUniformEquilibriumPayoff none
      (data.terminalPayoff initial) := by
  exact isUniformEquilibriumPayoff_of_periodThreeClearedGapComplementarity
    reward data.hazard data.hazard_nonneg data.hazard_le_one
      data.absorptionPositive data.complementary
      data.fixedOpponentContracts initial

end PeriodThreeClearedGapData

/-- The closed period-three value transforms playerwise affinely under
independent positive rescaling and translation of terminal rewards. -/
theorem quittingPeriodThreeClosedValue_playerwiseAffine
    (reward : {coalition : Finset Player // coalition.Nonempty} → Payoff Player)
    (scale shift : Payoff Player) (hazard : Fin 3 → Player → ℝ)
    (h0 : ∀ phase who, 0 ≤ hazard phase who)
    (h1 : ∀ phase who, hazard phase who ≤ 1)
    (hdenominator : 0 < quittingPeriodThreeAbsorptionDenominator hazard)
    (hcontracts : ∀ who,
      (∏ phase : Fin 3,
        quittingStationaryFixedOpponentsContinueMass
          (quittingBlockCycle hazard h0 h1 phase) who) < 1) :
    quittingPeriodThreeClosedValue
        (quittingPlayerwiseAffineReward reward scale shift) hazard =
      fun phase => quittingPlayerwiseAffinePayoff scale shift
        (quittingPeriodThreeClosedValue reward hazard phase) := by
  rw [quittingPeriodThreeClosedValue_eq_cyclicTerminalValue
      (quittingPlayerwiseAffineReward reward scale shift) hazard h0 h1
      hdenominator,
    quittingCyclicTerminalValue_playerwiseAffine reward scale shift
      (quittingBlockCycle hazard h0 h1)]
  · rw [quittingPeriodThreeClosedValue_eq_cyclicTerminalValue
      reward hazard h0 h1 hdenominator]
  · exact hcontracts

/-- Every cleared endpoint difference scales by the corresponding player's
positive affine factor; translations cancel. -/
theorem quittingPeriodThreeClearedEndpointDifference_playerwiseAffine
    (reward : {coalition : Finset Player // coalition.Nonempty} → Payoff Player)
    (scale shift : Payoff Player) (hazard : Fin 3 → Player → ℝ)
    (h0 : ∀ phase who, 0 ≤ hazard phase who)
    (h1 : ∀ phase who, hazard phase who ≤ 1)
    (hdenominator : 0 < quittingPeriodThreeAbsorptionDenominator hazard)
    (hcontracts : ∀ player,
      (∏ cyclePhase : Fin 3,
        quittingStationaryFixedOpponentsContinueMass
          (quittingBlockCycle hazard h0 h1 cyclePhase) player) < 1)
    (phase : Fin 3) (who : Player) :
    quittingPeriodThreeClearedEndpointDifference
        (quittingPlayerwiseAffineReward reward scale shift) hazard phase who =
      scale who *
        quittingPeriodThreeClearedEndpointDifference reward hazard phase who := by
  rw [quittingPeriodThreeClearedEndpointDifference_eq_mul_endpointDifference
      (quittingPlayerwiseAffineReward reward scale shift) hazard h0 h1
      hdenominator.ne',
    quittingPeriodThreeClearedEndpointDifference_eq_mul_endpointDifference
      reward hazard h0 h1 hdenominator.ne',
    quittingPeriodThreeClosedValue_playerwiseAffine
      reward scale shift hazard h0 h1 hdenominator hcontracts,
    quittingRootEndpointDifference_playerwiseAffine]
  ring

namespace PeriodThreeClearedGapData

/-- Independent positive affine transformations of the players' rewards
preserve period-three cleared-gap data with the same hazard word. -/
def playerwiseAffine
    {reward : {coalition : Finset Player // coalition.Nonempty} → Payoff Player}
    (data : PeriodThreeClearedGapData reward) (scale shift : Payoff Player)
    (hscale : ∀ who, 0 < scale who) :
    PeriodThreeClearedGapData
      (quittingPlayerwiseAffineReward reward scale shift) where
  hazard := data.hazard
  hazard_nonneg := data.hazard_nonneg
  hazard_le_one := data.hazard_le_one
  absorptionPositive := data.absorptionPositive
  complementary := by
    intro phase who
    rw [quittingPeriodThreeClearedEndpointDifference_playerwiseAffine
      reward scale shift data.hazard data.hazard_nonneg data.hazard_le_one
      data.absorptionPositive data.fixedOpponentContracts phase who]
    obtain ⟨hcontinue, hquit⟩ := data.complementary phase who
    constructor
    · rw [show (1 - data.hazard phase who) *
          (scale who * quittingPeriodThreeClearedEndpointDifference
            reward data.hazard phase who) =
        scale who * ((1 - data.hazard phase who) *
          quittingPeriodThreeClearedEndpointDifference
            reward data.hazard phase who) by ring]
      exact mul_nonpos_of_nonneg_of_nonpos (hscale who).le hcontinue
    · rw [show data.hazard phase who *
          (scale who * quittingPeriodThreeClearedEndpointDifference
            reward data.hazard phase who) =
        scale who * (data.hazard phase who *
          quittingPeriodThreeClearedEndpointDifference
            reward data.hazard phase who) by ring]
      exact mul_nonneg (hscale who).le hquit
  fixedOpponentContracts := data.fixedOpponentContracts

end PeriodThreeClearedGapData

end GameTheory

end
