/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.Debt.Ledger.PunishClock

/-!
# Two residuals of the phase-switch deviation cap

`QuittingLedgerPunishClock.lean` supplies the ledger and its two clocks; the
one-sided cap of `QuittingPhaseSwitchDeviationCap.lean` consumes three
hypotheses, (a)-(c).  This file closes two of the remaining wiring gaps
between the clocks and hypotheses (b) and (c).  (Hypothesis (a)'s own gap --
relating the *truncated* plan's ledger to bounds proved for the untruncated
plan -- is not closed here: see the honest note below.)

## (2) Ceiling-IR punishment attainment for hypothesis (b)

`quittingTerminalPayoff_update_quittingAlwaysContinue_le_max`
(`QuittingSimpleBranches.lean`) already shows that against the all-continue
*behaviour* profile, a deviator's terminal payoff is at most `max 0 (reward
(quittingSingletonTerminal who) who)`.  Hypothesis (b) of the cap needs the
same fact stated for the *hazard-sequence* formalism the cap consumes.  The
bridge is definitional: the root-sequence profile generated by the constant
sequence `fun _ => quittingAllContinueRoot`, started at stage `0`, is
literally `quittingAlwaysContinueProfile` (both are the constant profile
`fun _ _ _ => PMF.pure false`), so the live-hazard collapse
(`quittingRootSequenceHazardTerminalValue_eq_terminalPayoff_update`) reduces
hypothesis (b) for that punishment plan to the already-proved behaviour-level
bound.

The resulting punishment is only ever *credible* for **ceiling-IR** targets:
a target payoff `v` for the punished player with `v who ≥ max 0 (reward
(quittingSingletonTerminal who) who)`.  Targets strictly between the true
min-max punishment level and this ceiling need the true punishment
attainment, which is the separate lower-bound question left open by
`QuittingPunishmentFloor.lean`'s "what is and is not true" -- the naive floor
`max 0 (reward (quittingSingletonTerminal who) who) ≤ punishmentLevel` is
false in general, so nothing here claims the ceiling is *reached* below it,
only that it caps the punished player's incentive from above.

## (3) The Case-2 survival wiring for hypothesis (c)

Hypothesis (c) needs `quittingOpponentSurvivalWeight plan who 0 switch ≤
survivalCap` for the player `who` under test.  In Simon's Case 2 -- the
switch stage `î` achieved by the punished player `target`'s own
planned-survival clock `i^target_♯` at threshold `ε / M`
(`quittingRootSequencePlannedSurvivalStoppingIndex`) -- this is wired from a
single observation: `quittingOpponentSurvivalWeight plan who 0 switch` is a
product over *every* opponent of `who`, and whenever `who ≠ target`, `target`
is one of those opponents.  A product of factors in `[0, 1]` is at most any
one of its own factors, so `target`'s own prescribed survival curve alone
already bounds the whole opponent-survival product, and the clock's defining
inequality closes it.

This is stated purely in terms of the *plan* `plan`, which is exactly the
shape hypothesis (c) wants and exactly why "whether or not others deviate"
is not a separate case to handle here: `target`'s own prescribed survival
curve is a function of `plan` alone, and a unilateral deviation by a third
player leaves `target`'s coordinate of `plan` untouched
(`quittingOpponentSurvivalWeight_quittingRootSequenceUpdate` records the
general fact that updating one coordinate cannot move another player's
opponent-survival weight).

The honest scope: this covers every deviator `who ≠ target`.  The case
`who = target` -- the punished player's own incentive to deviate from a plan
that is about to punish someone else, or Simon's Case 1 where the switch is
instead achieved by a ledger clock -- is not addressed; it needs a different
argument and is out of scope here.

## The residual left untouched: hypothesis (a)'s truncation transfer

The dispatch for this file also asked to relate `quittingLedger reward
(quittingTruncatedRoots plan switch) who index` (what hypothesis (a) is fed,
via `quittingRootSequenceHazardTerminalValue_quittingTruncatedRoots_le_of_ledger_le`
in `QuittingLedgerPunishClock.lean`) to `quittingLedger reward plan who
index` (what the clocks bound).  Working the recursion out: the Bellman
identity behind `quittingRootSequenceTerminalValue` is affine with slope the
*joint* continue mass, so for `stage < switch` the two root sequences agree
and the values obey the same one-step recursion with the same coefficients,
but seeded from different values at `switch` itself (`0` for the truncated
sequence versus the plan's own genuine continuation value there).  The two
value curves therefore differ by `quittingJointSurvivalWeight (from index to
switch) * (-quittingRootSequenceTerminalValue reward plan who switch)` at
*every* index up to `switch`, not only at `switch - 1` -- the discrepancy
does not stay localised to the last stage, it back-propagates geometrically
through the whole prefix via the survival weight.  Consequently `quittingLedger
reward (quittingTruncatedRoots plan switch) who index = quittingLedger reward
plan who index` is **false** in general for `index ≥ 1` (the two sides agree
only trivially at `index = 0`): the correct relation is an explicit
correction term, not a plain equality, and closing it honestly would need
either that correction folded into `ε` throughout the assembled cap or an
independent argument that it vanishes in the limit relevant to Proposition 3.
That is more than a wiring lemma and is not attempted here.
-/

noncomputable section

namespace GameTheory

open StochasticGame Math.Probability Math.PMFProduct

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-! ## (2) Ceiling-IR punishment attainment -/

omit [DecidableEq ι] in
/-- The root-sequence profile generated by the constant all-continue root,
started at stage zero, is literally the all-continue behaviour profile: both
sides are the constant profile that hands every player pure Continue after
every history. -/
theorem quittingRootSequenceProfile_quittingAllContinueRoot_zero_eq
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) :
    quittingRootSequenceProfile reward (fun _ => quittingAllContinueRoot) 0 =
      quittingAlwaysContinueProfile reward :=
  rfl

/-- **Hypothesis (b), ceiling form.**  Every unilateral hazard deviation
against the all-continue punishment plan gains at most `max 0 (reward
(quittingSingletonTerminal who) who)`: the live-hazard collapse turns the
hazard-sequence statement into `quittingTerminalPayoff_update_quittingAlwaysContinue_le_max`,
whose content is that only the deviator's own singleton terminal state is
reachable against opponents who never quit. -/
theorem quittingRootSequenceHazardTerminalValue_quittingAllContinueRoots_le_max
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) (who : ι)
    (hazard : ℕ → PMF Bool) :
    quittingRootSequenceHazardTerminalValue reward
        (fun _ => quittingAllContinueRoot) who hazard 0 ≤
      max 0 (reward (quittingSingletonTerminal who) who) := by
  rw [quittingRootSequenceHazardTerminalValue_eq_terminalPayoff_update,
    quittingRootSequenceProfile_quittingAllContinueRoot_zero_eq]
  exact quittingTerminalPayoff_update_quittingAlwaysContinue_le_max reward who
    (fun time _history => hazard time)

/-- **Hypothesis (b), in the exact shape the cap consumes.**  Taking `punish
:= fun _ => quittingAllContinueRoot` and `punishCap := max 0 (reward
(quittingSingletonTerminal who) who)`, every nonnegative slack `punishError`
discharges hypothesis (b) of
`quittingRootSequenceHazardTerminalValue_quittingPhaseSwitchRoots_le` /
`quittingTerminalPayoff_update_quittingPhaseSwitchProfile_le` verbatim. -/
theorem hpunish_quittingAllContinueRoots
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) (who : ι)
    {punishError : ℝ} (hpunishError : 0 ≤ punishError) (g : ℕ → PMF Bool) :
    quittingRootSequenceHazardTerminalValue reward
        (fun _ => quittingAllContinueRoot) who g 0 ≤
      max 0 (reward (quittingSingletonTerminal who) who) + punishError := by
  have hbound :=
    quittingRootSequenceHazardTerminalValue_quittingAllContinueRoots_le_max reward who g
  linarith

/-- **Ceiling-IR targets are covered.**  Whenever a target payoff `v` for the
punished player dominates the solo-clipped ceiling, the same all-continue
punishment discharges hypothesis (b) against `v who` with the identical
slack.  This is the honest scope of the attainment result: targets strictly
between the true min-max punishment level and the ceiling need the true
punishment attainment, which is not addressed here. -/
theorem hpunish_quittingAllContinueRoots_of_ceilingIR
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) (who : ι) (v : Payoff ι)
    (hv : max 0 (reward (quittingSingletonTerminal who) who) ≤ v who)
    {punishError : ℝ} (hpunishError : 0 ≤ punishError) (g : ℕ → PMF Bool) :
    quittingRootSequenceHazardTerminalValue reward
        (fun _ => quittingAllContinueRoot) who g 0 ≤ v who + punishError := by
  have hbound := hpunish_quittingAllContinueRoots reward who hpunishError g
  linarith

/-! ## (3) The Case-2 survival wiring -/

/-- **A single opponent's continue probability bounds the whole deleted
mass.**  At one root, deleting `who`'s own coordinate leaves a product over
the remaining players; any one marked opponent's own continue probability
already bounds that whole product, since every factor lies in `[0, 1]`. -/
theorem quittingRootDeletedContinueMass_le_of_ne
    (root : ι → PMF Bool) {who marked : ι} (hmarked : marked ≠ who) :
    quittingRootDeletedContinueMass root who ≤ (root marked false).toReal := by
  unfold quittingRootDeletedContinueMass
  rw [quittingStationaryContinueMass_eq_prod_continueProbability]
  set forced : ι → PMF Bool := Function.update root who (PMF.pure false) with hforced
  set continueProbability : ι → ℝ := fun player => (forced player false).toReal
    with hcontinueProbability
  have hfactor0 : ∀ player, 0 ≤ continueProbability player :=
    fun _ => ENNReal.toReal_nonneg
  have hfactor1 : ∀ player, continueProbability player ≤ 1 := fun player =>
    ENNReal.toReal_mono ENNReal.one_ne_top (PMF.coe_le_one (forced player) false)
  have hrest1 :
      (∏ player ∈ (Finset.univ.erase marked : Finset ι), continueProbability player) ≤ 1 :=
    Finset.prod_le_one (fun player _ => hfactor0 player) (fun player _ => hfactor1 player)
  have hsplit :
      (∏ player, continueProbability player) =
        (∏ player ∈ (Finset.univ.erase marked : Finset ι), continueProbability player) *
          continueProbability marked := by
    simpa using (Finset.prod_erase_mul Finset.univ continueProbability
      (Finset.mem_univ marked)).symm
  have hmarkedEq : continueProbability marked = (root marked false).toReal := by
    simp [hcontinueProbability, hforced, Function.update_of_ne hmarked]
  rw [hsplit, hmarkedEq]
  nlinarith [mul_nonneg (sub_nonneg.mpr hrest1) (ENNReal.toReal_nonneg (a := root marked false))]

/-- The single-opponent bound, read off a root sequence at a fixed stage. -/
theorem quittingFixedOpponentsContinueMass_le_of_ne
    (roots : ℕ → ι → PMF Bool) {who marked : ι} (hmarked : marked ≠ who) (time : ℕ) :
    quittingFixedOpponentsContinueMass roots who time ≤
      (roots time marked false).toReal :=
  quittingRootDeletedContinueMass_le_of_ne (roots time) hmarked

/-- **The opponent-survival product is bounded by any one opponent's own
survival curve.**  Whenever `marked ≠ who`, `marked` is one factor inside
every stage of `who`'s opponent-survival product, so `marked`'s own
prescribed survival curve already bounds the whole product. -/
theorem quittingOpponentSurvivalWeight_le_quittingHazardSurvival_ownHazard
    (roots : ℕ → ι → PMF Bool) {who marked : ι} (hmarked : marked ≠ who) (fuel : ℕ) :
    quittingOpponentSurvivalWeight roots who 0 fuel ≤
      quittingHazardSurvival (quittingRootSequenceOwnHazard roots marked) fuel := by
  unfold quittingOpponentSurvivalWeight
  rw [quittingHazardSurvival_quittingRootSequenceOwnHazard]
  simp only [Nat.zero_add]
  apply Finset.prod_le_prod
  · intro offset _
    exact quittingStationaryContinueMass_nonneg _
  · intro offset _
    exact quittingFixedOpponentsContinueMass_le_of_ne roots hmarked offset

/-- **Case 2's reach-probability bound.**  If the switch stage is exactly the
punished player `target`'s own planned-survival stopping index at threshold
`ε / M` (Simon's Case 2, `î = i^target_♯`), then for every *other* player
`who` the plan's opponent-survival weight through the switch stage is at
most `ε / M` too -- one of `who`'s opponents is `target`, and `target`'s own
prescribed survival is already at or below the threshold there.  This is
hypothesis (c) of the phase-switch cap in that case, stated on the plan
alone and so independent of whatever `who` (or any third player) chooses to
play. -/
theorem quittingOpponentSurvivalWeight_le_of_eq_quittingRootSequencePlannedSurvivalStoppingIndex
    (plan : ℕ → ι → PMF Bool) {target who : ι} (hwho : who ≠ target) (threshold : ℝ)
    {switch : ℕ}
    (hswitch : switch =
      quittingRootSequencePlannedSurvivalStoppingIndex plan target threshold)
    (hexists : ∃ cutoff,
      quittingHazardSurvival (quittingRootSequenceOwnHazard plan target) cutoff ≤
        threshold) :
    quittingOpponentSurvivalWeight plan who 0 switch ≤ threshold := by
  have hbound := quittingHazardSurvival_quittingRootSequencePlannedSurvivalStoppingIndex_le
    plan target hexists
  rw [← hswitch] at hbound
  exact (quittingOpponentSurvivalWeight_le_quittingHazardSurvival_ownHazard
    plan hwho.symm switch).trans hbound

/-- **Case 2, with the deviator quantifier made explicit.**  The bound above,
packaged as hypothesis (c) needs it: quantified over every candidate deviator
other than the punished player. -/
theorem quittingOpponentSurvivalWeight_le_of_target_plannedSurvivalStoppingIndex
    (plan : ℕ → ι → PMF Bool) (target : ι) (threshold : ℝ) {switch : ℕ}
    (hswitch : switch =
      quittingRootSequencePlannedSurvivalStoppingIndex plan target threshold)
    (hexists : ∃ cutoff,
      quittingHazardSurvival (quittingRootSequenceOwnHazard plan target) cutoff ≤
        threshold) :
    ∀ who : ι, who ≠ target →
      quittingOpponentSurvivalWeight plan who 0 switch ≤ threshold :=
  fun _who hwho =>
    quittingOpponentSurvivalWeight_le_of_eq_quittingRootSequencePlannedSurvivalStoppingIndex
      plan hwho threshold hswitch hexists

end GameTheory
