/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.VanishingDiscount.Fink.Schedule
import UniformEquilibrium.VanishingDiscount.Analytic.Accounting.ProcessedHarmonicResponseAlternative

/-!
# Behavioral realization of predictable invisible-response mixtures

A predictable selector in the processed harmonic response alternative is a
PMF over source-tagged invisible actions.  This file realizes it as an actual
behavior strategy for the owning player against the scheduled Bellman
profile.

The selector is pushed forward to the player's action space.  Distinct
response indices carrying the same action are therefore combined
automatically by `PMF.map`.  Source compatibility ensures that every index
with positive mass belongs to the current-state fiber.  The resulting
one-step state law is exactly the selector mixture of the corresponding
scheduled pure-deviation kernels.

The universal calendar need not lie inside an arbitrary germ radius during
its finitely many initial stages.  We use the endpoint Fink profile as a
fallback there.  Once the calendar enters the germ interval, the scheduled
kernels are exactly the moving Fink pure-deviation kernels.

Finally, the actual state-history marginal of the stochastic-game history
law is identified with the adaptive state-history law generated by those
mixed kernels.  It is therefore an admissible `historyLaw` for the calendar
response alternative, with no opaque realization interface.
-/

noncomputable section

namespace GameTheory
namespace StochasticGame
namespace AnalyticBellmanGerm
namespace LowerValueJet

open Math Math.PMFProduct Math.Probability Set

variable {ι : Type} [Fintype ι] [DecidableEq ι]
  {G : StochasticGame ι}
  [Fintype G.State] [DecidableEq G.State]
  [∀ i, Fintype (G.Act i)] [∀ i, DecidableEq (G.Act i)]
  {germ : G.AnalyticBellmanGerm}

/-- Public state history obtained by forgetting past actions from a game
history and appending its current state. -/
def stateHistoryOfHist {stage : ℕ} (history : G.Hist stage) :
    Fin (stage + 1) → G.State :=
  Fin.snoc (fun index => (history.1 index).1) history.2

omit [Fintype ι] [DecidableEq ι] [Fintype G.State]
    [DecidableEq G.State] [∀ i, Fintype (G.Act i)]
    [∀ i, DecidableEq (G.Act i)] in
@[simp]
theorem stateHistoryOfHist_last {stage : ℕ} (history : G.Hist stage) :
    stateHistoryOfHist history (Fin.last stage) = history.2 := by
  simp [stateHistoryOfHist]

omit [Fintype ι] [DecidableEq ι] [Fintype G.State]
    [DecidableEq G.State] [∀ i, Fintype (G.Act i)]
    [∀ i, DecidableEq (G.Act i)] in
@[simp]
theorem stateHistoryOfHist_empty (initial : G.State) :
    stateHistoryOfHist (G.emptyHist initial) =
      fun _ : Fin 1 => initial := by
  funext index
  have index_eq : index = Fin.last 0 := Fin.ext (by omega)
  rw [index_eq, stateHistoryOfHist_last]
  rfl

omit [Fintype ι] [DecidableEq ι] [Fintype G.State]
    [DecidableEq G.State] [∀ i, Fintype (G.Act i)]
    [∀ i, DecidableEq (G.Act i)] in
@[simp]
theorem stateHistoryOfHist_snoc
    {stage : ℕ} (history : G.Hist stage)
    (jointAction : G.JointAct) (successor : G.State) :
    stateHistoryOfHist
        ((Fin.snoc history.1 (history.2, jointAction), successor) :
          G.Hist (stage + 1)) =
      Fin.snoc (stateHistoryOfHist history) successor := by
  funext index
  refine Fin.lastCases ?_ (fun earlier => ?_) index
  · simp [stateHistoryOfHist]
  · refine Fin.lastCases ?_ (fun old => ?_) earlier
    · simp [stateHistoryOfHist]
    · simp [stateHistoryOfHist]

/-- The scheduled Fink mixed profile.  Before the universal scale enters
the germ interval, use the endpoint profile as a finite-prefix fallback. -/
def calendarFinkMixedProfile
    (germ : G.AnalyticBellmanGerm)
    (stage : ℕ) (source : G.State) :
    ∀ player, PMF (G.Act player) :=
  if valid :
      residualCalendarScale stage ∈ Ioo (0 : ℝ) germ.radius then
    G.finkProfile (germ.finkPointAt valid) source
  else
    germ.endpointProfile source

omit [DecidableEq G.State] in
theorem calendarFinkMixedProfile_eq_finkPointAt
    (germ : G.AnalyticBellmanGerm)
    (stage : ℕ)
    (valid :
      residualCalendarScale stage ∈ Ioo (0 : ℝ) germ.radius)
    (source : G.State) :
    calendarFinkMixedProfile germ stage source =
      G.finkProfile (germ.finkPointAt valid) source := by
  simp [calendarFinkMixedProfile, valid]

/-- The baseline behavior profile associated with the safe universal
calendar schedule. -/
def calendarFinkBehaviorProfile
    (germ : G.AnalyticBellmanGerm) : G.BehaviorProfile :=
  G.scheduledMarkovBehaviorProfile
    (fun stage source => calendarFinkMixedProfile germ stage source)

/-- Scheduled pure-deviation state kernel carried by one source-tagged
invisible response. -/
def calendarInvisibleResponseKernel
    (germ : G.AnalyticBellmanGerm) {who : ι}
    (stage : ℕ) (response : germ.InvisibleNeutralAction who) :
    PMF G.State :=
  (pmfPi
    (Function.update
      (calendarFinkMixedProfile germ stage response.source)
      who (PMF.pure response.1.2))).bind
    (G.transition response.source)

omit [DecidableEq G.State] in
/-- Once the calendar parameter is valid, the scheduled response kernel is
the semantic moving Fink pure-deviation kernel. -/
theorem calendarInvisibleResponseKernel_eq_finkPointAt
    (germ : G.AnalyticBellmanGerm) {who : ι}
    (stage : ℕ)
    (valid :
      residualCalendarScale stage ∈ Ioo (0 : ℝ) germ.radius)
    (response : germ.InvisibleNeutralAction who) :
    calendarInvisibleResponseKernel germ stage response =
      G.finkPureDeviationStateKernel
        (germ.finkPointAt valid)
        response.source who response.1.2 := by
  unfold calendarInvisibleResponseKernel finkPureDeviationStateKernel
  rw [calendarFinkMixedProfile_eq_finkPointAt germ stage valid]

omit [DecidableEq G.State] in
/-- On a finite-prefix stage outside the germ interval, the scheduled
response kernel is the endpoint pure-deviation kernel, not a moving one. -/
theorem calendarInvisibleResponseKernel_eq_endpoint
    (germ : G.AnalyticBellmanGerm) {who : ι}
    (stage : ℕ)
    (invalid :
      ¬residualCalendarScale stage ∈ Ioo (0 : ℝ) germ.radius)
    (response : germ.InvisibleNeutralAction who) :
    calendarInvisibleResponseKernel germ stage response =
      G.finkPureDeviationStateKernel
        germ.endpointFinkPoint
        response.source who response.1.2 := by
  unfold calendarInvisibleResponseKernel
    calendarFinkMixedProfile finkPureDeviationStateKernel
  rw [dif_neg invalid]
  rw [germ.finkProfile_endpointFinkPoint]

/-- Actual behavior strategy obtained by pushing a predictable response
selector to the owner's action space.  Action-map collisions are summed by
the PMF pushforward. -/
def invisibleResponseBehaviorStrategy
    (germ : G.AnalyticBellmanGerm) (who : ι)
    (selection :
      ∀ stage, (Fin (stage + 1) → G.State) →
        PMF (germ.InvisibleNeutralAction who)) :
    G.BehaviorStrategy who :=
  fun stage history =>
    (selection stage (stateHistoryOfHist history)).map
      fun response => response.1.2

/-- Behavior profile in which the fixed owner realizes the response
selector and every other player follows the scheduled Fink profile. -/
def realizedInvisibleResponseProfile
    (germ : G.AnalyticBellmanGerm) (who : ι)
    (selection :
      ∀ stage, (Fin (stage + 1) → G.State) →
        PMF (germ.InvisibleNeutralAction who)) :
    G.BehaviorProfile :=
  Function.update (calendarFinkBehaviorProfile germ) who
    (invisibleResponseBehaviorStrategy germ who selection)

/-- One-step state law induced by a behavior profile after a game history. -/
def behaviorStateStep
    (profile : G.BehaviorProfile)
    {stage : ℕ} (history : G.Hist stage) : PMF G.State :=
  (G.stageActionDist profile history).bind
    (G.transition history.2)

/-- The selector mixture of scheduled response kernels after one public
state history. -/
def calendarInvisibleMixedStep
    (germ : G.AnalyticBellmanGerm) {who : ι}
    (selection :
      ∀ stage, (Fin (stage + 1) → G.State) →
        PMF (germ.InvisibleNeutralAction who))
    (stage : ℕ) (history : Fin (stage + 1) → G.State) :
    PMF G.State :=
  (selection stage history).bind
    (calendarInvisibleResponseKernel germ stage)

omit [DecidableEq G.State] in
/-- A source-compatible selector cannot put all its mass outside the current
source fiber.  In particular, the current fiber contains an invisible
response whenever such a selector is supplied. -/
theorem exists_invisibleResponse_at_currentSource
    (germ : G.AnalyticBellmanGerm) {who : ι}
    (selection :
      ∀ stage, (Fin (stage + 1) → G.State) →
        PMF (germ.InvisibleNeutralAction who))
    (source_compatible :
      ∀ stage history response,
        selection stage history response ≠ 0 →
          response.source = history (Fin.last stage))
    (stage : ℕ) (history : Fin (stage + 1) → G.State) :
    ∃ response : germ.InvisibleNeutralAction who,
      response.source = history (Fin.last stage) := by
  let response :=
    (selection stage history).support_nonempty.choose
  exact
    ⟨response,
      source_compatible stage history response
        (selection stage history).support_nonempty.choose_spec⟩

omit [DecidableEq G.State] in
/-- Exact operational realization.  Pushing the response selector through
the action map, independently mixing opponents, and applying the game
transition gives precisely the selector mixture of scheduled response
kernels. -/
theorem behaviorStateStep_realizedInvisibleResponseProfile
    (germ : G.AnalyticBellmanGerm) (who : ι)
    (selection :
      ∀ stage, (Fin (stage + 1) → G.State) →
        PMF (germ.InvisibleNeutralAction who))
    (source_compatible :
      ∀ stage history response,
        selection stage history response ≠ 0 →
          response.source = history (Fin.last stage))
    {stage : ℕ} (history : G.Hist stage) :
    behaviorStateStep
        (realizedInvisibleResponseProfile germ who selection)
        history =
      calendarInvisibleMixedStep germ selection stage
        (stateHistoryOfHist history) := by
  unfold behaviorStateStep realizedInvisibleResponseProfile
  change
    (G.stageActionDist
      (Function.update
        (G.scheduledMarkovBehaviorProfile
          (fun stage source =>
            calendarFinkMixedProfile germ stage source))
        who
        (invisibleResponseBehaviorStrategy germ who selection))
      history).bind (G.transition history.2) =
      calendarInvisibleMixedStep germ selection stage
        (stateHistoryOfHist history)
  rw [G.stageActionDist_update_scheduledMarkovBehaviorProfile]
  unfold invisibleResponseBehaviorStrategy
    calendarInvisibleMixedStep
  rw [pmfPi_update_bind, PMF.bind_bind, PMF.bind_map]
  apply ProbabilityMassFunction.bind_congr_on_support
  intro response response_mem
  have source_eq :
      response.source = history.2 := by
    rw [← stateHistoryOfHist_last history]
    exact
      source_compatible stage (stateHistoryOfHist history)
        response response_mem
  unfold calendarInvisibleResponseKernel
  rw [source_eq]
  rfl

/-- Actual public state-history marginal generated by the realized behavior
profile. -/
def realizedInvisibleStateHistoryLaw
    (germ : G.AnalyticBellmanGerm) (who : ι)
    (initial : G.State)
    (selection :
      ∀ stage, (Fin (stage + 1) → G.State) →
        PMF (germ.InvisibleNeutralAction who))
    (stage : ℕ) :
    PMF (Fin (stage + 1) → G.State) :=
  (G.histDist
    (realizedInvisibleResponseProfile germ who selection)
    initial stage).map stateHistoryOfHist

omit [DecidableEq G.State] in
/-- One-step recursion for the actual public state-history marginal. -/
theorem realizedInvisibleStateHistoryLaw_succ
    (germ : G.AnalyticBellmanGerm) (who : ι)
    (initial : G.State)
    (selection :
      ∀ stage, (Fin (stage + 1) → G.State) →
        PMF (germ.InvisibleNeutralAction who))
    (source_compatible :
      ∀ stage history response,
        selection stage history response ≠ 0 →
          response.source = history (Fin.last stage))
    (stage : ℕ) :
    realizedInvisibleStateHistoryLaw germ
        who initial selection (stage + 1) =
      (realizedInvisibleStateHistoryLaw germ
        who initial selection stage).bind fun history =>
          (calendarInvisibleMixedStep germ
            selection stage history).map
              (Fin.snoc history) := by
  unfold realizedInvisibleStateHistoryLaw
  rw [G.histDist_succ, PMF.map_bind]
  calc
    (G.histDist
        (realizedInvisibleResponseProfile germ who selection)
        initial stage).bind
        (fun history =>
          (((G.stageActionDist
              (realizedInvisibleResponseProfile germ who selection)
              history).bind
                (fun jointAction =>
                  (G.transition history.2 jointAction).bind
                    (fun successor =>
                      PMF.pure
                        ((Fin.snoc history.1
                          (history.2, jointAction), successor) :
                            G.Hist (stage + 1))))).map
            stateHistoryOfHist)) =
      (G.histDist
        (realizedInvisibleResponseProfile germ who selection)
        initial stage).bind
        (fun history =>
          (behaviorStateStep
            (realizedInvisibleResponseProfile germ who selection)
            history).map
              (Fin.snoc (stateHistoryOfHist history))) := by
        congr 1
        funext history
        rw [PMF.map_bind, behaviorStateStep]
        rw [PMF.map_bind]
        congr 1
        funext jointAction
        rw [PMF.map_bind]
        congr 1
        funext successor
        simp only [PMF.pure_map, Function.comp_apply]
        exact congrArg PMF.pure
          (stateHistoryOfHist_snoc history jointAction successor)
    _ =
      (G.histDist
        (realizedInvisibleResponseProfile germ who selection)
        initial stage).bind
        (fun history =>
          (calendarInvisibleMixedStep germ selection stage
            (stateHistoryOfHist history)).map
              (Fin.snoc (stateHistoryOfHist history))) := by
        congr 1
        funext history
        rw [
          behaviorStateStep_realizedInvisibleResponseProfile germ
            who selection source_compatible history]
    _ =
      ((G.histDist
        (realizedInvisibleResponseProfile germ who selection)
        initial stage).map stateHistoryOfHist).bind
        (fun history =>
          (calendarInvisibleMixedStep germ
            selection stage history).map
              (Fin.snoc history)) := by
        rw [PMF.bind_map]
        rfl

omit [DecidableEq G.State] in
/-- The actual public state-history marginal is exactly the adaptive
history law generated by the corresponding mixed moving response kernels. -/
theorem realizedInvisibleStateHistoryLaw_eq_adaptiveHistoryLaw
    (germ : G.AnalyticBellmanGerm) (who : ι)
    (initial : G.State)
    (selection :
      ∀ stage, (Fin (stage + 1) → G.State) →
        PMF (germ.InvisibleNeutralAction who))
    (source_compatible :
      ∀ stage history response,
        selection stage history response ≠ 0 →
          response.source = history (Fin.last stage))
    (stage : ℕ) :
    realizedInvisibleStateHistoryLaw germ who initial selection stage =
      adaptiveHistoryLaw
        (adaptiveMarkovStep initial
          (calendarInvisibleMixedStep germ selection))
        (stage + 1) := by
  induction stage with
  | zero =>
      unfold realizedInvisibleStateHistoryLaw
      rw [G.histDist_zero, PMF.pure_map]
      rw [adaptiveHistoryLaw_succ, adaptiveHistoryLaw_zero]
      rw [PMF.pure_bind, adaptiveMarkovStep_zero, PMF.pure_map]
      exact congrArg PMF.pure (stateHistoryOfHist_empty initial)
  | succ stage inductionHypothesis =>
      rw [
        realizedInvisibleStateHistoryLaw_succ germ
          who initial selection source_compatible stage,
        inductionHypothesis]
      rw [
        adaptiveHistoryLaw_succ
          (adaptiveMarkovStep initial
            (calendarInvisibleMixedStep germ selection))
          (stage + 1)]
      rfl

omit [DecidableEq G.State] in
/-- The calendar response alternative applied to the actual state-history
law of the realizing behavior strategy. -/
theorem
    HarmonicInvisibleQuotientCorrection.ownedStagePublicResponse_or_realizedSublinearPositiveGain
    {jet : germ.LowerValueJet} {who : ι}
    {family : jet.InvisibleNeutralQuotientFamily who}
    (correction :
      jet.HarmonicInvisibleQuotientCorrection who family)
    (initial : G.State)
    (selection :
      ∀ stage, (Fin (stage + 1) → G.State) →
        PMF (germ.InvisibleNeutralAction who))
    (source_compatible :
      ∀ stage history response,
        selection stage history response ≠ 0 →
          response.source = history (Fin.last stage)) :
    (∃ response : germ.InvisibleNeutralAction who,
        Nonempty
          (AnalyticFinkStagePublicResponse germ
            (ownedInvisibleForwardResponse response))) ∨
      (IsAsymptoticallySublinear
          (correction.calendarPositiveResponseGain
            (realizedInvisibleStateHistoryLaw germ
              who initial selection)
            selection) ∧
        ∀ stage,
          realizedInvisibleStateHistoryLaw
              germ who initial selection stage =
            adaptiveHistoryLaw
              (adaptiveMarkovStep initial
                (calendarInvisibleMixedStep germ selection))
              (stage + 1)) := by
  rcases
      correction.ownedStagePublicResponse_or_sublinearPositiveGain
        (realizedInvisibleStateHistoryLaw germ who initial selection)
        selection with response | sublinear
  · exact Or.inl response
  · exact Or.inr
      ⟨sublinear,
        realizedInvisibleStateHistoryLaw_eq_adaptiveHistoryLaw
          germ who initial selection source_compatible⟩

end LowerValueJet
end AnalyticBellmanGerm
end StochasticGame
end GameTheory
