import UniformEquilibrium.Quitting.Classification.InstantPunishmentSureQuitterCharacterization
import UniformEquilibrium.Quitting.Terminal.TargetTail.TerminalTargetSemantics

noncomputable section

namespace GameTheory

open StochasticGame

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- The literal payoff generated by a supplied root against the coordinatewise
punishment vector. -/
def quittingPunishmentSureRootTarget
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool) : Payoff ι :=
  quittingRootSuccessorPayoff reward
    (fun who ↦ quittingPunishmentValue reward who) root

/-- A supplied exact punishment-vector Nash root with a sure quitter produces
its own literal successor payoff as a uniform-equilibrium payoff, and that
same payoff lies above the punishment vector. -/
theorem quittingPunishmentSureRootTarget_isUniformEquilibriumPayoff_and_floor
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (quitter : ι) (root : ι → PMF Bool)
    (hquit : root quitter = PMF.pure true)
    (hdefect : ∀ player,
      quittingRootCoordinateNashDefect reward
        (fun who ↦ quittingPunishmentValue reward who) root player = 0) :
    (quittingGame reward).IsUniformEquilibriumPayoff none
        (quittingPunishmentSureRootTarget reward root) ∧
      ∀ who, quittingPunishmentValue reward who ≤
        quittingPunishmentSureRootTarget reward root who := by
  let punishment : Payoff ι := fun who ↦ quittingPunishmentValue reward who
  have hnash : IsεQuittingRootNash reward punishment 0 root :=
    (isZeroQuittingRootNash_iff_coordinateNashDefect_eq_zero
      reward punishment root).2 hdefect
  have hsure : QuittingRootHasSureQuitter root := ⟨quitter, hquit⟩
  have hcontinueMass : quittingStationaryContinueMass root = 0 := by
    have hmass := (quittingRootHasSureQuitter_iff_allContinue_mass_zero root).1 hsure
    unfold quittingStationaryContinueMass quittingAllContinueAction
    rw [hmass]
    rfl
  constructor
  · apply quittingGame_isUniformEquilibriumPayoff_of_terminalNash_all_errors_fixedTarget
    intro ε hε
    have hsupport : IsQuittingRootSupportApproxNash reward punishment 0 root :=
      isQuittingRootSupportApproxNash_zero_of_isZeroNash reward punishment root hnash
    have hrational : QuittingSimonRationalPayoffAt reward 0 punishment := by
      intro who
      simp [punishment]
    obtain ⟨punishRow, -, hterminal⟩ :=
      exists_oneStagePunishedProfile_of_rational_support_sureQuitter
        reward punishment root quitter (η := 0) (δ := ε) le_rfl hε
          hrational hsupport hquit
    refine ⟨quittingOneStagePunishedProfile reward root punishRow, by simpa using hterminal, ?_⟩
    funext who
    rw [quittingTerminalPayoff_oneStagePunishedProfile reward root punishRow who
      hcontinueMass]
    unfold quittingPunishmentSureRootTarget
    rw [quittingRootSuccessorPayoff_apply_eq_affine, hcontinueMass, zero_mul, add_zero]
  · intro who
    exact quittingPunishmentValue_le_rootSuccessorPayoff_of_tail_ge
      reward punishment root who (by rfl) hnash

/-- The finite sure-root condition exposes a witness whose own successor
payoff is a punishment-individually-rational uniform-equilibrium payoff. -/
theorem exists_punishmentSureRootTarget_of_hasPunishmentVectorNashRootWithSureQuitter
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (hroot : HasQuittingPunishmentVectorNashRootWithSureQuitter reward) :
    ∃ (quitter : ι) (root : ι → PMF Bool),
      root quitter = PMF.pure true ∧
        (∀ player,
          quittingRootCoordinateNashDefect reward
            (fun who ↦ quittingPunishmentValue reward who) root player = 0) ∧
        (quittingGame reward).IsUniformEquilibriumPayoff none
          (quittingPunishmentSureRootTarget reward root) ∧
        ∀ who, quittingPunishmentValue reward who ≤
          quittingPunishmentSureRootTarget reward root who := by
  obtain ⟨quitter, root, hquit, hdefect⟩ := hroot
  obtain ⟨huniform, hfloor⟩ :=
    quittingPunishmentSureRootTarget_isUniformEquilibriumPayoff_and_floor
      reward quitter root hquit hdefect
  exact ⟨quitter, root, hquit, hdefect, huniform, hfloor⟩

end GameTheory
