/-
Copyright (c) 2026 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/

import UniformEquilibrium.Quitting.Classification.InstantPunishmentEquivalence
import UniformEquilibrium.Quitting.Classification.LCP.StrategicTransport
import UniformEquilibrium.Quitting.Paths.LiveTail

/-!
# The three existence branches over a payoff table with a nonzero never payoff

The repository quitting game fixes the payoff of never terminating to zero,
while the model of Ashkenazi-Golan, Krasikov, Rainer and Solan,
*Absorption paths and equilibria in quitting games*, Mathematical Programming
(2022), Section 3, allows an arbitrary payoff `r(C)` when nobody ever quits.
`GameTheory.QuittingLCPClassification.QuittingPayoffTable` is that larger
model: terminal rewards together with a never payoff.

This file states the three branches of Theorem 3.4 over a payoff table and
reduces each to the zero-never branch of
`UniformEquilibrium/Quitting/Classification/ExistenceBranches.lean` at the
translated reward `QuittingPayoffTable.zeroNeverReward`.  The current
zero-never statements are therefore the normalized case by theorem rather than
by convention.

## The strategic carrier

A quitting game's states, action sets and transitions do not mention the
reward table; only its stage payoffs do.  So `(quittingGame r).BehaviorProfile`
is the same type for every `r`, and the absorption masses do not depend on `r`
either: `quittingAbsorbedMassLimit_congr_reward`.  The definitions below take
the game generated by the table's own terminal rewards as their strategic
carrier and attach `QuittingPayoffTable.terminalPayoff` as the payoff
functional; that functional, not the carrier's stage payoff, is what pays the
never payoff on the nonabsorption event.

## The adapter

`QuittingPayoffTable.terminalPayoff_eq_add_never` is the single computation
behind every reduction: on every profile the table pays exactly the translated
repository game's terminal payoff plus the player's own never payoff.  A
playerwise constant cancels from every unilateral comparison, so approximate
Nash inequalities, best-reply values, min-max values, and one-stage
`ε`-perfectness all transfer at the same error.
-/

noncomputable section

namespace GameTheory
namespace QuittingLCPClassification

open StochasticGame

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-! ## The dynamics do not depend on the reward table -/

/-- A behavior profile is unchanged when only the quitting game's reward
table changes. -/
def quittingBehaviorProfileCongrReward
    (reward reward' : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) :
    (quittingGame reward').BehaviorProfile :=
  profile

/-- A behavior strategy is unchanged when only the quitting game's reward
table changes. -/
def quittingBehaviorStrategyCongrReward
    (reward reward' : {S : Finset ι // S.Nonempty} → Payoff ι)
    (who : ι) (strategy : (quittingGame reward).BehaviorStrategy who) :
    (quittingGame reward').BehaviorStrategy who :=
  strategy

@[simp] theorem quittingBehaviorProfileCongrReward_update
    (reward reward' : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) (who : ι)
    (strategy : (quittingGame reward).BehaviorStrategy who) :
    quittingBehaviorProfileCongrReward reward reward'
        (Function.update profile who strategy) =
      Function.update (quittingBehaviorProfileCongrReward reward reward' profile)
        who (quittingBehaviorStrategyCongrReward reward reward' who strategy) :=
  rfl

omit [DecidableEq ι] in
/-- Public history distributions of a quitting game are the same for every
reward table: only the stage payoff of `quittingGame` mentions the table. -/
theorem histDist_quittingGame_congr_reward
    (reward reward' : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    (state : Option {S : Finset ι // S.Nonempty}) (time : ℕ) :
    (quittingGame reward).histDist profile state time =
      (quittingGame reward').histDist profile state time := by
  exact histDist_quittingGame_reward_irrelevant
    reward reward' profile state time

omit [DecidableEq ι] in
/-- Limiting absorption masses are the same for every reward table. -/
theorem quittingAbsorbedMassLimit_congr_reward
    (reward reward' : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile)
    (S : {S : Finset ι // S.Nonempty}) :
    quittingAbsorbedMassLimit reward profile S =
      quittingAbsorbedMassLimit reward' profile S := by
  exact quittingAbsorbedMassLimit_reward_irrelevant
    reward reward' profile S

omit [DecidableEq ι] in
/-- Splicing a root before a continuation profile does not depend on the
reward table either. -/
theorem quittingRootThenContinuationProfile_congr_reward
    (reward reward' : {S : Finset ι // S.Nonempty} → Payoff ι)
    (root : ι → PMF Bool)
    (continuation : (quittingGame reward).BehaviorProfile) :
    quittingRootThenContinuationProfile reward root continuation =
      quittingRootThenContinuationProfile reward' root continuation := by
  funext who time history
  cases time <;> rfl

omit [DecidableEq ι] in
/-- A root-sequence profile does not depend on the reward table. -/
theorem quittingRootSequenceProfile_congr_reward
    (reward reward' : {S : Finset ι // S.Nonempty} → Payoff ι)
    (roots : ℕ → ι → PMF Bool) (start : ℕ) :
    quittingRootSequenceProfile reward roots start =
      quittingRootSequenceProfile reward' roots start := by
  funext who time history
  rfl

/-! ## The payoff a table assigns to a behavior profile -/

/-- The repository reward obtained by subtracting each player's never payoff
from all of that player's outcomes.  It is the terminal part of the playerwise
translation that normalizes the never payoff to zero. -/
def QuittingPayoffTable.zeroNeverReward (table : QuittingPayoffTable ι) :
    {S : Finset ι // S.Nonempty} → Payoff ι :=
  fun S who => table.terminal S who - table.never who

/-- Normalizing the never payoff to zero is not a new operation: it is the
playerwise translation of `QuittingPayoffTable.translate` by the negated never
payoff, so anything already known to be translation invariant applies to it. -/
theorem QuittingPayoffTable.repository_zeroNeverReward
    (table : QuittingPayoffTable ι) :
    repositoryQuittingPayoffTable table.zeroNeverReward =
      table.translate (fun who => -table.never who) := by
  ext S who
  · simp [repositoryQuittingPayoffTable, QuittingPayoffTable.translate,
      QuittingPayoffTable.zeroNeverReward, sub_eq_add_neg]
  · simp [repositoryQuittingPayoffTable, QuittingPayoffTable.translate]

/-- Expected payoff of a payoff table on a behavior profile: absorbed states
receive the table's terminal rewards weighted by their limiting absorption
masses, and the residual nonabsorption mass receives the never payoff. -/
def QuittingPayoffTable.terminalPayoff (table : QuittingPayoffTable ι)
    (profile : (quittingGame table.terminal).BehaviorProfile) (who : ι) : ℝ :=
  (∑ S : {S : Finset ι // S.Nonempty},
      quittingAbsorbedMassLimit table.terminal profile S *
        table.terminal S who) +
    (1 - quittingTerminalAbsorptionMass table.terminal profile) *
      table.never who

/-- **The playerwise translation adapter.**  On every profile the table's
payoff is the translated repository game's terminal payoff plus that player's
never payoff, whether or not the profile absorbs. -/
theorem QuittingPayoffTable.terminalPayoff_eq_add_never
    (table : QuittingPayoffTable ι)
    (profile : (quittingGame table.terminal).BehaviorProfile) (who : ι) :
    table.terminalPayoff profile who =
      quittingTerminalPayoff table.zeroNeverReward profile who +
        table.never who := by
  classical
  set mass : {S : Finset ι // S.Nonempty} → ℝ :=
    fun S => quittingAbsorbedMassLimit table.terminal profile S with hmassdef
  have hmass : ∀ S, quittingAbsorbedMassLimit table.zeroNeverReward profile S =
      mass S := fun S =>
    quittingAbsorbedMassLimit_congr_reward table.zeroNeverReward table.terminal
      profile S
  have hsplit : (∑ S, mass S * table.zeroNeverReward S who) =
      (∑ S, mass S * table.terminal S who) -
        (∑ S, mass S) * table.never who := by
    rw [Finset.sum_mul, ← Finset.sum_sub_distrib]
    refine Finset.sum_congr rfl fun S _ => ?_
    rw [QuittingPayoffTable.zeroNeverReward, mul_sub]
  unfold QuittingPayoffTable.terminalPayoff quittingTerminalPayoff
    quittingTerminalAbsorptionMass
  simp only [hmass]
  rw [hsplit]
  ring

/-- Scaling every outcome of one player scales that player's terminal payoff
on every behavior profile by the same factor. -/
theorem QuittingPayoffTable.terminalPayoff_scale
    (table : QuittingPayoffTable ι) (factor : Payoff ι)
    (profile : (quittingGame table.terminal).BehaviorProfile)
    (who : ι) :
    (table.scale factor).terminalPayoff
        (quittingBehaviorProfileCongrReward table.terminal
          (table.scale factor).terminal profile) who =
      factor who * table.terminalPayoff profile who := by
  classical
  let scaledProfile := quittingBehaviorProfileCongrReward table.terminal
    (table.scale factor).terminal profile
  have hmass : ∀ S,
      quittingAbsorbedMassLimit (table.scale factor).terminal scaledProfile S =
        quittingAbsorbedMassLimit table.terminal profile S :=
    fun S => by
      change quittingAbsorbedMassLimit (table.scale factor).terminal profile S =
        quittingAbsorbedMassLimit table.terminal profile S
      exact quittingAbsorbedMassLimit_congr_reward
        (table.scale factor).terminal table.terminal profile S
  unfold QuittingPayoffTable.terminalPayoff quittingTerminalAbsorptionMass
  change
    (∑ S, quittingAbsorbedMassLimit (table.scale factor).terminal
          scaledProfile S * (factor who * table.terminal S who)) +
        (1 - ∑ S, quittingAbsorbedMassLimit (table.scale factor).terminal
          scaledProfile S) * (factor who * table.never who) = _
  simp_rw [hmass]
  change
    (∑ S, quittingAbsorbedMassLimit table.terminal profile S *
          (factor who * table.terminal S who)) +
        (1 - ∑ S, quittingAbsorbedMassLimit table.terminal profile S) *
          (factor who * table.never who) = _
  have hsum :
      (∑ S, quittingAbsorbedMassLimit table.terminal profile S *
          (factor who * table.terminal S who)) =
        factor who * ∑ S,
          quittingAbsorbedMassLimit table.terminal profile S *
            table.terminal S who := by
    rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro S _
    ring
  rw [hsum]
  ring

/-- A terminal approximate-Nash profile remains approximate Nash after
positive playerwise scaling, with the error scaled player by player. -/
theorem QuittingPayoffTable.isεAsymptoticNash_scale
    (table : QuittingPayoffTable ι) (factor : Payoff ι)
    (hfactor : ∀ who, 0 ≤ factor who) {η ε : ℝ}
    (profile : (quittingGame table.terminal).BehaviorProfile)
    (hnash : (quittingGame table.terminal).IsεAsymptoticNash
      table.terminalPayoff η profile)
    (herror : ∀ who, factor who * η ≤ ε) :
    (quittingGame (table.scale factor).terminal).IsεAsymptoticNash
      (table.scale factor).terminalPayoff ε
        (quittingBehaviorProfileCongrReward table.terminal
          (table.scale factor).terminal profile) := by
  intro who deviation
  let originalDeviation := quittingBehaviorStrategyCongrReward
    (table.scale factor).terminal table.terminal who deviation
  have h := hnash who originalDeviation
  rw [QuittingPayoffTable.terminalPayoff_scale table factor]
  change factor who * table.terminalPayoff profile who + ε ≥
    (table.scale factor).terminalPayoff
      (quittingBehaviorProfileCongrReward table.terminal
        (table.scale factor).terminal
        (Function.update profile who originalDeviation)) who
  rw [QuittingPayoffTable.terminalPayoff_scale table factor]
  exact (mul_le_mul_of_nonneg_left h (hfactor who)).trans (by
    linarith [herror who])

/-- Viewing a repository reward in the larger model changes no payoff: the
never payoff it adds is zero, so the table's functional is the repository
terminal payoff on the nose.  The table-level branches are therefore
conservative extensions of the zero-never ones rather than variants. -/
@[simp] theorem terminalPayoff_repositoryQuittingPayoffTable
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (profile : (quittingGame reward).BehaviorProfile) (who : ι) :
    (repositoryQuittingPayoffTable reward).terminalPayoff profile who =
      quittingTerminalPayoff reward profile who := by
  rw [QuittingPayoffTable.terminalPayoff_eq_add_never]
  have hnever : (repositoryQuittingPayoffTable reward).never who = 0 := rfl
  have hzero : (repositoryQuittingPayoffTable reward).zeroNeverReward =
      reward := by
    funext S player
    simp [QuittingPayoffTable.zeroNeverReward, repositoryQuittingPayoffTable]
  rw [hnever, hzero, add_zero]

/-- Approximate Nash inequalities transfer at the same error, because the
translation adds the same playerwise constant to both sides. -/
theorem QuittingPayoffTable.isεAsymptoticNash_iff
    (table : QuittingPayoffTable ι) (ε : ℝ)
    (profile : (quittingGame table.terminal).BehaviorProfile) :
    (quittingGame table.terminal).IsεAsymptoticNash table.terminalPayoff ε
        profile ↔
      (quittingGame table.terminal).IsεAsymptoticNash
        (quittingTerminalPayoff table.zeroNeverReward) ε profile := by
  constructor
  · intro hnash who deviation
    have h := hnash who deviation
    rw [table.terminalPayoff_eq_add_never, table.terminalPayoff_eq_add_never]
      at h
    linarith
  · intro hnash who deviation
    have h := hnash who deviation
    rw [table.terminalPayoff_eq_add_never, table.terminalPayoff_eq_add_never]
    linarith

/-! ## Table-level best-reply and min-max values -/

/-- Player `who`'s best-reply value against a fixed plan, measured by the
table. -/
def QuittingPayoffTable.bestReplyValue (table : QuittingPayoffTable ι)
    (profile : (quittingGame table.terminal).BehaviorProfile) (who : ι) : ℝ :=
  ⨆ deviation : (quittingGame table.terminal).BehaviorStrategy who,
    table.terminalPayoff (Function.update profile who deviation) who

/-- Player `who`'s min-max at the active state, measured by the table. -/
def QuittingPayoffTable.punishmentValue (table : QuittingPayoffTable ι)
    (who : ι) : ℝ :=
  ⨅ profile : (quittingGame table.terminal).BehaviorProfile,
    table.bestReplyValue profile who

theorem QuittingPayoffTable.bddAbove_range_terminalPayoff_update
    (table : QuittingPayoffTable ι)
    (profile : (quittingGame table.terminal).BehaviorProfile) (who : ι) :
    BddAbove (Set.range fun deviation :
      (quittingGame table.terminal).BehaviorStrategy who =>
        table.terminalPayoff (Function.update profile who deviation) who) := by
  obtain ⟨B, hB⟩ :=
    bddAbove_range_quittingTerminalPayoff_update table.zeroNeverReward profile
      who
  refine ⟨B + table.never who, ?_⟩
  rintro _ ⟨deviation, rfl⟩
  have hzero : quittingTerminalPayoff table.zeroNeverReward
      (Function.update profile who deviation) who ≤ B := hB ⟨deviation, rfl⟩
  have hshift : table.terminalPayoff (Function.update profile who deviation)
      who = quittingTerminalPayoff table.zeroNeverReward
        (Function.update profile who deviation) who + table.never who :=
    table.terminalPayoff_eq_add_never _ who
  show table.terminalPayoff (Function.update profile who deviation) who ≤
    B + table.never who
  linarith

/-- Best-reply values shift by the player's never payoff. -/
theorem QuittingPayoffTable.bestReplyValue_eq_add_never
    (table : QuittingPayoffTable ι)
    (profile : (quittingGame table.terminal).BehaviorProfile) (who : ι) :
    table.bestReplyValue profile who =
      quittingBestReplyValue table.zeroNeverReward profile who +
        table.never who := by
  haveI : Nonempty ((quittingGame table.terminal).BehaviorStrategy who) :=
    ⟨fun _ _ => PMF.pure false⟩
  haveI : Nonempty ((quittingGame table.zeroNeverReward).BehaviorStrategy who) :=
    ⟨fun _ _ => PMF.pure false⟩
  have hbddZero :=
    bddAbove_range_quittingTerminalPayoff_update table.zeroNeverReward profile
      who
  have hbddTable := table.bddAbove_range_terminalPayoff_update profile who
  have hshift : ∀ deviation :
      (quittingGame table.terminal).BehaviorStrategy who,
        table.terminalPayoff (Function.update profile who deviation) who =
          quittingTerminalPayoff table.zeroNeverReward
            (Function.update profile who deviation) who + table.never who :=
    fun deviation => table.terminalPayoff_eq_add_never _ who
  refine le_antisymm ?_ ?_
  · refine ciSup_le fun deviation => ?_
    have hle : quittingTerminalPayoff table.zeroNeverReward
        (Function.update profile who deviation) who ≤
          quittingBestReplyValue table.zeroNeverReward profile who :=
      le_ciSup hbddZero deviation
    have := hshift deviation
    linarith
  · have hsup : quittingBestReplyValue table.zeroNeverReward profile who ≤
        table.bestReplyValue profile who - table.never who := by
      refine ciSup_le fun deviation => ?_
      have hle : table.terminalPayoff (Function.update profile who deviation)
          who ≤ table.bestReplyValue profile who := le_ciSup hbddTable deviation
      have := hshift deviation
      linarith
    linarith

theorem QuittingPayoffTable.bddBelow_range_bestReplyValue
    (table : QuittingPayoffTable ι) (who : ι) :
    BddBelow (Set.range fun profile :
      (quittingGame table.terminal).BehaviorProfile =>
        table.bestReplyValue profile who) := by
  obtain ⟨B, hB⟩ :=
    bddBelow_range_quittingBestReplyValue table.zeroNeverReward who
  refine ⟨B + table.never who, ?_⟩
  rintro _ ⟨profile, rfl⟩
  have hzero : B ≤ quittingBestReplyValue table.zeroNeverReward profile who :=
    hB ⟨profile, rfl⟩
  have hshift := table.bestReplyValue_eq_add_never profile who
  show B + table.never who ≤ table.bestReplyValue profile who
  linarith

/-- Min-max values shift by the player's never payoff. -/
theorem QuittingPayoffTable.punishmentValue_eq_add_never
    (table : QuittingPayoffTable ι) (who : ι) :
    table.punishmentValue who =
      quittingPunishmentValue table.zeroNeverReward who + table.never who := by
  haveI : Nonempty ((quittingGame table.terminal).BehaviorProfile) :=
    ⟨fun _ _ _ => PMF.pure false⟩
  haveI : Nonempty ((quittingGame table.zeroNeverReward).BehaviorProfile) :=
    ⟨fun _ _ _ => PMF.pure false⟩
  have hbddZero :=
    bddBelow_range_quittingBestReplyValue table.zeroNeverReward who
  have hbddTable := table.bddBelow_range_bestReplyValue who
  refine le_antisymm ?_ ?_
  · have hle : table.punishmentValue who - table.never who ≤
        quittingPunishmentValue table.zeroNeverReward who := by
      refine le_ciInf fun profile => ?_
      have hinf : table.punishmentValue who ≤
          table.bestReplyValue profile who := ciInf_le hbddTable profile
      have hshift := table.bestReplyValue_eq_add_never profile who
      linarith
    linarith
  · refine le_ciInf fun profile => ?_
    have hinf : quittingPunishmentValue table.zeroNeverReward who ≤
        quittingBestReplyValue table.zeroNeverReward profile who :=
      ciInf_le hbddZero profile
    have hshift := table.bestReplyValue_eq_add_never profile who
    linarith

/-! ## The three branches over a payoff table -/

/-- **Branch S.1 over a payoff table.** -/
def QuittingPayoffTable.StationaryεEquilibriumExistence
    (table : QuittingPayoffTable ι) : Prop :=
  ∀ ε : ℝ, 0 < ε → ∃ root : ι → PMF Bool,
    (quittingGame table.terminal).IsεAsymptoticNash table.terminalPayoff ε
      (quittingStationaryProfile table.terminal root)

/-- **Branch S.2 over a payoff table**, in the paper's shape: the punishment
continuation is an arbitrary behavior profile.  By
`GameTheory.quittingInstantPunishmentεEquilibriumExistence_iff_profilePunishment` that
shape and the constant-row shape have the same existence statement. -/
def QuittingPayoffTable.InstantPunishmentεEquilibriumExistence
    (table : QuittingPayoffTable ι) : Prop :=
  ∀ ε : ℝ, 0 < ε → ∃ (quitter : ι) (root : ι → PMF Bool)
      (punish : (quittingGame table.terminal).BehaviorProfile),
    root quitter = PMF.pure true ∧
      table.bestReplyValue punish quitter ≤
        table.punishmentValue quitter + ε ∧
      (quittingGame table.terminal).IsεAsymptoticNash table.terminalPayoff ε
        (quittingRootThenContinuationProfile table.terminal root punish)

/-- The table's own continuation vector at a stage of a root sequence. -/
def QuittingPayoffTable.rootSequenceTailVector
    (table : QuittingPayoffTable ι) (roots : ℕ → ι → PMF Bool) (start : ℕ) :
    Payoff ι :=
  fun who => table.terminalPayoff
    (quittingRootSequenceProfile table.terminal roots start) who

/-- **Branch S.3 over a payoff table.** -/
def QuittingPayoffTable.SequentiallyεPerfectAbsorbingExistence
    (table : QuittingPayoffTable ι) : Prop :=
  ∀ ε : ℝ, 0 < ε → ∃ roots : ℕ → ι → PMF Bool,
    IsCompletelyAbsorbing roots ∧
      ∀ time : ℕ, QuittingRowεPerfect table.terminal
        (table.rootSequenceTailVector roots (time + 1)) (roots time) ε

/-! ## Reduction to the zero-never branches -/

/-- **S.1 reduces to the zero-never branch.**  A stationary profile's payoff
moves by the same playerwise constant for the profile and for every deviation
from it, so the branch survives normalization of the never payoff at the same
tolerance and with the same witnessing row. -/
theorem QuittingPayoffTable.stationaryεEquilibriumExistence_iff
    (table : QuittingPayoffTable ι) :
    table.StationaryεEquilibriumExistence ↔
      QuittingStationaryεEquilibriumExistence table.zeroNeverReward := by
  constructor
  · intro hbranch ε hε
    obtain ⟨root, hroot⟩ := hbranch ε hε
    exact ⟨root, (table.isεAsymptoticNash_iff ε
      (quittingStationaryProfile table.terminal root)).1 hroot⟩
  · intro hbranch ε hε
    obtain ⟨root, hroot⟩ := hbranch ε hε
    exact ⟨root, (table.isεAsymptoticNash_iff ε
      (quittingStationaryProfile table.terminal root)).2 hroot⟩

/-- **S.2 reduces to the zero-never branch**, in the constant-row shape that
`GameTheory.QuittingInstantPunishmentεEquilibriumExistence` uses.  Two
independent steps compose here: normalization moves the best-reply value and
the min-max by the same never payoff, so their gap is untouched, and
`GameTheory.quittingInstantPunishmentεEquilibriumExistence_iff_profilePunishment` then
trades the arbitrary punishment continuation for a constant row. -/
theorem QuittingPayoffTable.instantPunishmentεEquilibriumExistence_iff
    (table : QuittingPayoffTable ι) :
    table.InstantPunishmentεEquilibriumExistence ↔
      QuittingInstantPunishmentεEquilibriumExistence table.zeroNeverReward := by
  rw [quittingInstantPunishmentεEquilibriumExistence_iff_profilePunishment]
  constructor
  · intro hbranch ε hε
    obtain ⟨quitter, root, punish, hquit, hcap, hnash⟩ := hbranch ε hε
    refine ⟨quitter, root, punish, hquit, ?_, ?_⟩
    · rw [table.bestReplyValue_eq_add_never,
        table.punishmentValue_eq_add_never] at hcap
      linarith
    · rw [← quittingRootThenContinuationProfile_congr_reward table.terminal
        table.zeroNeverReward root punish]
      exact (table.isεAsymptoticNash_iff ε
        (quittingRootThenContinuationProfile table.terminal root punish)).1
        hnash
  · intro hbranch ε hε
    obtain ⟨quitter, root, punish, hquit, hcap, hnash⟩ := hbranch ε hε
    rw [← quittingRootThenContinuationProfile_congr_reward table.terminal
      table.zeroNeverReward root punish] at hnash
    refine ⟨quitter, root, punish, hquit, ?_,
      (table.isεAsymptoticNash_iff ε
        (quittingRootThenContinuationProfile table.terminal root punish)).2
        hnash⟩
    rw [table.bestReplyValue_eq_add_never, table.punishmentValue_eq_add_never]
    linarith

/-- The table's continuation vector is the translated one, shifted by the
never payoff. -/
theorem QuittingPayoffTable.rootSequenceTailVector_eq_add_never
    (table : QuittingPayoffTable ι) (roots : ℕ → ι → PMF Bool) (start : ℕ)
    (who : ι) :
    table.rootSequenceTailVector roots start who =
      quittingRootSequenceTailVector table.zeroNeverReward roots start who +
        table.never who :=
  table.terminalPayoff_eq_add_never _ who

/-- Playerwise table scaling scales the continuation vector of every fixed
root sequence coordinatewise. -/
theorem QuittingPayoffTable.rootSequenceTailVector_scale
    (table : QuittingPayoffTable ι) (factor : Payoff ι)
    (roots : ℕ → ι → PMF Bool) (start : ℕ) (who : ι) :
    (table.scale factor).rootSequenceTailVector roots start who =
      factor who * table.rootSequenceTailVector roots start who := by
  unfold QuittingPayoffTable.rootSequenceTailVector
  rw [← quittingRootSequenceProfile_congr_reward table.terminal
    (table.scale factor).terminal roots start]
  exact table.terminalPayoff_scale factor
    (quittingRootSequenceProfile table.terminal roots start) who

/-- One-stage `ε`-perfectness is invariant under translating the terminal
rewards and the continuation vector by the same playerwise constant. -/
theorem quittingRowεPerfect_translate_iff
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι) (shift tail : Payoff ι)
    (root : ι → PMF Bool) (ε : ℝ) :
    QuittingRowεPerfect (fun S who => reward S who + shift who)
        (fun who => tail who + shift who) root ε ↔
      QuittingRowεPerfect reward tail root ε := by
  have hshift : ∀ (continuation : Payoff ι) (row : ι → PMF Bool) (who : ι),
      quittingRootExpectedPayoff (fun S player => reward S player + shift player)
          (fun player => continuation player + shift player) row who =
        quittingRootExpectedPayoff reward continuation row who + shift who := by
    intro continuation row who
    have hsplit : (fun action =>
        quittingRootPayoff (fun S player => reward S player + shift player)
          (fun player => continuation player + shift player) action who) =
        fun action =>
          quittingRootPayoff reward continuation action who + shift who := by
      funext action
      unfold quittingRootPayoff
      by_cases hquit : (quittingQuitters action).Nonempty <;> simp [hquit]
    unfold quittingRootExpectedPayoff
    rw [hsplit, Math.Probability.expect_add, Math.Probability.expect_const]
  constructor <;> intro hperfect who <;>
      obtain ⟨hquit, hcontinue, hsupportQuit, hsupportContinue⟩ := hperfect who
    <;> refine ⟨?_, ?_, ?_, ?_⟩
  · unfold quittingRootQuitPayoff quittingRootSuccessorPayoff at *
    rw [hshift, hshift] at hquit
    linarith
  · unfold quittingRootContinuePayoff quittingRootSuccessorPayoff at *
    rw [hshift, hshift] at hcontinue
    linarith
  · intro hmem
    unfold quittingRootQuitPayoff quittingRootSuccessorPayoff at *
    have h := hsupportQuit hmem
    rw [hshift, hshift] at h
    linarith
  · intro hmem
    unfold quittingRootContinuePayoff quittingRootSuccessorPayoff at *
    have h := hsupportContinue hmem
    rw [hshift, hshift] at h
    linarith
  · unfold quittingRootQuitPayoff quittingRootSuccessorPayoff at *
    rw [hshift, hshift]
    linarith
  · unfold quittingRootContinuePayoff quittingRootSuccessorPayoff at *
    rw [hshift, hshift]
    linarith
  · intro hmem
    unfold quittingRootQuitPayoff quittingRootSuccessorPayoff at *
    rw [hshift, hshift]
    linarith [hsupportQuit hmem]
  · intro hmem
    unfold quittingRootContinuePayoff quittingRootSuccessorPayoff at *
    rw [hshift, hshift]
    linarith [hsupportContinue hmem]

/-- Positive playerwise rescaling preserves one-stage perfection after
rescaling each player's error allowance. -/
theorem quittingRowεPerfect_scale
    (reward : {S : Finset ι // S.Nonempty} → Payoff ι)
    (factor tail : Payoff ι) (root : ι → PMF Bool) {η ε : ℝ}
    (hfactor : ∀ who, 0 ≤ factor who)
    (hperfect : QuittingRowεPerfect reward tail root η)
    (herror : ∀ who, factor who * η ≤ ε) :
    QuittingRowεPerfect
      (fun S who => factor who * reward S who)
      (fun who => factor who * tail who) root ε := by
  have hscale : ∀ (continuation : Payoff ι) (row : ι → PMF Bool)
      (who : ι),
      quittingRootExpectedPayoff
          (fun S player => factor player * reward S player)
          (fun player => factor player * continuation player) row who =
        factor who * quittingRootExpectedPayoff reward continuation row who := by
    intro continuation row who
    have hpointwise : (fun action =>
        quittingRootPayoff (fun S player => factor player * reward S player)
          (fun player => factor player * continuation player) action who) =
        fun action => factor who *
          quittingRootPayoff reward continuation action who := by
      funext action
      unfold quittingRootPayoff
      by_cases hquit : (quittingQuitters action).Nonempty <;> simp [hquit]
    unfold quittingRootExpectedPayoff
    rw [hpointwise, Math.Probability.expect_const_mul]
  intro who
  obtain ⟨hquit, hcontinue, hsupportQuit, hsupportContinue⟩ := hperfect who
  refine ⟨?_, ?_, ?_, ?_⟩
  · unfold quittingRootQuitPayoff quittingRootSuccessorPayoff at *
    rw [hscale, hscale]
    exact (mul_le_mul_of_nonneg_left hquit (hfactor who)).trans (by
      linarith [herror who])
  · unfold quittingRootContinuePayoff quittingRootSuccessorPayoff at *
    rw [hscale, hscale]
    exact (mul_le_mul_of_nonneg_left hcontinue (hfactor who)).trans (by
      linarith [herror who])
  · intro hused
    unfold quittingRootQuitPayoff quittingRootSuccessorPayoff at *
    rw [hscale, hscale]
    have h := mul_le_mul_of_nonneg_left (hsupportQuit hused) (hfactor who)
    linarith [herror who]
  · intro hused
    unfold quittingRootContinuePayoff quittingRootSuccessorPayoff at *
    rw [hscale, hscale]
    have h := mul_le_mul_of_nonneg_left (hsupportContinue hused) (hfactor who)
    linarith [herror who]

/-- Branch S.3 is preserved by nonnegative playerwise scaling.  Finiteness
provides one common row tolerance small enough for every coordinate. -/
theorem QuittingPayoffTable.sequentiallyεPerfectAbsorbingExistence_scale
    (table : QuittingPayoffTable ι) (factor : Payoff ι)
    (hfactor : ∀ who, 0 ≤ factor who)
    (hbranch : table.SequentiallyεPerfectAbsorbingExistence) :
    (table.scale factor).SequentiallyεPerfectAbsorbingExistence := by
  intro ε hε
  let bound : ℝ := 1 + ∑ who, factor who
  have hbound : 0 < bound := by
    dsimp [bound]
    have hsum : 0 ≤ ∑ who, factor who :=
      Finset.sum_nonneg fun who _ => hfactor who
    linarith
  let η := ε / bound
  have hη : 0 < η := div_pos hε hbound
  obtain ⟨roots, habsorbing, hperfect⟩ := hbranch η hη
  refine ⟨roots, habsorbing, fun time => ?_⟩
  have hfactorBound (who : ι) : factor who ≤ bound := by
    have hle : factor who ≤ ∑ player, factor player :=
      Finset.single_le_sum (fun player _ => hfactor player)
        (Finset.mem_univ who)
    dsimp [bound]
    linarith
  have herror (who : ι) : factor who * η ≤ ε := by
    dsimp [η]
    rw [show factor who * (ε / bound) =
      (factor who * ε) / bound by ring, div_le_iff₀ hbound]
    simpa only [mul_comm] using
      mul_le_mul_of_nonneg_right (hfactorBound who) hε.le
  have hscaled := quittingRowεPerfect_scale table.terminal factor
    (table.rootSequenceTailVector roots (time + 1)) (roots time)
    hfactor (hperfect time) herror
  change QuittingRowεPerfect
    (fun S who => factor who * table.terminal S who)
    ((table.scale factor).rootSequenceTailVector roots (time + 1))
    (roots time) ε
  rw [show (table.scale factor).rootSequenceTailVector roots (time + 1) =
    fun who => factor who *
      table.rootSequenceTailVector roots (time + 1) who by
      funext who
      exact table.rootSequenceTailVector_scale factor roots (time + 1) who]
  exact hscaled

/-- **S.3 reduces to the zero-never branch.**  Absorption is a property of the
rows alone, and normalization shifts the terminal rewards and the plan's own
continuation vector by the same playerwise constant, which is exactly the
invariance `quittingRowεPerfect_translate_iff` needs.  The witnessing row
sequence is unchanged. -/
theorem QuittingPayoffTable.sequentiallyεPerfectAbsorbingExistence_iff
    (table : QuittingPayoffTable ι) :
    table.SequentiallyεPerfectAbsorbingExistence ↔
      QuittingSequentiallyεPerfectAbsorbingExistence table.zeroNeverReward := by
  have hrow : ∀ (roots : ℕ → ι → PMF Bool) (time : ℕ) (ε : ℝ),
      QuittingRowεPerfect table.terminal
          (table.rootSequenceTailVector roots (time + 1)) (roots time) ε ↔
        QuittingRowεPerfect table.zeroNeverReward
          (quittingRootSequenceTailVector table.zeroNeverReward roots
            (time + 1)) (roots time) ε := by
    intro roots time ε
    have hterminal : table.terminal =
        fun S who => table.zeroNeverReward S who + table.never who := by
      funext S who
      simp [QuittingPayoffTable.zeroNeverReward]
    have htail : table.rootSequenceTailVector roots (time + 1) =
        fun who => quittingRootSequenceTailVector table.zeroNeverReward roots
          (time + 1) who + table.never who := by
      funext who
      exact table.rootSequenceTailVector_eq_add_never roots (time + 1) who
    rw [hterminal, htail]
    exact quittingRowεPerfect_translate_iff table.zeroNeverReward
      table.never _ (roots time) ε
  constructor <;> intro hbranch ε hε <;>
      obtain ⟨roots, habsorb, hperfect⟩ := hbranch ε hε
  · exact ⟨roots, habsorb, fun time => (hrow roots time ε).1 (hperfect time)⟩
  · exact ⟨roots, habsorb, fun time => (hrow roots time ε).2 (hperfect time)⟩

end QuittingLCPClassification
end GameTheory
