#!/usr/bin/env python3
"""Generate the Lean module that audits every project-owned declaration."""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "AxiomAudit.lean"
AUDITED_DIRECTORIES = {
    ROOT / "UniformEquilibrium",
    ROOT / "MathUE",
}
LEAN_LIBRARY_RE = re.compile(r"^lean_lib\s+([A-Za-z0-9_'.]+)\s+where\s*$", re.MULTILINE)


def module_roots() -> set[str]:
    lakefile = (ROOT / "lakefile.lean").read_text(encoding="utf-8")
    return set(LEAN_LIBRARY_RE.findall(lakefile)) - {"AxiomAudit"}


def source_modules() -> list[str]:
    roots = module_roots()
    modules: list[str] = []
    for root in AUDITED_DIRECTORIES:
        for directory, names, filenames in os.walk(root):
            base = pathlib.Path(directory)
            for filename in filenames:
                if not filename.endswith(".lean"):
                    continue
                path = (base / filename).relative_to(ROOT)
                if path == pathlib.Path("AxiomAudit.lean"):
                    continue
                if path.parts[0].removesuffix(".lean") not in roots:
                    continue
                modules.append(".".join(path.with_suffix("").parts))
    return sorted(modules)


def expected() -> str:
    imports = "\n".join(f"import {module}" for module in source_modules())
    roots = "\n".join(f"  `{root}," for root in sorted(module_roots()))
    return f'''/-
This file is generated by `python scripts/generate_axiom_audit.py`.
Do not edit it directly.
Only UniformEquilibrium and MathUE modules are audited;
Other modules such as Research and Literature are not to be quoted as formalized.
-/

{imports}
import Lean.Util.CollectAxioms

open Lean Elab Command

private def projectModuleRoots : Array Name := #[
{roots}
]

private def allowedLibraryAxioms : NameSet :=
  #[``propext, ``Quot.sound, ``Classical.choice].foldl
    (init := {{}}) fun names name => names.insert name

private def isProjectModule (moduleName : Name) : Bool :=
  projectModuleRoots.any fun root => root.isPrefixOf moduleName

run_cmd do
  let env ← getEnv
  let moduleNames := env.allImportedModuleNames
  let declarations := env.constants.map₁.fold (init := #[]) fun names name _ =>
    match env.getModuleIdxFor? name with
    | some moduleIndex =>
        let moduleName := moduleNames[moduleIndex.toNat]!
        if isProjectModule moduleName then names.push name else names
    | none => names
  let declarations := declarations.qsort Name.lt
  if declarations.isEmpty then
    throwError "Project axiom audit found no project declarations"
  let mut failures : Array String := #[]
  for declaration in declarations do
    let axioms ← Lean.collectAxioms declaration
    let forbidden := axioms.filter fun axiomName =>
      !allowedLibraryAxioms.contains axiomName
    unless forbidden.isEmpty do
      let names := String.intercalate ", " (forbidden.toList.map toString)
      failures := failures.push s!"{{declaration}}: {{names}}"
  unless failures.isEmpty do
    throwError m!"Project axiom audit failed:\\n{{String.intercalate "\\n" failures.toList}}"
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = expected()
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
    if current == rendered:
        return 0
    if args.check:
        print(
            "AxiomAudit.lean is stale; run: python scripts/generate_axiom_audit.py",
            file=sys.stderr,
        )
        return 1
    OUTPUT.write_text(rendered, encoding="utf-8")
    print("generated AxiomAudit.lean")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
