#!/usr/bin/env python3
"""Synchronize paper modules with the citation-of-record bibliography."""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
import textwrap
import unicodedata


ROOT = pathlib.Path(__file__).resolve().parents[1]
BIBLIOGRAPHY = ROOT / "docs" / "references" / "00_BIBLIOGRAPHY.md"
PAPERS = ROOT / "Literature" / "Papers"
COVERAGE = ROOT / "Literature" / "Coverage.lean"
ALL = ROOT / "Literature" / "All.lean"

SECTION_ROLES = {
    "Foundations": "foundations",
    "Zero-sum: the uniform value": "zeroSumUniformValue",
    "Zero-sum: partial observation and the boundary": "zeroSumBoundary",
    "Non-zero-sum: existence": "nonzeroSumExistence",
    "Non-zero-sum: post-2020": "recentNonzeroSum",
    "Algorithmic finite-memory equilibrium": "finiteMemoryAlgorithms",
    "Counterexamples and separations": "counterexamples",
    "Proof-assistant formalization": "formalization",
    "Surveys and textbooks": "surveys",
}

BOLD_ENTRY_RE = re.compile(r"^\*\*(.+?)\*\*\s+—")
SECTION_RE = re.compile(r"^##\s+(.+?)\s*$")
FOUNDATION_ROW_RE = re.compile(r"^\|\s*([^|]+?)\s*\|")
FIELD_RE = {
    "paperId": re.compile(r'^\s*paperId\s*:=\s*"([^"]+)"\s*$', re.MULTILINE),
    "bibliographyLabel": re.compile(
        r'^\s*bibliographyLabel\s*:=\s*"([^"]+)"\s*$', re.MULTILINE
    ),
}


class Paper:
    def __init__(self, label: str, role: str) -> None:
        self.label = label
        self.role = role
        words = ascii_words(label.replace("&", " and "))
        self.paper_id = "_".join(word.lower() for word in words)
        self.module = "".join(word[:1].upper() + word[1:] for word in words)


def ascii_words(text: str) -> list[str]:
    normalized = unicodedata.normalize("NFKD", text)
    ascii_text = normalized.encode("ascii", "ignore").decode("ascii")
    return re.findall(r"[A-Za-z0-9]+", ascii_text)


def bibliography_papers() -> list[Paper]:
    papers: list[Paper] = []
    section: str | None = None
    in_foundations = False
    for line in BIBLIOGRAPHY.read_text(encoding="utf-8").splitlines():
        section_match = SECTION_RE.match(line)
        if section_match:
            section = section_match.group(1)
            in_foundations = section == "Foundations"
            continue
        if section not in SECTION_ROLES:
            continue
        if in_foundations:
            row_match = FOUNDATION_ROW_RE.match(line)
            if row_match:
                label = row_match.group(1).strip()
                if label not in {"Work", "---"} and not set(label) <= {"-", ":"}:
                    papers.append(Paper(label, SECTION_ROLES[section]))
            continue
        entry_match = BOLD_ENTRY_RE.match(line)
        if entry_match:
            papers.append(Paper(entry_match.group(1).strip(), SECTION_ROLES[section]))
    labels = [paper.label for paper in papers]
    ids = [paper.paper_id for paper in papers]
    modules = [paper.module for paper in papers]
    for values, name in ((labels, "labels"), (ids, "paper ids"), (modules, "modules")):
        duplicates = sorted({value for value in values if values.count(value) > 1})
        if duplicates:
            raise ValueError(f"duplicate literature {name}: {', '.join(duplicates)}")
    return papers


def lean_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def wrap_comment(text: str, width: int = 88) -> str:
    return "\n".join(textwrap.wrap(text, width=width))


def paper_template(paper: Paper) -> str:
    namespace = f"Literature.Papers.{paper.module}"
    label = lean_string(paper.label)
    return f'''import Literature.Catalog

/-!
# Literature audit

{wrap_comment(f"Bibliography label: {paper.label}")}

This record contains bibliographic coverage and no source-claim
correspondence.
-/

namespace {namespace}

/-- Paper-level coverage record. -/
def record : Literature.PaperRecord where
  paperId := {lean_string(paper.paper_id)}
  bibliographyLabel := {label}
  bibliographyLocator :=
    "docs/references/00_BIBLIOGRAPHY.md :: " ++
      {label}
  role := .{paper.role}
  sourceEvidence := .bibliographic
  auditStatus := .catalogued
  claims := []

end {namespace}
'''


def coverage_text(papers: list[Paper]) -> str:
    imports = "\n".join(
        f"import Literature.Papers.{paper.module}" for paper in papers
    )
    records = "\n".join(
        f"    Literature.Papers.{paper.module}.record," for paper in papers
    )
    return f'''/-
This file is generated by `python scripts/generate_literature.py`.
Do not edit it directly.
-/

{imports}

namespace Literature

/-- Every work in the citation-of-record bibliography, in bibliography order. -/
def allPapers : List PaperRecord :=
  [
{records}
  ]

theorem allPapers_length : allPapers.length = {len(papers)} := by
  decide

theorem allPaperIds_nodup :
    (allPapers.map fun paper => paper.paperId).Nodup := by
  decide

theorem allBibliographyLabels_nodup :
    (allPapers.map fun paper => paper.bibliographyLabel).Nodup := by
  decide

end Literature
'''


def all_text() -> str:
    return '''/-
This file is generated by `python scripts/generate_literature.py`.
Do not edit it directly.
-/

import Literature.Coverage
'''


def validate_paper(path: pathlib.Path, paper: Paper) -> list[str]:
    errors: list[str] = []
    text = path.read_text(encoding="utf-8")
    expected = {
        "paperId": paper.paper_id,
        "bibliographyLabel": paper.label,
    }
    for field, value in expected.items():
        match = FIELD_RE[field].search(text)
        if not match:
            errors.append(f"{path.relative_to(ROOT)}: missing {field}")
        elif match.group(1) != value:
            errors.append(
                f"{path.relative_to(ROOT)}: {field} is {match.group(1)!r}, "
                f"expected {value!r}"
            )
    namespace = f"namespace Literature.Papers.{paper.module}"
    if namespace not in text:
        errors.append(f"{path.relative_to(ROOT)}: missing namespace {namespace}")
    if "def record : Literature.PaperRecord where" not in text:
        errors.append(f"{path.relative_to(ROOT)}: missing PaperRecord declaration")
    return errors


def synchronize(check: bool) -> list[str]:
    papers = bibliography_papers()
    errors: list[str] = []
    expected_paths = {PAPERS / f"{paper.module}.lean" for paper in papers}
    actual_paths = set(PAPERS.glob("*.lean")) if PAPERS.is_dir() else set()
    for stale in sorted(actual_paths - expected_paths):
        errors.append(f"unexpected paper module {stale.relative_to(ROOT)}")
    if not check:
        PAPERS.mkdir(parents=True, exist_ok=True)
    for paper in papers:
        path = PAPERS / f"{paper.module}.lean"
        if not path.is_file():
            if check:
                errors.append(f"missing paper module {path.relative_to(ROOT)}")
                continue
            path.write_text(paper_template(paper), encoding="utf-8")
        errors.extend(validate_paper(path, paper))
    generated = ((COVERAGE, coverage_text(papers)), (ALL, all_text()))
    for path, expected in generated:
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == expected:
            continue
        if check:
            errors.append(f"stale generated literature file {path.relative_to(ROOT)}")
        else:
            path.write_text(expected, encoding="utf-8")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        errors = synchronize(args.check)
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1
    if errors:
        print(*errors, sep="\n", file=sys.stderr)
        return 1
    if not args.check:
        print("synchronized Literature paper modules and aggregate catalog")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
