#!/usr/bin/env python3
"""Generate volatile documentation from the structured project-status ledger."""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
from typing import Any


ROOT = pathlib.Path(__file__).resolve().parents[1]
STATUS_SOURCE = ROOT / "docs" / "ProjectStatus.json"
FRONTIER_SOURCE = ROOT / "docs" / "QuittingProofFrontier.json"
STATUS_OUTPUT = ROOT / "docs" / "STATUS.md"
README = ROOT / "README.md"
FRONTIER = ROOT / "docs" / "FRONTIER.md"
AGENTS = ROOT / "AGENTS.md"
CLAUDE = ROOT / "CLAUDE.md"

README_BEGIN = "<!-- BEGIN GENERATED STATUS -->"
README_END = "<!-- END GENERATED STATUS -->"
FRONTIER_BEGIN = "<!-- BEGIN GENERATED OPEN LEAVES -->"
FRONTIER_END = "<!-- END GENERATED OPEN LEAVES -->"


def load_json(path: pathlib.Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def status_table(claims: list[dict[str, str]], from_docs: bool) -> str:
    prefix = "../" if from_docs else ""
    lines = [
        "| Claim | Status | Exact declaration | Scope |",
        "| --- | --- | --- | --- |",
    ]
    for claim in claims:
        source = f"{prefix}{claim['source']}"
        declaration = f"[`{claim['declaration']}`]({source})"
        lines.append(
            f"| {claim['subject']} | {claim['kind']} | {declaration} | "
            f"{claim['scope']} |"
        )
    return "\n".join(lines)


def render_readme_status(status: dict[str, Any]) -> str:
    return "\n".join(
        [
            README_BEGIN,
            "This table is generated from "
            "[`docs/ProjectStatus.json`](docs/ProjectStatus.json).",
            "",
            status_table(status["claims"], from_docs=False),
            "",
            "Declaration kind and umbrella reachability are checked by the documentation "
            "gate. Compilation truth still comes from the relevant Lean check or CI run.",
            README_END,
        ]
    )


def render_status(status: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# Project status",
            "",
            "> Generated by `python scripts/generate_docs.py` from "
            "`docs/ProjectStatus.json`; do not edit this file directly.",
            "",
            "This is a compact declaration index, not a replacement for Lean compilation. An",
            "entry records whether the source contains an open proposition or theorem",
            "declaration and whether its module is reachable from the stated umbrella. Report",
            "a result as *proved in Lean here* only after the relevant Lean check has completed.",
            "",
            "## Headline declarations",
            "",
            status_table(status["claims"], from_docs=True),
            "",
            "## Current quitting proof search",
            "",
            status["quitting_frontier"]["summary"],
            "",
            "The live formal-leaf ledger is "
            "[`QuittingProofFrontier.json`](QuittingProofFrontier.json). Its source and "
            "evidence paths are checked by `python scripts/check_docs.py`.",
            "",
            "## Evidence language",
            "",
            "- `M`: rigorous mathematical proof or counterexample.",
            "- `L`: checked Lean declaration at its exact hypotheses.",
            "- `A`: checked adapter from actual source data.",
            "- `C`: checked downstream consumer producing semantic closure or a valid",
            "  recursive output.",
            "",
            "These seals are independent. Integration records umbrella reachability, not",
            "unconditionality or strategy-class completeness.",
            "",
        ]
    )


def render_open_leaves(frontier: dict[str, Any]) -> str:
    nodes = {node["id"]: node for node in frontier["nodes"]}
    lines = [
        FRONTIER_BEGIN,
        "This dependency table is generated from "
        "[`QuittingProofFrontier.json`](QuittingProofFrontier.json).",
        "",
        "| From | Status | To | Seals | Checked declaration or open interface |",
        "| --- | --- | --- | --- | --- |",
    ]
    for edge in frontier["edges"]:
        source = edge["source"]
        declaration = edge["declaration"]
        source_link = f"[`{declaration}`](../{source})"
        seals = ", ".join(f"`{seal}`" for seal in edge.get("evidence_seals", []))
        lines.append(
            f"| `{edge['from']}` | `{edge['status']}` | `{edge['to']}` | "
            f"{seals} | {source_link} |"
        )
    open_edges = [edge for edge in frontier["edges"] if edge["status"] == "open-producer"]
    if open_edges:
        lines.extend(["", "The open producer arrows are:", ""])
        for edge in open_edges:
            lines.append(
                f"- `{edge['from']}` to `{edge['to']}`: {edge['meaning']}"
            )
    lines.extend(["", "The DAG nodes have these mathematical meanings:", ""])
    for node in frontier["nodes"]:
        lines.append(f"- `{node['id']}`: {node['meaning']}")
    lines.extend(["", FRONTIER_END])
    return "\n".join(lines)


def replace_generated(text: str, begin: str, end: str, replacement: str) -> str:
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    if not pattern.search(text):
        raise ValueError(f"missing generated markers: {begin} / {end}")
    return pattern.sub(replacement, text, count=1)


def expected_files() -> dict[pathlib.Path, str]:
    status = load_json(STATUS_SOURCE)
    frontier = load_json(FRONTIER_SOURCE)
    return {
        STATUS_OUTPUT: render_status(status),
        README: replace_generated(
            README.read_text(encoding="utf-8"),
            README_BEGIN,
            README_END,
            render_readme_status(status),
        ),
        FRONTIER: replace_generated(
            FRONTIER.read_text(encoding="utf-8"),
            FRONTIER_BEGIN,
            FRONTIER_END,
            render_open_leaves(frontier),
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[pathlib.Path] = []
    for path, expected in expected_files().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == expected:
            continue
        if args.check:
            stale.append(path)
        else:
            path.write_text(expected, encoding="utf-8")
            print(f"generated {path.relative_to(ROOT)}")
    agents_bytes = AGENTS.read_bytes()
    claude_bytes = CLAUDE.read_bytes() if CLAUDE.exists() else None
    if claude_bytes != agents_bytes:
        if args.check:
            stale.append(CLAUDE)
        else:
            CLAUDE.write_bytes(agents_bytes)
            print(f"generated {CLAUDE.relative_to(ROOT)}")
    if stale:
        print("Generated documentation is stale:", file=sys.stderr)
        for path in stale:
            print(path.relative_to(ROOT), file=sys.stderr)
        print("Run: python scripts/generate_docs.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
