/-
Copyright (c) 2025 GameTheory contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: GameTheory contributors
-/
import UniformEquilibrium.ProofView.Core.KernelGame

/-!
# Repeated Play of a Stage Game

Repetition-generic infrastructure for repeating a `KernelGame` stage game
with observable strategy profiles: history-dependent repeated strategies, the
stage-profile path they generate, and finite-horizon average payoffs.

This is a deterministic-monitoring model: histories record the stage profiles
chosen, not realized outcomes of the stage kernel (see
`KernelGame.ProfileHistory`), so a repeated profile generates a deterministic
stage-profile path and repeated payoffs aggregate stage expected utilities.

Payoff aggregations over infinite play carrying extra data — discounting,
limits — build on this module; see
`UniformEquilibrium.ProofView.Concepts.Repeated.Discounted` for the discounted
repeated game and `UniformEquilibrium.ProofView.Concepts.Repeated.Uniform` for uniform
equilibrium.

## Main definitions

* `KernelGame.ProfileHistory` — realized period profiles before a period
* `KernelGame.RepeatedStrategy` / `KernelGame.RepeatedProfile` —
  history-dependent repeated-game strategies and profiles
* `KernelGame.stationaryRepeatedProfile` / `KernelGame.periodicRepeatedProfile`
  — stationary and periodic repeated play
* `KernelGame.repeatedPlay` — the stage-profile path of a repeated profile
* `KernelGame.finiteAveragePayoff` — average payoff over the first `T` stages
* `KernelGame.HasLongRunAveragePayoff` — convergence of the `T`-stage average
  payoffs
-/

noncomputable section

open scoped BigOperators

namespace GameTheory

namespace KernelGame

variable {ι : Type}

/-- Histories of the stage profiles chosen before period `t`.

This is an observable-profile monitoring model: after each period, every
player observes the entire stage profile that was played — not a realized
outcome drawn from the stage kernel, which is never part of histories.  In
ordinary normal-form stage games these profiles are action profiles.  In
compiled `KernelGame`s they may instead be profiles of semantic strategies or
policies.  When `G` is a mixed extension, the observations are the
mixed-action profiles themselves, which is the observable-mixed-actions
assumption of the Folk theorem literature; monitoring of realized public
signals is a strictly coarser model that this structure does not capture. -/
abbrev ProfileHistory (G : KernelGame ι) (t : ℕ) : Type :=
  Fin t → Profile G

/-- A repeated-game strategy: choose the next period's `G.Strategy i` after
every finite profile history. -/
abbrev RepeatedStrategy (G : KernelGame ι) (i : ι) : Type :=
  (t : ℕ) → G.ProfileHistory t → G.Strategy i

/-- A repeated-game strategy profile. -/
abbrev RepeatedProfile (G : KernelGame ι) : Type :=
  ∀ i, G.RepeatedStrategy i

/-- Stationary repeated play of a fixed stage-game profile. -/
def stationaryRepeatedProfile (G : KernelGame ι) (σ : Profile G) :
    G.RepeatedProfile :=
  fun i _ _ => σ i

/-- Periodic repeated play of a finite cycle of stage-game profiles. -/
def periodicRepeatedProfile (G : KernelGame ι)
    {n : ℕ} [NeZero n] (cycle : Fin n → Profile G) :
    G.RepeatedProfile :=
  fun i t _ => cycle (Fin.ofNat n t) i

/-- The stage-profile path generated by a repeated-game strategy profile. -/
def repeatedPlay (G : KernelGame ι)
    (σ : G.RepeatedProfile) : (t : ℕ) → Profile G
  | t => fun i => σ i t (fun k => repeatedPlay G σ k)
termination_by t => t
decreasing_by exact k.isLt

@[simp] theorem repeatedPlay_stationaryRepeatedProfile
    (G : KernelGame ι) (σ : Profile G) (t : ℕ) :
    G.repeatedPlay (G.stationaryRepeatedProfile σ) t = σ := by
  funext i
  simp [repeatedPlay, stationaryRepeatedProfile]

@[simp] theorem repeatedPlay_periodicRepeatedProfile
    (G : KernelGame ι) {n : ℕ} [NeZero n]
    (cycle : Fin n → Profile G) (t : ℕ) :
    G.repeatedPlay (G.periodicRepeatedProfile cycle) t =
      cycle (Fin.ofNat n t) := by
  funext i
  simp [repeatedPlay, periodicRepeatedProfile]

/-- If one player deviates from a stationary repeated profile, every realized
stage profile is the stationary profile with only that player's current action
updated. -/
theorem repeatedPlay_update_stationaryRepeatedProfile
    (G : KernelGame ι) [DecidableEq ι] (σ : Profile G) (who : ι)
    (dev : G.RepeatedStrategy who) (t : ℕ) :
    G.repeatedPlay
        (Function.update (G.stationaryRepeatedProfile σ) who dev) t =
      Function.update σ who
        (dev t (fun k => G.repeatedPlay
          (Function.update (G.stationaryRepeatedProfile σ) who dev) k)) := by
  funext i
  by_cases hi : i = who
  · subst hi
    rw [repeatedPlay]
    simp [Function.update]
  · simp [repeatedPlay, stationaryRepeatedProfile, Function.update, hi]

/-- Average payoff over the first `T` stages of repeated play. -/
def finiteAveragePayoff (G : KernelGame ι) (T : ℕ)
    (σ : G.RepeatedProfile) (who : ι) : ℝ :=
  (T : ℝ)⁻¹ * ∑ t ∈ Finset.range T, G.eu (G.repeatedPlay σ t) who

/-- The `T`-stage average payoff of stationary repeated play is the stage
payoff. -/
theorem finiteAveragePayoff_stationaryRepeatedProfile
    (G : KernelGame ι) {T : ℕ} (hT : T ≠ 0) (σ : Profile G) (who : ι) :
    G.finiteAveragePayoff T (G.stationaryRepeatedProfile σ) who =
      G.eu σ who := by
  have hT' : (T : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hT
  simp [finiteAveragePayoff, Finset.sum_const, ← mul_assoc,
    inv_mul_cancel₀ hT']

/-- A stagewise payoff bound bounds the `T`-stage average payoff. -/
theorem finiteAveragePayoff_le_of_forall_stageEU_le
    (G : KernelGame ι) {σ : G.RepeatedProfile} {B : ℝ} {who : ι}
    (h : ∀ t, G.eu (G.repeatedPlay σ t) who ≤ B)
    {T : ℕ} (hT : T ≠ 0) :
    G.finiteAveragePayoff T σ who ≤ B := by
  have hT' : (T : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hT
  calc G.finiteAveragePayoff T σ who
      ≤ (T : ℝ)⁻¹ * ∑ _t ∈ Finset.range T, B := by
        unfold finiteAveragePayoff
        gcongr with t _
        exact h t
    _ = B := by
        rw [Finset.sum_const, Finset.card_range, nsmul_eq_mul, ← mul_assoc,
          inv_mul_cancel₀ hT', one_mul]

/-- A repeated profile has long-run average payoff `v` if its `T`-stage
average payoffs converge to `v` coordinatewise. -/
def HasLongRunAveragePayoff (G : KernelGame ι)
    (σ : G.RepeatedProfile) (v : Payoff ι) : Prop :=
  ∀ who, Filter.Tendsto (fun T => G.finiteAveragePayoff T σ who)
    Filter.atTop (nhds (v who))

/-- The long-run average payoff of stationary repeated play is the stage
payoff. -/
theorem hasLongRunAveragePayoff_stationaryRepeatedProfile
    (G : KernelGame ι) (σ : Profile G) :
    G.HasLongRunAveragePayoff (G.stationaryRepeatedProfile σ) (G.eu σ) := by
  intro who
  have h : (fun _ : ℕ => G.eu σ who) =ᶠ[Filter.atTop]
      fun T => G.finiteAveragePayoff T (G.stationaryRepeatedProfile σ) who := by
    filter_upwards [Filter.eventually_ge_atTop 1] with T hT
    exact (G.finiteAveragePayoff_stationaryRepeatedProfile (by omega) σ who).symm
  exact Filter.Tendsto.congr' h tendsto_const_nhds

end KernelGame

end GameTheory
